import {
  PROMPT_SOURCE_SNAPSHOT_ON,
  type PromptSourceId,
  type PromptSourceRecord,
} from "./types";

const accessedOn = PROMPT_SOURCE_SNAPSHOT_ON;
const verifiedOn = PROMPT_SOURCE_SNAPSHOT_ON;

export const PROMPT_SOURCES = [
  {
    id: "dlai-prompt-engineering-course",
    tier: "primary",
    kind: "official-course",
    title: "ChatGPT Prompt Engineering for Developers",
    publisher: "DeepLearning.AI with OpenAI",
    url: "https://www.deeplearning.ai/courses/chatgpt-prompt-eng",
    exactAnchor: "https://www.deeplearning.ai/courses/chatgpt-prompt-eng#course-outline",
    accessedOn,
    verifiedOn,
    claimIds: [
      "curriculum.guidelines-iteration-applications-chatbot",
      "curriculum.hands-on-experimentation",
      "practice.summarize-infer-transform-expand",
    ],
    licence: "proprietary",
    licenceUrl: "https://community.deeplearning.ai/t/respecting-intellectual-property-how-to-share-deeplearning-ai-course-materials-responsibly/681787",
    reuse: "link-only",
    currency: "mixed",
    caveats: [
      "Do not copy course prompts, notebooks, labs, screenshots, quizzes, transcripts, or model outputs.",
      "Model and API examples may age even while the course outline remains current.",
      "The original hands-on course uses the OpenAI API and Jupyter notebooks and assumes basic Python; this aicourse.top course is an original no-code conceptual adaptation.",
    ],
    note: "Pedagogical spine only. Write new lessons, prompts, exercises, data, figures, and outputs.",
  },
  {
    id: "dlai-ai-prompting-for-everyone",
    tier: "primary",
    kind: "official-course",
    title: "AI Prompting for Everyone",
    publisher: "DeepLearning.AI",
    url: "https://www.deeplearning.ai/courses/ai-prompting-for-everyone",
    exactAnchor: "https://www.deeplearning.ai/courses/ai-prompting-for-everyone#course-outline",
    accessedOn,
    verifiedOn,
    claimIds: [
      "modern.context-and-tools",
      "grounding.search-and-deep-research",
      "modern.model-comparison",
    ],
    licence: "proprietary",
    licenceUrl: "https://community.deeplearning.ai/t/respecting-intellectual-property-how-to-share-deeplearning-ai-course-materials-responsibly/681787",
    reuse: "link-only",
    currency: "current",
    caveats: [
      "Do not copy videos, labs, assignments, screenshots, prompts, or model outputs.",
      "Advice about models, search modes, and tools is time-sensitive and should be rechecked before publication.",
    ],
    note: "Current Andrew Ng source for context, source-aware search, model comparison, critique, and modern multimodal prompting. Use original course materials throughout.",
  },
  {
    id: "dlai-batch-course-announcement",
    tier: "primary",
    kind: "official-announcement",
    title: "New course: ChatGPT Prompt Engineering for Developers",
    publisher: "DeepLearning.AI",
    url: "https://www.deeplearning.ai/the-batch/new-course-chatgpt-prompt-engineering-for-developers",
    exactAnchor: "https://www.deeplearning.ai/the-batch/new-course-chatgpt-prompt-engineering-for-developers",
    accessedOn,
    verifiedOn,
    claimIds: [
      "curriculum.consumer-versus-developer-prompting",
      "curriculum.hands-on-experimentation",
      "practice.summarize-infer-transform-expand",
    ],
    licence: "proprietary",
    licenceUrl: null,
    reuse: "original-only",
    currency: "historical",
    caveats: ["This is a 2023 launch announcement, not current model guidance."],
    note: "Use for Andrew Ng's framing and provenance, then explain the ideas in original language.",
  },
  {
    id: "dlai-course-materials-policy",
    tier: "primary",
    kind: "official-policy",
    title: "Respecting Intellectual Property: How to Share DeepLearning.AI Course Materials Responsibly",
    publisher: "DeepLearning.AI Community Team",
    url: "https://community.deeplearning.ai/t/respecting-intellectual-property-how-to-share-deeplearning-ai-course-materials-responsibly/681787",
    exactAnchor: "https://community.deeplearning.ai/t/respecting-intellectual-property-how-to-share-deeplearning-ai-course-materials-responsibly/681787",
    accessedOn,
    verifiedOn,
    claimIds: [
      "copyright.direct-course-reuse-restricted",
      "publisher-guidance.cite-inspired-project-code",
    ],
    licence: "proprietary",
    licenceUrl: null,
    reuse: "link-only",
    currency: "current",
    caveats: [
      "Treat this as publisher guidance, not independent legal advice.",
      "Obtain permission before any direct reuse that falls outside the stated guidance.",
    ],
    note: "Fail closed on DeepLearning.AI course assets and direct course text.",
  },
  {
    id: "openai-chatgpt-prompt-guide",
    tier: "primary",
    kind: "official-github",
    title: "ChatGPT Enterprise: Practical prompt engineering for everyday work",
    publisher: "OpenAI",
    url: "https://github.com/openai/openai-cookbook/blob/main/examples/chatgpt/chatgpt_prompt_guide/chatgpt_prompt_guide.md",
    exactAnchor: "https://github.com/openai/openai-cookbook/blob/main/examples/chatgpt/chatgpt_prompt_guide/chatgpt_prompt_guide.md#3-scope-the-problem",
    supportingAnchors: [
      "https://github.com/openai/openai-cookbook/blob/main/examples/chatgpt/chatgpt_prompt_guide/chatgpt_prompt_guide.md#4-write-the-prompt-clearly",
      "https://github.com/openai/openai-cookbook/blob/main/examples/chatgpt/chatgpt_prompt_guide/chatgpt_prompt_guide.md#6-improve-accuracy",
    ],
    accessedOn,
    verifiedOn,
    claimIds: [
      "prompt.scope-before-drafting",
      "prompt.context-instructions-constraints-output",
      "prompt.acceptance-criteria",
      "prompt.meta-prompting",
      "grounding.evidence-and-uncertainty-rules",
    ],
    licence: "MIT",
    licenceUrl: "https://github.com/openai/openai-cookbook/blob/main/LICENSE",
    reuse: "original-only",
    currency: "current",
    caveats: [
      "The guide is written for ChatGPT Enterprise workflows.",
      "MIT notices are required if substantial source text or code is copied, but this course does not copy them.",
    ],
    note: "Primary structure source for scope, context, constraints, output, and success checks.",
  },
  {
    id: "openai-prompt-evaluation-flywheel",
    tier: "primary",
    kind: "official-github",
    title: "Building Resilient Prompts Using an Evaluation Flywheel",
    publisher: "OpenAI",
    url: "https://github.com/openai/openai-cookbook/blob/main/examples/evaluation/Building_resilient_prompts_using_an_evaluation_flywheel.md",
    exactAnchor: "https://github.com/openai/openai-cookbook/blob/main/examples/evaluation/Building_resilient_prompts_using_an_evaluation_flywheel.md#the-evaluation-flywheel",
    supportingAnchors: [
      "https://github.com/openai/openai-cookbook/blob/main/examples/evaluation/Building_resilient_prompts_using_an_evaluation_flywheel.md#aligning-your-llm-judge",
    ],
    accessedOn,
    verifiedOn,
    claimIds: [
      "eval.analyze-measure-improve",
      "eval.representative-test-set",
      "eval.manual-failure-analysis",
      "eval.llm-judge-alignment",
    ],
    licence: "MIT",
    licenceUrl: "https://github.com/openai/openai-cookbook/blob/main/LICENSE",
    reuse: "original-only",
    currency: "current",
    caveats: ["Platform tooling is OpenAI specific, while the evaluation loop is broadly applicable."],
    note: "Core evidence for teaching measurable prompt iteration instead of one-shot demonstrations.",
  },
  {
    id: "openai-latest-model-guidance",
    tier: "primary",
    kind: "official-doc",
    title: "Model guidance",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/latest-model",
    exactAnchor: "https://developers.openai.com/api/docs/guides/latest-model#prompting-best-practices",
    accessedOn,
    verifiedOn,
    claimIds: [
      "modern.lean-outcome-first-prompts",
      "modern.model-specific-validation",
    ],
    licence: "site-terms",
    licenceUrl: null,
    reuse: "original-only",
    currency: "time-sensitive",
    caveats: [
      "Recheck immediately before publication and after major model releases.",
      "API guidance does not apply identically to chat-only interfaces.",
    ],
    note: "Current operational source for lean prompts and model-specific guidance.",
  },
  {
    id: "openai-structured-outputs-guide",
    tier: "primary",
    kind: "official-doc",
    title: "Structured model outputs",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/structured-outputs",
    exactAnchor: "https://developers.openai.com/api/docs/guides/structured-outputs#handling-mistakes",
    supportingAnchors: [
      "https://developers.openai.com/api/docs/guides/structured-outputs#handling-user-generated-input",
      "https://developers.openai.com/api/docs/guides/structured-outputs#refusals",
    ],
    accessedOn,
    verifiedOn,
    claimIds: ["modern.structured-outputs"],
    licence: "site-terms",
    licenceUrl: null,
    reuse: "original-only",
    currency: "time-sensitive",
    caveats: [
      "Structured Outputs is an API feature and does not apply identically to ordinary chat interfaces.",
      "Schema adherence constrains output shape; it does not establish that the returned facts are correct.",
      "Applications must handle incompatible input, refusals, incomplete or truncated responses, and other model mistakes.",
    ],
    note: "Direct first-party support for schema-conforming API output, kept separate from factual-grounding claims.",
  },
  {
    id: "anthropic-prompt-engineering-overview",
    tier: "primary",
    kind: "official-doc",
    title: "Prompt engineering overview",
    publisher: "Anthropic",
    url: "https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/overview",
    exactAnchor: "https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/overview",
    accessedOn,
    verifiedOn,
    claimIds: [
      "eval.criteria-before-optimization",
      "architecture.prompting-is-not-a-universal-fix",
      "modern.model-specific-validation",
    ],
    licence: "site-terms",
    licenceUrl: null,
    reuse: "original-only",
    currency: "time-sensitive",
    caveats: [
      "Guidance is Claude specific.",
      "Recheck model-specific advice before publication.",
    ],
    note: "Primary comparative source for defining success criteria before prompt optimization.",
  },
  {
    id: "anthropic-prompting-best-practices",
    tier: "primary",
    kind: "official-doc",
    title: "Prompting best practices",
    publisher: "Anthropic",
    url: "https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices",
    exactAnchor: "https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices",
    accessedOn,
    verifiedOn,
    claimIds: [
      "prompt.clear-specific-instructions",
      "prompt.zero-shot-and-few-shot",
      "workflow.decompose-and-chain",
      "modern.model-specific-validation",
    ],
    licence: "site-terms",
    licenceUrl: null,
    reuse: "original-only",
    currency: "time-sensitive",
    caveats: [
      "Guidance is Claude specific and changes with model generations.",
      "Provider-specific recommendations about example counts, XML, or chaining must be validated on the selected model and task.",
    ],
    note: "Anthropic's living reference for clear instructions, examples, XML structure, and explicit chains when intermediate inspection or a fixed pipeline is required.",
  },
  {
    id: "google-prompt-design-strategies",
    tier: "primary",
    kind: "official-doc",
    title: "Prompt design strategies",
    publisher: "Google AI for Developers",
    url: "https://ai.google.dev/gemini-api/docs/prompting-strategies",
    exactAnchor: "https://ai.google.dev/gemini-api/docs/prompting-strategies#clear-and-specific-instructions",
    supportingAnchors: [
      "https://ai.google.dev/gemini-api/docs/prompting-strategies#few-shot",
      "https://ai.google.dev/gemini-api/docs/prompting-strategies#prompt-components",
    ],
    accessedOn,
    verifiedOn,
    claimIds: [
      "prompt.clear-specific-instructions",
      "prompt.zero-shot-and-few-shot",
      "prompt.positive-consistent-examples",
      "workflow.decompose-and-chain",
    ],
    licence: "site-terms",
    licenceUrl: null,
    reuse: "original-only",
    currency: "time-sensitive",
    caveats: [
      "Guidance is Gemini specific.",
      "Recommendations about always using examples must be tested rather than taught as universal rules.",
    ],
    note: "Primary comparative source for examples, context, decomposition, and iteration.",
  },
  {
    id: "openai-model-spec-untrusted-data",
    tier: "primary",
    kind: "official-doc",
    title: "OpenAI Model Spec",
    publisher: "OpenAI",
    url: "https://model-spec.openai.com/2026-08-18.html",
    exactAnchor: "https://model-spec.openai.com/2026-08-18.html#ignore_untrusted_data",
    supportingAnchors: [
      "https://model-spec.openai.com/2026-08-18.html#scope_of_autonomy",
      "https://model-spec.openai.com/2026-08-18.html#control_side_effects",
    ],
    accessedOn,
    verifiedOn,
    claimIds: [
      "safety.untrusted-data-has-no-authority",
      "safety.format-untrusted-data-explicitly",
      "safety.scope-permissions-and-approval",
    ],
    licence: "CC0-1.0",
    licenceUrl: "https://github.com/openai/model_spec/blob/main/LICENSE",
    reuse: "original-only",
    currency: "time-sensitive",
    caveats: [
      "The Model Spec describes intended OpenAI model behavior, not a complete application security control.",
      "Formatting untrusted data helps interpretation but does not eliminate prompt injection risk.",
    ],
    note: "Core safety source for instruction authority, bounded autonomy, explicit approval points, and control of consequential side effects.",
  },
  {
    id: "openai-agent-builder-safety",
    tier: "primary",
    kind: "official-doc",
    title: "Safety in building agents",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/agent-builder-safety",
    exactAnchor: "https://developers.openai.com/api/docs/guides/agent-builder-safety#keep-tool-approvals-on",
    supportingAnchors: [
      "https://developers.openai.com/api/docs/guides/agent-builder-safety#dont-use-untrusted-variables-in-developer-messages",
      "https://developers.openai.com/api/docs/guides/agent-builder-safety#use-structured-outputs-to-constrain-data-flow",
      "https://developers.openai.com/api/docs/guides/agent-builder-safety#use-guardrails-for-user-inputs",
      "https://developers.openai.com/api/docs/guides/agent-builder-safety#run-trace-graders-and-evals",
      "https://developers.openai.com/api/docs/guides/agent-builder-safety#combine-techniques",
    ],
    accessedOn,
    verifiedOn,
    claimIds: ["safety.application-tool-approvals-and-guardrails"],
    licence: "site-terms",
    licenceUrl: null,
    reuse: "original-only",
    currency: "time-sensitive",
    caveats: [
      "The page is scoped to MCP and Agent Builder workflows; its approval advice should not be presented as a universal provider interface.",
      "Agent Builder is deprecated and scheduled to shut down on 30 November 2026, so retain only the general layered-control principles and recheck the page before publication.",
      "Guardrails, structured outputs, validation, confirmations, and isolation reduce risk but do not eliminate prompt injection.",
    ],
    note: "Current first-party evidence for application-enforced tool approvals, constrained data flow, input guardrails, trace review, and layered mitigations.",
  },
  {
    id: "anthropic-jailbreak-prompt-injection-mitigation",
    tier: "primary",
    kind: "official-doc",
    title: "Mitigate jailbreaks and prompt injections",
    publisher: "Anthropic",
    url: "https://platform.claude.com/docs/en/test-and-evaluate/strengthen-guardrails/mitigate-jailbreaks",
    exactAnchor: "https://platform.claude.com/docs/en/test-and-evaluate/strengthen-guardrails/mitigate-jailbreaks#indirect-prompt-injection",
    supportingAnchors: [
      "https://platform.claude.com/docs/en/test-and-evaluate/strengthen-guardrails/mitigate-jailbreaks#jailbreaks-and-direct-prompt-injection",
      "https://platform.claude.com/docs/en/test-and-evaluate/strengthen-guardrails/mitigate-jailbreaks#continuous-monitoring",
      "https://platform.claude.com/docs/en/test-and-evaluate/strengthen-guardrails/mitigate-jailbreaks#advanced-chain-safeguards",
    ],
    accessedOn,
    verifiedOn,
    claimIds: ["safety.least-privilege-and-injection-monitoring"],
    licence: "site-terms",
    licenceUrl: null,
    reuse: "original-only",
    currency: "time-sensitive",
    caveats: [
      "Message-block formats, named models, and classifier examples are Claude specific and should not be generalized across providers.",
      "Least privilege, sandboxing, output screening, and monitoring strengthen defenses but do not make prompt injection impossible.",
    ],
    note: "Current first-party evidence for least privilege, narrow permissions, sandboxed tools, screening untrusted tool results, continuous monitoring, and layered safeguards.",
  },
  {
    id: "microsoft-prompt-engineering-fundamentals",
    tier: "corroborating",
    kind: "official-github",
    title: "Prompt Engineering Fundamentals",
    publisher: "Microsoft",
    url: "https://github.com/microsoft/generative-ai-for-beginners/blob/main/04-prompt-engineering-fundamentals/README.md",
    exactAnchor: "https://github.com/microsoft/generative-ai-for-beginners/blob/main/04-prompt-engineering-fundamentals/README.md#prompt-engineering-fundamentals",
    accessedOn,
    verifiedOn,
    claimIds: [
      "prompt.components-and-sandbox-practice",
      "model.outputs-vary-by-model-and-run",
      "prompt.clear-specific-instructions",
    ],
    licence: "MIT",
    licenceUrl: "https://github.com/microsoft/generative-ai-for-beginners/blob/main/LICENSE",
    reuse: "original-only",
    currency: "mixed",
    caveats: [
      "Some examples use older models and older provider terminology.",
      "Third-party images or linked assets may have separate terms.",
    ],
    note: "Corroborating source for fundamentals, experimentation, and model variability.",
  },
  {
    id: "microsoft-advanced-prompts",
    tier: "corroborating",
    kind: "official-github",
    title: "Creating Advanced Prompts",
    publisher: "Microsoft",
    url: "https://github.com/microsoft/generative-ai-for-beginners/blob/main/05-advanced-prompts/README.md",
    exactAnchor: "https://github.com/microsoft/generative-ai-for-beginners/blob/main/05-advanced-prompts/README.md#techniques-for-prompting",
    supportingAnchors: [
      "https://github.com/microsoft/generative-ai-for-beginners/blob/main/05-advanced-prompts/README.md#least-to-most",
    ],
    accessedOn,
    verifiedOn,
    claimIds: [
      "prompt.templates-and-least-to-most",
      "workflow.decompose-and-chain",
      "prompt.zero-shot-and-few-shot",
    ],
    licence: "MIT",
    licenceUrl: "https://github.com/microsoft/generative-ai-for-beginners/blob/main/LICENSE",
    reuse: "original-only",
    currency: "mixed",
    caveats: [
      "Older chain-of-thought framing must not be presented as universal guidance for current reasoning models.",
      "Validate every technique on the selected model and task.",
    ],
    note: "Corroborating source for templates, examples, and task decomposition.",
  },
  {
    id: "dair-prompt-engineering-guide",
    tier: "corroborating",
    kind: "community-github",
    title: "Prompt Engineering Guide",
    publisher: "DAIR.AI",
    url: "https://github.com/dair-ai/Prompt-Engineering-Guide",
    exactAnchor: "https://github.com/dair-ai/Prompt-Engineering-Guide#guides",
    supportingAnchors: [
      "https://github.com/dair-ai/Prompt-Engineering-Guide/blob/main/guides/prompts-intro.md#prompting-introduction",
    ],
    accessedOn,
    verifiedOn,
    claimIds: [
      "taxonomy.prompt-elements-and-techniques",
      "taxonomy.retrieval-evaluation-and-risks",
      "prompt.zero-shot-and-few-shot",
    ],
    licence: "MIT",
    licenceUrl: "https://github.com/dair-ai/Prompt-Engineering-Guide/blob/main/LICENSE.md",
    reuse: "original-only",
    currency: "mixed",
    caveats: [
      "This is a curated secondary taxonomy, not a model provider specification.",
      "Some introductory examples were tested with the legacy text-davinci-003 model.",
    ],
    note: "Use as a discovery map and bibliography after checking claims against current first-party sources.",
  },
  {
    id: "anthropic-interactive-prompt-tutorial",
    tier: "corroborating",
    kind: "official-github",
    title: "Welcome to Anthropic's Prompt Engineering Interactive Tutorial",
    publisher: "Anthropic",
    url: "https://github.com/anthropics/prompt-eng-interactive-tutorial",
    exactAnchor: "https://github.com/anthropics/prompt-eng-interactive-tutorial#table-of-contents",
    accessedOn,
    verifiedOn,
    claimIds: [
      "tutorial.roles-boundaries-formatting-examples",
      "tutorial.unsupported-claims-complex-prompts-chaining",
      "workflow.decompose-and-chain",
    ],
    licence: "undeclared",
    licenceUrl: null,
    reuse: "link-only",
    currency: "legacy",
    caveats: [
      "The repository declares no licence, so public availability does not authorize reuse.",
      "The tutorial targets Claude 3 Haiku and contains dated model-specific guidance.",
    ],
    note: "Link and paraphrase concepts only. Do not copy notebooks, prompts, exercises, or answer keys.",
  },
] as const satisfies readonly PromptSourceRecord[];

function indexPromptSources(
  sources: readonly PromptSourceRecord[],
): Readonly<Record<PromptSourceId, PromptSourceRecord>> {
  const index = {} as Record<PromptSourceId, PromptSourceRecord>;

  for (const source of sources) {
    index[source.id] = source;
  }

  return Object.freeze(index);
}

export const PROMPT_SOURCE_BY_ID = indexPromptSources(PROMPT_SOURCES);
