import type { CourseKitSourceAuthoringSeed } from "../course-kit/authoring";
import type { CourseKitNonEmpty } from "../course-kit/types";

const ACCESSED_ON = "2026-08-26";

export const RESPONSIBLE_AI_SOURCE_SEEDS = [
  {
    record: {
      id: "nist-ai-rmf",
      title: "Artificial Intelligence Risk Management Framework (AI RMF 1.0)",
      publisher: "National Institute of Standards and Technology",
      url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-ai-rmf-10",
      evidenceUrls: ["https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-ai-rmf-10", "https://doi.org/10.6028/NIST.AI.100-1"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2023-01-26",
      revision: "NIST AI 100-1, version 1.0; NIST has announced a revision process",
      kind: "official-guidance",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "United States government work boundary; third-party credited material excluded",
      supports: "A voluntary, use-case-agnostic Govern–Map–Measure–Manage structure for contextual AI risk management.",
      boundary: "AI RMF 1.0 is not a law, certification, deployment approval, or fixed future version; legal risk classes require jurisdiction-specific sources.",
    },
    zhHans: { supports: "支持以 Govern、Map、Measure、Manage 组织有情境的自愿 AI 风险管理。", boundary: "AI RMF 1.0 不是法律、认证、部署批准或永久版本；法律风险分类必须回到具体法域。" },
  },
  {
    record: {
      id: "nist-ai-rmf-playbook",
      title: "NIST AI RMF Playbook and Core",
      publisher: "National Institute of Standards and Technology",
      url: "https://www.nist.gov/itl/ai-risk-management-framework/nist-ai-rmf-playbook",
      evidenceUrls: ["https://www.nist.gov/itl/ai-risk-management-framework/nist-ai-rmf-playbook", "https://airc.nist.gov/airmf-resources/airmf/5-sec-core/"],
      accessedOn: ACCESSED_ON,
      revision: "Rolling Playbook updated 2026-06-10; based on AI RMF 1.0",
      kind: "official-guidance",
      stability: "current-documentation",
      reuseStatus: "licence-noted-no-copy",
      licence: "United States government work boundary; third-party credited material excluded",
      supports: "Optional actions for governance, monitoring, appeal, override, incident handling, change management, and decommissioning.",
      boundary: "The Playbook explicitly offers suggestions rather than a mandatory checklist and will change after the AI RMF revision.",
    },
    zhHans: { supports: "支持治理、监测、申诉、覆盖、事件、变更与退役的可选行动。", boundary: "Playbook 是建议而非强制清单，并会随 AI RMF 修订而变化。" },
  },
  {
    record: {
      id: "oecd-ai-principles",
      title: "OECD AI Principles — 2024 update",
      publisher: "Organisation for Economic Co-operation and Development",
      url: "https://oecd.ai/en/wonk/evolving-with-innovation-the-2024-oecd-ai-principles-update",
      evidenceUrls: ["https://oecd.ai/en/wonk/evolving-with-innovation-the-2024-oecd-ai-principles-update"],
      accessedOn: ACCESSED_ON,
      revision: "Principles adopted 2019; updated May 2024",
      kind: "official-guidance",
      stability: "version-pinned",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Policy principles for human rights, transparency, robustness, safety, security, and accountability in trustworthy AI.",
      boundary: "The principles are not a jurisdiction's directly enforceable law or a technical conformance test.",
    },
    zhHans: { supports: "支持可信 AI 的人权、透明、稳健、安全、安保与问责政策原则。", boundary: "这些原则不是某法域直接执行的法律，也不是技术符合性测试。" },
  },
  {
    record: {
      id: "algorithmic-impact-assessment",
      title: "Algorithmic Impact Assessment and Directive on Automated Decision-Making",
      publisher: "Government of Canada, Treasury Board of Canada Secretariat",
      url: "https://www.canada.ca/en/government/system/digital-government/digital-government-innovations/responsible-use-ai/algorithmic-impact-assessment.html",
      evidenceUrls: ["https://www.canada.ca/en/government/system/digital-government/digital-government-innovations/responsible-use-ai/algorithmic-impact-assessment.html", "https://www.tbs-sct.canada.ca/pol/doc-eng.aspx?id=32592"],
      accessedOn: ACCESSED_ON,
      revision: "Directive modified 2025-06-24; 65 risk and 41 mitigation questions",
      jurisdiction: "Canada — federal administrative decisions within the Directive's scope",
      kind: "official-guidance",
      stability: "jurisdiction-and-date-bound",
      reuseStatus: "licence-noted-no-copy",
      licence: "Open Government Licence – Canada, subject to its terms",
      supports: "A structured impact-level assessment and mitigation record for covered Canadian federal automated administrative decisions.",
      boundary: "It does not govern every Canadian private-sector, provincial, research, test, or international AI use.",
    },
    zhHans: { supports: "支持加拿大联邦适用行政自动化决定的结构化影响等级与缓解记录。", boundary: "它不覆盖所有加拿大私营、省级、研究、测试或国际 AI 用途。" },
  },
  {
    record: {
      id: "oecd-privacy",
      title: "OECD Guidelines Governing the Protection of Privacy and Transborder Flows of Personal Data",
      publisher: "Organisation for Economic Co-operation and Development",
      url: "https://legalinstruments.oecd.org/public/doc/114/body-text.en.html",
      evidenceUrls: ["https://legalinstruments.oecd.org/public/doc/114/body-text.en.html"],
      accessedOn: ACCESSED_ON,
      revision: "Adopted 1980; revised 2013",
      kind: "official-guidance",
      stability: "version-pinned",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Collection limitation, data quality, purpose specification, use limitation, security safeguards, openness, participation, and accountability principles.",
      boundary: "These policy principles do not replace a locally applicable privacy law, lawful basis analysis, or sector-specific duty.",
    },
    zhHans: { supports: "支持收集限制、数据质量、目的限定、使用限制、安全保障、开放、个人参与与问责原则。", boundary: "这些政策原则不能替代当地隐私法、合法基础分析或行业义务。" },
  },
  {
    record: {
      id: "nist-privacy-framework",
      title: "NIST Privacy Framework",
      publisher: "National Institute of Standards and Technology",
      url: "https://www.nist.gov/privacy-framework/privacy-framework",
      evidenceUrls: ["https://www.nist.gov/privacy-framework/privacy-framework"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2020-01-16",
      revision: "Final version 1.0; version 1.1 remained an Initial Public Draft at access",
      kind: "official-guidance",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "United States government work boundary; third-party credited material excluded",
      supports: "A risk-based structure for identifying, governing, controlling, communicating, and protecting against privacy risk.",
      boundary: "Privacy Framework 1.0 is voluntary and does not determine lawful basis, individual rights, or final version 1.1 requirements.",
    },
    zhHans: { supports: "支持识别、治理、控制、沟通与保护隐私风险的风险导向结构。", boundary: "Privacy Framework 1.0 是自愿框架，不决定合法基础、个人权利或尚未最终定稿的 1.1 要求。" },
  },
  {
    record: {
      id: "eu-gdpr",
      title: "Regulation (EU) 2016/679 (General Data Protection Regulation)",
      publisher: "European Union",
      url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32016R0679",
      evidenceUrls: ["https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32016R0679"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2016-05-04",
      jurisdiction: "European Union / European Economic Area subject to applicable scope",
      kind: "law-or-regulation",
      stability: "jurisdiction-and-date-bound",
      reuseStatus: "link-and-paraphrase-only",
      supports: "The official legal text for data-minimisation principles and safeguards around certain solely automated decisions.",
      boundary: "The course does not determine territorial scope, lawful basis, exceptions, controller roles, or an individual's legal remedy for a particular deployment.",
    },
    zhHans: { supports: "支持数据最小化原则及特定纯自动化决定保障的欧盟正式法律文本。", boundary: "课程不为具体部署判断地域适用、合法基础、例外、控制者角色或个人法律救济。" },
  },
  {
    record: {
      id: "fairlearn-user-guide",
      title: "Fairlearn User Guide",
      publisher: "Fairlearn project",
      url: "https://fairlearn.org/main/user_guide/index.html",
      evidenceUrls: ["https://fairlearn.org/main/user_guide/index.html"],
      accessedOn: ACCESSED_ON,
      revision: "Rolling development documentation accessed 2026-08-26; implementation must pin a released version",
      kind: "official-documentation",
      stability: "current-documentation",
      reuseStatus: "licence-noted-no-copy",
      licence: "MIT project licence; site and third-party assets are not presumed reusable",
      supports: "Fairness-assessment and mitigation interfaces together with an explicit sociotechnical framing of fairness.",
      boundary: "No metric or API can establish complete justice, due process, absence of harm, or the right policy trade-off.",
    },
    zhHans: { supports: "支持公平评估与缓解接口，并明确把公平视为社会技术问题。", boundary: "任何指标或 API 都不能证明完整正义、正当程序、无伤害或正确政策取舍。" },
  },
  {
    record: {
      id: "gender-shades",
      title: "Gender Shades: Intersectional Accuracy Disparities in Commercial Gender Classification",
      publisher: "Proceedings of Machine Learning Research",
      url: "https://proceedings.mlr.press/v81/buolamwini18a/",
      evidenceUrls: ["https://proceedings.mlr.press/v81/buolamwini18a/"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2018-02-23",
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "A primary research case showing why aggregate performance can hide intersectional subgroup disparities.",
      boundary: "The task, labels, products, population and results are case-bounded and cannot be treated as current universal face-model error rates.",
    },
    zhHans: { supports: "支持总体性能可能掩盖交叉子群差异的一手研究案例。", boundary: "任务、标签、产品、人群与结果只适用于该案例，不能当作当前所有视觉模型的普遍误差率。" },
  },
  {
    record: {
      id: "nist-sp-1270",
      title: "Towards a Standard for Identifying and Managing Bias in Artificial Intelligence",
      publisher: "National Institute of Standards and Technology",
      url: "https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.1270.pdf",
      evidenceUrls: ["https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.1270.pdf"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2022-03-16",
      revision: "NIST SP 1270",
      kind: "technical-report",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "United States government work boundary; third-party credited material excluded",
      supports: "A lifecycle-oriented taxonomy and management framing for systemic, computational, and human-cognitive bias.",
      boundary: "The report does not prescribe one fairness metric, subgroup threshold, or certification result for every use case.",
    },
    zhHans: { supports: "支持系统性、计算性与人类认知偏差的生命周期分类与管理框架。", boundary: "报告不为所有用途规定单一公平指标、子群阈值或认证结论。" },
  },
  {
    record: {
      id: "uncertainty-calibration",
      title: "On Calibration of Modern Neural Networks",
      publisher: "Proceedings of Machine Learning Research",
      url: "https://proceedings.mlr.press/v70/guo17a.html",
      evidenceUrls: ["https://proceedings.mlr.press/v70/guo17a.html"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2017-08-06",
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Primary empirical evidence about neural-network miscalibration and temperature scaling in the studied settings.",
      boundary: "Calibration is not accuracy, causal confidence, fairness, or a guarantee under distribution shift; reported gains are case-bounded.",
    },
    zhHans: { supports: "支持特定实验中神经网络失校准与温度缩放的一手证据。", boundary: "校准不等于准确、因果确信、公平或分布变化下的保证；论文结果只适用于研究条件。" },
  },
  {
    record: {
      id: "model-cards",
      title: "Model Cards for Model Reporting",
      publisher: "ACM Conference on Fairness, Accountability, and Transparency",
      url: "https://research.google/pubs/model-cards-for-model-reporting/",
      evidenceUrls: ["https://research.google/pubs/model-cards-for-model-reporting/", "https://doi.org/10.1145/3287560.3287596"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2019-01-29",
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "A reporting framework for intended uses, evaluation conditions, subgroup results, caveats, and limitations.",
      boundary: "A completed card does not prove its claims, certify the model, authorize deployment, or replace continuous evaluation.",
    },
    zhHans: { supports: "支持记录允许用途、评估条件、子群结果、警示与局限的报告框架。", boundary: "填完卡片不能证明其中主张、认证模型、授权部署或替代持续评估。" },
  },
  {
    record: {
      id: "datasheets",
      title: "Datasheets for Datasets",
      publisher: "Communications of the ACM",
      url: "https://www.microsoft.com/en-us/research/publication/datasheets-for-datasets/",
      evidenceUrls: ["https://www.microsoft.com/en-us/research/publication/datasheets-for-datasets/", "https://doi.org/10.1145/3458723"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2021-12-01",
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Dataset documentation prompts covering motivation, composition, collection, processing, distribution, use, and maintenance.",
      boundary: "A datasheet does not establish lawful rights, consent, representativeness, completeness, or truth of its answers.",
    },
    zhHans: { supports: "支持记录数据动机、构成、采集、处理、分发、用途与维护的提示框架。", boundary: "数据说明书不能证明合法权利、同意、代表性、完整性或填写内容真实。" },
  },
  {
    record: {
      id: "nist-genai-profile",
      title: "Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile",
      publisher: "National Institute of Standards and Technology",
      url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf",
      evidenceUrls: ["https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2024-07-26",
      revision: "NIST AI 600-1",
      kind: "official-guidance",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "United States government work boundary; third-party credited material excluded",
      supports: "GenAI risk actions, adversarial testing, incident signals, documentation, monitoring, and change-management considerations.",
      boundary: "The profile is a companion to AI RMF 1.0, not a universal system-card template, certification checklist, or regulation.",
    },
    zhHans: { supports: "支持生成式 AI 风险行动、对抗测试、事件信号、文档、监测与变更管理。", boundary: "该文件是 AI RMF 1.0 配套资料，不是统一系统卡模板、认证清单或法规。" },
  },
  {
    record: {
      id: "eu-hleg-ethics-guidelines-2019-historical",
      title: "Ethics Guidelines for Trustworthy AI",
      publisher: "European Commission High-Level Expert Group on AI",
      url: "https://digital-strategy.ec.europa.eu/en/library/ethics-guidelines-trustworthy-ai",
      evidenceUrls: ["https://digital-strategy.ec.europa.eu/en/library/ethics-guidelines-trustworthy-ai"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2019-04-08",
      revision: "Historical, non-binding expert guidance",
      jurisdiction: "European Union policy context; non-binding",
      kind: "official-guidance",
      stability: "historical",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Historical human-agency and oversight guidance, including meaningful human review and reserved authority.",
      boundary: "It is non-binding 2019 expert guidance and must not be presented as the current EU AI Act or a legal compliance conclusion.",
    },
    zhHans: { supports: "支持关于人工能动性、有效监督与保留决定权的历史性指导。", boundary: "这是 2019 年非约束专家指南，不得被写成现行 EU AI Act 或法律合规结论。" },
  },
  {
    record: {
      id: "eu-ai-act-2024",
      title: "Regulation (EU) 2024/1689 and current implementation timeline",
      publisher: "European Union and European Commission",
      url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj?locale=en",
      evidenceUrls: ["https://eur-lex.europa.eu/eli/reg/2024/1689/oj?locale=en", "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2024-07-12",
      revision: "Official Journal text plus Commission implementation page updated 2026-08-03",
      jurisdiction: "European Union, subject to instrument scope and phased application",
      kind: "law-or-regulation",
      stability: "jurisdiction-and-date-bound",
      reuseStatus: "link-and-paraphrase-only",
      supports: "The official legal instrument and a current official implementation timeline for risk classes, human oversight, transparency, and phased application.",
      boundary: "The Commission overview is non-binding and cannot replace article-level legal analysis, consolidated amendments, exceptions, standards, or competent-authority interpretation.",
    },
    zhHans: { supports: "支持风险分类、人工监督、透明与分阶段适用的正式法源及当前官方实施时间线。", boundary: "Commission 概览不具约束力，不能代替逐条法律分析、合并修订、例外、协调标准或主管机关解释。" },
  },
  {
    record: {
      id: "unesco-ai-ethics",
      title: "Recommendation on the Ethics of Artificial Intelligence",
      publisher: "UNESCO",
      url: "https://www.unesco.org/en/legal-affairs/recommendation-ethics-artificial-intelligence",
      evidenceUrls: ["https://www.unesco.org/en/legal-affairs/recommendation-ethics-artificial-intelligence"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2021-11-23",
      revision: "Recommendation adopted by the General Conference",
      kind: "normative-standard",
      stability: "version-pinned",
      reuseStatus: "link-and-paraphrase-only",
      supports: "A global standard-setting recommendation covering human rights, oversight, accountability, redress, governance, and lifecycle responsibility.",
      boundary: "A UNESCO Recommendation is not automatically directly enforceable national law and does not specify a complete technical implementation.",
    },
    zhHans: { supports: "支持覆盖人权、监督、问责、救济、治理与生命周期责任的全球标准制定建议。", boundary: "UNESCO 建议不会自动成为直接执行的国内法，也不规定完整技术实现。" },
  },
  {
    record: {
      id: "nist-incident-response-r3",
      title: "Incident Response Recommendations and Considerations for Cybersecurity Risk Management",
      publisher: "National Institute of Standards and Technology",
      url: "https://csrc.nist.gov/pubs/sp/800/61/r3/final",
      evidenceUrls: ["https://csrc.nist.gov/pubs/sp/800/61/r3/final"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2025-04-03",
      revision: "NIST SP 800-61 Revision 3 final; Revision 2 withdrawn",
      kind: "official-guidance",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "United States government work boundary; third-party credited material excluded",
      supports: "Preparation, detection, response, recovery, evidence preservation, communication, and improvement within a broader risk-management lifecycle.",
      boundary: "This cybersecurity guidance does not define every AI-specific incident, sector reporting law, disclosure deadline, or method for undoing irreversible harm.",
    },
    zhHans: { supports: "支持风险管理生命周期中的准备、侦测、响应、恢复、证据保存、沟通与改进。", boundary: "该网络安全指南不定义所有 AI 特有事件、行业报告法律、披露时限，也不能撤销不可逆伤害。" },
  },
] as const satisfies CourseKitNonEmpty<CourseKitSourceAuthoringSeed>;

export type ResponsibleAiSourceId =
  (typeof RESPONSIBLE_AI_SOURCE_SEEDS)[number]["record"]["id"];
