import type { ClaudeLessonSlug, ClaudePracticeManifest } from "./types";

export const CLAUDE_PRACTICES = [
  { id: "practice-choose-your-surface", lessonSlug: "choose-your-surface", estimatedMinutes: 10, workspace: "disposable", requiresWriteAccess: false, evidenceItems: 2, promptKey: "lessons.choose-your-surface.practice.brief", observableActionCount: 3, selfCheckCriteriaCount: 2, completionKey: "claude.lesson.choose-your-surface" },
  { id: "practice-describe-the-outcome", lessonSlug: "describe-the-outcome", estimatedMinutes: 15, workspace: "either", requiresWriteAccess: false, evidenceItems: 2, promptKey: "lessons.describe-the-outcome.practice.brief", observableActionCount: 3, selfCheckCriteriaCount: 2, completionKey: "claude.lesson.describe-the-outcome" },
  { id: "practice-iterate-with-examples", lessonSlug: "iterate-with-examples", estimatedMinutes: 14, workspace: "disposable", requiresWriteAccess: false, evidenceItems: 2, promptKey: "lessons.iterate-with-examples.practice.brief", observableActionCount: 3, selfCheckCriteriaCount: 2, completionKey: "claude.lesson.iterate-with-examples" },
  { id: "practice-discern-verify-protect", lessonSlug: "discern-verify-protect", estimatedMinutes: 18, workspace: "disposable", requiresWriteAccess: false, evidenceItems: 2, promptKey: "lessons.discern-verify-protect.practice.brief", observableActionCount: 3, selfCheckCriteriaCount: 2, completionKey: "claude.lesson.discern-verify-protect" },
  { id: "practice-work-with-files", lessonSlug: "work-with-files", estimatedMinutes: 16, workspace: "disposable", requiresWriteAccess: true, evidenceItems: 2, promptKey: "lessons.work-with-files.practice.brief", observableActionCount: 3, selfCheckCriteriaCount: 2, completionKey: "claude.lesson.work-with-files" },
  { id: "practice-build-projects", lessonSlug: "build-projects", estimatedMinutes: 20, workspace: "personal-files", requiresWriteAccess: true, evidenceItems: 2, promptKey: "lessons.build-projects.practice.brief", observableActionCount: 3, selfCheckCriteriaCount: 2, completionKey: "claude.lesson.build-projects" },
  { id: "practice-create-artifacts", lessonSlug: "create-artifacts", estimatedMinutes: 18, workspace: "disposable", requiresWriteAccess: true, evidenceItems: 2, promptKey: "lessons.create-artifacts.practice.brief", observableActionCount: 3, selfCheckCriteriaCount: 2, completionKey: "claude.lesson.create-artifacts" },
  { id: "practice-research-with-citations", lessonSlug: "research-with-citations", estimatedMinutes: 25, workspace: "either", requiresWriteAccess: false, evidenceItems: 2, promptKey: "lessons.research-with-citations.practice.brief", observableActionCount: 3, selfCheckCriteriaCount: 2, completionKey: "claude.lesson.research-with-citations" },
  { id: "practice-extend-with-tools", lessonSlug: "extend-with-tools", estimatedMinutes: 18, workspace: "disposable", requiresWriteAccess: false, evidenceItems: 2, promptKey: "lessons.extend-with-tools.practice.brief", observableActionCount: 3, selfCheckCriteriaCount: 2, completionKey: "claude.lesson.extend-with-tools" },
  { id: "practice-delegate-with-cowork", lessonSlug: "delegate-with-cowork", estimatedMinutes: 25, workspace: "personal-files", requiresWriteAccess: true, evidenceItems: 2, promptKey: "lessons.delegate-with-cowork.practice.brief", observableActionCount: 3, selfCheckCriteriaCount: 2, completionKey: "claude.lesson.delegate-with-cowork" },
  { id: "practice-software-engineering", lessonSlug: "software-engineering", estimatedMinutes: 30, workspace: "personal-repository", requiresWriteAccess: true, evidenceItems: 2, promptKey: "lessons.software-engineering.practice.brief", observableActionCount: 3, selfCheckCriteriaCount: 2, completionKey: "claude.lesson.software-engineering" },
  { id: "practice-research-and-data", lessonSlug: "research-and-data", estimatedMinutes: 30, workspace: "disposable", requiresWriteAccess: true, evidenceItems: 2, promptKey: "lessons.research-and-data.practice.brief", observableActionCount: 3, selfCheckCriteriaCount: 2, completionKey: "claude.lesson.research-and-data" },
  { id: "practice-writing-and-office", lessonSlug: "writing-and-office", estimatedMinutes: 30, workspace: "personal-files", requiresWriteAccess: true, evidenceItems: 2, promptKey: "lessons.writing-and-office.practice.brief", observableActionCount: 3, selfCheckCriteriaCount: 2, completionKey: "claude.lesson.writing-and-office" },
  { id: "practice-teaching-and-learning", lessonSlug: "teaching-and-learning", estimatedMinutes: 25, workspace: "disposable", requiresWriteAccess: true, evidenceItems: 2, promptKey: "lessons.teaching-and-learning.practice.brief", observableActionCount: 3, selfCheckCriteriaCount: 2, completionKey: "claude.lesson.teaching-and-learning" },
  { id: "practice-portfolio-capstone", lessonSlug: "portfolio-capstone", estimatedMinutes: 75, workspace: "either", requiresWriteAccess: true, evidenceItems: 2, promptKey: "lessons.portfolio-capstone.practice.brief", observableActionCount: 3, selfCheckCriteriaCount: 2, completionKey: "claude.lesson.portfolio-capstone" },
] as const satisfies readonly ClaudePracticeManifest[];

export const CLAUDE_PRACTICE_BY_LESSON = Object.fromEntries(
  CLAUDE_PRACTICES.map((practice) => [practice.lessonSlug, practice]),
) as Readonly<Record<ClaudeLessonSlug, ClaudePracticeManifest>>;
