import {
  AGENT_ORCHESTRATION_COURSE_ID,
  AGENT_ORCHESTRATION_DEFAULT_CONTENT_LOCALE,
  type AgentOrchestrationCourseManifest,
  type AgentOrchestrationModuleManifest,
  type AgentOrchestrationPhaseManifest,
} from "./types";

export const AGENT_ORCHESTRATION_PHASES = [
  {
    id: "frame",
    order: 1,
    moduleSlugs: [
      "workflow-agent-boundary",
      "task-graphs-contracts",
      "chaining-routing",
      "parallel-fanout-fanin",
    ],
  },
  {
    id: "compose",
    order: 2,
    moduleSlugs: [
      "manager-roles-ownership",
      "delegation-handoffs",
      "orchestrator-workers-verification",
      "tools-aci-mcp",
    ],
  },
  {
    id: "control",
    order: 3,
    moduleSlugs: [
      "context-state-memory",
      "budgets-concurrency-stopping",
      "reliability-recovery",
      "security-authority-human-control",
    ],
  },
  {
    id: "operate",
    order: 4,
    moduleSlugs: [
      "tracing-observability-economics",
      "evaluation-regression-evolution",
      "production-orchestration-capstone",
    ],
  },
] as const satisfies readonly AgentOrchestrationPhaseManifest[];

export const AGENT_ORCHESTRATION_MODULES = [
  {
    slug: "workflow-agent-boundary",
    order: 1,
    phaseId: "frame",
    minutes: 55,
    sourceIds: [
      "openai-building-agents",
      "openai-practical-guide",
      "anthropic-effective-agents",
    ],
    conceptDomainIds: ["boundaries-autonomy", "production-operations"],
    patternIds: ["single-agent-loop"],
    labId: "pattern-selector",
  },
  {
    slug: "task-graphs-contracts",
    order: 2,
    phaseId: "frame",
    minutes: 65,
    sourceIds: [
      "openai-sdk-orchestration",
      "anthropic-effective-agents",
      "microsoft-agent-framework",
    ],
    conceptDomainIds: ["task-graphs-contracts", "roles-control-ownership"],
    patternIds: ["prompt-chain", "parallel-fanout", "group-or-hierarchical"],
    labId: "graph-contract",
  },
  {
    slug: "chaining-routing",
    order: 3,
    phaseId: "frame",
    minutes: 60,
    sourceIds: [
      "anthropic-effective-agents",
      "openai-sdk-orchestration",
      "openai-structured-outputs",
      "claude-academy-api",
    ],
    conceptDomainIds: ["deterministic-workflows", "task-graphs-contracts"],
    patternIds: ["prompt-chain", "router"],
    labId: "pattern-selector",
  },
  {
    slug: "parallel-fanout-fanin",
    order: 4,
    phaseId: "frame",
    minutes: 70,
    sourceIds: [
      "anthropic-effective-agents",
      "openai-sdk-orchestration",
      "openai-function-calling",
      "openai-responses-multi-agent",
      "openai-codex-subagents",
      "openai-codex-sandbox-security",
      "openai-agents-python-patterns",
      "oracle-critical-path",
      "etcd-quorum-glossary",
    ],
    conceptDomainIds: ["parallelism-aggregation", "scheduling-budgets"],
    patternIds: ["parallel-fanout", "group-or-hierarchical"],
    labId: "graph-contract",
  },
  {
    slug: "manager-roles-ownership",
    order: 5,
    phaseId: "compose",
    minutes: 65,
    sourceIds: [
      "openai-agents-orchestration",
      "openai-practical-guide",
      "anthropic-research-system",
    ],
    conceptDomainIds: ["roles-control-ownership", "delegation-communication"],
    patternIds: ["manager-tools", "group-or-hierarchical"],
    labId: "handoff-contract",
  },
  {
    slug: "delegation-handoffs",
    order: 6,
    phaseId: "compose",
    minutes: 70,
    sourceIds: [
      "openai-agents-orchestration",
      "openai-results-state",
      "claude-academy-subagents",
      "claude-sdk-subagents",
    ],
    conceptDomainIds: ["delegation-communication", "roles-control-ownership"],
    patternIds: ["manager-tools", "handoff"],
    labId: "handoff-contract",
  },
  {
    slug: "orchestrator-workers-verification",
    order: 7,
    phaseId: "compose",
    minutes: 75,
    sourceIds: [
      "anthropic-effective-agents",
      "anthropic-research-system",
      "openai-sdk-orchestration",
      "openai-agents-python-patterns",
      "claude-cookbooks-patterns",
      "anthropic-harness-long-running",
    ],
    conceptDomainIds: [
      "dynamic-orchestration",
      "delegation-communication",
      "evaluation-evolution",
    ],
    patternIds: [
      "orchestrator-workers",
      "evaluator-optimizer",
      "group-or-hierarchical",
    ],
    labId: "graph-contract",
  },
  {
    slug: "tools-aci-mcp",
    order: 8,
    phaseId: "compose",
    minutes: 70,
    sourceIds: [
      "openai-tools",
      "openai-function-calling",
      "openai-mcp-connectors",
      "anthropic-writing-tools",
      "anthropic-effective-agents",
      "mcp-spec-2026",
      "mcp-changelog-2026",
      "mcp-versioning-2026",
      "mcp-python-sdk-v2",
      "claude-academy-mcp-legacy",
      "mcp-ts-migration-2026",
    ],
    conceptDomainIds: ["tools-protocols", "security-governance"],
    patternIds: ["single-agent-loop", "manager-tools"],
    labId: "handoff-contract",
  },
  {
    slug: "context-state-memory",
    order: 9,
    phaseId: "control",
    minutes: 75,
    sourceIds: [
      "openai-context-management",
      "openai-running-agents",
      "openai-results-state",
      "openai-compaction",
      "anthropic-context-engineering",
      "anthropic-managed-agents",
      "azure-cosmos-distributed-lock",
    ],
    conceptDomainIds: ["context-state-memory", "reliability-durability"],
    patternIds: ["single-agent-loop", "group-or-hierarchical"],
    labId: "context-recovery",
  },
  {
    slug: "budgets-concurrency-stopping",
    order: 10,
    phaseId: "control",
    minutes: 65,
    sourceIds: [
      "openai-sdk-orchestration",
      "openai-responses-multi-agent",
      "openai-codex-subagents",
      "openai-codex-sandbox-security",
      "openai-latency",
      "openai-cost",
      "claude-sdk-agent-loop",
      "anthropic-research-system",
    ],
    conceptDomainIds: ["scheduling-budgets", "parallelism-aggregation"],
    patternIds: ["parallel-fanout", "orchestrator-workers"],
    labId: "context-recovery",
  },
  {
    slug: "reliability-recovery",
    order: 11,
    phaseId: "control",
    minutes: 80,
    sourceIds: [
      "openai-model-retries",
      "openai-webhooks",
      "openai-background",
      "openai-running-agents",
      "claude-sdk-checkpointing",
      "anthropic-managed-agents",
      "github-aws-return-path-issue",
      "aws-idempotent-apis",
      "aws-backoff-jitter",
      "azure-retry-storm",
      "azure-compensating-transactions",
      "azure-cosmos-distributed-lock",
    ],
    conceptDomainIds: ["reliability-durability", "task-graphs-contracts"],
    patternIds: ["prompt-chain", "orchestrator-workers"],
    labId: "context-recovery",
  },
  {
    slug: "security-authority-human-control",
    order: 12,
    phaseId: "control",
    minutes: 80,
    sourceIds: [
      "openai-guardrails-approvals",
      "openai-sdk-hitl",
      "openai-safety",
      "openai-mcp-connectors",
      "claude-sdk-permissions",
      "claude-secure-deployment",
    ],
    conceptDomainIds: ["security-governance", "roles-control-ownership"],
    patternIds: ["single-agent-loop", "manager-tools", "handoff"],
    labId: "governance-trace",
  },
  {
    slug: "tracing-observability-economics",
    order: 13,
    phaseId: "operate",
    minutes: 65,
    sourceIds: [
      "openai-observability",
      "openai-tracing",
      "openai-latency",
      "openai-cost",
      "google-sre-error-budget",
      "claude-sdk-observability",
      "anthropic-research-system",
      "otel-overview",
      "otel-baggage-security",
    ],
    conceptDomainIds: ["observability-economics", "production-operations"],
    patternIds: ["orchestrator-workers", "evaluator-optimizer"],
    labId: "governance-trace",
  },
  {
    slug: "evaluation-regression-evolution",
    order: 14,
    phaseId: "operate",
    minutes: 75,
    sourceIds: [
      "openai-agent-evals",
      "anthropic-agent-evals",
      "openai-agents-python-v022",
      "openai-swarm-lifecycle",
      "anthropic-agent-sdk-v02143",
      "langgraph-v1211",
      "microsoft-agent-framework",
      "autogen-maintenance",
    ],
    conceptDomainIds: ["evaluation-evolution", "observability-economics"],
    patternIds: ["router", "evaluator-optimizer", "orchestrator-workers"],
    labId: "governance-trace",
  },
  {
    slug: "production-orchestration-capstone",
    order: 15,
    phaseId: "operate",
    minutes: 90,
    sourceIds: [
      "openai-background",
      "openai-webhooks",
      "openai-running-agents",
      "anthropic-managed-agents",
      "microsoft-agent-framework",
      "google-adk-v271",
    ],
    conceptDomainIds: [
      "production-operations",
      "reliability-durability",
      "security-governance",
      "evaluation-evolution",
    ],
    patternIds: [
      "single-agent-loop",
      "router",
      "parallel-fanout",
      "manager-tools",
      "handoff",
      "orchestrator-workers",
      "evaluator-optimizer",
    ],
    labId: "production-readiness",
  },
] as const satisfies readonly AgentOrchestrationModuleManifest[];

export const AGENT_ORCHESTRATION_COURSE_MANIFEST = {
  id: AGENT_ORCHESTRATION_COURSE_ID,
  version: "1.1.1",
  displayNumber: 15,
  publishedOn: "2026-08-23",
  defaultContentLocale: AGENT_ORCHESTRATION_DEFAULT_CONTENT_LOCALE,
  phases: AGENT_ORCHESTRATION_PHASES,
  modules: AGENT_ORCHESTRATION_MODULES,
} as const satisfies AgentOrchestrationCourseManifest;
