import type {
  AgentOrchestrationSourceLayer,
  AgentOrchestrationSourceRecord,
  AgentOrchestrationSourceReuseStatus,
} from "./types";

const ACCESSED_ON = "2026-08-23";

/**
 * Course 15 source ledger.
 *
 * Product documentation is linked and paraphrased. Repository examples are
 * pinned to a release when a suitable release exists. A source's `boundary`
 * is part of the learner-facing evidence contract, not internal metadata.
 */
type AgentOrchestrationSourceCore = Omit<
  AgentOrchestrationSourceRecord,
  | "layer"
  | "reuseStatus"
  | "transformation"
  | "supportsZhHans"
  | "boundaryZhHans"
  | "claimEvidenceUrls"
> & {
  /** Omit only when the primary `url` is the complete claim-evidence set. */
  readonly claimEvidenceUrls?: readonly [string, ...string[]];
};

const AGENT_ORCHESTRATION_SOURCE_CORES = [
  {
    id: "openai-building-agents",
    title: "Building agents",
    publisher: "OpenAI",
    url: "https://developers.openai.com/tracks/building-agents",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "The current OpenAI distinction between ordinary model use, agent loops, orchestration, tools, state, guardrails, and evaluation.",
    boundary: "The page is a current product track without a public revision date; API names and recommended models must be rechecked before deployment.",
  },
  {
    id: "openai-practical-guide",
    title: "A practical guide to building agents",
    publisher: "OpenAI",
    url: "https://cdn.openai.com/business-guides-and-resources/a-practical-guide-to-building-agents.pdf",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "stable-concept",
    supports: "The single-agent loop, manager pattern, decentralized handoff pattern, and layered guardrail design.",
    boundary: "This is a conceptual business guide, not a wire protocol, runtime trace, or guarantee that every OpenAI product uses one topology.",
  },
  {
    id: "openai-sdk-orchestration",
    title: "Agent orchestration",
    publisher: "OpenAI Agents SDK",
    url: "https://openai.github.io/openai-agents-python/multi_agent/",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "LLM-directed and code-directed orchestration, structured routing, sequential chains, evaluator loops, and application-level parallel runs.",
    boundary: "The SDK is one implementation surface; examples and main-branch documentation may move ahead of a released package.",
  },
  {
    id: "openai-agents-orchestration",
    title: "Orchestration and handoffs",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/agents/orchestration",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "The ownership difference between manager-style agents-as-tools and handoffs where a specialist takes control.",
    boundary: "The examples describe current OpenAI SDK semantics, not a universal definition implemented identically by every framework.",
  },
  {
    id: "openai-structured-outputs",
    title: "Structured model outputs",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/structured-outputs",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Strict response contracts, the difference between structured response formats and function calling, and refusal or incomplete states.",
    boundary: "Schema conformance establishes shape, not truth, authorization, calibration, or safety of the proposed action.",
  },
  {
    id: "openai-function-calling",
    title: "Function calling",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/function-calling",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "The model-tool-result loop, strict function schemas, call identity, and provider-side parallel tool calls.",
    boundary: "Producing several tool calls in one model turn is not the same control plane as running several complete agents concurrently.",
  },
  {
    id: "openai-responses-multi-agent",
    title: "Multi-agent",
    publisher: "OpenAI Responses API",
    url: "https://developers.openai.com/api/docs/guides/responses-multi-agent",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "beta",
    supports: "Hosted root and subagent execution, nested task paths, HTTP and WebSocket coordination, concurrency controls, and current limitations.",
    boundary: "This capability is Beta, model-limited, token-intensive, and schema-sensitive; it is a frontier case rather than the course's stable foundation.",
  },
  {
    id: "openai-codex-subagents",
    title: "Subagents",
    publisher: "OpenAI Codex",
    url: "https://learn.chatgpt.com/docs/agent-configuration/subagents",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Current Codex subagent availability, spawned-thread controls, context return, shared-write guidance, sandbox inheritance, and the agents.max_concurrent_threads_per_session field.",
    boundary: "This is a Codex client/runtime surface, not Responses Multi-agent; the page does not promise a numeric default for an unset thread cap or a no-fixed-depth rule.",
  },
  {
    id: "openai-codex-sandbox-security",
    title: "Agent approvals & security",
    publisher: "OpenAI Codex",
    url: "https://learn.chatgpt.com/docs/agent-approvals-security",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "The distinction between OS-enforced sandbox boundaries, approval policy, network controls, protected paths, and runtime-specific defaults in Codex.",
    boundary: "Approval is a decision gate, not containment: depending on runtime and configuration, an approved action may execute outside the ordinary sandbox or with network access. Approval does not prove correctness or make the widened blast radius safe. Command-network policy still does not govern every web, app, MCP, browser, or hosted connection surface.",
  },
  {
    id: "openai-agents-python-patterns",
    title: "Agent patterns examples",
    publisher: "OpenAI",
    url: "https://github.com/openai/openai-agents-python/tree/v0.22.0/examples/agent_patterns",
    accessedOn: ACCESSED_ON,
    kind: "official-github",
    stability: "version-pinned",
    revision: "v0.22.0",
    license: "MIT",
    supports: "Runnable official examples for deterministic flows, routing, agents-as-tools, judge loops, parallelization, guardrails, and human review.",
    boundary: "Examples demonstrate SDK patterns, not production guarantees; integrations, error handling, and model availability still require local verification.",
  },
  {
    id: "openai-results-state",
    title: "Results and state",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/agents/results",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Final output, history, last-agent ownership, interruptions, and resumable run state.",
    boundary: "A run result can represent an interruption rather than completion; applications must not treat every returned object as a successful answer.",
  },
  {
    id: "openai-tools",
    title: "Tools",
    publisher: "OpenAI Agents SDK",
    url: "https://openai.github.io/openai-agents-python/tools/",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Hosted, local, function, MCP, agent-as-tool, tool-search, and programmatic-tool execution surfaces.",
    boundary: "Some tools are experimental or model-specific; an available tool is not automatically authorized for every agent or user.",
  },
  {
    id: "openai-mcp-connectors",
    title: "MCP and connectors",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/tools-connectors-mcp",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Remote MCP connection, approvals, allowed-tool boundaries, and the prompt-injection and data-sharing threat model.",
    boundary: "Third-party MCP servers are external systems whose behavior, retention, and security OpenAI does not verify for the application.",
  },
  {
    id: "openai-context-management",
    title: "Context management",
    publisher: "OpenAI Agents SDK",
    url: "https://openai.github.io/openai-agents-python/context/",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "The distinction between application-local run context and model-visible conversational context.",
    boundary: "Objects placed in application context are not automatically model memory, and secrets can still leak if a tool or prompt serializes them.",
  },
  {
    id: "openai-running-agents",
    title: "Running agents",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/agents/running-agents",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Agent-loop execution and the application-history, session, conversation ID, and previous-response continuation strategies.",
    boundary: "Mixing several continuation strategies can duplicate context; durable business execution still requires an application-owned state model.",
  },
  {
    id: "openai-compaction",
    title: "Compaction",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/compaction",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Server-side and standalone compaction for balancing long-context quality, latency, and cost.",
    boundary: "Compacted state is not a human-readable audit record and must not replace explicit task state, evidence, or durable artifacts.",
  },
  {
    id: "openai-model-retries",
    title: "Models: timeouts and retries",
    publisher: "OpenAI Agents SDK",
    url: "https://openai.github.io/openai-agents-js/guides/models/",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Opt-in model retry policies, per-attempt timeouts, backoff, abort behavior, and replay-safety limits.",
    boundary: "The API is SDK-version sensitive; retries cannot make external side effects exactly-once and unsafe streamed or stateful work should fail closed.",
  },
  {
    id: "openai-webhooks",
    title: "Webhooks",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/webhooks",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Signature verification, fast acknowledgement, possible duplicate delivery, retry timing, and webhook-id deduplication.",
    boundary: "Webhook consumers must tolerate repeated delivery, but finite retries do not guarantee eventual delivery; receiving a repeated event does not authorize repeating a business side effect.",
  },
  {
    id: "openai-background",
    title: "Background mode",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/background",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Asynchronous long model responses, polling, cancellation, stream resumption, and current storage constraints.",
    boundary: "Background mode manages one asynchronous response within its documented polling, storage, and retention constraints; it is not a complete multi-step workflow engine, transaction log, or compensation system.",
  },
  {
    id: "openai-guardrails-approvals",
    title: "Guardrails and human review",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/agents/guardrails-approvals",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Input, output, and tool guardrails; blocking versus parallel checks; and approval at an execution boundary.",
    boundary: "Guardrail coverage is scoped and does not automatically propagate across every handoff, hosted tool, or side effect.",
  },
  {
    id: "openai-sdk-hitl",
    title: "Human-in-the-loop",
    publisher: "OpenAI Agents SDK",
    url: "https://openai.github.io/openai-agents-python/human_in_the_loop/",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Interruptions, approve or reject decisions, serialized run state, and resumption of the same run.",
    boundary: "Approval permits an action; it does not prove the action is correct, and serialized state can contain sensitive application context.",
  },
  {
    id: "openai-safety",
    title: "Safety best practices",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/safety-best-practices",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Moderation, red teaming, human oversight, input and output constraints, user communication, and safety identifiers.",
    boundary: "General safety guidance must be extended with a system-specific threat model, authorization checks, isolation, incident response, and domain review.",
  },
  {
    id: "openai-observability",
    title: "Integrations and observability",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/agents/integrations-observability",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Workflow, model, tool, handoff, guardrail, and custom tracing spans across agent runs.",
    boundary: "A trace is evidence about execution, not an evaluation verdict; production observability also needs outcomes, errors, privacy controls, and service metrics.",
  },
  {
    id: "openai-tracing",
    title: "Tracing",
    publisher: "OpenAI Agents SDK",
    url: "https://openai.github.io/openai-agents-python/tracing/",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Tracing configuration, sensitive-data capture controls, custom processors, and zero-data-retention limitations.",
    boundary: "Trace payloads can themselves expose prompts, arguments, and results; collection requires minimization, redaction, retention, and access policy.",
  },
  {
    id: "openai-latency",
    title: "Latency optimization",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/latency-optimization",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Reducing tokens and requests, parallelizing independent work, and avoiding unnecessary model calls.",
    boundary: "Parallelism reduces wall-clock time only for suitable independent work and can increase total tokens, complexity, and tail latency.",
  },
  {
    id: "openai-cost",
    title: "Cost optimization",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/cost-optimization",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Reducing requests and tokens and selecting the smallest model that meets an evaluated quality threshold.",
    boundary: "Cost optimization cannot be separated from task-success, safety, and latency measurement; a cheaper failed run is not an improvement.",
  },
  {
    id: "openai-agent-evals",
    title: "Evaluate agent workflows",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/agent-evals",
    accessedOn: ACCESSED_ON,
    kind: "openai-official",
    stability: "current-documentation",
    supports: "Trace grading, tool and handoff evaluation, datasets, repeatable eval runs, and workflow-level regression testing.",
    boundary: "An evaluator is another measurement instrument; graders need calibration, multiple trials, and end-state checks rather than blind trust.",
  },
  {
    id: "openai-agents-python-v022",
    title: "OpenAI Agents Python v0.22.0",
    publisher: "OpenAI",
    url: "https://github.com/openai/openai-agents-python/blob/v0.22.0/README.md",
    claimEvidenceUrls: [
      "https://github.com/openai/openai-agents-python/blob/v0.22.0/README.md",
      "https://github.com/openai/openai-agents-python/releases/tag/v0.22.0",
    ],
    versionAnchorUrl: "https://github.com/openai/openai-agents-python/releases/tag/v0.22.0",
    accessedOn: ACCESSED_ON,
    kind: "official-github",
    stability: "version-pinned",
    revision: "v0.22.0",
    license: "MIT",
    supports: "The pinned README identifies the official Python Agents SDK surface, while the v0.22.0 release notes directly substantiate replay-state redaction, isolated RunState checkpoint usage, output-guardrail hardening, and handoff expansion in generated graphs.",
    boundary: "The release notes support only their listed v0.22.0 changes, not every SDK behavior; the rolling main branch can be ahead of the tag and projects must test their exact dependency lock.",
  },
  {
    id: "openai-swarm-lifecycle",
    title: "Swarm (experimental, educational)",
    publisher: "OpenAI",
    url: "https://github.com/openai/swarm/blob/main/README.md",
    accessedOn: ACCESSED_ON,
    kind: "official-github",
    stability: "historical",
    license: "MIT",
    supports: "OpenAI's official lifecycle notice that experimental Swarm has been replaced by the production-ready Agents SDK and that production users should migrate to the Agents SDK.",
    boundary: "The rolling README is lifecycle evidence, not a pinned implementation contract; it does not require an immediate rewrite without application-specific migration and regression tests.",
  },
  {
    id: "anthropic-effective-agents",
    title: "Building effective agents",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/engineering/building-effective-agents",
    accessedOn: ACCESSED_ON,
    publishedOn: "2024-12-19",
    kind: "anthropic-official",
    stability: "stable-concept",
    supports: "Workflow versus agent boundaries, augmented LLMs, chaining, routing, parallelization, orchestrator-workers, evaluator-optimizer, autonomous loops, and Anthropic's agent-computer interface (ACI) term with its HCI-style tool-documentation and testing guidance.",
    boundary: "These are stable architecture patterns, not current tooling guidance, a specification of Claude Code internals, or proof that more autonomy is better; Anthropic explicitly notes that much of the tooling landscape described has changed since December 2024.",
  },
  {
    id: "claude-academy-api",
    title: "Building with the Claude API",
    publisher: "Claude Academy",
    url: "https://academy.claude.com/courses/building-with-the-claude-api",
    accessedOn: ACCESSED_ON,
    kind: "claude-academy",
    stability: "current-documentation",
    supports: "Anthropic's official learning sequence for APIs, tool use, evaluation, RAG, MCP, agents, chaining, routing, and parallelization.",
    boundary: "Academy text, quizzes, screenshots, and video remain Anthropic content; this course links and paraphrases rather than redistributing them.",
  },
  {
    id: "anthropic-research-system",
    title: "How we built our multi-agent research system",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/engineering/multi-agent-research-system",
    accessedOn: ACCESSED_ON,
    publishedOn: "2025-06-13",
    kind: "anthropic-official",
    stability: "stable-concept",
    supports: "Lead-researcher and parallel-subagent architecture, context isolation, dynamic decomposition, citation work, coordination failures, and token economics.",
    boundary: "Reported quality and token multipliers are internal research-system results, not universal performance constants for other models or tasks.",
  },
  {
    id: "claude-academy-subagents",
    title: "Introduction to subagents",
    publisher: "Claude Academy",
    url: "https://academy.claude.com/courses/introduction-to-subagents",
    accessedOn: ACCESSED_ON,
    kind: "claude-academy",
    stability: "current-documentation",
    supports: "Separate subagent context, scoped instructions and tools, structured return formats, obstacle reporting, and selection boundaries.",
    boundary: "A subagent summary is a lossy communication channel; evidence and unresolved uncertainty need explicit fields or durable artifacts.",
  },
  {
    id: "claude-sdk-subagents",
    title: "Subagents",
    publisher: "Claude Agent SDK",
    url: "https://code.claude.com/docs/en/agent-sdk/subagents",
    accessedOn: ACCESSED_ON,
    kind: "anthropic-official",
    stability: "current-documentation",
    supports: "Current Claude Agent SDK subagent isolation, specialized prompts, restricted tools, parallel work, and parent-result return behavior.",
    boundary: "The semantics belong to the Claude Agent SDK and can change with the runtime; they are not a cross-framework protocol.",
  },
  {
    id: "anthropic-writing-tools",
    title: "Writing effective tools for agents — with agents",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/engineering/writing-tools-for-agents",
    accessedOn: ACCESSED_ON,
    publishedOn: "2025-09-11",
    kind: "anthropic-official",
    stability: "stable-concept",
    supports: "Tool interfaces as agent-computer contracts, clear namespaces and schemas, actionable errors, compact results, and eval-driven refinement.",
    boundary: "A well-described tool improves model use but does not supply authorization, isolation, transactionality, or a trustworthy external system.",
  },
  {
    id: "mcp-spec-2026",
    title: "Model Context Protocol specification 2026-07-28",
    publisher: "Model Context Protocol",
    url: "https://modelcontextprotocol.io/specification/2026-07-28",
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-07-28",
    kind: "open-standard",
    stability: "version-pinned",
    revision: "2026-07-28",
    supports: "The current stateless core, self-contained requests, per-request capabilities, tools, resources, prompts, elicitation, and extension model.",
    boundary: "MCP standardizes capability exchange; it does not provide task decomposition, an agent loop, memory, approvals, sandboxing, or an eval harness by itself.",
  },
  {
    id: "mcp-changelog-2026",
    title: "MCP 2026-07-28 key changes",
    publisher: "Model Context Protocol",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/changelog",
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-07-28",
    kind: "open-standard",
    stability: "version-pinned",
    revision: "2026-07-28 changes since 2025-11-25",
    supports: "The exact 2026-07-28 removed, introduced, deprecated, and compatibility-relevant protocol changes, including stateless requests, server/discover, MRTR, resultType, subscriptions/listen, and legacy-feature deprecations.",
    boundary: "The changelog describes a protocol revision, not the default behavior of every installed SDK, client, server, Academy lesson, or hosted integration.",
  },
  {
    id: "mcp-versioning-2026",
    title: "MCP versioning",
    publisher: "Model Context Protocol",
    url: "https://modelcontextprotocol.io/docs/2026-07-28/learn/versioning",
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-07-28",
    kind: "open-standard",
    stability: "version-pinned",
    revision: "2026-07-28",
    supports: "Date-formatted protocol versions, Draft/Current/Final states, feature deprecation, per-request negotiation, UnsupportedProtocolVersionError, server/discover, and simultaneous legacy-version support.",
    boundary: "A Current revision may still receive backward-compatible changes, and compatibility requires the actual client and server to support a mutually acceptable revision.",
  },
  {
    id: "mcp-python-sdk-v2",
    title: "MCP Python SDK v2.0.0",
    publisher: "Model Context Protocol",
    url: "https://github.com/modelcontextprotocol/python-sdk/blob/6f69a3758ebf2ee55ce050f58b470ce11af71133/README.md",
    claimEvidenceUrls: [
      "https://github.com/modelcontextprotocol/python-sdk/blob/6f69a3758ebf2ee55ce050f58b470ce11af71133/README.md",
      "https://github.com/modelcontextprotocol/python-sdk/releases/tag/v2.0.0",
    ],
    versionAnchorUrl: "https://github.com/modelcontextprotocol/python-sdk/releases/tag/v2.0.0",
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-07-28",
    kind: "official-github",
    stability: "version-pinned",
    revision: "6f69a3758ebf2ee55ce050f58b470ce11af71133",
    license: "MIT",
    supports: "The pinned SDK source and v2.0.0 release notes establish a stable Python implementation for MCP 2026-07-28, automatic version negotiation, and simultaneous serving of earlier protocol revisions.",
    boundary: "Earlier Academy lessons and v1 examples may use handshake, session, and transport details that no longer describe the current core specification.",
  },
  {
    id: "claude-academy-mcp-legacy",
    title: "Model Context Protocol: Advanced Topics",
    publisher: "Claude Academy",
    url: "https://academy.claude.com/courses/model-context-protocol-advanced-topics",
    accessedOn: ACCESSED_ON,
    kind: "claude-academy",
    stability: "historical",
    supports: "A dated learning reference for pre-2026-07-28 MCP concepts including initialization, roots, sampling, logging callbacks, and SSE session management.",
    boundary: "This Academy material is not normative for MCP 2026-07-28; the course uses it only to teach temporal drift and migration, never as the current implementation contract.",
  },
  {
    id: "mcp-ts-migration-2026",
    title: "MCP TypeScript SDK migration: supporting 2026-07-28",
    publisher: "Model Context Protocol",
    url: "https://github.com/modelcontextprotocol/typescript-sdk/blob/3e90449fd52997da43b79a536d2c19c446603cc7/docs/migration/support-2026-07-28.md",
    versionAnchorUrl: "https://github.com/modelcontextprotocol/typescript-sdk/commit/3e90449fd52997da43b79a536d2c19c446603cc7",
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-08-17",
    kind: "official-sdk-docs",
    stability: "version-pinned",
    revision: "3e90449fd52997da43b79a536d2c19c446603cc7",
    license: "MIT",
    supports: "The concrete SDK migration boundary between older handshake and session-oriented examples and the self-contained 2026-07-28 protocol model.",
    boundary: "A migration guide describes one official SDK path; deployed clients and servers must still negotiate and test the versions they actually implement.",
  },
  {
    id: "anthropic-context-engineering",
    title: "Effective context engineering for AI agents",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents",
    accessedOn: ACCESSED_ON,
    publishedOn: "2025-09-29",
    kind: "anthropic-official",
    stability: "stable-concept",
    supports: "Context as a scarce attention budget, just-in-time retrieval, compaction, memory, and subagent context isolation.",
    boundary: "Context engineering selects model-visible evidence; it does not replace structured state, durable storage, provenance, or access control.",
  },
  {
    id: "anthropic-managed-agents",
    title: "Scaling Managed Agents: Decoupling the brain from the hands",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/engineering/managed-agents",
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-04-08",
    kind: "anthropic-official",
    stability: "current-documentation",
    supports: "A durable event-log session, model-loop harness, sandbox separation, crash recovery, and external credential boundary.",
    boundary: "Managed Agents is a vendor runtime and current product conditions may be Beta or policy-sensitive; the architecture is not a universal storage prescription.",
  },
  {
    id: "claude-sdk-agent-loop",
    title: "How the agent loop works",
    publisher: "Claude Agent SDK",
    url: "https://code.claude.com/docs/en/agent-sdk/agent-loop",
    accessedOn: ACCESSED_ON,
    kind: "anthropic-official",
    stability: "current-documentation",
    supports: "Tool-loop execution, maximum turns and budgets, compaction, resume and fork, and ordering read-only versus state-changing tools.",
    boundary: "Runtime defaults and limits are version-specific; a local tool loop still needs application-level cost, time, and side-effect controls.",
  },
  {
    id: "claude-sdk-checkpointing",
    title: "File checkpointing",
    publisher: "Claude Agent SDK",
    url: "https://code.claude.com/docs/en/agent-sdk/file-checkpointing",
    accessedOn: ACCESSED_ON,
    kind: "anthropic-official",
    stability: "current-documentation",
    supports: "File-change checkpoints and the documented recovery boundary for selected editing tools.",
    boundary: "The checkpoint does not cover every shell or subagent side effect and therefore is not a complete transaction or rollback mechanism.",
  },
  {
    id: "claude-sdk-permissions",
    title: "Configure permissions",
    publisher: "Claude Agent SDK",
    url: "https://code.claude.com/docs/en/agent-sdk/permissions",
    accessedOn: ACCESSED_ON,
    kind: "anthropic-official",
    stability: "current-documentation",
    supports: "The current six-stage tool-permission order—hooks, deny rules, ask rules, permission mode, allow rules, then canUseTool—plus child-agent inheritance and least-privilege design.",
    boundary: "Auto-approved calls may not reach canUseTool; use PreToolUse when a check must run on every call. allowed_tools pre-approves matches but does not constrain all unlisted tools; a fixed surface requires an appropriate dontAsk/deny/tool-removal configuration plus hooks and sandboxing. Permission policy is not operating-system isolation, and bypass modes require a separately controlled environment.",
  },
  {
    id: "claude-secure-deployment",
    title: "Securely deploying AI agents",
    publisher: "Claude Agent SDK",
    url: "https://code.claude.com/docs/en/agent-sdk/secure-deployment",
    accessedOn: ACCESSED_ON,
    kind: "anthropic-official",
    stability: "current-documentation",
    supports: "Prompt-injection and model-error threat models, least privilege, sandboxing, network and filesystem controls, credential proxies, and audit trails.",
    boundary: "This is defense-in-depth guidance, not certification that any default SDK configuration is safe for a particular threat model.",
  },
  {
    id: "claude-sdk-observability",
    title: "Observability with OpenTelemetry",
    publisher: "Claude Agent SDK",
    url: "https://code.claude.com/docs/en/agent-sdk/observability",
    accessedOn: ACCESSED_ON,
    kind: "anthropic-official",
    stability: "current-documentation",
    supports: "OpenTelemetry traces, metrics, events, token and cost signals, latency, tool calls, and failures.",
    boundary: "Some tracing capabilities are Beta, and telemetry content needs its own redaction, access, and retention policy.",
  },
  {
    id: "anthropic-agent-evals",
    title: "Demystifying evals for AI agents",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents",
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-01-09",
    kind: "anthropic-official",
    stability: "stable-concept",
    supports: "Task, trial, grader, trajectory, outcome, harness, suite, repeated trials, calibrated graders, and eval-driven development.",
    boundary: "Offline evals complement rather than replace production monitoring, A/B tests, user feedback, incident analysis, and human review.",
  },
  {
    id: "anthropic-harness-long-running",
    title: "Effective harnesses for long-running agents",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents",
    accessedOn: ACCESSED_ON,
    publishedOn: "2025-11-26",
    kind: "anthropic-official",
    stability: "stable-concept",
    supports: "Incremental long-running work, structured progress artifacts, verification state, and reliable recovery across context windows.",
    boundary: "The article describes an engineering approach, not a guarantee that a harness can eliminate model drift or incomplete work.",
  },
  {
    id: "claude-cookbooks-patterns",
    title: "Claude Cookbooks: agent patterns",
    publisher: "Anthropic",
    url: "https://github.com/anthropics/claude-cookbooks/tree/e22e683065954c07fae8bc4bc5fccf34d6595297/patterns/agents",
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-06-09",
    kind: "official-github",
    stability: "version-pinned",
    revision: "e22e683065954c07fae8bc4bc5fccf34d6595297",
    license: "MIT",
    supports: "Pinned minimal implementations of chaining, routing, parallelization, orchestrator-workers, evaluator-optimizer, and asynchronous multi-agent orchestration.",
    boundary: "Cookbooks are teaching examples rather than a production runtime and do not supply durable state, sandboxing, permissions, or recovery by themselves.",
  },
  {
    id: "anthropic-agent-sdk-v02143",
    title: "Claude Agent SDK Python v0.2.143",
    publisher: "Anthropic",
    url: "https://github.com/anthropics/claude-agent-sdk-python/blob/22795fe604a0682fc6c57d8ba998ebb50621446d/README.md",
    versionAnchorUrl: "https://github.com/anthropics/claude-agent-sdk-python/releases/tag/v0.2.143",
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-08-20",
    kind: "official-github",
    stability: "version-pinned",
    revision: "22795fe604a0682fc6c57d8ba998ebb50621446d",
    license: "MIT source; Anthropic services remain subject to separate terms",
    supports: "The pinned README provides reproducible evidence for the Python query loop, matching-tool pre-approval configuration, hooks, in-process MCP tools, and the documented presence of programmatic subagents and session forking in this source revision.",
    boundary: "The release tag establishes package version only; checkpoint and telemetry semantics require their separate current documentation, and an MIT SDK license does not license the hosted model service or override Anthropic terms.",
  },
  {
    id: "microsoft-agent-framework",
    title: "Microsoft Agent Framework Python 1.15.0",
    publisher: "Microsoft",
    url: "https://github.com/microsoft/agent-framework/blob/7a2b8038cc7809714308152782e58d4943720f61/README.md",
    claimEvidenceUrls: [
      "https://github.com/microsoft/agent-framework/blob/7a2b8038cc7809714308152782e58d4943720f61/README.md",
      "https://github.com/microsoft/agent-framework/releases/tag/python-1.15.0",
    ],
    versionAnchorUrl: "https://github.com/microsoft/agent-framework/releases/tag/python-1.15.0",
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-08-21",
    kind: "official-github",
    stability: "version-pinned",
    revision: "7a2b8038cc7809714308152782e58d4943720f61",
    license: "MIT",
    supports: "The pinned README directly documents graph-oriented sequential, concurrent, handoff, group, checkpoint, time-travel, human-review, and telemetry patterns; the Python 1.15.0 notes separately substantiate A2A input handling plus MCP argument-filtering and name-shadowing changes in that release stream.",
    boundary: "The repository contains multiple language and component release streams; one component tag must not be presented as the version of the whole framework.",
  },
  {
    id: "github-aws-return-path-issue",
    title: "CLI Agent Orchestrator issue 284: return-path failure",
    publisher: "AWS Labs community repository",
    url: "https://github.com/awslabs/cli-agent-orchestrator/issues/284",
    accessedOn: ACCESSED_ON,
    kind: "community-github-case",
    stability: "historical",
    supports: "A concrete public failure case showing why caller identity, task IDs, and return destinations should be structured rather than inferred from prose.",
    boundary: "An issue report is a bounded historical case and does not prove the same defect remains in the current project or generalizes to every orchestrator.",
  },
  {
    id: "aws-idempotent-apis",
    title: "Making retries safe with idempotent APIs",
    publisher: "AWS Builders' Library",
    url: "https://aws.amazon.com/builders-library/making-retries-safe-with-idempotent-APIs/",
    accessedOn: ACCESSED_ON,
    kind: "engineering-official",
    stability: "stable-concept",
    supports: "Stable caller-supplied operation identifiers, semantic equivalence, deduplication, and the ambiguous outcome where an effect commits but its response is lost.",
    boundary: "Idempotency is a service and application contract, not an emergent property of an agent or a generic request ID.",
  },
  {
    id: "aws-backoff-jitter",
    title: "Exponential backoff and jitter",
    publisher: "AWS Architecture Blog",
    url: "https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/",
    accessedOn: ACCESSED_ON,
    kind: "engineering-official",
    stability: "stable-concept",
    supports: "Finite exponential backoff with randomized jitter to reduce synchronized retry contention.",
    boundary: "Backoff changes timing only; it does not make an unsafe mutation replayable or replace a retry budget and failure classification.",
  },
  {
    id: "azure-retry-storm",
    title: "Retry Storm antipattern",
    publisher: "Microsoft Azure Architecture Center",
    url: "https://learn.microsoft.com/en-us/azure/architecture/antipatterns/retry-storm/",
    accessedOn: ACCESSED_ON,
    kind: "engineering-official",
    stability: "stable-concept",
    supports: "Honoring Retry-After, avoiding layered retry storms, using finite backoff, and opening a circuit breaker when a dependency continues to fail.",
    boundary: "Retry-After and circuit-breaker behavior remain dependency and application contracts; they do not make non-idempotent effects safe to replay.",
  },
  {
    id: "azure-compensating-transactions",
    title: "Compensating Transaction pattern",
    publisher: "Microsoft Azure Architecture Center",
    url: "https://learn.microsoft.com/en-us/azure/architecture/patterns/compensating-transaction",
    accessedOn: ACCESSED_ON,
    kind: "engineering-official",
    stability: "stable-concept",
    supports: "Compensation for eventually consistent multi-step workflows, including idempotent compensators and operations that cannot restore the exact prior state.",
    boundary: "Compensation is not atomic rollback; it can fail and irreversible effects require a manual reconciliation path.",
  },
  {
    id: "azure-cosmos-distributed-lock",
    title: "Azure Cosmos DB design pattern: Global Distributed Lock",
    publisher: "Microsoft Learn",
    url: "https://learn.microsoft.com/en-us/samples/azure-samples/cosmos-db-design-patterns/distributed-lock/",
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-07-06",
    kind: "engineering-official",
    stability: "current-documentation",
    supports: "A bounded implementation example combining atomic lock acquisition, ETag optimistic concurrency, TTL recovery, monotonically increasing fencing tokens, and downstream rejection of stale writers.",
    boundary: "This is an Azure Cosmos DB sample, not a universal lock service or proof for another datastore; correctness depends on the deployed store's atomicity and consistency plus downstream enforcement and failure testing.",
  },
  {
    id: "google-sre-error-budget",
    title: "Example Error Budget Policy",
    publisher: "Google SRE Workbook",
    url: "https://sre.google/workbook/error-budget-policy/",
    accessedOn: ACCESSED_ON,
    publishedOn: "2018-02-19",
    kind: "engineering-official",
    stability: "stable-concept",
    license: "CC BY-NC-ND 4.0; linked and paraphrased only",
    supports: "Error budget as the permitted unreliability implied by an SLO and as an explicit control for reliability work and release decisions.",
    boundary: "The example policy and its thresholds are not universal; each service must define user-centered SLIs, an SLO window, ownership, and decision rules.",
  },
  {
    id: "otel-overview",
    title: "OpenTelemetry specification overview",
    publisher: "OpenTelemetry",
    url: "https://opentelemetry.io/docs/specs/otel/overview/",
    accessedOn: ACCESSED_ON,
    kind: "open-standard",
    stability: "current-documentation",
    revision: "Specification 1.60.0",
    supports: "A span's single parent identifier, zero or more causal links, and the recommendation to use links rather than a parent for scatter/gather aggregation initiated by several spans.",
    boundary: "The specification defines telemetry semantics, not proof that every branch was instrumented, sampled, exported, retained, or correctly associated by a particular backend.",
  },
  {
    id: "otel-baggage-security",
    title: "Baggage",
    publisher: "OpenTelemetry",
    url: "https://opentelemetry.io/docs/concepts/signals/baggage/",
    accessedOn: ACCESSED_ON,
    kind: "engineering-official",
    stability: "current-documentation",
    supports: "Official guidance that sensitive Baggage can propagate in HTTP headers to unintended resources, including third-party APIs, and that Baggage has no built-in integrity checks.",
    boundary: "This is current explanatory guidance rather than the versioned normative specification. Do not put secrets or unminimized personal data in Baggage, and never treat Baggage as trusted authorization input.",
  },
  {
    id: "oracle-critical-path",
    title: "About Critical Path Activities",
    publisher: "Oracle Primavera P6",
    url: "https://docs.oracle.com/cd/F74773_01/p6help/en/6623.htm",
    accessedOn: ACCESSED_ON,
    kind: "engineering-official",
    stability: "stable-concept",
    supports: "Longest path as the sequence of driving activities that determines a project end date, together with the warning that constraints or resource leveling can break that relationship-driven longest path.",
    boundary: "This is official Primavera scheduling documentation, not a proof that one vendor algorithm solves arbitrary resource-constrained agent scheduling; the course's weighted-DAG and makespan formulation remains a bounded engineering synthesis.",
  },
  {
    id: "etcd-quorum-glossary",
    title: "etcd glossary: Quorum",
    publisher: "etcd",
    url: "https://etcd.io/docs/v3.7/learning/glossary/",
    accessedOn: ACCESSED_ON,
    kind: "engineering-official",
    stability: "current-documentation",
    supports: "The etcd v3.7 definition of quorum as the active-member count required for consensus to modify cluster state, with a member majority required to reach quorum.",
    boundary: "This is an etcd/Raft product definition, not a universal synonym for any k-of-n application join, a majority vote on answer truth, or a complete treatment of consensus membership and quorum-intersection proofs.",
  },
  {
    id: "langgraph-v1211",
    title: "LangGraph Python core 1.2.11",
    publisher: "LangChain",
    url: "https://github.com/langchain-ai/langgraph/blob/644815f9e5bc52ad8f7a5227a456227e9c3e639b/README.md",
    versionAnchorUrl: "https://github.com/langchain-ai/langgraph/releases/tag/1.2.11",
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-08-11",
    kind: "official-github",
    stability: "version-pinned",
    revision: "644815f9e5bc52ad8f7a5227a456227e9c3e639b",
    license: "MIT",
    supports: "The pinned README directly describes LangGraph as a stateful orchestration runtime and documents durable execution, human-in-the-loop control, and short- and long-term memory as its open-source runtime capabilities.",
    boundary: "The 1.2.11 release page is only the version anchor; the open-source runtime and commercial LangSmith services are separate, and core, checkpoint, and SDK release streams must not be conflated.",
  },
  {
    id: "google-adk-v271",
    title: "Google ADK v2.7.1 anchor and workflow documentation",
    publisher: "Google",
    url: "https://github.com/google/adk-docs/blob/main/docs/workflows/index.md",
    claimEvidenceUrls: [
      "https://github.com/google/adk-docs/blob/main/docs/workflows/index.md",
      "https://github.com/google/adk-docs/blob/main/docs/workflows/collaboration.md",
      "https://github.com/google/adk-docs/blob/main/docs/sessions/state.md",
    ],
    versionAnchorUrl: "https://github.com/google/adk-python/releases/tag/v2.7.1",
    accessedOn: ACCESSED_ON,
    kind: "official-github",
    stability: "current-documentation",
    revision: "d71f1bf1d77fd1e2fdc8b9a82d48645d64c5afc3",
    license: "Apache-2.0",
    supports: "Current official ADK documentation supports graph, dynamic, collaborative, and template workflows; branching, sequential, loop, and parallel execution; collaboration control transfer; and session state. A separate release anchor identifies Python v2.7.1 and its commit.",
    boundary: "The v2.7.1 release page establishes version and two listed fixes, not this broader feature set; the claim-evidence pages are rolling documentation, and 2.x behavior must be rechecked and tested against the deployed package.",
  },
  {
    id: "autogen-maintenance",
    title: "AutoGen maintenance notice",
    publisher: "Microsoft",
    url: "https://github.com/microsoft/autogen/blob/027ecf0a379bcc1d09956d46d12d44a3ad9cee14/README.md",
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-04-06",
    kind: "official-github",
    stability: "historical",
    revision: "027ecf0a379bcc1d09956d46d12d44a3ad9cee14",
    license: "MIT code; documentation has separate terms including CC BY 4.0 content",
    supports: "Lifecycle evidence that AutoGen is in maintenance mode and that Microsoft points new projects toward Microsoft Agent Framework.",
    boundary: "AutoGen remains useful historical prior art; maintenance status is not evidence that every existing AutoGen deployment should be rewritten immediately.",
  },
] as const satisfies readonly AgentOrchestrationSourceCore[];

type AgentOrchestrationSourceId =
  (typeof AGENT_ORCHESTRATION_SOURCE_CORES)[number]["id"];

const ENGINEERING_GUIDANCE_SOURCE_IDS = new Set<string>([
  "openai-practical-guide",
  "anthropic-effective-agents",
  "anthropic-research-system",
  "anthropic-writing-tools",
  "anthropic-context-engineering",
  "anthropic-managed-agents",
  "anthropic-agent-evals",
  "anthropic-harness-long-running",
]);

const SOURCE_ZH_HANS = {
  "openai-building-agents": {
    supportsZhHans: "当前 OpenAI 对常规模型调用、智能体循环、编排、工具、状态、护栏与评估的区分。",
    boundaryZhHans: "该页面是未提供公开修订日期的当前产品学习路径；部署前必须重新核对 API 名称与推荐模型。",
  },
  "openai-practical-guide": {
    supportsZhHans: "单智能体循环、管理者模式、去中心化移交模式与分层护栏设计。",
    boundaryZhHans: "这是概念性的业务指南，不是线协议或运行时追踪，也不保证每种 OpenAI 产品都采用同一种拓扑。",
  },
  "openai-sdk-orchestration": {
    supportsZhHans: "由 LLM 驱动和代码驱动的编排、结构化路由、顺序链、评估器循环，以及应用层并行运行。",
    boundaryZhHans: "该 SDK 只是一个实现界面；示例和 main 分支文档可能领先于已发布的软件包。",
  },
  "openai-agents-orchestration": {
    supportsZhHans: "管理者式 agents-as-tools 与移交后由专家接管之间的所有权差异。",
    boundaryZhHans: "这些示例描述的是当前 OpenAI SDK 语义，不是所有框架都会以相同方式实现的通用定义。",
  },
  "openai-structured-outputs": {
    supportsZhHans: "严格响应契约、结构化响应格式与函数调用的区别，以及拒绝或未完成状态。",
    boundaryZhHans: "符合 schema 只能证明结构正确，不能证明内容真实、操作已获授权、判断经过校准，或拟议操作安全。",
  },
  "openai-function-calling": {
    supportsZhHans: "模型—工具—结果循环、严格函数 schema、调用标识，以及提供方侧的并行工具调用。",
    boundaryZhHans: "模型在一次 turn 中生成多个工具调用，并不等同于用一个控制平面并发运行多个完整智能体。",
  },
  "openai-responses-multi-agent": {
    supportsZhHans: "托管式 root Agent 与 subagent 执行、嵌套任务路径、HTTP 与 WebSocket 协调、并发控制及当前限制。",
    boundaryZhHans: "Responses Multi-agent 仍处于 Beta，受模型限制、消耗较多 token 且对 schema 敏感；它是前沿案例，而不是本课程的稳定基础。",
  },
  "openai-codex-subagents": {
    supportsZhHans: "当前 Codex subagent 的可用性、派生任务线程控制、上下文回传、共享写入指引、sandbox 继承，以及 agents.max_concurrent_threads_per_session 字段。",
    boundaryZhHans: "这是 Codex 客户端与运行时界面，不是 Responses Multi-agent；该页面没有承诺未设置线程上限时的数值默认值，也没有承诺不存在固定深度限制。",
  },
  "openai-codex-sandbox-security": {
    supportsZhHans: "Codex 中由操作系统强制执行的 sandbox 边界、审批策略、网络控制、受保护路径与运行时特定默认值之间的区别。",
    boundaryZhHans: "审批是决策门而非隔离边界：依据运行时与配置，获批动作可能在普通 sandbox 之外执行或获得网络访问。审批不能证明正确性，也不能让扩大的影响面自动安全；命令网络策略仍不管辖所有 Web、app、MCP、browser 或托管连接界面。",
  },
  "openai-agents-python-patterns": {
    supportsZhHans: "可运行的官方示例，覆盖代码主导流程、路由、agents-as-tools、judge 循环、并行化、护栏和人工审查。",
    boundaryZhHans: "这些示例演示的是 SDK 模式，而非生产保证；集成、错误处理与模型可用性仍需在本地验证。",
  },
  "openai-results-state": {
    supportsZhHans: "最终输出、历史记录、last-agent 所有权、中断，以及可恢复的 run state。",
    boundaryZhHans: "run result 可能表示中断而非完成；应用不得把每一个返回对象都视为成功答案。",
  },
  "openai-tools": {
    supportsZhHans: "托管、本地、function、MCP、agent-as-tool、tool-search 与 programmatic-tool 执行界面。",
    boundaryZhHans: "部分工具仍属实验性或仅适用于特定模型；工具可用并不意味着每个智能体或用户都已获权使用。",
  },
  "openai-mcp-connectors": {
    supportsZhHans: "远程 MCP 连接、审批、允许工具边界，以及提示注入与数据共享威胁模型。",
    boundaryZhHans: "第三方 MCP server 是外部系统；OpenAI 不会替应用验证其行为、数据保留方式或安全性。",
  },
  "openai-context-management": {
    supportsZhHans: "应用本地 run context 与模型可见 conversational context 之间的区别。",
    boundaryZhHans: "放入应用 context 的对象不会自动成为模型记忆；如果工具或 prompt 将秘密序列化，秘密仍可能泄露。",
  },
  "openai-running-agents": {
    supportsZhHans: "智能体循环执行，以及通过应用历史、session、conversation ID 与 previous response 进行续接的策略。",
    boundaryZhHans: "混用多种续接策略可能重复上下文；持久化业务执行仍需要由应用拥有的状态模型。",
  },
  "openai-compaction": {
    supportsZhHans: "服务器端与独立 compaction，用于平衡长上下文质量、延迟与成本。",
    boundaryZhHans: "压缩后的状态不是人类可读的审计记录，不能替代显式任务状态、证据或持久化产物。",
  },
  "openai-model-retries": {
    supportsZhHans: "可选启用的模型重试策略、每次尝试的 timeout、backoff、abort 行为与 replay-safety 限制。",
    boundaryZhHans: "该 API 对 SDK 版本敏感；重试不能让外部副作用获得 exactly-once 语义，对不安全的流式或有状态工作应采用失败关闭。",
  },
  "openai-webhooks": {
    supportsZhHans: "签名验证、快速确认、可能的重复投递、重试时序，以及基于 webhook ID 的去重。",
    boundaryZhHans: "Webhook 消费者必须容忍重复投递，但有限重试并不保证最终一定送达；收到重复事件也不授权应用重复执行业务副作用。",
  },
  "openai-background": {
    supportsZhHans: "异步长时模型响应、轮询、取消、流式续传，以及当前存储约束。",
    boundaryZhHans: "Background mode 只在文档所述轮询、存储与保留约束内管理单个异步 response；它不是完整的多步骤工作流引擎、事务日志或补偿系统。",
  },
  "openai-guardrails-approvals": {
    supportsZhHans: "输入、输出与工具护栏；阻塞式与并行检查；以及在执行边界进行审批。",
    boundaryZhHans: "护栏的覆盖范围有限，不会自动传播到每一次移交、托管工具调用或副作用。",
  },
  "openai-sdk-hitl": {
    supportsZhHans: "中断、批准或拒绝决策、序列化 run state，以及同一 run 的恢复。",
    boundaryZhHans: "批准只代表允许执行某项操作，不能证明操作正确；序列化状态也可能包含敏感的应用 context。",
  },
  "openai-safety": {
    supportsZhHans: "内容审核、红队测试、人类监督、输入与输出约束、用户沟通，以及安全标识符。",
    boundaryZhHans: "通用安全指引必须结合具体系统的威胁模型、授权检查、隔离、事件响应和领域审查进行扩展。",
  },
  "openai-observability": {
    supportsZhHans: "跨智能体 run 的工作流、模型、工具、移交、护栏与自定义 tracing span。",
    boundaryZhHans: "trace 是执行证据，不是评估结论；生产可观测性还需要结果、错误、隐私控制与服务指标。",
  },
  "openai-tracing": {
    supportsZhHans: "Tracing 配置、敏感数据采集控制、自定义 processor，以及 Zero Data Retention 的限制。",
    boundaryZhHans: "Trace payload 本身可能暴露 prompt、参数与结果；采集时需要最小化、脱敏、保留期限与访问策略。",
  },
  "openai-latency": {
    supportsZhHans: "减少 token 与请求、并行处理相互独立的工作，以及避免不必要的模型调用。",
    boundaryZhHans: "并行化只会缩短适合独立执行任务的墙钟时间，同时可能增加总 token、复杂度与尾延迟。",
  },
  "openai-cost": {
    supportsZhHans: "减少请求与 token，并选择能够达到经评估质量阈值的最小模型。",
    boundaryZhHans: "成本优化不能脱离任务成功率、安全性与延迟测量；更便宜但失败的 run 并不是改进。",
  },
  "openai-agent-evals": {
    supportsZhHans: "Trace grading、工具与移交评估、数据集、可重复的 eval run，以及工作流级回归测试。",
    boundaryZhHans: "评估器本身也是一种测量工具；grader 需要校准、多次试验与最终状态检查，不能被盲目信任。",
  },
  "openai-agents-python-v022": {
    supportsZhHans: "固定版本 README 标识官方 Python Agents SDK 界面；v0.22.0 release notes 则直接支持 replay state 脱敏、RunState checkpoint 用量隔离、输出 guardrail 加固，以及生成图中的 handoff 扩展。",
    boundaryZhHans: "Release notes 只支持其中明确列出的 v0.22.0 变更，并不证明 SDK 的全部行为；滚动 main 可能领先于 tag，项目仍须测试实际 dependency lock。",
  },
  "openai-swarm-lifecycle": {
    supportsZhHans: "OpenAI 的官方生命周期说明：实验性 Swarm 已由面向生产的 Agents SDK 取代，生产用户应迁移到 Agents SDK。",
    boundaryZhHans: "滚动更新的 README 只能作为生命周期证据，不是版本锁定的实现契约；在完成应用特定的迁移与回归测试前，它也不要求立即重写现有系统。",
  },
  "anthropic-effective-agents": {
    supportsZhHans: "工作流与智能体边界、增强型 LLM、链式处理、路由、并行化、orchestrator-workers、evaluator-optimizer、自主循环，以及 Anthropic 对智能体—计算机接口（ACI）的命名和类 HCI 的工具文档与测试建议。",
    boundaryZhHans: "这些是稳定的架构模式，不是当前工具选型指南或 Claude Code 内部实现规范，也不能证明自主性更高一定更好；Anthropic 已明确注明，文中许多工具生态信息自 2024 年 12 月后已有变化。",
  },
  "claude-academy-api": {
    supportsZhHans: "Anthropic 关于 API、工具使用、评估、RAG、MCP、智能体、链式处理、路由与并行化的官方学习序列。",
    boundaryZhHans: "Academy 的文字、测验、截图与视频仍是 Anthropic 内容；本课程只提供链接与释义，不重新分发这些材料。",
  },
  "anthropic-research-system": {
    supportsZhHans: "lead researcher 与并行 subagent 架构、上下文隔离、动态任务分解、引用工作、协调失败与 token 经济性。",
    boundaryZhHans: "文中质量与 token 倍数来自 Anthropic 内部研究系统，不是适用于其他模型或任务的通用性能常数。",
  },
  "claude-academy-subagents": {
    supportsZhHans: "独立的 subagent context、限定范围的指令与工具、结构化返回格式、障碍报告与选择边界。",
    boundaryZhHans: "Subagent 摘要是一条有损通信通道；证据与尚未解决的不确定性需要显式字段或持久化产物。",
  },
  "claude-sdk-subagents": {
    supportsZhHans: "当前 Claude Agent SDK 的 subagent 隔离、专用 prompt、受限工具、并行工作，以及向 parent 返回结果的行为。",
    boundaryZhHans: "这些语义属于 Claude Agent SDK，并可能随运行时变化；它们不是跨框架协议。",
  },
  "anthropic-writing-tools": {
    supportsZhHans: "将工具界面视为智能体—计算机契约、清晰的 namespace 与 schema、可操作的错误信息、紧凑结果，以及由 eval 驱动的改进。",
    boundaryZhHans: "描述良好的工具有助于模型正确使用，但不能提供授权、隔离、事务性，也不能保证外部系统可信。",
  },
  "mcp-spec-2026": {
    supportsZhHans: "当前无状态核心、自包含请求、每请求能力声明、tools、resources、prompts、elicitation 与 extension 模型。",
    boundaryZhHans: "MCP 标准化的是能力交换；它本身不提供任务分解、智能体循环、记忆、审批、sandbox 或 eval harness。",
  },
  "mcp-changelog-2026": {
    supportsZhHans: "准确列出 2026-07-28 版本删除、新增、弃用及影响兼容性的协议变更，包括无状态请求、server/discover、MRTR、resultType、subscriptions/listen 与旧特性弃用。",
    boundaryZhHans: "该 changelog 描述的是一次协议修订，不代表每个已安装 SDK、client、server、Academy 课程或托管集成的默认行为。",
  },
  "mcp-versioning-2026": {
    supportsZhHans: "日期格式的协议版本、Draft／Current／Final 状态、特性弃用、每请求协商、UnsupportedProtocolVersionError、server/discover，以及同时支持旧版本的机制。",
    boundaryZhHans: "Current 修订仍可能加入向后兼容的变更；兼容性的前提是实际 client 与 server 支持一个双方都可接受的修订版本。",
  },
  "mcp-python-sdk-v2": {
    supportsZhHans: "固定的 SDK 源码与 v2.0.0 release notes 共同证明：这是 MCP 2026-07-28 的稳定 Python 实现，支持自动版本协商，并可同时服务较早的协议修订。",
    boundaryZhHans: "较早的 Academy 课程与 v1 示例可能采用 handshake、session 与 transport 细节，这些已不能描述当前核心规范。",
  },
  "claude-academy-mcp-legacy": {
    supportsZhHans: "关于 2026-07-28 之前 MCP 概念的历史学习资料，包括初始化、roots、sampling、logging callback 与 SSE session 管理。",
    boundaryZhHans: "该 Academy 材料不是 MCP 2026-07-28 的规范性依据；本课程只用它讲解时间漂移与迁移，绝不将其作为当前实现契约。",
  },
  "mcp-ts-migration-2026": {
    supportsZhHans: "明确说明旧式 handshake 和面向 session 的示例，与 2026-07-28 自包含协议模型之间的具体 SDK 迁移边界。",
    boundaryZhHans: "迁移指南只描述一个官方 SDK 的路径；已部署 client 与 server 仍须协商并测试各自实际实现的版本。",
  },
  "anthropic-context-engineering": {
    supportsZhHans: "将 context 视为稀缺的注意力预算、即时检索、compaction、memory 与 subagent context 隔离。",
    boundaryZhHans: "Context engineering 选择的是模型可见证据，不能替代结构化状态、持久化存储、来源记录或访问控制。",
  },
  "anthropic-managed-agents": {
    supportsZhHans: "持久化 event-log session、模型循环 harness、sandbox 分离、崩溃恢复与外部凭据边界。",
    boundaryZhHans: "Managed Agents 是厂商运行时，当前产品条件可能仍属 Beta 或受策略影响；该架构不是通用存储方案。",
  },
  "claude-sdk-agent-loop": {
    supportsZhHans: "工具循环执行、最大 turn 数与预算、compaction、resume 与 fork，以及只读工具和状态变更工具的调用顺序。",
    boundaryZhHans: "运行时默认值与限制取决于版本；本地工具循环仍需要应用层的成本、时间与副作用控制。",
  },
  "claude-sdk-checkpointing": {
    supportsZhHans: "文件变更 checkpoint，以及文档为部分编辑工具规定的恢复边界。",
    boundaryZhHans: "Checkpoint 不覆盖所有 shell 或 subagent 副作用，因此不是完整的事务或 rollback 机制。",
  },
  "claude-sdk-permissions": {
    supportsZhHans: "当前六阶段工具权限顺序：hooks、deny rules、ask rules、permission mode、allow rules，最后是 canUseTool；以及 child agent 继承和最小权限设计。",
    boundaryZhHans: "自动批准的调用可能不会到达 canUseTool；若检查必须覆盖每次调用，应使用 PreToolUse。allowed_tools 只会预先批准匹配项，并不限制所有未列工具；固定工具面需要适当组合 dontAsk、deny/工具移除配置、hooks 与 sandbox。权限策略不是操作系统隔离，bypass mode 需要另行受控的执行环境。",
  },
  "claude-secure-deployment": {
    supportsZhHans: "提示注入与模型错误威胁模型、最小权限、sandbox、网络与文件系统控制、凭据代理，以及审计轨迹。",
    boundaryZhHans: "这是纵深防御指引，不是对任何默认 SDK 配置在特定威胁模型下安全性的认证。",
  },
  "claude-sdk-observability": {
    supportsZhHans: "OpenTelemetry trace、metric、event、token 与成本信号、延迟、工具调用及失败。",
    boundaryZhHans: "部分 tracing 能力仍处于 Beta；telemetry 内容需要自己的脱敏、访问与保留策略。",
  },
  "anthropic-agent-evals": {
    supportsZhHans: "Task、trial、grader、trajectory、outcome、harness、suite、重复试验、校准后的 grader，以及 eval 驱动的开发。",
    boundaryZhHans: "离线 eval 是对生产监控、A/B test、用户反馈、事件分析与人工审查的补充，而不是替代。",
  },
  "anthropic-harness-long-running": {
    supportsZhHans: "渐进式长时工作、结构化进度产物、验证状态，以及跨 context window 的可靠恢复。",
    boundaryZhHans: "该文章描述的是一种工程方法，不能保证 harness 能消除模型漂移或未完成工作。",
  },
  "claude-cookbooks-patterns": {
    supportsZhHans: "版本锁定的最小实现，涵盖链式处理、路由、并行化、orchestrator-workers、evaluator-optimizer 与异步多智能体编排。",
    boundaryZhHans: "Cookbook 是教学示例而非生产运行时，本身不提供持久化状态、sandbox、权限或恢复机制。",
  },
  "anthropic-agent-sdk-v02143": {
    supportsZhHans: "固定版本 README 为 Python query loop、匹配工具预批准配置、hook、进程内 MCP 工具，以及该源码修订中记录的 programmatic subagent 与 session forking 提供可复现证据。",
    boundaryZhHans: "Release tag 只证明软件包版本；checkpoint 与 telemetry 语义须查各自的当前文档，MIT SDK 许可证也不许可托管模型服务或取代 Anthropic 条款。",
  },
  "microsoft-agent-framework": {
    supportsZhHans: "固定版本 README 直接记录面向图的顺序、并发、handoff、群组、checkpoint、time travel、人工审查与 telemetry 模式；Python 1.15.0 notes 另行支持该发布流中的 A2A 输入处理、MCP 参数过滤与名称遮蔽变更。",
    boundaryZhHans: "该仓库包含多种语言与组件的独立发布流；不能把某个组件 tag 表述为整个框架的版本。",
  },
  "github-aws-return-path-issue": {
    supportsZhHans: "一个具体的公开失败案例，说明 caller identity、task ID 与 return destination 应采用结构化字段，而不能从自然语言中推断。",
    boundaryZhHans: "该 issue 是范围有限的历史案例，不能证明当前项目仍有同一缺陷，也不能推广到所有编排器。",
  },
  "aws-idempotent-apis": {
    supportsZhHans: "由调用方提供的稳定 operation ID、语义等价性、去重，以及副作用已提交但响应丢失这一结果不明确的情形。",
    boundaryZhHans: "幂等性是服务与应用之间的契约，不是智能体自然获得的属性，也不等同于一个通用 request ID。",
  },
  "aws-backoff-jitter": {
    supportsZhHans: "带随机 jitter 的有限指数 backoff，用于降低同步重试造成的资源争用。",
    boundaryZhHans: "Backoff 只改变重试时序；它不能让不安全的写操作变得可重放，也不能替代重试预算与故障分类。",
  },
  "azure-retry-storm": {
    supportsZhHans: "遵守 Retry-After、避免多层 retry storm、采用有限 backoff，并在依赖持续失败时打开 circuit breaker。",
    boundaryZhHans: "Retry-After 与 circuit breaker 行为仍是依赖服务和应用的契约；它们不能让非幂等副作用变得可安全重放。",
  },
  "azure-compensating-transactions": {
    supportsZhHans: "对最终一致的多步骤工作流进行补偿，包括幂等 compensator，以及无法精确恢复先前状态的操作。",
    boundaryZhHans: "补偿不是原子 rollback；补偿本身也可能失败，不可逆副作用需要人工 reconciliation 路径。",
  },
  "azure-cosmos-distributed-lock": {
    supportsZhHans: "一个有界实现示例，组合原子锁获取、ETag 乐观并发控制、TTL 恢复、单调递增 fencing token，以及下游拒绝陈旧写入者。",
    boundaryZhHans: "这是 Azure Cosmos DB 示例，不是通用锁服务，也不能证明其他数据存储具有同样保证；正确性取决于已部署存储的原子性与一致性、下游强制检查及故障测试。",
  },
  "google-sre-error-budget": {
    supportsZhHans: "将 error budget 定义为 SLO 所隐含的可容许不可靠程度，并将其作为可靠性工作与发布决策的显式控制。",
    boundaryZhHans: "示例策略及其阈值并不通用；每项服务都必须定义面向用户的 SLI、SLO 时间窗口、责任归属与决策规则。",
  },
  "otel-overview": {
    supportsZhHans: "Span 的单一 parent identifier、零个或多个因果 links，以及 scatter/gather 由多个 span 发起时使用 links 而非 parent 的建议。",
    boundaryZhHans: "该规范定义遥测语义，不能证明所有分支都已正确埋点、采样、导出、保留，或被特定后端正确关联。",
  },
  "otel-baggage-security": {
    supportsZhHans: "官方指南说明：敏感 Baggage 可能通过 HTTP headers 传播到非预期资源（包括第三方 API），且 Baggage 没有内建完整性检查。",
    boundaryZhHans: "这是当前解释性指南，而非带版本的规范性标准。Baggage 中不得放入 secrets 或未最小化的个人数据，也绝不能把 Baggage 当作可信授权输入。",
  },
  "oracle-critical-path": {
    supportsZhHans: "将最长路径定义为决定项目结束日期的一系列驱动活动，并明确指出约束或资源平衡可能打破这种由依赖关系驱动的最长路径。",
    boundaryZhHans: "这是 Oracle Primavera 的官方调度文档，不能证明某一厂商算法可以解决任意资源受限的智能体调度；课程中的加权 DAG 与 makespan 表述仍是有边界的工程综合。",
  },
  "etcd-quorum-glossary": {
    supportsZhHans: "etcd v3.7 将 quorum 定义为修改集群状态并达成共识所需的活跃成员数量，并要求成员多数才能达到 quorum。",
    boundaryZhHans: "这是 etcd/Raft 产品定义，不是任意 k-of-n 应用汇合规则、答案真值多数票的通用同义词，也不是对共识成员关系与 quorum 交集证明的完整论述。",
  },
  "langgraph-v1211": {
    supportsZhHans: "固定版本 README 直接把 LangGraph 描述为有状态编排运行时，并记录持久化执行、human-in-the-loop 控制，以及短期与长期 memory 等开源能力。",
    boundaryZhHans: "1.2.11 release 页面只作为版本锚点；开源运行时与商业 LangSmith 服务相互独立，core、checkpoint 与 SDK 发布流不得混为一谈。",
  },
  "google-adk-v271": {
    supportsZhHans: "当前官方 ADK 文档支持 graph、dynamic、collaborative 与 template workflow，分支、顺序、循环与并行执行，协作控制权转移及 session state；另有独立 release 锚点标识 Python v2.7.1 及其 commit。",
    boundaryZhHans: "v2.7.1 release 页面只证明版本及其中列出的两项修复，不证明上述完整特性；claim evidence 是滚动文档，部署前必须针对实际软件包重新核对并测试 2.x 行为。",
  },
  "autogen-maintenance": {
    supportsZhHans: "生命周期证据表明 AutoGen 已进入维护模式，且 Microsoft 建议新项目采用 Microsoft Agent Framework。",
    boundaryZhHans: "AutoGen 仍是有价值的历史先例；维护状态不能证明每个现有 AutoGen 部署都应立即重写。",
  },
} as const satisfies Record<
  AgentOrchestrationSourceId,
  { readonly supportsZhHans: string; readonly boundaryZhHans: string }
>;

function sourceLayer(
  source: AgentOrchestrationSourceCore,
): AgentOrchestrationSourceLayer {
  if (source.kind === "open-standard") return "normative-standard";
  if (source.kind === "official-sdk-docs") return "sdk-or-framework";
  if (source.kind === "claude-academy") return "engineering-guidance";
  if (ENGINEERING_GUIDANCE_SOURCE_IDS.has(source.id)) return "engineering-guidance";
  if (source.kind === "engineering-official") return "engineering-guidance";
  if (source.kind === "official-github") return "repository-evidence";
  if (source.kind === "community-github-case") return "bounded-case-study";
  if (
    source.publisher.includes("SDK")
    || source.id.includes("sdk-")
    || source.id.includes("agents-python")
  ) {
    return "sdk-or-framework";
  }
  return "product-documentation";
}

function sourceReuseStatus(
  source: AgentOrchestrationSourceCore,
): AgentOrchestrationSourceReuseStatus {
  if (source.license) return "license-noted-no-copy";
  return "link-and-paraphrase-only";
}

function sourceClaimEvidenceUrls(
  source: AgentOrchestrationSourceCore,
): readonly [string, ...string[]] {
  return source.claimEvidenceUrls ?? [source.url];
}

function sourceTransformation(source: AgentOrchestrationSourceCore): string {
  if (source.kind === "open-standard") {
    return "Version-bounded normative facts were extracted and paraphrased with a direct link; no specification prose, schema, code, or media was copied.";
  }
  if (source.kind === "official-github") {
    if (source.id === "google-adk-v271") {
      return "The release tag was retained only as a version anchor while behavior claims were paraphrased from separately linked current official documentation; no repository code, prose, screenshot, or diagram was copied.";
    }
    return "Only a release-, commit-, or lifecycle-bounded claim was paraphrased; no repository code, prose, screenshot, or diagram was copied.";
  }
  if (source.kind === "community-github-case") {
    return "The record is used only as a bounded failure case; no issue prose or media was copied and no present-tense defect is inferred.";
  }
  return "The supported claim was paraphrased within its stated boundary and linked to the source; no source layout, long-form prose, code, or media was copied.";
}

export const AGENT_ORCHESTRATION_SOURCES =
  AGENT_ORCHESTRATION_SOURCE_CORES.map(
    (source): AgentOrchestrationSourceRecord => ({
      ...source,
      claimEvidenceUrls: sourceClaimEvidenceUrls(source),
      layer: sourceLayer(source),
      reuseStatus: sourceReuseStatus(source),
      transformation: sourceTransformation(source),
      ...SOURCE_ZH_HANS[source.id],
    }),
  );

const SOURCE_BY_ID = new Map<string, AgentOrchestrationSourceRecord>(
  AGENT_ORCHESTRATION_SOURCES.map(
    (source): [string, AgentOrchestrationSourceRecord] => [source.id, source],
  ),
);

export function getAgentOrchestrationSource(
  id: string,
): AgentOrchestrationSourceRecord {
  const source = SOURCE_BY_ID.get(id);
  if (!source) throw new Error(`Unknown agent-orchestration source: ${id}`);
  return source;
}
