import type { CreatorOpsSourceRecord } from "./types";

const ACCESSED_ON = "2026-08-26";

/**
 * Course 16 links to repositories as inspectable implementation evidence.
 * No repository prose, screenshots, logos, sample media, or code is copied.
 * A PASS applies only to the bounded classroom use described here; model,
 * media, plugin, target-site, and deployment rights remain separate checks.
 */
export const CREATOR_OPS_SOURCES = [
  {
    id: "openai-agents",
    repository: "openai/openai-agents-python",
    publisher: "OpenAI",
    url: "https://github.com/openai/openai-agents-python",
    revision: "5f9f4f09c3fe840b5a4c09bdbbf6f0b1239bf0ec",
    committedAt: "2026-08-25T07:11:24Z",
    licenseUrl: "https://github.com/openai/openai-agents-python/blob/5f9f4f09c3fe840b5a4c09bdbbf6f0b1239bf0ec/LICENSE",
    license: "MIT",
    decision: "conditional",
    role: "core-runtime",
    accessedOn: ACCESSED_ON,
    snapshot: "v0.22.0 visible on 2026-08-26; recheck before implementation",
    supports: {
      en: "A compact code track for agents, tools, handoffs, guardrails, human approval, and traces.",
      "zh-Hans": "用于智能体、工具、交接、护栏、人工审批与追踪的轻量代码主线。",
    },
    boundary: {
      en: "The SDK does not define an editorial strategy, grant platform authority, or make model output publishable; API access and costs are separate.",
      "zh-Hans": "SDK 不会替你定义编辑策略、授予平台权限或使模型输出自动可发布；API 访问与费用是另一层合同。",
    },
  },
  {
    id: "langgraph",
    repository: "langchain-ai/langgraph",
    publisher: "LangChain",
    url: "https://github.com/langchain-ai/langgraph",
    revision: "38031739e551638e373fb553453256c23feeb41f",
    committedAt: "2026-08-24T21:42:27Z",
    licenseUrl: "https://github.com/langchain-ai/langgraph/blob/38031739e551638e373fb553453256c23feeb41f/LICENSE",
    license: "MIT",
    decision: "pass",
    role: "core-runtime",
    accessedOn: ACCESSED_ON,
    snapshot: "Pinned tree and latest reviewed core release are both v1.2.11 (2026-08-11); use as the advanced stateful track",
    supports: {
      en: "Stateful graphs, checkpoints, durable execution, and human-in-the-loop control for long editorial workflows.",
      "zh-Hans": "为长链路编辑工作流提供状态图、检查点、耐久执行与人在回路控制。",
    },
    boundary: {
      en: "It is an advanced alternative to the Agents SDK, not a second mandatory runtime; persistence and deployment choices still need design and testing.",
      "zh-Hans": "它是 Agents SDK 的进阶替代路径，而不是第二条强制主线；持久化与部署仍需单独设计和测试。",
    },
  },
  {
    id: "open-deep-research",
    repository: "langchain-ai/open_deep_research",
    publisher: "LangChain",
    url: "https://github.com/langchain-ai/open_deep_research",
    revision: "1b7d2e80db9faa586165c60e09096dbbfd483a64",
    committedAt: "2026-08-10T18:13:29Z",
    licenseUrl: "https://github.com/langchain-ai/open_deep_research/blob/1b7d2e80db9faa586165c60e09096dbbfd483a64/LICENSE",
    license: "MIT",
    decision: "pass",
    role: "research-input",
    accessedOn: ACCESSED_ON,
    snapshot: "Archived by its owner after the pinned 2026-08-10 commit; use only as a static reference architecture",
    supports: {
      en: "An inspectable reference architecture for configurable search, research synthesis, MCP connections, and evaluation.",
      "zh-Hans": "为可配置搜索、研究综合、MCP 连接与评测提供可检查的参考架构。",
    },
    boundary: {
      en: "The repository is archived and carries no ongoing-maintenance expectation. Its answer is a research draft, not a verified fact set; every consequential claim still needs source-level review.",
      "zh-Hans": "该仓库已归档，不应期待持续维护。其答案只是研究草稿，并非已核事实集；所有关键主张仍须回到来源逐条复核。",
    },
  },
  {
    id: "crawl4ai",
    repository: "unclecode/crawl4ai",
    publisher: "Crawl4AI maintainers",
    url: "https://github.com/unclecode/crawl4ai",
    revision: "7e801521428ee12509994d39151006f64055ebe3",
    committedAt: "2026-07-15T08:24:13Z",
    licenseUrl: "https://github.com/unclecode/crawl4ai/blob/7e801521428ee12509994d39151006f64055ebe3/LICENSE",
    license: "Apache-2.0 text with an additional mandatory prominent-attribution condition",
    decision: "conditional",
    role: "research-input",
    accessedOn: ACCESSED_ON,
    snapshot: "v0.9.2 visible in July 2026; the extra attribution condition and target permissions require separate review",
    supports: {
      en: "Turning authorized web pages into structured, LLM-ready Markdown for a research packet.",
      "zh-Hans": "把已获授权的网页转换为结构化、适合模型处理的 Markdown 研究材料。",
    },
    boundary: {
      en: "A crawler's technical ability is not permission; respect robots, rate limits, copyright, privacy, and the target's current terms.",
      "zh-Hans": "能抓取不等于获授权；必须遵守 robots、频率限制、版权、隐私及目标站点的当前条款。",
    },
  },
  {
    id: "rsshub",
    repository: "DIYgod/RSSHub",
    publisher: "RSSHub community",
    url: "https://github.com/DIYgod/RSSHub",
    revision: "1afe42be27c7e95a641d59a89c97aa2d8f902655",
    committedAt: "2026-08-25T17:00:58Z",
    licenseUrl: "https://github.com/DIYgod/RSSHub/blob/1afe42be27c7e95a641d59a89c97aa2d8f902655/LICENSE",
    license: "AGPL-3.0",
    decision: "conditional",
    role: "research-input",
    accessedOn: ACCESSED_ON,
    snapshot: "No formal release contract; route behavior and upstream policy are version-sensitive",
    supports: {
      en: "A feed layer for official RSS, open APIs, and sources the learner owns or is authorized to monitor.",
      "zh-Hans": "把官方 RSS、开放 API、自有或获授权来源汇入统一信号流。",
    },
    boundary: {
      en: "Use only authorized routes in the core lab; social-platform routes can fail or conflict with terms, and network deployment triggers AGPL duties.",
      "zh-Hans": "核心实验仅用获授权路由；社交平台路由可能失效或与条款冲突，网络部署还会触发 AGPL 义务。",
    },
  },
  {
    id: "trendradar",
    repository: "sansan0/TrendRadar",
    publisher: "TrendRadar maintainers",
    url: "https://github.com/sansan0/TrendRadar",
    revision: "8ee26026ba6c11dec41a95fb3895a7162876caa1",
    committedAt: "2026-07-17T13:53:35Z",
    licenseUrl: "https://github.com/sansan0/TrendRadar/blob/8ee26026ba6c11dec41a95fb3895a7162876caa1/LICENSE",
    license: "GPL-3.0",
    decision: "conditional",
    role: "research-input",
    accessedOn: ACCESSED_ON,
    snapshot: "README changelog and v6.x labels visible; no GitHub release contract",
    supports: {
      en: "A practical comparison case for filtering many trend signals and producing a reviewable digest.",
      "zh-Hans": "用于比较如何过滤大量热点信号并生成可审阅摘要。",
    },
    boundary: {
      en: "A hot list or AI digest is a lead, not a fact or audience need; frequency, source permission, and every claim require review.",
      "zh-Hans": "热榜或 AI 摘要只是线索，不是事实或受众需求；频率、来源授权与每项主张都要复核。",
    },
  },
  {
    id: "markitdown",
    repository: "microsoft/markitdown",
    publisher: "Microsoft",
    url: "https://github.com/microsoft/markitdown",
    revision: "9dc0d6579b8739c9d0671ff205e071e3053c7df1",
    committedAt: "2026-08-19T19:34:00Z",
    licenseUrl: "https://github.com/microsoft/markitdown/blob/9dc0d6579b8739c9d0671ff205e071e3053c7df1/LICENSE",
    license: "MIT",
    decision: "conditional",
    role: "research-input",
    accessedOn: ACCESSED_ON,
    snapshot: "Latest reviewed stable release was v0.1.7 on 2026-07-29; pinned repository tree reviewed on 2026-08-26",
    supports: {
      en: "Converting owned PDF, Office, HTML, image, and audio inputs into Markdown; the course records provenance fields separately.",
      "zh-Hans": "把自有 PDF、Office、HTML、图片与音频输入转为 Markdown；出处字段由课程来源登记表另行记录。",
    },
    boundary: {
      en: "Conversion does not prove extraction accuracy or grant reuse rights; compare critical fields with the original file.",
      "zh-Hans": "格式转换不证明抽取准确，也不授予再利用权；关键字段必须对照原文件。",
    },
  },
  {
    id: "activepieces",
    repository: "activepieces/activepieces",
    publisher: "Activepieces",
    url: "https://github.com/activepieces/activepieces",
    revision: "eb33135e7442c9d5463ed57aadd015ff9fc3c79d",
    committedAt: "2026-08-25T18:13:17Z",
    licenseUrl: "https://github.com/activepieces/activepieces/blob/eb33135e7442c9d5463ed57aadd015ff9fc3c79d/LICENSE",
    additionalLicenseUrls: [
      "https://github.com/activepieces/activepieces/blob/eb33135e7442c9d5463ed57aadd015ff9fc3c79d/packages/ee/LICENSE",
    ],
    license: "MIT Community Edition; commercial terms for enterprise code",
    decision: "pass",
    role: "core-runtime",
    accessedOn: ACCESSED_ON,
    snapshot: "Community Edition boundary reviewed on 2026-08-26",
    supports: {
      en: "A visual workflow track for versioned automations, approval steps, and official integrations without making code mandatory.",
      "zh-Hans": "为版本化自动化、审批步骤与官方集成提供无需强制编程的可视化路径。",
    },
    boundary: {
      en: "The PASS covers Community Edition only; enterprise folders, hosted features, connector permissions, and downstream API terms are separate.",
      "zh-Hans": "PASS 仅覆盖社区版；企业目录、托管功能、连接器权限及下游 API 条款需要另审。",
    },
  },
  {
    id: "prefect",
    repository: "PrefectHQ/prefect",
    publisher: "Prefect",
    url: "https://github.com/PrefectHQ/prefect",
    revision: "57ee2c2c10f662fee32807c126a117adce32dd28",
    committedAt: "2026-08-25T17:15:00Z",
    licenseUrl: "https://github.com/PrefectHQ/prefect/blob/57ee2c2c10f662fee32807c126a117adce32dd28/LICENSE",
    license: "Apache-2.0",
    decision: "pass",
    role: "core-runtime",
    accessedOn: ACCESSED_ON,
    snapshot: "Pinned tree is the v3.8.4 release commit (2026-08-25); pin worker permissions and tested integrations",
    supports: {
      en: "Schedules, retries, state transitions, and recovery for a deterministic production track.",
      "zh-Hans": "为确定性生产路径提供调度、重试、状态转换与故障恢复。",
    },
    boundary: {
      en: "Scheduling a job does not make an action safe or idempotent; external side effects need approval and reconciliation contracts.",
      "zh-Hans": "排程不会让动作自动安全或幂等；外部副作用需要审批与对账合同。",
    },
  },
  {
    id: "playwright",
    repository: "microsoft/playwright",
    publisher: "Microsoft",
    url: "https://github.com/microsoft/playwright",
    revision: "036533f7f3c14b1d5b3359d69f0464ceba540334",
    committedAt: "2026-08-25T18:25:58Z",
    licenseUrl: "https://github.com/microsoft/playwright/blob/036533f7f3c14b1d5b3359d69f0464ceba540334/LICENSE",
    license: "Apache-2.0",
    decision: "pass",
    role: "distribution",
    accessedOn: ACCESSED_ON,
    snapshot: "Pinned tree reports 1.63.0-next; latest reviewed stable release was v1.62.1 on 2026-07-30; pin the tested version",
    supports: {
      en: "Deterministic browser tests for learner-owned preview pages, approval forms, and published-link verification.",
      "zh-Hans": "对学员自有预览页、审批表单与已发布链接进行确定性浏览器测试。",
    },
    boundary: {
      en: "Use it for testing owned or explicitly authorized surfaces, not to evade platform controls or automate unapproved account actions.",
      "zh-Hans": "仅用于自有或明确授权界面测试，不得绕过平台控制或自动执行未经批准的账号动作。",
    },
  },
  {
    id: "browser-use",
    repository: "browser-use/browser-use",
    publisher: "Browser Use",
    url: "https://github.com/browser-use/browser-use",
    revision: "9a2db2d2db42c6f68a871f011b3b25fdcaa71847",
    committedAt: "2026-08-24T21:37:36Z",
    licenseUrl: "https://github.com/browser-use/browser-use/blob/9a2db2d2db42c6f68a871f011b3b25fdcaa71847/LICENSE",
    license: "MIT",
    decision: "conditional",
    role: "distribution",
    accessedOn: ACCESSED_ON,
    snapshot: "Pinned tree and latest reviewed stable release are both 0.13.8 (2026-08-16); pin the exact tested tag or commit",
    supports: {
      en: "A contrast case for agent-driven browser tasks when APIs are absent and the target is owned or explicitly authorized.",
      "zh-Hans": "用于比较无 API 且目标界面自有或明确授权时的智能体浏览器任务。",
    },
    boundary: {
      en: "The lab forbids CAPTCHA bypass, stealth proxies, login-state reuse, bulk posting, and third-party targets without written authority.",
      "zh-Hans": "实验禁止绕过验证码、隐身代理、复用登录态、批量发帖以及在无书面授权时操作第三方目标。",
    },
  },
  {
    id: "comfyui",
    repository: "Comfy-Org/ComfyUI",
    publisher: "Comfy Org",
    url: "https://github.com/Comfy-Org/ComfyUI",
    revision: "7d9d0c391b90b3d89c2ec880a870bb34236a417c",
    committedAt: "2026-08-25T19:40:46Z",
    licenseUrl: "https://github.com/Comfy-Org/ComfyUI/blob/7d9d0c391b90b3d89c2ec880a870bb34236a417c/LICENSE",
    license: "GPL-3.0",
    decision: "conditional",
    role: "production",
    accessedOn: ACCESSED_ON,
    snapshot: "Pinned tree reports 0.33.0; latest reviewed stable release was v0.34.0 on 2026-08-26; retain the >=0.30.0 security floor",
    supports: {
      en: "A node graph for reproducible image and video generation with visible parameters and rerunnable workflows.",
      "zh-Hans": "以可见参数和可重复运行工作流构建可复现的图像与视频生成节点图。",
    },
    boundary: {
      en: "ComfyUI's GPL does not cover every model, LoRA, custom node, style, face, or training asset; each dependency and output needs rights review.",
      "zh-Hans": "ComfyUI 的 GPL 不覆盖所有模型、LoRA、自定义节点、风格、肖像或训练素材；每项依赖和输出都要审权。",
    },
  },
  {
    id: "diffusers",
    repository: "huggingface/diffusers",
    publisher: "Hugging Face",
    url: "https://github.com/huggingface/diffusers",
    revision: "c969cf2f7ec56f0292c35bece674d170c8f9daa5",
    committedAt: "2026-08-25T17:27:18Z",
    licenseUrl: "https://github.com/huggingface/diffusers/blob/c969cf2f7ec56f0292c35bece674d170c8f9daa5/LICENSE",
    license: "Apache-2.0",
    decision: "pass",
    role: "production",
    accessedOn: ACCESSED_ON,
    snapshot: "v0.40.0 visible on 2026-08-20",
    supports: {
      en: "A code-level pipeline abstraction for reproducible image, video, and audio generation experiments.",
      "zh-Hans": "为可复现图像、视频与音频生成实验提供代码级流水线抽象。",
    },
    boundary: {
      en: "Library licensing is separate from every downloaded model and output-use policy; a model card must be attached to the asset receipt.",
      "zh-Hans": "库许可证与每个下载模型及输出使用政策相互独立；资产回执必须附模型卡。",
    },
  },
  {
    id: "whisper",
    repository: "openai/whisper",
    publisher: "OpenAI",
    url: "https://github.com/openai/whisper",
    revision: "5f86d1d86363843179951550570367b37c5d6f78",
    committedAt: "2026-07-28T20:18:29Z",
    licenseUrl: "https://github.com/openai/whisper/blob/5f86d1d86363843179951550570367b37c5d6f78/LICENSE",
    license: "MIT (code and published model weights)",
    decision: "pass",
    role: "production",
    accessedOn: ACCESSED_ON,
    snapshot: "v20250625 visible; repository activity reviewed on 2026-08-26",
    supports: {
      en: "Local transcription and subtitle drafts for media the learner owns or is authorized to process.",
      "zh-Hans": "为学员自有或获授权音视频生成本地转写与字幕草稿。",
    },
    boundary: {
      en: "Transcripts can omit, hallucinate, or mis-time words; people, names, numbers, quotations, and consent require human verification.",
      "zh-Hans": "转写可能遗漏、臆造或错配时间；人物、姓名、数字、引语与同意状态必须人工核验。",
    },
  },
  {
    id: "cosyvoice",
    repository: "QwenAudio/CosyVoice",
    publisher: "QwenAudio",
    url: "https://github.com/QwenAudio/CosyVoice",
    revision: "074ca6dc9e80a2f424f1f74b48bdd7d3fea531cc",
    committedAt: "2026-05-25T18:15:40Z",
    licenseUrl: "https://github.com/QwenAudio/CosyVoice/blob/074ca6dc9e80a2f424f1f74b48bdd7d3fea531cc/LICENSE",
    license: "Apache-2.0 code; model and voice rights require separate review",
    decision: "conditional",
    role: "production",
    accessedOn: ACCESSED_ON,
    snapshot: "Repository reviewed on 2026-08-26",
    supports: {
      en: "A Chinese, Cantonese, and multilingual TTS option for an explicitly consented synthetic voice track.",
      "zh-Hans": "为已明确同意的合成音轨提供中文、粤语与多语种 TTS 选项。",
    },
    boundary: {
      en: "Do not clone or imitate a real person's voice without explicit documented consent; inspect every model and voice license separately.",
      "zh-Hans": "没有明确、可记录的同意不得克隆或模仿真人声音；每个模型与音色许可证都要单独检查。",
    },
  },
  {
    id: "ffmpeg",
    repository: "FFmpeg/FFmpeg",
    publisher: "FFmpeg project",
    url: "https://github.com/FFmpeg/FFmpeg",
    revision: "a1050d48b0df3f7c3fa1c631ec8e82528b3f7c85",
    committedAt: "2026-08-25T16:10:16Z",
    licenseUrl: "https://github.com/FFmpeg/FFmpeg/blob/a1050d48b0df3f7c3fa1c631ec8e82528b3f7c85/LICENSE.md",
    license: "LGPL-2.1+ by default; build options can change obligations",
    decision: "conditional",
    role: "production",
    accessedOn: ACCESSED_ON,
    snapshot: "Main repository reviewed on 2026-08-26; record the actual build configuration",
    supports: {
      en: "Deterministic transcoding, subtitles, mixing, resizing, and packaging for reusable content assets.",
      "zh-Hans": "为可复用内容资产提供确定性转码、字幕、混音、缩放与封装。",
    },
    boundary: {
      en: "Enabled GPL or non-free components can alter distribution rights, and FFmpeg does not grant rights to the media being processed.",
      "zh-Hans": "启用 GPL 或非自由组件会改变分发义务，FFmpeg 也不会授予被处理媒体的权利。",
    },
  },
  {
    id: "mixpost",
    repository: "inovector/mixpost",
    publisher: "Inovector",
    url: "https://github.com/inovector/mixpost",
    revision: "df57648b866310446703f5294350552b62735df5",
    committedAt: "2026-03-16T10:06:37Z",
    licenseUrl: "https://github.com/inovector/mixpost/blob/df57648b866310446703f5294350552b62735df5/LICENSE.md",
    license: "MIT for the Lite repository",
    decision: "pass",
    role: "distribution",
    accessedOn: ACCESSED_ON,
    snapshot: "Lite v2.6.0 visible in March 2026; verify connectors before use",
    supports: {
      en: "An inspectable self-hosted calendar and official-connector distribution reference for approved content.",
      "zh-Hans": "为已审批内容提供可检查的自托管日历与官方连接器分发参考。",
    },
    boundary: {
      en: "Each platform connector, token scope, quota, content rule, and app-review requirement remains governed by that platform's current terms.",
      "zh-Hans": "每个平台连接器、令牌权限、配额、内容规则与应用审核仍受该平台当前条款约束。",
    },
  },
  {
    id: "umami",
    repository: "umami-software/umami",
    publisher: "Umami Software",
    url: "https://github.com/umami-software/umami",
    revision: "ca661c7057984aa98ed4f7083d84dae2f65bfcb0",
    committedAt: "2026-08-20T17:38:48Z",
    licenseUrl: "https://github.com/umami-software/umami/blob/ca661c7057984aa98ed4f7083d84dae2f65bfcb0/LICENSE",
    license: "MIT",
    decision: "pass",
    role: "measurement",
    accessedOn: ACCESSED_ON,
    snapshot: "Pinned tree and latest reviewed stable release are both v3.3.1 (2026-08-20)",
    supports: {
      en: "Privacy-conscious first-party page, event, funnel, and campaign measurement for owned destinations.",
      "zh-Hans": "在自有落地页上进行重视隐私的第一方页面、事件、漏斗与活动测量。",
    },
    boundary: {
      en: "Analytics is observational; attribution windows, bots, consent rules, missing events, and channel changes limit causal conclusions.",
      "zh-Hans": "分析数据是观察性的；归因窗口、机器人、同意规则、漏事件与渠道变化都会限制因果结论。",
    },
  },
  {
    id: "langfuse",
    repository: "langfuse/langfuse",
    publisher: "Langfuse",
    url: "https://github.com/langfuse/langfuse",
    revision: "27807e9c241b1cde7c37fe4648205430259a0c91",
    committedAt: "2026-08-25T16:23:32Z",
    licenseUrl: "https://github.com/langfuse/langfuse/blob/27807e9c241b1cde7c37fe4648205430259a0c91/LICENSE",
    additionalLicenseUrls: [
      "https://github.com/langfuse/langfuse/blob/27807e9c241b1cde7c37fe4648205430259a0c91/ee/LICENSE",
    ],
    license: "MIT core with separately licensed enterprise directory",
    decision: "conditional",
    role: "measurement",
    accessedOn: ACCESSED_ON,
    snapshot: "Pinned tree reports 4.19.0; latest reviewed stable release was v4.21.0 on 2026-08-26; core and enterprise licenses remain split",
    supports: {
      en: "Traces, costs, datasets, experiments, and human scores for the editorial agent pipeline.",
      "zh-Hans": "为编辑智能体流水线记录追踪、成本、数据集、实验与人工评分。",
    },
    boundary: {
      en: "Instrumentation can miss steps and may contain sensitive prompts or audience data; sampling, retention, redaction, and license scope need policy.",
      "zh-Hans": "埋点可能漏步骤并含敏感提示或受众数据；采样、保留、脱敏与许可范围都要制定政策。",
    },
  },
  {
    id: "promptfoo",
    repository: "promptfoo/promptfoo",
    publisher: "Promptfoo",
    url: "https://github.com/promptfoo/promptfoo",
    revision: "0170037970dd4732f7542c60ceafa5f4951289de",
    committedAt: "2026-08-25T06:07:45Z",
    licenseUrl: "https://github.com/promptfoo/promptfoo/blob/0170037970dd4732f7542c60ceafa5f4951289de/LICENSE",
    license: "MIT for the open-source project; inspect enterprise additions",
    decision: "pass",
    role: "assurance",
    accessedOn: ACCESSED_ON,
    snapshot: "Pinned package version 0.122.0; the 0.122.0 release was visible on 2026-08-04",
    supports: {
      en: "Versioned quality checks and adversarial cases for prompts, agents, brand voice, factuality, and unsafe publish requests.",
      "zh-Hans": "为提示、智能体、品牌语气、事实性与不安全发布请求建立版本化质量与对抗测试。",
    },
    boundary: {
      en: "Configs and referenced scripts can execute with local permissions; treat them as trusted code and isolate untrusted eval inputs.",
      "zh-Hans": "配置及引用脚本可能以本地权限执行；应把它们视为受信代码，并隔离不可信评测输入。",
    },
  },
  {
    id: "nemoguardrails",
    repository: "NVIDIA-NeMo/Guardrails",
    publisher: "NVIDIA",
    url: "https://github.com/NVIDIA-NeMo/Guardrails",
    revision: "3524afa8a68f4f51506429d3009400c3bb8d2949",
    committedAt: "2026-08-25T01:09:47Z",
    licenseUrl: "https://github.com/NVIDIA-NeMo/Guardrails/blob/3524afa8a68f4f51506429d3009400c3bb8d2949/LICENSE.md",
    license: "Apache-2.0",
    decision: "pass",
    role: "assurance",
    accessedOn: ACCESSED_ON,
    snapshot: "Pinned tree reports 0.24.0.dev0; latest reviewed stable line was 0.23.0 in July 2026",
    supports: {
      en: "Input, output, retrieval, and tool-call rails as one layer in an editorial safety case.",
      "zh-Hans": "把输入、输出、检索与工具调用 rails 作为编辑安全论证的一层。",
    },
    boundary: {
      en: "A rail is fallible software, not a policy waiver; human review, permissions, evals, logging, and incident response remain necessary.",
      "zh-Hans": "rail 是会失效的软件，不是政策豁免；人工复核、权限、评测、日志与事件响应仍然必要。",
    },
  },
  {
    id: "c2pa-rs",
    repository: "contentauth/c2pa-rs",
    publisher: "Content Authenticity Initiative",
    url: "https://github.com/contentauth/c2pa-rs",
    revision: "7132161cdb0dbb01f01ae0563d5926214c9044db",
    committedAt: "2026-08-25T19:25:32Z",
    licenseUrl: "https://github.com/contentauth/c2pa-rs/blob/7132161cdb0dbb01f01ae0563d5926214c9044db/LICENSE-MIT",
    additionalLicenseUrls: [
      "https://github.com/contentauth/c2pa-rs/blob/7132161cdb0dbb01f01ae0563d5926214c9044db/LICENSE-APACHE",
    ],
    license: "MIT OR Apache-2.0",
    decision: "pass",
    role: "assurance",
    accessedOn: ACCESSED_ON,
    snapshot: "Pinned c2patool CLI reports 0.28.0-dev while the root c2pa crate reports 0.91.0-dev; latest reviewed c2patool stable release was v0.27.15 on 2026-08-13",
    supports: {
      en: "Writing and verifying Content Credentials so an asset receipt can carry provenance and edit history.",
      "zh-Hans": "写入与验证 Content Credentials，使资产回执能够携带出处与编辑历史。",
    },
    boundary: {
      en: "A valid manifest reports signed assertions; it does not prove that the depicted event is true or that every right was cleared.",
      "zh-Hans": "有效清单只证明签名声明的完整性；它不证明画面事件真实，也不证明所有权利已清理。",
    },
  },
  {
    id: "scancode",
    repository: "aboutcode-org/scancode-toolkit",
    publisher: "AboutCode",
    url: "https://github.com/aboutcode-org/scancode-toolkit",
    revision: "3c532f0fa89113c4aae0301664f17293562aeedb",
    committedAt: "2026-08-07T21:53:50Z",
    licenseUrl: "https://github.com/aboutcode-org/scancode-toolkit/blob/3c532f0fa89113c4aae0301664f17293562aeedb/apache-2.0.LICENSE",
    additionalLicenseUrls: [
      "https://github.com/aboutcode-org/scancode-toolkit/blob/3c532f0fa89113c4aae0301664f17293562aeedb/cc-by-4.0.LICENSE",
    ],
    license: "Apache-2.0 code; reference data includes CC-BY-4.0",
    decision: "pass",
    role: "assurance",
    accessedOn: ACCESSED_ON,
    snapshot: "Pinned tree reports 33.0.0rc1; latest reviewed stable release was v32.5.0 in January 2026",
    supports: {
      en: "Scanning code packages for license, copyright, dependency, and SBOM signals before adopting a creator tool.",
      "zh-Hans": "采用创作者工具前扫描代码包的许可证、版权、依赖与 SBOM 信号。",
    },
    boundary: {
      en: "A scan is triage, not legal advice or proof of rights; unclear findings, media, models, plugins, and services require separate review.",
      "zh-Hans": "扫描只是分诊，不是法律意见或权利证明；不明确结果、媒体、模型、插件与服务仍须另审。",
    },
  },
  {
    id: "n8n-case",
    repository: "n8n-io/n8n",
    publisher: "n8n",
    url: "https://github.com/n8n-io/n8n",
    revision: "e0c5edc84e784efa14459a2e1b03b223160ed951",
    committedAt: "2026-08-25T15:52:57Z",
    licenseUrl: "https://github.com/n8n-io/n8n/blob/e0c5edc84e784efa14459a2e1b03b223160ed951/LICENSE.md",
    license: "Sustainable Use License and Enterprise License",
    decision: "excluded",
    role: "license-case",
    accessedOn: ACCESSED_ON,
    snapshot: "Source-available license reviewed on 2026-08-26",
    supports: {
      en: "A licensing case showing why visible source and popularity do not equal permission to redistribute, white-label, or build a competing service.",
      "zh-Hans": "用于说明源代码可见和高热度不等于获准再分发、白标或建立竞争服务。",
    },
    boundary: {
      en: "Excluded from the runnable course stack; learners may use the official product separately only under its current license and service terms.",
      "zh-Hans": "不进入课程可运行技术栈；学员仅可在当前许可证与服务条款下另行使用官方产品。",
    },
  },
  {
    id: "dify-case",
    repository: "langgenius/dify",
    publisher: "LangGenius",
    url: "https://github.com/langgenius/dify",
    revision: "c7520d7c71031dfa5764d966a523c5766abdc2d6",
    committedAt: "2026-08-25T13:10:06Z",
    licenseUrl: "https://github.com/langgenius/dify/blob/c7520d7c71031dfa5764d966a523c5766abdc2d6/LICENSE",
    license: "Dify Open Source License (Apache-2.0 with additional conditions)",
    decision: "excluded",
    role: "license-case",
    accessedOn: ACCESSED_ON,
    snapshot: "Additional logo and multi-tenant conditions reviewed on 2026-08-26",
    supports: {
      en: "A case for separating low-code capability from white-label, multi-tenant, and branding rights.",
      "zh-Hans": "用于区分低代码能力与白标、多租户及品牌修改权。",
    },
    boundary: {
      en: "Not used as the course platform or packaged lab; consult the current license before any deployment or branding change.",
      "zh-Hans": "不作为课程平台或打包实验；任何部署或品牌修改前都要检查当前许可证。",
    },
  },
  {
    id: "moneyprinter-case",
    repository: "harry0703/MoneyPrinterTurbo",
    publisher: "MoneyPrinterTurbo maintainers",
    url: "https://github.com/harry0703/MoneyPrinterTurbo",
    revision: "6cd36b5a2c56b49b24621463038e4db3963f0a43",
    committedAt: "2026-08-25T10:01:38Z",
    licenseUrl: "https://github.com/harry0703/MoneyPrinterTurbo/blob/6cd36b5a2c56b49b24621463038e4db3963f0a43/LICENSE",
    license: "MIT code; bundled media and upload services have separate rights",
    decision: "excluded",
    role: "license-case",
    accessedOn: ACCESSED_ON,
    snapshot: "v1.3.5 visible on 2026-08-22",
    supports: {
      en: "A case for decomposing one-click video generation into script, rights-cleared assets, rendering, review, and authorized publishing stages.",
      "zh-Hans": "用于把一键视频生成拆成脚本、权利清晰素材、渲染、复核与授权发布阶段。",
    },
    boundary: {
      en: "Excluded from hands-on use because default music provenance and third-party auto-upload paths do not meet this course's release standard.",
      "zh-Hans": "因默认音乐出处及第三方自动上传路径不满足本课程发布标准，不进入动手实验。",
    },
  },
  {
    id: "mediacrawler-case",
    repository: "NanmiCoder/MediaCrawler",
    publisher: "MediaCrawler maintainers",
    url: "https://github.com/NanmiCoder/MediaCrawler",
    revision: "d6f7c5bb906b6dac40ddf343ef9e26438a3de092",
    committedAt: "2026-08-14T08:18:52Z",
    licenseUrl: "https://github.com/NanmiCoder/MediaCrawler/blob/d6f7c5bb906b6dac40ddf343ef9e26438a3de092/LICENSE",
    license: "NON-COMMERCIAL LEARNING LICENSE 1.1",
    decision: "excluded",
    role: "license-case",
    accessedOn: ACCESSED_ON,
    snapshot: "Non-commercial and anti-large-scale-crawling terms reviewed on 2026-08-26",
    supports: {
      en: "A negative licensing and authorization case for creator-economy research.",
      "zh-Hans": "作为创作者经济研究中的负面许可证与授权案例。",
    },
    boundary: {
      en: "Do not install or run it in this public, commercially relevant course: the custom license is non-commercial and platform-login crawling creates added risk.",
      "zh-Hans": "本公开且与商业运营相关的课程中不得安装或运行：其自定义许可证仅限非商业，平台登录态抓取还增加风险。",
    },
  },
] as const satisfies readonly CreatorOpsSourceRecord[];

const SOURCE_BY_ID = new Map<string, CreatorOpsSourceRecord>(
  CREATOR_OPS_SOURCES.map((source) => [source.id, source]),
);

export function getCreatorOpsSource(id: string): CreatorOpsSourceRecord {
  const source = SOURCE_BY_ID.get(id);
  if (!source) throw new Error(`Unknown creator-ops source: ${id}`);
  return source;
}
