import {
  GITHUB_FIGURE_IDS,
  type GithubFigureId,
  type GithubFigureManifest,
} from "./types";

const SOURCE_COMMIT = "4f8c3170cea7f72cf41fc976f5dbf4e8a0b8567f" as const;
const RAW_ROOT = `https://raw.githubusercontent.com/github/docs/${SOURCE_COMMIT}/assets/images/help`;
const OBSERVED_ON = "2026-08-24" as const;

export const GITHUB_FIGURES = [
  {
    id: "fig-01",
    lessonSlug: "repository-readme",
    src: "/courses/github/figures/01-create-menu.png",
    webpSrc: "/courses/github/figures/01-create-menu.webp",
    width: 732,
    height: 516,
    sourceUrl:
      "https://docs.github.com/assets/cb-29762/images/help/repository/repo-create-global-nav-update.png",
    immutableSourceUrl: `${RAW_ROOT}/repository/repo-create-global-nav-update.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-new-repository",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "f1c0f1b3c2bdcb9026c6b635775611a10cc85d4e004ab32bd54c705f40b6ae23",
    privacyReviewed: true,
  },
  {
    id: "fig-02",
    lessonSlug: "repository-readme",
    src: "/courses/github/figures/02-repository-name.png",
    webpSrc: "/courses/github/figures/02-repository-name.webp",
    width: 1528,
    height: 350,
    sourceUrl:
      "https://docs.github.com/assets/cb-89988/images/help/repository/create-repository-name.png",
    immutableSourceUrl: `${RAW_ROOT}/repository/create-repository-name.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-new-repository",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "7c903455267a7e9127c963cedac1ca90e2d3debaa58c0057c5bf4d2cae784a7c",
    privacyReviewed: true,
  },
  {
    id: "fig-03",
    lessonSlug: "repository-readme",
    src: "/courses/github/figures/03-readme-preview.png",
    webpSrc: "/courses/github/figures/03-readme-preview.webp",
    width: 1512,
    height: 304,
    sourceUrl:
      "https://docs.github.com/assets/cb-35434/images/help/repository/edit-readme-preview-changes.png",
    immutableSourceUrl: `${RAW_ROOT}/repository/edit-readme-preview-changes.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/quickstart-for-writing-on-github",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "d50c9d93ce164bd352d72916f92a19a8f6ef7012b7c1ce3af5449baae9614c7e",
    privacyReviewed: true,
  },
  {
    id: "fig-04",
    lessonSlug: "branches-commits",
    src: "/courses/github/figures/04-branching.png",
    webpSrc: "/courses/github/figures/04-branching.webp",
    width: 2098,
    height: 528,
    sourceUrl:
      "https://docs.github.com/assets/cb-23923/images/help/repository/branching.png",
    immutableSourceUrl: `${RAW_ROOT}/repository/branching.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/get-started/using-github/github-flow",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "73042f69d246dc19f411aff82e0d0be5c894c0feed09df19923cc0b6a90e0785",
    privacyReviewed: true,
  },
  {
    id: "fig-05",
    lessonSlug: "branches-commits",
    src: "/courses/github/figures/05-branch-dropdown.png",
    webpSrc: "/courses/github/figures/05-branch-dropdown.webp",
    width: 760,
    height: 344,
    sourceUrl:
      "https://docs.github.com/assets/cb-16584/images/help/branches/branch-selection-dropdown-global-nav-update.png",
    immutableSourceUrl: `${RAW_ROOT}/branches/branch-selection-dropdown-global-nav-update.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/pull-requests/how-tos/commit-changes/managing-branches-within-your-repository",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "7adb87f2ce26d3c63a6b6a4d878bdfe0a55b529e5a37f3862d090bb30fa4c84f",
    privacyReviewed: true,
  },
  {
    id: "fig-06",
    lessonSlug: "branches-commits",
    src: "/courses/github/figures/06-diff.png",
    webpSrc: "/courses/github/figures/06-diff.webp",
    width: 1434,
    height: 516,
    sourceUrl:
      "https://docs.github.com/assets/cb-32937/images/help/repository/diffs.png",
    immutableSourceUrl: `${RAW_ROOT}/repository/diffs.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/get-started/using-github/hello-world",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "a0c89344736c2456d962c7c550330ea18e6cd18eb8b63044f0fcd695f3167421",
    privacyReviewed: true,
  },
  {
    id: "fig-07",
    lessonSlug: "pull-requests-reviews",
    src: "/courses/github/figures/07-pr-changed-files.png",
    webpSrc: "/courses/github/figures/07-pr-changed-files.webp",
    width: 1308,
    height: 122,
    sourceUrl:
      "https://docs.github.com/assets/cb-23571/images/help/pull_requests/pull-request-tabs-changed-files.png",
    immutableSourceUrl: `${RAW_ROOT}/pull_requests/pull-request-tabs-changed-files.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/pull-requests/how-tos/review-pull-requests/reviewing-proposed-changes-in-a-pull-request",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "f961a8d4c77aca43f45ab5795c520eff0cd3f7e7e85480f52b0247b50ac17ded",
    privacyReviewed: true,
  },
  {
    id: "fig-08",
    lessonSlug: "pull-requests-reviews",
    src: "/courses/github/figures/08-review-suggestion.png",
    webpSrc: "/courses/github/figures/08-review-suggestion.webp",
    width: 1378,
    height: 514,
    sourceUrl:
      "https://docs.github.com/assets/cb-26289/images/help/pull_requests/suggestion-block.png",
    immutableSourceUrl: `${RAW_ROOT}/pull_requests/suggestion-block.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/pull-requests/how-tos/review-pull-requests/reviewing-proposed-changes-in-a-pull-request",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "42e6833ab90cf65663270c06514fee5b2df051a26ae7f360ddf994ab7b724418",
    privacyReviewed: true,
  },
  {
    id: "fig-09",
    lessonSlug: "pull-requests-reviews",
    src: "/courses/github/figures/09-review-changes.png",
    webpSrc: "/courses/github/figures/09-review-changes.webp",
    width: 2114,
    height: 416,
    sourceUrl:
      "https://docs.github.com/assets/cb-53614/images/help/pull_requests/review-changes-button.png",
    immutableSourceUrl: `${RAW_ROOT}/pull_requests/review-changes-button.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/pull-requests/how-tos/review-pull-requests/reviewing-proposed-changes-in-a-pull-request",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "e0272f8ee4b1a464eb66fbe7d212d483ba7c365888c23f5b00c7fc8b436fae49",
    privacyReviewed: true,
  },
  {
    id: "fig-10",
    lessonSlug: "issues-discussions",
    src: "/courses/github/figures/10-issues-tab.png",
    webpSrc: "/courses/github/figures/10-issues-tab.webp",
    width: 1752,
    height: 140,
    sourceUrl:
      "https://docs.github.com/assets/cb-51267/images/help/repository/repo-tabs-issues-global-nav-update.png",
    immutableSourceUrl: `${RAW_ROOT}/repository/repo-tabs-issues-global-nav-update.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/issues/tracking-your-work-with-issues/learning-about-issues/about-issues",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "6b5e64f70058e49692f95caab6d997fabaaa6b3fb487ca7e3c26341ebf051e81",
    privacyReviewed: true,
  },
  {
    id: "fig-11",
    lessonSlug: "issues-discussions",
    src: "/courses/github/figures/11-discussions.png",
    webpSrc: "/courses/github/figures/11-discussions.webp",
    width: 2498,
    height: 1535,
    sourceUrl:
      "https://docs.github.com/assets/cb-531261/images/help/discussions/hero.png",
    immutableSourceUrl: `${RAW_ROOT}/discussions/hero.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "bf87184d39f692474231dca24cdea2eb857b16e66aab9f04f5763ff2aaf09082",
    privacyReviewed: true,
  },
  {
    id: "fig-12",
    lessonSlug: "projects-office-work",
    src: "/courses/github/figures/12-project-table.png",
    webpSrc: "/courses/github/figures/12-project-table.webp",
    width: 3532,
    height: 704,
    sourceUrl:
      "https://docs.github.com/assets/cb-96059/images/help/issues/quickstart-projects-table-view.png",
    immutableSourceUrl: `${RAW_ROOT}/issues/quickstart-projects-table-view.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/quickstart-for-projects",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "5e8eb80ece0e464dbd65d4db352a42600b4db7aaff072b92d1d9db2394561b27",
    privacyReviewed: true,
  },
  {
    id: "fig-13",
    lessonSlug: "projects-office-work",
    src: "/courses/github/figures/13-project-board.png",
    webpSrc: "/courses/github/figures/13-project-board.webp",
    width: 3530,
    height: 738,
    sourceUrl:
      "https://docs.github.com/assets/cb-79314/images/help/issues/quickstart-projects-board-view.png",
    immutableSourceUrl: `${RAW_ROOT}/issues/quickstart-projects-board-view.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/quickstart-for-projects",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "b96757d772c17a53abd831fc7e99c342cea2e457e6e392117a036309b0acb93b",
    privacyReviewed: true,
  },
  {
    id: "fig-14",
    lessonSlug: "notifications-governance",
    src: "/courses/github/figures/14-notifications.png",
    webpSrc: "/courses/github/figures/14-notifications.webp",
    width: 430,
    height: 266,
    sourceUrl:
      "https://docs.github.com/assets/cb-13619/images/help/notifications/notifications-general-existence-indicator.png",
    immutableSourceUrl: `${RAW_ROOT}/notifications/notifications-general-existence-indicator.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/subscriptions-and-notifications/how-tos/managing-subscriptions-for-activity-on-github/managing-your-subscriptions",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "6ed1f955602b8bbf96b8d45e6991999f504cbf10a53d4e6f6e410538c7ecf2a0",
    privacyReviewed: true,
  },
  {
    id: "fig-15",
    lessonSlug: "start-secure",
    src: "/courses/github/figures/15-2fa-setup.png",
    webpSrc: "/courses/github/figures/15-2fa-setup.webp",
    width: 725,
    height: 446,
    sourceUrl:
      "https://docs.github.com/assets/cb-23826/images/help/2fa/ghes-3.8-and-higher-2fa-wizard-app-click-code.png",
    immutableSourceUrl: `${RAW_ROOT}/2fa/ghes-3.8-and-higher-2fa-wizard-app-click-code.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "01a9f72fd6ad1a2771045339f5edd9c5d1713ccfd5d2d722f578b09c004e5600",
    privacyReviewed: true,
  },
  {
    id: "fig-16",
    lessonSlug: "forks-conflicts",
    src: "/courses/github/figures/16-merge-conflict.png",
    webpSrc: "/courses/github/figures/16-merge-conflict.webp",
    width: 1668,
    height: 248,
    sourceUrl:
      "https://docs.github.com/assets/cb-69649/images/help/pull_requests/resolve-merge-conflicts-button.png",
    immutableSourceUrl: `${RAW_ROOT}/pull_requests/resolve-merge-conflicts-button.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/pull-requests/how-tos/merge-and-close-pull-requests/resolving-a-merge-conflict-on-github",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "5af80b9d3116c090063d53c6c86882d84ffe04d1dad6ab75d2a81939fbe923e4",
    privacyReviewed: true,
  },
  {
    id: "fig-17",
    lessonSlug: "writing-publishing",
    src: "/courses/github/figures/17-release-link.png",
    webpSrc: "/courses/github/figures/17-release-link.webp",
    width: 1072,
    height: 1220,
    sourceUrl:
      "https://docs.github.com/assets/cb-90524/images/help/releases/release-link.png",
    immutableSourceUrl: `${RAW_ROOT}/releases/release-link.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "4cbf2ca3b3d748ccaf087a323945cca5dc30774145fc6944c4ceee1813fdee27",
    privacyReviewed: true,
  },
  {
    id: "fig-18",
    lessonSlug: "research-reproducibility",
    src: "/courses/github/figures/18-citation-link.png",
    webpSrc: "/courses/github/figures/18-citation-link.webp",
    width: 1918,
    height: 1336,
    sourceUrl:
      "https://docs.github.com/assets/cb-223034/images/help/repository/citation-link.png",
    immutableSourceUrl: `${RAW_ROOT}/repository/citation-link.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "a5fe20a5ca73a193024a9c9d78fc85160ed36bafe565e61a92194e755856fa67",
    privacyReviewed: true,
  },
  {
    id: "fig-19",
    lessonSlug: "software-automation",
    src: "/courses/github/figures/19-actions-tab.png",
    webpSrc: "/courses/github/figures/19-actions-tab.webp",
    width: 1242,
    height: 186,
    sourceUrl:
      "https://docs.github.com/assets/cb-12958/images/help/repository/actions-tab-global-nav-update.png",
    immutableSourceUrl: `${RAW_ROOT}/repository/actions-tab-global-nav-update.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage: "https://docs.github.com/en/actions/get-started/quickstart",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "106fc6abc283f71c0e416bb8b3eeeb1d532a0f855f4ce95d54677a1b3720ad1d",
    privacyReviewed: true,
  },
  {
    id: "fig-20",
    lessonSlug: "software-automation",
    src: "/courses/github/figures/20-actions-workflow.png",
    webpSrc: "/courses/github/figures/20-actions-workflow.webp",
    width: 2194,
    height: 474,
    sourceUrl:
      "https://docs.github.com/assets/cb-64036/images/help/repository/actions-quickstart-workflow-sidebar.png",
    immutableSourceUrl: `${RAW_ROOT}/repository/actions-quickstart-workflow-sidebar.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage: "https://docs.github.com/en/actions/get-started/quickstart",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "6423f6ca4525830027d69e7d9bb515a6f04487f126e9a7d9af6805ed057a0846",
    privacyReviewed: true,
  },
  {
    id: "fig-21",
    lessonSlug: "teaching-capstone",
    src: "/courses/github/figures/21-template-setting.png",
    webpSrc: "/courses/github/figures/21-template-setting.webp",
    width: 2196,
    height: 216,
    sourceUrl:
      "https://docs.github.com/assets/cb-28260/images/help/repository/repo-actions-settings.png",
    immutableSourceUrl: `${RAW_ROOT}/repository/repo-actions-settings.png`,
    sourceCommit: SOURCE_COMMIT,
    sourcePage:
      "https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository",
    sourcePublisher: "GitHub Docs",
    sourceLicence: "CC-BY-4.0",
    observedOn: OBSERVED_ON,
    sha256: "55780efaf6bbcdb662727f6d6bf8381e2bb7769937bc080570c856e0c42e7468",
    privacyReviewed: true,
  },
] as const satisfies readonly GithubFigureManifest[];

export const GITHUB_FIGURE_BY_ID = Object.fromEntries(
  GITHUB_FIGURES.map((figure) => [figure.id, figure]),
) as unknown as Record<GithubFigureId, GithubFigureManifest>;

if (GITHUB_FIGURES.length !== GITHUB_FIGURE_IDS.length) {
  throw new Error(
    `GitHub figure registry mismatch: expected ${GITHUB_FIGURE_IDS.length}, found ${GITHUB_FIGURES.length}`,
  );
}
