import {
  GITHUB_COURSE_ID,
  type GithubCourseManifest,
  type GithubLessonManifest,
  type GithubUnitManifest,
} from "./types";

export const GITHUB_UNITS = [
  {
    id: "unit-1",
    order: 1,
    lessonSlugs: [
      "start-secure",
      "repository-readme",
      "branches-commits",
      "pull-requests-reviews",
    ],
  },
  {
    id: "unit-2",
    order: 2,
    lessonSlugs: [
      "issues-discussions",
      "projects-office-work",
      "forks-conflicts",
      "notifications-governance",
    ],
  },
  {
    id: "unit-3",
    order: 3,
    lessonSlugs: [
      "software-automation",
      "research-reproducibility",
      "writing-publishing",
      "teaching-capstone",
    ],
  },
] as const satisfies readonly GithubUnitManifest[];

export const GITHUB_LESSONS = [
  {
    slug: "start-secure",
    order: 1,
    unitId: "unit-1",
    minutes: 45,
    prerequisites: [],
    sections: [
      { copyIndex: 0, figureIds: [] },
      { copyIndex: 1, figureIds: ["fig-15"] },
      { copyIndex: 2, figureIds: [] },
    ],
    sourceIds: [
      "github-about-repositories",
      "github-hello-world",
      "github-account-2fa",
      "github-commit-email",
      "github-commit-signature",
      "github-sensitive-data",
    ],
    quizIds: ["q01", "q02"],
  },
  {
    slug: "repository-readme",
    order: 2,
    unitId: "unit-1",
    minutes: 50,
    prerequisites: ["start-secure"],
    sections: [
      { copyIndex: 0, figureIds: ["fig-01", "fig-02"] },
      { copyIndex: 1, figureIds: ["fig-03"] },
      { copyIndex: 2, figureIds: [] },
    ],
    sourceIds: [
      "github-create-repository",
      "github-about-repositories",
      "github-markdown",
    ],
    quizIds: ["q03", "q04"],
  },
  {
    slug: "branches-commits",
    order: 3,
    unitId: "unit-1",
    minutes: 50,
    prerequisites: ["repository-readme"],
    sections: [
      { copyIndex: 0, figureIds: ["fig-04"] },
      { copyIndex: 1, figureIds: ["fig-05"] },
      { copyIndex: 2, figureIds: ["fig-06"] },
    ],
    sourceIds: ["github-flow", "github-branches", "github-commits"],
    quizIds: ["q05", "q06"],
  },
  {
    slug: "pull-requests-reviews",
    order: 4,
    unitId: "unit-1",
    minutes: 55,
    prerequisites: ["branches-commits"],
    sections: [
      { copyIndex: 0, figureIds: ["fig-07"] },
      { copyIndex: 1, figureIds: ["fig-08"] },
      { copyIndex: 2, figureIds: ["fig-09"] },
    ],
    sourceIds: [
      "github-flow",
      "github-pull-requests",
      "github-review-pull-request",
      "github-repository-roles",
    ],
    quizIds: ["q07", "q08"],
  },
  {
    slug: "issues-discussions",
    order: 5,
    unitId: "unit-2",
    minutes: 45,
    prerequisites: ["pull-requests-reviews"],
    sections: [
      { copyIndex: 0, figureIds: ["fig-10"] },
      { copyIndex: 1, figureIds: ["fig-11"] },
      { copyIndex: 2, figureIds: [] },
    ],
    sourceIds: [
      "github-issues",
      "github-issue-linking",
      "github-discussions",
      "github-team-planning",
    ],
    quizIds: ["q09", "q10"],
  },
  {
    slug: "projects-office-work",
    order: 6,
    unitId: "unit-2",
    minutes: 50,
    prerequisites: ["issues-discussions"],
    sections: [
      { copyIndex: 0, figureIds: [] },
      { copyIndex: 1, figureIds: ["fig-12", "fig-13"] },
      { copyIndex: 2, figureIds: [] },
    ],
    sourceIds: [
      "github-team-planning",
      "github-projects",
      "github-repository-roles",
      "github-sensitive-data",
      "github-docs-projects-story",
    ],
    quizIds: ["q11", "q12"],
  },
  {
    slug: "forks-conflicts",
    order: 7,
    unitId: "unit-2",
    minutes: 55,
    prerequisites: ["projects-office-work"],
    sections: [
      { copyIndex: 0, figureIds: [] },
      { copyIndex: 1, figureIds: ["fig-16"] },
      { copyIndex: 2, figureIds: [] },
    ],
    sourceIds: ["github-forks", "github-merge-conflicts", "github-flow"],
    quizIds: ["q13", "q14"],
  },
  {
    slug: "notifications-governance",
    order: 8,
    unitId: "unit-2",
    minutes: 45,
    prerequisites: ["forks-conflicts"],
    sections: [
      { copyIndex: 0, figureIds: ["fig-14"] },
      { copyIndex: 1, figureIds: [] },
      { copyIndex: 2, figureIds: [] },
    ],
    sourceIds: [
      "github-notifications",
      "github-repository-roles",
      "github-sensitive-data",
      "github-account-2fa",
    ],
    quizIds: ["q15", "q16"],
  },
  {
    slug: "software-automation",
    order: 9,
    unitId: "unit-3",
    minutes: 60,
    prerequisites: ["notifications-governance"],
    sections: [
      { copyIndex: 0, figureIds: ["fig-19"] },
      { copyIndex: 1, figureIds: ["fig-20"] },
      { copyIndex: 2, figureIds: [] },
    ],
    sourceIds: [
      "github-connecting",
      "github-actions-quickstart",
      "github-actions-checkout",
      "github-actions-security",
      "github-releases",
      "github-sothebys-actions",
    ],
    quizIds: ["q17", "q18"],
  },
  {
    slug: "research-reproducibility",
    order: 10,
    unitId: "unit-3",
    minutes: 60,
    prerequisites: ["software-automation"],
    sections: [
      { copyIndex: 0, figureIds: [] },
      { copyIndex: 1, figureIds: ["fig-18"] },
      { copyIndex: 2, figureIds: [] },
    ],
    sourceIds: [
      "github-citation-files",
      "github-releases",
      "github-immutable-releases",
      "github-archive",
      "zenodo-github",
      "github-sensitive-data",
      "plos-research-lab",
    ],
    quizIds: ["q19", "q20"],
  },
  {
    slug: "writing-publishing",
    order: 11,
    unitId: "unit-3",
    minutes: 55,
    prerequisites: ["research-reproducibility"],
    sections: [
      { copyIndex: 0, figureIds: [] },
      { copyIndex: 1, figureIds: [] },
      { copyIndex: 2, figureIds: ["fig-17"] },
    ],
    sourceIds: [
      "github-markdown",
      "github-review-pull-request",
      "github-releases",
      "github-flow",
      "plos-manubot-writing",
      "deep-review-usage",
    ],
    quizIds: ["q21", "q22"],
  },
  {
    slug: "teaching-capstone",
    order: 12,
    unitId: "unit-3",
    minutes: 90,
    prerequisites: ["writing-publishing"],
    sections: [
      { copyIndex: 0, figureIds: ["fig-21"] },
      { copyIndex: 1, figureIds: [] },
      { copyIndex: 2, figureIds: [] },
    ],
    sourceIds: [
      "github-template-repository",
      "github-skills-introduction",
      "classroom50-repository",
      "classroom50-quickstart",
      "classroom50-feedback-pr",
      "github-classroom-retirement",
      "github-classroom-transition",
      "github-actions-security",
    ],
    quizIds: ["q23", "q24"],
  },
] as const satisfies readonly GithubLessonManifest[];

export const GITHUB_COURSE_MANIFEST = {
  id: GITHUB_COURSE_ID,
  sequence: 6,
  version: "1.0.0",
  publishedOn: "2026-08-23",
  sourceSnapshotOn: "2026-08-24",
  units: GITHUB_UNITS,
  lessons: GITHUB_LESSONS,
} as const satisfies GithubCourseManifest;
