import {
  GITHUB_SOURCE_IDS,
  type GithubSourceId,
  type GithubSourceRecord,
} from "./types";

const ACCESSED_ON = "2026-08-24";
const VERIFIED_AT = "2026-08-24T11:52:00+08:00";

export const GITHUB_SOURCES = [
  {
    id: "github-account-2fa",
    kind: "official-doc",
    tier: "primary",
    title: "Configuring two-factor authentication",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["account-2fa", "recovery-codes"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Primary account-security procedure. Initial 2FA uses TOTP or SMS; GitHub strongly recommends TOTP, with security keys added afterward as backup methods instead of relying on SMS.",
  },
  {
    id: "github-commit-email",
    kind: "official-doc",
    tier: "primary",
    title: "Setting your commit email address",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/account-and-profile/how-tos/email-preferences/setting-your-commit-email-address",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["commit-email-account-linkage", "commit-email-privacy"],
    reuseMode: "paraphrased",
    note: "Explains how GitHub associates command-line commits through the email recorded in the commit and that attribution requires an address connected to the account or the GitHub-provided noreply address. Account attribution is distinct from cryptographic commit-signature verification.",
  },
  {
    id: "github-commit-signature",
    kind: "official-doc",
    tier: "primary",
    title: "About commit signature verification",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["commit-signing-separate", "verified-signature"],
    reuseMode: "paraphrased",
    note: "Establishes that cryptographic commit signing and GitHub's Verified status are separate from account authentication and commit-email attribution.",
  },
  {
    id: "github-about-repositories",
    kind: "official-doc",
    tier: "primary",
    title: "About repositories",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/repositories/creating-and-managing-repositories/about-repositories",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["repository-definition", "visibility", "collaboration-model"],
    reuseMode: "paraphrased",
    note: "Defines repository, branch, clone, fork, merge, pull request, remote, and upstream terminology.",
  },
  {
    id: "github-hello-world",
    kind: "official-doc",
    tier: "primary",
    title: "Hello World",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/get-started/using-github/hello-world",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["browser-first", "beginner-path"],
    reuseMode: "paraphrased",
    note: "Official browser-first learning sequence; it requires no coding, command-line, or Git prerequisite.",
  },
  {
    id: "github-create-repository",
    kind: "official-doc",
    tier: "primary",
    title: "Creating a new repository",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-new-repository",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["repository-create", "visibility-choice", "readme-initialise"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Primary creation workflow and source for the repository-creation figures.",
  },
  {
    id: "github-markdown",
    kind: "official-doc",
    tier: "primary",
    title: "Quickstart for writing on GitHub",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/quickstart-for-writing-on-github",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["markdown", "readme", "writing-workflow"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Primary Markdown and README guidance.",
  },
  {
    id: "github-flow",
    kind: "official-doc",
    tier: "primary",
    title: "GitHub flow",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/get-started/using-github/github-flow",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["branch-proposal-review-merge", "non-code-contexts"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Official branch-to-pull-request workflow, explicitly useful for documentation, policy, and roadmap work as well as code.",
  },
  {
    id: "github-branches",
    kind: "official-doc",
    tier: "primary",
    title: "Managing branches within your repository",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/pull-requests/how-tos/commit-changes/managing-branches-within-your-repository",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["branch-create", "branch-delete"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Current web-interface branch procedure.",
  },
  {
    id: "github-commits",
    kind: "official-doc",
    tier: "primary",
    title: "Commits",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/pull-requests/reference/commits",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["commit-snapshot", "commit-message"],
    reuseMode: "paraphrased",
    note: "Defines commits and their role in repository history.",
  },
  {
    id: "github-pull-requests",
    kind: "official-doc",
    tier: "primary",
    title: "Pull requests",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/pull-requests/reference/pull-requests",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["pull-request-proposal", "draft-pull-request"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Defines pull requests as proposals for reviewing and merging changes.",
  },
  {
    id: "github-review-pull-request",
    kind: "official-doc",
    tier: "primary",
    title: "Reviewing proposed changes in a pull request",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/pull-requests/how-tos/review-pull-requests/reviewing-proposed-changes-in-a-pull-request",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["review-diff", "suggested-change", "approve-request-changes"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Primary review procedure and source for the pull-request review figures.",
  },
  {
    id: "github-merge-conflicts",
    kind: "official-doc",
    tier: "primary",
    title: "Resolving a merge conflict on GitHub",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/pull-requests/how-tos/merge-and-close-pull-requests/resolving-a-merge-conflict-on-github",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["simple-web-conflict", "complex-local-conflict"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Distinguishes simple web-resolvable conflicts from conflicts that require local resolution.",
  },
  {
    id: "github-forks",
    kind: "official-doc",
    tier: "primary",
    title: "Forks",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/pull-requests/reference/forks",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["fork-definition", "fork-visibility"],
    reuseMode: "paraphrased",
    note: "Current permission and visibility behavior for repository forks.",
  },
  {
    id: "github-issues",
    kind: "official-doc",
    tier: "primary",
    title: "About issues",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/issues/tracking-your-work-with-issues/learning-about-issues/about-issues",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["issue-purpose", "sub-issues", "dependencies"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Primary issue-tracking model.",
  },
  {
    id: "github-issue-linking",
    kind: "official-doc",
    tier: "primary",
    title: "Linking a pull request to an issue",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: [
      "issue-closing-keywords",
      "default-branch-closing",
      "commit-message-closing",
    ],
    reuseMode: "paraphrased",
    note: "Primary semantics for linking and closing issues from pull-request descriptions versus commit messages, including the default-branch condition.",
  },
  {
    id: "github-discussions",
    kind: "official-doc",
    tier: "primary",
    title: "About discussions",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["discussion-purpose", "question-answer", "announcement"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Primary open-ended conversation and community Q&A model.",
  },
  {
    id: "github-team-planning",
    kind: "official-doc",
    tier: "primary",
    title: "Planning and tracking work for your team or project",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/issues/tracking-your-work-with-issues/learning-about-issues/planning-and-tracking-work-for-your-team-or-project",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["cross-functional-planning", "product-project-team-personal"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Explicitly covers product, project, team, and personal planning beyond software development.",
  },
  {
    id: "github-projects",
    kind: "official-doc",
    tier: "primary",
    title: "Projects documentation",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/issues/planning-and-tracking-with-projects",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["project-table", "project-board", "project-roadmap"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Primary project-view and custom-field guidance.",
  },
  {
    id: "github-notifications",
    kind: "official-doc",
    tier: "primary",
    title: "Managing your subscriptions",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/subscriptions-and-notifications/how-tos/managing-subscriptions-for-activity-on-github/managing-your-subscriptions",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["watch-subscribe", "notification-triage"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Primary notification and subscription-management procedure.",
  },
  {
    id: "github-repository-roles",
    kind: "official-doc",
    tier: "primary",
    title: "Repository roles for an organization",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["least-privilege", "organization-roles", "review-gates"],
    reuseMode: "paraphrased",
    note: "Primary repository-role capability table.",
  },
  {
    id: "github-sensitive-data",
    kind: "official-doc",
    tier: "primary",
    title: "Removing sensitive data from a repository",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: [
      "secret-rotation-first",
      "history-rewrite-limits",
      "sensitive-history-boundary",
    ],
    reuseMode: "paraphrased",
    note: "Establishes that exposed credentials should be revoked or rotated first, that deletion in a later commit is insufficient, and that removing sensitive material from distributed repository history is limited and disruptive.",
  },
  {
    id: "github-connecting",
    kind: "official-doc",
    tier: "primary",
    title: "Connecting to GitHub",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/get-started/using-github/connecting-to-github",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["browser-desktop-cli-choice", "local-remote"],
    reuseMode: "paraphrased",
    note: "Current comparison of browser, github.dev, Codespaces, GitHub Desktop, editor, CLI, and API workflows.",
  },
  {
    id: "github-actions-quickstart",
    kind: "official-doc",
    tier: "primary",
    title: "Quickstart for GitHub Actions",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/actions/get-started/quickstart",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["actions-workflow", "workflow-directory"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Current first-workflow example. At this snapshot the Docs example still uses checkout v6, so the action's own release ledger is the authority for its latest major version.",
  },
  {
    id: "github-actions-checkout",
    kind: "official-project",
    tier: "primary",
    title: "actions/checkout v7.0.1",
    publisher: "GitHub Actions",
    url: "https://github.com/actions/checkout/releases/tag/v7.0.1",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["current-checkout-version"],
    reuseMode: "link-only",
    licence: "MIT",
    note: "GitHub's action repository marks v7.0.1 as Latest and its current README uses checkout v7. The GitHub Docs quickstart still shows v6, an official-source lag recorded explicitly for future audits.",
  },
  {
    id: "github-actions-security",
    kind: "official-doc",
    tier: "primary",
    title: "Secure use reference",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/actions/reference/security/secure-use",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: [
      "least-privilege-token",
      "untrusted-input",
      "third-party-actions",
    ],
    reuseMode: "paraphrased",
    note: "Primary security boundaries for workflow permissions, secrets, untrusted input, and third-party actions.",
  },
  {
    id: "github-releases",
    kind: "official-doc",
    tier: "primary",
    title: "Managing releases in a repository",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: [
      "tagged-release",
      "release-notes",
      "release-assets",
      "ordinary-release-edit-delete",
    ],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Primary release-creation and distribution workflow, including the distinct behavior of repositories with immutable releases enabled.",
  },
  {
    id: "github-immutable-releases",
    kind: "official-doc",
    tier: "primary",
    title: "Immutable releases",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/code-security/concepts/supply-chain-security/immutable-releases",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: [
      "immutable-release-tag-lock",
      "immutable-release-asset-integrity",
      "immutable-release-deletion-boundaries",
      "immutable-release-tag-name-nonreuse",
    ],
    reuseMode: "paraphrased",
    note: "Primary lifecycle boundaries for immutable-release tags and assets, including deletion of the release and the permanent prohibition on reusing its tag name.",
  },
  {
    id: "github-citation-files",
    kind: "official-doc",
    tier: "primary",
    title: "About CITATION files",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["citation-cff", "apa-bibtex", "preferred-citation"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Primary citation-metadata behavior and source for the Cite this repository figure.",
  },
  {
    id: "github-archive",
    kind: "official-doc",
    tier: "primary",
    title: "About archiving content and data on GitHub",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/repositories/archiving-a-github-repository/about-archiving-content-and-data-on-github",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["archive-read-only", "long-term-preservation", "privacy"],
    reuseMode: "paraphrased",
    note: "Primary GitHub archival scope; the course distinguishes repository history from a domain repository or backup policy.",
  },
  {
    id: "zenodo-github",
    kind: "partner-doc",
    tier: "corroborating",
    title: "GitHub and software",
    publisher: "Zenodo",
    url: "https://help.zenodo.org/docs/github/",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["doi-release-archive", "citation-metadata"],
    reuseMode: "link-only",
    note: "Official Zenodo documentation for archiving public GitHub releases and describing software deposits.",
  },
  {
    id: "github-template-repository",
    kind: "official-doc",
    tier: "primary",
    title: "Creating a template repository",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["template-repository", "starter-files", "unrelated-history"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for GitHub Docs content and assets",
    note: "Primary template repository behavior and source for the template-setting figure.",
  },
  {
    id: "github-skills-introduction",
    kind: "official-project",
    tier: "primary",
    title: "Introduction to GitHub",
    publisher: "GitHub Skills",
    url: "https://github.com/skills/introduction-to-github",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["guided-practice", "branch-commit-pull-request-merge"],
    reuseMode: "link-only",
    licence: "MIT",
    note: "Official practice repository for the core browser workflow.",
  },
  {
    id: "github-sothebys-actions",
    kind: "practitioner-story",
    tier: "corroborating",
    title: "How Sotheby's uses GitHub Actions",
    publisher: "GitHub ReadME Project",
    url: "https://github.com/readme/guides/sothebys-github-actions",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["engineering-ci-practice"],
    reuseMode: "link-only",
    note: "A real engineering narrative for CI feedback; current workflow syntax still comes from GitHub Docs.",
  },
  {
    id: "plos-research-lab",
    kind: "peer-reviewed",
    tier: "corroborating",
    title: "GitHub enables collaborative and reproducible laboratory research",
    publisher: "PLOS Biology",
    url: "https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3003029",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: [
      "research-issues-practice",
      "reproducible-structure",
      "data-boundaries",
    ],
    reuseMode: "paraphrased",
    licence: "CC-BY",
    note: "Peer-reviewed enacted laboratory practice using issues, plain-text project structure, and reproducibility safeguards.",
  },
  {
    id: "plos-manubot-writing",
    kind: "peer-reviewed",
    tier: "corroborating",
    title: "Open collaborative writing with Manubot",
    publisher: "PLOS Computational Biology",
    url: "https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007128",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: [
      "collaborative-writing-practice",
      "themed-pull-requests",
      "review-rounds",
    ],
    reuseMode: "paraphrased",
    licence: "CC-BY",
    note: "Peer-reviewed, multi-author GitHub writing case using themed pull requests and continuous integration.",
  },
  {
    id: "deep-review-usage",
    kind: "project-guide",
    tier: "corroborating",
    title: "Manubot usage guidelines",
    publisher: "greenelab/deep-review",
    url: "https://github.com/greenelab/deep-review/blob/44ff95a2756bd03a32c046eb8983ac9c4f223b0a/USAGE.md",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["semantic-linefeeds", "sentence-per-source-line"],
    reuseMode: "link-only",
    note: "Immutable project-guide snapshot that explicitly recommends one sentence per source line for more precise diffs, review comments, and conflict handling.",
  },
  {
    id: "github-docs-projects-story",
    kind: "practitioner-story",
    tier: "corroborating",
    title: "How the GitHub Docs team uses GitHub Projects",
    publisher: "The GitHub Blog",
    url: "https://github.blog/engineering/engineering-principles/how-the-github-docs-team-uses-github-projects/",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["office-project-practice", "audience-specific-views"],
    reuseMode: "link-only",
    note: "Real cross-functional content-work practice from GitHub's own documentation team.",
  },
  {
    id: "classroom50-repository",
    kind: "official-project",
    tier: "corroborating",
    title: "Classroom 50",
    publisher: "Fifty Foundation",
    url: "https://github.com/foundation50/classroom50",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["current-assignment-platform"],
    reuseMode: "link-only",
    licence: "Repository licence applies",
    note: "Open-source partner named in GitHub's Classroom transition communication; instructors must recheck current release and security status.",
  },
  {
    id: "classroom50-quickstart",
    kind: "official-project",
    tier: "corroborating",
    title: "Classroom 50 Quickstart",
    publisher: "Fifty Foundation",
    url: "https://github.com/foundation50/classroom50/wiki/Quickstart",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: [
      "instructor-setup",
      "organization-requirements",
      "assignment-distribution",
      "actions-autograding",
      "roster-workflow",
      "score-export",
    ],
    reuseMode: "link-only",
    note: "Current instructor setup and operating documentation, including organization-plan prerequisites, assignment distribution, autograding, rosters, score collection, and CSV export. The course does not freeze volatile CLI commands into the lesson.",
  },
  {
    id: "classroom50-feedback-pr",
    kind: "official-project",
    tier: "corroborating",
    title: "Feedback Pull Request implementation",
    publisher: "Fifty Foundation",
    url: "https://github.com/foundation50/classroom50/discussions/10",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["feedback-pull-requests"],
    reuseMode: "link-only",
    note: "Project-maintainer confirmation that feedback pull requests were implemented; instructors must still recheck the active project before adoption.",
  },
  {
    id: "github-classroom-retirement",
    kind: "official-announcement",
    tier: "primary",
    title: "GitHub Classroom sign-ups are no longer available",
    publisher: "The GitHub Changelog",
    url: "https://github.blog/changelog/2026-05-26-github-classroom-sign-ups-are-no-longer-available/",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["classroom-no-new-signups", "classroom-august-28-retirement"],
    reuseMode: "paraphrased",
    note: "Time-sensitive primary announcement: no new sign-ups from 26 May 2026 and decommissioning on 28 August 2026.",
  },
  {
    id: "github-classroom-transition",
    kind: "official-announcement",
    tier: "primary",
    title: "GitHub Classroom transition discussion",
    publisher: "GitHub Community",
    url: "https://github.com/orgs/community/discussions/196615",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["classroom-transition-partners", "classroom-data-export"],
    reuseMode: "link-only",
    note: "GitHub's current transition and export guidance, including partner options and preservation of repositories and organizations.",
  },
  {
    id: "github-docs-license",
    kind: "official-project",
    tier: "primary",
    title: "github/docs",
    publisher: "GitHub",
    url: "https://github.com/github/docs",
    accessedOn: ACCESSED_ON,
    verifiedAt: VERIFIED_AT,
    claimIds: ["docs-assets-licence", "figure-provenance"],
    reuseMode: "asset-reused",
    licence: "CC-BY-4.0 for content, assets, and data; MIT for code",
    note: "Reuse basis for the local GitHub Docs screenshots. The course is independent and does not imply GitHub endorsement.",
  },
] as const satisfies readonly GithubSourceRecord[];

export const GITHUB_SOURCE_BY_ID = Object.fromEntries(
  GITHUB_SOURCES.map((source) => [source.id, source]),
) as unknown as Record<GithubSourceId, GithubSourceRecord>;

if (GITHUB_SOURCES.length !== GITHUB_SOURCE_IDS.length) {
  throw new Error(
    `GitHub source registry mismatch: expected ${GITHUB_SOURCE_IDS.length}, found ${GITHUB_SOURCES.length}`,
  );
}
