export const MCP_CLAIM_MAP = [
  {
    id: "stateless-core",
    lessonOrder: 3,
    lessonSlug: "discovery-versioning",
    claim: "MCP 2026-07-28 is handshake-free and carries protocol version and client capabilities on every request.",
    sourceIds: ["mcp-spec-overview", "mcp-changelog", "mcp-discovery"],
  },
  {
    id: "removed-vs-deprecated",
    lessonOrder: 3,
    lessonSlug: "discovery-versioning",
    claim: "initialize/initialized and ping are removed from the current core; roots, sampling, logging, DCR, and HTTP+SSE are deprecated.",
    sourceIds: ["mcp-changelog", "mcp-deprecated"],
  },
  {
    id: "tool-contracts",
    lessonOrder: 5,
    lessonSlug: "tools",
    claim: "Tools use JSON Schema 2020-12, may return any JSON structuredContent, and expose annotations that clients treat as untrusted hints.",
    sourceIds: ["mcp-tools", "mcp-schema"],
  },
  {
    id: "http-transport",
    lessonOrder: 9,
    lessonSlug: "transports-json-rpc",
    claim: "Current Streamable HTTP uses one POST per message, requires Mcp-Method on every request and Mcp-Name on named operations, and requires client handling of optional x-mcp-header annotations. The core defines no client-to-server notification over Streamable HTTP; transport notification mechanics return 202 with no body, while protocol sessions, endpoint GET/DELETE, and Last-Event-ID resumption are absent.",
    sourceIds: ["mcp-streamable-http", "mcp-transports"],
  },
  {
    id: "subscriptions-progress-cancel",
    lessonOrder: 10,
    lessonSlug: "flow-control",
    claim: "subscriptions/listen correlates notifications with the listen request ID; numeric progress must increase after reporting begins; cancellation differs by transport.",
    sourceIds: ["mcp-subscriptions", "mcp-progress", "mcp-cancellation"],
  },
  {
    id: "cache-and-cursors",
    lessonOrder: 10,
    lessonSlug: "flow-control",
    claim: "The six cacheable Complete discovery/list/read result families must include TTL and cache scope, and an empty string remains a valid nextCursor.",
    sourceIds: ["mcp-caching", "mcp-pagination"],
  },
  {
    id: "oauth-boundary",
    lessonOrder: 11,
    lessonSlug: "authorization",
    claim: "Authorization is optional overall; HTTP authorization follows the MCP OAuth resource flow, while stdio credentials come from the environment.",
    sourceIds: ["mcp-auth", "mcp-auth-security"],
  },
  {
    id: "state-handle-security",
    lessonOrder: 12,
    lessonSlug: "security",
    claim: "Explicit state handles are identifiers rather than bearer authority and must be unpredictable and reauthorized on every request.",
    sourceIds: ["mcp-security", "mcp-spec-overview"],
  },
  {
    id: "host-support",
    lessonOrder: 15,
    lessonSlug: "host-integrations",
    claim: "Claude, OpenAI/Codex, and Gemini provide distinct MCP product surfaces whose transport, approvals, filters, and extension support must be checked separately.",
    sourceIds: ["anthropic-mcp", "claude-desktop-mcp", "claude-remote-mcp", "openai-codex-mcp", "openai-responses-mcp", "google-gemini-mcp-current"],
  },
  {
    id: "practitioner-bounds",
    lessonOrder: 16,
    lessonSlug: "practitioner-patterns",
    claim: "The named GitHub reports establish bounded observations in their stated environments, not prevalence or universal product behavior.",
    sourceIds: ["github-experience-tool-scope", "github-experience-write-auth", "github-experience-research-timeout", "github-experience-knowledge-health", "github-experience-ops-timeout", "github-experience-teaching-gap"],
  },
  {
    id: "registry-boundary",
    lessonOrder: 17,
    lessonSlug: "production-registry",
    claim: "Registry namespace verification supports publisher identity but does not certify package safety, permissions, or organizational fit.",
    sourceIds: ["mcp-registry", "mcp-security"],
  },
  {
    id: "extensions",
    lessonOrder: 18,
    lessonSlug: "apps-tasks-capstone",
    claim: "Extensions are disabled by default and versioned independently: MCP Apps is Stable at its frozen 2026-01-26 specification, Tasks and Client Credentials are Draft, Enterprise-Managed Authorization is Stable, and useful fallbacks remain required.",
    sourceIds: ["mcp-extensions", "mcp-apps-spec", "mcp-tasks-spec", "mcp-auth-extension-status"],
  },
] as const;
