import type {
  McpCapstoneCopy,
  McpCopyMetadata,
  McpInteractiveCopy,
  McpLocalizedAssessmentCopy,
  McpLocalizedExtensionCopy,
  McpLocalizedFigureCopy,
  McpLocalizedLessonCopy,
} from "./types";

/**
 * English interface copy is the source for the generated locale bundles. The
 * values live here so a component cannot quietly introduce learner-facing
 * English that bypasses the localization contract.
 */
export const MCP_ENGLISH_UI_COPY = {
  dashboardCourseTemplate: "Course {sequence}",
  dashboardProtocolTemplate: "MCP {version}",
  dashboardEvidenceSnapshotTemplate: "Evidence snapshot {date}",
  dashboardCourseFactsAria: "Course facts",
  dashboardFactLead: "Protocol literacy → production evidence",
  dashboardLessons: "Lessons",
  dashboardStudyTime: "Study time",
  dashboardStudyTimeTemplate: "{hours}h {minutes}m",
  dashboardEvidenceFigures: "Evidence figures",
  dashboardConceptLedger: "Concept ledger",
  dashboardInspectCurriculum: "Inspect the curriculum",
  dashboardCorrectionEyebrow: "The correction that shapes this course",
  dashboardCorrectionTitle: "Current MCP is stateless and handshake-free.",
  dashboardCorrectionBody: "Every request carries protocol version and client capabilities. Servers implement server/discover; subscriptions use subscriptions/listen; server-requested input uses MRTR. Roots, sampling, protocol logging, Dynamic Client Registration, and HTTP+SSE are deprecated.",
  dashboardLearnMigration: "Learn the migration",
  dashboardVisualEyebrow: "Licensed first-party visual evidence",
  dashboardVisualTitle: "Learn from eight genuine, provenance-checked interfaces.",
  dashboardVisualBody: "Six first-party MCP Inspector documentation figures retain CC BY 4.0 attribution. Two course-authored terminal captures show Gemini CLI status and Codex CLI configuration with pinned clients, synthetic data, privacy-safe crops, hashes, and strict captions about what the pixels do—and do not—prove. Older Google and OpenAI documentation images without figure-level reuse clearance remain withheld.",
  dashboardLegacyFlagged: "Legacy UI evidence is visibly flagged",
  dashboardObservedTemplate: "Observed {date}",
  dashboardCurriculumEyebrow: "Five evidence gates",
  dashboardCurriculumTitle: "The complete curriculum",
  dashboardCurriculumBody: "Each lesson ends with a practice artifact, a source-grounded check, and a local completion milestone.",
  dashboardMinutesTemplate: "{minutes} min",
  dashboardConceptEyebrow: "Completeness contract",
  dashboardConceptTitle: "Every key concept, status visible",
  dashboardConceptBody: "“Defined in the core specification” identifies where a concept is specified; capability families remain optional unless negotiated. “Absent from 2026-07-28 core” describes a breaking-revision boundary, not the lifecycle registry’s formal Removed status. Inspector and approvals are tooling or host practices.",
  dashboardStatusCore: "Defined in the core specification",
  dashboardStatusOptional: "Optional capability",
  dashboardStatusPractice: "Tooling / host practice",
  dashboardStatusExtension: "Negotiated extension",
  dashboardStatusDeprecated: "Deprecated · migration only",
  dashboardStatusRemoved: "Absent from 2026-07-28 core · legacy-version only",
  dashboardSourceEyebrow: "Source method",
  dashboardSourceTitle: "Normative truth and product experience stay separate.",
  dashboardSourcesTemplate: "{count} sources",
  dashboardClaimEyebrow: "Claim-to-source map",
  dashboardClaimTitle: "High-risk claims are traceable at sentence level.",
  dashboardClaimBody: "The lesson bibliography gives context; this compact map identifies the exact primary sources governing claims most likely to age or be copied incorrectly.",
  dashboardLessonTemplate: "Lesson {order}",
  dashboardIntegrityTitle: "Course integrity",
  dashboardIntegrityBody: "Course text, original interface code, and—where separately copyrightable—the course-authored capture selection, privacy crops, and surrounding material are offered under the site’s MIT license. Visible Gemini CLI and Codex CLI interface/output remains subject to each upstream Apache-2.0 license and provider trademark terms. The six Inspector figures remain CC BY 4.0. Every master, transformation, client version, rights layer, and withheld asset is traced in public/courses/mcp/figure-manifest.json and NOTICE.md; no provider affiliation or endorsement is implied.",
  dashboardIntegrityDateTemplate: "Protocol claims were checked against MCP 2026-07-28 on {date}. Product interfaces can change sooner; every lesson keeps its observed date and direct source.",

  progressEyebrow: "Private browser progress",
  progressPercentTemplate: "{percent}% complete",
  progressSummaryTemplate: "Lessons completed: {completed}/{total} · final assessment: {assessment} · capstone: {capstone}",
  progressAssessmentPassed: "passed",
  progressAssessmentNotPassed: "not passed",
  progressCapstoneComplete: "complete",
  progressCapstoneOpen: "open",
  progressAria: "MCP course progress",
  progressContinue: "Continue",
  progressStart: "Start course",
  progressTakeAssessment: "Take assessment",
  progressOpenCapstone: "Open capstone",
  progressResetStatus: "MCP course progress was reset in this browser.",
  progressResetGroupAria: "Confirm progress reset",
  progressResetQuestion: "Reset all MCP lessons, assessment, and capstone progress?",
  progressResetYes: "Yes, reset",
  progressResetCancel: "Cancel",
  progressResetAction: "Reset MCP progress",

  assessmentEyebrow: "Source-grounded assessment",
  assessmentTitle: "Final protocol and practice check",
  assessmentIntroTemplate: "{count} new scenario questions · pass at ≥80% ({threshold}/{count} required) · explanations appear after submission.",
  assessmentBody: "This versioned summative bank is separate from the lesson checks and tests transfer across protocol, security, host, and practitioner scenarios.",
  assessmentBestTemplate: "Best score in this browser: {best}/{count}",
  assessmentBegin: "Begin assessment",
  assessmentOutcomeTemplate: "Outcome: {outcome}",
  assessmentCorrect: "Correct.",
  assessmentNotYet: "Not yet.",
  assessmentReviewLesson: "Review the mapped lesson",
  assessmentAnsweredTemplate: "Answered: {answered}/{count}",
  assessmentScore: "Score assessment",
  assessmentPassed: "Assessment passed",
  assessmentReviewRequired: "Review required",
  assessmentPassBody: "You met the 80% protocol-literacy gate. Keep the explanations with your capstone evidence.",
  assessmentFailBodyTemplate: "You need {threshold} correct. Review the explanations, revisit the named lessons, and try again.",
  assessmentRetry: "Retry assessment",

  capstoneEyebrow: "Auditable capstone",
  capstoneTitle: "Build CourseOps—or audit a public server",
  capstoneBody: "Both tracks submit the same evidence classes. Check an item only when another person could inspect it without relying on your memory.",
  capstoneCredentialNotice: "This checklist is private self-attestation, not an independently verified certificate or credential. For a formal learning claim, ask a qualified reviewer to inspect the evidence pack.",
  capstoneDownloadPack: "Download evidence-pack template",
  capstoneDownloadFixture: "Download CourseOps fixture",
  capstoneBuilderTitle: "Builder track",
  capstoneBuilderBody: "Implement a small server and policy-aware client, then connect one real host.",
  capstoneAuditorTitle: "Auditor track",
  capstoneAuditorBody: "Reproduce and review a public server with synthetic data, immutable evidence, and a threat model.",
  capstoneReadyTemplate: "Evidence classes ready: {count}/{total}",
  capstoneMarked: "Capstone evidence marked complete ✓",
  capstoneMark: "Mark capstone evidence complete",

  lessonBreadcrumbAria: "Breadcrumb",
  lessonCourseBack: "MCP Course 10",
  lessonTemplate: "Lesson {order}",
  lessonCourseNavAria: "MCP course lessons",
  lessonMinutesTemplate: "{minutes} min",
  lessonConceptsAria: "Concepts in this lesson",
  lessonStatusCore: "Core spec",
  lessonStatusOptional: "Optional",
  lessonStatusPractice: "Tooling / practice",
  lessonStatusExtension: "Extension",
  lessonStatusDeprecated: "Deprecated",
  lessonStatusRemoved: "Absent from 2026-07-28 core · legacy only",
  lessonObjectiveEyebrow: "Observable objective",
  lessonObjectiveTitle: "After this lesson, you can…",
  lessonExtensionEyebrow: "Independent version manifest",
  lessonExtensionTitle: "Do not inherit the core version onto extensions.",
  lessonExtensionBody: "These records freeze the exact evidence used by this course. Re-check them before implementation because maturity and extension revisions can move independently of MCP 2026-07-28.",
  lessonExtensionTableAria: "MCP extension version and maturity table",
  lessonExtensionColumn: "Extension",
  lessonMaturityColumn: "Maturity",
  lessonRevisionColumn: "Frozen revision",
  lessonFallbackColumn: "Fallback boundary",
  lessonMaturityStable: "stable",
  lessonMaturityDraft: "draft",
  lessonMaturityDated: "dated specification",
  lessonObservedTemplate: "observed {date}",
  lessonFiguresEyebrow: "Interface evidence",
  lessonFiguresTitle: "Read the pixels, then read the boundary.",
  lessonPracticeEyebrow: "Deliberate practice",
  lessonKeepEvidence: "Keep the evidence",
  lessonEvidenceTitle: "Evidence to retain",
  lessonSafetyLabel: "Safety boundary:",
  lessonReferenceEyebrow: "Runnable reference",
  lessonReferenceTitle: "Inspect a tested CourseOps wire fixture",
  lessonReferenceBody: "This small, synthetic Node.js fixture demonstrates the course’s 2026-07-28 request envelope, discovery, tools, resources, prompts, validation, dry-run writes, conflicts, and notification no-response rule. It complements—rather than replaces—a current official SDK.",
  lessonReferenceDownload: "Download tested fixture (.zip)",
  lessonTakeawayLabel: "Takeaway —",
  lessonSourcesEyebrow: "Evidence ledger",
  lessonSourcesTitle: "Sources used in this lesson",
  lessonSourceAccessedTemplate: "{publisher} · accessed {date}",
  lessonSourceTierNormative: "normative",
  lessonSourceTierOfficial: "official guide",
  lessonSourceTierAcademy: "academy",
  lessonSourceTierPractitioner: "practitioner",
  lessonNavigationAria: "Lesson navigation",
  lessonPrevious: "Previous",
  lessonNext: "Next",
  lessonFinish: "Finish",
  lessonFinalAssessment: "Final assessment",

  figureEvidenceDirect: "Direct MCP UI",
  figureEvidenceInventory: "Host inventory",
  figureEvidenceContext: "Host context only",
  figureEvidenceDesign: "Documentation design example",
  figureLegacyBanner: "Legacy UI evidence · not a current wire template",
  figureLookFor: "Look for:",
  figureAttributionTemplate: "{publisher} · {rights} · observed {date}",
  figureOpenSource: "Open first-party source",
  externalNewTab: "opens in a new tab",

  checkEyebrow: "Knowledge check",
  checkChooseOne: "Choose one answer",
  checkAnswer: "Check answer",
  checkCorrect: "Correct.",
  checkReview: "Review this one.",

  completionEyebrow: "Evidence checkpoint",
  completionTitle: "Did you complete the practice and keep its evidence?",
  completionBody: "Mark this lesson only after the named artifacts exist. Progress stays in this browser.",
  completionStorageUnavailable: "Browser storage is unavailable; this page session will remember progress only until you refresh or close it.",
  completionMarked: "Marked complete ✓",
  completionMark: "Mark lesson complete",

  labEyebrow: "Interactive practice",
  labBody: "Change the controls and explain the invariant in your own words before continuing.",
  labArchitectureTitle: "Trust-boundary workbench",
  labEnvelopeTitle: "Current-envelope workbench",
  labToolTitle: "Tool-contract builder",
  labRiskTitle: "Risk decision drill",
  labParticipantMapAria: "MCP participant map",
  labHost: "HOST",
  labHostSummary: "Model + policy + UX",
  labClientA: "Client A",
  labClientB: "Client B",
  labLocalServer: "Local server",
  labRemoteServer: "Remote server",
  labChooseParticipant: "Choose an MCP participant",
  labOwnsTemplate: "{participant} owns",
  labMustNot: "Must not",
  labCurrentMethod: "Current method",
  labEnvelopeDescription: "The generated JSON below contains a JSON-RPC request ID and method, method-specific parameters, then the required protocol version and client capabilities inside params._meta.",
  labRequiredLabel: "Required:",
  labRequiredBody: "protocol version and client capabilities on every request.",
  labRecommendedLabel: "Recommended:",
  labRecommendedBody: "self-reported clientInfo for display and debugging, never authorization.",
  labCurrentResultLabel: "Current result:",
  labCurrentResultBody: "a successful response declares resultType, normally complete.",
  labToolName: "Namespaced tool name",
  labHasSideEffect: "Has a side effect",
  labSupportsDryRun: "Supports dry run",
  labAcceptUnknown: "Accept unknown fields",
  labGuardrails: "contract guardrails",
  labGeneratedJsonAria: "Generated tool contract JSON",
  labAnnotationsNote: "Annotations help a host explain risk. They do not enforce the behavior shown here.",
  labRiskAllow: "allow",
  labRiskReview: "review",
  labRiskConfirm: "confirm",
  labRiskBlock: "block",
  labRiskChoiceAriaTemplate: "Choose a response for: {case}",
  labRiskButtonAriaTemplate: "{level} for: {case}",
  labDefensible: "Defensible choice.",
  labBestAnswerTemplate: "Best answer: {level}.",
} as const;

export type McpUiKey = keyof typeof MCP_ENGLISH_UI_COPY;
export type McpUiCopy = Readonly<Record<McpUiKey, string>>;

export interface McpCourseCopy {
  readonly _meta: McpCopyMetadata;
  readonly meta: {
    readonly title: string;
    readonly shortTitle: string;
    readonly kicker: string;
    readonly summary: string;
    readonly audience: string;
    readonly sourceNote: string;
    readonly localeNote: string;
  };
  readonly ui: McpUiCopy;
  readonly units: Readonly<Record<string, { readonly title: string; readonly summary: string }>>;
  readonly concepts: Readonly<Record<string, { readonly label: string }>>;
  readonly lessons: Readonly<Record<string, McpLocalizedLessonCopy>>;
  readonly assessment: Readonly<Record<string, McpLocalizedAssessmentCopy>>;
  readonly figures: Readonly<Record<string, McpLocalizedFigureCopy>>;
  readonly sourceNotes: Readonly<Record<string, string>>;
  readonly claims: Readonly<Record<string, string>>;
  readonly extensions: Readonly<Record<string, McpLocalizedExtensionCopy>>;
  readonly capstone: McpCapstoneCopy;
  readonly interactive: McpInteractiveCopy;
}
