import type { McpFigure } from "./types";

const INSPECTOR_SOURCE = "https://modelcontextprotocol.io/docs/2026-07-28/tools/inspector/web";

export const MCP_FIGURES = [
  {
    id: "inspector-settings",
    src: "/courses/mcp/figures/inspector-settings.png",
    webpSrc: "/courses/mcp/figures/inspector-settings-1600.webp",
    mobileWebpSrc: "/courses/mcp/figures/inspector-settings-960.webp",
    width: 3840,
    height: 2160,
    alt: "MCP Inspector server settings showing protocol era, pagination, network-log, extension, header, metadata, timeout, and roots controls.",
    caption: "This real settings panel exposes protocol-era and test controls, advertised Tasks and Apps extensions, headers, metadata, timeouts, and a legacy roots compatibility field.",
    teachingPoint: "A green connection is only a transport check; capabilities and behavior still need inspection.",
    evidenceClass: "direct-mcp-ui",
    legacyNote: "The Protocol Era control is set to Legacy (2025-11-25 handshake), and roots is deprecated. For a new design, select or probe Modern 2026-07-28 and verify the resulting envelope.",
    sourceUrl: INSPECTOR_SOURCE,
    publisher: "Model Context Protocol",
    observedOn: "2026-08-23",
    rights: "MCP documentation · CC BY 4.0",
    sha256: "74662c86b620e80d89e090ef54c1c208e9eca2d7c1aa8f2da10ef8bbdc2b717e",
  },
  {
    id: "inspector-tools",
    src: "/courses/mcp/figures/inspector-tools.png",
    webpSrc: "/courses/mcp/figures/inspector-tools-1600.webp",
    mobileWebpSrc: "/courses/mcp/figures/inspector-tools-960.webp",
    width: 3840,
    height: 2160,
    alt: "MCP Inspector Tools tab with get_weather selected and a successful result.",
    caption: "A real Tools tab separates discovery, arguments, invocation, and returned content so each contract can be tested directly.",
    teachingPoint: "Inspect a tool schema and its failure behavior before allowing an LLM to select it.",
    evidenceClass: "direct-mcp-ui",
    sourceUrl: INSPECTOR_SOURCE,
    publisher: "Model Context Protocol",
    observedOn: "2026-08-23",
    rights: "MCP documentation · CC BY 4.0",
    sha256: "8426d6390853b5663bb445df8e0d5dc48435fc02d6885d5b2d294853b4bedae6",
  },
  {
    id: "inspector-resources",
    src: "/courses/mcp/figures/inspector-resources.png",
    webpSrc: "/courses/mcp/figures/inspector-resources-1600.webp",
    mobileWebpSrc: "/courses/mcp/figures/inspector-resources-960.webp",
    width: 3840,
    height: 2160,
    alt: "MCP Inspector Resources tab showing discoverable resources and resource templates.",
    caption: "Resources are addressable context: the host can list, select, read, cache, and sometimes subscribe to them.",
    teachingPoint: "A resource URI is an identity and access boundary, not merely a file path.",
    evidenceClass: "direct-mcp-ui",
    legacyNote: "Legacy subscription UI is visible. Current clients use subscriptions/listen; do not copy older resources/subscribe behavior.",
    sourceUrl: INSPECTOR_SOURCE,
    publisher: "Model Context Protocol",
    observedOn: "2026-08-23",
    rights: "MCP documentation · CC BY 4.0",
    sha256: "868247257b143b800ee446b41fc7ce45fca31ae0673b4ed4f29ca1712c745078",
  },
  {
    id: "inspector-prompts",
    src: "/courses/mcp/figures/inspector-prompts.png",
    webpSrc: "/courses/mcp/figures/inspector-prompts-1600.webp",
    mobileWebpSrc: "/courses/mcp/figures/inspector-prompts-960.webp",
    width: 3840,
    height: 2160,
    alt: "MCP Inspector Prompts tab with a prompt template and arguments.",
    caption: "Prompts are discoverable, user-invoked templates; this UI keeps their arguments and rendered messages visible.",
    teachingPoint: "Prompts guide model interaction, but they do not grant authority or replace a tool permission boundary.",
    evidenceClass: "direct-mcp-ui",
    sourceUrl: INSPECTOR_SOURCE,
    publisher: "Model Context Protocol",
    observedOn: "2026-08-23",
    rights: "MCP documentation · CC BY 4.0",
    sha256: "f1395e4719c303365269e135e59a03c673753270a8587560e4145955de258cb6",
  },
  {
    id: "inspector-protocol",
    src: "/courses/mcp/figures/inspector-protocol.png",
    webpSrc: "/courses/mcp/figures/inspector-protocol-1600.webp",
    mobileWebpSrc: "/courses/mcp/figures/inspector-protocol-960.webp",
    width: 3840,
    height: 2160,
    alt: "MCP Inspector Protocol tab marked Legacy, showing a tools/call request and JSON-RPC response from an earlier protocol era.",
    caption: "The Protocol tab is visibly marked LEGACY in this capture. It still teaches trace reading—direction, method, parameters, latency, result, and status—but its envelope is not a 2026-07-28 template.",
    teachingPoint: "When a host UI says only ‘failed,’ the wire trace shows which layer actually failed.",
    evidenceClass: "direct-mcp-ui",
    legacyNote: "Legacy capture: this request omits the current per-request metadata and resultType. Use the lesson’s generated envelope for 2026-07-28.",
    sourceUrl: INSPECTOR_SOURCE,
    publisher: "Model Context Protocol",
    observedOn: "2026-08-23",
    rights: "MCP documentation · CC BY 4.0",
    sha256: "7abdc6df52d3dc9e28d6d91183507c2adab06971e8ce6d9e72dfd031146973b3",
  },
  {
    id: "inspector-apps",
    src: "/courses/mcp/figures/inspector-apps.png",
    webpSrc: "/courses/mcp/figures/inspector-apps-1600.webp",
    mobileWebpSrc: "/courses/mcp/figures/inspector-apps-960.webp",
    width: 3840,
    height: 2160,
    alt: "MCP Inspector Apps tab rendering an interactive MCP App.",
    caption: "MCP Apps add a sandboxed interactive surface to a tool-and-resource contract; support is negotiated as an extension.",
    teachingPoint: "The iframe is presentation, while tool authorization and server-side validation remain the control plane.",
    evidenceClass: "direct-mcp-ui",
    sourceUrl: INSPECTOR_SOURCE,
    publisher: "Model Context Protocol",
    observedOn: "2026-08-23",
    rights: "MCP documentation · CC BY 4.0",
    sha256: "2a436610093a2c11e229fd8fa3bc8126dbed715b1b02e694f940a911ba91a04a",
  },
  {
    id: "gemini-cli-mcp-inventory",
    src: "/courses/mcp/figures/gemini-cli-mcp-inventory.png",
    webpSrc: "/courses/mcp/figures/gemini-cli-mcp-inventory-1600.webp",
    mobileWebpSrc: "/courses/mcp/figures/gemini-cli-mcp-inventory-960.webp",
    width: 1692,
    height: 952,
    alt: "Gemini CLI 0.56.0 terminal UI listing MCP management commands and two synthetic configured servers, with Everything connected and modern-only CourseOps disconnected.",
    caption: "Gemini CLI 0.56.0 exposes add, remove, list, enable, and disable commands, then reports connection status for two synthetic local configurations. A status is evidence to investigate—not a root-cause diagnosis.",
    teachingPoint: "Host inventory proves what the product configured and observed; protocol compatibility still needs a versioned wire trace.",
    evidenceClass: "host-inventory",
    legacyNote: "Gemini CLI 0.56.0 uses a legacy-era MCP SDK path. The connected Everything server demonstrates host UI status, while the modern-only CourseOps server is visibly disconnected; neither line proves 2026-07-28 wire support.",
    sourceUrl: "https://github.com/google-gemini/gemini-cli/releases/tag/v0.56.0",
    publisher: "Google",
    observedOn: "2026-08-24",
    rights: "Course-authored terminal capture of Apache-2.0 Gemini CLI output; privacy crop removes window chrome and user name; no endorsement",
    sha256: "b0e6bc2c964f005691e1dea2d1a5200b085edc5440c66e07da1749efeda29489",
  },
  {
    id: "codex-cli-mcp-configuration",
    src: "/courses/mcp/figures/codex-cli-mcp-configuration.png",
    webpSrc: "/courses/mcp/figures/codex-cli-mcp-configuration-1600.webp",
    mobileWebpSrc: "/courses/mcp/figures/codex-cli-mcp-configuration-960.webp",
    width: 1692,
    height: 952,
    alt: "OpenAI Codex CLI 0.149.1 terminal UI showing the experimental MCP 2026-07-28 feature enabled and a synthetic CourseOps stdio server configuration with a masked protocol environment marker.",
    caption: "Codex CLI 0.149.1 shows a synthetic stdio server’s effective tool filters and a masked 2026-07-28 marker. The feature is visibly under development; this command reads configuration and does not establish a live MCP connection.",
    teachingPoint: "Configuration UI can verify declared transport and filters, but only a connection trace can verify negotiation and behavior.",
    evidenceClass: "host-inventory",
    legacyNote: "Codex 0.149.1 keeps MCP 2026-07-28 support experimental and off by default. A real modern stdio session requires both client feature enablement and the per-server protocol marker.",
    sourceUrl: "https://github.com/openai/codex/releases/tag/rust-v0.149.1",
    publisher: "OpenAI",
    observedOn: "2026-08-24",
    rights: "Course-authored terminal capture of Apache-2.0 Codex CLI output with upstream NOTICE; privacy crop removes window chrome and user name; no endorsement",
    sha256: "d2be69914c0dccfc39761554f4635f2a42fd360991cede0273fa6141644fe95c",
  },
] as const satisfies readonly McpFigure[];

export const MCP_FIGURE_BY_ID = Object.fromEntries(
  MCP_FIGURES.map((figure) => [figure.id, figure]),
) as Readonly<Record<string, McpFigure>>;
