import type { McpSource } from "./types";

export const MCP_SOURCES = [
  {
    id: "mcp-architecture",
    title: "Architecture overview",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://modelcontextprotocol.io/docs/2026-07-28/learn/architecture",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Current participant, layer, statelessness, discovery, primitive, and transport model.",
  },
  {
    id: "mcp-spec-overview",
    title: "MCP specification: Overview",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/basic",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative base protocol, metadata, JSON-RPC message, and required-component rules.",
  },
  {
    id: "mcp-changelog",
    title: "MCP specification: 2026-07-28 changelog",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/changelog",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative record of the stateless, handshake-free core and other revision-level changes.",
  },
  {
    id: "mcp-versioning",
    title: "MCP specification: Versioning",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/basic/versioning",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative version selection, unsupported-version response, and compatibility rules.",
  },
  {
    id: "mcp-discovery",
    title: "MCP specification: Server discovery",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/server/discover",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative server/discover exchange, version compatibility, identity, capabilities, and TTL.",
  },
  {
    id: "mcp-tools",
    title: "MCP specification: Tools",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/server/tools",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative tool discovery and invocation, JSON Schema 2020-12, structured output, and trust rules.",
  },
  {
    id: "mcp-resources",
    title: "MCP specification: Resources",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/server/resources",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative resources, URI templates, reads, list changes, and resource subscriptions.",
  },
  {
    id: "mcp-prompts",
    title: "MCP specification: Prompts",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/server/prompts",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative user-controlled prompt discovery, retrieval, arguments, and list changes.",
  },
  {
    id: "mcp-completion",
    title: "MCP specification: Argument completion",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/server/utilities/completion",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative completion support for prompt arguments and resource-template variables.",
  },
  {
    id: "mcp-elicitation",
    title: "MCP specification: Elicitation",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/client/elicitation",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative form and URL modes, user control, and the prohibition on collecting secrets in form mode.",
  },
  {
    id: "mcp-mrtr",
    title: "MCP specification: Multi round-trip requests",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/basic/patterns/mrtr",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative InputRequiredResult, retry, requestState, and nested input-response mechanics.",
  },
  {
    id: "mcp-transports",
    title: "MCP specification: Transports",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/basic/transports",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative stdio and Streamable HTTP framing and interoperability requirements.",
  },
  {
    id: "mcp-stdio",
    title: "MCP specification: stdio transport",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/basic/transports/stdio",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative newline-delimited stdio framing and the stdout-only protocol boundary.",
  },
  {
    id: "mcp-streamable-http",
    title: "MCP specification: Streamable HTTP transport",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/basic/transports/streamable-http",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative per-request POST, JSON or request-scoped SSE responses, MCP headers, and header/body consistency rules.",
  },
  {
    id: "mcp-subscriptions",
    title: "MCP specification: Subscriptions",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/basic/patterns/subscriptions",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative listen stream, acknowledgement, filters, notification correlation, and cancellation.",
  },
  {
    id: "mcp-progress",
    title: "MCP specification: Progress",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/basic/patterns/progress",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative progress tokens and notifications/progress reporting.",
  },
  {
    id: "mcp-cancellation",
    title: "MCP specification: Cancellation",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/basic/patterns/cancellation",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative transport-specific cooperative cancellation: close a Streamable HTTP request’s SSE response stream; use notifications/cancelled for stdio and applicable custom transports.",
  },
  {
    id: "mcp-auth",
    title: "MCP specification: Authorization",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/basic/authorization",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative OAuth-based authorization for HTTP transports, metadata discovery, resource indicators, and registration.",
  },
  {
    id: "mcp-auth-security",
    title: "MCP specification: Authorization security considerations",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/basic/authorization/security-considerations",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative OAuth security requirements including token audience, confused-deputy defenses, and redirect validation.",
  },
  {
    id: "mcp-security",
    title: "MCP security best practices",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://modelcontextprotocol.io/docs/2026-07-28/tutorials/security/security_best_practices",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Current threat guidance including state handle hijacking, token passthrough, SSRF, DNS rebinding, and local-server risks.",
  },
  {
    id: "mcp-caching",
    title: "MCP specification: Caching",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/server/utilities/caching",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative ttlMs, public/private cache scope, and cacheable complete-result behavior.",
  },
  {
    id: "mcp-pagination",
    title: "MCP specification: Pagination",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/server/utilities/pagination",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative opaque cursor and nextCursor behavior, including empty-string cursors.",
  },
  {
    id: "mcp-schema",
    title: "MCP specification: Schema reference",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/schema",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Normative method, result, error, content-block, annotation, and metadata types.",
  },
  {
    id: "mcp-inspector",
    title: "MCP Inspector: Web interface",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://modelcontextprotocol.io/docs/2026-07-28/tools/inspector/web",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "First-party interface guide and source for the Inspector figures used in this course.",
  },
  {
    id: "mcp-build-server",
    title: "Build an MCP server",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://modelcontextprotocol.io/docs/2026-07-28/develop/build-server",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Current Python and TypeScript quickstart and its stdio logging boundary.",
  },
  {
    id: "mcp-build-client",
    title: "Build an MCP client",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://modelcontextprotocol.io/docs/2026-07-28/develop/build-client",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Current client connection, discovery, invocation, and model-integration workflow.",
  },
  {
    id: "mcp-sdk",
    title: "MCP SDKs",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://modelcontextprotocol.io/docs/2026-07-28/sdk",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Current SDK support tiers and version-specific implementation entry points.",
  },
  {
    id: "mcp-deprecated",
    title: "MCP specification: Deprecated features",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/deprecated",
    accessedOn: "2026-08-23",
    protocolVersion: "2026-07-28",
    note: "Current registry for roots, sampling, logging, DCR, legacy context flags, and HTTP+SSE deprecations.",
  },
  {
    id: "mcp-registry",
    title: "The MCP Registry",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://modelcontextprotocol.io/registry/about",
    accessedOn: "2026-08-23",
    note: "Preview status, namespace verification, metadata scope, and the registry-versus-marketplace boundary.",
  },
  {
    id: "mcp-apps",
    title: "MCP Apps extension",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://modelcontextprotocol.io/extensions/apps/overview",
    accessedOn: "2026-08-23",
    note: "Interactive UI resources, sandboxed rendering, postMessage bridge, and extension support caveats.",
  },
  {
    id: "mcp-extensions",
    title: "MCP extensions overview",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://modelcontextprotocol.io/extensions/overview",
    accessedOn: "2026-08-23",
    note: "Extension lifecycle, explicit capability negotiation, support variability, and independent versioning.",
  },
  {
    id: "mcp-extension-matrix",
    title: "MCP extension support matrix",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://modelcontextprotocol.io/extensions/client-matrix",
    accessedOn: "2026-08-24",
    note: "Community-maintained discovery aid that may be incomplete or inaccurate; effective support still requires negotiated capabilities, current host documentation, and a trace.",
  },
  {
    id: "mcp-apps-spec",
    title: "MCP Apps specification: 2026-01-26 snapshot",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://github.com/modelcontextprotocol/ext-apps/blob/10195ad91851502134930e9b80ec2c04e277a720/specification/2026-01-26/apps.mdx",
    accessedOn: "2026-08-24",
    note: "Immutable independently versioned Apps extension contract. Its dated initialize example is legacy core syntax and must be translated through the current per-request capability model.",
  },
  {
    id: "mcp-auth-extensions",
    title: "MCP authorization extensions",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://modelcontextprotocol.io/extensions/auth/overview",
    accessedOn: "2026-08-23",
    note: "Overview of supplementary, explicitly negotiated authorization mechanisms.",
  },
  {
    id: "mcp-auth-extension-status",
    title: "MCP authorization extensions: immutable status registry",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://github.com/modelcontextprotocol/ext-auth/blob/fb374c7db2b34f18ca9183882e0beecdf661892b/README.md",
    accessedOn: "2026-08-24",
    note: "Frozen extension status evidence: Enterprise-Managed Authorization is Stable; OAuth Client Credentials is Draft; both are optional and independently versioned.",
  },
  {
    id: "mcp-client-credentials",
    title: "OAuth Client Credentials extension",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://modelcontextprotocol.io/extensions/auth/oauth-client-credentials",
    accessedOn: "2026-08-23",
    note: "Machine-to-machine OAuth client-credentials extension and its deployment boundary.",
  },
  {
    id: "mcp-enterprise-auth",
    title: "Enterprise-Managed Authorization extension",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://modelcontextprotocol.io/extensions/auth/enterprise-managed-authorization",
    accessedOn: "2026-08-23",
    note: "Centralized identity-provider policy for enterprise MCP authorization.",
  },
  {
    id: "mcp-tasks",
    title: "MCP Tasks extension",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://modelcontextprotocol.io/extensions/tasks/overview",
    accessedOn: "2026-08-23",
    note: "Durable long-running work, polling, input_required, result retrieval, and cooperative cancellation.",
  },
  {
    id: "mcp-tasks-spec",
    title: "MCP Tasks draft specification",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://github.com/modelcontextprotocol/ext-tasks/blob/e4345978be1f602f1fc48d89051e8559dd5302a6/specification/draft/tasks.md",
    accessedOn: "2026-08-24",
    note: "Immutable draft Tasks contract: currently augments tools/call only; defines required task timestamps and nullable TTL plus an optional polling interval.",
  },
  {
    id: "mcp-feature-lifecycle",
    title: "MCP feature lifecycle",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://modelcontextprotocol.io/community/feature-lifecycle",
    accessedOn: "2026-08-24",
    note: "Lifecycle vocabulary for Active, Deprecated, and formally Removed features; breaking-revision absence is labelled separately in this course.",
  },
  {
    id: "mcp-subscriptions-clarification",
    title: "Subscriptions graceful-completion clarification",
    publisher: "Model Context Protocol",
    tier: "normative",
    url: "https://github.com/modelcontextprotocol/modelcontextprotocol/commit/71f7c162e42ea1cd6ca88d83c70d89324fb6b0da",
    accessedOn: "2026-08-24",
    protocolVersion: "2026-07-28",
    note: "Compatible 2026-07-29 clarification: a server-initiated graceful listen shutdown should send a successful completion result before closing.",
  },
  {
    id: "mcp-roadmap",
    title: "MCP roadmap: August 2026",
    publisher: "Model Context Protocol",
    tier: "official-guide",
    url: "https://blog.modelcontextprotocol.io/posts/mcp-roadmap/",
    accessedOn: "2026-08-24",
    note: "Future-watchlist only. Roadmap priorities are prospective and do not become current core until a normative revision or independently versioned extension says so.",
  },
  {
    id: "claude-academy-intro",
    title: "Introduction to Model Context Protocol",
    publisher: "Anthropic",
    tier: "academy",
    url: "https://academy.claude.com/courses/introduction-to-model-context-protocol",
    accessedOn: "2026-08-23",
    note: "Conceptual and hands-on learning sequence; dated protocol details are checked against the current normative specification.",
  },
  {
    id: "claude-academy-advanced",
    title: "Model Context Protocol: Advanced Topics",
    publisher: "Anthropic",
    tier: "academy",
    url: "https://academy.claude.com/courses/model-context-protocol-advanced-topics",
    accessedOn: "2026-08-23",
    note: "Historical curriculum cross-check only: its sampling, logging, roots, stateful HTTP, and server-initiated-request lessons predate the stateless 2026 core and are not implementation guidance.",
  },
  {
    id: "anthropic-mcp",
    title: "Connect Claude Code to tools via MCP",
    publisher: "Anthropic",
    tier: "official-guide",
    url: "https://code.claude.com/docs/en/mcp",
    accessedOn: "2026-08-23",
    note: "Current Claude Code product documentation for local stdio and remote HTTP servers, configuration scopes, OAuth, tool controls, and the /mcp interface.",
  },
  {
    id: "claude-desktop-mcp",
    title: "Getting Started with Local MCP Servers on Claude Desktop",
    publisher: "Anthropic",
    tier: "official-guide",
    url: "https://support.claude.com/en/articles/10949351-getting-started-with-local-mcp-servers-on-claude-desktop",
    accessedOn: "2026-08-23",
    note: "Current Claude Desktop workflow for installing and developing local MCP desktop extensions; local packages execute with local-machine authority and require review.",
  },
  {
    id: "claude-remote-mcp",
    title: "Get started with custom connectors using remote MCP",
    publisher: "Anthropic",
    tier: "official-guide",
    url: "https://support.claude.com/en/articles/11175166-get-started-with-custom-connectors-using-remote-mcp",
    accessedOn: "2026-08-23",
    note: "Current Claude custom-connector workflow and the important boundary that remote connections originate from Anthropic cloud infrastructure.",
  },
  {
    id: "openai-codex-mcp",
    title: "Model Context Protocol in Codex",
    publisher: "OpenAI",
    tier: "official-guide",
    url: "https://learn.chatgpt.com/docs/extend/mcp",
    accessedOn: "2026-08-23",
    note: "Official Codex, IDE, CLI, and ChatGPT MCP configuration, authentication, and approval controls.",
  },
  {
    id: "openai-codex-0149-release",
    title: "Codex CLI 0.149.1 release and source",
    publisher: "OpenAI",
    tier: "official-guide",
    url: "https://github.com/openai/codex/releases/tag/rust-v0.149.1",
    accessedOn: "2026-08-24",
    note: "Exact first-party release used for the course-authored configuration capture; the MCP 2026-07-28 feature is under development and disabled by default.",
  },
  {
    id: "openai-codex-0149-license",
    title: "Codex CLI 0.149.1 Apache-2.0 license and NOTICE",
    publisher: "OpenAI",
    tier: "official-guide",
    url: "https://github.com/openai/codex/blob/ff29a44391deccde0aba0f8390337d7f3c319ea4/LICENSE",
    accessedOn: "2026-08-24",
    note: "Immutable license evidence for the captured open-source client; the separate NOTICE is retained in the asset manifest and no trademark rights or endorsement are claimed.",
  },
  {
    id: "openai-responses-mcp",
    title: "Connectors and remote MCP servers in the Responses API",
    publisher: "OpenAI",
    tier: "official-guide",
    url: "https://developers.openai.com/api/docs/guides/tools-connectors-mcp",
    accessedOn: "2026-08-23",
    note: "Official Responses API remote-server shape, OAuth, allowed tools, and approval behavior.",
  },
  {
    id: "openai-academy-mcp",
    title: "MCP for Builders",
    publisher: "OpenAI",
    tier: "academy",
    url: "https://academy.openai.com/public/clubs/builders-etkn1/resources/mcp-for-builders",
    accessedOn: "2026-08-23",
    note: "OpenAI Academy framing and builder resources, interpreted as educational guidance rather than protocol law.",
  },
  {
    id: "openai-apps-ui",
    title: "Add UI to your MCP server",
    publisher: "OpenAI",
    tier: "official-guide",
    url: "https://developers.openai.com/plugins/build/chatgpt-ui",
    accessedOn: "2026-08-23",
    note: "Official MCP Apps-compatible component flow. It remains linked design guidance; its screenshots are not redistributed because the page does not grant an explicit open image license.",
  },
  {
    id: "google-gemini-mcp",
    title: "Gemini CLI developer use cases: MCP servers",
    publisher: "Google",
    tier: "official-guide",
    url: "https://codelabs.developers.google.com/genai-for-dev-cli-dev-use-cases#17",
    accessedOn: "2026-08-23",
    note: "Official Gemini CLI server configuration and /mcp user interface. Use the dated host workflow only: do not copy legacy transport/server choices, and do not treat page-level text licensing as an image-reuse grant.",
  },
  {
    id: "google-gemini-mcp-current",
    title: "MCP servers with Gemini CLI",
    publisher: "Google",
    tier: "official-guide",
    url: "https://geminicli.com/docs/tools/mcp-server/",
    accessedOn: "2026-08-23",
    note: "Current Gemini CLI configuration, server allow/exclude controls, /mcp inventory, tool filtering, confirmation, and management commands.",
  },
  {
    id: "google-gemini-056-release",
    title: "Gemini CLI 0.56.0 release and source",
    publisher: "Google",
    tier: "official-guide",
    url: "https://github.com/google-gemini/gemini-cli/releases/tag/v0.56.0",
    accessedOn: "2026-08-24",
    note: "Exact first-party release used for the course-authored host-inventory capture; its MCP SDK path is legacy-era rather than evidence of 2026-07-28 wire compatibility.",
  },
  {
    id: "google-gemini-056-license",
    title: "Gemini CLI 0.56.0 Apache-2.0 license",
    publisher: "Google",
    tier: "official-guide",
    url: "https://github.com/google-gemini/gemini-cli/blob/b6e23a7dc29eb15fede4bbe646d91869e948b45a/LICENSE",
    accessedOn: "2026-08-24",
    note: "Immutable Apache-2.0 source-license evidence for the captured client; Google and Gemini marks remain separate and no endorsement is implied.",
  },
  {
    id: "google-gemini-cli-transition",
    title: "Gemini CLI transition for individual Google AI plans",
    publisher: "Google",
    tier: "official-guide",
    url: "https://github.com/google-gemini/gemini-cli/discussions/28017",
    accessedOn: "2026-08-24",
    note: "Official product-boundary notice: individual Google AI plan access moved to Antigravity CLI, while enterprise Code Assist and API-key paths remain distinct.",
  },
  {
    id: "google-github-mcp",
    title: "Gemini CLI code analysis: GitHub MCP",
    publisher: "Google",
    tier: "official-guide",
    url: "https://codelabs.developers.google.com/gemini-cli-code-analysis#7",
    accessedOn: "2026-08-23",
    note: "Official GitHub MCP connection example and host-visible tool inventory. Do not copy its broad classic PAT in project settings; use secure injection, least privilege, and the maintained GitHub server.",
  },
  {
    id: "github-mcp-server",
    title: "GitHub MCP Server",
    publisher: "GitHub",
    tier: "practitioner",
    url: "https://github.com/github/github-mcp-server",
    accessedOn: "2026-08-23",
    note: "First-party production server with toolsets, read-only mode, fine-grained configuration, and beta dynamic toolset discovery for supported local deployments; dynamic discovery is unavailable in the Remote GitHub MCP Server.",
  },
  {
    id: "github-experience-tool-scope",
    title: "Addressing GitHub MCP's Key Issues: Token Scopes, Verbose Prompts, and Lack of Project Context · Issue #1683",
    publisher: "GitHub",
    tier: "practitioner",
    url: "https://github.com/github/github-mcp-server/issues/1683",
    accessedOn: "2026-08-23",
    note: "One user reports project-context, token-scope, and verbose-interaction friction; treat it as a design tension, not prevalence, and migrate roots suggestions to explicit parameters, resource URIs, or configuration.",
  },
  {
    id: "github-experience-write-auth",
    title: "Docker MCP Toolkit OAuth integration returns 403 on write operations · Issue #1314",
    publisher: "GitHub",
    tier: "practitioner",
    url: "https://github.com/github/github-mcp-server/issues/1314",
    accessedOn: "2026-08-23",
    note: "One Docker MCP Toolkit setup reported successful reads but failed writes; later maintainer context ties step-up scopes to client support, so it illustrates compatibility rather than a universal current defect.",
  },
  {
    id: "github-experience-scope-challenges",
    title: "Scope filtering/challenging · Discussion #1802",
    publisher: "GitHub",
    tier: "practitioner",
    url: "https://github.com/github/github-mcp-server/discussions/1802",
    accessedOn: "2026-08-23",
    note: "Maintainer announcement of one implementation's interactive re-authorization, static-scope tool filtering, and server-to-server token behavior; support is not universal across clients.",
  },
  {
    id: "github-experience-research-timeout",
    title: "Improve reranker handling to avoid MCP timeouts during semantic search · Issue #283",
    publisher: "Community project",
    tier: "practitioner",
    url: "https://github.com/54yyyu/zotero-mcp/issues/283",
    accessedOn: "2026-08-23",
    note: "One Windows/Zotero library report links cross-encoder reranking to a client timeout and a faster fallback; it supports layered timeout and graceful-degradation design, not a general performance claim.",
  },
  {
    id: "github-experience-knowledge-health",
    title: "MCP server connection hangs on standard read/query calls (no error, no timeout response) · Issue #268",
    publisher: "Community project",
    tier: "practitioner",
    url: "https://github.com/aaronsb/obsidian-mcp-plugin/issues/268",
    accessedOn: "2026-08-23",
    note: "One Claude Desktop and loopback-HTTP report where the plugin remained Running while calls hung; use as bounded evidence that readiness is not request health.",
  },
  {
    id: "github-experience-ops-timeout",
    title: "[BUG] Default MCP server connection timeout (5s) is too low for sidecar gateway deployments, causing intermittent ‘Failed to create MCP session’ errors · Issue #1272",
    publisher: "Community project",
    tier: "practitioner",
    url: "https://github.com/kagent-dev/kagent/issues/1272",
    accessedOn: "2026-08-23",
    note: "One EKS/sidecar report traced intermittent connection failure to layered timeout propagation; it is historical implementation evidence, not a universal timeout default.",
  },
  {
    id: "github-experience-teaching-gap",
    title: "Add New Quizzes tools (create / update quizzes and questions) · Issue #124",
    publisher: "Community project",
    tier: "practitioner",
    url: "https://github.com/bruchris/canvas-lms-mcp/issues/124",
    accessedOn: "2026-08-23",
    note: "A maintainer-described Canvas assistant workflow fell back to direct APIs because required quiz-write tools were missing; use as capability-fit evidence, not efficacy evidence.",
  },
  {
    id: "github-official-servers",
    title: "MCP reference server implementations",
    publisher: "Model Context Protocol",
    tier: "practitioner",
    url: "https://github.com/modelcontextprotocol/servers",
    accessedOn: "2026-08-23",
    note: "Reference implementations and the boundary between maintained examples and archived community servers.",
  },
  {
    id: "github-inspector",
    title: "MCP Inspector repository",
    publisher: "Model Context Protocol",
    tier: "practitioner",
    url: "https://github.com/modelcontextprotocol/inspector",
    accessedOn: "2026-08-23",
    note: "Issue and release history for the protocol debugging tool used throughout the course.",
  },
  {
    id: "github-openai-mcpkit",
    title: "OpenAI MCPKit",
    publisher: "OpenAI",
    tier: "practitioner",
    url: "https://github.com/openai/openai-mcpkit",
    accessedOn: "2026-08-23",
    note: "Authenticated enterprise-server blueprint and deployment-pattern example. Its current README implements the 2025-06-18 authorization pattern, so it is not implementation authority for MCP 2026-07-28.",
  },
  {
    id: "github-mcp-apps-examples",
    title: "MCP Apps examples",
    publisher: "Model Context Protocol",
    tier: "practitioner",
    url: "https://github.com/modelcontextprotocol/ext-apps/tree/main/examples",
    accessedOn: "2026-08-23",
    note: "Cross-framework app examples for maps, dashboards, media, workflows, and starter servers.",
  },
] as const satisfies readonly McpSource[];

export const MCP_SOURCE_BY_ID = Object.fromEntries(
  MCP_SOURCES.map((source) => [source.id, source]),
) as Readonly<Record<string, McpSource>>;
