import type { AgenticVideoEditingClaimRecord } from "./types";

const REVIEWED_ON = "2026-08-28";

/**
 * Claim-level evidence ledger for Course 20. Implementation facts, engineering
 * syntheses, fail-closed course policies, and jurisdiction-specific guidance
 * remain distinct so a repository or field signal can never impersonate a
 * standard, a law, or a release decision.
 */
export const AGENTIC_VIDEO_EDITING_CLAIMS = [
  {
    id: "m1-intent-before-mutation",
    text: "The core workflow defines audience, intended claim, acceptance checks, stopping rules, and accountable decision roles before any media mutation.",
    textZhHans: "核心工作流在任何媒体修改前先定义受众、预期主张、验收检查、停止规则和可追责决策角色。",
    support: "course-policy",
    kind: "course-fail-closed-policy",
    sourceIds: [],
    boundary: "This is the course control policy, not a universal legal rule or proof that an edit is good.",
    boundaryZhHans: "这是课程控制政策，不是普遍法律规则，也不能证明某次剪辑质量良好。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m1-misleading-edit-boundary",
    text: "For factual work, juxtaposition, commentary, or editing can materially mislead even when each source fragment is genuine.",
    textZhHans: "在事实性作品中，即使每个源片段都真实，拼接、解说或剪辑仍可能造成实质性误导。",
    support: "direct",
    kind: "implementation-fact",
    sourceIds: ["bbc-editorial-accuracy"],
    boundary: "BBC guidance is an authoritative editorial practice source for its scope; it is not presented as globally binding law.",
    boundaryZhHans: "BBC 指南在其适用范围内是权威编辑实践来源，但本课程不把它表述为全球强制法律。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m2-ffprobe-observation-boundary",
    text: "ffprobe can report container and stream information in machine-readable form, but a successful probe does not establish rights, privacy clearance, identity, or semantic accuracy.",
    textZhHans: "ffprobe 可以以机器可读形式报告容器和流信息，但成功探测并不能证明权利、隐私许可、身份或语义准确性。",
    support: "derived",
    kind: "engineering-synthesis",
    sourceIds: ["ffprobe-docs"],
    boundary: "The documentation supports media inspection; the non-rights boundary is an explicit engineering inference.",
    boundaryZhHans: "文档支持媒体检查；不能由此推断权利许可，是课程明确标出的工程推论。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m2-c2pa-provenance-not-truth",
    text: "C2PA can bind tamper-evident provenance assertions to media; its specification does not make value judgments about whether those assertions are good, bad, truthful, rights-cleared, or consensual.",
    textZhHans: "C2PA 可以把防篡改的来源声明绑定到媒体；其规范不判断这些声明是好是坏、是否真实、是否已获权利许可或同意。",
    support: "direct",
    kind: "implementation-fact",
    sourceIds: ["c2pa-spec"],
    boundary: "A valid or trusted manifest still requires a human or application to evaluate the assertions and other evidence; it does not prove truth, rights, consent, or lawful use.",
    boundaryZhHans: "即使 manifest 有效或可信，仍需人类或应用评估声明及其他证据；它不能证明真实性、权利、同意或合法使用。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m2-exact-use-rights-policy",
    text: "Course rights decisions bind exact asset bytes to use, destination, territory, term, attribution, transformation, model-upload permission, reviewer, and decision time; unknown remains blocked.",
    textZhHans: "课程权利决定把准确素材字节与用途、目的地、地域、期限、署名、变换、模型上传许可、审查者和决策时间绑定；未知状态保持阻断。",
    support: "course-policy",
    kind: "course-fail-closed-policy",
    sourceIds: [],
    boundary: "This conservative record is not legal advice and does not replace jurisdiction- and contract-specific review.",
    boundaryZhHans: "这项保守记录不是法律意见，也不能替代针对具体法域与合同的审查。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m3-rational-clocks",
    text: "Source time, timeline time, frame rate, time base, start timecode, drop-frame status, VFR packet timestamps, and audio sample clocks are distinct quantities and must not be collapsed into decimal seconds.",
    textZhHans: "源时间、时间线时间、帧率、time base、起始时间码、drop-frame 状态、VFR packet 时间戳和音频采样时钟是不同量，不能折叠成小数秒。",
    support: "derived",
    kind: "engineering-synthesis",
    sourceIds: ["ffprobe-docs", "opentimelineio-docs"],
    boundary: "Exact conform behavior remains dependent on the learner's media, decoder, proxy recipe, and recorded PTS map.",
    boundaryZhHans: "准确 conform 行为仍取决于学习者素材、decoder、proxy recipe 与已记录的 PTS 映射。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m3-machine-evidence-needs-review",
    text: "ASR, word alignment, diarization, and shot detection are evidence locators; critical names, numbers, negation, quotation boundaries, and edit points return to source media and human review.",
    textZhHans: "ASR、词级对齐、说话人分离和镜头检测只是证据定位器；关键人名、数字、否定、引语边界和剪辑点必须回到源媒体并经人工复核。",
    support: "derived",
    kind: "engineering-synthesis",
    sourceIds: ["whisper", "whisperx", "pyscenedetect"],
    boundary: "Repository capabilities do not establish accuracy for a particular language, speaker, recording, or frame boundary.",
    boundaryZhHans: "仓库能力不能证明特定语言、说话者、录音或帧边界上的准确度。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m4-j-l-cut-definition",
    text: "A J cut brings the next scene's audio in before its picture; an L cut lets the prior scene's audio continue after the picture changes.",
    textZhHans: "J cut 让下一场景的声音先于画面进入；L cut 让上一场景的声音在画面切换后继续。",
    support: "direct",
    kind: "implementation-fact",
    sourceIds: ["adobe-j-l-cuts"],
    boundary: "Adobe documents the editing practice; using it well remains a contextual editorial judgment.",
    boundaryZhHans: "Adobe 记录了这种剪辑实践；是否运用得当仍是依情境而定的编辑判断。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m4-context-preservation",
    text: "A candidate segment is acceptable only when its cut motivation, continuity, screen direction, reaction, pacing, B-roll implication, and surrounding context do not create an unsupported claim.",
    textZhHans: "候选片段只有在切点动机、连续性、视线方向、反应、节奏、B-roll 暗示及上下文都不会制造无依据主张时才可接受。",
    support: "course-policy",
    kind: "course-fail-closed-policy",
    sourceIds: ["bbc-editorial-accuracy"],
    boundary: "This is a conservative course acceptance rule informed by editorial guidance, not a guarantee against all interpretive disagreement.",
    boundaryZhHans: "这是参考编辑指南制定的保守课程验收规则，不保证消除所有解释分歧。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m5-otio-not-renderer",
    text: "OpenTimelineIO represents editorial structure and timing, but it does not decode or render media and does not automatically verify that a source range is available.",
    textZhHans: "OpenTimelineIO 表示剪辑结构与时间，但不解码或渲染媒体，也不会自动验证源区间是否可用。",
    support: "direct",
    kind: "implementation-fact",
    sourceIds: ["opentimelineio", "opentimelineio-docs"],
    boundary: "Adapter availability and round-trip fidelity vary by format and application.",
    boundaryZhHans: "Adapter 可用性与 round-trip 保真度会因格式和应用而异。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m5-production-compile-inputs",
    text: "Production compilation consumes the approved edit plan, delivery matrix, approved asset ledger, and tool policy together; edit-plan JSON alone is intentionally insufficient.",
    textZhHans: "生产编译必须共同消费已批准的 edit plan、delivery matrix、approved asset ledger 和 tool policy；单个 edit-plan JSON 被有意设计为不足以独立执行。",
    support: "course-policy",
    kind: "course-fail-closed-policy",
    sourceIds: [],
    boundary: "A runtime adapter must still prove how it maps each validated operation to a specific engine version.",
    boundaryZhHans: "Runtime adapter 仍须证明如何把每项已验证 operation 映射到具体引擎版本。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m7-caption-requirement",
    text: "WCAG 2.2 SC 1.2.2 requires captions for prerecorded audio in synchronized media unless the media is a clearly labelled text alternative; captions include relevant dialogue, speaker identity, and meaningful non-speech audio.",
    textZhHans: "WCAG 2.2 SC 1.2.2 要求为同步媒体中的预录音频提供字幕，除非媒体是明确标记的文本替代；字幕还包括相关对白、说话人身份和有意义的非语音声音。",
    support: "direct",
    kind: "implementation-fact",
    sourceIds: ["wcag-2-2-captions"],
    boundary: "Applicable law, contract, organizational policy, language practice, and destination support can require more.",
    boundaryZhHans: "适用法律、合同、机构政策、语言实践与目的地支持可能提出更高要求。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m7-accessibility-applicability",
    text: "Caption, transcript, descriptive transcript, audio-description, flash, contrast, and player-support needs are assessed against the actual media and destination, with an explicit rationale when a feature is not applicable.",
    textZhHans: "字幕、转录、描述性转录、音频描述、闪烁、对比度和播放器支持必须针对实际媒体与目的地判断；若不适用，也要给出明确理由。",
    support: "direct",
    kind: "engineering-synthesis",
    sourceIds: ["w3c-media-planning", "w3c-visual-description"],
    boundary: "The course records applicability; it does not claim that one automated check proves conformance.",
    boundaryZhHans: "课程记录适用性，但不声称单项自动检查足以证明符合要求。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m7-loudness-destination-specific",
    text: "ITU-R BS.1770 defines measurement algorithms and EBU R 128 specifies a broadcast recommendation; neither supplies one universal loudness target for every social destination.",
    textZhHans: "ITU-R BS.1770 定义测量算法，EBU R 128 给出广播建议；两者都没有为所有社交目的地提供一个通用响度目标。",
    support: "derived",
    kind: "engineering-synthesis",
    sourceIds: ["itu-bs-1770", "ebu-r128"],
    boundary: "The destination contract must record its own current target, tolerance, true-peak limit, and verification method.",
    boundaryZhHans: "目的地合同必须记录自身当前目标、容差、true-peak 上限与验证方法。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m7-color-transform-boundary",
    text: "Color management records source tags, working transform, display/output transform, scopes, and shot matching; SDR and HDR are separate delivery branches.",
    textZhHans: "色彩管理记录源标签、工作变换、显示/输出变换、示波器检查和镜头匹配；SDR 与 HDR 是不同交付分支。",
    support: "derived",
    kind: "engineering-synthesis",
    sourceIds: ["aces-docs"],
    boundary: "ACES is one color-management system, not a mandatory transform for every core-track file.",
    boundaryZhHans: "ACES 是一种色彩管理系统，并非每个 fixture-safe 文件都必须采用的变换。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m6-mcp-annotations-untrusted",
    text: "MCP tool descriptions and annotations are behavioral hints and must be treated as untrusted unless they come from a trusted server; a read-only hint is not enforcement.",
    textZhHans: "MCP 工具描述与 annotations 只是行为提示；除非来自可信服务器，否则必须视为不可信；read-only hint 并不是强制机制。",
    support: "direct",
    kind: "implementation-fact",
    sourceIds: ["model-context-protocol-spec"],
    boundary: "Trust in a server still does not remove the need for least privilege, validation, consent, and runtime containment.",
    boundaryZhHans: "信任某个 server 仍不能取消最小权限、验证、同意与 runtime containment。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m6-indirect-injection-authority",
    text: "Transcript, OCR, frame text, metadata, filenames, web content, tool descriptions, and tool results are untrusted data and cannot expand filesystem, network, credential, cost, generation, or publish authority.",
    textZhHans: "转录、OCR、画面文字、元数据、文件名、网页内容、工具描述和工具结果都是不可信数据，不能扩张文件系统、网络、凭证、成本、生成或发布权限。",
    support: "derived",
    kind: "engineering-synthesis",
    sourceIds: ["owasp-prompt-injection", "owasp-excessive-agency", "model-context-protocol-spec"],
    boundary: "Prompt wording alone is not a security boundary; enforcement belongs in tool design, identity, network, filesystem, cost, and confirmation controls.",
    boundaryZhHans: "仅靠 prompt 措辞不是安全边界；强制执行必须落在工具设计、身份、网络、文件系统、成本与确认控制。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m8-render-receipt-boundary",
    text: "A current render receipt binds exact input hashes, approved plan, delivery matrix, asset ledger, tool policy, engine/build configuration, fixed argv or code, output hash, and output probe.",
    textZhHans: "当前有效的渲染回执绑定准确输入 hash、已批准计划、delivery matrix、asset ledger、tool policy、引擎/构建配置、固定 argv 或代码、输出 hash 和输出 probe。",
    support: "course-policy",
    kind: "course-fail-closed-policy",
    sourceIds: ["ffmpeg", "ffprobe-docs"],
    boundary: "A successful process exit and decodable file do not prove semantic, accessibility, rights, or release correctness.",
    boundaryZhHans: "进程成功退出且文件可解码，不能证明语义、无障碍、权利或发布正确。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m9-qc-is-multidimensional",
    text: "Release QC separately records technical, semantic, editorial, audio, caption, color, accessibility, rights/privacy, and destination results, plus bounded repair and regression receipts.",
    textZhHans: "发布 QC 分别记录技术、语义、剪辑、音频、字幕、色彩、无障碍、权利/隐私和目的地结果，并记录有限修复与回归回执。",
    support: "course-policy",
    kind: "course-fail-closed-policy",
    sourceIds: ["wcag-2-2-captions", "itu-bs-1770", "aces-docs", "bbc-editorial-accuracy"],
    boundary: "No single metric, VMAF score, player preview, or automated checklist proves all layers.",
    boundaryZhHans: "任何单一 metric、VMAF 分数、播放器预览或自动 checklist 都不能证明全部层次。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m10-handoff-recovery-closure",
    text: "A recoverable handoff binds the current artifact graph, timeline interchange, media execution surface, relink map, secret-free runbook, interruption/resume evidence, and an independent recovery result.",
    textZhHans: "可恢复的交接绑定当前 artifact graph、时间线交换、媒体执行面、relink map、无 secret runbook、中断／续跑证据与独立恢复结果。",
    support: "derived",
    kind: "engineering-synthesis",
    sourceIds: ["opentimelineio", "ffmpeg"],
    boundary: "Recovery proves that another operator can reproduce the bounded handoff; it does not prove rights, editorial truth, legal compliance, or publication authority.",
    boundaryZhHans: "恢复演练只证明另一位操作员能复现有边界的交接；不能证明权利、编辑真实性、法律合规或发布权限。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m10-eu-article-50-boundary",
    text: "EU AI Act Article 50 contains transparency duties for specified AI-generated or manipulated content, including deep-fake disclosure provisions and exceptions; applicability is jurisdiction- and fact-dependent.",
    textZhHans: "欧盟《人工智能法》第50条对特定 AI 生成或操纵内容规定透明度义务，包括 deep fake 披露条款与例外；是否适用取决于法域和事实。",
    support: "direct",
    kind: "jurisdiction-dependent-guidance",
    sourceIds: ["eu-ai-act-article-50"],
    boundary: "Course content is not legal advice and does not export EU requirements into a global rule.",
    boundaryZhHans: "课程内容不是法律意见，也不会把欧盟要求外推为全球规则。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m10-usco-human-authorship-boundary",
    text: "The U.S. Copyright Office's AI study distinguishes human-authored expressive contribution from material determined by a machine and separately addresses digital replicas; these are United States guidance and policy analysis.",
    textZhHans: "美国版权局 AI 研究区分人类创作性表达贡献与由机器决定的材料，并另行讨论数字替身；这些属于美国指导与政策分析。",
    support: "direct",
    kind: "jurisdiction-dependent-guidance",
    sourceIds: ["usco-ai-study"],
    boundary: "This United States jurisdiction record does not decide ownership, registration, publicity, privacy, contract, or consent questions for a learner's project and is not legal advice.",
    boundaryZhHans: "这项美国法域记录不能决定学习者项目的所有权、登记、公开权、隐私、合同或同意问题，也不是法律意见。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m10-synthetic-media-course-boundary",
    text: "The core capstone forbids synthetic faces, voice clones, fabricated quotations or testimonials, event replacement, and unauthorized identity manipulation; the optional extension requires consent, terms, human contribution, region ledger, disclosure, jurisdiction review, and provenance.",
    textZhHans: "核心 capstone 禁止合成人脸、声音克隆、伪造引语或证言、事件替换及未经授权的身份操纵；可选扩展要求同意、条款、人类贡献、区域台账、披露、法域审查和 provenance。",
    support: "course-policy",
    kind: "course-fail-closed-policy",
    sourceIds: ["c2pa-spec", "eu-ai-act-article-50", "usco-ai-study"],
    boundary: "This is a conservative educational boundary, not a finding that every omitted or included use is lawful.",
    boundaryZhHans: "这是保守的教学边界，不代表对所有被排除或纳入用途是否合法作出认定。",
    reviewedOn: REVIEWED_ON,
  },
  {
    id: "m10-do-not-publish-valid",
    text: "A hash-bound do-not-publish decision with rationale, unresolved risks, and recovery evidence is a successful capstone outcome.",
    textZhHans: "带 hash 绑定、理由、未解决风险和恢复证据的 do-not-publish 决定，是合格的 capstone 结果。",
    support: "course-policy",
    kind: "course-fail-closed-policy",
    sourceIds: [],
    boundary: "Course completion never grants external release authority.",
    boundaryZhHans: "课程完成永远不会授予对外发布权限。",
    reviewedOn: REVIEWED_ON,
  },
] as const satisfies readonly AgenticVideoEditingClaimRecord[];

export function getAgenticVideoEditingClaim(id: string): AgenticVideoEditingClaimRecord {
  const claim = AGENTIC_VIDEO_EDITING_CLAIMS.find((candidate) => candidate.id === id);
  if (!claim) throw new Error(`Unknown Course 20 claim: ${id}`);
  return claim;
}
