import {
  AGENTIC_VIDEO_EDITING_COURSE_ID,
  AGENTIC_VIDEO_EDITING_DEFAULT_CONTENT_LOCALE,
  type AgenticVideoEditingCourseManifest,
  type AgenticVideoEditingModuleManifest,
  type AgenticVideoEditingOutcomeCoverage,
  type AgenticVideoEditingPhaseManifest,
} from "./types";

export const AGENTIC_VIDEO_EDITING_PHASES = [
  { id: "define", order: 1, moduleSlugs: ["agentic-editing-contract", "media-ingest-provenance"] },
  { id: "understand", order: 2, moduleSlugs: ["transcripts-shots-index", "semantic-analysis-director"] },
  { id: "edit", order: 3, moduleSlugs: ["declarative-edit-plan", "agent-tools-mcp", "captions-audio-formats", "deterministic-rendering"] },
  { id: "verify", order: 4, moduleSlugs: ["verification-human-review", "production-capstone"] },
] as const satisfies readonly AgenticVideoEditingPhaseManifest[];

export const AGENTIC_VIDEO_EDITING_MODULES = [
  {
    slug: "agentic-editing-contract", order: 1, phaseId: "define", minutes: 75,
    instructionMinutes: 50, practiceMinutes: 20, checkpointMinutes: 5, extensionMinutes: 10,
    coreMinutes: 75, practicumMinutes: 10, productionLabAvailable: true,
    objectiveId: "objective-brief-and-authority", requires: [], prerequisiteSlugs: [], requiredArtifactSlugs: [],
    inputArtifactIds: [], outputArtifactIds: ["creative-brief-responsibility-map"], invalidatesOn: [],
    artifactIds: ["creative-brief-responsibility-map"], artifactContractId: "creative-brief-responsibility-map",
    finalQuestionId: "q1", capstoneCriterionIds: ["creative-brief-responsibility-map"],
    sourceIds: ["video-use", "videodb-director", "bbc-editorial-accuracy"],
    systemRoles: ["agent-system", "agent-ready-tool", "deterministic-automation", "media-engine", "human-control"],
  },
  {
    slug: "media-ingest-provenance", order: 2, phaseId: "define", minutes: 65,
    instructionMinutes: 30, practiceMinutes: 30, checkpointMinutes: 5, extensionMinutes: 20,
    coreMinutes: 65, practicumMinutes: 20, productionLabAvailable: true,
    objectiveId: "objective-ingest-rights-untrusted-media", requires: ["agentic-editing-contract"],
    prerequisiteSlugs: ["agentic-editing-contract"], requiredArtifactSlugs: ["agentic-editing-contract"],
    inputArtifactIds: ["creative-brief-responsibility-map"], outputArtifactIds: ["media-manifest-provenance-quarantine"], invalidatesOn: ["creative-brief-responsibility-map"],
    artifactIds: ["media-manifest-provenance-quarantine"], artifactContractId: "media-manifest-provenance-quarantine",
    finalQuestionId: "q2", capstoneCriterionIds: ["media-manifest-provenance-quarantine"],
    sourceIds: ["ffmpeg", "ffprobe-docs", "c2pa-spec", "usco-ai-study"],
    systemRoles: ["media-engine", "agent-ready-tool", "human-control"],
  },
  {
    slug: "transcripts-shots-index", order: 3, phaseId: "understand", minutes: 75,
    instructionMinutes: 35, practiceMinutes: 35, checkpointMinutes: 5, extensionMinutes: 25,
    coreMinutes: 75, practicumMinutes: 25, productionLabAvailable: true,
    objectiveId: "objective-timecoded-evidence", requires: ["media-ingest-provenance"],
    prerequisiteSlugs: ["media-ingest-provenance"], requiredArtifactSlugs: ["media-ingest-provenance"],
    inputArtifactIds: ["media-manifest-provenance-quarantine"], outputArtifactIds: ["evidence-index-transcript-shots"], invalidatesOn: ["media-manifest-provenance-quarantine"],
    artifactIds: ["evidence-index-transcript-shots"], artifactContractId: "evidence-index-transcript-shots",
    finalQuestionId: "q3", capstoneCriterionIds: ["evidence-index-transcript-shots"],
    sourceIds: ["whisper", "whisperx", "pyscenedetect", "ffmpeg", "ffprobe-docs"],
    systemRoles: ["agent-ready-tool", "media-engine", "human-control"],
  },
  {
    slug: "semantic-analysis-director", order: 4, phaseId: "understand", minutes: 75,
    instructionMinutes: 35, practiceMinutes: 35, checkpointMinutes: 5, extensionMinutes: 15,
    coreMinutes: 75, practicumMinutes: 15, productionLabAvailable: true,
    objectiveId: "objective-editing-grammar-candidates", requires: ["transcripts-shots-index"],
    prerequisiteSlugs: ["transcripts-shots-index"], requiredArtifactSlugs: ["agentic-editing-contract", "transcripts-shots-index"],
    inputArtifactIds: ["creative-brief-responsibility-map", "evidence-index-transcript-shots"], outputArtifactIds: ["candidate-segments-system-card"], invalidatesOn: ["creative-brief-responsibility-map", "evidence-index-transcript-shots"],
    artifactIds: ["candidate-segments-system-card"], artifactContractId: "candidate-segments-system-card",
    finalQuestionId: "q4", capstoneCriterionIds: ["candidate-segments-system-card"],
    sourceIds: ["video-use", "videodb-director", "adobe-j-l-cuts", "bbc-editorial-accuracy"],
    systemRoles: ["agent-system", "agent-ready-tool", "deterministic-automation", "human-control"],
  },
  {
    slug: "declarative-edit-plan", order: 5, phaseId: "edit", minutes: 80,
    instructionMinutes: 35, practiceMinutes: 40, checkpointMinutes: 5, extensionMinutes: 30,
    coreMinutes: 80, practicumMinutes: 30, productionLabAvailable: true,
    objectiveId: "objective-production-edit-plan-v3", requires: ["semantic-analysis-director"],
    prerequisiteSlugs: ["semantic-analysis-director"], requiredArtifactSlugs: ["media-ingest-provenance", "transcripts-shots-index", "semantic-analysis-director"],
    inputArtifactIds: ["media-manifest-provenance-quarantine", "evidence-index-transcript-shots", "candidate-segments-system-card"], outputArtifactIds: ["edit-plan-v3-validation-approval", "plan-diff-independent-approval"], invalidatesOn: ["media-manifest-provenance-quarantine", "evidence-index-transcript-shots", "candidate-segments-system-card"],
    artifactIds: ["edit-plan-v3-validation-approval", "plan-diff-independent-approval"], artifactContractId: "edit-plan-v3-validation-approval",
    finalQuestionId: "q5", capstoneCriterionIds: ["edit-plan-v3-validation-approval", "plan-diff-independent-approval"],
    sourceIds: ["opentimelineio", "opentimelineio-docs", "ffprobe-docs", "video-edit-cli"],
    systemRoles: ["agent-ready-tool", "deterministic-automation", "human-control"],
  },
  {
    slug: "agent-tools-mcp", order: 6, phaseId: "edit", minutes: 75,
    instructionMinutes: 30, practiceMinutes: 40, checkpointMinutes: 5, extensionMinutes: 25,
    coreMinutes: 75, practicumMinutes: 25, productionLabAvailable: true,
    objectiveId: "objective-least-privilege-indirect-injection", requires: ["declarative-edit-plan"],
    prerequisiteSlugs: ["declarative-edit-plan"], requiredArtifactSlugs: ["declarative-edit-plan"],
    inputArtifactIds: ["edit-plan-v3-validation-approval", "plan-diff-independent-approval"], outputArtifactIds: ["tool-policy-adversarial-recovery"], invalidatesOn: ["edit-plan-v3-validation-approval", "plan-diff-independent-approval"],
    artifactIds: ["tool-policy-adversarial-recovery"], artifactContractId: "tool-policy-adversarial-recovery",
    finalQuestionId: "q6", capstoneCriterionIds: ["tool-policy-adversarial-recovery"],
    sourceIds: ["model-context-protocol-spec", "owasp-prompt-injection", "owasp-excessive-agency", "davinci-resolve-mcp"],
    systemRoles: ["agent-ready-tool", "agent-system", "human-control"],
  },
  {
    slug: "captions-audio-formats", order: 7, phaseId: "edit", minutes: 70,
    instructionMinutes: 30, practiceMinutes: 35, checkpointMinutes: 5, extensionMinutes: 15,
    coreMinutes: 70, practicumMinutes: 15, productionLabAvailable: true,
    objectiveId: "objective-delivery-accessibility-contract", requires: ["agent-tools-mcp"],
    prerequisiteSlugs: ["agent-tools-mcp"], requiredArtifactSlugs: ["declarative-edit-plan", "agent-tools-mcp"],
    inputArtifactIds: ["edit-plan-v3-validation-approval", "tool-policy-adversarial-recovery"], outputArtifactIds: ["delivery-matrix-accessibility"], invalidatesOn: ["edit-plan-v3-validation-approval", "tool-policy-adversarial-recovery"],
    artifactIds: ["delivery-matrix-accessibility"], artifactContractId: "delivery-matrix-accessibility",
    finalQuestionId: "q7", capstoneCriterionIds: [],
    sourceIds: ["wcag-2-2-captions", "w3c-media-planning", "w3c-visual-description", "itu-bs-1770", "ebu-r128", "aces-docs", "ffmpeg"],
    systemRoles: ["agent-ready-tool", "deterministic-automation", "media-engine", "human-control"],
  },
  {
    slug: "deterministic-rendering", order: 8, phaseId: "edit", minutes: 85,
    instructionMinutes: 30, practiceMinutes: 50, checkpointMinutes: 5, extensionMinutes: 25,
    coreMinutes: 85, practicumMinutes: 25, productionLabAvailable: true,
    objectiveId: "objective-controlled-receipt-backed-render", requires: ["captions-audio-formats"],
    prerequisiteSlugs: ["captions-audio-formats"], requiredArtifactSlugs: ["media-ingest-provenance", "declarative-edit-plan", "agent-tools-mcp", "captions-audio-formats"],
    inputArtifactIds: ["media-manifest-provenance-quarantine", "edit-plan-v3-validation-approval", "plan-diff-independent-approval", "tool-policy-adversarial-recovery", "delivery-matrix-accessibility"], outputArtifactIds: ["render-receipt-output-probe", "candidate-media-reference"], invalidatesOn: ["media-manifest-provenance-quarantine", "edit-plan-v3-validation-approval", "plan-diff-independent-approval", "tool-policy-adversarial-recovery", "delivery-matrix-accessibility"],
    artifactIds: ["render-receipt-output-probe", "candidate-media-reference"], artifactContractId: "render-receipt-output-probe",
    finalQuestionId: "q8", capstoneCriterionIds: ["render-receipt-output-probe", "candidate-media-reference"],
    sourceIds: ["ffmpeg", "ffprobe-docs", "remotion", "remotion-skills"],
    systemRoles: ["media-engine", "agent-ready-tool", "deterministic-automation", "human-control"],
  },
  {
    slug: "verification-human-review", order: 9, phaseId: "verify", minutes: 75,
    instructionMinutes: 30, practiceMinutes: 40, checkpointMinutes: 5, extensionMinutes: 10,
    coreMinutes: 75, practicumMinutes: 10, productionLabAvailable: true,
    objectiveId: "objective-multilayer-qc-repair-regression", requires: ["deterministic-rendering"],
    prerequisiteSlugs: ["deterministic-rendering"], requiredArtifactSlugs: ["media-ingest-provenance", "declarative-edit-plan", "captions-audio-formats", "deterministic-rendering"],
    inputArtifactIds: ["media-manifest-provenance-quarantine", "edit-plan-v3-validation-approval", "plan-diff-independent-approval", "delivery-matrix-accessibility", "render-receipt-output-probe", "candidate-media-reference"], outputArtifactIds: ["verification-repair-approval"], invalidatesOn: ["media-manifest-provenance-quarantine", "edit-plan-v3-validation-approval", "plan-diff-independent-approval", "delivery-matrix-accessibility", "render-receipt-output-probe", "candidate-media-reference"],
    artifactIds: ["verification-repair-approval"], artifactContractId: "verification-repair-approval",
    finalQuestionId: "q9", capstoneCriterionIds: ["verification-repair-approval"],
    sourceIds: ["vmaf", "ffmpeg", "wcag-2-2-captions", "w3c-visual-description", "itu-bs-1770", "ebu-r128", "aces-docs", "bbc-editorial-accuracy"],
    systemRoles: ["media-engine", "agent-ready-tool", "deterministic-automation", "human-control"],
  },
  {
    slug: "production-capstone", order: 10, phaseId: "verify", minutes: 75,
    instructionMinutes: 30, practiceMinutes: 40, checkpointMinutes: 5, extensionMinutes: 5,
    coreMinutes: 75, practicumMinutes: 5, productionLabAvailable: true,
    objectiveId: "objective-packaging-recovery-release-handoff", requires: ["verification-human-review"],
    prerequisiteSlugs: ["verification-human-review"], requiredArtifactSlugs: ["agentic-editing-contract", "media-ingest-provenance", "transcripts-shots-index", "semantic-analysis-director", "declarative-edit-plan", "captions-audio-formats", "agent-tools-mcp", "deterministic-rendering", "verification-human-review"],
    inputArtifactIds: ["creative-brief-responsibility-map", "media-manifest-provenance-quarantine", "evidence-index-transcript-shots", "candidate-segments-system-card", "edit-plan-v3-validation-approval", "plan-diff-independent-approval", "tool-policy-adversarial-recovery", "delivery-matrix-accessibility", "render-receipt-output-probe", "candidate-media-reference", "verification-repair-approval"], outputArtifactIds: ["release-package-runbook-recovery"], invalidatesOn: ["creative-brief-responsibility-map", "media-manifest-provenance-quarantine", "evidence-index-transcript-shots", "candidate-segments-system-card", "edit-plan-v3-validation-approval", "plan-diff-independent-approval", "tool-policy-adversarial-recovery", "delivery-matrix-accessibility", "render-receipt-output-probe", "candidate-media-reference", "verification-repair-approval"],
    artifactIds: ["release-package-runbook-recovery"], artifactContractId: "release-package-runbook-recovery",
    finalQuestionId: "q10", capstoneCriterionIds: ["release-package-runbook-recovery", "release-decision-postmortem"],
    sourceIds: ["opentimelineio", "ffmpeg", "c2pa-spec", "eu-ai-act-article-50", "usco-ai-study", "bbc-editorial-accuracy"],
    systemRoles: ["agent-system", "agent-ready-tool", "media-engine", "human-control"],
  },
] as const satisfies readonly AgenticVideoEditingModuleManifest[];

export const AGENTIC_VIDEO_EDITING_COURSE_MANIFEST = {
  id: AGENTIC_VIDEO_EDITING_COURSE_ID,
  version: "1.2.0",
  displayNumber: 20,
  publishedOn: "2026-08-26",
  revisedOn: "2026-08-28",
  researchCutoff: "2026-08-26",
  coreGuidedMinutes: 750,
  builderExtensionMinutes: 180,
  finalAssessmentMinutes: 30,
  estimatedCapstoneMinutes: 240,
  defaultContentLocale: AGENTIC_VIDEO_EDITING_DEFAULT_CONTENT_LOCALE,
  phases: AGENTIC_VIDEO_EDITING_PHASES,
  modules: AGENTIC_VIDEO_EDITING_MODULES,
} as const satisfies AgenticVideoEditingCourseManifest;

export const AGENTIC_VIDEO_EDITING_OUTCOME_COVERAGE = [
  { outcomeIndex: 0, moduleSlugs: ["agentic-editing-contract"], artifactContractIds: ["creative-brief-responsibility-map"], finalQuestionIds: ["q1"], capstoneCriterionIds: ["creative-brief-responsibility-map"] },
  { outcomeIndex: 1, moduleSlugs: ["media-ingest-provenance"], artifactContractIds: ["media-manifest-provenance-quarantine"], finalQuestionIds: ["q2"], capstoneCriterionIds: ["media-manifest-provenance-quarantine"] },
  { outcomeIndex: 2, moduleSlugs: ["transcripts-shots-index"], artifactContractIds: ["evidence-index-transcript-shots"], finalQuestionIds: ["q3"], capstoneCriterionIds: ["evidence-index-transcript-shots"] },
  { outcomeIndex: 3, moduleSlugs: ["semantic-analysis-director", "declarative-edit-plan"], artifactContractIds: ["candidate-segments-system-card", "edit-plan-v3-validation-approval", "plan-diff-independent-approval"], finalQuestionIds: ["q4", "q5"], capstoneCriterionIds: ["candidate-segments-system-card", "edit-plan-v3-validation-approval", "plan-diff-independent-approval"] },
  { outcomeIndex: 4, moduleSlugs: ["agent-tools-mcp", "captions-audio-formats"], artifactContractIds: ["tool-policy-adversarial-recovery", "delivery-matrix-accessibility"], finalQuestionIds: ["q6", "q7"], capstoneCriterionIds: ["tool-policy-adversarial-recovery"] },
  { outcomeIndex: 5, moduleSlugs: ["deterministic-rendering"], artifactContractIds: ["render-receipt-output-probe", "candidate-media-reference"], finalQuestionIds: ["q8"], capstoneCriterionIds: ["render-receipt-output-probe", "candidate-media-reference"] },
  { outcomeIndex: 6, moduleSlugs: ["verification-human-review"], artifactContractIds: ["verification-repair-approval"], finalQuestionIds: ["q9"], capstoneCriterionIds: ["verification-repair-approval"] },
  { outcomeIndex: 7, moduleSlugs: ["production-capstone"], artifactContractIds: ["release-package-runbook-recovery", "release-decision-postmortem"], finalQuestionIds: ["q10"], capstoneCriterionIds: ["release-package-runbook-recovery", "release-decision-postmortem"] },
] as const satisfies readonly AgenticVideoEditingOutcomeCoverage[];
