import type {
  AgenticVideoEditingSourceRecord,
  AgenticVideoEditingSourceUsage,
} from "./types";

const ACCESSED_ON = "2026-08-26";
const FOLLOW_UP_ACCESSED_ON = "2026-08-28";

/**
 * Course 20 source ledger.
 *
 * Commit-pinned GitHub entries support inspectable implementation claims and
 * license boundaries. Versioned standards carry protocol/accessibility claims.
 * Mutable issues, official web pages, and X posts are dated observations only;
 * none is allowed to silently expand a pinned repository claim. No upstream
 * code, post media, issue attachments, or service output is copied into the
 * public course.
 */
export const AGENTIC_VIDEO_EDITING_SOURCES = [
  {
    id: "video-use",
    kind: "github-repository",
    role: "agent-architecture",
    repository: "browser-use/video-use",
    title: "video-use: edit videos with coding agents",
    publisher: "Browser Use",
    url: "https://github.com/browser-use/video-use/blob/92c2b34e44c205cbc2acae7f6ca7c1c219d5dd66/SKILL.md",
    claimEvidenceUrls: [
      "https://github.com/browser-use/video-use/blob/92c2b34e44c205cbc2acae7f6ca7c1c219d5dd66/SKILL.md",
      "https://github.com/browser-use/video-use/blob/92c2b34e44c205cbc2acae7f6ca7c1c219d5dd66/README.md",
      "https://github.com/browser-use/video-use/blob/92c2b34e44c205cbc2acae7f6ca7c1c219d5dd66/install.md",
      "https://github.com/browser-use/video-use/blob/92c2b34e44c205cbc2acae7f6ca7c1c219d5dd66/LICENSE",
    ],
    accessedOn: ACCESSED_ON,
    stability: "commit-pinned-at-cutoff",
    revision: "92c2b34e44c205cbc2acae7f6ca7c1c219d5dd66",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link and paraphrase the workflow; do not republish project code, examples, or demo media.",
    rightsDecisionZhHans: "链接并转述工作流；不再发布项目代码、示例或演示媒体。",
    supports: "A transcript-led agent workflow that inventories footage, proposes a strategy, waits for approval, builds an EDL, renders into a separate edit directory, inspects cut boundaries, and retains session artifacts.",
    supportsZhHans: "一种以转录为主界面的智能体流程：盘点素材、提出策略、等待批准、生成 EDL、在独立 edit 目录渲染、检查切点并保留会话产物。",
    boundary: "The repository is young, depends on FFmpeg and currently asks for an ElevenLabs key for transcription; open-source code does not make every provider call free or suitable for confidential footage.",
    boundaryZhHans: "该仓库较新，依赖 FFmpeg，当前转录安装流程还要求 ElevenLabs 密钥；代码开源不代表所有服务调用免费，也不代表适合机密素材。",
  },
  {
    id: "ffmpeg",
    kind: "github-repository",
    role: "execution-engine",
    repository: "FFmpeg/FFmpeg",
    title: "FFmpeg multimedia framework",
    publisher: "FFmpeg",
    url: "https://github.com/FFmpeg/FFmpeg/blob/bf1b838f2ab88b4f8fd83443325c782ea0e0f7fa/README.md",
    claimEvidenceUrls: [
      "https://github.com/FFmpeg/FFmpeg/blob/bf1b838f2ab88b4f8fd83443325c782ea0e0f7fa/README.md",
      "https://github.com/FFmpeg/FFmpeg/blob/bf1b838f2ab88b4f8fd83443325c782ea0e0f7fa/LICENSE.md",
      "https://ffmpeg.org/ffprobe.html",
    ],
    versionAnchorUrl: "https://github.com/FFmpeg/FFmpeg/tree/n9.0.1",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "9.0.1 Lei",
    resolvedCommit: "bf1b838f2ab88b4f8fd83443325c782ea0e0f7fa",
    license: "LGPL-2.1-or-later by default; build-dependent GPL/nonfree boundary",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Teach command structure and link to upstream; learners must inspect their binary configuration and codec licenses.",
    rightsDecisionZhHans: "讲解命令结构并链接上游；学习者必须检查自己二进制的编译配置与编解码器许可证。",
    supports: "Scriptable probing, trimming, filtering, audio processing, subtitle composition, transcoding, and machine-readable media inspection through ffprobe.",
    supportsZhHans: "通过 FFmpeg 与 ffprobe 进行可脚本化、可检查的探测、剪切、滤镜、音频处理、字幕合成、转码和媒体检查。",
    boundary: "FFmpeg executes media operations but does not decide story intent. Fast stream-copy cuts may preserve material around a seek point; bit-identical output is not guaranteed across builds, codecs, hardware, or threading. Redistribution depends on the actual build, and a build that enables nonfree components generally cannot be redistributed.",
    boundaryZhHans: "FFmpeg 执行媒体操作但不判断叙事意图；快速流复制剪切可能保留 seek point 附近内容；跨编译、编解码器、硬件或线程设置不保证逐位一致。再分发取决于实际编译配置，启用 nonfree 组件的构建通常不能再分发。",
  },
  {
    id: "remotion",
    kind: "github-repository",
    role: "execution-engine",
    repository: "remotion-dev/remotion",
    title: "Remotion: make videos programmatically with React",
    publisher: "Remotion",
    url: "https://github.com/remotion-dev/remotion/blob/a2c2a6260fee129bb55f97b9632d998f589839b7/README.md",
    claimEvidenceUrls: [
      "https://github.com/remotion-dev/remotion/blob/a2c2a6260fee129bb55f97b9632d998f589839b7/README.md",
      "https://github.com/remotion-dev/remotion/blob/a2c2a6260fee129bb55f97b9632d998f589839b7/LICENSE.md",
    ],
    versionAnchorUrl: "https://github.com/remotion-dev/remotion/releases/tag/v4.0.517",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v4.0.517",
    resolvedCommit: "a2c2a6260fee129bb55f97b9632d998f589839b7",
    latestObservedVersion: "v4.0.518",
    latestObservedUrl: "https://github.com/remotion-dev/remotion/releases/tag/v4.0.518",
    latestObservedOn: FOLLOW_UP_ACCESSED_ON,
    license: "Remotion License (special commercial terms)",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link and teach original examples only; surface the company-license threshold before learners adopt it commercially.",
    rightsDecisionZhHans: "仅链接并讲解原创示例；学习者商业采用前必须看到公司许可证门槛。",
    supports: "Frame-addressable React compositions for repeatable titles, captions, diagrams, data graphics, brand templates, preview, and rendering.",
    supportsZhHans: "用逐帧可寻址的 React composition 重复生成标题、字幕、图解、数据图形、品牌模板、预览与渲染。",
    boundary: "Programmatic composition is not a general-purpose semantic rough-cut engine. Under the pinned v4.0.517 license, personal and nonprofit use and for-profit organizations with up to three employees are in the free category; larger for-profit organizations need a Company License. Re-check current terms before adoption; this is not legal advice.",
    boundaryZhHans: "程序化合成并非通用语义粗剪引擎。按固定的 v4.0.517 许可，个人、非营利组织及最多三名员工的营利组织属于免费范围；更大的营利组织需要 Company License。采用前须复核最新条款；这不是法律意见。",
  },
  {
    id: "remotion-skills",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "remotion-dev/remotion",
    title: "Remotion Agent Skills",
    publisher: "Remotion",
    url: "https://github.com/remotion-dev/remotion/blob/7aee2f4b3d5c05c77761f2dc6ec5aeac701dcce8/packages/skills/README.md",
    claimEvidenceUrls: [
      "https://github.com/remotion-dev/remotion/blob/7aee2f4b3d5c05c77761f2dc6ec5aeac701dcce8/packages/skills/README.md",
      "https://github.com/remotion-dev/skills/tree/7c5c10caa5294d01b168a08c9648b4deef717274",
    ],
    accessedOn: ACCESSED_ON,
    stability: "commit-pinned-at-cutoff",
    revision: "remotion 7aee2f4b3d5c05c77761f2dc6ec5aeac701dcce8; skills 7c5c10caa5294d01b168a08c9648b4deef717274",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link to the maintained skills and paraphrase their scope. The standalone skills repository has no root license grant, and a skill never changes the Remotion runtime license.",
    rightsDecisionZhHans: "链接维护中的 skills 并转述其范围。独立 skills 仓库根目录没有许可证授权，而且 skill 不会改变 Remotion runtime 许可证。",
    supports: "Agent guidance for creating, marking up, previewing, rendering, captioning, and maintaining Remotion projects from Codex, Claude Code, Cursor, and related hosts.",
    supportsZhHans: "为 Codex、Claude Code、Cursor 等宿主提供创建、编写、预览、渲染、字幕和维护 Remotion 项目的智能体操作知识。",
    boundary: "A skill is operational guidance for a host agent, not an editing agent, model, renderer, or proof that a generated composition is correct. The standalone skills repository does not publish a root LICENSE at the research cutoff.",
    boundaryZhHans: "Skill 是供宿主智能体使用的操作知识，不是剪辑智能体、模型或渲染器，也不能证明生成的 composition 正确；研究截止时独立 skills 仓库根目录未发布 LICENSE。",
  },
  {
    id: "opentimelineio",
    kind: "github-repository",
    role: "timeline-contract",
    repository: "AcademySoftwareFoundation/OpenTimelineIO",
    title: "OpenTimelineIO",
    publisher: "Academy Software Foundation",
    url: "https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/44236713c1db295a6ffc66189ae98dbdfd0cb9c4/README.md",
    claimEvidenceUrls: [
      "https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/44236713c1db295a6ffc66189ae98dbdfd0cb9c4/README.md",
      "https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/44236713c1db295a6ffc66189ae98dbdfd0cb9c4/docs/tutorials/otio-filebundles.md",
      "https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/44236713c1db295a6ffc66189ae98dbdfd0cb9c4/LICENSE.txt",
    ],
    versionAnchorUrl: "https://github.com/AcademySoftwareFoundation/OpenTimelineIO/releases/tag/v0.18.1",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v0.18.1 pre-release",
    resolvedCommit: "44236713c1db295a6ffc66189ae98dbdfd0cb9c4",
    license: "Apache-2.0",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Use an original JSON teaching schema inspired by timeline concepts; link to OTIO for production interchange.",
    rightsDecisionZhHans: "使用受时间线概念启发的原创教学 JSON schema；生产交换则链接 OTIO。",
    supports: "A versioned, inspectable representation of editorial cut order, timing, tracks, transitions, metadata, and external media references, with adapter-based interchange.",
    supportsZhHans: "以有版本、可检查的形式表示剪辑顺序、时间、轨道、转场、元数据和外部媒体引用，并通过适配器交换。",
    boundary: "v0.18.1 is marked pre-release. Core .otio data references rather than embeds media; .otioz/.otiod adapters can bundle associated media, but OTIO still does not decode, encode, or render it. Adapter availability and fidelity vary by interchange format.",
    boundaryZhHans: "v0.18.1 被标为 pre-release。核心 .otio 数据引用而不内嵌媒体；.otioz/.otiod 适配器可打包相关媒体，但 OTIO 仍不解码、编码或渲染。不同交换格式的适配器可用性与保真度各异。",
  },
  {
    id: "whisper",
    kind: "github-repository",
    role: "analysis-component",
    repository: "openai/whisper",
    title: "Whisper",
    publisher: "OpenAI",
    url: "https://github.com/openai/whisper/blob/31243bad24cc746f07d4c8bfdd2d974872cb1803/README.md",
    claimEvidenceUrls: [
      "https://github.com/openai/whisper/blob/31243bad24cc746f07d4c8bfdd2d974872cb1803/README.md",
      "https://github.com/openai/whisper/blob/31243bad24cc746f07d4c8bfdd2d974872cb1803/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/openai/whisper/releases/tag/v20250625",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v20250625",
    resolvedCommit: "31243bad24cc746f07d4c8bfdd2d974872cb1803",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link to upstream and use learner-owned sample transcripts; never redistribute third-party recordings.",
    rightsDecisionZhHans: "链接上游并使用学习者自有样本转录；绝不再分发第三方录音。",
    supports: "Local multilingual speech recognition and timestamped transcription as one evidence channel for dialogue editing.",
    supportsZhHans: "本地多语言语音识别与带时间戳转录，可作为对白剪辑的一条证据通道。",
    boundary: "Recognition errors, names, numbers, negation, and timing boundaries require review. Whisper alone does not assign speakers; labels from a separate diarization component also require review. A transcript is not permission to alter meaning.",
    boundaryZhHans: "识别错误、人名、数字、否定词与时间边界都需复核。Whisper 本身不分配说话人；独立 diarization 组件给出的标签也需复核。转录文本并不授权改变原意。",
  },
  {
    id: "whisperx",
    kind: "github-repository",
    role: "analysis-component",
    repository: "m-bain/whisperX",
    title: "WhisperX",
    publisher: "WhisperX maintainers",
    url: "https://github.com/m-bain/whisperX/blob/3ccc17b8de34f305300f8a3fd3c9f76ba820c0d0/README.md",
    claimEvidenceUrls: [
      "https://github.com/m-bain/whisperX/blob/3ccc17b8de34f305300f8a3fd3c9f76ba820c0d0/README.md",
      "https://github.com/m-bain/whisperX/blob/3ccc17b8de34f305300f8a3fd3c9f76ba820c0d0/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/m-bain/whisperX/releases/tag/v3.8.6",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v3.8.6",
    resolvedCommit: "3ccc17b8de34f305300f8a3fd3c9f76ba820c0d0",
    license: "BSD-2-Clause",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link and paraphrase alignment concepts; model downloads and diarization terms must be reviewed separately.",
    rightsDecisionZhHans: "链接并转述对齐概念；模型下载与说话人分离条款需单独审查。",
    supports: "Forced alignment for word-level timestamps and optional diarization layered on a faster-whisper transcription backend.",
    supportsZhHans: "在 faster-whisper 转录后端上增加强制对齐的词级时间戳与可选说话人分离。",
    boundary: "Word alignment can still fail at accents, overlap, music, unsupported languages, or transcript errors; some diarization models require a token and separate terms.",
    boundaryZhHans: "口音、重叠语音、音乐、不支持语言或转录错误仍会使词对齐失败；部分说话人分离模型需要令牌和单独条款。",
  },
  {
    id: "pyscenedetect",
    kind: "github-repository",
    role: "analysis-component",
    repository: "Breakthrough/PySceneDetect",
    title: "PySceneDetect",
    publisher: "PySceneDetect maintainers",
    url: "https://github.com/Breakthrough/PySceneDetect/blob/6ebb72392de8acfb6c539bf15d0aa912ce7ab6b2/README.md",
    claimEvidenceUrls: [
      "https://github.com/Breakthrough/PySceneDetect/blob/6ebb72392de8acfb6c539bf15d0aa912ce7ab6b2/README.md",
      "https://github.com/Breakthrough/PySceneDetect/blob/6ebb72392de8acfb6c539bf15d0aa912ce7ab6b2/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/Breakthrough/PySceneDetect/releases/tag/v0.7.1",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v0.7.1",
    resolvedCommit: "6ebb72392de8acfb6c539bf15d0aa912ce7ab6b2",
    license: "BSD-3-Clause",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link to the detector documentation and publish only original threshold experiments.",
    rightsDecisionZhHans: "链接检测器文档，仅发布原创阈值实验。",
    supports: "Content, adaptive, and threshold detectors can produce candidate shot boundaries, scene lists or CSV output, and representative stills that a separate course step can assemble into a contact-sheet index.",
    supportsZhHans: "内容、自适应和阈值检测器可生成候选镜头边界、场景清单或 CSV 及代表帧；课程另行把这些代表帧组装为联系表索引。",
    boundary: "Shot-boundary detection finds visual transitions, not semantic scenes; camera motion, flashes, fades, and thresholds produce different errors.",
    boundaryZhHans: "镜头边界检测发现视觉切换而非语义场景；镜头运动、闪光、淡化和阈值会产生不同错误。",
  },
  {
    id: "qwen3-vl",
    kind: "github-repository",
    role: "analysis-component",
    repository: "QwenLM/Qwen3-VL",
    title: "Qwen3-VL",
    publisher: "QwenLM",
    url: "https://github.com/QwenLM/Qwen3-VL/blob/96588727e44c78b25ba03ea03b8e12f7e64fd0da/README.md",
    claimEvidenceUrls: [
      "https://github.com/QwenLM/Qwen3-VL/blob/96588727e44c78b25ba03ea03b8e12f7e64fd0da/README.md",
      "https://github.com/QwenLM/Qwen3-VL/blob/96588727e44c78b25ba03ea03b8e12f7e64fd0da/LICENSE",
    ],
    accessedOn: ACCESSED_ON,
    stability: "commit-pinned-at-cutoff",
    revision: "96588727e44c78b25ba03ea03b8e12f7e64fd0da",
    license: "Apache-2.0 for repository code; model terms are separate",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Teach candidate labeling with locally supplied frames; learners must inspect the selected model's terms and privacy path.",
    rightsDecisionZhHans: "用本地提供的帧讲解候选标注；学习者必须检查所选模型的条款与隐私路径。",
    supports: "Long-video understanding, OCR, descriptions, and approximate text-to-time localization useful for proposing candidate segments from sampled visual evidence.",
    supportsZhHans: "长视频理解、OCR、描述和近似文本时间定位，可从抽样视觉证据中提出候选片段。",
    boundary: "Model timestamps and semantic labels are hypotheses, not frame-accurate truth. A separate dated-observation record preserves issue #1761 without treating the mutable issue as repository documentation or a maintainer-confirmed defect.",
    boundaryZhHans: "模型时间戳与语义标签是候选假设而非逐帧真值。课程另用有日期的观察记录保存 issue #1761，不把可变 issue 当成仓库文档或维护者确认的缺陷。",
  },
  {
    id: "qwen3-vl-issue-1761",
    kind: "dated-repository-issue",
    role: "field-signal",
    repository: "QwenLM/Qwen3-VL",
    issueNumber: 1761,
    title: "Qwen3-VL issue #1761: user report about frame-list timestamps",
    publisher: "GitHub user report in QwenLM/Qwen3-VL",
    url: "https://github.com/QwenLM/Qwen3-VL/issues/1761",
    claimEvidenceUrls: ["https://github.com/QwenLM/Qwen3-VL/issues/1761"],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    publishedOn: "2025-11-04",
    stability: "dated-observation",
    observedAt: FOLLOW_UP_ACCESSED_ON,
    observedState: "open",
    observedBodySha256: "8bf6791a91280bb0cfe51d9bbc3f74786c7e15d8c2033d849000341db3ea6eae",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link to and minimally paraphrase the dated user report; do not copy its attachment, prompt, generated output, or linked video into course materials.",
    rightsDecisionZhHans: "仅链接并最小化转述这条有日期的用户报告；不把附件、提示词、生成输出或所链接视频复制进课程材料。",
    supports: "At the recorded observation, one user reported that a frame-list API workflow mapped a 265-second video to an approximately 65-second result and asked how to obtain accurate event timestamps.",
    supportsZhHans: "在所记录的观察时点，一名用户报告 frame-list API 工作流把 265 秒视频映射成约 65 秒结果，并询问如何得到准确事件时间戳。",
    boundary: "This is a mutable, open user report with no label, assignee, linked fix, or maintainer-confirmed root cause at the observation time. It is not prevalence evidence and does not prove that the pinned repository commit has a universal defect.",
    boundaryZhHans: "这是可变且仍开放的用户报告；观察时没有标签、负责人、关联修复或维护者确认的根因。它不提供发生率证据，也不能证明固定仓库提交存在普遍缺陷。",
  },
  {
    id: "vmaf",
    kind: "github-repository",
    role: "quality-control",
    repository: "Netflix/vmaf",
    title: "VMAF",
    publisher: "Netflix",
    url: "https://github.com/Netflix/vmaf/blob/3f9e02af258a5c0e30124fc585a3c3af90126dee/README.md",
    claimEvidenceUrls: [
      "https://github.com/Netflix/vmaf/blob/3f9e02af258a5c0e30124fc585a3c3af90126dee/README.md",
      "https://github.com/Netflix/vmaf/blob/3f9e02af258a5c0e30124fc585a3c3af90126dee/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/Netflix/vmaf/releases/tag/v3.2.0",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v3.2.0",
    resolvedCommit: "3f9e02af258a5c0e30124fc585a3c3af90126dee",
    license: "BSD-2-Clause-Patent",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link to upstream and use only on learner-controlled reference/distorted pairs.",
    rightsDecisionZhHans: "链接上游，并仅在学习者控制的参考/失真成对素材上使用。",
    supports: "Full-reference perceptual video-quality assessment for aligned reference and distorted versions of the same content after encoding or processing.",
    supportsZhHans: "对同一内容经编码或处理后的对齐参考/失真版本进行全参考感知视频质量评估。",
    boundary: "VMAF does not judge narrative, truth, captions, music choice, or differently edited timelines and must not be used as a universal quality score.",
    boundaryZhHans: "VMAF 不判断叙事、真实性、字幕、音乐选择或不同剪辑时间线，不能当作通用质量分数。",
  },
  {
    id: "auto-editor",
    kind: "github-repository",
    role: "deterministic-automation",
    repository: "WyattBlue/auto-editor",
    title: "Auto-Editor",
    publisher: "Auto-Editor maintainers",
    url: "https://github.com/WyattBlue/auto-editor/blob/2f7ba68049ee67317a7afe6a0555ea6cf30ad101/README.md",
    claimEvidenceUrls: [
      "https://github.com/WyattBlue/auto-editor/blob/2f7ba68049ee67317a7afe6a0555ea6cf30ad101/README.md",
      "https://github.com/WyattBlue/auto-editor/blob/2f7ba68049ee67317a7afe6a0555ea6cf30ad101/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/WyattBlue/auto-editor/releases/tag/31.5.0",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "31.5.0",
    resolvedCommit: "2f7ba68049ee67317a7afe6a0555ea6cf30ad101",
    license: "Unlicense",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link to the project and teach original rule-threshold experiments on synthetic footage.",
    rightsDecisionZhHans: "链接项目，并在合成素材上讲授原创规则阈值实验。",
    supports: "Rule-driven first-pass editing based on loudness and motion, with exports to several NLE timeline formats.",
    supportsZhHans: "基于响度与运动的规则型初剪，并可导出到若干 NLE 时间线格式。",
    boundary: "It is deterministic automation, not an agent; aggressive thresholds can damage breath, timing, sentence boundaries, or deliberate silence.",
    boundaryZhHans: "它是确定性自动化而非智能体；过激阈值可能破坏呼吸、节奏、句子边界或有意停顿。",
  },
  {
    id: "videodb-director",
    kind: "github-repository",
    role: "agent-architecture",
    repository: "video-db/Director",
    title: "Director: AI video agents framework",
    publisher: "VideoDB",
    url: "https://github.com/video-db/Director/blob/70e0b3dfdf59c679a25f4bea511e3cc4c5f2457f/README.md",
    claimEvidenceUrls: [
      "https://github.com/video-db/Director/blob/70e0b3dfdf59c679a25f4bea511e3cc4c5f2457f/README.md",
      "https://github.com/video-db/Director/blob/70e0b3dfdf59c679a25f4bea511e3cc4c5f2457f/LICENSE",
      "https://github.com/video-db/Director/releases/tag/First",
    ],
    accessedOn: ACCESSED_ON,
    stability: "commit-pinned-at-cutoff",
    revision: "70e0b3dfdf59c679a25f4bea511e3cc4c5f2457f; latest named release v0.1.1",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Use as an architecture reading and link to code; do not make the cloud-dependent repository a required course runtime.",
    rightsDecisionZhHans: "作为架构阅读并链接代码；不把依赖云服务的仓库设为课程必需运行时。",
    supports: "A multi-agent framework in which a reasoning engine selects video search, scene, editing, subtitle, and sharing capabilities from a natural-language request.",
    supportsZhHans: "多智能体框架：推理引擎从自然语言请求中选择视频搜索、场景、剪辑、字幕与分享能力。",
    boundary: "It relies on VideoDB infrastructure and an API key; repository visibility and demos do not establish local privacy or production reliability.",
    boundaryZhHans: "它依赖 VideoDB 基础设施与 API 密钥；仓库可见和演示不能证明本地隐私或生产可靠性。",
  },
  {
    id: "montaj",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "theSamPadilla/montaj",
    title: "Montaj agent video toolkit",
    publisher: "Montaj maintainers",
    url: "https://github.com/theSamPadilla/montaj/blob/634d523f4b022a19c5cf98ffa4f9e609178437c7/README.md",
    claimEvidenceUrls: [
      "https://github.com/theSamPadilla/montaj/blob/634d523f4b022a19c5cf98ffa4f9e609178437c7/README.md",
      "https://github.com/theSamPadilla/montaj/blob/634d523f4b022a19c5cf98ffa4f9e609178437c7/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/theSamPadilla/montaj/releases/tag/v3.10.1",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v3.10.1",
    resolvedCommit: "634d523f4b022a19c5cf98ffa4f9e609178437c7",
    latestObservedVersion: "v4.2.0",
    latestObservedUrl: "https://github.com/theSamPadilla/montaj/releases/tag/v4.2.0",
    latestObservedOn: FOLLOW_UP_ACCESSED_ON,
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Teach the schema-and-tool pattern through original fixtures; link to Montaj for optional exploration.",
    rightsDecisionZhHans: "用原创 fixture 讲解 schema 与工具模式；链接 Montaj 供选修探索。",
    supports: "Small JSON-schema operations, workflow steps, a project source of truth, and pending-to-draft-to-human-final lifecycle designed for an external host agent.",
    supportsZhHans: "面向外部宿主智能体的小型 JSON-schema 操作、工作流步骤、项目事实源，以及 pending→draft→human final 生命周期。",
    boundary: "Montaj explicitly does not supply the reasoning agent; it is new, low-adoption, and some generation paths invoke paid providers.",
    boundaryZhHans: "Montaj 明确不提供推理智能体；项目较新、采用度低，部分生成路径会调用付费服务商。",
  },
  {
    id: "timeline-studio",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "MartinDelophy/ai-video-editor",
    title: "Timeline Studio agent editing surface",
    publisher: "Timeline Studio maintainers",
    url: "https://github.com/MartinDelophy/ai-video-editor/blob/2a59ffcfc6042deb56456cdadf6434ce39a647cd/README.md",
    claimEvidenceUrls: [
      "https://github.com/MartinDelophy/ai-video-editor/blob/2a59ffcfc6042deb56456cdadf6434ce39a647cd/README.md",
      "https://github.com/MartinDelophy/ai-video-editor/blob/2a59ffcfc6042deb56456cdadf6434ce39a647cd/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/MartinDelophy/ai-video-editor/releases/tag/v1.0.5",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v1.0.5",
    resolvedCommit: "2a59ffcfc6042deb56456cdadf6434ce39a647cd",
    latestObservedVersion: "v1.0.6",
    latestObservedUrl: "https://github.com/MartinDelophy/ai-video-editor/releases/tag/v1.0.6",
    latestObservedOn: FOLLOW_UP_ACCESSED_ON,
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Paraphrase inspect, diff, dry-run, and transaction patterns; do not embed third-party demo assets.",
    rightsDecisionZhHans: "转述 inspect、diff、dry-run 与事务模式；不嵌入第三方演示资产。",
    supports: "Stable clip IDs, project inspection, plan diffs, dry runs, transactional writes, idempotent operation IDs, and an editable timeline source of truth.",
    supportsZhHans: "稳定 clip ID、工程检查、计划差异、dry-run、事务写入、幂等 operation ID 与可编辑时间线事实源。",
    boundary: "The project is only weeks old at the research cutoff, and its headless renderer covers a documented subset rather than every browser-editor operation. The v1.0.5 tag resolves to code whose package.json still reports 1.0.0, so the tag and package version must be recorded separately.",
    boundaryZhHans: "研究截止时该项目仅发布数周，headless 渲染器只覆盖文档声明子集。v1.0.5 tag 对应代码的 package.json 仍写 1.0.0，因此必须分开记录 tag 与包版本。",
  },
  {
    id: "qcut",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "Quriosity-agent/qcut",
    title: "QCut editor and structured CLI",
    publisher: "QCut maintainers",
    url: "https://github.com/Quriosity-agent/qcut/blob/d297613a965102caf45cd5f7cbd0d407340b3dcd/README.md",
    claimEvidenceUrls: [
      "https://github.com/Quriosity-agent/qcut/blob/d297613a965102caf45cd5f7cbd0d407340b3dcd/README.md",
      "https://github.com/Quriosity-agent/qcut/blob/d297613a965102caf45cd5f7cbd0d407340b3dcd/qcut/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/Quriosity-agent/qcut/releases/tag/v2026.08.26.1",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v2026.08.26.1",
    resolvedCommit: "d297613a965102caf45cd5f7cbd0d407340b3dcd",
    latestObservedVersion: "v2026.08.26.3",
    latestObservedUrl: "https://github.com/Quriosity-agent/qcut/releases/tag/v2026.08.26.3",
    latestObservedOn: FOLLOW_UP_ACCESSED_ON,
    license: "MIT for qcut source tree; providers and assets remain separate",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link to the editor and teach the shared-visible-state pattern without copying provider assets.",
    rightsDecisionZhHans: "链接编辑器并讲解人机共享可见状态模式，不复制服务商资产。",
    supports: "A desktop NLE, machine-readable CLI, and agent plugins that let humans and agents work against one visible multitrack project.",
    supportsZhHans: "桌面 NLE、机器可读 CLI 与智能体插件，使人和智能体在同一个可见多轨工程上工作。",
    boundary: "Editor control requires the app, optional analysis or generation may upload selected media, and the public project is still young.",
    boundaryZhHans: "编辑器控制需要启动应用；可选分析或生成可能上传所选媒体，且公开项目仍较新。",
  },
  {
    id: "velorn",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "VelornLabs/velorn",
    title: "Velorn local MCP video editor",
    publisher: "Velorn Labs",
    url: "https://github.com/VelornLabs/velorn/blob/90aa9028ee38a98458c6fbd9a9a79b189462e019/README.md",
    claimEvidenceUrls: [
      "https://github.com/VelornLabs/velorn/blob/90aa9028ee38a98458c6fbd9a9a79b189462e019/README.md",
      "https://github.com/VelornLabs/velorn/blob/90aa9028ee38a98458c6fbd9a9a79b189462e019/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/VelornLabs/velorn/releases/tag/v0.3.29",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v0.3.29",
    resolvedCommit: "90aa9028ee38a98458c6fbd9a9a79b189462e019",
    latestObservedVersion: "v0.3.30",
    latestObservedUrl: "https://github.com/VelornLabs/velorn/releases/tag/v0.3.30",
    latestObservedOn: FOLLOW_UP_ACCESSED_ON,
    license: "GPL-3.0-only",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Use as a linked safety-pattern case; do not copy GPL code into course fixtures.",
    rightsDecisionZhHans: "作为安全模式案例链接；不把 GPL 代码复制到课程 fixture。",
    supports: "A desktop timeline with many local MCP tools, preview-first write operations, undoable ordinary edits, and queued generation/export actions.",
    supportsZhHans: "带大量本地 MCP 工具的桌面时间线，多数写操作先预览，普通编辑可撤销，生成与导出进入队列。",
    boundary: "Some generation depends on local ComfyUI; v0.3.29 also adds optional Pexels search/import that requires a configured API key and network access. Some workflows are beta, and not every filesystem or project action is undoable.",
    boundaryZhHans: "部分生成依赖本地 ComfyUI；v0.3.29 另有需配置 API key 与联网的可选 Pexels 搜索/导入。部分工作流仍为 beta，并非所有文件系统或工程动作都可撤销。",
  },
  {
    id: "veac",
    kind: "github-repository",
    role: "timeline-contract",
    repository: "AgentsMesh/veac",
    title: "VEAC agent-first video editing DSL",
    publisher: "AgentsMesh",
    url: "https://github.com/AgentsMesh/veac/blob/e3472918a8c05fe53be1c2bf6c6a76cd5730d8af/README.md",
    claimEvidenceUrls: [
      "https://github.com/AgentsMesh/veac/blob/e3472918a8c05fe53be1c2bf6c6a76cd5730d8af/README.md",
      "https://github.com/AgentsMesh/veac/blob/e3472918a8c05fe53be1c2bf6c6a76cd5730d8af/docs/architecture.md",
      "https://github.com/AgentsMesh/veac/blob/e3472918a8c05fe53be1c2bf6c6a76cd5730d8af/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/AgentsMesh/veac/releases/tag/v0.2.0",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v0.2.0",
    resolvedCommit: "e3472918a8c05fe53be1c2bf6c6a76cd5730d8af",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link as an emerging DSL example and use an original constrained edit-plan schema in the lab.",
    rightsDecisionZhHans: "作为新兴 DSL 示例链接，在实验中使用原创受约束 edit-plan schema。",
    supports: "An agent-readable DSL compiled to FFmpeg, with explicit checks, an intermediate representation, and dry-run output before execution.",
    supportsZhHans: "面向智能体、编译到 FFmpeg 的 DSL，提供显式检查、中间表示与执行前 dry-run 输出。",
    boundary: "The documented scope is constrained and does not establish feature parity with a full NLE. The v0.2.0 tag resolves to a workspace whose Cargo.toml still reports 0.1.0; record the tag and package version separately. Manifests, packaging, and relinking are course design requirements, not verified VEAC features.",
    boundaryZhHans: "文档所示范围有限，不能据此认定与完整 NLE 功能对等。v0.2.0 tag 对应 workspace 的 Cargo.toml 仍写 0.1.0，必须分开记录 tag 与包版本。清单、打包和 relink 是课程设计要求，并非已核验的 VEAC 功能。",
  },
  {
    id: "video-edit-cli",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "computerlovetech/video-edit-cli",
    title: "video-edit-cli",
    publisher: "Computer Love Technology",
    url: "https://github.com/computerlovetech/video-edit-cli/blob/69aeeec7dad7470c1379c7115cbd4d96a4be8686/README.md",
    claimEvidenceUrls: [
      "https://github.com/computerlovetech/video-edit-cli/blob/69aeeec7dad7470c1379c7115cbd4d96a4be8686/README.md",
      "https://github.com/computerlovetech/video-edit-cli/blob/69aeeec7dad7470c1379c7115cbd4d96a4be8686/skills/video-edit-cli/references/edit-plan.md",
      "https://github.com/computerlovetech/video-edit-cli/blob/69aeeec7dad7470c1379c7115cbd4d96a4be8686/src/video_editor/inspection.py",
      "https://github.com/computerlovetech/video-edit-cli/blob/69aeeec7dad7470c1379c7115cbd4d96a4be8686/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/computerlovetech/video-edit-cli/releases/tag/v0.1.2",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v0.1.2",
    resolvedCommit: "69aeeec7dad7470c1379c7115cbd4d96a4be8686",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Paraphrase non-destructive JSON and provenance patterns; the lab ships its own schema and fixtures.",
    rightsDecisionZhHans: "转述非破坏性 JSON 与 provenance 模式；实验提供自己的 schema 与 fixture。",
    supports: "Fixed video operations with JSON stdout, ordered keep decisions with reasons, inspection artifacts, and provenance sidecars suitable for agent tool calls.",
    supportsZhHans: "具有 JSON stdout、带理由的有序保留决策、检查产物与 provenance sidecar 的固定视频操作，适合智能体调用。",
    boundary: "The project has minimal public adoption and must not be treated as a mature production dependency solely because its interface is well shaped.",
    boundaryZhHans: "项目公开采用度很低，不能只因接口设计良好就把它视为成熟生产依赖。",
  },
  {
    id: "davinci-resolve-mcp",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "samuelgursky/davinci-resolve-mcp",
    title: "DaVinci Resolve MCP Server",
    publisher: "Samuel Gursky",
    url: "https://github.com/samuelgursky/davinci-resolve-mcp/blob/c3c075bcc930b4f967b3abae3073bc48e435c5af/docs/guides/media-analysis-guide.md",
    claimEvidenceUrls: [
      "https://github.com/samuelgursky/davinci-resolve-mcp/blob/c3c075bcc930b4f967b3abae3073bc48e435c5af/docs/guides/media-analysis-guide.md",
      "https://github.com/samuelgursky/davinci-resolve-mcp/blob/c3c075bcc930b4f967b3abae3073bc48e435c5af/examples/README.md",
      "https://github.com/samuelgursky/davinci-resolve-mcp/blob/c3c075bcc930b4f967b3abae3073bc48e435c5af/README.md",
      "https://github.com/samuelgursky/davinci-resolve-mcp/blob/c3c075bcc930b4f967b3abae3073bc48e435c5af/LICENSE",
    ],
    accessedOn: ACCESSED_ON,
    stability: "commit-pinned-at-cutoff",
    revision: "c3c075bcc930b4f967b3abae3073bc48e435c5af",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Record the pinned MIT license and link or paraphrase safety guidance; no repository code or screenshots are copied into the course.",
    rightsDecisionZhHans: "记录固定版本的 MIT 许可证并链接或转述安全指南；课程不复制仓库代码或截图。",
    supports: "Read-only source-media inspection, sidecar analysis, dry-run plans before mutation, disposable test projects, and explicit recovery guidance for an MCP-operated NLE.",
    supportsZhHans: "在 MCP 操作的 NLE 中先只读检查源素材、把分析写入 sidecar、变更前 dry-run、使用一次性测试工程并明确恢复说明。",
    boundary: "This community project is not a Blackmagic Design product, Resolve scripting support is version/edition sensitive, and tool access does not supply editorial judgment.",
    boundaryZhHans: "这是社区项目而非 Blackmagic Design 产品；Resolve 脚本支持受版本与版本类型影响，工具访问本身不提供剪辑判断。",
  },
  {
    id: "mosaic-skills",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "mosaic-ai-labs/skills",
    title: "Mosaic agent skills",
    publisher: "Mosaic",
    url: "https://github.com/mosaic-ai-labs/skills/tree/8331979eb00cc4840a78fddf2355c4a04c0c3219",
    claimEvidenceUrls: [
      "https://github.com/mosaic-ai-labs/skills/tree/8331979eb00cc4840a78fddf2355c4a04c0c3219",
      "https://github.com/mosaic-ai-labs/skills/blob/8331979eb00cc4840a78fddf2355c4a04c0c3219/LICENSE",
    ],
    accessedOn: ACCESSED_ON,
    stability: "commit-pinned-at-cutoff",
    revision: "8331979eb00cc4840a78fddf2355c4a04c0c3219",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Record the pinned MIT license and link to the public skills snapshot; do not copy code, branded assets, example footage, or provider output.",
    rightsDecisionZhHans: "记录固定版本的 MIT 许可证并链接公开 skills 快照；不复制代码、品牌资产、示例素材或服务商输出。",
    supports: "A commit-pinned package of agent-facing skill instructions that demonstrates how an external host can describe Mosaic-oriented media operations.",
    supportsZhHans: "固定到提交的 agent-facing skill 指令包，展示外部宿主如何描述面向 Mosaic 的媒体操作。",
    boundary: "The repository snapshot establishes only the checked-in skill surface. Current API availability, authentication, credits, data handling, social connections, and legal terms belong to a separate dated official-web observation and may change independently.",
    boundaryZhHans: "仓库快照只证明已检入的 skill 表面。当前 API 可用性、认证、credits、数据处理、社交连接与法律条款属于另一条有日期的官网观察，可能独立变化。",
  },
  {
    id: "mosaic-service-observation",
    kind: "dated-official-web",
    role: "field-signal",
    title: "Mosaic API and legal pages: dated service observation",
    publisher: "Mosaic",
    url: "https://docs.mosaic.so/api/introduction",
    claimEvidenceUrls: [
      "https://docs.mosaic.so/api/introduction",
      "https://mosaic.so/legal",
    ],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    stability: "dated-observation",
    observedAt: FOLLOW_UP_ACCESSED_ON,
    observedState: "official API introduction and legal pages available at observation time",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase only the dated official pages; never treat live service documentation as immutable repository evidence or authorization to upload or publish media.",
    rightsDecisionZhHans: "只链接并转述有日期的官网页面；绝不把 live 服务文档当成不可变仓库证据，也不视为上传或发布媒体的授权。",
    supports: "At the observation date, Mosaic's official pages described an authenticated cloud API and published service/legal information relevant to evaluating an optional agent workflow.",
    supportsZhHans: "在观察日期，Mosaic 官网描述了需要认证的云 API，并公开了评估可选智能体工作流所需的服务与法律信息。",
    boundary: "This mutable observation does not freeze prices, credits, endpoint behavior, provider relationships, data handling, retention, training use, account permissions, or social-publishing authorization. Re-check all of them before a real project.",
    boundaryZhHans: "这条可变观察不冻结价格、credits、endpoint 行为、服务商关系、数据处理、保留、训练用途、账号权限或社交发布授权；真实项目开始前必须全部复核。",
  },
  {
    id: "model-context-protocol-spec",
    kind: "official-standard",
    role: "protocol-specification",
    title: "Model Context Protocol specification: tools and authorization",
    publisher: "Model Context Protocol",
    url: "https://github.com/modelcontextprotocol/modelcontextprotocol/blob/d8fdc88fb970313247d8a180ac1ec3f6a10a8885/docs/specification/2025-11-25/server/tools.mdx",
    claimEvidenceUrls: [
      "https://github.com/modelcontextprotocol/modelcontextprotocol/blob/d8fdc88fb970313247d8a180ac1ec3f6a10a8885/docs/specification/2025-11-25/server/tools.mdx",
      "https://github.com/modelcontextprotocol/modelcontextprotocol/blob/d8fdc88fb970313247d8a180ac1ec3f6a10a8885/docs/specification/2025-11-25/basic/authorization.mdx",
      "https://modelcontextprotocol.io/specification/2025-11-25",
    ],
    versionAnchorUrl: "https://modelcontextprotocol.io/specification/2025-11-25",
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    publishedOn: "2025-11-25",
    stability: "fixed-standard",
    revision: "2025-11-25",
    resolvedCommit: "d8fdc88fb970313247d8a180ac1ec3f6a10a8885",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase protocol requirements; the course ships no MCP specification text or implementation code.",
    rightsDecisionZhHans: "链接并转述协议要求；课程不再发布 MCP 规范正文或实现代码。",
    supports: "The versioned specification defines tool schemas and results, input validation, access controls, user confirmation for sensitive operations, result validation, timeouts, logging, and an authorization flow with scope and audience controls.",
    supportsZhHans: "版本化规范定义工具 schema 与结果、输入校验、访问控制、敏感操作的人类确认、结果校验、超时、日志，以及带 scope 与 audience 控制的授权流程。",
    boundary: "MCP is a protocol contract, not a host sandbox, media-rights decision, cost policy, undo system, or guarantee that a server, tool description, or tool result is trustworthy. Course-specific allow-lists and fail-closed controls remain an engineering policy.",
    boundaryZhHans: "MCP 是协议合同，不是宿主沙箱、媒体权利决定、成本策略、撤销系统，也不保证 server、工具描述或工具结果可信。课程的 allow-list 与 fail-closed 控制仍属于工程政策。",
  },
  {
    id: "wcag-2-2-captions",
    kind: "official-standard",
    role: "accessibility-standard",
    title: "WCAG 2.2 Success Criterion 1.2.2: Captions (Prerecorded)",
    publisher: "W3C Web Accessibility Initiative",
    url: "https://www.w3.org/TR/WCAG22/#captions-prerecorded",
    claimEvidenceUrls: [
      "https://www.w3.org/TR/WCAG22/#captions-prerecorded",
      "https://www.w3.org/WAI/WCAG22/Understanding/captions-prerecorded.html",
    ],
    versionAnchorUrl: "https://www.w3.org/TR/WCAG22/",
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    publishedOn: "2023-10-05",
    stability: "fixed-standard",
    revision: "WCAG 2.2 W3C Recommendation; SC 1.2.2 Level A",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link to the W3C Recommendation and understanding document; write original captions and examples for the synthetic course media.",
    rightsDecisionZhHans: "链接 W3C Recommendation 与理解文档；为课程合成媒体编写原创字幕和示例。",
    supports: "WCAG 2.2 SC 1.2.2 requires captions for prerecorded audio content in synchronized media except when the media is a clearly labeled alternative for text; W3C explains that captions include relevant speech and non-speech audio information.",
    supportsZhHans: "WCAG 2.2 SC 1.2.2 要求为同步媒体中的预录音频内容提供字幕，除非该媒体是明确标记的文本替代；W3C 说明字幕包含相关语音与非语音音频信息。",
    boundary: "A sidecar file, automatic transcript, or burned-in text does not by itself prove timing, speaker, non-speech, readability, language, or delivery correctness. Applicable law, policy, contract, and platform requirements may demand more than this criterion.",
    boundaryZhHans: "仅有 sidecar、自动转录或烧录文字并不能证明时间、说话人、非语音信息、可读性、语言或交付正确。适用法律、政策、合同与平台可能提出高于本条标准的要求。",
  },
  {
    id: "ffprobe-docs",
    kind: "official-documentation",
    role: "execution-engine",
    title: "ffprobe Documentation",
    publisher: "FFmpeg Project",
    url: "https://ffmpeg.org/ffprobe.html",
    claimEvidenceUrls: ["https://ffmpeg.org/ffprobe.html"],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    stability: "dated-observation",
    revision: "official documentation observed 2026-08-28",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase the official documentation; ship only project-authored commands, manifests, and media fixtures.",
    rightsDecisionZhHans: "链接并转述官方文档；只发布项目原创命令、manifest 与媒体 fixture。",
    supports: "ffprobe gathers multimedia stream information and can emit human- and machine-readable representations of container, stream, packet, frame, and timecode observations.",
    supportsZhHans: "ffprobe 收集多媒体流信息，并能以人类或机器可读形式输出容器、流、packet、frame 与 timecode 观察。",
    boundary: "A successful probe describes what the selected build can observe; it does not establish identity, rights, privacy clearance, semantic truth, or cross-machine bitwise reproducibility.",
    boundaryZhHans: "成功 probe 只描述所选构建能观察到的内容；不证明身份、权利、隐私许可、语义真实性或跨机器逐位可复现。",
  },
  {
    id: "opentimelineio-docs",
    kind: "official-documentation",
    role: "timeline-contract",
    title: "OpenTimelineIO timeline structure tutorial",
    publisher: "Academy Software Foundation",
    url: "https://opentimelineio.readthedocs.io/en/latest/tutorials/otio-timeline-structure.html",
    claimEvidenceUrls: ["https://opentimelineio.readthedocs.io/en/latest/tutorials/otio-timeline-structure.html"],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    stability: "dated-observation",
    revision: "0.19.0.dev1 documentation observed 2026-08-28",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link to the official tutorial and paraphrase timeline behavior; do not copy diagrams or examples into the course.",
    rightsDecisionZhHans: "链接官方教程并转述时间线行为；不把图表或示例复制进课程。",
    supports: "The tutorial distinguishes source ranges, available ranges, tracks, stacks, and transitions, and states that OTIO itself does not snap or verify unavailable source ranges.",
    supportsZhHans: "教程区分 source range、available range、track、stack 与 transition，并说明 OTIO 自身不会 snap 或验证不可用源区间。",
    boundary: "The latest documentation is mutable and describes a development version; production interchange still requires a pinned library and adapter fidelity tests.",
    boundaryZhHans: "latest 文档可变且描述开发版本；生产交换仍需固定库版本并测试 adapter 保真度。",
  },
  {
    id: "w3c-media-planning",
    kind: "official-documentation",
    role: "accessibility-standard",
    title: "Planning Audio and Video Media",
    publisher: "W3C Web Accessibility Initiative",
    url: "https://www.w3.org/WAI/media/av/planning/",
    claimEvidenceUrls: ["https://www.w3.org/WAI/media/av/planning/"],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    publishedOn: "2024-09-17",
    stability: "fixed-standard",
    revision: "WAI resource updated 2024-09-17",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase the WAI planning checklist; use original examples and applicability records in the course.",
    rightsDecisionZhHans: "链接并转述 WAI 规划清单；课程使用原创示例与适用性记录。",
    supports: "WAI separates captions, transcripts, descriptive transcripts, audio description, accessible media-player support, and explicit not-applicable communication for audio and video projects.",
    supportsZhHans: "WAI 区分字幕、转录、描述性转录、音频描述、可访问播放器支持，以及音视频项目中明确的不适用说明。",
    boundary: "The planning resource explains WCAG relationships and user needs; it is not a substitute for testing the actual player, file, language, policy, contract, or jurisdiction.",
    boundaryZhHans: "该规划资源解释 WCAG 关系与用户需求；不能替代对实际播放器、文件、语言、政策、合同或法域的测试。",
  },
  {
    id: "w3c-visual-description",
    kind: "official-documentation",
    role: "accessibility-standard",
    title: "Description of Visual Information",
    publisher: "W3C Web Accessibility Initiative",
    url: "https://www.w3.org/WAI/media/av/description/",
    claimEvidenceUrls: ["https://www.w3.org/WAI/media/av/description/"],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    stability: "fixed-standard",
    revision: "WAI visual-description guidance observed 2026-08-28",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase the WAI guidance; the course supplies only original description examples for its own synthetic fixture.",
    rightsDecisionZhHans: "链接并转述 WAI 指南；课程只为自身合成 fixture 提供原创描述示例。",
    supports: "WAI explains when visual information needs audio description or a descriptive transcript and how description should communicate meaningful visual information without unnecessary detail.",
    supportsZhHans: "WAI 解释何时视觉信息需要音频描述或描述性转录，以及描述应如何传达有意义的视觉信息而不过度堆砌细节。",
    boundary: "Applicability depends on whether the visuals add information not already available in audio or equivalent text and on the selected conformance target.",
    boundaryZhHans: "是否适用取决于画面是否增加音频或等效文本中没有的信息，也取决于所选符合性目标。",
  },
  {
    id: "itu-bs-1770",
    kind: "official-standard",
    role: "audio-standard",
    title: "ITU-R BS.1770: loudness and true-peak measurement algorithms",
    publisher: "International Telecommunication Union",
    url: "https://www.itu.int/rec/R-REC-BS.1770",
    claimEvidenceUrls: ["https://www.itu.int/rec/R-REC-BS.1770"],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    stability: "dated-observation",
    revision: "in-force recommendation page updated 2025-03-14; observed 2026-08-28",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link to the ITU recommendation record and paraphrase only the measurement scope; do not redistribute the standard text.",
    rightsDecisionZhHans: "链接 ITU recommendation 记录，仅转述测量范围；不再分发标准正文。",
    supports: "The in-force BS.1770 recommendation defines algorithms for measuring audio programme loudness and true-peak audio level.",
    supportsZhHans: "现行 BS.1770 recommendation 定义音频节目响度与 true-peak 音频电平的测量算法。",
    boundary: "A measurement algorithm is not one universal delivery target; each destination contract must state its target, tolerance, channel layout, and measurement procedure.",
    boundaryZhHans: "测量算法不是一个通用交付目标；每个目的地合同都必须声明目标、容差、声道布局和测量步骤。",
  },
  {
    id: "ebu-r128",
    kind: "official-standard",
    role: "audio-standard",
    title: "EBU R 128 loudness normalisation",
    publisher: "European Broadcasting Union",
    url: "https://tech.ebu.ch/publications/r128",
    claimEvidenceUrls: ["https://tech.ebu.ch/publications/r128"],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    publishedOn: "2023-11-01",
    stability: "fixed-standard",
    revision: "version 5.0, November 2023",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link to the EBU publication record and paraphrase the recommendation; do not redistribute the publication.",
    rightsDecisionZhHans: "链接 EBU 出版记录并转述 recommendation；不再分发出版物。",
    supports: "EBU R 128 version 5.0 is a broadcast loudness-normalisation recommendation that references measurement practice and a -23 LUFS target with stated tolerances in its revision history.",
    supportsZhHans: "EBU R 128 5.0 是广播响度标准化建议，其版本记录涉及测量实践及带容差的 -23 LUFS 目标。",
    boundary: "R 128 is not silently applied to every social platform; the course uses it to teach the difference between a measurement standard, a broadcast recommendation, and a destination contract.",
    boundaryZhHans: "R 128 不会被默认套用到所有社交平台；课程用它区分测量标准、广播建议和目的地合同。",
  },
  {
    id: "aces-docs",
    kind: "official-documentation",
    role: "color-management",
    title: "Academy Color Encoding System documentation",
    publisher: "Academy of Motion Picture Arts and Sciences",
    url: "https://docs.acescentral.com/",
    claimEvidenceUrls: ["https://docs.acescentral.com/"],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    stability: "dated-observation",
    revision: "official documentation observed 2026-08-28",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase ACES concepts; do not copy diagrams, transforms, or specification text into the course.",
    rightsDecisionZhHans: "链接并转述 ACES 概念；不复制图表、transform 或规范正文。",
    supports: "ACES is an industry color-management standard spanning capture, editing, visual effects, mastering, presentation, archiving, and remastering through declared transforms.",
    supportsZhHans: "ACES 是覆盖拍摄、剪辑、视效、母版、展示、归档与再母版的行业色彩管理标准，并通过声明的 transforms 管理流程。",
    boundary: "The core sandbox remains a documented SDR Rec.709 branch; ACES is taught as an official builder-extension reference, not as a mandatory or automatic color-correctness proof.",
    boundaryZhHans: "核心 sandbox 保持有记录的 SDR Rec.709 分支；ACES 作为官方 builder 扩展参考，而不是强制要求或自动色彩正确性证明。",
  },
  {
    id: "owasp-prompt-injection",
    kind: "official-documentation",
    role: "security-guidance",
    title: "OWASP LLM01:2025 Prompt Injection",
    publisher: "OWASP GenAI Security Project",
    url: "https://genai.owasp.org/llmrisk/llm01-prompt-injection/",
    claimEvidenceUrls: ["https://genai.owasp.org/llmrisk/llm01-prompt-injection/"],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    publishedOn: "2025-01-01",
    stability: "dated-observation",
    revision: "LLM01:2025 observed 2026-08-28",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase OWASP mitigation guidance; use only original adversarial fixtures and test cases in the course.",
    rightsDecisionZhHans: "链接并转述 OWASP 缓解指南；课程仅使用原创对抗 fixture 与测试。",
    supports: "OWASP distinguishes direct and indirect prompt injection, including attacks carried by external files, websites, and multimodal content that can influence connected functions and decisions.",
    supportsZhHans: "OWASP 区分直接与间接 prompt injection，包括通过外部文件、网页和多模态内容影响已连接功能与决策的攻击。",
    boundary: "OWASP guidance is risk guidance, not a complete certification; prompt filtering alone cannot enforce filesystem, identity, network, cost, secret, or publish boundaries.",
    boundaryZhHans: "OWASP 是风险指南而非完整认证；仅过滤 prompt 不能强制文件系统、身份、网络、成本、secret 或发布边界。",
  },
  {
    id: "owasp-excessive-agency",
    kind: "official-documentation",
    role: "security-guidance",
    title: "OWASP LLM06:2025 Excessive Agency",
    publisher: "OWASP GenAI Security Project",
    url: "https://genai.owasp.org/llmrisk/llm062025-excessive-agency/",
    claimEvidenceUrls: ["https://genai.owasp.org/llmrisk/llm062025-excessive-agency/"],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    publishedOn: "2025-01-01",
    stability: "dated-observation",
    revision: "LLM06:2025 observed 2026-08-28",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase OWASP guidance; do not copy third-party attack stories or imply OWASP certification.",
    rightsDecisionZhHans: "链接并转述 OWASP 指南；不复制第三方攻击故事，也不暗示获得 OWASP 认证。",
    supports: "OWASP traces damaging agent actions to excessive functionality, permissions, or autonomy and recommends minimizing tools, functions, privileges, and unreviewed high-impact actions.",
    supportsZhHans: "OWASP 将有害智能体动作追溯到过度功能、权限或自主性，并建议缩减工具、功能、权限以及未经审查的高影响动作。",
    boundary: "Least privilege reduces blast radius but does not prove a model will resist manipulation; independent validation and explicit human confirmation remain necessary.",
    boundaryZhHans: "最小权限降低爆炸半径，但不能证明模型会抵抗操纵；仍需独立验证与显式人工确认。",
  },
  {
    id: "c2pa-spec",
    kind: "official-standard",
    role: "media-provenance",
    title: "C2PA Technical Specification 2.4",
    publisher: "Coalition for Content Provenance and Authenticity",
    url: "https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html",
    claimEvidenceUrls: ["https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html"],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    publishedOn: "2026-01-01",
    stability: "fixed-standard",
    revision: "C2PA Specifications 2.4",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase the CC BY 4.0 specification with attribution; do not present Content Credentials as rights, consent, or truth certificates.",
    rightsDecisionZhHans: "按 CC BY 4.0 署名链接并转述规范；不把 Content Credentials 说成权利、同意或真相证书。",
    supports: "C2PA 2.4 specifies tamper-evident manifests, claims, assertions, content bindings, signer identity, validation, provenance, and AI-disclosure assertions for digital assets.",
    supportsZhHans: "C2PA 2.4 规范数字资产的防篡改 manifest、claim、assertion、内容绑定、签名者身份、验证、provenance 与 AI disclosure assertion。",
    boundary: "The specification explicitly avoids value judgments about provenance assertions; validation associates claims with an asset and signer but does not prove factual truth, ownership, consent, or lawful use.",
    boundaryZhHans: "规范明确避免评价 provenance assertion 的好坏；验证只把 claim 与资产和签名者关联，不证明事实真实性、所有权、同意或合法使用。",
  },
  {
    id: "bbc-editorial-accuracy",
    kind: "official-documentation",
    role: "editorial-guidance",
    title: "BBC Editorial Guidelines: Accuracy",
    publisher: "British Broadcasting Corporation",
    url: "https://downloads.bbc.co.uk/guidelines/editorialguidelines/pdfs/Editorial_Guidelines_in_full.pdf",
    claimEvidenceUrls: ["https://downloads.bbc.co.uk/guidelines/editorialguidelines/pdfs/Editorial_Guidelines_in_full.pdf"],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    stability: "dated-observation",
    revision: "full editorial guidelines PDF observed 2026-08-28, section 3.4.16-3.4.20",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase the editorial boundary; do not redistribute the PDF or present BBC policy as global law.",
    rightsDecisionZhHans: "链接并转述剪辑边界；不再分发 PDF，也不把 BBC 政策描述为全球法律。",
    supports: "The accuracy guidance warns against inter-cutting or manipulating factual material in ways that materially mislead, distort chronology or meaning, or obscure where reconstruction begins and ends.",
    supportsZhHans: "准确性指南警告不要以会造成实质性误导、扭曲时间顺序或含义、或模糊重建起止边界的方式交叉剪接或操纵事实材料。",
    boundary: "BBC policy is a strong primary editorial-practice source for its own scope, not a complete statement of every genre, broadcaster, platform, contract, or jurisdiction.",
    boundaryZhHans: "BBC 政策是其范围内强有力的第一方编辑实践来源，但不是所有类型、广播机构、平台、合同或法域的完整规则。",
  },
  {
    id: "adobe-j-l-cuts",
    kind: "official-documentation",
    role: "editorial-guidance",
    title: "Adobe Premiere: Perform J cuts and L cuts",
    publisher: "Adobe",
    url: "https://helpx.adobe.com/premiere/desktop/edit-projects/trim-clips/perform-j-cuts-and-l-cuts.html",
    claimEvidenceUrls: ["https://helpx.adobe.com/premiere/desktop/edit-projects/trim-clips/perform-j-cuts-and-l-cuts.html"],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    publishedOn: "2025-08-22",
    stability: "dated-observation",
    revision: "official vendor documentation updated 2025-08-22",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase the split-edit definitions; no Adobe screenshots, video, or branded tutorial media are copied.",
    rightsDecisionZhHans: "链接并转述 split edit 定义；不复制 Adobe 截图、视频或品牌教程媒体。",
    supports: "Adobe defines J and L cuts as split edits where sound and picture change at different times: incoming audio leads picture in a J cut, while outgoing audio continues under new picture in an L cut.",
    supportsZhHans: "Adobe 将 J/L cut 定义为声音与画面在不同时间切换的 split edit：J cut 中下一段声音先行，L cut 中上一段声音延续到新画面。",
    boundary: "Vendor documentation establishes terminology and mechanics, not universal aesthetic quality, semantic integrity, or endorsement of a particular edit.",
    boundaryZhHans: "厂商文档只支持术语与操作机制，不证明普遍审美质量、语义完整性或对特定剪辑的背书。",
  },
  {
    id: "eu-ai-act-article-50",
    kind: "law-regulation",
    role: "legal-guidance",
    title: "Regulation (EU) 2024/1689, Article 50",
    publisher: "EUR-Lex",
    url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689",
    claimEvidenceUrls: ["https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689"],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    publishedOn: "2024-07-12",
    effectiveOn: "2024-08-01",
    jurisdiction: "European Union",
    stability: "fixed-standard",
    revision: "Regulation (EU) 2024/1689, Article 50",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link to EUR-Lex and paraphrase with an explicit EU-jurisdiction and no-legal-advice boundary; do not copy long statutory passages.",
    rightsDecisionZhHans: "链接 EUR-Lex 并在明确欧盟法域与非法律意见边界下转述；不复制长篇法条。",
    supports: "Article 50 establishes specified transparency duties for providers and deployers of certain AI systems, including marking and disclosure provisions for defined generated or manipulated media and deep fakes, subject to scope and exceptions.",
    supportsZhHans: "第50条为特定 AI 系统提供者与部署者规定透明度义务，包括对定义范围内生成或操纵媒体及 deep fake 的标记与披露条款，并有适用范围与例外。",
    boundary: "Applicability, dates, roles, exceptions, sector rules, and enforcement are jurisdiction- and fact-dependent. The course is not legal advice and does not turn Article 50 into a global rule.",
    boundaryZhHans: "适用性、日期、角色、例外、行业规则与执行取决于法域和事实。课程不是法律意见，也不把第50条外推为全球规则。",
  },
  {
    id: "usco-ai-study",
    kind: "regulatory-guidance",
    role: "legal-guidance",
    title: "U.S. Copyright Office Artificial Intelligence Study",
    publisher: "United States Copyright Office",
    url: "https://www.copyright.gov/policy/artificial-intelligence/",
    claimEvidenceUrls: [
      "https://www.copyright.gov/policy/artificial-intelligence/",
      "https://www.copyright.gov/newsnet/2024/1048.html",
      "https://www.copyright.gov/newsnet/2025/1060.html",
    ],
    accessedOn: FOLLOW_UP_ACCESSED_ON,
    publishedOn: "2025-01-29",
    jurisdiction: "United States",
    stability: "dated-observation",
    revision: "AI Report Part 1 digital replicas and Part 2 copyrightability",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase the Office's reports with a United States and no-legal-advice boundary; do not redistribute report text.",
    rightsDecisionZhHans: "在明确美国法域与非法律意见边界下链接并转述报告；不再分发报告正文。",
    supports: "The Office's study separately addresses digital replicas and copyrightability, including the role of human-authored expressive contribution when AI-generated material appears in a work.",
    supportsZhHans: "美国版权局研究分别讨论数字替身与可版权性，包括作品含 AI 生成材料时人类创作性表达贡献的作用。",
    boundary: "The reports are United States guidance and policy analysis, not a ruling on a learner's ownership, registration, publicity, privacy, contract, consent, or international-law position.",
    boundaryZhHans: "这些报告属于美国指导与政策分析，不裁定学习者项目的所有权、登记、形象权、隐私、合同、同意或国际法问题。",
  },
  {
    id: "x-video-use-release",
    kind: "x-post",
    role: "field-signal",
    title: "Introducing Video Use",
    publisher: "Gregor Zunic on X",
    url: "https://x.com/gregpr07/status/2044554557221675380",
    claimEvidenceUrls: [
      "https://x.com/gregpr07/status/2044554557221675380",
      "https://publish.x.com/oembed?url=https%3A%2F%2Fx.com%2Fgregpr07%2Fstatus%2F2044554557221675380",
    ],
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-04-15",
    stability: "dated-field-signal",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase the dated post; do not copy the post video, screenshots, or wording.",
    rightsDecisionZhHans: "链接并转述该有日期的帖子；不复制帖子视频、截图或原文表达。",
    supports: "A project-author launch signal whose oEmbed-visible text describes a talk-to-camera workflow producing final.mp4 while a coding agent handles filler removal, color correction, captions, and animations. Silence handling is documented by the repository, not the visible oEmbed excerpt.",
    supportsZhHans: "项目作者的发布信号；oEmbed 可见文本说明对镜头讲话的工作流输出 final.mp4，同时编码智能体处理口头填充、调色、字幕与动画。静音处理来自仓库文档，而非 oEmbed 可见片段。",
    boundary: "A launch demo and author claim do not establish universal quality, reliability, time savings, or zero cost; repository inspection supplies the technical corroboration.",
    boundaryZhHans: "发布演示与作者自述不能证明普遍质量、可靠性、节时或零成本；技术佐证来自仓库检查。",
    statusId: "2044554557221675380",
    authorIdentity: "Gregor Zunic (@gregpr07)",
    authorRole: "Post author; project relationship is corroborated by the paired repository, not inferred from oEmbed alone",
    threadContext: "Thread topology was not independently established. The oEmbed text is truncated; identity, date, URL, and only the visible launch text were checked through X official oEmbed. Direct status-page access was inconsistent during the audit and is not used as the text record.",
    mediaContext: "Linked demonstration media is not copied, embedded, or treated as a reproducible benchmark.",
    textCompleteness: "oembed-truncated-repository-corroborated",
    verificationMethod: "x-official-oembed",
    verifiedOn: ACCESSED_ON,
    verificationStatus: "identity-date-url-verified-visible-text-truncated",
    corroborationScope: "oEmbed verifies identity, date, URL, and a truncated launch statement; the pinned repositories corroborate workflow mechanisms only, not quality, savings, or the full post wording.",
    corroborationScopeZhHans: "oEmbed 核验身份、日期、URL 与被截断的发布陈述；固定仓库只佐证工作流机制，不佐证质量、节时或帖子全文。",
    corroboratingSourceIds: ["video-use", "ffmpeg"],
  },
  {
    id: "x-remotion-skills",
    kind: "x-post",
    role: "field-signal",
    title: "Remotion now has Agent Skills",
    publisher: "Remotion on X",
    url: "https://x.com/Remotion/status/2013626968386765291",
    claimEvidenceUrls: [
      "https://x.com/Remotion/status/2013626968386765291",
      "https://publish.x.com/oembed?url=https%3A%2F%2Fx.com%2FRemotion%2Fstatus%2F2013626968386765291",
    ],
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-01-20",
    stability: "dated-field-signal",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link to the official post and repository; no post media is republished.",
    rightsDecisionZhHans: "链接官方帖子与仓库；不再发布帖子媒体。",
    supports: "An official dated announcement that Remotion publishes Agent Skills for coding-agent video workflows.",
    supportsZhHans: "Remotion 官方发布的有日期公告，说明其为编码智能体视频工作流提供 Agent Skills。",
    boundary: "The announcement establishes availability, not that one prompt reliably produces a finished edit or that every use is covered by a free license.",
    boundaryZhHans: "该公告只证明功能可用，不证明一句提示词能可靠完成成片，也不证明所有使用都属于免费许可。",
    statusId: "2013626968386765291",
    authorIdentity: "Remotion (@Remotion)",
    authorRole: "Official project account",
    threadContext: "Thread topology was not independently established; the announcement text used by the course is complete in X official oEmbed.",
    mediaContext: "Demonstration media is linked only and is not used as a quality benchmark.",
    textCompleteness: "oembed-complete",
    verificationMethod: "x-official-oembed",
    verifiedOn: ACCESSED_ON,
    verificationStatus: "identity-date-url-and-visible-text-verified",
    corroborationScope: "oEmbed contains the complete announcement used by the course; repositories corroborate availability and scope, not generated-output quality.",
    corroborationScopeZhHans: "oEmbed 包含课程使用的完整公告；仓库佐证可用性与能力范围，不佐证生成结果质量。",
    corroboratingSourceIds: ["remotion", "remotion-skills"],
  },
  {
    id: "x-davinci-mcp",
    kind: "x-post",
    role: "field-signal",
    title: "DaVinci Resolve MCP Server showcase",
    publisher: "GitHub Projects Community on X",
    url: "https://x.com/GithubProjects/status/2075105180023144837",
    claimEvidenceUrls: [
      "https://x.com/GithubProjects/status/2075105180023144837",
      "https://publish.x.com/oembed?url=https%3A%2F%2Fx.com%2FGithubProjects%2Fstatus%2F2075105180023144837",
    ],
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-07-09",
    stability: "dated-field-signal",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase capability categories; do not reuse the showcase media.",
    rightsDecisionZhHans: "链接并转述能力类别；不复用展示媒体。",
    supports: "A dated community showcase whose oEmbed-visible text lists project lifecycle, media-pool, editing, color-grading, Fusion, and Fairlight access through a Resolve MCP server.",
    supportsZhHans: "有日期的社区展示；oEmbed 可见文本列出 Resolve MCP server 的工程生命周期、媒体池、剪辑、调色、Fusion 与 Fairlight 访问。",
    boundary: "The display name says GitHub Projects Community; organizational affiliation is not inferred. Current tool counts and safety behavior must come from specifically cited repository documents.",
    boundaryZhHans: "显示名为 GitHub Projects Community；课程不据此推断组织隶属。当前工具数量与安全行为必须来自明确引用的仓库文档。",
    statusId: "2075105180023144837",
    authorIdentity: "GitHub Projects Community (@GithubProjects)",
    authorRole: "Showcase account; organizational affiliation is not established by oEmbed",
    threadContext: "Thread topology was not independently established. The oEmbed text is truncated; identity, date, URL, and the visible capability list were verified through X official oEmbed.",
    mediaContext: "Linked demo media is not copied and cannot establish the quality of arbitrary edits.",
    textCompleteness: "oembed-truncated-repository-corroborated",
    verificationMethod: "x-official-oembed",
    verifiedOn: ACCESSED_ON,
    verificationStatus: "identity-date-url-verified-visible-text-truncated",
    corroborationScope: "oEmbed verifies the display name, date, URL, and a truncated capability showcase; the pinned media-analysis guide and examples corroborate only a bounded, review-oriented subset and its safety patterns.",
    corroborationScopeZhHans: "oEmbed 核验显示名、日期、URL 与被截断的能力展示；固定 media-analysis guide 与 examples 只佐证有边界、面向审查的能力子集及安全模式。",
    corroboratingSourceIds: ["davinci-resolve-mcp"],
  },
  {
    id: "x-creator-workflow-guide",
    kind: "x-post",
    role: "field-signal",
    title: "Claude Code video-production guide expansion",
    publisher: "りょー on X",
    url: "https://x.com/cryptoninjanime/status/1955108960060706862",
    claimEvidenceUrls: [
      "https://x.com/cryptoninjanime/status/1955108960060706862",
      "https://publish.x.com/oembed?url=https%3A%2F%2Fx.com%2Fcryptoninjanime%2Fstatus%2F1955108960060706862",
    ],
    accessedOn: ACCESSED_ON,
    publishedOn: "2025-08-12",
    stability: "dated-field-signal",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and summarize only the oEmbed-visible guide-expansion statement; do not copy the attached video or infer the truncated continuation.",
    rightsDecisionZhHans: "只链接并概述 oEmbed 可见的指南扩展陈述；不复制附件视频，也不推断被截断的后文。",
    supports: "A dated creator signal whose visible oEmbed text says a planned Remotion-and-Claude-Code editing course broadened into a wider Claude Code video-production guide as more techniques and information emerged.",
    supportsZhHans: "有日期的创作者实践信号：oEmbed 可见文本说明，原拟的 Remotion×Claude Code 剪辑课程随着更多技术与信息出现，扩展为更广的 Claude Code 视频制作指南。",
    boundary: "The post does not publish the complete project, prompts, source footage, failure cases, or a comparative benchmark.",
    boundaryZhHans: "帖子没有公开完整工程、提示词、源素材、失败案例或对比基准。",
    statusId: "1955108960060706862",
    authorIdentity: "りょー｜AI動画制作・編集 (@cryptoninjanime)",
    authorRole: "Post author; no formal role or organizational affiliation is inferred from oEmbed",
    threadContext: "Creator guide-expansion post; identity, date, URL, and only the visible text were verified through X official oEmbed. The continuation is truncated and is not reconstructed from search snippets.",
    mediaContext: "Any attached or linked media is not copied and is not treated as performance evidence; media context was not independently verified.",
    textCompleteness: "oembed-truncated-repository-corroborated",
    verificationMethod: "x-official-oembed",
    verifiedOn: ACCESSED_ON,
    verificationStatus: "identity-date-url-verified-visible-text-truncated",
    corroborationScope: "The repositories corroborate the Remotion and agent-skill mechanisms only. The post supports scope expansion as a dated creator observation; it does not compare tool quality, efficiency, or human replacement.",
    corroborationScopeZhHans: "仓库只佐证 Remotion 与 agent skill 机制；帖子只支持有日期的创作者范围扩展观察，不比较工具质量、效率，也不证明可以取代人类。",
    corroboratingSourceIds: ["remotion", "remotion-skills"],
  },
  {
    id: "x-mosaic-slack",
    kind: "x-post",
    role: "field-signal",
    title: "Mosaic video editing API for agents",
    publisher: "Adish Jain on X",
    url: "https://x.com/_adishj/status/2032121100126265551",
    claimEvidenceUrls: [
      "https://x.com/_adishj/status/2032121100126265551",
      "https://publish.x.com/oembed?url=https%3A%2F%2Fx.com%2F_adishj%2Fstatus%2F2032121100126265551",
      "https://mosaic.so/legal",
    ],
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-03-12",
    stability: "dated-field-signal",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase the workflow; the archived-footage demo and all post media are excluded from course assets.",
    rightsDecisionZhHans: "链接并转述工作流；档案素材演示及全部帖子媒体不进入课程资产。",
    supports: "A dated, oEmbed-truncated demonstration post whose visible text says a Slack-hosted agent used the Mosaic API to clip, edit, and post video.",
    supportsZhHans: "有日期、被 oEmbed 截断的演示帖；可见文本说明 Slack 中的智能体使用 Mosaic API 对视频进行 clip、edit 与 post。",
    boundary: "The post does not establish footage authorization, privacy suitability, output quality, or permission for unattended publishing; those require separate evidence and approval.",
    boundaryZhHans: "帖子不证明素材授权、隐私适用性、输出质量或无人值守发布权限；这些都需要单独证据与批准。",
    statusId: "2032121100126265551",
    authorIdentity: "Adish Jain (@_adishj)",
    authorRole: "Post author using first-person plural about Mosaic; no formal title is inferred from oEmbed",
    threadContext: "Demonstration post; oEmbed-truncated. Identity, date, URL, and the visible clip-edit-post statement were verified through X official oEmbed; thread structure was not independently established.",
    mediaContext: "The demonstration uses described archival footage whose authorization is not documented in the post; no media is copied.",
    textCompleteness: "oembed-truncated-repository-corroborated",
    verificationMethod: "x-official-oembed",
    verifiedOn: ACCESSED_ON,
    verificationStatus: "identity-date-url-verified-visible-text-truncated",
    corroborationScope: "oEmbed verifies identity, date, URL, and a truncated demonstration statement; Mosaic documentation corroborates API mechanics and its legal page supports the separate privacy boundary, but neither proves footage authorization or output quality.",
    corroborationScopeZhHans: "oEmbed 核验身份、日期、URL 与被截断的演示陈述；Mosaic 文档佐证 API 机制，legal 页面支撑独立隐私边界，但都不能证明素材授权或输出质量。",
    corroboratingSourceIds: ["mosaic-skills", "mosaic-service-observation"],
  },
] as const satisfies readonly AgenticVideoEditingSourceRecord[];

const VERSION_WATCH_SOURCE_IDS = new Set([
  "qwen3-vl-issue-1761",
  "montaj",
  "timeline-studio",
  "qcut",
  "velorn",
]);
const ATLAS_ONLY_SOURCE_IDS = new Set([
  "qwen3-vl",
  "auto-editor",
  "veac",
]);

/**
 * Explicitly separates evidence used by teaching claims from dated signals,
 * release watching, and atlas-only discovery. X never becomes effectiveness
 * evidence merely to increase a source-use count.
 */
export const AGENTIC_VIDEO_EDITING_SOURCE_USAGE =
  Object.fromEntries(AGENTIC_VIDEO_EDITING_SOURCES.map((source) => [
    source.id,
    source.kind === "x-post"
      ? "field-signal-context"
      : VERSION_WATCH_SOURCE_IDS.has(source.id)
        ? "version-watch"
        : ATLAS_ONLY_SOURCE_IDS.has(source.id)
          ? "atlas-only"
          : "claim-evidence",
  ])) as Readonly<Record<string, AgenticVideoEditingSourceUsage>>;

export function getAgenticVideoEditingSource(
  id: string,
): AgenticVideoEditingSourceRecord {
  const source = AGENTIC_VIDEO_EDITING_SOURCES.find((item) => item.id === id);
  if (!source) throw new Error(`Unknown agentic-video-editing source: ${id}`);
  return source;
}
