export const RESPONSIBLE_AI_EN_COURSE_COPY = {
  meta: {
    title: "Responsible AI and Human Oversight",
    kicker: "Course 16 · Govern purpose, evidence, authority, and recourse",
    summary: "Build a decision-ready governance dossier for an AI use case. The course treats safety as an operating system of bounded purpose, tested impacts, human authority, contestability, incident learning, and explicit no-deploy conditions.",
    audience: "AI product teams, educators, researchers, engineers, reviewers, and decision owners who must justify whether and how an AI system should be used.",
    prerequisite: "AI literacy. Basic evaluation knowledge is recommended for the technical audit units.",
    level: "Beginner to intermediate",
    duration: "10 modules · 10 hr 50 min",
    startCta: "Classify the use case",
    resumeCta: "Resume the governance dossier",
    fallbackNotice: "The course interface follows your selected language, but the teaching text on this page is English. English content remains left-to-right.",
    evidenceNote: "Core methods are grounded in primary standards, official guidance, and original research. Jurisdiction-specific rules are dated appendices, not permanent legal conclusions.",
  },
  principles: [
    "Govern a stated use in a stated context, not an abstract model in isolation.",
    "Separate a system's capability from its authority to affect people or resources.",
    "Test distributional harms and uncertainty before selecting a release threshold.",
    "Give a named person the power, information, time, and procedure to stop or override the system.",
    "Preserve contestability, incident evidence, and no-deploy conditions as first-class release artifacts.",
  ],
  outcomes: [
    "Classify an AI use case by purpose, affected population, consequence, reversibility, and exposure.",
    "Produce an impact assessment, stakeholder map, risk register, and data map with accountable owners.",
    "Run subgroup and uncertainty checks without claiming that one fairness metric resolves the policy choice.",
    "Write model cards, datasheets, and an original system assurance card whose limitations are usable at the decision point.",
    "Design approval, override, stopping, escalation, appeal, and responsibility boundaries.",
    "Red-team realistic misuse and failure paths, then connect findings to incident response and disclosure.",
    "Issue a reviewable go, conditional-go, or no-go memo whose evidence and unresolved risks are visible.",
  ],
  quiz: {
    title: "Responsible AI final assessment",
    intro: "Twelve questions are drawn from the bank. Passing requires at least 10 correct and every critical human-authority, data-rights, and no-deploy question correct.",
  },
  capstone: {
    title: "Governance dossier capstone",
    intro: "Apply the full governance loop to one bounded AI use case. A checklist is not evidence: every artifact must name the decision, owner, evidence, uncertainty, and next gate.",
    instructions: [
      "Use a real or carefully specified hypothetical use case without uploading personal, confidential, or restricted data.",
      "Keep all nine artifacts versioned and cross-reference their risk IDs, evidence IDs, decision owners, and unresolved questions.",
      "Finish with a go, conditional-go, or no-go memo. A conditional decision must name the condition, verifier, deadline, and rollback trigger.",
    ],
    attestation: "I reviewed every required artifact and did not represent checklist completion as legal approval, certification, or permission to automate a high-risk decision.",
  },
} as const;

export const RESPONSIBLE_AI_EN_MODULES = {
  "purpose-risk-classification": {
    title: "Purpose and risk classification",
    summary: "Turn an attractive capability into a bounded use-case contract before discussing deployment.",
    objective: "State who uses the system, for what decision, on whose data, with what consequence, exposure, reversibility, and accountable owner.",
    artifact: "Purpose and risk brief",
    sections: [
      { heading: "Classify the use, not the label", paragraphs: ["A model called an assistant can still shape a consequential decision. Begin with the operational purpose, users, affected people, data flow, action, and downstream consequence. Risk rises when errors are difficult to detect, affect rights or access, scale quickly, or cannot be reversed."], sourceIds: ["nist-ai-rmf"], evidenceMode: "source-grounded" },
      { heading: "Write the boundary", paragraphs: ["List intended uses, prohibited uses, out-of-scope populations, operating assumptions, and the conditions that force a stop. A classification organises scrutiny; it does not grant authority, prove compliance, or make an unsafe use acceptable."], sourceIds: ["oecd-ai-principles"], evidenceMode: "instructional-synthesis" },
      { heading: "Choose evidence before release", paragraphs: ["For each risk, name the test, decision threshold, reviewer, and action on failure. Include a no-deploy condition now, while there is still room to change the design."], sourceIds: ["nist-ai-rmf"], evidenceMode: "instructional-synthesis" },
    ],
    practice: { title: "Draft the purpose boundary", brief: "Classify one proposed AI use using consequence, reversibility, exposure, and affected population.", steps: ["Open the original fictional case at /courses/responsible-ai/governance-case-synthetic-v1.json and read its NOTICE before treating any field as evidence.", "Write the intended decision and prohibited decisions, then name direct and indirect stakeholders.", "Record three failure modes and one no-deploy condition."], deliverable: "A one-page purpose and risk brief with an accountable owner.", reviewGate: "A reviewer can tell exactly what the system is not permitted to do." },
    checkpoint: { question: "What must happen before a team treats a high-stakes AI assistant as deployable?", options: ["Document the bounded use, evidence, authority, affected people, and no-deploy conditions", "Confirm that the model has a high general benchmark score", "Ask users to accept a broad disclaimer", "Rename the system as decision support"], correctIndex: 0, explanation: "A label or generic benchmark does not define the actual decision, risk, authority, or release evidence." },
    takeaway: "Risk classification is a scrutiny map, never an authorization stamp.",
  },
  "stakeholders-impact-assessment": {
    title: "Stakeholders and impact assessment",
    summary: "Trace benefits, burdens, failure exposure, and voice across people who build, use, fund, review, and experience the system.",
    objective: "Produce a stakeholder map and impact assessment that includes people with little power over the deployment.",
    artifact: "Stakeholder and impact map",
    sections: [
      { heading: "Map power as well as contact", paragraphs: ["Direct users are only one group. Include data subjects, people classified by outputs, frontline staff, appeal reviewers, maintainers, communities, and those excluded by access or language. Record who receives benefits, who absorbs errors, and who can change the design."], sourceIds: ["algorithmic-impact-assessment"], evidenceMode: "source-grounded" },
      { heading: "Describe impact pathways", paragraphs: ["Connect system events to plausible effects: an input is missing, confidence is overstated, a staff member defers, an output propagates, and a person loses an opportunity. Separate evidence from assumptions and invite affected expertise before the design is frozen."], sourceIds: ["nist-ai-rmf"], evidenceMode: "instructional-synthesis" },
      { heading: "Turn consultation into decisions", paragraphs: ["Record what was heard, what changed, what did not change, who decided, and why. Consultation without a response path is not meaningful participation."], sourceIds: ["algorithmic-impact-assessment"], evidenceMode: "instructional-synthesis" },
    ],
    practice: { title: "Run an impact workshop", brief: "Map one normal, edge, and failure journey from each low-power stakeholder's perspective.", steps: ["List stakeholders and their decision power.", "Trace benefits and harms through the full workflow.", "Assign mitigations, owners, evidence, and follow-up dates."], deliverable: "Stakeholder map and impact assessment.", reviewGate: "At least one affected group without deployment authority has a documented concern and response." },
    checkpoint: { question: "Which stakeholder is easiest to omit but essential to an impact assessment?", options: ["A person affected by an output who never operates the system", "The vendor's sales lead only", "Only the engineer who trained the model", "Only the procurement owner"], correctIndex: 0, explanation: "People can bear system consequences without ever touching the interface or choosing the deployment." },
    takeaway: "Impact follows the whole sociotechnical workflow, not merely the model boundary.",
  },
  "data-rights-privacy-minimisation": {
    title: "Data rights, privacy and minimisation",
    summary: "Make every data element justify its collection, access, retention, transformation, and deletion path.",
    objective: "Build a data map that connects purpose, lawful or authorised basis, access, retention, provenance, and downstream use.",
    artifact: "Data map and minimisation decision log",
    sections: [
      { heading: "Follow data through the system", paragraphs: ["Inventory source, fields, sensitivity, data subjects, collection context, transformations, recipients, storage locations, retention, and deletion. Training, retrieval, prompts, logs, feedback, and evaluation datasets are separate flows with separate risks."], sourceIds: ["nist-privacy-framework"], evidenceMode: "source-grounded" },
      { heading: "Minimise by design", paragraphs: ["For every field ask whether the purpose can be met without it, with a less precise value, for a shorter period, or in a controlled local environment. Removing unnecessary data reduces exposure more reliably than promising careful handling later."], sourceIds: ["oecd-privacy"], evidenceMode: "source-grounded" },
      { heading: "Preserve rights and provenance", paragraphs: ["Record consent or other authority without assuming one basis applies everywhere. Define correction, access, deletion, withdrawal, and provenance procedures appropriate to the context. A technical data map is not jurisdiction-specific legal advice."], sourceIds: ["oecd-privacy"], evidenceMode: "version-watch" },
    ],
    practice: { title: "Minimise a data flow", brief: "Challenge every field and every retained copy in a proposed pipeline.", steps: ["Draw collection, transformation, access, logging, and deletion.", "Mark sensitive and derived data.", "Remove or reduce at least one unjustified element and document the trade-off."], deliverable: "Versioned data map with retention and rights actions.", reviewGate: "No field remains merely because it might be useful later." },
    checkpoint: { question: "What is the strongest privacy control for an input not needed by the declared purpose?", options: ["Do not collect or retain it", "Encrypt it and keep it indefinitely", "Hide it from the user interface", "Add it to a broad consent form"], correctIndex: 0, explanation: "Security controls help protect retained data, but minimisation removes an unnecessary exposure altogether." },
    takeaway: "The safest unnecessary data field is the one the system never receives.",
  },
  "fairness-subgroup-audit": {
    title: "Fairness and subgroup audit",
    summary: "Inspect who receives errors and benefits without pretending one metric settles a normative choice.",
    objective: "Design a subgroup audit with justified groups, uncertainty, sample adequacy, intersectional checks, and an action rule.",
    artifact: "Subgroup test and decision memo",
    sections: [
      { heading: "Start from the harm", paragraphs: ["Choose metrics after identifying the decision and harm. False negatives, false positives, ranking position, calibration, access, and service quality can matter differently. A fairness metric is a lens on a declared concern, not a universal certificate."], sourceIds: ["fairlearn-user-guide"], evidenceMode: "source-grounded" },
      { heading: "Audit slices responsibly", paragraphs: ["Predefine relevant groups where possible, report denominators and uncertainty, examine intersections, and avoid exposing identities in small cells. Missing or noisy group labels can hide harm as easily as they can create spurious differences."], sourceIds: ["gender-shades"], evidenceMode: "source-grounded" },
      { heading: "Connect findings to authority", paragraphs: ["Specify what gap triggers investigation, redesign, restricted use, monitoring, or no deployment. Aggregate performance must never erase a material subgroup failure."], sourceIds: ["fairlearn-user-guide"], evidenceMode: "instructional-synthesis" },
    ],
    practice: { title: "Build the subgroup audit", brief: "Create a table that makes denominators, uncertainty, gaps, and decisions visible.", steps: ["Define the harm and metric for each relevant slice.", "Calculate or plan confidence intervals and small-cell handling.", "Write the action attached to each threshold."], deliverable: "Subgroup audit table and mitigation decision.", reviewGate: "The conclusion cannot be reconstructed from overall accuracy alone." },
    checkpoint: { question: "A model has strong overall accuracy but a severe false-negative rate for one affected subgroup. What is the responsible conclusion?", options: ["Treat the subgroup failure as a release issue and investigate or restrict the use", "Average the result into the overall score", "Remove the subgroup column from reporting", "Assume a larger model will resolve it"], correctIndex: 0, explanation: "A material distributional failure is not cancelled by aggregate performance." },
    takeaway: "Fairness evidence must change a decision; otherwise it is decorative reporting.",
  },
  "explainability-uncertainty-limitations": {
    title: "Explainability, uncertainty and limitations",
    summary: "Give each decision-maker the explanation and uncertainty needed for their next action.",
    objective: "Write an explanation and limitations card matched to users, reviewers, affected people, and operators.",
    artifact: "Explanation and limitations card",
    sections: [
      { heading: "Explain for a decision", paragraphs: ["A developer debugging a pipeline, a reviewer checking a case, and a person contesting an outcome need different evidence. Define the audience, question, available action, and known limitations before choosing an explanation method."], sourceIds: ["nist-ai-rmf"], evidenceMode: "source-grounded" },
      { heading: "Represent uncertainty honestly", paragraphs: ["Scores are not automatically calibrated probabilities. Show validation context, uncertainty intervals where appropriate, out-of-distribution conditions, missing-data effects, and cases where the system should abstain."], sourceIds: ["uncertainty-calibration"], evidenceMode: "source-grounded" },
      { heading: "Test usefulness, not attractiveness", paragraphs: ["Check whether intended readers can identify the reason, limitation, alternative, and next step. A polished feature-importance chart can still be misleading or unusable at the decision point."], sourceIds: ["nist-ai-rmf"], evidenceMode: "instructional-synthesis" },
    ],
    practice: { title: "Write for three audiences", brief: "Explain one output to an operator, affected person, and technical reviewer.", steps: ["State what the system can and cannot infer.", "Show uncertainty and abstention conditions.", "Give each audience a concrete next action or contest path."], deliverable: "Multi-audience explanation and limitations card.", reviewGate: "A reader can act safely without interpreting the explanation as proof of causality." },
    checkpoint: { question: "When is an explanation adequate?", options: ["When the intended reader can understand the relevant reason, limitation, uncertainty, and next action", "When it contains the most technical detail possible", "When it makes every model look deterministic", "When it replaces an appeal process"], correctIndex: 0, explanation: "Explanation quality is audience- and decision-dependent and never substitutes for recourse." },
    takeaway: "An explanation earns its place only when it supports a safer, reviewable decision.",
  },
  "model-data-system-cards": {
    title: "Model, data and system cards",
    summary: "Document the model as one component inside a versioned data and operational system.",
    objective: "Create linked cards that expose intended use, provenance, evaluation, limitations, owners, dependencies, and change history.",
    artifact: "Linked model, data, and system assurance card",
    sections: [
      { heading: "Separate the records", paragraphs: ["A model card reports model purpose, evaluation, and limitations. A datasheet records dataset motivation, composition, collection, processing, uses, and maintenance. This course's original system assurance card connects components, safeguards, evaluations, deployment context, and residual risks without claiming to be a universal standard."], sourceIds: ["model-cards", "datasheets", "nist-genai-profile"], evidenceMode: "source-grounded" },
      { heading: "Bind claims to versions", paragraphs: ["Record model, data, prompt, retrieval corpus, code, policy, and evaluation versions. A card without a release identifier becomes stale prose that cannot explain a production outcome."], sourceIds: ["model-cards"], evidenceMode: "instructional-synthesis" },
      { heading: "Write for handoff and challenge", paragraphs: ["Name owners, unresolved risks, excluded uses, monitoring, and update triggers. Link evidence rather than copying long claims, and distinguish observed results from intended safeguards."], sourceIds: ["nist-genai-profile"], evidenceMode: "instructional-synthesis" },
    ],
    practice: { title: "Build the assurance chain", brief: "Link one dataset, model, and application release through stable identifiers.", steps: ["Record purpose and provenance for each layer.", "Bind evaluation results to exact versions.", "List limitations, owners, monitoring, and update triggers."], deliverable: "Cross-linked assurance card set.", reviewGate: "A reviewer can identify which record must change when data, model, prompt, or policy changes." },
    checkpoint: { question: "Why is a model card alone insufficient for an AI application release?", options: ["The deployed system also depends on data, prompts, retrieval, code, policy, users, and operating context", "Model cards are only for images", "System behaviour never depends on deployment context", "A model card automatically records incidents"], correctIndex: 0, explanation: "Application risk emerges from the whole sociotechnical system and its versions." },
    takeaway: "Documentation is an executable handoff contract when versions, evidence, and owners are bound together.",
  },
  "human-authority-oversight-boundaries": {
    title: "Human authority and oversight boundaries",
    summary: "Design real human control: information, competence, time, authority, and a safe action path.",
    objective: "Specify approval-before-effect, override, stop, escalation, workload, and responsibility boundaries.",
    artifact: "Human authority and override flow",
    sections: [
      { heading: "Authority is more than presence", paragraphs: ["A person watching an automated process is not meaningful oversight if they cannot understand the signal, inspect evidence, pause action, change the outcome, or obtain support. Name the human role and the exact decisions reserved to it."], sourceIds: ["eu-hleg-ethics-guidelines-2019-historical", "eu-ai-act-2024"], evidenceMode: "source-grounded" },
      { heading: "Put approval before consequence", paragraphs: ["Consequential actions should stop at a visible approval boundary with relevant context, uncertainty, alternatives, and the effect of approval. Logging an action for later review is not equivalent to authorising it before harm."], sourceIds: ["nist-ai-rmf"], evidenceMode: "instructional-synthesis" },
      { heading: "Engineer for workload and failure", paragraphs: ["Test alert volume, automation bias, fatigue, unavailable reviewers, conflicts of interest, and emergency stop. Assign final responsibility explicitly; the model, vendor, or interface cannot be the accountable owner."], sourceIds: ["eu-hleg-ethics-guidelines-2019-historical"], evidenceMode: "instructional-synthesis" },
    ],
    practice: { title: "Draw the authority map", brief: "Map proposal, review, approval, execution, override, stop, and accountability.", steps: ["Mark every state-changing action.", "Put named approval gates before consequential effects.", "Test absence, overload, disagreement, and emergency stop scenarios."], deliverable: "Authority, override, and stopping flow.", reviewGate: "Every consequential branch ends with a named accountable human role and a feasible action." },
    checkpoint: { question: "Which design demonstrates meaningful human oversight?", options: ["A trained reviewer receives relevant evidence before effect and can deny, override, stop, and escalate", "A person receives a monthly log after all actions", "The interface shows a confidence score but has no stop control", "The vendor accepts responsibility for every local decision"], correctIndex: 0, explanation: "Oversight requires timely information, competence, authority, and an effective control path." },
    takeaway: "Capability can be delegated; accountability and consequential authority must remain explicit.",
  },
  "escalation-appeal-contestability": {
    title: "Escalation, appeal and contestability",
    summary: "Give people a visible route to challenge, correct, and reverse an AI-influenced outcome.",
    objective: "Design escalation and appeal flows with notice, access, independent review, remedy, time limits, and evidence preservation.",
    artifact: "Escalation and appeal flow",
    sections: [
      { heading: "Make the decision visible", paragraphs: ["People cannot contest a process they do not know exists. State when AI materially influenced an outcome, what information can be inspected, how to correct data, and how to reach a human reviewer."], sourceIds: ["unesco-ai-ethics"], evidenceMode: "source-grounded" },
      { heading: "Separate escalation from appeal", paragraphs: ["Escalation moves an unresolved case to a more capable or authorised role during operation. Appeal challenges an outcome after or around the decision. Both need service levels, evidence, ownership, and a remedy path."], sourceIds: ["algorithmic-impact-assessment"], evidenceMode: "instructional-synthesis" },
      { heading: "Protect the record", paragraphs: ["Preserve relevant inputs, model and policy versions, human actions, reasons, and changes without over-retaining personal data. An independent reviewer should be able to reconstruct the decision and reverse it when warranted."], sourceIds: ["unesco-ai-ethics"], evidenceMode: "instructional-synthesis" },
    ],
    practice: { title: "Prototype the contest path", brief: "Walk one affected person from notice to correction, review, decision, and remedy.", steps: ["Write the notice in plain language.", "Define evidence access and correction steps.", "Name reviewer independence, time limit, remedy, and audit record."], deliverable: "Accessible escalation and appeal flow.", reviewGate: "The route works for a person who cannot use the original digital channel." },
    checkpoint: { question: "What makes an appeal process contestable rather than symbolic?", options: ["A visible route, relevant evidence, independent human review, correction, reasoned decision, and remedy", "A generic support mailbox with no deadline", "A model-generated explanation that cannot change the outcome", "A waiver accepted before use"], correctIndex: 0, explanation: "Contestability requires a practical route capable of correcting or reversing the decision." },
    takeaway: "If challenge cannot change the outcome, it is feedback—not recourse.",
  },
  "red-teaming-incidents-disclosure": {
    title: "Red teaming, incidents and disclosure",
    summary: "Test plausible misuse and failure, then preserve evidence for containment, learning, and proportionate disclosure.",
    objective: "Run threat- and impact-informed tests and connect findings to incident severity, response, communication, and regression controls.",
    artifact: "Red-team and incident log",
    sections: [
      { heading: "Test the system people will use", paragraphs: ["Probe abuse, prompt injection, data leakage, unsafe automation, subgroup harms, overreliance, distribution shift, and control bypass in the full workflow. A model-only jailbreak score cannot represent application permissions or human procedures."], sourceIds: ["nist-genai-profile"], evidenceMode: "source-grounded" },
      { heading: "Record failures without theatre", paragraphs: ["Each finding needs a reproducible scenario, expected control, observed result, severity rationale, evidence, owner, fix, retest, and residual risk. Do not inflate a creative prompt list into proof of comprehensive safety."], sourceIds: ["nist-genai-profile"], evidenceMode: "instructional-synthesis" },
      { heading: "Prepare the incident path", paragraphs: ["Define detection, triage, containment, rollback or disablement, notification, preservation, disclosure, and postmortem. Incident examples can suggest tests, but they do not establish the prevalence of a failure in your system."], sourceIds: ["nist-incident-response-r3"], evidenceMode: "source-grounded" },
    ],
    practice: { title: "Run a bounded red-team exercise", brief: "Test three realistic misuse or failure scenarios against declared controls.", steps: ["Choose scenarios from the threat and impact assessment.", "Capture reproducible evidence and severity.", "Assign containment, fix, retest, disclosure, and regression checks."], deliverable: "Red-team finding log and incident drill record.", reviewGate: "At least one test reaches the human stop or rollback path rather than ending at detection." },
    checkpoint: { question: "What is the most useful red-team output?", options: ["A reproducible finding tied to an expected control, severity, owner, fix, retest, and residual risk", "The largest possible list of imaginative prompts", "A statement that no issue was found", "A model-only score with no application context"], correctIndex: 0, explanation: "Actionable evidence connects a realistic failure to control performance and a closed learning loop." },
    takeaway: "Red teaming becomes governance only when findings change controls and survive into regression testing.",
  },
  "governance-dossier-capstone": {
    title: "Governance dossier capstone",
    summary: "Assemble the evidence, authority, recourse, and incident contracts into one release decision.",
    objective: "Produce nine cross-linked artifacts and defend a go, conditional-go, or no-go decision without hiding uncertainty.",
    artifact: "Complete governance dossier and decision memo",
    sections: [
      { heading: "Build one evidence graph", paragraphs: ["Risk IDs should connect purpose, stakeholders, data, subgroup tests, limitations, authority, appeals, red-team findings, mitigations, and monitoring. Resolve contradictions or carry them visibly into the decision memo."], sourceIds: ["nist-ai-rmf"], evidenceMode: "instructional-synthesis" },
      { heading: "Decide under uncertainty", paragraphs: ["A conditional go names the exact condition, evidence required, responsible verifier, deadline, restricted scope, and rollback trigger. A no-go is a valid engineering result when risks cannot be reduced or authority cannot be made legitimate."], sourceIds: ["oecd-ai-principles"], evidenceMode: "instructional-synthesis" },
      { heading: "Review the reviewers", paragraphs: ["Check conflicts, stakeholder representation, technical competence, legal or policy expertise where applicable, and who can reopen the decision after a change or incident. The dossier supports accountable judgment; it does not certify the system."], sourceIds: ["nist-ai-rmf"], evidenceMode: "version-watch" },
    ],
    practice: { title: "Run the release panel", brief: "Present the dossier to reviewers who own technical, operational, affected-person, and decision perspectives.", steps: ["Verify all nine artifacts and cross-links.", "Record objections, missing evidence, and conflicts.", "Issue the decision with conditions, monitoring, stop, appeal, and review date."], deliverable: "Signed decision record and versioned governance dossier.", reviewGate: "A reviewer can identify what evidence would force the decision to change." },
    checkpoint: { question: "When should the capstone result be no-deploy?", options: ["When a material risk, authority gap, rights issue, or evidence gap cannot be reduced within the bounded use", "Only when model accuracy is below 50 percent", "Never, because the course requires a launch", "Whenever a reviewer asks a difficult question"], correctIndex: 0, explanation: "A responsible release process must be able to stop when required controls or evidence are absent." },
    takeaway: "The dossier is complete only when it can support—and survive—a reasoned decision not to deploy.",
  },
} as const;
