import type { RagFigureId, RagFigureManifest } from "./types";

const difyCommit = "bca060d6b2d741071394605cadae46badb9911c5";
const claudeQuickstartsCommit = "5264b729deda905dba3e5402d717bebed000325c";

export const RAG_FIGURES = [
  {
    id: "rag-decision-map",
    format: "semantic-html",
    status: "available",
    sourceId: null,
    authenticUi: false,
    product: null,
    rightsStatus: "course-original",
    raster: null,
  },
  {
    id: "dify-rag-workflow",
    format: "authentic-ui-screenshot",
    status: "available",
    sourceId: "dify-docs",
    authenticUi: true,
    product: "Dify",
    rightsStatus: "licensed-local-figure",
    raster: {
      pngPath: "/courses/rag/figures/dify-rag-workflow-ui.png",
      webpPath: "/courses/rag/figures/dify-rag-workflow-ui.webp",
      width: 2022,
      height: 580,
      pngSha256: "3ba484c0884aa3c91024d8aaec177b237dda7a4840489d5055270931bdc5b17f",
      webpSha256: "2de71da3040cb166c5fe0d3f94f39d739a78e9f8dac838515a5360c2373fe64e",
      upstreamUrl: `https://raw.githubusercontent.com/langgenius/dify-docs/${difyCommit}/images/use-dify/workflow/knowledge-retrieval-node-example.png`,
      upstreamCommit: difyCommit,
      observedOn: "2026-08-23",
      privacyReview: "no-personal-data-visible",
    },
  },
  {
    id: "corpus-control-plane",
    format: "semantic-html",
    status: "available",
    sourceId: null,
    authenticUi: false,
    product: null,
    rightsStatus: "course-original",
    raster: null,
  },
  {
    id: "dify-chunk-settings",
    format: "authentic-ui-screenshot",
    status: "available",
    sourceId: "dify-docs",
    authenticUi: true,
    product: "Dify",
    rightsStatus: "licensed-local-figure",
    raster: {
      pngPath: "/courses/rag/figures/dify-chunk-settings-ui.png",
      webpPath: "/courses/rag/figures/dify-chunk-settings-ui.webp",
      width: 846,
      height: 913,
      pngSha256: "3aa56fb2498d3a34bc44a34fb71026790a77dfc95aae3570642cd677740745ce",
      webpSha256: "702d39414250c5f677f00739aa5d39e048ac95cf9ecef7d96fd51a51a14a62dd",
      upstreamUrl: `https://raw.githubusercontent.com/langgenius/dify-docs/${difyCommit}/images/use-dify/tutorial/workflow-101-lesson-04/document-processing.png`,
      upstreamCommit: difyCommit,
      observedOn: "2026-08-23",
      privacyReview: "no-personal-data-visible",
    },
  },
  {
    id: "dify-chunk-inspector",
    format: "authentic-ui-screenshot",
    status: "available",
    sourceId: "dify-docs",
    authenticUi: true,
    product: "Dify",
    rightsStatus: "licensed-local-figure",
    raster: {
      pngPath: "/courses/rag/figures/dify-chunk-inspector-ui.png",
      webpPath: "/courses/rag/figures/dify-chunk-inspector-ui.webp",
      width: 3398,
      height: 1320,
      pngSha256: "3316fd15465f037cf00ec76d5cfd6e2e85236ec770af48b7d0a1854bdfe689b3",
      webpSha256: "1e8fe1aec6fb6a7e8ad035d8f8c07d1c046092389b367e8a17fbe0bc3065d980",
      upstreamUrl: `https://raw.githubusercontent.com/langgenius/dify-docs/${difyCommit}/images/use-dify/knowledge/manage-document-chunks.png`,
      upstreamCommit: difyCommit,
      observedOn: "2026-08-23",
      privacyReview: "no-personal-data-visible",
    },
  },
  {
    id: "retrieval-scoreboard",
    format: "semantic-html",
    status: "available",
    sourceId: null,
    authenticUi: false,
    product: null,
    rightsStatus: "course-original",
    raster: null,
  },
  {
    id: "context-budget",
    format: "semantic-html",
    status: "available",
    sourceId: null,
    authenticUi: false,
    product: null,
    rightsStatus: "course-original",
    raster: null,
  },
  {
    id: "claude-support-rag-ui",
    format: "authentic-ui-screenshot",
    status: "available",
    sourceId: "anthropic-quickstarts",
    authenticUi: true,
    product: "Claude-powered Anthropic quickstart",
    rightsStatus: "licensed-local-figure",
    raster: {
      pngPath: "/courses/rag/figures/claude-support-rag-ui.png",
      webpPath: "/courses/rag/figures/claude-support-rag-ui.webp",
      width: 3272,
      height: 2212,
      pngSha256: "44e23e51f1665c4a99da1ac05f2692247e0030df9e33c27bcc9c91cda517822c",
      webpSha256: "d3c794a984d49dc68953c4923bb610a95f0bbbb10ee623927abb638c4821882f",
      upstreamUrl: `https://raw.githubusercontent.com/anthropics/claude-quickstarts/${claudeQuickstartsCommit}/customer-support-agent/tutorial/preview.png`,
      upstreamCommit: claudeQuickstartsCommit,
      observedOn: "2026-08-23",
      privacyReview: "no-personal-data-visible",
    },
  },
  {
    id: "anthropic-knowledge-wiki-architecture",
    format: "official-teaching-diagram",
    status: "available",
    sourceId: "anthropic-quickstarts",
    authenticUi: false,
    product: "Anthropic knowledge-wiki architecture",
    rightsStatus: "licensed-local-figure",
    raster: null,
    vector: {
      svgPath: "/courses/rag/figures/anthropic-knowledge-wiki-architecture.svg",
      width: 960,
      height: 700,
      svgSha256: "947a005c4690087aed08f92a1681e95c2e6de7909e1edc7a75e085fa5d00131f",
      upstreamUrl: `https://raw.githubusercontent.com/anthropics/claude-quickstarts/${claudeQuickstartsCommit}/managed-agents/knowledge-wiki/assets/architecture.svg`,
      upstreamCommit: claudeQuickstartsCommit,
      observedOn: "2026-08-24",
      privacyReview: "no-personal-data-visible",
    },
  },
  {
    id: "evaluation-stack",
    format: "semantic-html",
    status: "available",
    sourceId: null,
    authenticUi: false,
    product: null,
    rightsStatus: "course-original",
    raster: null,
  },
  {
    id: "threat-boundary",
    format: "semantic-html",
    status: "available",
    sourceId: null,
    authenticUi: false,
    product: null,
    rightsStatus: "course-original",
    raster: null,
  },
  {
    id: "dify-citations-ui",
    format: "authentic-ui-screenshot",
    status: "available",
    sourceId: "dify-docs",
    authenticUi: true,
    product: "Dify",
    rightsStatus: "licensed-local-figure",
    raster: {
      pngPath: "/courses/rag/figures/dify-citations-ui.png",
      webpPath: "/courses/rag/figures/dify-citations-ui.webp",
      width: 1578,
      height: 904,
      pngSha256: "88e33f0ac6573c2a380924a6c9cef419f52f752ec3db14bd137cb90152c55d50",
      webpSha256: "e9928c4819c90728aef178b22c477499c7ad0ecb00a3aae8573f086b27d8ced1",
      upstreamUrl: `https://raw.githubusercontent.com/langgenius/dify-docs/${difyCommit}/images/use-dify/workflow/citations-and-attributions.png`,
      upstreamCommit: difyCommit,
      observedOn: "2026-08-23",
      privacyReview: "no-personal-data-visible",
    },
  },
] as const satisfies readonly RagFigureManifest[];

export const RAG_FIGURE_BY_ID = Object.freeze(Object.fromEntries(
  RAG_FIGURES.map((figure) => [figure.id, figure]),
)) as Readonly<Record<RagFigureId, RagFigureManifest>>;
