import {
  RAG_COURSE_ID,
  RAG_SOURCE_SNAPSHOT_ON,
  type RagCourseManifest,
  type RagLessonManifest,
  type RagUnitManifest,
} from "./types";

export const RAG_UNITS = [
  {
    id: "frame",
    order: 1,
    lessonSlugs: ["choose-rag", "trace-the-pipeline", "corpus-contract"],
  },
  {
    id: "index",
    order: 2,
    lessonSlugs: ["parse-and-chunk", "embeddings-and-indexes", "retrieval-engineering"],
  },
  {
    id: "answer",
    order: 3,
    lessonSlugs: ["rerank-and-assemble", "ground-and-cite", "advanced-patterns"],
  },
  {
    id: "operate",
    order: 4,
    lessonSlugs: ["evaluate-rag", "secure-and-refresh", "production-capstone"],
  },
] as const satisfies readonly RagUnitManifest[];

export const RAG_LESSONS = [
  {
    slug: "choose-rag",
    order: 1,
    unitId: "frame",
    minutes: 45,
    figureId: "rag-decision-map",
    conceptIds: [
      "rag-definition",
      "selection-boundary",
      "long-context",
      "fine-tuning",
      "search-tools-sql",
    ],
    sourceIds: [
      "anthropic-academy-api",
      "anthropic-academy-vertex",
      "openai-academy-rag-bootcamp",
      "google-skills-boost-rag",
      "anthropic-contextual-retrieval",
      "google-rag-engine-overview",
      "lewis-rag-paper",
    ],
  },
  {
    slug: "trace-the-pipeline",
    order: 2,
    unitId: "frame",
    minutes: 50,
    figureId: "dify-rag-workflow",
    conceptIds: ["rag-definition", "observability", "production-reliability"],
    sourceIds: [
      "google-rag-engine-overview",
      "openai-retrieval-guide",
      "langchain-rag-from-scratch",
      "dify-docs",
    ],
  },
  {
    slug: "corpus-contract",
    order: 3,
    unitId: "frame",
    minutes: 55,
    figureId: "corpus-control-plane",
    conceptIds: [
      "source-authority",
      "permissions-provenance",
      "metadata-versioning",
      "privacy-tenancy",
      "freshness-deletion",
    ],
    sourceIds: [
      "google-rag-reference-architecture",
      "openai-knowledge-retrieval",
      "openai-data-controls",
      "owasp-rag-security",
      "azure-search-rag-demo",
      "user-report-paperqa-vendor-leak",
    ],
  },
  {
    slug: "parse-and-chunk",
    order: 4,
    unitId: "index",
    minutes: 65,
    figureId: "dify-chunk-settings",
    conceptIds: ["parsing-ocr-layout", "chunking", "metadata-versioning"],
    sourceIds: [
      "google-parse-chunk",
      "openai-retrieval-guide",
      "anthropic-contextual-retrieval",
      "dify-docs",
      "ragflow",
      "user-report-ragflow-reading-order",
    ],
  },
  {
    slug: "embeddings-and-indexes",
    order: 5,
    unitId: "index",
    minutes: 60,
    figureId: "dify-chunk-inspector",
    conceptIds: ["embeddings", "vector-index", "dense-retrieval", "metadata-versioning"],
    sourceIds: [
      "anthropic-academy-api",
      "google-rag-engine-overview",
      "openai-retrieval-guide",
      "dify-docs",
    ],
  },
  {
    slug: "retrieval-engineering",
    order: 6,
    unitId: "index",
    minutes: 75,
    figureId: "retrieval-scoreboard",
    conceptIds: [
      "dense-retrieval",
      "sparse-retrieval",
      "hybrid-fusion",
      "query-transformation",
      "filters-acl",
      "domain-contexts",
    ],
    sourceIds: [
      "anthropic-academy-api",
      "anthropic-contextual-retrieval",
      "google-hybrid-search",
      "openai-retrieval-guide",
      "openai-file-search-guide",
      "openai-knowledge-retrieval",
      "azure-search-rag-demo",
      "sourcegraph-cody-context",
      "user-report-sourcegraph-no-context",
    ],
  },
  {
    slug: "rerank-and-assemble",
    order: 7,
    unitId: "answer",
    minutes: 60,
    figureId: "context-budget",
    conceptIds: ["reranking-diversity", "context-assembly", "cost-latency"],
    sourceIds: [
      "google-ranking",
      "anthropic-contextual-retrieval",
      "anthropic-context-engineering",
      "openai-retrieval-guide",
    ],
  },
  {
    slug: "ground-and-cite",
    order: 8,
    unitId: "answer",
    minutes: 65,
    figureId: "claude-support-rag-ui",
    conceptIds: [
      "grounding-abstention",
      "citations",
      "answer-evaluation",
      "citation-evaluation",
    ],
    sourceIds: [
      "anthropic-citations",
      "anthropic-projects-rag-help",
      "anthropic-quickstarts",
      "google-check-grounding",
      "openai-file-search-guide",
      "user-report-azure-missing-citations",
    ],
  },
  {
    slug: "advanced-patterns",
    order: 9,
    unitId: "answer",
    minutes: 65,
    figureId: "anthropic-knowledge-wiki-architecture",
    conceptIds: ["agentic-multihop", "multimodal-rag", "graph-rag", "domain-contexts"],
    sourceIds: [
      "openai-academy-graphrag",
      "openai-multimodal-rag",
      "anthropic-quickstarts",
      "self-rag-paper",
      "microsoft-graphrag",
      "paperqa",
      "sourcegraph-cody-context",
      "privategpt",
    ],
  },
  {
    slug: "evaluate-rag",
    order: 10,
    unitId: "operate",
    minutes: 75,
    figureId: "evaluation-stack",
    conceptIds: [
      "retrieval-evaluation",
      "answer-evaluation",
      "citation-evaluation",
      "observability",
    ],
    sourceIds: [
      "openai-evaluation-guide",
      "openai-knowledge-retrieval",
      "google-check-grounding",
      "azure-search-rag-demo",
      "user-report-privategpt-wrong-answer",
      "user-report-azure-missing-citations",
    ],
  },
  {
    slug: "secure-and-refresh",
    order: 11,
    unitId: "operate",
    minutes: 70,
    figureId: "threat-boundary",
    conceptIds: [
      "filters-acl",
      "prompt-injection-poisoning",
      "privacy-tenancy",
      "freshness-deletion",
      "production-reliability",
    ],
    sourceIds: [
      "owasp-rag-security",
      "anthropic-prompt-injection-defences",
      "google-model-armor",
      "google-rag-reference-architecture",
      "openai-data-controls",
      "azure-search-rag-demo",
      "user-report-paperqa-vendor-leak",
    ],
  },
  {
    slug: "production-capstone",
    order: 12,
    unitId: "operate",
    minutes: 95,
    figureId: "dify-citations-ui",
    conceptIds: [
      "cost-latency",
      "production-reliability",
      "domain-contexts",
      "retrieval-evaluation",
      "answer-evaluation",
      "citation-evaluation",
      "observability",
    ],
    sourceIds: [
      "google-rag-reference-architecture",
      "openai-knowledge-retrieval",
      "azure-search-rag-demo",
      "paperqa",
      "privategpt",
      "dify-docs",
    ],
  },
] as const satisfies readonly RagLessonManifest[];

export const RAG_COURSE_MANIFEST = {
  id: RAG_COURSE_ID,
  version: "1.1.0",
  displayNumber: 9,
  publishedOn: "2026-08-24",
  sourceSnapshotOn: RAG_SOURCE_SNAPSHOT_ON,
  units: RAG_UNITS,
  lessons: RAG_LESSONS,
} as const satisfies RagCourseManifest;
