import {
  RAG_SOURCE_SNAPSHOT_ON,
  type RagSourceId,
  type RagSourceRecord,
} from "./types";

const accessedOn = RAG_SOURCE_SNAPSHOT_ON;

export const RAG_SOURCES = [
  {
    id: "anthropic-academy-api",
    evidenceLabel: "official-course",
    title: "Building with the Claude API",
    publisher: "Claude Academy",
    url: "https://academy.claude.com/courses/building-with-the-claude-api",
    exactAnchor: "https://academy.claude.com/courses/building-with-the-claude-api",
    accessedOn,
    licence: "site-terms",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Official curriculum source for the RAG flow, chunking, embeddings, BM25, implementation, and multi-index retrieval.",
    caveat: "Link and paraphrase only. Academy lesson pages, videos, quizzes, and screenshots are not republished.",
  },
  {
    id: "anthropic-academy-vertex",
    evidenceLabel: "official-course",
    title: "Claude with Google Cloud's Vertex AI",
    publisher: "Claude Academy",
    url: "https://academy.claude.com/courses/claude-with-google-cloud-s-vertex-ai",
    exactAnchor: "https://academy.claude.com/courses/claude-with-google-cloud-s-vertex-ai",
    accessedOn,
    licence: "site-terms",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Official course that joins Claude, Vertex AI, hybrid retrieval, reranking, and contextual retrieval.",
    caveat: "Course structure and product behaviour can change. No Academy media is copied into this course.",
  },
  {
    id: "anthropic-contextual-retrieval",
    evidenceLabel: "official-doc",
    title: "Introducing Contextual Retrieval",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/engineering/contextual-retrieval",
    exactAnchor: "https://www.anthropic.com/engineering/contextual-retrieval",
    accessedOn,
    licence: "site-terms",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Primary source for dense plus BM25 retrieval, rank fusion, contextual chunks, reranking, and evaluation.",
    caveat: "Anthropic's reported improvements describe its experiments and are not universal performance guarantees.",
  },
  {
    id: "anthropic-context-engineering",
    evidenceLabel: "official-doc",
    title: "Effective context engineering for AI agents",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents",
    exactAnchor: "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents",
    accessedOn,
    licence: "site-terms",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Supports finite context budgets, selection, ordering, and the difference between retrieval and useful context.",
    caveat: "Advice is model and workflow dependent and must be evaluated against the course task set.",
  },
  {
    id: "anthropic-prompt-injection-defences",
    evidenceLabel: "official-doc",
    title: "Mitigating the risk of prompt injections in browser use",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/research/prompt-injection-defenses",
    exactAnchor: "https://www.anthropic.com/research/prompt-injection-defenses",
    accessedOn,
    licence: "site-terms",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Browser-agent-specific Anthropic research on indirect prompt injection from untrusted pages and documents and on layered defenses.",
    caveat: "This is browser-agent-specific evidence. General RAG controls come from OWASP guidance and deployment testing; no defense is treated as complete.",
  },
  {
    id: "anthropic-citations",
    evidenceLabel: "official-doc",
    title: "Citations",
    publisher: "Anthropic",
    url: "https://platform.claude.com/docs/en/build-with-claude/citations",
    exactAnchor: "https://platform.claude.com/docs/en/build-with-claude/citations",
    accessedOn,
    licence: "site-terms",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Current Claude API reference for document citations and source position metadata.",
    caveat: "A rendered citation is not proof that the cited span supports the claim.",
  },
  {
    id: "anthropic-projects-rag-help",
    evidenceLabel: "official-doc",
    title: "Retrieval augmented generation for Projects",
    publisher: "Anthropic Help Center",
    url: "https://support.claude.com/en/articles/11473015-retrieval-augmented-generation-rag-for-projects",
    exactAnchor: "https://support.claude.com/en/articles/11473015-retrieval-augmented-generation-rag-for-projects",
    accessedOn,
    licence: "site-terms",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Current product help for how Claude Projects can retrieve from Project Knowledge.",
    caveat: "UI, plan access, limits, and activation behaviour are time sensitive and are date stamped here.",
  },
  {
    id: "anthropic-quickstarts",
    evidenceLabel: "official-repository",
    title: "Claude RAG and knowledge-wiki quickstarts",
    publisher: "Anthropic",
    url: "https://github.com/anthropics/claude-quickstarts",
    exactAnchor: "https://github.com/anthropics/claude-quickstarts/tree/5264b729deda905dba3e5402d717bebed000325c",
    accessedOn,
    licence: "MIT",
    licenceUrl: "https://github.com/anthropics/claude-quickstarts/blob/5264b729deda905dba3e5402d717bebed000325c/LICENSE",
    reuse: "licensed-local-figure",
    note: "Anthropic-maintained Claude-powered RAG interface with visible application activity status, plus an official knowledge-wiki architecture diagram with versioned memory and fact-level provenance.",
    caveat: "The interface is an MIT-licensed reference application, not the consumer Claude.ai interface. The architecture asset is a teaching diagram, not product UI or a production guarantee.",
    commit: "5264b729deda905dba3e5402d717bebed000325c",
  },
  {
    id: "openai-academy-rag-bootcamp",
    evidenceLabel: "official-event",
    title: "Builder Bootcamp: RAG",
    publisher: "OpenAI Academy",
    url: "https://academy.openai.com/public/clubs/builders-etkn1/events/builder-bootcamp-rag-b3yo6kdfwv",
    exactAnchor: "https://academy.openai.com/public/clubs/builders-etkn1/events/builder-bootcamp-rag-b3yo6kdfwv",
    accessedOn,
    licence: "site-terms",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Official Academy event linking File Search, Responses, vector stores, grounded answers, tuning, and evaluation.",
    caveat: "This Academy event and livestream is linked and synthesised independently. The course does not export or rehost Academy material.",
  },
  {
    id: "openai-academy-graphrag",
    evidenceLabel: "official-video",
    title: "Automate Knowledge Graphs for RAG",
    publisher: "OpenAI Academy",
    url: "https://academy.openai.com/public/videos/automate-knowledge-graphs",
    exactAnchor: "https://academy.openai.com/public/videos/automate-knowledge-graphs",
    accessedOn,
    licence: "site-terms",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Official Academy-hosted video session on GraphRAG enrichment.",
    caveat: "This hosted session is not treated as the sole or canonical definition of GraphRAG.",
  },
  {
    id: "openai-retrieval-guide",
    evidenceLabel: "official-doc",
    title: "Retrieval guide",
    publisher: "OpenAI Developers",
    url: "https://developers.openai.com/api/docs/guides/retrieval",
    exactAnchor: "https://developers.openai.com/api/docs/guides/retrieval",
    accessedOn,
    licence: "site-terms",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Primary OpenAI source for vector stores, its current 800-token and 400-token-overlap managed default, search, query rewriting, ranking, and filters.",
    caveat: "Managed defaults are starting points, not universally optimal settings.",
  },
  {
    id: "openai-file-search-guide",
    evidenceLabel: "official-doc",
    title: "File Search",
    publisher: "OpenAI Developers",
    url: "https://developers.openai.com/api/docs/guides/tools-file-search",
    exactAnchor: "https://developers.openai.com/api/docs/guides/tools-file-search",
    accessedOn,
    licence: "site-terms",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Current source for managed file retrieval, attributes, result inclusion, and answer annotations.",
    caveat: "API names, response shapes, limits, and billing can change and should be rechecked before implementation.",
  },
  {
    id: "openai-evaluation-guide",
    evidenceLabel: "official-doc",
    title: "Evaluation best practices",
    publisher: "OpenAI Developers",
    url: "https://developers.openai.com/api/docs/guides/evaluation-best-practices",
    exactAnchor: "https://developers.openai.com/api/docs/guides/evaluation-best-practices",
    accessedOn,
    licence: "site-terms",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Primary source for representative eval sets, explicit rubrics, human calibration, and regression testing.",
    caveat: "Model judges must be validated against human decisions for the task. OpenAI says its hosted Evals platform becomes read-only on 2026-10-31 and is scheduled to shut down on 2026-11-30; verify current tooling before implementation.",
  },
  {
    id: "openai-data-controls",
    evidenceLabel: "official-doc",
    title: "Your data and API data controls",
    publisher: "OpenAI Developers",
    url: "https://developers.openai.com/api/docs/guides/your-data",
    exactAnchor: "https://developers.openai.com/api/docs/guides/your-data#default-usage-policies-by-endpoint",
    accessedOn,
    licence: "site-terms",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Time-sensitive source for application state, retention, deletion, and endpoint-specific controls.",
    caveat: "Policy varies by endpoint, account, agreement, region, and date. This course does not generalise it.",
  },
  {
    id: "openai-knowledge-retrieval",
    evidenceLabel: "official-repository",
    title: "OpenAI Knowledge Retrieval starter kit",
    publisher: "OpenAI",
    url: "https://github.com/openai/openai-knowledge-retrieval",
    exactAnchor: "https://github.com/openai/openai-knowledge-retrieval",
    accessedOn,
    licence: "MIT",
    licenceUrl: "https://github.com/openai/openai-knowledge-retrieval/blob/main/LICENSE",
    reuse: "link-and-synthesise",
    note: "End-to-end starter covering chunking, query expansion, HyDE, filters, reranking, citations, and evals.",
    caveat: "A starter kit is an implementation reference, not evidence of universal production readiness.",
  },
  {
    id: "openai-multimodal-rag",
    evidenceLabel: "official-repository",
    title: "Image understanding with RAG",
    publisher: "OpenAI Cookbook",
    url: "https://developers.openai.com/cookbook/examples/multimodal/image_understanding_with_rag",
    exactAnchor: "https://developers.openai.com/cookbook/examples/multimodal/image_understanding_with_rag",
    accessedOn,
    licence: "MIT",
    licenceUrl: "https://github.com/openai/openai-cookbook/blob/main/LICENSE",
    reuse: "link-and-synthesise",
    note: "Official example for retrieval and generation over images, text feedback, metadata, and evaluation.",
    caveat: "The example architecture does not prove one representation or embedding works for every modality.",
  },
  {
    id: "google-skills-boost-rag",
    evidenceLabel: "official-course",
    title: "Create Generative AI Apps on Google Cloud",
    publisher: "Google Skills",
    url: "https://www.skills.google/paths/1282/course_templates/1120",
    exactAnchor: "https://www.skills.google/paths/1282/course_templates/1120",
    accessedOn,
    licence: "site-terms",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Formal Google learning source for RAG, production architecture, and a cloud RAG application.",
    caveat: "Some hands-on labs can require credits. Course assets are not copied into this site.",
  },
  {
    id: "google-rag-engine-overview",
    evidenceLabel: "official-doc",
    title: "RAG Engine overview",
    publisher: "Google Cloud",
    url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/build/rag-engine/rag-overview",
    exactAnchor: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/build/rag-engine/rag-overview",
    accessedOn,
    licence: "CC-BY-4.0",
    licenceUrl: "https://developers.google.com/terms/site-policies",
    reuse: "link-and-synthesise",
    note: "Official managed-RAG overview for ingestion, transformation, embeddings, indexing, retrieval, and generation.",
    caveat: "Product-specific architecture is separated from provider-neutral concepts.",
  },
  {
    id: "google-rag-reference-architecture",
    evidenceLabel: "official-doc",
    title: "RAG reference architecture with Vertex AI",
    publisher: "Google Cloud Architecture Center",
    url: "https://docs.cloud.google.com/architecture/rag-genai-gemini-enterprise-vertexai",
    exactAnchor: "https://docs.cloud.google.com/architecture/rag-genai-gemini-enterprise-vertexai",
    accessedOn,
    licence: "CC-BY-4.0",
    licenceUrl: "https://developers.google.com/terms/site-policies",
    reuse: "link-and-synthesise",
    note: "Primary architecture source for separate ingestion and serving flows, security, metadata, and operations.",
    caveat: "Service choices are Google specific and do not define RAG universally.",
  },
  {
    id: "google-parse-chunk",
    evidenceLabel: "official-doc",
    title: "Parse and chunk documents",
    publisher: "Google Cloud",
    url: "https://docs.cloud.google.com/generative-ai-app-builder/docs/parse-chunk-documents",
    exactAnchor: "https://docs.cloud.google.com/generative-ai-app-builder/docs/parse-chunk-documents",
    accessedOn,
    licence: "CC-BY-4.0",
    licenceUrl: "https://developers.google.com/terms/site-policies",
    reuse: "link-and-synthesise",
    note: "Official source for digital parsing, OCR, layout-aware structure, content-aware chunks, and its current 500-token chunk-size limit default.",
    caveat: "Supported formats, defaults, and parser behaviour are product specific and time sensitive.",
  },
  {
    id: "google-hybrid-search",
    evidenceLabel: "official-doc",
    title: "Query a Vector Search index",
    publisher: "Google Cloud",
    url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/build/vector-search/query-index-public-endpoint",
    exactAnchor: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/build/vector-search/query-index-public-endpoint",
    accessedOn,
    licence: "CC-BY-4.0",
    licenceUrl: "https://developers.google.com/terms/site-policies",
    reuse: "link-and-synthesise",
    note: "Supports hybrid search, filters, and reciprocal-rank fusion examples.",
    caveat: "Sample fusion weights and thresholds are examples, not universal optima.",
  },
  {
    id: "google-ranking",
    evidenceLabel: "official-doc",
    title: "Rank and rerank documents",
    publisher: "Google Cloud",
    url: "https://docs.cloud.google.com/generative-ai-app-builder/docs/ranking",
    exactAnchor: "https://docs.cloud.google.com/generative-ai-app-builder/docs/ranking",
    accessedOn,
    licence: "CC-BY-4.0",
    licenceUrl: "https://developers.google.com/terms/site-policies",
    reuse: "link-and-synthesise",
    note: "Official source for separating candidate retrieval from more expensive relevance ranking.",
    caveat: "Reranking adds cost and latency and must be evaluated against a no-reranker baseline.",
  },
  {
    id: "google-check-grounding",
    evidenceLabel: "official-doc",
    title: "Check grounding",
    publisher: "Google Cloud",
    url: "https://docs.cloud.google.com/generative-ai-app-builder/docs/check-grounding",
    exactAnchor: "https://docs.cloud.google.com/generative-ai-app-builder/docs/check-grounding",
    accessedOn,
    licence: "CC-BY-4.0",
    licenceUrl: "https://developers.google.com/terms/site-policies",
    reuse: "link-and-synthesise",
    note: "Official source for overall and claim-level support scores with claim citations.",
    caveat: "A grounding score is a system output, not a guaranteed probability that a claim is true.",
  },
  {
    id: "google-model-armor",
    evidenceLabel: "official-doc",
    title: "Model Armor overview",
    publisher: "Google Cloud",
    url: "https://docs.cloud.google.com/model-armor/overview",
    exactAnchor: "https://docs.cloud.google.com/model-armor/overview",
    accessedOn,
    licence: "CC-BY-4.0",
    licenceUrl: "https://developers.google.com/terms/site-policies",
    reuse: "link-and-synthesise",
    note: "Current Google source for screening prompts, responses, and documents in generative AI pipelines.",
    caveat: "Screening is one layer and does not replace authorisation, provenance, least privilege, or adversarial tests.",
  },
  {
    id: "lewis-rag-paper",
    evidenceLabel: "research-paper",
    title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
    publisher: "NeurIPS 2020",
    url: "https://papers.nips.cc/paper/2020/hash/6b493230205f780e1bc26945df7481e5-Abstract.html",
    exactAnchor: "https://papers.nips.cc/paper/2020/hash/6b493230205f780e1bc26945df7481e5-Abstract.html",
    accessedOn,
    licence: "undeclared",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Foundational research source for combining parametric and retrieved non-parametric memory.",
    caveat: "The 2020 architecture is foundational history, not a complete production pattern for current systems.",
  },
  {
    id: "self-rag-paper",
    evidenceLabel: "research-paper",
    title: "Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection",
    publisher: "ICLR 2024",
    url: "https://openreview.net/forum?id=hSyW5go0v8",
    exactAnchor: "https://openreview.net/forum?id=hSyW5go0v8",
    accessedOn,
    licence: "undeclared",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Primary paper for the specifically trained Self-RAG architecture and its retrieval and reflection signals.",
    caveat: "Self-RAG is one research architecture, not a generic name for every workflow that retrieves iteratively.",
  },
  {
    id: "microsoft-graphrag",
    evidenceLabel: "official-repository",
    title: "GraphRAG",
    publisher: "Microsoft",
    url: "https://github.com/microsoft/graphrag",
    exactAnchor: "https://microsoft.github.io/graphrag/index/overview/",
    accessedOn,
    licence: "MIT",
    licenceUrl: "https://github.com/microsoft/graphrag/blob/main/LICENSE",
    reuse: "link-and-synthesise",
    note: "Primary source for entity, relationship, community, local, and global graph-based retrieval patterns.",
    caveat: "The repository is a research reference, indexing can be expensive, and GraphRAG is not always superior.",
  },
  {
    id: "owasp-rag-security",
    evidenceLabel: "security-guidance",
    title: "Retrieval-Augmented Generation Security Cheat Sheet",
    publisher: "OWASP",
    url: "https://cheatsheetseries.owasp.org/cheatsheets/RAG_Security_Cheat_Sheet.html",
    exactAnchor: "https://cheatsheetseries.owasp.org/cheatsheets/RAG_Security_Cheat_Sheet.html",
    accessedOn,
    licence: "CC-BY-SA-4.0",
    licenceUrl: "https://github.com/OWASP/CheatSheetSeries/blob/master/LICENSE.md",
    reuse: "link-and-synthesise",
    note: "Defensive guidance for poisoning, indirect injection, provenance, least privilege, and output validation.",
    caveat: "A checklist supports threat modeling but does not certify a deployment as secure.",
  },
  {
    id: "azure-search-rag-demo",
    evidenceLabel: "official-repository",
    title: "Azure Search OpenAI Demo",
    publisher: "Microsoft Azure Samples",
    url: "https://github.com/Azure-Samples/azure-search-openai-demo",
    exactAnchor: "https://github.com/Azure-Samples/azure-search-openai-demo",
    accessedOn,
    licence: "MIT",
    licenceUrl: "https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/LICENSE",
    reuse: "link-and-synthesise",
    note: "Enterprise reference for citations, retrieval inspection, ACLs, telemetry, evaluation, and multimodal paths.",
    caveat: "The sample itself warns that production deployments need additional security work.",
  },
  {
    id: "paperqa",
    evidenceLabel: "maintainer-repository",
    title: "PaperQA2",
    publisher: "FutureHouse",
    url: "https://github.com/Future-House/paper-qa",
    exactAnchor: "https://github.com/Future-House/paper-qa",
    accessedOn,
    licence: "Apache-2.0",
    licenceUrl: "https://github.com/Future-House/paper-qa/blob/main/LICENSE",
    reuse: "link-and-synthesise",
    note: "Scientific-paper context with metadata, page evidence, reranking, iterative queries, and citation quality.",
    caveat: "Named benchmark results and internal-service features are not universal claims about the open-source package.",
  },
  {
    id: "sourcegraph-cody-context",
    evidenceLabel: "official-doc",
    title: "Cody context",
    publisher: "Sourcegraph",
    url: "https://sourcegraph.com/docs/cody/core-concepts/context",
    exactAnchor: "https://sourcegraph.com/docs/cody/core-concepts/context",
    accessedOn,
    licence: "site-terms",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Codebase context source covering lexical search, graph context, repositories, and explicit file scope.",
    caveat: "Current product behaviour belongs to current documentation, not older repository snapshots.",
  },
  {
    id: "privategpt",
    evidenceLabel: "maintainer-repository",
    title: "PrivateGPT",
    publisher: "Zylon",
    url: "https://github.com/zylon-ai/private-gpt",
    exactAnchor: "https://github.com/zylon-ai/private-gpt",
    accessedOn,
    licence: "Apache-2.0",
    licenceUrl: "https://github.com/zylon-ai/private-gpt/blob/main/LICENSE",
    reuse: "link-and-synthesise",
    note: "Local deployment context spanning ingestion, parsing, splitting, embeddings, storage, API, and UI.",
    caveat: "A local label does not prove every dependency, telemetry path, parser, embedding call, or model stays offline.",
  },
  {
    id: "ragflow",
    evidenceLabel: "maintainer-repository",
    title: "RAGFlow",
    publisher: "InfiniFlow",
    url: "https://github.com/infiniflow/ragflow",
    exactAnchor: "https://github.com/infiniflow/ragflow/blob/main/docs/basics/rag.md",
    accessedOn,
    licence: "Apache-2.0",
    licenceUrl: "https://github.com/infiniflow/ragflow/blob/main/LICENSE",
    reuse: "link-and-synthesise",
    note: "Complex-document context with visible parsing, chunk templates, retrieval testing, and multimodal support.",
    caveat: "Maintainer-described capabilities are not independent performance validation.",
  },
  {
    id: "langchain-rag-from-scratch",
    evidenceLabel: "maintainer-repository",
    title: "RAG From Scratch",
    publisher: "LangChain",
    url: "https://github.com/langchain-ai/rag-from-scratch",
    exactAnchor: "https://github.com/langchain-ai/rag-from-scratch",
    accessedOn,
    licence: "undeclared",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "Compact maintainers' tutorial that exposes indexing, retrieval, and generation as separate stages.",
    caveat: "It is deliberately simplified and package imports can age.",
  },
  {
    id: "dify-docs",
    evidenceLabel: "maintainer-repository",
    title: "Dify Knowledge Retrieval documentation",
    publisher: "LangGenius",
    url: "https://github.com/langgenius/dify-docs",
    exactAnchor: "https://github.com/langgenius/dify-docs/blob/bca060d6b2d741071394605cadae46badb9911c5/en/cloud/use-dify/nodes/knowledge-retrieval.mdx",
    accessedOn,
    licence: "CC-BY-4.0",
    licenceUrl: "https://github.com/langgenius/dify-docs/blob/bca060d6b2d741071394605cadae46badb9911c5/LICENSE",
    reuse: "licensed-local-figure",
    note: "Licensed documentation screenshots make workflow, chunking, chunk inspection, retrieval settings, and citations visible.",
    caveat: "Visible model names and numeric settings are historical UI examples, not recommended universal defaults.",
    commit: "bca060d6b2d741071394605cadae46badb9911c5",
  },
  {
    id: "user-report-sourcegraph-no-context",
    evidenceLabel: "individual-user-report",
    title: "Reported Cody no-context failure",
    publisher: "GitHub user report",
    url: "https://github.com/sourcegraph/sourcegraph-public-snapshot/issues/60500",
    exactAnchor: "https://github.com/sourcegraph/sourcegraph-public-snapshot/issues/60500",
    accessedOn,
    licence: "undeclared",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "A reported workflow produced a plausible response when no usable context was available.",
    caveat: "One closed report from one product version. It supports a test case, not a prevalence claim.",
  },
  {
    id: "user-report-ragflow-reading-order",
    evidenceLabel: "individual-user-report",
    title: "Reported complex-PDF reading-order failure",
    publisher: "GitHub user report",
    url: "https://github.com/infiniflow/ragflow/issues/10147",
    exactAnchor: "https://github.com/infiniflow/ragflow/issues/10147",
    accessedOn,
    licence: "undeclared",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "A report that makes parser reading order a concrete pre-embedding test case.",
    caveat: "An individual report does not establish a general defect rate or current behaviour.",
  },
  {
    id: "user-report-paperqa-vendor-leak",
    evidenceLabel: "individual-user-report",
    title: "Reported unintended provider call during local indexing",
    publisher: "GitHub user report",
    url: "https://github.com/Future-House/paper-qa/issues/1321",
    exactAnchor: "https://github.com/Future-House/paper-qa/issues/1321",
    accessedOn,
    licence: "undeclared",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "A report used to teach network-flow audits across parsing, metadata, embedding, and generation stages.",
    caveat: "Configuration and version specific. It is not proof of current default behaviour.",
  },
  {
    id: "user-report-privategpt-wrong-answer",
    evidenceLabel: "individual-user-report",
    title: "Reported relevant references with an incorrect answer",
    publisher: "GitHub discussion",
    url: "https://github.com/zylon-ai/private-gpt/discussions/241",
    exactAnchor: "https://github.com/zylon-ai/private-gpt/discussions/241",
    accessedOn,
    licence: "undeclared",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "A user-reported example that separates retrieval success from answer correctness.",
    caveat: "Old mixed reports across versions and configurations. It is used only as a failure-analysis prompt.",
  },
  {
    id: "user-report-azure-missing-citations",
    evidenceLabel: "individual-user-report",
    title: "Reported correct retrieval with omitted citations",
    publisher: "GitHub user report",
    url: "https://github.com/Azure-Samples/azure-search-openai-demo/issues/562",
    exactAnchor: "https://github.com/Azure-Samples/azure-search-openai-demo/issues/562",
    accessedOn,
    licence: "undeclared",
    licenceUrl: null,
    reuse: "link-and-synthesise",
    note: "A reported case used to motivate separate citation-presence and citation-correctness tests.",
    caveat: "Older model and API context. It supports a conceptual test, not a claim about current behaviour.",
  },
] as const satisfies readonly RagSourceRecord[];

function indexRagSources(
  sources: readonly RagSourceRecord[],
): Readonly<Record<RagSourceId, RagSourceRecord>> {
  const index = {} as Record<RagSourceId, RagSourceRecord>;
  for (const source of sources) index[source.id] = source;
  return Object.freeze(index);
}

export const RAG_SOURCE_BY_ID = indexRagSources(RAG_SOURCES);
