import type { CourseKitSourceAuthoringSeed } from "../course-kit/authoring";
import type { CourseKitNonEmpty } from "../course-kit/types";

const ACCESSED_ON = "2026-08-26";

export const AI_RESEARCH_SOURCE_SEEDS = [
  {
    record: {
      id: "osf-preregistration",
      title: "OSF Registrations",
      publisher: "Center for Open Science",
      url: "https://help.osf.io/article/330-welcome-to-registrations",
      evidenceUrls: ["https://help.osf.io/article/330-welcome-to-registrations"],
      accessedOn: ACCESSED_ON,
      revision: "Rolling OSF help documentation accessed 2026-08-26",
      kind: "official-documentation",
      stability: "current-documentation",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Timestamped, read-only registrations, embargoes, withdrawals, and the distinction between a mutable project and a registered snapshot.",
      boundary: "Registration timestamps a plan; it does not make the question, methods, analysis, or later interpretation valid or unbiased.",
    },
    zhHans: { supports: "支持带时间戳的只读注册、embargo、撤回，以及可变项目与注册快照的区分。", boundary: "注册只为计划加时间戳；它不会自动使问题、方法、分析或后续解释有效、无偏。" },
  },
  {
    record: {
      id: "prisma-2020",
      title: "PRISMA 2020 statement",
      publisher: "The BMJ and PRISMA Statement group",
      url: "https://www.bmj.com/content/372/bmj.n71.long",
      evidenceUrls: ["https://www.bmj.com/content/372/bmj.n71.long", "https://www.prisma-statement.org/prisma-2020-statement"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2021-03-29",
      revision: "PRISMA 2020",
      kind: "normative-standard",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "CC BY 4.0 for the BMJ article; original course diagrams and checklists are independently authored",
      supports: "A reporting checklist and flow structure for systematic reviews, including protocol, selection, synthesis, limitations, and availability reporting.",
      boundary: "PRISMA is a reporting guideline, not a conduct handbook, risk-of-bias tool, quality score, or guarantee that a search or conclusion is complete.",
    },
    zhHans: { supports: "支持系统综述的协议、筛选、综合、局限、可用性与流程报告结构。", boundary: "PRISMA 是报告指南，不是实施手册、偏倚工具、质量分数，也不保证检索或结论完整。" },
  },
  {
    record: {
      id: "prisma-search",
      title: "PRISMA-S: an extension to the PRISMA Statement for Reporting Literature Searches",
      publisher: "Systematic Reviews and PRISMA Statement group",
      url: "https://www.prisma-statement.org/prisma-search",
      evidenceUrls: ["https://www.prisma-statement.org/prisma-search", "https://doi.org/10.1186/s13643-020-01542-z"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2021-01-26",
      revision: "PRISMA-S, 16-item extension",
      kind: "normative-standard",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "Open-access article under CC BY; independently authored course fixtures",
      supports: "Reporting the information sources, complete strategies, limits, dates, peer review, deduplication, updates, and records produced by literature searches.",
      boundary: "Transparent reporting does not guarantee comprehensive retrieval, stable database indexing, correct query translation, or an unbiased review.",
    },
    zhHans: { supports: "支持报告信息源、完整策略、限制、日期、同行检查、去重、更新和检索记录数。", boundary: "透明报告不能保证全面召回、数据库索引稳定、查询转换正确或综述无偏。" },
  },
  {
    record: {
      id: "cochrane-search",
      title: "Cochrane Handbook, Chapter 4: Searching for and selecting studies",
      publisher: "Cochrane",
      url: "https://training.cochrane.org/handbook/current/chapter-04",
      evidenceUrls: ["https://training.cochrane.org/handbook/current/chapter-04", "https://training.cochrane.org/handbook/current"],
      accessedOn: ACCESSED_ON,
      revision: "Cochrane Handbook version 6.5, 2024",
      kind: "official-guidance",
      stability: "version-pinned",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Conceptual search development, information sources, search sensitivity, documentation, and search-to-selection workflow for intervention reviews.",
      boundary: "The chapter's health-intervention context and recommended sources cannot be copied mechanically into every discipline or evidence-synthesis design.",
    },
    zhHans: { supports: "支持干预综述中的概念检索、信息源、检索敏感性、记录与筛选流程。", boundary: "健康干预情境和推荐信息源不能机械外推到所有学科或综合设计。" },
  },
  {
    record: {
      id: "cochrane-selection",
      title: "Cochrane Handbook, Chapter 4: Study selection and record management",
      publisher: "Cochrane",
      url: "https://training.cochrane.org/handbook/current/chapter-04",
      evidenceUrls: ["https://training.cochrane.org/handbook/current/chapter-04"],
      accessedOn: ACCESSED_ON,
      revision: "Cochrane Handbook version 6.5, 2024",
      kind: "official-guidance",
      stability: "version-pinned",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Eligibility decisions, duplicate records, multiple reports, screening roles, exclusion reasons, and documentation of study selection.",
      boundary: "A documented flow does not prove that criteria were appropriate, independently applied, or free from systematic misunderstanding.",
    },
    zhHans: { supports: "支持资格决定、重复记录、多份报告、筛选角色、排除理由与研究选择记录。", boundary: "记录流程不能证明标准恰当、独立应用或没有系统性误解。" },
  },
  {
    record: {
      id: "grade-book-current",
      title: "GRADE Book and transitioning GRADE Handbook",
      publisher: "GRADE Working Group and GRADEpro",
      url: "https://book.gradepro.org/",
      evidenceUrls: ["https://book.gradepro.org/", "https://gdt.gradepro.org/app/handbook/handbook.html"],
      accessedOn: ACCESSED_ON,
      revision: "New GRADE Book available since 2024; 2013 handbook is being phased out chapter by chapter",
      kind: "official-guidance",
      stability: "current-documentation",
      reuseStatus: "link-and-paraphrase-only",
      supports: "A transparent framework for rating certainty in bodies of evidence and separating certainty judgments from recommendation strength.",
      boundary: "GRADE is primarily a health-evidence framework, still requires judgment, and the legacy handbook cannot be treated as a permanently current universal evidence hierarchy.",
    },
    zhHans: { supports: "支持对证据体确定性作透明判断，并区分证据确定性与建议强度。", boundary: "GRADE 主要面向健康证据，仍需判断；旧 handbook 不能当作永久现行、普遍证据层级。" },
  },
  {
    record: {
      id: "cochrane-bias",
      title: "Cochrane Handbook, Chapter 8: Assessing risk of bias in a randomized trial",
      publisher: "Cochrane",
      url: "https://training.cochrane.org/handbook/current/chapter-08",
      evidenceUrls: ["https://training.cochrane.org/handbook/current/chapter-08"],
      accessedOn: ACCESSED_ON,
      revision: "Cochrane Handbook version 6.5, 2024",
      kind: "official-guidance",
      stability: "version-pinned",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Domain-based, result-specific risk-of-bias judgments with supporting information rather than one unexplained quality score.",
      boundary: "The tool is design-specific, depends on reported and external information, and cannot be automated into an objective truth label.",
    },
    zhHans: { supports: "支持按领域、按结果并保存依据的偏倚风险判断，而不是不透明总质量分。", boundary: "工具依研究设计和可得信息而定，不能自动化为客观真值标签。" },
  },
  {
    record: {
      id: "cochrane-data-collection",
      title: "Cochrane Handbook, Chapter 5: Collecting data",
      publisher: "Cochrane",
      url: "https://training.cochrane.org/handbook/current/chapter-05",
      evidenceUrls: ["https://training.cochrane.org/handbook/current/chapter-05"],
      accessedOn: ACCESSED_ON,
      revision: "Cochrane Handbook version 6.5, 2024",
      kind: "official-guidance",
      stability: "version-pinned",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Predefined data-collection forms, duplicate checking, source locations, transformations, disagreements, and data management.",
      boundary: "The chapter does not establish OCR, PDF parsing, table extraction, or graph-reading accuracy for any tool or layout.",
    },
    zhHans: { supports: "支持预定义抽取表、双重核验、来源位置、转换、分歧与数据管理。", boundary: "该章不证明任何 OCR、PDF 解析、表格抽取或读图工具在所有版式上的准确性。" },
  },
  {
    record: {
      id: "pdf-2-spec",
      title: "PDF 2.0 — ISO 32000-2:2020",
      publisher: "ISO; free access facilitated by the PDF Association",
      url: "https://pdfa.org/resource/iso-32000-2/",
      evidenceUrls: ["https://pdfa.org/resource/iso-32000-2/"],
      accessedOn: ACCESSED_ON,
      revision: "ISO 32000-2:2020 with errata collection updated through June 2026",
      kind: "normative-standard",
      stability: "version-pinned",
      reuseStatus: "link-and-paraphrase-only",
      supports: "The distinction between PDF's document structure and a human-readable rendered page, including why extraction order is not equivalent to visual reading order.",
      boundary: "A specification does not prove a particular PDF conforms, preserves semantics, or can be extracted without layout-, font-, scan-, and tool-specific error.",
    },
    zhHans: { supports: "支持区分 PDF 文档结构与人类看到的渲染页面，以及抽取顺序不等于视觉阅读顺序。", boundary: "规范不能证明具体 PDF 合规、保留语义或可在所有版式、字体、扫描和工具条件下无误抽取。" },
  },
  {
    record: {
      id: "grobid-evaluation",
      title: "GROBID end-to-end evaluation",
      publisher: "GROBID project",
      url: "https://grobid.readthedocs.io/en/latest/End-to-end-evaluation/",
      evidenceUrls: ["https://grobid.readthedocs.io/en/latest/End-to-end-evaluation/", "https://github.com/grobidOrg/grobid"],
      accessedOn: ACCESSED_ON,
      revision: "Rolling project documentation accessed 2026-08-26",
      kind: "official-documentation",
      stability: "current-documentation",
      reuseStatus: "licence-noted-no-copy",
      licence: "Apache-2.0 project code; linked and paraphrased documentation",
      supports: "Task-level evaluation of scholarly-document parsing and the need to measure extraction quality against gold data.",
      boundary: "Reported accuracy is task-, corpus-, language-, layout-, version-, and metric-dependent and cannot replace page-level verification of critical claims.",
    },
    zhHans: { supports: "支持用 gold data 按任务评估学术文档解析，并测量抽取质量。", boundary: "准确率依任务、语料、语言、版式、版本和指标而变，不能替代关键主张的页级核验。" },
  },
  {
    record: {
      id: "crossref-rest",
      title: "Crossref REST API",
      publisher: "Crossref",
      url: "https://www.crossref.org/documentation/retrieve-metadata/rest-api/",
      evidenceUrls: ["https://www.crossref.org/documentation/retrieve-metadata/rest-api/"],
      accessedOn: ACCESSED_ON,
      revision: "Rolling documentation accessed 2026-08-26",
      kind: "official-documentation",
      stability: "current-documentation",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Querying deposited DOI metadata to reconcile titles, authors, venues, dates, relations, and identifiers.",
      boundary: "Deposited metadata does not verify a paper's claim, authorship-role inference, peer-review quality, full-text rights, or the correctness of every field.",
    },
    zhHans: { supports: "支持查询 DOI metadata 并核对题名、作者、来源、日期、关系与标识。", boundary: "存入的 metadata 不验证论文主张、作者角色推断、评审质量、全文权利或每个字段正确。" },
  },
  {
    record: {
      id: "niso-jats",
      title: "ANSI/NISO Z39.96-2024, JATS version 1.4",
      publisher: "National Information Standards Organization",
      url: "https://www.niso.org/publications/z3996-2024-jats",
      evidenceUrls: ["https://www.niso.org/publications/z3996-2024-jats", "https://jats.nlm.nih.gov/1.4/"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2024-10-01",
      revision: "JATS version 1.4",
      kind: "normative-standard",
      stability: "version-pinned",
      reuseStatus: "link-and-paraphrase-only",
      supports: "A common XML interchange structure for journal-article metadata, body, references, tables, and other components.",
      boundary: "Markup structure does not verify that an element is present in the human source, correctly tagged, factually true, or licensed for reuse.",
    },
    zhHans: { supports: "支持期刊文章 metadata、正文、参考文献、表格等组件的通用 XML 交换结构。", boundary: "标记结构不能证明元素在原文存在、标注正确、事实真实或获得复用许可。" },
  },
  {
    record: {
      id: "rag-original",
      title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
      publisher: "Advances in Neural Information Processing Systems",
      url: "https://proceedings.neurips.cc/paper/2020/hash/6b493230205f780e1bc26945df7481e5-Abstract.html",
      evidenceUrls: ["https://proceedings.neurips.cc/paper/2020/hash/6b493230205f780e1bc26945df7481e5-Abstract.html"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2020-12-06",
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "The original retrieval-augmented generation architecture and the separation between a parametric generator and retrieved non-parametric memory.",
      boundary: "The paper does not make retrieved passages, generated citations, or model answers authoritative; this course uses RAG only to locate material for primary-source verification.",
    },
    zhHans: { supports: "支持原始 RAG 架构以及参数生成器与检索到的非参数记忆之间的区分。", boundary: "论文不使检索片段、生成引文或模型答案成为权威；本课程只用 RAG 定位待核验的一手材料。" },
  },
  {
    record: {
      id: "asa-pvalues",
      title: "ASA Statement on Statistical Significance and P-Values",
      publisher: "American Statistical Association",
      url: "https://www.amstat.org/asa/files/pdfs/p-valuestatement.pdf",
      evidenceUrls: ["https://www.amstat.org/asa/files/pdfs/p-valuestatement.pdf"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2016-03-07",
      kind: "official-guidance",
      stability: "version-pinned",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Official principles that p-values do not measure effect size, importance, truth of a hypothesis, or the probability that results arose by chance alone.",
      boundary: "The statement does not validate any particular model, estimand, sampling design, multiplicity correction, causal claim, or decision threshold.",
    },
    zhHans: { supports: "支持 p 值不衡量效应大小、重要性、假设真实性或结果纯由偶然产生概率的官方原则。", boundary: "该声明不验证任何具体模型、estimand、抽样设计、多重性修正、因果主张或决策阈值。" },
  },
  {
    record: {
      id: "tidy-data",
      title: "Tidy Data",
      publisher: "Journal of Statistical Software",
      url: "https://doi.org/10.18637/jss.v059.i10",
      evidenceUrls: ["https://doi.org/10.18637/jss.v059.i10"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2014-09-12",
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "A tabular organisation in which variables, observations, and values have explicit structural roles that support reproducible transformation and analysis.",
      boundary: "Tidy structure is not the only valid data model and does not establish sampling validity, provenance, causal identification, or correct interpretation.",
    },
    zhHans: { supports: "支持让变量、观测和值具有显式结构角色的表格组织原则。", boundary: "Tidy 不是唯一有效数据模型，也不证明抽样效度、provenance、因果识别或解释正确。" },
  },
  {
    record: {
      id: "entreq",
      title: "Enhancing transparency in reporting the synthesis of qualitative research: ENTREQ",
      publisher: "BMC Medical Research Methodology",
      url: "https://doi.org/10.1186/1471-2288-12-181",
      evidenceUrls: ["https://doi.org/10.1186/1471-2288-12-181"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2012-11-27",
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "licence-noted-no-copy",
      licence: "Open-access CC BY article; independently authored course materials",
      supports: "Twenty-one reporting items for qualitative evidence synthesis across introduction, methods, search/selection, appraisal, and synthesis.",
      boundary: "ENTREQ is a reporting aid, not proof of synthesis trustworthiness, and it does not govern every primary qualitative design.",
    },
    zhHans: { supports: "支持定性证据综合在引言、方法、检索筛选、评估与综合五方面的 21 项报告内容。", boundary: "ENTREQ 是报告辅助，不证明综合可信，也不适用于每一种一手定性设计。" },
  },
  {
    record: {
      id: "coreq",
      title: "Consolidated criteria for reporting qualitative research (COREQ)",
      publisher: "International Journal for Quality in Health Care",
      url: "https://pubmed.ncbi.nlm.nih.gov/17872937/",
      evidenceUrls: ["https://pubmed.ncbi.nlm.nih.gov/17872937/", "https://doi.org/10.1093/intqhc/mzm042"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2007-09-14",
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "A 32-item reporting checklist for qualitative interviews and focus groups, including research team, design, analysis, and findings.",
      boundary: "COREQ applies to interviews and focus groups; it is not a universal qualitative-method checklist or a guarantee of analytic trustworthiness.",
    },
    zhHans: { supports: "支持访谈与焦点小组在研究团队、设计、分析和发现方面的 32 项报告清单。", boundary: "COREQ 只适用于访谈与焦点小组，不是普遍定性方法清单，也不保证分析可信。" },
  },
  {
    record: {
      id: "srqr",
      title: "Standards for Reporting Qualitative Research (SRQR)",
      publisher: "Academic Medicine",
      url: "https://pubmed.ncbi.nlm.nih.gov/24979285/",
      evidenceUrls: ["https://pubmed.ncbi.nlm.nih.gov/24979285/", "https://doi.org/10.1097/ACM.0000000000000388"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2014-09-01",
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "A broader set of reporting recommendations for qualitative research across traditions.",
      boundary: "SRQR improves reporting transparency but does not establish methodological fit, truthful participant representation, saturation, or transferability.",
    },
    zhHans: { supports: "支持跨多种定性传统的较广泛报告建议。", boundary: "SRQR 提高报告透明度，但不能证明方法匹配、参与者表述真实、达到饱和或可转移。" },
  },
  {
    record: {
      id: "acm-artifact-review",
      title: "ACM Artifact Review and Badging",
      publisher: "Association for Computing Machinery",
      url: "https://www.acm.org/publications/policies/artifact-review-and-badging-current",
      evidenceUrls: ["https://www.acm.org/publications/policies/artifact-review-and-badging-current"],
      accessedOn: ACCESSED_ON,
      revision: "Current ACM policy accessed 2026-08-26",
      kind: "official-guidance",
      stability: "current-documentation",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Distinctions among artifacts being available, evaluated as functional, evaluated as reusable, and results being reproduced or replicated.",
      boundary: "A badge is a specific review outcome, not proof that every claim is correct, the software is secure, or the artifact works outside the evaluated conditions.",
    },
    zhHans: { supports: "支持区分产物可用、功能已评估、可复用已评估，以及结果被复现或重复。", boundary: "徽章是特定审查结果，不证明所有主张正确、软件安全或产物在评估条件外可运行。" },
  },
  {
    record: {
      id: "icmje-ai",
      title: "ICMJE recommendations on AI use by authors",
      publisher: "International Committee of Medical Journal Editors",
      url: "https://icmje.org/recommendations/browse/artificial-intelligence/ai-use-by-authors.html",
      evidenceUrls: ["https://icmje.org/recommendations/browse/artificial-intelligence/ai-use-by-authors.html", "https://www.icmje.org/news-and-editorials/icmje-recommendations_annotated_jan26.pdf"],
      accessedOn: ACCESSED_ON,
      revision: "Current page and annotated recommendations, January 2026",
      kind: "official-guidance",
      stability: "current-documentation",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Disclosure of AI-assisted work, human responsibility for submitted material, confidentiality, citation verification, and why AI cannot be an author.",
      boundary: "ICMJE addresses medical-journal publication ethics; each journal, field, funder, institution, and law may impose different or additional rules.",
    },
    zhHans: { supports: "支持披露 AI 协助、人类对投稿负责、保密、引文核验，以及 AI 不能署名为作者。", boundary: "ICMJE 面向医学期刊伦理；期刊、学科、资助者、机构与法律可能另有要求。" },
  },
  {
    record: {
      id: "fair-principles",
      title: "The FAIR Guiding Principles for scientific data management and stewardship",
      publisher: "Scientific Data",
      url: "https://doi.org/10.1038/sdata.2016.18",
      evidenceUrls: ["https://doi.org/10.1038/sdata.2016.18"],
      accessedOn: ACCESSED_ON,
      publishedOn: "2016-03-15",
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "licence-noted-no-copy",
      licence: "CC BY 4.0; independent course synthesis",
      supports: "High-level goals for research objects to be findable, accessible under stated conditions, interoperable, and reusable with rich provenance.",
      boundary: "FAIR does not mean open, public, ethical, legally reusable, reproducible, high quality, or free of access controls.",
    },
    zhHans: { supports: "支持研究对象可发现、在声明条件下可访问、可互操作，并以丰富 provenance 支持复用。", boundary: "FAIR 不等于开放、公开、合伦理、合法可复用、可复现、高质量或不设访问控制。" },
  },
] as const satisfies CourseKitNonEmpty<CourseKitSourceAuthoringSeed>;

export type AiResearchSourceId =
  (typeof AI_RESEARCH_SOURCE_SEEDS)[number]["record"]["id"];
