import type { MathAnimationCourseCopy } from "../types";

export const MATH_ANIMATION_EN_COPY = {
  meta: {
    kicker: "From mathematical truth to inspected frames",
    title: "How to Make Mathematical Animations with Codex and Claude",
    summary: "Choose an engine with evidence, direct AI agents through a scene contract, and release a mathematically checked animation.",
    audience: "For teachers, researchers, designers, and developers who can read basic Python or TypeScript and want a reproducible animation workflow.",
    prerequisite: "You need Git, a code editor, and a terminal. The primary Manim path also needs Python, FFmpeg, and a LaTeX installation for formula rendering.",
    level: "Beginner to advanced",
    evidenceNote: "Repository capabilities are tied to dated revisions, licenses, official documentation, and local smoke evidence. X posts are practice signals only, never proof of effectiveness.",
  },
  ui: {
    course: "Course",
    courseNumber: "Course 19",
    modules: "Modules",
    minutes: "minutes",
    phases: "Phases",
    sources: "Sources",
    learningOutcomes: "What you will be able to do",
    curriculum: "Course map",
    evidenceBoundary: "Evidence boundary",
    repositoryLab: "Repository evidence lab",
    repositoryLabIntro: "Scores compare fit for this course, not universal quality. Open the evidence and choose for your intended output.",
    score: "Fit score",
    verdict: "Role",
    bestFor: "Best for",
    limit: "Primary limit",
    core: "Core path",
    advanced: "Advanced reference",
    extension: "Extension",
    companion: "Companion",
    chooseGoal: "Choose your output",
    goalVideo: "Narrated math video",
    goalWeb: "Interactive web animation",
    goalTalk: "Live talk or lesson",
    recommendation: "Recommended stack",
    start: "Start the course",
    resume: "Resume learning",
    progress: "Verified progress",
    reset: "Reset Course 19",
    resetConfirm: "Reset your Course 19 evidence, quiz, and capstone progress?",
    markComplete: "Save evidence and complete",
    completed: "Verified complete",
    artifactEvidence: "Artifact evidence",
    artifactEvidenceHelp: "Enter a repository-relative path, commit, or precise artifact receipt.",
    verificationEvidence: "Verification evidence",
    verificationEvidenceHelp: "Enter the command and observed result, render path, or inspected frame receipt.",
    evidenceRequired: "Pass the checkpoint and save both evidence records before completion.",
    storageNote: "Progress stays in this browser and is never uploaded.",
    storageUnavailable: "Persistent browser storage is unavailable. Progress is kept for this tab only.",
    resetDone: "Course 19 progress was reset.",
    resetMemory: "Course 19 progress was reset for this tab, but persistent storage is unavailable.",
    objective: "Objective",
    practiceArtifact: "Practice artifact",
    agentPrompt: "Agent task contract",
    copyPrompt: "Copy prompt",
    copied: "Copied",
    copyFailed: "Copy failed. Select the prompt manually",
    codeDependency: "This file matches the downloadable starter and runs with the adjacent manim/math_truth.py. The invariant test itself does not import Manim.",
    verificationGate: "Verification gate",
    checkpoint: "Checkpoint",
    checkAnswer: "Check answer",
    correct: "Correct. Save an artifact and verification record to complete this module.",
    incorrect: "Not yet. Revisit the boundary and try again.",
    answerCorrect: "Correct",
    answerIncorrect: "Incorrect",
    correctAnswer: "Correct answer",
    sourceLedger: "Source ledger",
    sourceBoundary: "What this source does not establish",
    accessedOn: "Accessed",
    previous: "Previous",
    next: "Next",
    backToCourse: "Back to Course 19",
    allModules: "All modules",
    finalAssessment: "Final assessment",
    submitAssessment: "Score assessment",
    startAssessment: "Begin assessment",
    retryAssessment: "Try again",
    bestScore: "Best score",
    scoreResult: "Assessment score",
    assessmentPassed: "Assessment passed",
    assessmentRetry: "Review the missed items and try again",
    capstone: "Capstone",
    markCapstone: "Record reviewed capstone",
    capstoneComplete: "Review evidence recorded",
    capstoneEvidence: "Release review evidence",
    capstoneEvidenceHelp: "Summarize the release folder, exact verification commands, independent reviewer decision, and unresolved risks.",
    capstoneAttestationBoundary: "This browser records your evidence reference. It cannot inspect the files or independently certify the review.",
    allChecksRequired: "All modules, the assessment, six artifact groups, and a substantive review receipt are required.",
    motionLab: "Unit-circle motion lab",
    play: "Play",
    pause: "Pause",
    scrubber: "Animation time",
    reducedMotion: "Motion is reduced by your system preference. Use the timeline to inspect static keyframes.",
    languageFallback: "This course has reviewed long-form copy in English and Simplified Chinese. You are viewing the English content inside your selected site language.",
  },
  principles: [
    "Write the mathematical invariant before writing an animation instruction.",
    "Choose a repository by output, maintenance, license, and reproducibility, not stars alone.",
    "Give Codex and Claude explicit roles, but treat those roles as a workflow choice rather than a fixed model boundary.",
    "A render is finished only after mathematical, visual, accessibility, and rights checks pass.",
  ],
  outcomes: [
    "Turn a mathematical explanation into a timed scene contract with observable acceptance checks.",
    "Evaluate Manim Community, ManimGL, Motion Canvas, Remotion, and companion libraries using a transparent rubric.",
    "Build equations, graphs, geometry, and continuity-preserving transforms in Manim Community.",
    "Use Codex to implement, test, render, and report repository changes from a bounded task contract.",
    "Use Claude to challenge the storyboard, exposition, ambiguity, and frame-level review while preserving factual boundaries.",
    "Ship a reproducible animation release pack with source, license, environment, invariant, accessibility, and export evidence.",
  ],
  phases: {
    frame: {
      title: "Frame the mathematical story",
      summary: "Choose the output, evaluate the engine, and write a scene contract before the first line of animation code.",
    },
    animate: {
      title: "Build semantic motion",
      summary: "Create a reliable Manim environment, preserve object identity, and connect equations, graphs, and geometry.",
    },
    direct: {
      title: "Direct the coding agents",
      summary: "Use bounded Codex and Claude loops, then branch into a browser-native Motion Canvas track when the output requires it.",
    },
    prove: {
      title: "Verify and release",
      summary: "Add voice or slides carefully, test mathematics and accessibility, then publish an auditable capstone package.",
    },
  },
  modules: {
    "outcome-before-engine": {
      kicker: "Decide before installing",
      title: "Start with the learning outcome, not the engine",
      summary: "A mathematical animation is a timed argument. Define what the viewer must understand and what evidence will show that the animation is correct.",
      objective: "Write a one-page outcome brief that separates mathematical truth, visual explanation, delivery format, and release constraints.",
      artifact: "OUTCOME_BRIEF.md with audience, misconception, invariant, output, duration, and acceptance tests",
      sections: [
        {
          heading: "Treat motion as part of the explanation",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-ce", "github-motion-canvas"],
          paragraphs: ["Manim Community models mathematical objects and transformations in Python, while Motion Canvas models a timed scene with TypeScript generators. Both make sequence, duration, and object state inspectable in code. Your first decision is therefore not which syntax looks friendlier. It is which representation matches the mathematical relationship you need to reveal."],
          bullets: ["Use semantic objects for equations, graphs, and geometry.", "Use a browser-native timeline when web preview and TypeScript integration dominate.", "Keep an interactive graph separate from a narrated animation unless the learning goal needs both."],
        },
        {
          heading: "Choose the deliverable before the toolchain",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["github-remotion"],
          paragraphs: ["An MP4 lesson, a live slide deck, and an interactive web scene have different constraints. Remotion is strong when React composition and media assembly are central, but its license requires context-specific review. Write the target aspect ratios, duration, narration needs, interaction model, and hosting boundary before comparing engines."],
        },
        {
          heading: "Use public examples as hypotheses",
          evidenceMode: "version-watch",
          sourceIds: ["x-minchoi-claude-manim"],
          paragraphs: ["An X post can show that someone used Claude to generate a Manim scene. It cannot establish mathematical correctness, repeatability, teaching impact, or current compatibility. Capture the post as a discovery signal, then verify commands, APIs, versions, and licenses in the repository and official documentation."],
        },
      ],
      agentPrompt: "Read the proposed topic and produce OUTCOME_BRIEF.md. State one learner misconception, one mathematical invariant, one visual change that exposes the invariant, the final delivery format, and six testable acceptance checks. Do not select an engine until the output constraints are explicit.",
      verificationGate: ["The mathematical claim can be checked without watching the animation.", "The scene has one primary learning change, not a list of decorative effects.", "The output format and aspect ratios are explicit.", "Every acceptance check has an observable pass or fail."],
      checkpoint: {
        question: "What should determine the first repository choice?",
        options: ["The highest star count", "The shortest installation command", "The intended learning change and output constraints", "The model named in an X post"],
        correctIndex: 2,
        explanation: "Repository fit begins with the mathematical and delivery contract. Popularity and demonstrations can inform discovery, but they do not replace the contract.",
      },
    },
    "repository-evidence-lab": {
      kicker: "Compare with a fixed rubric",
      title: "Evaluate the repositories before you depend on them",
      summary: "Score capability, maintenance, license clarity, preview, export, and teaching fit against pinned evidence.",
      objective: "Produce a repository decision record that can be repeated after a release or dependency change.",
      artifact: "REPOSITORY_DECISION.md with score breakdown, pinned revision, smoke result, license, and exclusion reasons",
      sections: [
        {
          heading: "Separate the two Manim families",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-ce", "github-manimgl", "github-manim-slides", "github-manim-voiceover"],
          paragraphs: ["Manim Community and ManimGL are related projects with incompatible commands and APIs. Use Manim Community as the primary teaching path because its community documentation and packaging target general use. Treat ManimGL as an advanced reference for the 3Blue1Brown production lineage. Manim Slides and Manim Voiceover are extensions, so validate their compatibility against the exact Manim Community version you pin."],
        },
        {
          heading: "Compare browser and video pipelines by job",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["github-motion-canvas", "github-remotion", "github-mafs", "github-jsxgraph"],
          paragraphs: ["Motion Canvas provides a TypeScript scene and timeline workflow. Remotion provides React-based video composition and rendering. Mafs and JSXGraph provide interactive mathematical companions rather than a complete narrated-video authoring pipeline. A high score means fit for this course contract, not that one project is universally better."],
        },
        {
          heading: "Pin what you actually tested",
          evidenceMode: "version-watch",
          sourceIds: ["github-manim-ce", "github-manimgl", "github-motion-canvas", "github-remotion"],
          paragraphs: ["Record an immutable commit SHA or release tag, the license file at that revision, installation commands, operating system, runtime versions, and the exact output inspected. If a render is blocked by LaTeX, a browser, a codec, or a native library, report the block instead of upgrading a documentation check into a render claim."],
        },
      ],
      agentPrompt: "Evaluate each candidate against the course rubric. For every row, provide a pinned commit or release, license evidence, exact smoke command, observed output, failure boundary, and best-fit use case. Never infer effectiveness from stars or an X post.",
      verificationGate: ["Manim Community and ManimGL are not mixed in one command path.", "Every repository record includes a version anchor and license boundary.", "Rendered, validated, and blocked results are distinguished.", "The recommendation names a specific output and learner profile."],
      checkpoint: {
        question: "A repository README parses and its tests pass, but no video was rendered because LaTeX is missing. What is the honest smoke status?",
        options: ["Validated, with the render block recorded", "Rendered", "Proven effective", "Exclude automatically"],
        correctIndex: 0,
        explanation: "A documentation or code validation is useful evidence, but it does not prove a render. The missing dependency belongs in the boundary.",
      },
    },
    "scene-contract-storyboard": {
      kicker: "Make intent executable",
      title: "Write a scene contract before prompting",
      summary: "Translate the mathematical argument into beats, state transitions, invariants, and frame-level acceptance checks.",
      objective: "Create a storyboard that a coding agent can implement and an independent reviewer can falsify.",
      artifact: "SCENE_CONTRACT.md and six-frame storyboard with timestamps, narration, state, and checks",
      sections: [
        {
          heading: "Give the repository durable instructions",
          evidenceMode: "source-grounded",
          sourceIds: ["github-3b1b-videos-claude", "anthropic-claude-memory"],
          paragraphs: ["The 3Blue1Brown videos repository includes project guidance for Claude Code and explicitly identifies its ManimGL environment. Anthropic documents repository-level instruction files as persistent project context. Use the same principle for your own scene: name the engine, commands, forbidden API mixing, render target, and verification sequence in a versioned project file."],
        },
        {
          heading: "Convert narration into state transitions",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["openai-codex-use-cases"],
          paragraphs: ["A useful scene contract describes the start state, the changed variable, the visual evidence, and the end state for each beat. The agent should know which object persists, which label updates, when the camera moves, and which fact must become visible before narration advances. This is a testable implementation contract, not a cinematic mood board."],
        },
        {
          heading: "Pressure-test ambiguity before coding",
          evidenceMode: "version-watch",
          sourceIds: ["openai-codex-use-cases", "anthropic-claude-memory"],
          paragraphs: ["Ask one agent to implement only after another pass identifies underspecified terms such as smooth, intuitive, elegant, or obvious. Replace them with timing, spatial, mathematical, and accessibility criteria. Model behavior changes over time, so the durable asset is the explicit contract and its tests, not a prompt that once happened to work."],
        },
      ],
      agentPrompt: "Turn the mathematical explanation into a scene contract. For each beat, list timestamp range, narration, persistent objects, state change, camera rule, mathematical invariant, and one frame-level acceptance check. Flag every ambiguous adjective and request a measurable replacement.",
      verificationGate: ["Every beat changes a named state or advances the argument.", "Persistent objects keep identity across transformations.", "Narration never claims a result before the visual evidence appears.", "Each ambiguous adjective has been replaced with an observable rule."],
      checkpoint: {
        question: "Which instruction is most implementable?",
        options: ["Make the tangent transition elegant", "Use beautiful pacing", "Explain the limit intuitively", "Over 1.2 seconds, move h from 2.0 to 0.1 while the displayed slope stays within 0.01 of 2+h"],
        correctIndex: 3,
        explanation: "It names state, timing, dependency, and tolerance. The other options require the agent to invent acceptance criteria.",
      },
    },
    "manim-environment-first-scene": {
      kicker: "Reproduce before expanding",
      title: "Build a Manim environment and first scene",
      summary: "Create a pinned Python environment, render one low-quality preview, and record every native dependency.",
      objective: "Render a minimal Manim Community scene from a clean checkout and preserve the environment evidence needed to repeat it.",
      artifact: "A reproducible first-scene folder with lock file, environment report, command log, preview video, and inspected still",
      sections: [
        {
          heading: "Follow the Community quickstart exactly",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-ce", "docs-manim-quickstart"],
          paragraphs: ["Start with the official Manim Community installation and quickstart for the pinned release. Keep the scene small: one title, one shape, and one semantic transformation. Render with the documented command and low-quality preview settings before adding LaTeX, voice, plugins, custom fonts, or camera work."],
        },
        {
          heading: "Record the native toolchain",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["docs-manim-quickstart", "ffmpeg-general"],
          paragraphs: ["Python package success is only one layer. Capture Python, Manim, FFmpeg, operating-system, and LaTeX versions, then save the exact render command and resulting file metadata. FFmpeg is the media boundary that turns frames and streams into an inspectable deliverable, so codec and frame-rate evidence belongs beside the Python lock file."],
        },
        {
          heading: "Stop on version drift",
          evidenceMode: "version-watch",
          sourceIds: ["github-manim-ce"],
          paragraphs: ["When a generated snippet uses an unknown class or command, compare it with the pinned documentation before changing dependencies. Do not let an agent silently switch from Manim Community to ManimGL or install the newest release. A documented incompatibility is a more valuable result than an unrepeatable local success."],
        },
      ],
      agentPrompt: "Inspect the repository instructions and existing environment. Create the smallest Manim Community scene, pin dependencies, render a low-quality preview, extract one representative still, and report the exact commands, output paths, versions, and any blocked native dependency.",
      verificationGate: ["A clean environment can install from the recorded dependency files.", "The logged command creates the claimed preview path.", "The scene imports from Manim Community only.", "One rendered still has been visually inspected, not merely located."],
      checkpoint: {
        question: "What should you do when the generated code uses a ManimGL-only API in a Manim Community project?",
        options: ["Upgrade every dependency", "Stop, identify the API mismatch, and rewrite against the pinned Community docs", "Install ManimGL into the same environment", "Keep the code if it parses"],
        correctIndex: 1,
        explanation: "The two Manim families are incompatible. Preserve the selected engine and repair the code against its pinned documentation.",
      },
    },
    "transformations-camera-continuity": {
      kicker: "Preserve what the learner tracks",
      title: "Animate transformations and camera continuity",
      summary: "Make object identity, attention, and spatial continuity explicit so motion carries reasoning instead of hiding edits.",
      objective: "Build a transformation sequence in which the viewer can identify what persisted, what changed, and why the camera moved.",
      artifact: "A 20-40 second transformation scene plus an identity map and three inspected keyframes",
      sections: [
        {
          heading: "Transform semantic parts, not screenshots",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-ce"],
          paragraphs: ["Manim Community provides transformations that can preserve relationships between mathematical objects. For algebra, match tokens that survive from one expression to the next. For geometry, keep the same point, line, or region object when its state changes. The viewer should not have to rediscover an object after every animation call."],
        },
        {
          heading: "Give every camera move a teaching job",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["github-manimgl"],
          paragraphs: ["The 3Blue1Brown production lineage demonstrates a rich camera and scene vocabulary, but imitation is not a learning objective. Pan or zoom only when it reveals scale, preserves spatial context, or moves attention to the next dependency. Record the reason for each camera move in the scene contract and remove moves that do not change understanding."],
        },
        {
          heading: "Inspect continuity at keyframes",
          evidenceMode: "version-watch",
          sourceIds: ["github-manim-ce", "github-manimgl"],
          paragraphs: ["Generated code may technically render while replacing objects, overlapping labels, or moving the camera across an unexplained cut. Export stills before, during, and after each major transform. Compare object identity, reading order, safe margins, and formula state at those frames before accepting the sequence."],
        },
      ],
      agentPrompt: "Implement the transformation storyboard using the pinned engine only. Add a comment for every persistent object and camera move. Render low quality, export start, midpoint, and end frames, then report any identity break, overlap, unexplained cut, or camera move without a teaching purpose.",
      verificationGate: ["The same semantic object persists through each intended transform.", "The camera never moves without a documented learning purpose.", "Labels remain readable at the target crops.", "Start, midpoint, and end frames agree with the storyboard."],
      checkpoint: {
        question: "When should the camera move?",
        options: ["Whenever a scene feels slow", "After every equation", "Whenever the agent suggests a zoom", "When the move reveals scale, context, or the next dependency"],
        correctIndex: 3,
        explanation: "Camera motion is justified by the explanation. Pace alone does not establish a teaching purpose.",
      },
    },
    "equations-graphs-geometry": {
      kicker: "Bind representations to one state",
      title: "Synchronize equations, graphs, and geometry",
      summary: "Drive multiple visual representations from shared variables and test the mathematical relationship at sampled times.",
      objective: "Build a secant-to-tangent scene whose graph, points, line, formula, and numeric slope stay synchronized.",
      artifact: "A synchronized secant-to-tangent scene with invariant tests and five sampled frame records",
      sections: [
        {
          heading: "Use one state variable as the source of truth",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-ce", "docs-manim-quickstart"],
          paragraphs: ["A value tracker can drive the moving point, secant line, delta label, numeric slope, and camera condition from one value of h. This avoids independent animations that merely look synchronized. Define the mathematical function outside the visual callbacks, then reuse it in both the scene and invariant tests."],
        },
        {
          heading: "Test the relation, not only the pixels",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["github-manim-ce"],
          paragraphs: ["For f(x)=x^2 at a=1, the secant slope is 2+h while h is nonzero. Sample h at five checkpoints and assert the displayed value, line slope, and analytic expression agree within a stated tolerance. A frame hash can detect visual drift, but it cannot prove the underlying relation is correct."],
        },
        {
          heading: "Make numerical boundaries visible",
          evidenceMode: "version-watch",
          sourceIds: ["docs-manim-quickstart"],
          paragraphs: ["The animation approaches h=0 without setting the secant calculation to an undefined denominator. Show the limit as a conclusion after the visual sequence, label approximation honestly, and choose a sampling rate that does not imply exact continuity between rendered frames. Record floating-point and interpolation tolerances in the test output."],
        },
      ],
      agentPrompt: "Implement the secant-to-tangent scene from SCENE_CONTRACT.md. Drive every dependent visual from one h tracker. Add tests at h values 2, 1, 0.5, 0.1, and 0.08, plus negative h samples for the two-sided algebra. Render and extract timeline frames. Report test values and frame paths as separate evidence unless a receipt records the actual h value, timestamp, and path for an exact match.",
      verificationGate: ["Point, secant, labels, and slope share one source of state.", "The analytic invariant passes at all sampled values.", "The scene never divides by h=0.", "Approximation and limit notation are clearly distinguished."],
      checkpoint: {
        question: "What is the strongest correctness check for the secant scene?",
        options: ["Watch the video once", "Check that the MP4 exists", "Assert the slope relation at sampled h values and separately inspect sampled frames", "Compare only the file size"],
        correctIndex: 2,
        explanation: "Mathematical assertions test the relation, while timeline frames test binding and legibility. They become matched evidence only when the receipt records the actual h value and timestamp.",
      },
    },
    "codex-implementation-loop": {
      kicker: "Make the coding loop auditable",
      title: "Use Codex for implementation, tests, and render evidence",
      summary: "Turn the scene contract into a bounded repository task, inspect the diff, and require commands plus artifacts in the handoff.",
      objective: "Run a Codex-first loop that changes only in-scope scene files and reports verifiable outputs instead of a success narrative.",
      artifact: "A Codex task packet containing prompt, plan, diff, command log, test output, render paths, and unresolved boundaries",
      sections: [
        {
          heading: "Give Codex a repository-grounded task",
          evidenceMode: "source-grounded",
          sourceIds: ["openai-codex-use-cases", "github-manim-ce"],
          paragraphs: ["A strong task contract names the repository, engine, scene file, mathematical invariant, allowed files, prohibited changes, required commands, and handoff format. Ask Codex to inspect local instructions and the pinned documentation before implementation. This reduces accidental API mixing and makes review proportional to the actual diff."],
        },
        {
          heading: "Separate implementation from acceptance",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["openai-model-guidance"],
          paragraphs: ["Let Codex implement and run deterministic checks, then review the diff and artifacts against the original scene contract. A passing type check is not a rendered animation, and a rendered animation is not mathematical validation. Require a result table that distinguishes code, test, render, frame inspection, and known gaps."],
        },
        {
          heading: "Re-check current product behavior",
          evidenceMode: "version-watch",
          sourceIds: ["openai-codex-use-cases", "openai-model-guidance"],
          paragraphs: ["Codex interfaces and model guidance evolve. Keep course prompts at the level of task contract, repository evidence, and verification rather than depending on a transient button or model name. Before teaching a product-specific action, compare the lesson with current official OpenAI documentation."],
        },
      ],
      agentPrompt: "Read AGENTS.md and SCENE_CONTRACT.md. Implement only the named scene and its invariant tests. Do not change dependencies unless the task explicitly permits it. Render a low-quality preview, export three keyframes, run the listed checks, inspect the diff, and hand back a table of commands, exit results, artifact paths, and remaining uncertainty.",
      verificationGate: ["The diff stays inside the allowed file set.", "The handoff separates tests, render, and visual inspection.", "Every claimed artifact path exists.", "Unresolved dependencies or visual ambiguity remain visible."],
      checkpoint: {
        question: "Which handoff is acceptable?",
        options: ["A diff plus exact commands, exit results, artifact paths, inspected frames, and remaining gaps", "Done, the animation looks good", "TypeScript passed so the video is correct", "The model said every requirement passed"],
        correctIndex: 0,
        explanation: "A repository task is auditable only when another person can locate and re-check the evidence.",
      },
    },
    "claude-direction-review": {
      kicker: "Use a second perspective",
      title: "Use Claude for direction, ambiguity, and review",
      summary: "Ask Claude to critique the exposition and frames against the same contract, then verify every suggested code or factual change.",
      objective: "Run a Claude-first review that finds story and communication risks without granting the reviewer authority over mathematical truth or repository state.",
      artifact: "A Claude review packet with storyboard critique, ambiguity list, frame notes, accepted changes, rejected changes, and verification status",
      sections: [
        {
          heading: "Persist the project boundary",
          evidenceMode: "source-grounded",
          sourceIds: ["anthropic-claude-code-overview", "anthropic-claude-memory", "github-3b1b-videos-claude"],
          paragraphs: ["Use CLAUDE.md to state the engine, local commands, mathematical invariant, visual vocabulary, protected files, and required evidence. The 3Blue1Brown repository is valuable because it makes its ManimGL context explicit. It is not a drop-in instruction set for Manim Community, so adapt the contract rather than copying engine-specific commands."],
        },
        {
          heading: "Review the story and frames independently",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["x-minchoi-claude-manim", "x-cintas-claude-pythagoras", "x-dhruv-math-animation-thread"],
          paragraphs: ["Public posts show examples of Claude producing Manim animations, including mathematical topics. Treat them as evidence that the workflow has been attempted, not that the generated mathematics or pedagogy was valid. Give Claude your storyboard and sampled frames, ask what a learner might misread, and require every concern to point to a timestamp, object, or sentence."],
        },
        {
          heading: "Keep model roles swappable",
          evidenceMode: "version-watch",
          sourceIds: ["anthropic-claude-code-overview", "x-minchoi-claude-manim", "x-cintas-claude-pythagoras", "x-dhruv-math-animation-thread"],
          paragraphs: ["This course recommends Codex for implementation and Claude for direction because the division creates a useful independent review loop. It is not a benchmark claim or a permanent capability boundary. You can reverse the roles, but the implementer and reviewer must still use the same scene contract and produce separate evidence."],
        },
      ],
      agentPrompt: "Review the scene contract, narration, and three sampled frames without editing code. Identify the earliest point at which a learner could form the wrong inference. For each concern, cite a timestamp or frame, explain the mathematical or visual risk, propose the smallest repair, and label anything that requires domain-expert verification.",
      verificationGate: ["Every critique points to a concrete scene element.", "Suggested factual changes are checked against the mathematical invariant.", "Engine-specific commands are not copied across Manim families.", "Accepted and rejected review suggestions are recorded."],
      checkpoint: {
        question: "Why does this course separate implementer and reviewer roles?",
        options: ["To avoid checking either model's work", "To create an independent evidence loop, not to claim a permanent model ranking", "Because Claude cannot write code", "Because Codex cannot review explanations"],
        correctIndex: 1,
        explanation: "The role split is a workflow design. Capabilities and products change, so the contract and independent verification remain the stable parts.",
      },
    },
    "motion-canvas-web-track": {
      kicker: "Branch when the browser is the medium",
      title: "Build a TypeScript track with Motion Canvas",
      summary: "Use a browser-native scene and generator timeline when TypeScript, live preview, or web composition is the primary constraint.",
      objective: "Create a unit-circle scene in Motion Canvas and document when an interactive math library should remain a separate companion.",
      artifact: "A Motion Canvas unit-circle scene, preview record, export record, and engine decision note",
      sections: [
        {
          heading: "Use the official generator workflow",
          evidenceMode: "source-grounded",
          sourceIds: ["github-motion-canvas", "docs-motion-canvas-quickstart"],
          paragraphs: ["Motion Canvas scenes are TypeScript generator functions that yield timed changes. Start from the official scaffold and keep the first scene to a circle, one point, projection lines, and a synchronized sine trace. Use the project preview to inspect timing, then use the documented exporter for the final output."],
        },
        {
          heading: "Do not confuse interaction with narration",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["github-mafs", "github-jsxgraph"],
          paragraphs: ["Mafs and JSXGraph are useful for learner-controlled mathematical exploration. They are companions when the learner should drag a point or change a parameter, but they do not automatically provide the same authored timeline, narration, and media export contract. Decide whether control belongs to the author, the learner, or both before joining the stacks."],
        },
        {
          heading: "Verify scaffold and export drift",
          evidenceMode: "version-watch",
          sourceIds: ["github-motion-canvas", "docs-motion-canvas-quickstart"],
          paragraphs: ["JavaScript package scaffolds, exporter options, and browser behavior can change. Pin the generated lock file and repository revision, then record the scaffold command, Node version, preview URL, export command, and observed artifact. Re-run this check before treating the lesson command as current."],
        },
      ],
      agentPrompt: "Create a Motion Canvas scene from the pinned official scaffold. Drive a unit-circle point and its sine projection from one signal. Preview the scene, inspect three timestamps, export using the documented path, and report Node, package revisions, commands, output, and any browser-specific issue.",
      verificationGate: ["One signal drives both circle and wave representations.", "The official scaffold and exporter match the pinned documentation.", "Learner interaction and authored narration are assigned deliberately.", "Preview and export evidence are reported separately."],
      checkpoint: {
        question: "When is Motion Canvas the stronger primary track for this course?",
        options: ["Whenever a repository has more stars", "When no timeline is needed", "When TypeScript, browser preview, and a code-controlled timeline are primary constraints", "When every learner interaction must become an MP4"],
        correctIndex: 2,
        explanation: "The selection follows output and workflow constraints. Interactive libraries can complement the timeline when learner control is required.",
      },
    },
    "voice-slides-remotion": {
      kicker: "Add production layers carefully",
      title: "Add voice, slides, and post-production",
      summary: "Extend a verified core scene without allowing narration, plugins, or video composition to obscure the mathematical source of truth.",
      objective: "Produce a narrated or presentation-ready variant while preserving a clean core render and a complete rights record.",
      artifact: "A layered export manifest that links core render, narration, slide or Remotion composition, captions, licenses, and final probe data",
      sections: [
        {
          heading: "Keep extensions outside the mathematical core",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-voiceover", "github-manim-slides", "ffmpeg-general"],
          paragraphs: ["Manim Voiceover and Manim Slides can add narration and live presentation workflows. Preserve a renderable core scene before adding either extension. Store narration text, timing markers, caption files, voice provenance, and slide controls separately so a plugin failure does not erase the checked mathematical animation."],
        },
        {
          heading: "Use Remotion as a composition layer when appropriate",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["github-remotion", "github-remotion-skills", "x-remotion-agent-skills", "ffmpeg-general"],
          paragraphs: ["Remotion can assemble React-based titles, captions, audio, and rendered math footage. Its official Agent Skills post is a workflow signal for Claude Code, while the repository and license are the controlling evidence. Review the commercial license boundary for your organization before treating it as a default production dependency."],
        },
        {
          heading: "Verify agent-skill compatibility claims",
          evidenceMode: "version-watch",
          sourceIds: ["github-remotion-skills", "x-remotion-agent-skills", "x-tobi-manim-skill"],
          paragraphs: ["X posts can expose useful agent-skill patterns, including Remotion skills and a Manim video skill example. Inspect the actual repository support list before claiming Codex compatibility. A project may support Claude Code, Cursor, Windsurf, or Copilot while only exposing OpenAI as an API provider, which is not the same as a Codex installer."],
        },
      ],
      agentPrompt: "Starting from the verified core render, add exactly one production layer: voiceover, slides, or Remotion composition. Preserve the core artifact. Record plugin and media licenses, caption or transcript output, exact export and ffprobe results, and any agent-skill compatibility boundary.",
      verificationGate: ["The core mathematical render remains independently reproducible.", "Narration, music, fonts, and media have explicit rights records.", "Captions or a transcript are included.", "Remotion and agent-skill claims match the repository and license evidence."],
      checkpoint: {
        question: "What does an X post announcing a Claude Code Agent Skill establish?",
        options: ["Automatic Codex compatibility", "Mathematical correctness", "A universal open-source license", "A dated workflow signal that must be checked against the repository and license"],
        correctIndex: 3,
        explanation: "The post establishes an announcement or use example. Compatibility, implementation, and rights require repository evidence.",
      },
    },
    "mathematical-visual-accessibility-qa": {
      kicker: "Inspect truth and access",
      title: "Run mathematical, visual, accessibility, and media QA",
      summary: "Test invariants, sample frames, reduced-motion behavior, captions, crops, codecs, and source boundaries before release.",
      objective: "Create a release report that can reject a beautiful but mathematically wrong, inaccessible, or unlicensed animation.",
      artifact: "QA_REPORT.md with invariant results, frame contact sheet, crop audit, motion alternative, transcript, media probe, and rights status",
      sections: [
        {
          heading: "Test mathematical invariants in code",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-ce", "github-motion-canvas"],
          paragraphs: ["Put analytic relationships in small functions or signals that can be sampled independently of the renderer. Assert key values and tolerances, then inspect exported timeline frames for binding, clipping, and legibility. Keep those as separate evidence unless the exporter records the actual mathematical state, timestamp, and frame path needed to claim an exact match."],
        },
        {
          heading: "Provide a non-motion equivalent",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["w3c-animation-interactions"],
          paragraphs: ["Honor prefers-reduced-motion in the course interface and in web-delivered animation controls. Provide a still sequence, transcript, or direct state change that communicates the same conclusion without requiring continuous motion. Do not autoplay, and never require a precise pointer gesture to reach a mathematical state."],
        },
        {
          heading: "Probe the actual release file",
          evidenceMode: "version-watch",
          sourceIds: ["ffmpeg-general", "github-manim-ce", "github-motion-canvas"],
          paragraphs: ["Use ffprobe or equivalent tooling to record duration, dimensions, frame rate, codec, and audio streams from the final artifact. Render and inspect horizontal and vertical layouts separately; a center crop of the landscape file is not portrait acceptance. Check caption timing, contrast, label overlap, and three mathematical keyframes, then re-run the probe whenever the export pipeline or engine version changes."],
        },
      ],
      agentPrompt: "Run the invariant tests; render 16:9 and 9:16 layouts separately; export five named keyframes from each; assemble contact sheets; test reduced-motion behavior; verify safe areas, captions or transcript; run ffprobe on both final files; and produce a pass, fail, blocked table with artifact paths. Do not treat a center crop as portrait acceptance.",
      verificationGate: ["Every mathematical invariant has code-level evidence.", "Every key assertion points to an inspected frame.", "A reduced-motion equivalent communicates the same conclusion.", "The final media and rights record are inspected, not inferred."],
      checkpoint: {
        question: "Why is a pixel regression insufficient by itself?",
        options: ["It cannot compare images", "It can detect visual change but cannot prove the mathematical relation is correct", "It replaces the renderer", "It always fails on video"],
        correctIndex: 1,
        explanation: "Pixel evidence and mathematical assertions answer different questions. A strong release uses both.",
      },
    },
    "capstone-release-pack": {
      kicker: "Release an argument, not a demo",
      title: "Ship the capstone animation release pack",
      summary: "Combine the scene, repository decision, agent records, tests, frames, accessibility assets, and rights ledger into one reproducible submission.",
      objective: "Release a 45-90 second mathematical animation that an independent reviewer can rebuild, inspect, and challenge.",
      artifact: "A complete capstone release folder with six required evidence groups and an independent review decision",
      sections: [
        {
          heading: "Build from a frozen contract",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-ce", "github-motion-canvas", "openai-codex-use-cases", "anthropic-claude-code-overview"],
          paragraphs: ["Choose Manim Community or Motion Canvas as the primary engine and freeze the scene contract before the final implementation pass. Use one agent as implementer and a separate review pass for story and frames. The release must preserve prompts, accepted changes, rejected suggestions, diffs, commands, and artifact paths."],
        },
        {
          heading: "Assemble six evidence groups",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["github-manim-ce", "github-motion-canvas", "w3c-animation-interactions"],
          paragraphs: ["The release pack contains the mathematical contract, pinned environment, source and rights ledger, agent collaboration record, QA and media evidence, and accessible final delivery. A reviewer should be able to reproduce the core render without paid model calls and understand the conclusion through either motion or the static alternative."],
        },
        {
          heading: "Release only after independent review",
          evidenceMode: "version-watch",
          sourceIds: ["openai-codex-use-cases", "anthropic-claude-code-overview", "w3c-animation-interactions"],
          paragraphs: ["Ask a reviewer who did not author the final scene to rerun the documented path and inspect the selected frames. Record pass, conditional pass, or fail with exact reasons. If versions, licenses, or product workflows have drifted since the source snapshot, update the evidence or keep the release blocked."],
        },
      ],
      agentPrompt: "Prepare the final release pack from the frozen scene contract. Rebuild the core render from a clean environment, run mathematical and media checks, export the accessible alternative, validate all source and license records, and request an independent review. Do not mark complete while any required evidence group is missing.",
      verificationGate: ["A clean environment reproduces the core render.", "All six evidence groups are present and linked.", "The animation passes mathematics, visual, accessibility, media, and rights checks.", "An independent reviewer records a decision and unresolved risk."],
      checkpoint: {
        question: "When is the capstone ready to release?",
        options: ["After all evidence groups pass and an independent reviewer records a decision", "When the final MP4 opens", "When both agents say done", "When the animation receives positive social engagement"],
        correctIndex: 0,
        explanation: "The capstone is an auditable release. Existence, model confidence, and social response do not replace the evidence gates.",
      },
    },
  },
  assessment: [
    {
      id: "engine-boundary",
      question: "Why must Manim Community and ManimGL be documented separately?",
      options: ["Only one is written in Python", "Their commands and APIs are incompatible", "They cannot render equations", "They always use different licenses"],
      correctIndex: 1,
      explanation: "Their related history does not make their code or commands interchangeable.",
    },
    {
      id: "source-hierarchy",
      question: "Which source should control a current installation claim?",
      options: ["An X screenshot", "A star count", "A model-generated summary", "Pinned repository and official documentation"],
      correctIndex: 3,
      explanation: "Social posts can lead to a source, but repository and official documentation control implementation facts.",
    },
    {
      id: "shared-state",
      question: "How should a point, secant line, and slope label remain synchronized?",
      options: ["Give each an independent duration", "Align them by eye", "Drive them from one state variable", "Render each in a separate scene"],
      correctIndex: 2,
      explanation: "Shared state makes the relation inspectable and testable.",
    },
    {
      id: "roles",
      question: "What does the Codex implementer and Claude reviewer split mean?",
      options: ["A recommended independent-review workflow", "A permanent model capability ranking", "Only Codex may edit files", "Only Claude may inspect frames"],
      correctIndex: 0,
      explanation: "The roles are swappable. Independent evidence is the stable requirement.",
    },
    {
      id: "render-proof",
      question: "What does a successful render prove?",
      options: ["The theorem is true", "The animation is accessible", "All media rights are cleared", "The pipeline produced media, but mathematics and communication still require checks"],
      correctIndex: 3,
      explanation: "Rendering is one gate among several independent acceptance layers.",
    },
    {
      id: "reduced-motion",
      question: "What is an acceptable reduced-motion treatment?",
      options: ["Static keyframes or an instant state change with equivalent explanation", "A faster loop", "Autoplay without controls", "Removing the mathematical conclusion"],
      correctIndex: 0,
      explanation: "The alternative preserves the learning outcome without requiring continuous motion.",
    },
    {
      id: "remotion-license",
      question: "How should Remotion licensing be described?",
      options: ["Universally MIT", "A custom license that must be reviewed for the intended use", "Public domain", "Defined by an X post"],
      correctIndex: 1,
      explanation: "The current repository license, not familiarity with the project, controls the rights boundary.",
    },
    {
      id: "release",
      question: "What can block release even when the final video looks correct?",
      options: ["A low repository star count", "Using Python rather than TypeScript", "Missing reproducibility, invariant, accessibility, or rights evidence", "Not posting the result on X"],
      correctIndex: 2,
      explanation: "A world-class release requires evidence across all acceptance layers.",
    },
  ],
  capstone: {
    title: "Explain one mathematical change in 45-90 seconds",
    summary: "Produce a concise animation in Manim Community or Motion Canvas and release it with enough evidence for another person to rebuild and challenge it.",
    scenario: "Choose a concept with a visible state change, such as a secant approaching a tangent, completing the square, a geometric proof, convergence, or a transformation of coordinates. Design for one misconception and one testable conclusion.",
    artifacts: [
      "Mathematical truth and scene contract with storyboard",
      "Repository decision, pinned environment, and exact commands",
      "Codex and Claude task, review, diff, and decision records",
      "Invariant tests, render log, media probe, and sampled keyframes",
      "Transcript or captions plus a reduced-motion static equivalent",
      "Source and license ledger plus independent release review",
    ],
    releaseRule: "All six artifact groups must be present, the final assessment must score at least 80 percent, and the independent review must record no unresolved mathematical, accessibility, or rights failure.",
  },
} as const satisfies MathAnimationCourseCopy;
