import type { MathAnimationCourseCopy } from "../types";

export const MATH_ANIMATION_ZH_HANS_COPY = {
  meta: {
    kicker: "从数学真值到经过检查的关键帧",
    title: "用 Codex 与 Claude 制作数学动画",
    summary: "基于证据选择动画引擎，用场景契约指挥 AI 编码代理，并发布经过数学检验的动画。",
    audience: "适合能阅读基础 Python 或 TypeScript，希望建立可复现动画工作流的教师、研究者、设计师与开发者。",
    prerequisite: "需要 Git、代码编辑器与终端。Manim 主路线还需要 Python、FFmpeg；公式渲染通常需要 LaTeX。",
    level: "从入门到进阶",
    evidenceNote: "仓库能力必须对应到有日期的修订版本、许可证、官方文档与本地冒烟证据。X 帖子只作为实践信号，不能单独证明有效性。",
  },
  ui: {
    course: "课程",
    courseNumber: "第 19 课",
    modules: "模块",
    minutes: "分钟",
    phases: "阶段",
    sources: "来源",
    learningOutcomes: "完成后你能够",
    curriculum: "课程地图",
    evidenceBoundary: "证据边界",
    repositoryLab: "GitHub 仓库证据实验室",
    repositoryLabIntro: "分数衡量的是对本课程任务的适配度，不是普遍质量排名。请打开证据，并根据你的输出目标选择。",
    score: "适配分数",
    verdict: "课程角色",
    bestFor: "最适合",
    limit: "主要限制",
    core: "核心路线",
    advanced: "进阶参考",
    extension: "扩展",
    companion: "配套工具",
    chooseGoal: "选择输出目标",
    goalVideo: "解说型数学视频",
    goalWeb: "交互式网页动画",
    goalTalk: "现场演讲或课堂",
    recommendation: "推荐技术栈",
    start: "开始课程",
    resume: "继续学习",
    progress: "经验证的进度",
    reset: "重置第 19 课",
    resetConfirm: "确定重置第 19 课的产物证据、测验和结课项目进度吗？",
    markComplete: "保存证据并完成",
    completed: "已验证完成",
    artifactEvidence: "产物证据",
    artifactEvidenceHelp: "填写仓库相对路径、commit 或准确的产物收据。",
    verificationEvidence: "验证证据",
    verificationEvidenceHelp: "填写命令与实际结果、渲染路径或已检查关键帧收据。",
    evidenceRequired: "必须通过理解检查，并保存两类证据后才能完成模块。",
    storageNote: "进度只保存在本浏览器中，不会上传。",
    storageUnavailable: "浏览器持久存储不可用，进度只在当前标签页保留。",
    resetDone: "第 19 课进度已重置。",
    resetMemory: "第 19 课已在当前标签页重置，但持久存储不可用。",
    objective: "学习目标",
    practiceArtifact: "实践产物",
    agentPrompt: "代理任务契约",
    copyPrompt: "复制提示词",
    copied: "已复制",
    copyFailed: "复制失败，请手动选择提示词",
    codeDependency: "此文件与可下载 starter 中的版本一致，并依赖相邻的 manim/math_truth.py；不变量测试本身不会导入 Manim。",
    verificationGate: "验收门槛",
    checkpoint: "理解检查",
    checkAnswer: "检查答案",
    correct: "回答正确。再保存产物与验证记录即可完成本模块。",
    incorrect: "尚未通过。请回看证据边界后再试一次。",
    answerCorrect: "回答正确",
    answerIncorrect: "回答错误",
    correctAnswer: "正确答案",
    sourceLedger: "来源台账",
    sourceBoundary: "本来源不能证明什么",
    accessedOn: "访问日期",
    previous: "上一模块",
    next: "下一模块",
    backToCourse: "返回第 19 课",
    allModules: "全部模块",
    finalAssessment: "结课测验",
    submitAssessment: "计算成绩",
    startAssessment: "开始测验",
    retryAssessment: "重新作答",
    bestScore: "最高成绩",
    scoreResult: "测验成绩",
    assessmentPassed: "测验已通过",
    assessmentRetry: "复习错题后再试",
    capstone: "结课项目",
    markCapstone: "记录已审核发布包",
    capstoneComplete: "审核证据已记录",
    capstoneEvidence: "发布审核证据",
    capstoneEvidenceHelp: "概述发布文件夹、准确验证命令、独立审核结论与未解决风险。",
    capstoneAttestationBoundary: "浏览器只记录你填写的证据引用，不能检查文件，也不能独立认证审核结论。",
    allChecksRequired: "全部模块、结课测验、六组产物与一份实质审核收据必须全部具备。",
    motionLab: "单位圆动画实验室",
    play: "播放",
    pause: "暂停",
    scrubber: "动画时间",
    reducedMotion: "系统偏好减少动态效果。请拖动时间轴检查静态关键帧。",
    languageFallback: "本课程的长篇内容已人工审阅英文与简体中文。当前站点语言暂时显示英文课程正文。",
  },
  principles: [
    "先写数学不变量，再写动画指令。",
    "按输出、维护、许可证与可复现性选择仓库，不能只看 star 数。",
    "为 Codex 与 Claude 指定清晰角色，但把角色看作工作流选择，而不是固定的模型能力边界。",
    "只有数学、视觉、无障碍与权利检查都通过，渲染才算完成。",
  ],
  outcomes: [
    "把数学解释转化为带时间、场景节拍与可观察验收条件的场景契约。",
    "使用透明量表评估 Manim Community、ManimGL、Motion Canvas、Remotion 与配套仓库。",
    "在 Manim Community 中制作公式、函数图像、几何图形与保持对象身份的变换。",
    "用 Codex 根据有边界的任务契约实现、测试、渲染并报告仓库改动。",
    "用 Claude 检查分镜、解释、歧义与关键帧，同时保留事实与权限边界。",
    "发布包含来源、许可证、环境、不变量、无障碍与导出证据的可复现动画包。",
  ],
  phases: {
    frame: {
      title: "界定数学故事",
      summary: "先选择输出、评估引擎并写好场景契约，再开始写动画代码。",
    },
    animate: {
      title: "构建有语义的运动",
      summary: "建立可靠的 Manim 环境，保持对象身份，并同步公式、图像与几何。",
    },
    direct: {
      title: "指挥编码代理",
      summary: "建立有边界的 Codex 与 Claude 循环，并在需要网页原生输出时切换到 Motion Canvas。",
    },
    prove: {
      title: "验证并发布",
      summary: "谨慎加入配音、幻灯片或后期，验证数学与无障碍，再提交可审计发布包。",
    },
  },
  modules: {
    "outcome-before-engine": {
      kicker: "安装之前先做决定",
      title: "先定义学习结果，再选择引擎",
      summary: "数学动画是一段按时间展开的论证。先说明学习者需要理解什么，以及用什么证据判断动画正确。",
      objective: "写出一页输出简报，分开数学真值、视觉解释、交付格式与发布约束。",
      artifact: "OUTCOME_BRIEF.md，包含受众、误解、不变量、输出、时长与验收测试",
      sections: [
        {
          heading: "把运动看作解释的一部分",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-ce", "github-motion-canvas"],
          paragraphs: ["Manim Community 用 Python 表达数学对象与变换，Motion Canvas 用 TypeScript 生成器表达有时间的场景。两者都让顺序、时长与对象状态可以在代码中检查。因此，第一个问题不是哪种语法更顺手，而是哪种表示方式更适合揭示你要解释的数学关系。"],
          bullets: ["公式、函数图像与几何优先使用有语义的数学对象。", "网页预览与 TypeScript 集成占主导时，考虑浏览器原生时间轴。", "只有当学习目标同时需要观看与操作时，才把交互图与叙事动画组合。"],
        },
        {
          heading: "先选交付物，再定工具链",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["github-remotion"],
          paragraphs: ["MP4 课程、现场幻灯片与交互网页有不同约束。Remotion 在 React 合成与媒体装配方面很强，但许可证必须根据使用场景单独审阅。比较引擎之前，先写明目标画幅、时长、旁白需求、交互方式与托管边界。"],
        },
        {
          heading: "把公开案例当作待验证假设",
          evidenceMode: "version-watch",
          sourceIds: ["x-minchoi-claude-manim"],
          paragraphs: ["X 帖子可以证明作者公开声称用 Claude 生成了 Manim 场景，却不能证明数学正确、可重复、教学有效或当前仍兼容。把帖子记录为发现信号，然后到仓库与官方文档核验命令、API、版本与许可证。"],
        },
      ],
      agentPrompt: "阅读拟讲主题并生成 OUTCOME_BRIEF.md。写明一个学习者误解、一个数学不变量、一个能揭示不变量的视觉变化、最终交付格式与六条可测试验收条件。在输出约束明确之前，不要选择引擎。",
      verificationGate: ["不观看动画也能独立检查数学主张。", "场景只围绕一个主要学习变化，不堆装饰效果。", "输出格式与目标画幅明确。", "每条验收条件都有可观察的通过或失败结果。"],
      checkpoint: {
        question: "第一次选择仓库时，最应该依据什么？",
        options: ["最高 star 数", "最短安装命令", "预期学习变化与输出约束", "X 帖子中出现的模型"],
        correctIndex: 2,
        explanation: "仓库适配首先来自数学与交付契约。流行度和演示可帮助发现，但不能代替契约。",
      },
    },
    "repository-evidence-lab": {
      kicker: "用固定量表比较",
      title: "依赖仓库之前先评估",
      summary: "用固定版本证据评估能力、维护、许可证、预览、导出与教学适配度。",
      objective: "制作一份可在版本或依赖变化后重复执行的仓库决策记录。",
      artifact: "REPOSITORY_DECISION.md，包含分项评分、固定修订、冒烟结果、许可证与排除理由",
      sections: [
        {
          heading: "分开两个 Manim 家族",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-ce", "github-manimgl", "github-manim-slides", "github-manim-voiceover"],
          paragraphs: ["Manim Community 与 ManimGL 有共同历史，但命令和 API 不兼容。课程把 Manim Community 作为主路线，因为它的社区文档与打包面向一般用户；ManimGL 作为研究 3Blue1Brown 制作体系的进阶参考。Manim Slides 与 Manim Voiceover 是扩展，必须针对实际固定的 Manim Community 版本验证兼容性。"],
        },
        {
          heading: "按任务比较网页与视频管线",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["github-motion-canvas", "github-remotion", "github-mafs", "github-jsxgraph"],
          paragraphs: ["Motion Canvas 提供 TypeScript 场景与时间轴，Remotion 提供基于 React 的视频合成与渲染。Mafs 与 JSXGraph 更适合交互式数学配套内容，而不是完整的解说视频制作管线。高分只表示适合本课程契约，不表示某个项目普遍优于其他项目。"],
        },
        {
          heading: "只固定真正测试过的版本",
          evidenceMode: "version-watch",
          sourceIds: ["github-manim-ce", "github-manimgl", "github-motion-canvas", "github-remotion"],
          paragraphs: ["记录不可变的 commit SHA 或 release tag、该修订下的许可证、安装命令、操作系统、运行时版本与实际检查过的输出。如果 LaTeX、浏览器、编码器或原生库导致渲染受阻，就报告阻塞，不能把文档检查升级成渲染成功。"],
        },
      ],
      agentPrompt: "按照课程量表评估每个候选仓库。每一行给出固定 commit 或 release、许可证证据、准确冒烟命令、观察到的输出、失败边界与最适用场景。绝不从 star 或 X 帖子推断有效性。",
      verificationGate: ["Manim Community 与 ManimGL 不出现在同一命令路径。", "每个仓库都有版本锚点与许可证边界。", "渲染成功、仅验证与受阻三种结果明确区分。", "建议对应具体输出与学习者。"],
      checkpoint: {
        question: "README 可解析且测试通过，但因缺少 LaTeX 没有渲染视频，正确的冒烟状态是什么？",
        options: ["仅验证，并记录渲染阻塞", "已渲染", "已证明有效", "自动排除"],
        correctIndex: 0,
        explanation: "文档或代码验证仍有价值，但不能证明已经渲染。缺失依赖必须进入边界。",
      },
    },
    "scene-contract-storyboard": {
      kicker: "让意图可以执行",
      title: "提示代理之前先写场景契约",
      summary: "把数学论证转化为场景节拍、状态变化、不变量与关键帧验收条件。",
      objective: "创建一份编码代理能够实现、独立审核者能够证伪的分镜。",
      artifact: "SCENE_CONTRACT.md 与六帧分镜，包含时间、旁白、状态与检查",
      sections: [
        {
          heading: "给仓库持续有效的指令",
          evidenceMode: "source-grounded",
          sourceIds: ["github-3b1b-videos-claude", "anthropic-claude-memory"],
          paragraphs: ["3Blue1Brown 的 videos 仓库包含 Claude Code 项目说明，并明确它使用 ManimGL。Anthropic 也把仓库级说明文件记录为持续项目上下文。你的项目同样应该在版本控制中写明引擎、命令、禁止混用的 API、渲染目标与验证顺序。"],
        },
        {
          heading: "把旁白转换为状态变化",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["openai-codex-use-cases"],
          paragraphs: ["有效的场景契约会为每个节拍写明起始状态、变化变量、视觉证据与结束状态。代理必须知道哪个对象持续存在、哪个标签更新、镜头何时移动，以及旁白继续前必须出现什么事实。这是一份可测试的实现契约，不是情绪板。"],
        },
        {
          heading: "编码前先攻击歧义",
          evidenceMode: "version-watch",
          sourceIds: ["openai-codex-use-cases", "anthropic-claude-memory"],
          paragraphs: ["让一次独立审核先找出流畅、直观、优雅、明显等未定义词，再用时间、空间、数学与无障碍条件替换它们。模型行为会变化，长期有效的资产是明确契约与测试，而不是某次碰巧奏效的提示词。"],
        },
      ],
      agentPrompt: "把数学解释写成场景契约。每个节拍列出时间范围、旁白、持续对象、状态变化、镜头规则、数学不变量与一条关键帧验收条件。标记所有模糊形容词，并要求可测量替代项。",
      verificationGate: ["每个节拍都改变命名状态或推进论证。", "需要保持的对象在变换中保留身份。", "旁白不会在视觉证据出现前先宣布结果。", "所有模糊形容词都替换为可观察规则。"],
      checkpoint: {
        question: "哪条指令最容易正确实现？",
        options: ["让切线过渡优雅", "使用漂亮的节奏", "直观地解释极限", "在 1.2 秒内把 h 从 2.0 移到 0.1，同时显示斜率与 2+h 的误差不超过 0.01"],
        correctIndex: 3,
        explanation: "它明确了状态、时间、依赖与容差。其他选项把验收条件留给代理猜测。",
      },
    },
    "manim-environment-first-scene": {
      kicker: "先复现，再扩展",
      title: "建立 Manim 环境并渲染第一个场景",
      summary: "建立固定的 Python 环境，渲染一段低清预览，并记录所有原生依赖。",
      objective: "从干净检出版本渲染最小 Manim Community 场景，并保留重复执行所需的环境证据。",
      artifact: "可复现的首场景文件夹，包含锁文件、环境报告、命令日志、预览视频与已检查静帧",
      sections: [
        {
          heading: "严格遵循 Community 快速开始",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-ce", "docs-manim-quickstart"],
          paragraphs: ["从固定 release 对应的 Manim Community 官方安装与快速开始文档出发。第一个场景只保留标题、一个图形与一个有语义的变换。在加入 LaTeX、配音、插件、自定义字体或镜头运动之前，先用文档提供的命令和低清参数完成预览。"],
        },
        {
          heading: "记录完整原生工具链",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["docs-manim-quickstart", "ffmpeg-general"],
          paragraphs: ["Python 包成功只是一层。记录 Python、Manim、FFmpeg、操作系统与 LaTeX 版本，并保存准确渲染命令与产物元数据。FFmpeg 把帧与媒体流转换为可检查交付物，因此编码器与帧率证据应与 Python 锁文件放在一起。"],
        },
        {
          heading: "发现版本漂移就停下",
          evidenceMode: "version-watch",
          sourceIds: ["github-manim-ce"],
          paragraphs: ["当生成代码使用未知类或命令时，先对照固定版本文档，再考虑改代码。不能让代理偷偷从 Manim Community 切换到 ManimGL，也不能自动安装最新 release。记录清楚的不兼容结果，比无法重复的本地成功更有价值。"],
        },
      ],
      agentPrompt: "检查仓库说明与现有环境。创建最小 Manim Community 场景，固定依赖，渲染低清预览，导出一张代表性静帧，并报告准确命令、输出路径、版本与任何受阻的原生依赖。",
      verificationGate: ["干净环境能根据记录的依赖文件安装。", "日志中的命令生成声明的预览路径。", "场景只从 Manim Community 导入。", "至少一张渲染静帧经过视觉检查，而不是只确认文件存在。"],
      checkpoint: {
        question: "Manim Community 项目中出现 ManimGL 专用 API 时应该怎么办？",
        options: ["升级全部依赖", "停止，确认 API 不匹配，并按固定版本 Community 文档重写", "在同一环境安装 ManimGL", "只要能解析就保留"],
        correctIndex: 1,
        explanation: "两个 Manim 家族不兼容。应保留已选引擎，并根据其固定文档修复代码。",
      },
    },
    "transformations-camera-continuity": {
      kicker: "保留学习者正在追踪的对象",
      title: "制作变换与镜头连续性",
      summary: "明确对象身份、注意力与空间连续性，让运动承载推理，而不是隐藏剪辑。",
      objective: "制作一段变换，让观看者能指出什么持续存在、什么发生变化，以及镜头为什么移动。",
      artifact: "20 到 40 秒的变换场景、对象身份表与三张已检查关键帧",
      sections: [
        {
          heading: "变换语义部件，而不是替换截图",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-ce"],
          paragraphs: ["Manim Community 提供能够保持数学对象关系的变换。代数场景要匹配前后继续存在的符号，几何场景要在状态改变时保留同一个点、线或区域对象。学习者不应在每次动画调用后重新寻找对象。"],
        },
        {
          heading: "每个镜头运动都要有教学任务",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["github-manimgl"],
          paragraphs: ["3Blue1Brown 的制作体系展示了丰富的镜头与场景语言，但模仿风格不是学习目标。只有在揭示尺度、保留空间上下文或引导到下一个依赖关系时才移动镜头。把每个镜头运动的理由写进场景契约，并删除不能改变理解的运动。"],
        },
        {
          heading: "在关键帧检查连续性",
          evidenceMode: "version-watch",
          sourceIds: ["github-manim-ce", "github-manimgl"],
          paragraphs: ["生成代码可能成功渲染，却替换了对象、重叠了标签，或在没有解释的情况下切换镜头。为每个主要变换导出前、中、后三张静帧，对照对象身份、阅读顺序、安全边距与公式状态后再接受。"],
        },
      ],
      agentPrompt: "只使用固定引擎实现变换分镜。为每个持续对象与镜头运动添加说明。渲染低清版本，导出起始、中点与结束帧，并报告身份断裂、重叠、无解释剪辑或无教学目的镜头运动。",
      verificationGate: ["同一语义对象在预定变换中持续存在。", "所有镜头运动都有记录的学习目的。", "标签在目标画幅裁切中仍可读。", "起始、中点与结束帧符合分镜。"],
      checkpoint: {
        question: "什么时候应该移动镜头？",
        options: ["场景显得慢时", "每个公式之后", "代理建议缩放时", "当运动能揭示尺度、上下文或下一个依赖关系时"],
        correctIndex: 3,
        explanation: "镜头运动由解释任务决定，节奏本身不能证明它有教学价值。",
      },
    },
    "equations-graphs-geometry": {
      kicker: "让多种表示共享同一状态",
      title: "同步公式、函数图像与几何",
      summary: "用共享变量驱动多种视觉表示，并在采样时刻检验数学关系。",
      objective: "制作割线趋近切线的场景，使图像、点、直线、公式与数值斜率始终同步。",
      artifact: "割线趋近切线场景、不变量测试与五个采样帧记录",
      sections: [
        {
          heading: "用一个状态变量作为真值来源",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-ce", "docs-manim-quickstart"],
          paragraphs: ["ValueTracker 可以让移动点、割线、差值标签、数值斜率与镜头条件共同依赖同一个 h。这样不会出现多个独立动画只是视觉上大致同步的情况。把数学函数放在视觉回调之外，并在场景和不变量测试中复用。"],
        },
        {
          heading: "检验关系，而不只比较像素",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["github-manim-ce"],
          paragraphs: ["对于 f(x)=x^2 与 a=1，h 非零时割线斜率为 2+h。在五个检查点采样 h，并断言显示数值、直线斜率与解析表达式在给定容差内一致。帧哈希可以发现视觉漂移，却不能证明数学关系正确。"],
        },
        {
          heading: "让数值边界可见",
          evidenceMode: "version-watch",
          sourceIds: ["docs-manim-quickstart"],
          paragraphs: ["动画可以让 h 接近 0，但不能把割线计算设置为分母为 0。视觉证据出现后再给出极限结论，明确标示近似值，并说明渲染帧之间不代表无限连续。把浮点与插值容差记录在测试输出中。"],
        },
      ],
      agentPrompt: "根据 SCENE_CONTRACT.md 实现割线趋近切线场景。让所有依赖视觉共用一个 h tracker。在 h 为 2、1、0.5、0.1、0.08 时添加测试，并用负 h 样本验证双侧代数。渲染并导出时间轴采样帧。除非收据记录实际 h、时间戳与路径形成精确对应，否则把测试数值与帧路径作为两组独立证据报告。",
      verificationGate: ["点、割线、标签与斜率共享一个状态来源。", "解析不变量在所有采样值通过。", "场景不会用 h=0 做除法。", "近似与极限符号清楚区分。"],
      checkpoint: {
        question: "哪种方法最能检查割线场景正确性？",
        options: ["完整观看一次视频", "只确认 MP4 存在", "在采样 h 值断言斜率关系，并另行检查时间轴采样帧", "只比较文件大小"],
        correctIndex: 2,
        explanation: "数学断言检验关系，时间轴采样帧检查绑定与可读性；只有收据记录实际 h 与时间戳时，二者才能称为精确匹配证据。",
      },
    },
    "codex-implementation-loop": {
      kicker: "让编码循环可审计",
      title: "用 Codex 完成实现、测试与渲染证据",
      summary: "把场景契约变成有边界的仓库任务，检查 diff，并要求交接包含命令与产物。",
      objective: "完成 Codex 优先的实现循环，只修改范围内的场景文件，并报告可验证输出，而不是成功叙事。",
      artifact: "Codex 任务包，包含提示、计划、diff、命令日志、测试输出、渲染路径与未解决边界",
      sections: [
        {
          heading: "给 Codex 仓库级任务契约",
          evidenceMode: "source-grounded",
          sourceIds: ["openai-codex-use-cases", "github-manim-ce"],
          paragraphs: ["强任务契约会写明仓库、引擎、场景文件、数学不变量、允许文件、禁止改动、必跑命令与交接格式。要求 Codex 实现前读取本地说明与固定版本文档，减少 API 混用，并让审核范围与实际 diff 对齐。"],
        },
        {
          heading: "把实现与验收分开",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["openai-model-guidance"],
          paragraphs: ["让 Codex 实现并运行确定性检查，然后根据原始场景契约审核 diff 与产物。类型检查通过不等于动画已渲染，渲染成功也不等于数学已验证。交接表必须分开代码、测试、渲染、关键帧检查与已知缺口。"],
        },
        {
          heading: "重新核验当前产品行为",
          evidenceMode: "version-watch",
          sourceIds: ["openai-codex-use-cases", "openai-model-guidance"],
          paragraphs: ["Codex 界面与模型指南会持续变化。课程提示应围绕任务契约、仓库证据与验证，而不是依赖临时按钮或模型名称。教授任何产品特定操作之前，都要对照当前 OpenAI 官方文档。"],
        },
      ],
      agentPrompt: "阅读 AGENTS.md 与 SCENE_CONTRACT.md。只实现指定场景与不变量测试。任务没有明确允许时不要改依赖。渲染低清预览，导出三张关键帧，运行列出的检查并审核 diff，最后用表格交接命令、退出结果、产物路径与剩余不确定性。",
      verificationGate: ["diff 只涉及允许文件。", "交接分开测试、渲染与视觉检查。", "每个声明的产物路径真实存在。", "未解决依赖或视觉歧义保持可见。"],
      checkpoint: {
        question: "哪种交接可以接受？",
        options: ["diff、准确命令、退出结果、产物路径、已检查帧与剩余缺口", "已完成，动画看起来不错", "TypeScript 已通过，所以视频正确", "模型声称全部要求通过"],
        correctIndex: 0,
        explanation: "只有另一个人能够定位并复核证据，仓库任务才算可审计。",
      },
    },
    "claude-direction-review": {
      kicker: "引入第二种视角",
      title: "用 Claude 检查导演逻辑、歧义与关键帧",
      summary: "让 Claude 根据同一契约审阅解释与画面，再逐条验证它建议的代码与事实改动。",
      objective: "完成 Claude 优先的独立审阅，发现叙事与沟通风险，但不把数学真值或仓库权限交给审核者。",
      artifact: "Claude 审核包，包含分镜批评、歧义清单、关键帧意见、接受和拒绝的变更及验证状态",
      sections: [
        {
          heading: "持久保存项目边界",
          evidenceMode: "source-grounded",
          sourceIds: ["anthropic-claude-code-overview", "anthropic-claude-memory", "github-3b1b-videos-claude"],
          paragraphs: ["在 CLAUDE.md 中写明引擎、本地命令、数学不变量、视觉词汇、受保护文件与证据要求。3Blue1Brown 仓库的价值在于明确了 ManimGL 上下文，但它不是 Manim Community 的即插即用说明。应改写项目契约，不能复制引擎专用命令。"],
        },
        {
          heading: "独立审核故事与画面",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["x-minchoi-claude-manim", "x-cintas-claude-pythagoras", "x-dhruv-math-animation-thread"],
          paragraphs: ["公开帖子记录了创作者让 Claude 生成 Manim 数学动画的实践，包括神经网络、勾股定理、球面定理、距离公式与黎曼和。它们不能证明生成数学正确或可复现。把分镜与采样帧交给 Claude，询问学习者可能误读之处，并要求每条意见指向时间、对象或句子。"],
        },
        {
          heading: "保持模型角色可交换",
          evidenceMode: "version-watch",
          sourceIds: ["anthropic-claude-code-overview", "x-minchoi-claude-manim", "x-cintas-claude-pythagoras", "x-dhruv-math-animation-thread"],
          paragraphs: ["课程建议 Codex 负责实现、Claude 负责导演审核，是因为这种分工能形成独立审查循环，并不是模型排行榜或永久能力边界。你可以交换角色，但实现者与审核者仍须使用同一场景契约，并分别提交证据。"],
        },
      ],
      agentPrompt: "只审阅场景契约、旁白与三张采样帧，不修改代码。找出学习者最早可能形成错误推断的位置。每条问题都引用时间或画面，说明数学或视觉风险，提出最小修复，并标示哪些内容需要学科专家核验。",
      verificationGate: ["每条批评都指向具体场景元素。", "所有事实改动建议都对照数学不变量检查。", "不同 Manim 家族的命令不互相复制。", "接受与拒绝的审核建议都有记录。"],
      checkpoint: {
        question: "为什么课程要分开实现者与审核者角色？",
        options: ["为了避免检查两个模型的工作", "为了建立独立证据循环，而不是宣称固定模型排名", "因为 Claude 不能写代码", "因为 Codex 不能审阅解释"],
        correctIndex: 1,
        explanation: "角色分工是工作流设计。能力与产品会变化，稳定的是契约与独立验证。",
      },
    },
    "motion-canvas-web-track": {
      kicker: "当浏览器就是媒介时切换路线",
      title: "用 Motion Canvas 构建 TypeScript 路线",
      summary: "当 TypeScript、即时网页预览或网页合成是主要约束时，使用浏览器原生场景与生成器时间轴。",
      objective: "用 Motion Canvas 制作单位圆场景，并说明交互数学库什么时候应保持为独立配套工具。",
      artifact: "Motion Canvas 单位圆场景、预览记录、导出记录与引擎决策说明",
      sections: [
        {
          heading: "使用官方生成器工作流",
          evidenceMode: "source-grounded",
          sourceIds: ["github-motion-canvas", "docs-motion-canvas-quickstart"],
          paragraphs: ["Motion Canvas 场景是通过 yield 产生时间变化的 TypeScript 生成器函数。从官方脚手架开始，第一个场景只保留圆、一个点、投影线与同步的正弦轨迹。先用项目预览检查时间，再用文档规定的导出器生成最终输出。"],
        },
        {
          heading: "不要混淆交互与叙事",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["github-mafs", "github-jsxgraph"],
          paragraphs: ["Mafs 与 JSXGraph 适合让学习者控制参数并探索数学关系。它们是很好的配套工具，却不会自动提供相同的作者时间轴、旁白与媒体导出契约。组合技术栈之前，先决定控制权属于作者、学习者，还是两者。"],
        },
        {
          heading: "验证脚手架与导出器漂移",
          evidenceMode: "version-watch",
          sourceIds: ["github-motion-canvas", "docs-motion-canvas-quickstart"],
          paragraphs: ["JavaScript 脚手架、导出选项与浏览器行为都会变化。固定生成后的 lockfile 与仓库修订，记录脚手架命令、Node 版本、预览地址、导出命令与实际产物。把课程命令写成当前事实之前，必须重跑检查。"],
        },
      ],
      agentPrompt: "根据固定版本官方脚手架创建 Motion Canvas 场景。让单位圆点与正弦投影共用一个 signal。预览场景并检查三个时间点，按文档路径导出，并报告 Node、包版本、命令、输出与浏览器问题。",
      verificationGate: ["圆与正弦表示由一个 signal 驱动。", "官方脚手架与导出器符合固定文档。", "学习者交互与作者叙事的控制权明确分配。", "预览与导出证据分别报告。"],
      checkpoint: {
        question: "什么时候 Motion Canvas 更适合作为本课程主路线？",
        options: ["仓库 star 更多时", "完全不需要时间轴时", "TypeScript、浏览器预览与代码控制时间轴是主要约束时", "所有学习者交互都必须转为 MP4 时"],
        correctIndex: 2,
        explanation: "选择取决于输出与工作流约束。需要学习者控制时，可加入交互库作为配套。",
      },
    },
    "voice-slides-remotion": {
      kicker: "谨慎添加制作层",
      title: "加入配音、幻灯片与后期合成",
      summary: "扩展已验证的核心场景，同时避免旁白、插件或视频合成遮蔽数学真值来源。",
      objective: "制作适合解说或展示的版本，并保留干净核心渲染与完整权利记录。",
      artifact: "分层导出清单，连接核心渲染、旁白、幻灯片或 Remotion 合成、字幕、许可证与媒体探测结果",
      sections: [
        {
          heading: "把扩展留在数学核心之外",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-voiceover", "github-manim-slides", "ffmpeg-general"],
          paragraphs: ["Manim Voiceover 与 Manim Slides 可以加入旁白与现场演示能力。在使用扩展之前先保留一份可独立渲染的核心场景。分别存储旁白文本、时间标记、字幕文件、声音来源与幻灯片控制，使插件故障不会抹去已验证的数学动画。"],
        },
        {
          heading: "需要时把 Remotion 用作合成层",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["github-remotion", "github-remotion-skills", "x-remotion-agent-skills", "ffmpeg-general"],
          paragraphs: ["Remotion 可以用 React 组合标题、字幕、音频与数学动画素材。官方 Agent Skills 帖子是 Claude Code 工作流信号，真正控制事实的是仓库与许可证。Remotion 使用自定义许可证，在把它作为组织默认生产依赖之前，必须审查适用的商业边界。"],
        },
        {
          heading: "核验 Agent Skill 的兼容声明",
          evidenceMode: "version-watch",
          sourceIds: ["github-remotion-skills", "x-remotion-agent-skills", "x-tobi-manim-skill"],
          paragraphs: ["X 帖子能够帮助发现 Remotion Skill 与 Manim video skill 等实践模式。声称支持 Codex 之前必须查看实际仓库支持列表。一个项目可能支持 Claude Code、Cursor、Windsurf 或 Copilot，同时只提供 OpenAI API provider，这并不等于提供 Codex 安装器。"],
        },
      ],
      agentPrompt: "从已验证核心渲染出发，只添加一种制作层：配音、幻灯片或 Remotion 合成。保留核心产物。记录插件与媒体许可证、字幕或 transcript、准确导出与 ffprobe 结果，以及 Agent Skill 兼容边界。",
      verificationGate: ["核心数学渲染仍可独立复现。", "旁白、音乐、字体与媒体有明确权利记录。", "包含字幕或 transcript。", "Remotion 与 Agent Skill 声明符合仓库和许可证证据。"],
      checkpoint: {
        question: "一条宣布 Claude Code Agent Skill 的 X 帖子能证明什么？",
        options: ["自动支持 Codex", "数学正确", "通用开源许可证", "有日期的工作流信号，仍须用仓库与许可证核验"],
        correctIndex: 3,
        explanation: "帖子能证明公告或使用案例。兼容、实现与权利需要仓库证据。",
      },
    },
    "mathematical-visual-accessibility-qa": {
      kicker: "同时检查真值与可访问性",
      title: "完成数学、视觉、无障碍与媒体 QA",
      summary: "发布前检查不变量、采样帧、reduced-motion、字幕、裁切、编码与来源边界。",
      objective: "制作一份能够拒绝数学错误、无障碍失败或权利不清动画的发布报告，即使动画本身很漂亮。",
      artifact: "QA_REPORT.md，包含不变量、关键帧总览、裁切审核、静态替代、transcript、媒体探测与权利状态",
      sections: [
        {
          heading: "在代码中检验数学不变量",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-ce", "github-motion-canvas"],
          paragraphs: ["把解析关系放入可以独立于渲染器采样的小函数或 signal。对关键值与容差做断言，再检查导出的时间轴帧是否正确绑定、裁切与可读。除非导出器记录实际数学状态、时间戳与帧路径，否则两者应保留为独立证据，不能宣称精确匹配。"],
        },
        {
          heading: "提供不依赖连续运动的等价内容",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["w3c-animation-interactions"],
          paragraphs: ["课程界面与网页动画控件都要尊重 prefers-reduced-motion。提供静帧序列、transcript 或即时状态变化，在不要求持续运动的情况下表达同一结论。禁止自动播放，也不能要求精细指针手势才能到达某个数学状态。"],
        },
        {
          heading: "探测实际发布文件",
          evidenceMode: "version-watch",
          sourceIds: ["ffmpeg-general", "github-manim-ce", "github-motion-canvas"],
          paragraphs: ["使用 ffprobe 或等效工具记录最终产物的时长、尺寸、帧率、编码与音频流。横版与竖版必须分别响应式渲染和检查，不能把横版居中裁切当成竖版验收。再检查字幕时间、对比度、标签重叠与三张数学关键帧；导出管线或引擎版本变化后必须重跑探测。"],
        },
      ],
      agentPrompt: "运行不变量测试；分别渲染 16:9 与 9:16 版式并各自导出五张命名关键帧；生成关键帧总览；测试 reduced-motion；检查安全区、字幕或 transcript；对两个最终文件运行 ffprobe；生成通过、失败、受阻表格及产物路径。不能把居中裁切当成竖版验收。",
      verificationGate: ["每个数学不变量都有代码级证据。", "每个关键主张都指向已检查帧。", "静态替代能表达相同结论。", "最终媒体与权利记录经过检查，而不是推断。"],
      checkpoint: {
        question: "为什么只有像素回归测试还不够？",
        options: ["它无法比较图片", "它能发现视觉变化，却不能证明数学关系正确", "它会代替渲染器", "它对视频必然失败"],
        correctIndex: 1,
        explanation: "像素证据与数学断言回答不同问题，可靠发布需要两者。",
      },
    },
    "capstone-release-pack": {
      kicker: "发布论证，不是发布演示",
      title: "提交结课动画发布包",
      summary: "把场景、仓库决策、代理记录、测试、关键帧、无障碍资产与权利台账放入一个可复现提交。",
      objective: "发布一段 45 到 90 秒的数学动画，使独立审核者能够重建、检查并挑战它。",
      artifact: "完整结课发布文件夹，包含六组必需证据与独立审核结论",
      sections: [
        {
          heading: "根据冻结契约构建",
          evidenceMode: "source-grounded",
          sourceIds: ["github-manim-ce", "github-motion-canvas", "openai-codex-use-cases", "anthropic-claude-code-overview"],
          paragraphs: ["选择 Manim Community 或 Motion Canvas 作为主引擎，并在最终实现前冻结场景契约。让一个代理担任实现者，再进行独立的故事与画面审核。发布包必须保留提示、接受的改动、拒绝的建议、diff、命令与产物路径。"],
        },
        {
          heading: "汇总六组证据",
          evidenceMode: "engineering-synthesis",
          sourceIds: ["github-manim-ce", "github-motion-canvas", "w3c-animation-interactions"],
          paragraphs: ["发布包包含数学与场景契约、固定环境、来源与权利台账、代理协作记录、QA 与媒体证据、可访问的最终交付。审核者应能在不调用付费模型的情况下复现核心渲染，并通过运动版本或静态替代理解结论。"],
        },
        {
          heading: "独立审核通过后再发布",
          evidenceMode: "version-watch",
          sourceIds: ["openai-codex-use-cases", "anthropic-claude-code-overview", "w3c-animation-interactions"],
          paragraphs: ["请没有编写最终场景的审核者重跑记录路径，并检查选定关键帧。以通过、有条件通过或失败记录准确理由。如果来源快照之后版本、许可证或产品工作流已经漂移，就更新证据或继续阻塞发布。"],
        },
      ],
      agentPrompt: "根据冻结场景契约准备最终发布包。从干净环境重建核心渲染，运行数学与媒体检查，导出无障碍替代，核验全部来源与许可证记录，并请求独立审核。任何必需证据组缺失时都不能标记完成。",
      verificationGate: ["干净环境可以复现核心渲染。", "六组证据全部存在并互相链接。", "动画通过数学、视觉、无障碍、媒体与权利检查。", "独立审核者记录决定与未解决风险。"],
      checkpoint: {
        question: "什么时候结课项目可以发布？",
        options: ["所有证据组通过且独立审核者记录决定后", "最终 MP4 能打开时", "两个代理都说完成时", "社交平台反馈积极时"],
        correctIndex: 0,
        explanation: "结课项目是可审计发布。文件存在、模型信心与社交反馈都不能代替证据门槛。",
      },
    },
  },
  assessment: [
    {
      id: "engine-boundary",
      question: "为什么必须分开记录 Manim Community 与 ManimGL？",
      options: ["只有一个使用 Python", "它们的命令和 API 不兼容", "它们不能渲染公式", "它们一定使用不同许可证"],
      correctIndex: 1,
      explanation: "相关历史并不代表代码与命令可以互换。",
    },
    {
      id: "source-hierarchy",
      question: "哪类来源应该控制当前安装声明？",
      options: ["X 截图", "star 数", "模型生成摘要", "固定仓库修订与官方文档"],
      correctIndex: 3,
      explanation: "社交帖子可引导到来源，但实现事实由仓库与官方文档控制。",
    },
    {
      id: "shared-state",
      question: "点、割线与斜率标签如何保持同步？",
      options: ["分别设置相同动画时长", "目测对齐", "由一个状态变量共同驱动", "放在不同场景渲染"],
      correctIndex: 2,
      explanation: "共享状态让关系可以检查与测试。",
    },
    {
      id: "roles",
      question: "Codex 实现者与 Claude 审核者的分工意味着什么？",
      options: ["推荐的独立审核工作流", "永久的模型能力排名", "只有 Codex 能编辑文件", "只有 Claude 能检查关键帧"],
      correctIndex: 0,
      explanation: "角色可以交换，独立证据才是稳定要求。",
    },
    {
      id: "render-proof",
      question: "渲染成功能够证明什么？",
      options: ["定理为真", "动画无障碍", "全部媒体权利已清理", "管线生成了媒体，但数学与沟通仍需检查"],
      correctIndex: 3,
      explanation: "渲染只是多个独立验收层之一。",
    },
    {
      id: "reduced-motion",
      question: "什么是合格的 reduced-motion 处理？",
      options: ["用静态关键帧或即时状态变化提供等价解释", "播放更快的循环", "无控件自动播放", "删除数学结论"],
      correctIndex: 0,
      explanation: "替代内容在不要求持续运动时保留学习结果。",
    },
    {
      id: "remotion-license",
      question: "课程应如何描述 Remotion 许可证？",
      options: ["通用 MIT", "自定义许可证，必须针对用途审查", "公有领域", "由 X 帖子决定"],
      correctIndex: 1,
      explanation: "权利边界由当前仓库许可证控制。",
    },
    {
      id: "release",
      question: "即使最终视频看起来正确，什么仍可阻止发布？",
      options: ["仓库 star 较少", "使用 Python 而不是 TypeScript", "缺少可复现、不变量、无障碍或权利证据", "没有把结果发布到 X"],
      correctIndex: 2,
      explanation: "高质量发布需要所有验收层都有证据。",
    },
  ],
  capstone: {
    title: "用 45 到 90 秒解释一个数学变化",
    summary: "使用 Manim Community 或 Motion Canvas 制作简洁动画，并提供足够证据让另一位审核者重建和质疑。",
    scenario: "选择一个状态变化可见的概念，例如割线趋近切线、配方法、几何证明、收敛或坐标变换。围绕一个常见误解与一个可测试结论设计。",
    artifacts: [
      "数学真值、场景契约与分镜",
      "仓库决策、固定环境与准确命令",
      "Codex 与 Claude 的任务、审核、diff 与决策记录",
      "不变量测试、渲染日志、媒体探测与采样关键帧",
      "字幕或 transcript，以及 reduced-motion 静态等价内容",
      "来源与许可证台账，以及独立发布审核",
    ],
    releaseRule: "六组产物必须全部存在，结课测验至少达到 80%，独立审核中不能留下未解决的数学、无障碍或权利失败。",
  },
} as const satisfies MathAnimationCourseCopy;
