import type { AiTutorCourseCopy } from "../types";

export const AI_TUTOR_EN_COPY = {
  meta: {
    title: "AI Tutor & Learning Systems Engineering",
    kicker: "Course 13 · Design for learning, not conversation",
    summary: "Engineer an AI tutor as an evidence-driven learning system: define what should be learned, diagnose carefully, adapt support, validate assessment signals, model uncertainty, test learning impact, and keep teachers in control.",
    audience: "For educators, instructional designers, learning engineers, product managers, researchers, and developers building or evaluating AI-supported learning.",
    prerequisite: "You should be able to read a product or research specification. No machine-learning implementation is required.",
    level: "Intermediate to advanced",
    duration: "8 modules, about 7.5 hours",
    startCta: "Start with the learning contract",
    resumeCta: "Resume the system design",
    englishOnly: "Course 13 is currently taught in English. The site shell remains in your selected language. Course copy is separated from the application logic so additional translations can be added later.",
    evidenceNote: "This course distinguishes design proposals, observed learner evidence, model inferences, and causal outcome evidence. A plausible tutor response is never treated as proof of learning.",
  },
  ui: {
    course: "Course 13",
    modules: "Modules",
    module: "Module",
    minutes: "minutes",
    phases: "Design phases",
    allModules: "All eight modules",
    curriculumTitle: "Build the learning loop in dependency order",
    curriculumIntro: "Each module produces one reviewable artifact. Together they form a minimum viable tutor specification that a teacher, researcher, and engineer can challenge before implementation.",
    learningOutcomes: "Learning outcomes",
    learningOutcomesTitle: "What you will be able to engineer",
    conceptMap: "Course concept map",
    relation: "System relationship",
    courseProgress: "Course progress",
    browserStorageNote: "Your Course 13 progress is saved only in this browser on this device.",
    storageUnavailable: "Progress cannot be saved right now. Keep this tab open to retain session progress, or enable site storage and reload.",
    resetProgress: "Reset Course 13 progress",
    resetConfirm: "Reset only Course 13 progress in this browser? Other course data will be preserved.",
    resetDone: "Course 13 progress was reset. Other course records were preserved.",
    resetDoneMemory: "Course 13 session progress was reset. Browser storage remains unavailable.",
    markModuleComplete: "Mark module complete",
    markModuleIncomplete: "Mark module incomplete",
    markedModuleComplete: "Module complete",
    moduleComplete: "You recorded this module as complete.",
    moduleIncomplete: "Complete the workshop and checkpoint, then record the module.",
    artifactAttestation: "I completed and reviewed this module's artifact.",
    artifactAttestationHelp: "Only this check is saved. Do not put learner-identifying content in browser storage.",
    finalAssessment: "Final design check",
    finalAssessmentTitle: "Can you protect the learning inference?",
    finalAssessmentIntro: "Answer one question from each module. Pass with at least 6 of 8 correct and a correct answer to the teacher-oversight question.",
    startAssessment: "Start the design check",
    checkAnswer: "Check answer",
    correct: "Correct",
    incorrect: "Not yet",
    nextQuestion: "Next question",
    finishAssessment: "Finish assessment",
    assessmentPassed: "Design check passed",
    assessmentNotPassed: "Design check not yet passed",
    retryAssessment: "Try the design check again",
    criticalBoundary: "Teacher-oversight boundary",
    capstone: "Capstone design review",
    capstoneArtifacts: "Required artifact packet",
    capstoneReview: "Review questions",
    capstoneInstructions: "Check each artifact only when it exists and another person could inspect it. Completion is a design record, not evidence that the tutor improves learning.",
    markCapstoneComplete: "Record capstone design complete",
    capstoneComplete: "Capstone design recorded",
    systemContract: "System contract",
    systemContractTitle: "Trace the decision before you automate it",
    signal: "Observed signal",
    inference: "Bounded inference",
    action: "Instructional action",
    outcomeEvidence: "Outcome evidence",
    stopRule: "Stop or escalate",
    objective: "Learning objective",
    objectiveTitle: "What you will be able to do",
    workshop: "Engineering workshop",
    steps: "Build steps",
    deliverables: "Deliverables",
    reviewGate: "Review gate",
    safetyBoundary: "Safety boundary",
    checkpoint: "Checkpoint",
    takeaway: "Engineering takeaway",
    sources: "Evidence boundaries",
    source: "Source",
    supports: "Supports",
    limitation: "Limit",
    research: "Research",
    standard: "Standard",
    officialGuidance: "Official guidance",
    teachingGuidance: "Teaching guidance",
    previous: "Previous module",
    next: "Next module",
    backToCourse: "Back to Course 13",
    openCourseMap: "Open module map",
    onThisPage: "On this page",
    phase: "Phase",
    evidenceBoundary: "Evidence boundary",
    courseIntegrity: "Course integrity",
    courseIntegrityTitle: "A system diagram is a hypothesis until learning evidence supports it",
    modulePosition: "Module {current}",
    moduleMapPosition: "Module {current} of {total}: {mapLabel}",
    phasePosition: "{current} of {total}",
    estimatedModuleTime: "Estimated module time: {minutes} minutes",
    progressPosition: "{complete} of {total} milestones",
    questionPosition: "Question {current} of {total}: {moduleTitle}",
    scorePosition: "{score} of {total}. Best score: {best} of {total}.",
    bestScorePosition: "Best score: {best} of {total}",
    artifactWithValue: "Artifact: {artifact}",
    minutesWithValue: "{minutes} minutes",
    accessedOn: "Accessed {date}",
    opensInNewTab: "opens in a new tab",
  },
  principles: [
    "Observed evidence before learner labels",
    "Support that fades toward independence",
    "Teacher authority before automated scale",
  ],
  outcomes: [
    "Translate a broad learning intention into observable performances, prerequisite concepts, and aligned evidence.",
    "Design a diagnostic sequence that separates observations from uncertain claims about learner knowledge.",
    "Specify contingent scaffolds that can increase, fade, and transfer responsibility to the learner.",
    "Close a formative assessment loop by connecting evidence to an immediate, reviewable next action.",
    "Validate generated or authored items with content review, response data, fairness checks, and version control.",
    "Represent learner state as a contestable, time-stamped estimate with provenance and calibrated uncertainty.",
    "Design an ethical learning-impact study with a defined estimand, comparison, outcome, attrition plan, and decision rule.",
    "Create a safety and teacher-oversight matrix with decision rights, escalation paths, monitoring, and rollback.",
  ],
  phases: {
    frame: {
      title: "Frame the learning claim",
      summary: "Define observable learning and collect evidence that can discriminate among plausible learner needs.",
    },
    adapt: {
      title: "Adapt support responsibly",
      summary: "Choose the smallest useful scaffold, observe the response, and fade support toward independent performance.",
    },
    validate: {
      title: "Validate measurement and inference",
      summary: "Treat questions and learner states as measurement instruments whose reliability, fairness, and uncertainty require review.",
    },
    govern: {
      title: "Evaluate learning impact and govern use",
      summary: "Test whether the system improves learning and make teacher authority, incident response, and learner recourse operational.",
    },
  },
  conceptMap: {
    title: "The evidence-to-action learning loop",
    summary: "An AI tutor earns the right to adapt only when its learning claim, evidence, inference, action, and outcome check remain traceable.",
    center: "Learner evidence, not chat fluency",
    teacherBoundary: "Teachers approve goals and high-impact actions, inspect uncertainty, handle escalations, and can override or stop the system. Learners can understand, contest, and seek help with consequential inferences.",
    relations: {
      "defines-evidence": "defines evidence",
      "selects-support": "selects support",
      "creates-response": "creates a response",
      "audits-signal": "audits signals used by",
      "strengthens-inference": "strengthens inference",
      "updates-action": "updates the next action",
      "provides-adaptation-state": "provides the adaptation state evaluated by",
      "supports-release": "supports a release decision",
      "revises-contract": "revises the contract",
    },
    nodes: {
      "objectives-concept-map": {
        shortTitle: "Objectives",
        role: "Define observable performance and prerequisite relationships.",
      },
      "diagnostic-engine": {
        shortTitle: "Diagnosis",
        role: "Elicit evidence that distinguishes among plausible knowledge states.",
      },
      "adaptive-scaffolding": {
        shortTitle: "Scaffolding",
        role: "Choose contingent help and plan how responsibility will transfer.",
      },
      "formative-assessment-loop": {
        shortTitle: "Formative loop",
        role: "Use the learner's response to improve the next learning move.",
      },
      "item-validation": {
        shortTitle: "Item quality",
        role: "Check whether tasks support the intended interpretation fairly.",
      },
      "learner-modeling": {
        shortTitle: "Learner state",
        role: "Maintain uncertain, time-stamped estimates rather than fixed labels.",
      },
      "learning-impact-experiment": {
        shortTitle: "Impact study",
        role: "Compare outcomes and implementation against a declared decision rule.",
      },
      "safety-teacher-oversight": {
        shortTitle: "Oversight",
        role: "Bound autonomy with roles, escalation, monitoring, and rollback.",
      },
    },
  },
  sourceAnnotations: {
    "constructive-alignment": {
      supports: "Aligning observable learning outcomes, learning activity, and assessment evidence.",
      limitation: "This is university teaching guidance, not an evaluation of a particular AI tutor.",
    },
    "concept-mapping": {
      supports: "Representing concepts as nodes and meaningful propositions as labeled relationships between concepts, within a defined focus question.",
      limitation: "This technical report describes concept-map theory and construction; it does not validate this course's particular system map or any automated routing policy.",
    },
    "evidence-centered-design": {
      supports: "Connecting claims about capability to observable evidence and tasks designed to elicit that evidence.",
      limitation: "The worked application concerns language assessment, so this course transfers the design logic rather than its exact test design.",
    },
    "scaffolding-review": {
      supports: "Contingency, fading, and transfer of responsibility as defining properties of scaffolding.",
      limitation: "The review centers human teacher-student interaction; AI implementation still needs separate usability, safety, and outcome evidence.",
    },
    "apa-formative-assessment": {
      supports: "Using timely assessment evidence to adjust instruction and interpreting results with attention to reliability, validity, and fairness.",
      limitation: "The guidance is broad and does not prescribe one automated feedback policy or learner model.",
    },
    "testing-standards": {
      supports: "Validity, reliability, fairness, and responsible interpretation as connected obligations in assessment use.",
      limitation: "A short course cannot replace the full standards or qualified psychometric review for consequential testing.",
    },
    "knowledge-tracing": {
      supports: "The foundational idea of updating an uncertain estimate of skill knowledge from learner performance over time.",
      limitation: "The original model makes simplifying assumptions and does not establish that one state model is valid across domains, populations, or modern tutor designs.",
    },
    "negotiated-learner-modeling": {
      supports: "Opening learner-model representations to learners and teachers, accepting additional evidence, and negotiating disputed estimates to support accuracy and reflection.",
      limitation: "The paper proposes and synthesizes negotiated learner-model practices; it does not establish that every visualization, negotiation workflow, or automated correction will improve outcomes.",
    },
    "wwc-standards": {
      supports: "Design and review considerations for causal education studies, including baseline equivalence, attrition, and transparent effect estimation.",
      limitation: "The handbook is a study-review standard, not a guarantee that any proposed experiment is ethical, adequately powered, or well implemented.",
    },
    "unesco-genai-guidance": {
      supports: "A human-centered approach to generative AI in education, with attention to agency, privacy, age appropriateness, and institutional responsibility.",
      limitation: "The guidance is cross-jurisdictional and must be combined with current local law, institutional policy, and learner-specific safeguards.",
    },
    "nist-ai-rmf": {
      supports: "Documented roles, continuous risk management, measurement, governance, and differentiated human oversight.",
      limitation: "The framework is voluntary and sector-neutral; an education deployment needs more specific policy, child-safety, accessibility, and assessment controls.",
    },
  },
  modules: {
    "objectives-concept-map": {
      kicker: "Module 01 · Learning contract",
      title: "Learning objectives and the system concept map",
      summary: "Turn a broad educational ambition into observable performance, prerequisite relationships, evidence claims, and an inspectable tutoring loop.",
      objective: "Write one measurable learning objective and connect it to prerequisite concepts, eliciting tasks, scoring evidence, and permitted tutor actions.",
      artifact: "Learning contract and concept map",
      sections: [
        {
          heading: "Start with a learner performance, not an AI feature",
          paragraphs: [
            "A learning system needs a claim about what the learner will be able to do under stated conditions. 'Use an AI tutor' and 'understand fractions' are not yet testable system requirements. A stronger objective names the performance, content, conditions, and acceptable quality, such as: given two unlike fractions and no worked example, the learner will produce a common-denominator solution and explain why it preserves value.",
            "This objective constrains every downstream decision. Diagnosis must elicit evidence about the named performance. Scaffolds must support the relevant reasoning rather than merely produce the answer. Assessment must sample the intended knowledge. The learner model may represent only claims for which the system has defensible evidence.",
          ],
          bullets: [
            "Performance: the observable action the learner completes.",
            "Content: the concept, procedure, or practice being learned.",
            "Condition: tools, support, time, and context available during performance.",
            "Criterion: the quality threshold and the reasoning that must be visible.",
          ],
          sourceIds: ["constructive-alignment"],
        },
        {
          heading: "Use a concept map to expose dependencies",
          paragraphs: [
            "A concept map is not decoration. It is a dependency hypothesis. Nodes represent concepts or practices; directed edges state the relation that must hold, such as prerequisite for, contrasts with, or provides evidence for. Add an observable example and a common misconception to each critical node. This turns a picture into a design object that can guide diagnosis and content sequencing.",
            "Keep the map smaller than the domain. The first release should cover only the concepts required for the target outcome. Mark uncertain edges and concepts that require teacher review. If two designers cannot explain an edge in the same way, the system is not ready to route learners on that edge.",
          ],
          sourceIds: ["concept-mapping", "constructive-alignment"],
        },
        {
          heading: "Connect claims, evidence, tasks, and actions",
          paragraphs: [
            "Evidence-centered design asks what claim you want to make, what learner behavior would support that claim, and what task could elicit that behavior. An AI tutor adds a fourth obligation: what instructional action is permitted at each level of evidence. The action should be no stronger than the evidence that supports it.",
            "Write explicit non-claims. A correct multiple-choice response does not by itself establish durable understanding, transfer, motivation, or independent performance. Stating these boundaries early prevents a dashboard probability or fluent explanation from becoming an accidental label about the learner.",
          ],
          sourceIds: ["evidence-centered-design", "testing-standards"],
        },
      ],
      systemContract: {
        signal: "A scored performance, explanation, or work trace aligned to the target objective.",
        inference: "The response supports one bounded claim about a concept or practice, with stated alternatives and uncertainty.",
        action: "Select an aligned task, probe, explanation, or scaffold that the evidence authorizes.",
        outcomeEvidence: "A later, less-supported performance on the same construct or a defined transfer task.",
        stopRule: "Stop design when the objective is not observable, the concept edge is ambiguous, or the task measures a different construct.",
      },
      workshop: {
        title: "Build a one-page learning contract",
        brief: "Choose one narrow learning outcome and make its evidence and system boundaries visible before designing a chat experience.",
        steps: [
          "Write the learner performance, content, condition, and criterion in one sentence.",
          "Draw five to nine prerequisite or component nodes and label every edge with a relationship.",
          "Attach one observable example and one plausible misconception to each critical node.",
          "For the target claim, specify evidence, an eliciting task, a scoring rule, and one allowed tutor action.",
          "List at least three conclusions the evidence must not be used to make.",
        ],
        deliverables: [
          "One measurable objective",
          "One labeled concept map",
          "One claim-evidence-task-action table",
          "One non-claims list",
        ],
        reviewGate: "A teacher and a domain expert can independently explain what performance counts, why each critical edge exists, and what the tutor may infer.",
        safetyBoundary: "Do not encode disability, language background, effort, intelligence, or motivation as hidden explanations for performance unless the context, consent, evidence, and use are explicitly justified.",
      },
      checkpoint: {
        question: "Which objective is ready to constrain an AI tutor design?",
        options: [
          "Learners will understand proportional reasoning.",
          "The tutor will personalize every explanation.",
          "Given a ratio table, learners will identify a multiplicative relationship and justify it with two corresponding pairs.",
          "Learners will enjoy mathematics more.",
        ],
        correctIndex: 2,
        explanation: "The third option names an observable performance, context, content, and evidence in the justification. The other statements require further operational definition before they can guide diagnosis or assessment.",
      },
      takeaway: "A tutor is only as educational as the learning claim that constrains its evidence and actions.",
    },
    "diagnostic-engine": {
      kicker: "Module 02 · Evidence before routing",
      title: "Diagnosis without overclaiming",
      summary: "Design short diagnostic sequences that distinguish among plausible needs while keeping observations separate from uncertain learner-state inferences.",
      objective: "Create a diagnostic decision table with competing hypotheses, discriminating probes, confidence rules, and a safe fallback when evidence is weak or conflicting.",
      artifact: "Diagnostic evidence and routing table",
      sections: [
        {
          heading: "Diagnosis is a decision under uncertainty",
          paragraphs: [
            "A wrong answer is an observation, not a diagnosis. The same response may result from a misconception, a calculation slip, ambiguous wording, language load, inaccessible presentation, guessing, or missing prerequisite knowledge. A diagnostic engine should preserve these alternatives until a discriminating observation changes their relative support.",
            "Define the decision the diagnosis will support. Choosing the next practice problem needs less certainty than assigning a remediation track or notifying a teacher. The cost of a wrong inference should determine how much evidence, review, and consent are required.",
          ],
          bullets: [
            "Observation: what the learner selected, wrote, said, requested, or revised.",
            "Hypothesis: a possible explanation for the observation.",
            "Probe: a task designed to distinguish among hypotheses.",
            "Action threshold: the evidence level needed before a particular response is permitted.",
          ],
          sourceIds: ["evidence-centered-design", "testing-standards"],
        },
        {
          heading: "Design probes for contrast, not repetition",
          paragraphs: [
            "Repeating the same item with different numbers often confirms only that the learner can repeat the same response pattern. A discriminating probe changes the representation, asks for a reason, presents a counterexample, or isolates a prerequisite. Each option or open response should map to a plausible evidence pattern rather than a generic wrong category.",
            "Keep diagnostic sequences short and reversible. Start with low-burden evidence, update confidence, and ask another probe only when it can change the next action. If no safe action depends on the distinction, do not collect more learner data merely because the system can.",
          ],
          sourceIds: ["evidence-centered-design", "apa-formative-assessment"],
        },
        {
          heading: "Route with confidence bands and a fallback",
          paragraphs: [
            "Use interpretable bands such as insufficient evidence, tentative, and supported for this decision. Record what evidence contributed, when it was observed, and what evidence conflicts. Confidence is about the claim and decision, not a score for the learner as a person.",
            "Every branch needs a fallback. When evidence is sparse, contradictory, inaccessible, or outside the modeled domain, the tutor can ask the learner to choose a goal, offer a neutral review, or escalate to a teacher. It should not conceal uncertainty behind a confident diagnosis.",
          ],
          sourceIds: ["testing-standards", "apa-formative-assessment"],
        },
      ],
      systemContract: {
        signal: "A response pattern, explanation, hint request, latency interval, or revision that is relevant and ethically collected.",
        inference: "One or more competing, decision-specific hypotheses with provenance and a confidence band.",
        action: "Ask a discriminating probe, offer a neutral review, choose a low-risk next task, or escalate.",
        outcomeEvidence: "The learner's response to the probe and later independent performance on the target skill.",
        stopRule: "Do not diagnose when the evidence is inaccessible, outside the model, contradicted, or insufficient for the consequence of the action.",
      },
      workshop: {
        title: "Build a diagnostic decision table",
        brief: "Use one common error from your concept map and design the smallest sequence that can distinguish among at least three explanations.",
        steps: [
          "Record the initial observation without interpreting it.",
          "List at least three plausible explanations, including one task or interface explanation.",
          "Design a probe whose response patterns would change support for those explanations.",
          "Define confidence bands and the actions permitted in each band.",
          "Add a fallback for conflicting, missing, or out-of-scope evidence.",
        ],
        deliverables: [
          "Observation and hypothesis table",
          "One discriminating probe",
          "Confidence-to-action policy",
          "Fallback and escalation rule",
        ],
        reviewGate: "A reviewer can follow every route from observed response to hypothesis update and can identify a non-diagnostic explanation the design considered.",
        safetyBoundary: "Collect the minimum evidence needed for the instructional decision. Do not infer protected characteristics, mental health, intent, or stable ability from ordinary tutoring traces.",
      },
      checkpoint: {
        question: "A learner gives one wrong answer and the diagnostic hypotheses remain equally plausible. What is the best next move?",
        options: [
          "Assign the most common misconception label.",
          "Ask a short probe designed to distinguish among the hypotheses.",
          "Lower the learner's mastery score permanently.",
          "Show the complete solution and mark the concept learned.",
        ],
        correctIndex: 1,
        explanation: "A discriminating probe can create information that changes the decision. The other options turn weak evidence into a strong label or remove the opportunity to diagnose.",
      },
      takeaway: "Preserve alternative explanations until evidence earns a narrower instructional decision.",
    },
    "adaptive-scaffolding": {
      kicker: "Module 03 · Contingent support",
      title: "Scaffolding that fades toward independence",
      summary: "Engineer support as a contingent policy with explicit entry, escalation, fading, and transfer rules rather than an endless stream of helpful answers.",
      objective: "Specify a scaffold ladder and fading policy that responds to evidence while protecting productive effort and independent performance.",
      artifact: "Scaffold ladder and fading policy",
      sections: [
        {
          heading: "Support becomes scaffolding only when it is contingent",
          paragraphs: [
            "A hint, explanation, or worked example is not automatically a scaffold. Scaffolding responds to the learner's current performance, changes as evidence changes, and aims to transfer responsibility. A fixed explanation shown to everyone may be useful instruction, but it does not implement a contingent tutoring policy.",
            "Define a ladder from the least directive support to the most directive support. A typical sequence might move from goal reminder, to self-explanation prompt, to strategic cue, to representation change, to partial worked example, and only then to direct instruction. Domain and accessibility needs may require a different order.",
          ],
          sourceIds: ["scaffolding-review"],
        },
        {
          heading: "Fading needs evidence and a transfer target",
          paragraphs: [
            "Remove help when the learner demonstrates reliable performance under a less-supported condition, not merely after time passes or one correct answer appears. Plan the transfer target in advance: an independent problem, a new representation, a delayed attempt, or an explanation without the tutor's language.",
            "Overhelp can create answer completion without learning. Log which scaffold was shown, what the learner did next, and whether later performance required less support. A high completion rate with stable or increasing help is a warning, not success.",
          ],
          bullets: [
            "Contingency: support changes in response to relevant evidence.",
            "Fading: support decreases when less-supported performance is demonstrated.",
            "Transfer: responsibility moves from tutor prompts to learner planning and monitoring.",
          ],
          sourceIds: ["scaffolding-review"],
        },
        {
          heading: "Protect agency, accessibility, and legitimate help seeking",
          paragraphs: [
            "A learner may request more direct help for valid reasons. Treat help seeking as information, not laziness. Offer choices such as another example, a simpler representation, a definition, or teacher assistance, and explain what each choice changes. Accessibility support should not be faded merely because it resembles instructional support.",
            "Set boundaries for generation. The tutor should not invent prerequisites, silently change the learning objective, or give a final answer in a context where independent performance is required. When it cannot provide a safe, aligned scaffold, it should say so and route to an approved resource or teacher.",
          ],
          sourceIds: ["scaffolding-review", "unesco-genai-guidance"],
        },
      ],
      systemContract: {
        signal: "Current attempt evidence, prior scaffold exposure, learner request, and accessibility preference.",
        inference: "The least directive support likely to make the next learner action possible, expressed with uncertainty.",
        action: "Offer one scaffold level, invite the learner's work, then update or fade based on the response.",
        outcomeEvidence: "Correct and explained performance with less support, on a new or delayed task.",
        stopRule: "Stop escalating when the tutor would complete the assessed work, the task is unsafe, or teacher intervention is required.",
      },
      workshop: {
        title: "Design a six-level scaffold ladder",
        brief: "Choose one difficult step in your target performance and specify how support enters, escalates, fades, and transfers responsibility.",
        steps: [
          "Name the learner action the scaffold should enable without completing it.",
          "Order six supports from least to most directive and state the purpose of each.",
          "Define evidence that triggers entry, escalation, repetition, and fading.",
          "Add a transfer task that removes the tutor's wording or representation.",
          "Separate accessibility accommodations from supports that should fade.",
        ],
        deliverables: [
          "Six-level scaffold ladder",
          "Trigger and fading table",
          "Independent transfer task",
          "Accessibility and help-seeking note",
        ],
        reviewGate: "For every scaffold level, a reviewer can identify the learner action that remains and the evidence that will justify less support.",
        safetyBoundary: "Do not withhold accessibility support, shame help seeking, or optimize for task completion at the cost of learner agency and independent performance.",
      },
      checkpoint: {
        question: "What is the strongest evidence that a scaffold should fade?",
        options: [
          "The learner has viewed it three times.",
          "The learner says the tutor is helpful.",
          "The learner completes a relevant task accurately with less support and can explain the reasoning.",
          "The tutor has reached the end of its hint sequence.",
        ],
        correctIndex: 2,
        explanation: "Fading should respond to evidence of less-supported performance. Exposure counts, satisfaction, and sequence position do not establish readiness for transferred responsibility.",
      },
      takeaway: "The purpose of a scaffold is to make itself less necessary.",
    },
    "formative-assessment-loop": {
      kicker: "Module 04 · Evidence changes action",
      title: "The formative assessment loop",
      summary: "Turn short checks into a closed instructional loop in which evidence changes the next action and that action is evaluated by later learner work.",
      objective: "Design a formative cycle that elicits aligned evidence, interprets it cautiously, selects an immediate response, and checks whether the response helped.",
      artifact: "Formative evidence-to-action specification",
      sections: [
        {
          heading: "A check is formative only when it informs what happens next",
          paragraphs: [
            "A quiz, confidence rating, or chat question is not formative merely because it occurs during learning. Its evidence must be interpreted in relation to an objective and used by the learner, tutor, or teacher to adjust the next step. If the result is collected only for a dashboard, the instructional loop remains open.",
            "Keep the time between evidence and action short enough for the response to matter. Choose a response class before implementation: revisit a prerequisite, contrast examples, prompt explanation, change representation, assign independent practice, or request teacher review.",
          ],
          sourceIds: [
            "apa-formative-assessment",
            "constructive-alignment",
            "evidence-centered-design",
          ],
        },
        {
          heading: "Feedback should create learner work",
          paragraphs: [
            "Feedback is an input to a learner decision, not a polished message from the system. It should identify the goal, make the current evidence inspectable, and request a next action. Generic praise and answer revelation may improve the interaction while producing little evidence of changed understanding.",
            "Design feedback for uptake. Ask the learner to revise, explain, compare, predict, or apply. Then retain the revision as new evidence while keeping the earlier attempt available for audit. Do not overwrite a learning trace with the tutor's corrected version.",
          ],
          bullets: [
            "Where am I going? Restate the relevant success criterion.",
            "Where am I now? Point to observable evidence without assigning a personal label.",
            "What is the next move? Require a learner action that can produce new evidence.",
          ],
          sourceIds: ["apa-formative-assessment"],
        },
        {
          heading: "Measure the effect of the instructional response",
          paragraphs: [
            "Log the evidence, inference, action, and subsequent outcome as separate fields. This makes it possible to ask whether a particular response helped learners with a particular evidence pattern. It also exposes when a tutor repeatedly recommends an action without measuring the result.",
            "Use aggregate views for teacher sensemaking, not automated ranking. Show missingness and uncertainty, allow teachers to inspect examples, and avoid averaging across unlike objectives. A formative dashboard should support a decision about instruction, not create an unexplained score.",
          ],
          sourceIds: ["apa-formative-assessment", "testing-standards"],
        },
      ],
      systemContract: {
        signal: "A brief, aligned learner response plus the level of support used to produce it.",
        inference: "A decision-specific description of the current gap, with missing and conflicting evidence visible.",
        action: "Give feedback that asks the learner to revise, explain, compare, or apply within the same learning cycle.",
        outcomeEvidence: "The requested learner action and a later, less-supported check of the same objective.",
        stopRule: "Do not continue an automated feedback loop when responses repeat without improvement, the evidence is out of scope, or the learner requests human help.",
      },
      workshop: {
        title: "Close one formative loop",
        brief: "Specify a five-minute learning cycle in which each possible evidence pattern leads to a next action and a follow-up observation.",
        steps: [
          "Choose one objective and one short task that elicits relevant evidence.",
          "Define three evidence patterns without learner labels.",
          "Assign one immediate instructional response to each pattern.",
          "Write the learner action each response must produce.",
          "Define the follow-up evidence and a rule for changing the response policy.",
        ],
        deliverables: [
          "Evidence-pattern table",
          "Feedback and learner-action scripts",
          "Follow-up task",
          "Policy review rule",
        ],
        reviewGate: "Every collected response has a named instructional use, and every tutor action has a later observation that can show whether it helped.",
        safetyBoundary: "Do not expose sensitive learner traces in dashboards or use formative data for a new consequential purpose without notice, justification, and appropriate review.",
      },
      checkpoint: {
        question: "What turns an assessment event into a formative assessment process?",
        options: [
          "It is short and automatically scored.",
          "It occurs before the final exam.",
          "Its evidence changes a learner or teacher action, and later work checks the effect of that action.",
          "It produces a mastery percentage on a dashboard.",
        ],
        correctIndex: 2,
        explanation: "Timing and automation are not sufficient. The defining loop connects evidence to an instructional or learning action and then inspects subsequent evidence.",
      },
      takeaway: "If evidence does not change a next action, the loop is reporting, not formative assessment.",
    },
    "item-validation": {
      kicker: "Module 05 · Measurement quality",
      title: "Item validation before learner decisions",
      summary: "Treat every generated or authored question as an unvalidated measurement instrument until content review, response evidence, fairness checks, and version control support its use.",
      objective: "Create an item validation plan that links an item to a claim, examines response behavior, checks fairness and accessibility, and defines release or retirement criteria.",
      artifact: "Item validation and version report",
      sections: [
        {
          heading: "Validate the interpretation, not just the answer key",
          paragraphs: [
            "An item can have one defensible key and still fail to measure the intended knowledge. It may depend on reading complexity, hidden conventions, cultural familiarity, interface behavior, or an unintended shortcut. Begin with the claim the item is meant to support and describe the response process a knowledgeable learner would use.",
            "Require domain review and learner-facing review before pilot use. Check alignment, accuracy, ambiguity, accessibility, scoring, and the plausibility of distractors. For generated items, preserve the prompt, model or authoring tool, review record, and exact released version.",
          ],
          sourceIds: ["testing-standards", "evidence-centered-design"],
        },
        {
          heading: "Use response statistics as diagnostics, not verdicts",
          paragraphs: [
            "Pilot data can reveal patterns worth investigating. Proportion correct describes observed difficulty in a sample. Item-total association can indicate whether responses move with the broader score. Distractor frequencies show whether incorrect options attract responses. None of these statistics alone establishes validity or fairness.",
            "A very easy item may be appropriate for a prerequisite check but provide little information near a mastery threshold. A low or negative discrimination estimate can signal a wrong key, ambiguity, multidimensional demands, poor sampling, or a mismatch between item and score. Inspect learner work and content before deciding what to change.",
          ],
          sourceIds: ["testing-standards", "apa-formative-assessment"],
        },
        {
          heading: "Check fairness, accessibility, exposure, and drift",
          paragraphs: [
            "Compare item behavior across relevant groups only with adequate sample, context, privacy protection, and qualified analysis. A statistical difference is a flag for investigation, not proof of bias. Examine opportunity to learn, language, accessibility, differential item functioning, scoring, and administration conditions together.",
            "Version the item bank. Track exposure, edits, scoring changes, performance over time, and the decisions each item is allowed to support. Retire or quarantine items when content changes, leakage occurs, accessibility fails, or new evidence undermines the intended interpretation.",
          ],
          sourceIds: ["testing-standards"],
        },
      ],
      systemContract: {
        signal: "Item content, intended claim, scoring rule, reviewer record, response data, subgroup context, and exposure history.",
        inference: "The item is approved, limited, under review, or retired for a stated use and population.",
        action: "Release for a bounded purpose, revise and repilot, quarantine, or retire with version history preserved.",
        outcomeEvidence: "Expert review, learner response processes, pilot statistics, accessibility results, and monitored drift after release.",
        stopRule: "Do not score or route learners with an item whose key, construct alignment, accessibility, or permitted use is unresolved.",
      },
      workshop: {
        title: "Write an item validation report",
        brief: "Take three items, including one AI-generated item, and decide whether each is ready, limited, revisable, or retired.",
        steps: [
          "State the claim and intended response process for each item.",
          "Run a structured review for accuracy, ambiguity, accessibility, scoring, and unintended demand.",
          "Define the pilot sample and the response indicators you will inspect.",
          "Add fairness, exposure, and version-monitoring checks.",
          "Record a release status, permitted use, owner, and next review date.",
        ],
        deliverables: [
          "Three item specification records",
          "Structured review notes",
          "Pilot analysis plan",
          "Versioned release decisions",
        ],
        reviewGate: "No item enters the learner model until its intended interpretation, allowed use, scoring, accessibility, and current version are inspectable.",
        safetyBoundary: "Do not use unvalidated generated items for grades, placement, discipline, eligibility, or other consequential decisions. Protect secure items and learner response data.",
      },
      checkpoint: {
        question: "A pilot item is answered correctly by 96 percent of learners and has near-zero discrimination. What can you conclude?",
        options: [
          "The item is excellent because almost everyone succeeds.",
          "The item is invalid and must be deleted immediately.",
          "The item is easy in this sample and may provide little separation; inspect its intended purpose, content, responses, and sample before deciding.",
          "The learner model should assign mastery to everyone who saw it.",
        ],
        correctIndex: 2,
        explanation: "Observed ease and low discrimination are diagnostic evidence, not a complete validity judgment. The item's purpose, content, sample, response process, and allowed decision all matter.",
      },
      takeaway: "An answer key checks correctness; validation checks whether the resulting interpretation is defensible.",
    },
    "learner-modeling": {
      kicker: "Module 06 · Uncertain state",
      title: "Learner models as contestable estimates",
      summary: "Represent knowledge state as a time-stamped, evidence-linked estimate that can express uncertainty, decay, conflict, and human correction.",
      objective: "Specify a learner-state schema and update policy that preserves provenance, confidence, missingness, and decision limits without turning estimates into identities.",
      artifact: "Learner-state schema and update policy",
      sections: [
        {
          heading: "Model claims, not people",
          paragraphs: [
            "A learner model is a compact hypothesis about variables useful for instruction. It is not a complete portrait of a learner and should not become one. Prefer claim-specific states such as evidence for solving linear equations under a given support condition over labels such as weak student, visual learner, unmotivated, or low ability.",
            "Define every state variable with its instructional purpose, evidence sources, update rule, uncertainty representation, retention period, and prohibited uses. If a variable cannot change a legitimate learning decision, it may not belong in the model.",
          ],
          sourceIds: ["knowledge-tracing", "testing-standards"],
        },
        {
          heading: "Separate evidence events from state estimates",
          paragraphs: [
            "Keep retention-limited evidence payloads separate from the current estimate derived from them. An event records the task version, response, scoring, support, time, and context. An append-only audit marker records that an event existed, changed, or was deleted without retaining a personal response after its authorized retention period. The state record identifies the model version, estimate, uncertainty, contributing evidence, and update time. This separation supports recalculation, audit, and deletion without claiming that personal data is permanently immutable.",
            "Account for guessing, slips, missing data, support level, and time. A correct answer after a full worked example should update independent mastery differently from a correct unsupported transfer task. Conflicting or stale evidence should widen uncertainty rather than disappear inside an average.",
          ],
          sourceIds: ["knowledge-tracing", "testing-standards"],
        },
        {
          heading: "Calibrate, expose, and contest the estimate",
          paragraphs: [
            "Evaluate whether confidence bands correspond to observed future performance. Calibration asks whether claims made with similar confidence succeed at similar rates. Also inspect subgroup performance, missingness, and the consequences of false-positive and false-negative mastery decisions.",
            "Give teachers a view of contributing evidence and model uncertainty, not just a color. Give learners an age-appropriate explanation, a way to provide new evidence, and a route to contest consequential errors. Human override should create an auditable event and a reason, not silently erase model output.",
          ],
          sourceIds: ["negotiated-learner-modeling", "testing-standards", "nist-ai-rmf"],
        },
      ],
      systemContract: {
        signal: "Versioned, retention-limited learner evidence events with task, scoring, support, time, context, and provenance.",
        inference: "A claim-specific state estimate with uncertainty, recency, model version, and decision limits.",
        action: "Choose only actions allowed by the estimate's confidence and consequence tier; otherwise collect evidence or defer.",
        outcomeEvidence: "Future independent performance, calibration results, subgroup error analysis, corrections, and teacher review.",
        stopRule: "Do not update or act when provenance is missing, the model is out of domain, uncertainty exceeds the action threshold, or a consequential dispute is unresolved.",
      },
      workshop: {
        title: "Design a contestable learner-state record",
        brief: "Specify one skill state from raw evidence through update, display, correction, retention, and permitted action.",
        steps: [
          "Define the claim and the instructional decisions it may support.",
          "Specify deletable evidence payload fields, append-only audit markers, and the separate state fields.",
          "Write update rules for supported, unsupported, stale, missing, and conflicting evidence.",
          "Define confidence thresholds and the actions allowed at each threshold.",
          "Design teacher inspection, learner explanation, correction, retention, and deletion flows.",
        ],
        deliverables: [
          "Evidence event schema",
          "Learner-state schema",
          "Update and threshold policy",
          "Contestability and retention flow",
        ],
        reviewGate: "A reviewer can reconstruct why the current estimate exists, what it does not mean, how uncertain it is, and how a learner or teacher can challenge it.",
        safetyBoundary: "Never expose hidden psychological, disability, protected-class, or high-stakes predictions as ordinary tutoring state. Minimize collection and separate learning support from discipline, surveillance, and eligibility decisions.",
      },
      checkpoint: {
        question: "New evidence conflicts with an older high-confidence learner-state estimate. What is the safest model behavior?",
        options: [
          "Ignore the new evidence because the old estimate was confident.",
          "Replace the state with the latest answer and hide the conflict.",
          "Preserve both evidence events, widen or recompute uncertainty, and limit actions until the conflict is resolved.",
          "Ask the language model to choose which record feels more plausible.",
        ],
        correctIndex: 2,
        explanation: "Conflict is information. Preserving provenance and revising uncertainty supports audit and prevents a strong action from resting on an unexplained state change.",
      },
      takeaway: "A learner state is a versioned estimate for a bounded decision, never a fixed truth about a person.",
    },
    "learning-impact-experiment": {
      kicker: "Module 07 · Outcome evidence",
      title: "Experiments for learning impact",
      summary: "Design a study that can distinguish an attractive interaction from a credible improvement in learning, while tracking implementation, attrition, and unintended effects.",
      objective: "Write a learning-impact protocol with a target estimand, primary outcome, comparison condition, assignment unit, analysis plan, safety monitoring, and go-revise-stop rule.",
      artifact: "Learning-impact experiment protocol",
      sections: [
        {
          heading: "Name the causal question and the estimand",
          paragraphs: [
            "Start with the contrast you want to learn about. For example: what is the average effect of access to the tutor's adaptive scaffold policy, compared with the same curriculum and teacher support without that policy, on an independently scored delayed transfer task after four weeks? This specifies intervention, comparison, outcome, population, and time.",
            "Choose one primary learning outcome aligned to the course objective and measured independently of the tutor when possible. Engagement, message count, completion, and satisfaction are implementation or experience measures. They may explain use, but they do not substitute for learning outcomes.",
          ],
          sourceIds: ["wwc-standards", "constructive-alignment"],
        },
        {
          heading: "Protect the comparison before analyzing results",
          paragraphs: [
            "Choose the assignment unit that matches how the system is delivered. Individual randomization may fail when students share tutor outputs. Classroom randomization changes the effective sample size and requires cluster-aware planning and analysis. When randomization is not feasible, document baseline equivalence, selection threats, and the narrower inference the design permits.",
            "Predefine eligibility, recruitment, consent, sample-size rationale, assignment, outcome scoring, missing-data handling, attrition reporting, subgroup analyses, and exclusions. Freeze the primary analysis before seeing outcome differences. Record product changes and exposure so the tested intervention can be identified.",
          ],
          sourceIds: ["wwc-standards"],
        },
        {
          heading: "Interpret learning, implementation, and harm together",
          paragraphs: [
            "Report the effect estimate with uncertainty, not only a significance label. Show baseline values, sample flow, attrition, exposure, and outcome reliability. Analyze whether the tutor was used as intended and whether teachers changed other instruction in response. A null result can reflect no effect, weak implementation, insensitive measurement, or inadequate precision.",
            "Monitor adverse and distributional outcomes. Look for increased dependency, answer copying, frustration, differential access, subgroup error, teacher workload, privacy incidents, and displacement of productive peer or teacher interaction. A positive average effect does not automatically justify release when harms are concentrated or oversight fails.",
          ],
          sourceIds: ["wwc-standards", "unesco-genai-guidance", "nist-ai-rmf"],
        },
      ],
      systemContract: {
        signal: "Assignment records, baseline measures, intervention exposure, implementation fidelity, primary learning outcomes, attrition, and adverse events.",
        inference: "A bounded estimate of the tutor policy's effect for the studied population, implementation, comparison, and time window.",
        action: "Continue, revise, narrow, pause, or stop according to a preregistered decision rule and safety review.",
        outcomeEvidence: "Effect estimates with uncertainty, sample flow, implementation evidence, subgroup diagnostics, and monitored harms.",
        stopRule: "Pause when consent, assignment integrity, outcome scoring, safety monitoring, or the ability to identify the tested intervention breaks down.",
      },
      workshop: {
        title: "Write a one-page learning-impact protocol",
        brief: "Design the smallest ethical study that can answer one decision-relevant question about your tutor policy.",
        steps: [
          "Write the population, intervention, comparison, primary outcome, and time horizon in one estimand sentence.",
          "Choose the assignment unit and document contamination, baseline, and clustering risks.",
          "Define primary analysis, missing-data and attrition handling, and a minimum detectable or decision-relevant effect.",
          "Add implementation, teacher-workload, learner-agency, and adverse-event measures.",
          "Precommit to go, revise, narrow, pause, and stop conditions.",
        ],
        deliverables: [
          "Estimand and study diagram",
          "Outcome and scoring specification",
          "Assignment and analysis plan",
          "Decision and safety-monitoring rules",
        ],
        reviewGate: "A research reviewer can identify exactly what contrast the result would support, what threats remain, and which product decision each possible result would trigger.",
        safetyBoundary: "Obtain appropriate ethics, institutional, teacher, learner, and guardian review. Do not withhold established support, conceal assignment, or continue after a safety stopping condition is met.",
      },
      checkpoint: {
        question: "Tutor users improve from pretest to posttest, but there is no comparison condition. What can the team conclude?",
        options: [
          "The tutor caused the improvement.",
          "Learning improved over time in the observed group, but the tutor's causal contribution is not identified by this design.",
          "The tutor is ineffective because no control group exists.",
          "High usage proves the tutor caused the gain.",
        ],
        correctIndex: 1,
        explanation: "The observed gain is descriptive. Without a credible comparison, maturation, instruction, practice, selection, and other changes remain alternative explanations for the gain.",
      },
      takeaway: "Measure the learning contrast the product decision needs, not the interaction metrics the system produces most easily.",
    },
    "safety-teacher-oversight": {
      kicker: "Module 08 · Human authority",
      title: "Safety, teacher oversight, and release control",
      summary: "Turn human oversight into an operating system with named decision rights, risk tiers, escalation, learner recourse, monitoring, incident response, and rollback.",
      objective: "Create a risk and oversight matrix that assigns every tutor action to an autonomy tier, teacher role, escalation path, monitoring signal, and rollback procedure.",
      artifact: "Safety and teacher-oversight release packet",
      sections: [
        {
          heading: "Tier actions by consequence, not technical difficulty",
          paragraphs: [
            "Classify tutor actions by the harm a wrong action could cause and how reversible it is. Offering an optional practice example differs from assigning a learner to a remedial track, notifying a caregiver, influencing a grade, or responding to a disclosure of abuse or self-harm. Higher-consequence actions need stronger evidence, qualified human approval, and clearer recourse.",
            "Write prohibited and human-only actions before building. Define content and interaction boundaries for age, domain, crisis, regulated advice, academic integrity, harassment, sexual content, and sensitive data. A generic safety prompt is not a control unless its failures, owner, monitoring, and fallback are tested.",
          ],
          bullets: [
            "Autonomous low-risk: reversible practice selection within an approved objective.",
            "Teacher-visible: feedback or routing that a teacher can inspect and correct.",
            "Teacher-approved: consequential actions held until a qualified person accepts them.",
            "Human-only or prohibited: actions the tutor must not initiate or complete.",
          ],
          sourceIds: ["unesco-genai-guidance", "nist-ai-rmf"],
        },
        {
          heading: "Make teacher oversight operational",
          paragraphs: [
            "Name who approves objectives, content, item releases, learner-model changes, intervention policies, experiments, and production incidents. Show teachers the evidence and uncertainty needed for their decision. A confirm button without sufficient review time, context, authority, or an alternative action is not meaningful oversight.",
            "Design escalation with severity, routing, response time, learner-facing message, data exposure limit, and closure evidence. Give teachers pause and override controls. Give learners a clear way to ask for a person, understand why an action occurred, correct relevant information, and appeal a consequential decision.",
          ],
          sourceIds: ["nist-ai-rmf", "unesco-genai-guidance"],
        },
        {
          heading: "Test, monitor, respond, and roll back",
          paragraphs: [
            "Before release, test ordinary errors and adversarial cases across content, prompt injection, data leakage, unsupported certainty, bias, accessibility, teacher workload, and escalation. Include representative teachers and learners. Record unresolved risks and restrict scope instead of converting missing evidence into approval.",
            "After release, monitor safety events, override rates, unresolved escalations, subgroup errors, refusal quality, dependency, and model or content drift. Define incident owners, preservation of evidence, communication, corrective action, and rollback to a known safe version. Reapprove the system when models, policies, learner populations, or consequential uses change.",
          ],
          sourceIds: ["nist-ai-rmf", "unesco-genai-guidance", "testing-standards"],
        },
      ],
      systemContract: {
        signal: "Action type, consequence tier, learner context, evidence confidence, policy match, safety signals, and human availability.",
        inference: "The action is permitted autonomously, teacher-visible, teacher-approved, human-only, or prohibited under the current policy.",
        action: "Proceed within scope, defer for approval, escalate with context, refuse safely, pause the tutor, or roll back.",
        outcomeEvidence: "Teacher decisions, learner recourse, safety events, overrides, subgroup errors, resolution time, and post-incident verification.",
        stopRule: "Stop or defer when policy is missing, evidence conflicts, high-impact approval is unavailable, a serious safety signal appears, or monitoring and rollback are not operational.",
      },
      workshop: {
        title: "Run the teacher-led release review",
        brief: "Classify the tutor's actions, assign decision rights, and demonstrate an escalation and rollback before any real learner deployment.",
        steps: [
          "Inventory every tutor action and assign an autonomy and consequence tier.",
          "Name the accountable teacher or specialist role, evidence view, approval time, and alternative action for each consequential decision.",
          "Write escalation flows for uncertainty, out-of-scope content, safety disclosures, privacy events, and academic-integrity concerns.",
          "Test ordinary, adversarial, accessibility, and subgroup cases with representative reviewers.",
          "Run a tabletop incident from detection through learner communication, evidence preservation, rollback, correction, and reapproval.",
        ],
        deliverables: [
          "Action and autonomy inventory",
          "Teacher decision-rights matrix",
          "Escalation and learner-recourse flows",
          "Monitoring, incident, and rollback runbook",
        ],
        reviewGate: "A named teacher owner can stop the system, explain a consequential action from evidence, resolve an escalation, and restore a known safe version without vendor intervention.",
        safetyBoundary: "Do not deploy with real learners until applicable law and policy, privacy, accessibility, safeguarding, security, assessment, teacher workload, learner recourse, incident response, and rollback have qualified owners and evidence.",
      },
      checkpoint: {
        question: "The tutor is highly confident, but its evidence conflicts and the proposed action would change a learner's academic pathway. What should happen?",
        options: [
          "Apply the action because the model confidence is high.",
          "Average the conflicting evidence and continue automatically.",
          "Defer the action, preserve the evidence and uncertainty, and route the decision to an authorized teacher with a learner recourse path.",
          "Delete the conflicting evidence so the teacher sees one recommendation.",
        ],
        correctIndex: 2,
        explanation: "A consequential, contested inference requires qualified human authority, preserved evidence, and recourse. Model confidence cannot override conflict or the action's risk tier.",
        critical: true,
      },
      takeaway: "Teacher oversight is a designed control with authority, evidence, time, and recourse, not a person placed near an automated decision.",
    },
  },
  capstone: {
    title: "Design review for a minimum viable AI tutor",
    summary: "Assemble the eight module artifacts into one traceable release candidate. The capstone ends with a build, revise, narrow, or stop decision. It does not ask you to claim learning impact before an appropriate study produces evidence.",
    scenario: "Use a real, low-risk learning objective for which a teacher and domain reviewer are available, or use this safe fixture: a four-week adult-learning unit on interpreting everyday data displays. Use synthetic learner records during design and testing.",
    artifacts: [
      "A measurable learning objective, labeled concept map, and explicit non-claims.",
      "A diagnostic table with competing hypotheses, discriminating probes, confidence bands, and fallback.",
      "A scaffold ladder with entry, escalation, fading, transfer, and accessibility rules.",
      "A formative evidence-to-action loop with a follow-up measure for each tutor response.",
      "A versioned item validation report with content, response, fairness, accessibility, and exposure checks.",
      "A learner-state schema with provenance, uncertainty, decision limits, correction, retention, and deletion.",
      "A learning-impact protocol with estimand, comparison, outcome, assignment, analysis, attrition, and safety rules.",
      "A teacher-led release packet with action tiers, decision rights, escalation, recourse, monitoring, incident response, and rollback.",
    ],
    reviewQuestions: [
      "Can a reviewer trace every automated action back to an objective, evidence event, bounded inference, and permitted policy?",
      "What is the most harmful false inference the system can make, and which control prevents or contains it?",
      "Where can a learner see, correct, or contest information that changes their experience?",
      "Which decisions are teacher-visible, teacher-approved, human-only, or prohibited, and why?",
      "What evidence would cause the team to narrow, pause, roll back, or stop the system?",
      "Which claims remain design hypotheses, and which have actual outcome evidence for this population and use?",
    ],
    completionStatement: "I have an inspectable Course 13 design packet. I have not represented this design record as proof that the tutor improves learning, is safe for every learner, or is authorized for production use.",
  },
} as const satisfies AiTutorCourseCopy;
