import type { AgenticVideoEditingCourseCopy } from "../types";

const ui = {
  course: "Course",
  module: "Module",
  modules: "Modules",
  minute: "min",
  minutes: "Minutes",
  phase: "Phase",
  phases: "Phases",
  sources: "Sources",
  sourceAtlas: "Source atlas",
  artifact: "Artifact",
  practice: "Applied practice",
  checkpoint: "Checkpoint",
  evidence: "Evidence",
  evidenceMode: "Evidence mode",
  sourceGrounded: "Source-grounded",
  engineeringSynthesis: "Engineering synthesis",
  versionWatch: "Version watch",
  supports: "Supports",
  boundary: "Boundary",
  rights: "Rights decision",
  accessed: "Accessed",
  revision: "Revision",
  license: "License",
  published: "Published",
  verification: "Verification",
  corroboration: "Corroboration scope",
  tableOfContents: "Course map",
  onThisPage: "On this page",
  courseProgress: "Your production notebook",
  progressLedger: "Local progress ledger",
  browserStorageNote: "Saved only in this browser. No account or upload is required.",
  progressPosition: "{complete} of {total} milestones",
  complete: "Complete",
  pending: "Pending",
  nextUp: "Next",
  resetProgress: "Reset course",
  resetConfirm: "Reset Course 20 modules, artifacts, assessment, and capstone progress?",
  resetDone: "Course 20 progress reset.",
  resetDoneMemory: "Session progress reset. Browser storage remains unavailable.",
  storageUnavailable: "Browser storage is unavailable. Work will last only for this tab.",
  courseComplete: "Course record complete",
  moduleRecord: "Module record",
  moduleComplete: "Module complete",
  moduleIncomplete: "Complete the evidence gate",
  completionInstruction: "Pass the checkpoint and save a substantive artifact before closing this module.",
  checkpointRequirement: "Checkpoint passed",
  checkpointPending: "Checkpoint not yet passed",
  artifactRequirement: "Artifact saved",
  artifactPending: "Artifact not yet saved",
  saveArtifact: "Save artifact",
  artifactSaved: "Artifact saved locally.",
  artifactLabel: "Editable artifact",
  artifactHint: "Replace assumptions with project evidence: change at least three lines and add at least 40 substantive characters.",
  changedLines: "changed lines",
  selectAnswer: "Choose one answer.",
  checkAnswer: "Check answer",
  correct: "Correct",
  incorrect: "Not yet",
  markComplete: "Mark module complete",
  previous: "Previous",
  next: "Next",
  finalAssessment: "Final assessment",
  assessmentPass: "Pass mark: {percent}% and every critical question correct.",
  submitAssessment: "Score assessment",
  assessmentPassed: "Assessment passed",
  assessmentRetry: "Review the feedback and try again.",
  earlierPassRetained: "Your earlier passing record remains saved; this attempt did not pass.",
  score: "Score",
  criticalMiss: "A critical control question is still incorrect.",
  capstone: "Capstone",
  capstoneInstruction: "Check an item only after you can point to the artifact in your release package.",
  capstoneAttestation: "I reviewed the exact release candidate and confirm no critical blocker is being hidden.",
  capstoneComplete: "Capstone record complete",
  humanGate: "Human gate",
  aiBoundary: "Agent boundary",
  workSequence: "Work sequence",
  sourceRegister: "Source register",
  openExternal: "Open source",
  githubRepository: "GitHub repository",
  xPost: "Dated X field signal",
  roleExecutionEngine: "Execution engine",
  roleAnalysisComponent: "Analysis component",
  roleDeterministicAutomation: "Rule-based automation",
  roleTimelineContract: "Timeline contract",
  roleAgentArchitecture: "Agent architecture",
  roleAgentToolSurface: "Agent tool surface",
  roleQualityControl: "Quality control",
  roleFieldSignal: "Field signal",
  oembedComplete: "Complete visible post text",
  oembedTruncated: "Visible post text is truncated",
  officialXOembed: "Official X oEmbed",
  researchCutoff: "Research cutoff",
  systemRoles: "System roles",
  pipeline: "Production loop",
  distinctions: "Do not collapse these layers",
  outcomes: "What you will be able to deliver",
  start: "Start Course 20",
} as const;

export const AGENTIC_VIDEO_EDITING_EN_COPY = {
  meta: {
    title: "Agentic Video Editing: From Intent to a Verified Cut",
    shortTitle: "Agentic Video Editing",
    kicker: "Course 20 · GitHub- and X-grounded production course",
    summary: "Turn creative intent into an evidence-backed, previewable, reversible, and traceable edit—then keep release authority with an accountable human.",
    audience: "For creators, educators, product teams, and engineers who want agents inside a real editing workflow without surrendering editorial control.",
    prerequisite: "No paid account or API key is needed for the core course. Basic command-line and JSON literacy helps with the production exercises.",
    level: "Beginner to advanced",
    duration: "750 minutes · 4 phases · 10 modules · 12 milestones",
    startCta: "Start with the edit contract",
    resumeCta: "Resume production notebook",
    translationNote: "This route keeps its localized site shell but displays the reviewed English course edition. Reviewed long-form editions currently exist in English and Simplified Chinese.",
    evidenceNote: "GitHub repositories support inspectable implementation claims. X posts are dated practice signals, never proof of quality, speed, cost, or universal effectiveness.",
  },
  ui,
  principles: [
    "Intent before tools",
    "Original media stays read-only",
    "Claims point to evidence",
    "Plans precede mutations",
    "Preview before expensive execution",
    "Verification never impersonates approval",
    "Publishing remains human-authorized",
  ],
  outcomes: [
    "Write a creative brief with observable acceptance criteria, stop conditions, and named approvers.",
    "Build a local-first media ledger that records hashes, rights, privacy, network paths, and provenance.",
    "Turn ffprobe, transcript, shot-boundary, audio, and sampled-frame observations into a queryable evidence index.",
    "Separate an agent system from agent-ready tools, deterministic automation, media engines, and human authority.",
    "Produce a schema-valid edit plan with source ranges, reasons, evidence references, confidence, ambiguity, rights, and human-review requirements, then bind its frozen hash to a separate approval record.",
    "Compile approved plans into controlled FFmpeg, Remotion, CLI, MCP, or NLE operations without overwriting originals.",
    "Verify technical delivery, semantic integrity, captions, rights, privacy, and platform context through distinct gates.",
    "Package a recoverable, reproducibility-documented capstone with editable timeline, final renders, execution receipts, QC, provenance, and human release decision.",
  ],
  distinctions: [
    ["Agent system", "Chooses the next bounded action from goals, state, tools, and feedback; it must stop or escalate when authority or evidence is missing."],
    ["Agent-ready tool", "Exposes stable inputs, structured outputs, and inspectable errors to a host agent; it does not pursue an open-ended editorial goal."],
    ["Deterministic automation", "Runs encoded rules or a fixed sequence, such as loudness-based dead-space removal; it does not independently replan."],
    ["Media engine", "Executes commands, code, or timelines—FFmpeg and Remotion do not decide meaning, rights, taste, or release."],
    ["Human authority", "A governance layer—not another software class—that owns informed editorial, rights, risk, and release decisions."],
  ],
  phases: {
    define: {
      title: "Define the commission",
      verb: "Bound",
      summary: "Make intent, acceptance, source rights, network paths, and human authority explicit before analysis begins.",
    },
    understand: {
      title: "Understand through evidence",
      verb: "Observe",
      summary: "Index technical facts, words, shots, and reviewed visual hypotheses without turning model output into truth.",
    },
    edit: {
      title: "Edit through plans",
      verb: "Compose",
      summary: "Represent decisions as data, preview diffs, and let bounded tools execute an approved revision.",
    },
    verify: {
      title: "Verify and approve",
      verb: "Release",
      summary: "Run separate technical, semantic, accessibility, rights, and delivery gates before a human decides whether to publish.",
    },
  },
  modules: {
    "agentic-editing-contract": {
      kicker: "Define · Module 01",
      title: "Turn creative intent into an edit contract",
      summary: "Replace a vague request with an observable production contract and assign each system role honestly.",
      objective: "Write a brief that names the audience, claim, must-keep context, prohibited uses, acceptance criteria, stop conditions, and separate plan and release approvers.",
      artifact: "creative-brief.json + responsibility map",
      concepts: ["intent", "acceptance criteria", "system taxonomy", "authority", "stop conditions"],
      sections: [
        {
          heading: "A launch demo is not an operating contract",
          paragraphs: [
            "The Video Use X post is a dated launch signal for an agent-assisted talk-to-camera workflow. Its pinned repository—not the truncated oEmbed excerpt—documents transcript-to-EDL-to-render and an essential control: inventory sources, propose a strategy, wait for approval, and only then execute. A smooth demo cannot replace those gates.",
            "An executable brief names the audience, purpose, platform, target duration, central claim, must-keep context, prohibited material, and the exact checks that define success. ‘Make it engaging’ is a preference, not an acceptance test.",
          ],
          bullets: ["Ask before filling value judgments", "Bind approval to a named role", "Treat missing constraints as unresolved"],
          sourceIds: ["video-use", "x-video-use-release"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Separate intelligence from callable capability",
          paragraphs: [
            "VideoDB Director is an agent architecture because a reasoning layer selects capabilities from a request. Montaj is an agent-ready tool surface: its small schema-bound operations expect an external host agent to reason about order and parameters.",
            "Correct classification changes testing. Tools need contract tests; automations need trigger and sequence tests; engines need controlled render and media-conformance checks; agents also need policy, state, budget, stop, escalation, and authority tests.",
          ],
          bullets: ["Agent: chooses and replans", "Tool: performs one bounded operation", "Automation: follows encoded rules", "Engine: renders media"],
          sourceIds: ["videodb-director", "montaj"],
          evidenceMode: "engineering-synthesis",
        },
        {
          heading: "Keep the contract stable while tools move",
          paragraphs: [
            "These repositories are young and change quickly. The durable course contract is not a command copied from a launch week; it is the separation of intent, evidence, plan, preview, execution, verification, and approval.",
            "Before a real project, reopen the current README, release, license, and network path. A repository, X post, or version number cannot authorize client media or prove that today’s runtime matches the course snapshot.",
          ],
          sourceIds: ["video-use", "videodb-director", "montaj", "x-video-use-release"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "Rewrite a one-line request as a production contract",
        brief: "Transform ‘edit this interview into a compelling social video’ into a structured, reviewable commission that another editor can inspect without guessing.",
        steps: ["Define audience, context, one central claim, and intended action.", "List must-keep context, allowed reductions, and prohibited material.", "Write observable duration, aspect, caption, truth, and delivery criteria.", "Classify creative, factual, rights, privacy, safety, and technical risks.", "Name the plan approver, release approver, and stop conditions."],
        artifact: "A completed creative-brief.json and a one-page role map.",
        reviewGate: "The commissioner confirms goals, red lines, checks, and named authority before any media analysis.",
        aiBoundary: "The agent may detect omissions and propose wording; it may not decide facts, portrayal, political position, or release authority.",
        template: "# Edit contract\n- Audience:\n- Purpose and intended action:\n- Central claim:\n- Must keep:\n- May cut:\n- Must not use:\n- Acceptance checks:\n- Stop conditions:\n- Plan approver:\n- Release approver:\n- Unknowns requiring a decision:",
      },
      checkpoint: {
        question: "What should happen first when the request is ‘make the edit more engaging’?",
        options: ["Render three final cuts immediately", "Define the audience, intended result, and observable acceptance checks", "Add more transitions", "Let the model decide the brand position"],
        correctIndex: 1,
        explanation: "‘Engaging’ cannot be verified on its own. Turn it into audience outcomes and observable checks before planning or rendering.",
      },
      takeaway: "The strongest prompt is still weaker than a brief with evidence, stop conditions, and accountable authority.",
    },
    "media-ingest-provenance": {
      kicker: "Define · Module 02",
      title: "Protect originals, rights, and provenance",
      summary: "Build a local-first workspace that separates source evidence from every derived file and disclosure path.",
      objective: "Create a media manifest with stable IDs, hashes, technical metadata, rights, privacy, network policy, derivative lineage, and quarantine states.",
      artifact: "media-manifest.json + non-destructive workspace",
      concepts: ["read-only originals", "ffprobe", "rights ledger", "privacy", "provenance"],
      sections: [
        {
          heading: "Make original media immutable evidence",
          paragraphs: [
            "FFmpeg and ffprobe can expose duration, streams, codecs, frame rate, time base, color, and audio layout before any creative interpretation. Store those observations beside a stable asset ID and checksum; paths alone are not identities because files move.",
            "Every proxy, extracted audio file, transcript, preview, and render is a derivative with a parent asset and reproducible operation. Originals remain read-only, while work, cache, analysis, and versioned renders live in separate directories.",
          ],
          bullets: ["Probe before interpretation", "Never overwrite the only copy", "Make proxies relinkable", "Version every output"],
          sourceIds: ["ffmpeg"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Inspect before mutate",
          paragraphs: [
            "Timeline Studio, QCut, and the Resolve MCP guide converge on a useful safety posture: inspect current state first, show the proposed change, keep source media read-only, write analysis to sidecars, and preserve an undo or recovery route.",
            "Rights clearance is separate from technical access. Record ownership, recording consent, likeness, music, fonts, brands, third-party footage, allowed adaptation, commercial use, territory, term, upload permission, and publication scope. Unknown remains unknown and blocks release.",
          ],
          bullets: ["Dry-run before mutation", "Quarantine unknown rights", "Separate render from publish permission", "Log human overrides"],
          sourceIds: ["timeline-studio", "qcut", "davinci-resolve-mcp"],
          evidenceMode: "engineering-synthesis",
        },
        {
          heading: "Local-first does not mean every feature is offline",
          paragraphs: [
            "A desktop editor may export locally while optional analysis or generation sends selected media to a provider. The project must state what leaves the machine, where it goes, why it is necessary, how long it is retained, and who may authorize the transfer.",
            "Repository licenses do not automatically cover model weights, footage, music, fonts, provider output, or a person’s likeness. Recheck the current software license and each asset layer rather than treating a GitHub badge as a universal grant.",
          ],
          sourceIds: ["qcut", "ffmpeg", "davinci-resolve-mcp"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "Build an auditable ingest package",
        brief: "Inventory interview footage, a brand bumper, music, and B-roll without allowing unclear assets into analysis or publication.",
        steps: ["Assign asset IDs and record hashes plus ffprobe metadata.", "Separate originals, proxies, analysis, cache, and renders.", "Record owner, consent, allowed uses, upload policy, and expiry for each asset.", "Quarantine every unknown rather than inferring permission.", "Create the first provenance event for a derived proxy."],
        artifact: "media-manifest.json, directory manifest, and provenance event.",
        reviewGate: "The accountable rights approver verifies documented authority for every applicable rights layer and confirms the exact local or cloud path.",
        aiBoundary: "The agent may not turn a blank rights field into ‘cleared’, upload sensitive media, rename originals, or rewrite source metadata.",
        template: "# Media manifest review\n- Asset ID and SHA-256:\n- Source and owner:\n- Consent / likeness:\n- Allowed adaptations and platforms:\n- Local or cloud processing path:\n- Technical probe summary:\n- Parent / derivative relationship:\n- Rights state: cleared | restricted | unknown\n- Reviewer and date:",
      },
      checkpoint: {
        question: "A B-roll clip plays correctly, but its source and permission cannot be confirmed. What is the correct action?",
        options: ["Treat it as usable because it plays", "Publish first and wait for a complaint", "Mark it unknown, quarantine it, and request a rights decision", "Delete the provenance fields"],
        correctIndex: 2,
        explanation: "Unknown is not permission. Quarantine preserves the file while preventing it from entering the edit and release chain.",
      },
      takeaway: "Technical access, software license, asset rights, privacy permission, and publication authority are five different checks.",
    },
    "transcripts-shots-index": {
      kicker: "Understand · Module 03",
      title: "Build a time-coded evidence index",
      summary: "Combine media probes, transcripts, word alignment, shot boundaries, audio observations, and human correction without confusing measurement with meaning.",
      objective: "Produce a queryable evidence index that labels each value as measured, model-generated, human-verified, or creative inference.",
      artifact: "evidence-index.json + contact-sheet map",
      concepts: ["ASR", "word alignment", "shot boundary", "time base", "evidence origin"],
      sections: [
        {
          heading: "Inspect time before interpreting words",
          paragraphs: [
            "ffprobe exposes stream duration, time base, declared and average frame-rate fields, audio layout, and codec facts. Packet- or frame-level timestamps can flag possible variable frame rate; average and nominal rates alone do not prove CFR or VFR. Without that foundation, a transcript timestamp or cut boundary can look precise while pointing at the wrong frame.",
            "Whisper supplies a multilingual navigation layer; WhisperX adds forced alignment for candidate word-level timestamps. Names, numbers, negation, overlap, accents, music, and unsupported alignment languages remain human-review targets.",
          ],
          bullets: ["Declare every time unit", "Retain raw ASR output", "Mark confidence and uncertainty", "Relisten before quoting"],
          sourceIds: ["ffmpeg", "whisper", "whisperx"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "A shot boundary is not a story scene",
          paragraphs: [
            "PySceneDetect proposes visual boundaries through content, adaptive, or threshold detectors. Camera movement, flashes, fades, and static frames produce different false positives and misses; a statistics file helps calibrate rather than conceal that choice.",
            "The index links assets, time ranges, transcript spans, shots, loudness observations, contact-sheet frames, and reviewed descriptions. ‘Two people appear’ is an observation; ‘this shot expresses trust’ is an interpretation and needs a different label.",
          ],
          bullets: ["Keep detector method and threshold", "Allow merge, split, and moved boundaries", "Store machine and human layers separately"],
          sourceIds: ["pyscenedetect", "video-use"],
          evidenceMode: "engineering-synthesis",
        },
        {
          heading: "Analysis APIs and models drift",
          paragraphs: [
            "ASR models, aligners, detector APIs, and dependencies change. Pin the experiment environment, record model and tool versions, and retain input hashes so that a future re-index does not silently impersonate the earlier evidence bundle.",
            "An index accelerates retrieval; it does not prove a quotation, speaker identity, scene meaning, or authorization. Critical selections always return to the source audio and frames before approval.",
          ],
          sourceIds: ["whisper", "whisperx", "pyscenedetect", "video-use"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "Index an interview without hiding uncertainty",
        brief: "Create a time-coded evidence bundle for a short authorized interview and manually review every critical name, number, and quotation.",
        steps: ["Record ffprobe stream and time-base facts.", "Generate a machine transcript and word-alignment candidates.", "Generate shot boundaries plus a contact-sheet index.", "Human-review three central claims, all names, and all numbers.", "Label every field by evidence origin and review state."],
        artifact: "evidence-index.json with transcript, shot, probe, and review records.",
        reviewGate: "A content owner listens to every quotation that may enter the final cut and confirms its time range and context.",
        aiBoundary: "The agent may not invent descriptions for unavailable frames or turn a low-confidence name into an exact quotation.",
        template: "# Evidence index\n- Asset / time base:\n- Probe facts:\n- Transcript span + origin + confidence:\n- Shot candidate + detector + threshold:\n- Contact-sheet reference:\n- Human correction:\n- Creative interpretation (clearly labeled):\n- Unresolved ambiguity:",
      },
      checkpoint: {
        question: "A key name has low ASR confidence. What should the workflow do?",
        options: ["Replace it with the most common name", "Mark uncertainty, relisten to source audio, and obtain human confirmation", "Delete the whole interview", "Quote it because transcription finished"],
        correctIndex: 1,
        explanation: "ASR is a navigation and candidate-evidence layer. Critical names, numbers, and quotations return to the source.",
      },
      takeaway: "Precision-looking timestamps are still measurements with error, provenance, and a review state.",
    },
    "semantic-analysis-director": {
      kicker: "Understand · Module 04",
      title: "Let models propose, never pronounce",
      summary: "Use visual and language models to locate candidate moments while keeping exact boundaries, truth, and editorial meaning reviewable.",
      objective: "Design a planner–executor–reviewer loop whose candidate segments carry evidence, confidence, ambiguity, and an escalation route.",
      artifact: "candidate-segments.json + agent system card",
      concepts: ["visual hypotheses", "planner", "executor", "reviewer", "confidence", "escalation"],
      sections: [
        {
          heading: "Sample evidence instead of pretending the model watched perfectly",
          paragraphs: [
            "Video Use demonstrates a practical pattern: use transcript evidence as the main interface and generate richer visual timelines only where ambiguity demands it. That is more inspectable than asking a model to remember an entire file from sparse, undocumented sampling.",
            "Qwen3-VL can describe frames, read text, and propose approximate text-to-time matches. Its timestamps and semantic labels remain hypotheses; a reported frame-list timing mismatch is enough reason to verify every boundary against the actual media clock.",
          ],
          bullets: ["Expose the sampling policy", "Attach frame and transcript references", "Return ‘not found’ when evidence is absent"],
          sourceIds: ["video-use", "qwen3-vl", "x-video-use-release"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Planner, executor, and reviewer own different claims",
          paragraphs: [
            "The planner turns brief and evidence into candidate segments. The executor gathers or transforms only the evidence requested by a valid plan. The reviewer checks candidates against acceptance criteria and identifies ambiguity instead of merely scoring aesthetic fluency.",
            "A dynamic Director-style architecture is justified only when the next operation genuinely depends on observations. Fixed probe, transcription, or thumbnail steps remain deterministic automation and should not be wrapped in unnecessary model calls.",
          ],
          bullets: ["Planner cannot publish", "Executor cannot expand path or network authority", "Reviewer cannot silently rewrite the brief", "Human resolves meaning and portrayal"],
          sourceIds: ["videodb-director", "video-use"],
          evidenceMode: "engineering-synthesis",
        },
        {
          heading: "Version the model, prompt, sample, and evidence",
          paragraphs: [
            "A model name alone is not reproducibility. Record the exact service or local model, revision when available, sampling frames, prompt or rubric version, tool parameters, evidence bundle hash, and whether a human corrected the result.",
            "Model output cannot clear rights, establish speaker identity, or make a creative preference universal. When a repository or provider changes, rerun a small frozen evaluation set before accepting new candidate behavior.",
          ],
          sourceIds: ["qwen3-vl", "videodb-director", "x-video-use-release"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "Create evidence-backed candidate segments",
        brief: "Ask an analysis agent to propose six moments for a short cut while exposing exactly what it saw and where it remains uncertain.",
        steps: ["Define candidate labels from the approved brief.", "Select transcript spans and sampled frames with explicit policy.", "Generate candidates with evidence references, confidence, and ambiguity.", "Verify time boundaries against source media and shot/word indexes.", "Route high-risk or unresolved candidates to a human."],
        artifact: "candidate-segments.json and a bounded agent system card.",
        reviewGate: "An editor confirms that every candidate is grounded, context-preserving, and eligible to enter plan drafting.",
        aiBoundary: "The agent may propose relevance and visual meaning; it may not call an estimate a fact or hide a missing frame, transcript, or context span.",
        template: "# Candidate segment\n- Candidate ID:\n- Intended beat:\n- Source in / out:\n- Transcript evidence:\n- Frame / shot evidence:\n- Why it serves the brief:\n- Confidence:\n- Ambiguity:\n- Human review required because:\n- Status:",
      },
      checkpoint: {
        question: "How should the workflow treat a visual model’s timestamp for ‘the product reveal’?",
        options: ["As a frame-accurate fact", "As a candidate to verify against probe time base, frames, shots, and audio evidence", "As publication approval", "As proof that the footage is licensed"],
        correctIndex: 1,
        explanation: "Visual localization is useful retrieval evidence, but exact edit boundaries must return to an explicitly declared time base and source inspection.",
      },
      takeaway: "Models are strongest when they make inspectable proposals and weakest when the interface hides what they actually observed.",
    },
    "declarative-edit-plan": {
      kicker: "Edit · Module 05",
      title: "Represent the timeline as auditable data",
      summary: "Move editing decisions out of free-text shell commands and into a schema-valid plan that can be diffed, previewed, rejected, or compiled.",
      objective: "Create an edit-plan revision with stable operations, source and timeline ranges, reasons, evidence references, confidence, ambiguity, and review requirements; then freeze and hash it for a separate approval record.",
      artifact: "edit-plan.v2.json + Cut Plan Lab semantic-validation receipt",
      concepts: ["timeline data", "OTIO", "schema", "dry-run", "diff", "idempotency"],
      sections: [
        {
          heading: "A timeline is a decision record",
          paragraphs: [
            "Core .otio timeline data represents editorial structure and references media; it neither embeds nor decodes or renders media. OpenTimelineIO v0.18.1 also provides .otioz and .otiod bundle adapters that package content.otio with associated media. A bundle can therefore contain media, but OTIO still needs an execution application to decode, encode, or render it.",
          ],
          bullets: ["Separate source time from timeline time", "Declare units and time base", "Keep unsupported adapter fields", "Never call an OTIO file a render"],
          sourceIds: ["opentimelineio"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Validate, dry-run, diff, then execute",
          paragraphs: [
            "The course's original v2 plan binds each input to its media ID, expected hash, probe receipt, rights decision, and duration, and declares one rational time base. Each clip operation then carries an ID, kind, track, source media ID, integer source-frame range, timeline start frame, reason, evidence, confidence, ambiguity, rights state, and required human review. Free text alone cannot safely carry those invariants.",
            "VEAC and video-edit-cli illustrate agent-readable contracts: check structured operations, produce an intermediate or dry-run view, and preserve reasons plus provenance before delegating to FFmpeg. Timeline Studio adds inspect, diff, transactional writes, and idempotent operation IDs.",
            "JSON Schema checks shape, required fields, local ranges, enums, and fail-closed fixture states. A separate semantic validator checks source references, operation-ID uniqueness, positive and in-bounds frame ranges, timeline arithmetic, target tolerance, real hashes, and path containment; realpath and symlink checks must run in the executor. Neither layer can decide whether the story works—that remains editorial review.",
          ],
          bullets: ["Bind approval to plan hash", "Show added, removed, moved, and resized clips", "Make retries idempotent", "Keep a reversible source of truth"],
          sourceIds: ["veac", "video-edit-cli", "timeline-studio"],
          evidenceMode: "engineering-synthesis",
        },
        {
          heading: "Treat adapters and DSLs as changing edges",
          paragraphs: [
            "OTIO adapters, emerging DSLs, and editor-specific headless paths evolve independently. Keep one canonical plan, record every compiler or adapter version, and surface unmapped fields rather than silently dropping intent.",
            "The required lab uses an original browser-only fixture, not a third-party runtime. Its purpose is to pressure-test the contract even when a repository disappears or a tool changes syntax.",
          ],
          sourceIds: ["opentimelineio", "veac", "video-edit-cli", "timeline-studio"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "Build and pressure-test a 60-second plan",
        brief: "Select authorized interview clips, state why each survives, and create a versioned plan that another engine could execute without guessing.",
        steps: ["Select candidate segments from the evidence index.", "Add source ranges, rationale, evidence, confidence, ambiguity, and rights state.", "Run JSON Schema shape checks, then semantic reference, bounds, duration, hash, and path checks.", "Generate a dry-run summary and plan diff.", "Freeze the plan bytes; store its SHA-256 in a separate human approval record."],
        artifact: "edit-plan.v2.json, semantic-validation receipt, dry-run summary, plan diff, and separate approval record.",
        reviewGate: "An editor confirms order, contextual integrity, and target duration; approval names the exact plan hash.",
        aiBoundary: "The agent may not invent missing ranges, use uncleared media, issue arbitrary shell, or execute a revision newer than the approved plan.",
        template: "# Edit plan revision\nPlan fields (map these to edit-plan.v2):\n- Plan ID:\n- Target duration (frames):\n- Operation ID:\n- Source asset + expected input hash:\n- Source-frame start + duration:\n- Timeline start frame / track:\n- Reason and evidence refs:\n- Confidence and ambiguity:\n- Rights state / human review required:\nExternal receipt fields (not plan fields):\n- Frozen-plan SHA-256 + validation / diff receipt:\n- Creative-brief or delivery-matrix reference for aspect and output variant:\n- Separate approval-record reference:",
      },
      checkpoint: {
        question: "What is OpenTimelineIO’s correct role in this workflow?",
        options: ["A model that judges whether a story is true", "A social publishing service", "A representation and interchange layer for timeline structure, not a renderer", "A music-rights database"],
        correctIndex: 2,
        explanation: "OTIO carries editorial structure and metadata; actual media execution still belongs to FFmpeg, an NLE, Remotion, or another engine.",
      },
      takeaway: "A reviewable plan is the seam that keeps creative reasoning separate from irreversible media work.",
    },
    "deterministic-rendering": {
      kicker: "Edit · Module 06",
      title: "Compile approved plans into controlled, receipt-backed renders",
      summary: "Use FFmpeg for media operations and Remotion for code-driven graphics while retaining command, code, version, and output evidence.",
      objective: "Generate a versioned render receipt that proves what ran, against which inputs, with which license-sensitive build and output probe.",
      artifact: "render-receipt.json + controlled render plan",
      concepts: ["FFmpeg", "Remotion", "filtergraph", "frame timing", "render receipt", "license build"],
      sections: [
        {
          heading: "FFmpeg executes; it does not direct",
          paragraphs: [
            "FFmpeg can trim, concatenate, filter, crop, scale, pad, overlay, mix, caption, and encode. ffprobe can verify the result. The agent compiles only a validated plan into an allow-listed invocation; it does not ask the shell to interpret an unconstrained creative prompt.",
            "Fast stream-copy cuts may land near keyframes rather than exact frames; precise cuts usually require decoding and re-encoding. Record the full command, input hashes, FFmpeg version and configuration, exit code, stderr summary, and output probe.",
          ],
          bullets: ["Escape arguments", "Restrict input and output roots", "Disable overwrite by default", "Probe every final artifact"],
          sourceIds: ["ffmpeg"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Remotion makes graphics inspectable as code",
          paragraphs: [
            "Remotion treats frames and React components as an inspectable composition surface for titles, captions, charts, explainers, and brand templates. Its Agent Skills help coding agents create, preview, render, and maintain those projects.",
            "Generated code receives ordinary engineering review: type and lint checks, component preview, frame-range tests, overflow inspection, font and asset provenance, and a proxy render before full delivery. Code compilation is not brand or editorial approval.",
          ],
          bullets: ["Separate content data from visual components", "Preview components before full render", "Review generated code like any code", "Keep live-action rough cuts on a timeline route"],
          sourceIds: ["remotion", "remotion-skills", "x-remotion-skills"],
          evidenceMode: "engineering-synthesis",
        },
        {
          heading: "Licenses are part of the render environment",
          paragraphs: [
            "FFmpeg’s distributable license depends on the actual build configuration and optional codecs; Remotion uses a special license with a company-license threshold for some commercial organizations. Neither should be summarized as ‘free for everyone’.",
            "Before production, recheck current release notes, binary configuration, runtime license, font, music, stock, and component terms. A Skill repository license does not replace the Remotion runtime license.",
          ],
          sourceIds: ["ffmpeg", "remotion", "remotion-skills", "x-remotion-skills"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "Create a render and reproducibility receipt",
        brief: "Compile an approved plan into a safe FFmpeg operation and a small Remotion title card without letting either engine make editorial decisions.",
        steps: ["Resolve only approved assets and ranges.", "Generate an allow-listed FFmpeg invocation and dry-run summary.", "Create and preview a parameterized Remotion title component.", "Render to new versioned outputs.", "Probe outputs and record commands, code revision, versions, configuration, and errors."],
        artifact: "render-receipt.json, command plan, title component reference, and output probe.",
        reviewGate: "A technical reviewer confirms safe paths and valid output; an editor separately approves the visible result.",
        aiBoundary: "The agent may compile approved structure; it may not overwrite originals, hide command errors, infer license clearance, or treat exit zero as content approval.",
        template: "# Render receipt\n- Approved plan hash:\n- Input asset hashes:\n- Engine + version + build config:\n- Command or code revision:\n- Output path + hash:\n- Exit status / stderr summary:\n- Output probe:\n- Technical reviewer:\n- Editorial review state:",
      },
      checkpoint: {
        question: "What does a successful FFmpeg exit prove?",
        options: ["The video is licensed", "The story is effective", "The process completed according to the system; content, sync, captions, and rights still need review", "The agent may publish"],
        correctIndex: 2,
        explanation: "Execution success is one technical signal, not semantic, aesthetic, legal, accessibility, or release approval.",
      },
      takeaway: "A recorded render can repeat approved decisions when inputs, build, codecs, options, fonts, and hardware path are controlled; a reproducibility receipt is not a promise of cross-environment, bit-identical output or wise editorial judgment.",
    },
    "agent-tools-mcp": {
      kicker: "Edit · Module 07",
      title: "Operate CLI, Skill, MCP, and visible NLE surfaces safely",
      summary: "Give agents narrow, inspectable capabilities and reserve network, filesystem, generation, export, and project mutations for explicit authority.",
      objective: "Write a tool allow-list and dry-run contract for one agent-operated editing surface, including undo, cost, network, and recovery boundaries.",
      artifact: "tool-policy.yaml + mutation dry-run",
      concepts: ["CLI", "Skill", "MCP", "least privilege", "preview-first", "undo"],
      sections: [
        {
          heading: "Small tools make strong agent contracts",
          paragraphs: [
            "Montaj exposes schema-bound operations and a human-final lifecycle; QCut lets a machine-readable CLI and human-facing editor share one project; Velorn exposes many local MCP tools with preview-first patterns for ordinary writes.",
            "A Skill tells a host agent how to use a capability; MCP transports tool descriptions and calls; neither protocol supplies creative judgment. Name exactly which process owns reasoning, project state, filesystem writes, network access, and approval.",
          ],
          bullets: ["One operation, one schema", "Structured error states", "Visible project source of truth", "Preview before write"],
          sourceIds: ["montaj", "qcut", "velorn"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Professional NLE access needs stricter mutation rules",
          paragraphs: [
            "The Resolve MCP guide recommends read-only source inspection, sidecar analysis, dry-run plans before project mutation, disposable test projects, and explicit cleanup or recovery. Those controls matter more than how many tools the server exposes.",
            "Separate inspect from mutate, and separate project editing from generation, export, file creation, and social publishing. Each higher-impact capability gets its own permission, timeout, idempotency policy, and named approver.",
          ],
          bullets: ["Read current state first", "Prefer additive, undoable edits", "Test on a disposable project", "Provide recovery instructions"],
          sourceIds: ["davinci-resolve-mcp", "x-davinci-mcp", "qcut"],
          evidenceMode: "engineering-synthesis",
        },
        {
          heading: "New tool surfaces need a replaceable edge",
          paragraphs: [
            "Montaj, QCut, Velorn, and the Resolve MCP server are evolving quickly. Keep the course contract at the plan-and-tool boundary so a learner can swap the surface without rewriting intent, evidence, QC, or approval logic.",
            "Before use, recheck the supported application version, edition, local-versus-cloud path, license, provider keys, generation charges, undo coverage, and whether an action can affect files outside the project root.",
          ],
          sourceIds: ["montaj", "qcut", "velorn", "davinci-resolve-mcp", "x-davinci-mcp"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "Design a least-privilege editing tool policy",
        brief: "Choose a CLI, MCP, or NLE surface and define exactly what an agent may inspect, preview, change, generate, export, and never publish.",
        steps: ["Inventory tool categories and side effects.", "Split read-only, reversible write, file creation, network, paid generation, export, and publish permissions.", "Define schemas, roots, timeouts, cost bounds, and idempotency keys.", "Create a dry-run showing the exact mutation and recovery route.", "Have a human approve only the minimum required authority."],
        artifact: "tool-policy.yaml and a human-reviewed mutation dry-run.",
        reviewGate: "A technical owner approves least privilege and an editor confirms every mutation remains visible and recoverable.",
        aiBoundary: "The agent may not expand roots, expose keys, install providers, upload media, create paid generations, or publish without separate authorization.",
        template: "# Tool policy\n- Host agent:\n- Tool surface + version:\n- Read-only calls:\n- Reversible writes:\n- Non-undoable actions:\n- Allowed roots:\n- Network / provider path:\n- Cost and timeout:\n- Dry-run format:\n- Idempotency key:\n- Recovery:\n- Required approver:",
      },
      checkpoint: {
        question: "What does connecting an MCP server to an editor establish?",
        options: ["The server now has professional taste", "The host can call exposed tools under configured authority; judgment and safety still need explicit design", "Every action is undoable", "The project is officially endorsed by the editor vendor"],
        correctIndex: 1,
        explanation: "Tool access is capability, not judgment, official endorsement, or automatic authorization.",
      },
      takeaway: "The safest agent is not the one with the most tools; it is the one whose effects are narrow, visible, reviewable, and recoverable.",
    },
    "captions-audio-formats": {
      kicker: "Edit · Module 08",
      title: "Protect meaning across dialogue, captions, audio, and formats",
      summary: "Turn transcript-led rough cuts into accessible, listenable, and independently reviewed horizontal and vertical deliverables.",
      objective: "Create a delivery matrix that treats caption review, audio checks, graphics, and every aspect-ratio variant as separate acceptance surfaces.",
      artifact: "delivery-matrix.json + caption audit",
      concepts: ["semantic cuts", "captions", "audio", "aspect ratio", "safe zones", "variant QC"],
      sections: [
        {
          heading: "Edit from text, verify from sound and picture",
          paragraphs: [
            "Word alignment accelerates search, while Auto-Editor can propose loudness- or motion-based removals. Neither can see every reason a pause, breath, overlap, reaction, or filler belongs in a performance. Candidate deletions must return to the audiovisual source.",
            "A cut must not join words into a claim the speaker never made. Preserve context around negation, numbers, qualifications, questions, and emotional turns, and record every human rejection of an automated removal.",
          ],
          bullets: ["Transcript for retrieval", "Media for meaning", "Rules propose rather than decide", "Keep rejected automation evidence"],
          sourceIds: ["whisperx", "auto-editor"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Captions and audio are content, not decoration",
          paragraphs: [
            "Captions require reviewed words, meaningful segmentation, readable dwell time, speaker and sound treatment, language labels, safe zones, and editable sidecar delivery. Raw ASR is a draft; translated captions need their own provenance and reviewer.",
            "Audio review begins with intelligibility, clipping, abrupt cuts, sync, and the project’s current delivery target. Music rights and mix approval remain human responsibilities; an automatic ducking envelope still needs listening for masked meaning or pumping.",
          ],
          bullets: ["Editable captions plus burned-in preview", "Review names and numbers", "Inspect peaks and sync", "Record music rights separately"],
          sourceIds: ["whisperx", "ffmpeg"],
          evidenceMode: "engineering-synthesis",
        },
        {
          heading: "Reframe each variant instead of blindly cropping",
          paragraphs: [
            "A 9:16 version changes composition, multi-person framing, subtitle layout, graphics hierarchy, and implied emphasis. Crop windows belong to individual segments and require preview around cuts and occlusions.",
            "Remotion and FFmpeg can produce repeatable variants, but each output needs its own probe, caption check, visual-safe-area review, and approval. Passing the horizontal version never auto-passes the vertical version.",
          ],
          sourceIds: ["remotion", "ffmpeg", "auto-editor"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "Audit a captioned horizontal and vertical pair",
        brief: "Create two delivery plans from one approved cut without changing the speaker’s meaning or treating one variant’s success as the other’s evidence.",
        steps: ["Review every automated dialogue removal against source media.", "Correct caption words, segmentation, timing, and safe zones.", "Record dialogue, clipping, sync, and current loudness checks.", "Plan crop windows and graphics per segment for 9:16.", "Produce a separate QC row for every output."],
        artifact: "delivery-matrix.json, reviewed caption file, and audio/visual check receipts.",
        reviewGate: "A content reviewer, caption reviewer, audio reviewer, and editor each approve the exact relevant variant.",
        aiBoundary: "The agent may not alter meaning for duration, clear music, treat raw ASR as approved captions, or apply one crop blindly across the timeline.",
        template: "# Delivery matrix\n- Variant ID / aspect / resolution:\n- Approved cut hash:\n- Crop plan:\n- Caption language / reviewer:\n- Audio target / measurement:\n- Music rights reference:\n- Safe-zone review:\n- Technical probe:\n- Outstanding warning:\n- Human approval:",
      },
      checkpoint: {
        question: "What is the correct way to create a 9:16 version from an approved 16:9 cut?",
        options: ["Use one center crop for every shot without preview", "Auto-approve it because horizontal passed", "Plan framing per segment, reflow captions and graphics, then preview and verify independently", "Delete records for cropped-out people"],
        correctIndex: 2,
        explanation: "Aspect-ratio changes can alter composition, readability, and meaning, so each variant needs its own plan and review.",
      },
      takeaway: "Accessibility and delivery variants are editorial surfaces with their own evidence, not export checkboxes.",
    },
    "verification-human-review": {
      kicker: "Verify · Module 09",
      title: "Run bounded QC and keep judgment human",
      summary: "Separate machine-checkable delivery facts from semantic, aesthetic, rights, and release decisions, then bound every repair loop.",
      objective: "Produce an actionable verification report whose findings have time ranges, severity, evidence, owner, repair status, and escalation.",
      artifact: "verification-report.json + approval matrix",
      concepts: ["technical QC", "content integrity", "VMAF", "repair loop", "human judgment", "escalation"],
      sections: [
        {
          heading: "Metrics answer narrow questions",
          paragraphs: [
            "VMAF can compare aligned versions of the same content after encoding or processing. It cannot judge narrative, truth, captions, music, or a differently edited timeline. Use it only where the reference and distorted sequence actually correspond.",
            "A separately specified technical gate can use ffprobe and available FFmpeg filters to check decoding, duration, streams, resolution, frame rate, black or frozen frames, and audio signals; sync and caption bounds need their own declared algorithms and fixtures. Build capabilities must be probed, and each check records pass, fail, not-checked, or unavailable. A pass is never proof that the video is good or safe to publish.",
          ],
          bullets: ["Match metric to claim", "Retain inputs and configuration", "Never collapse not-checked into pass"],
          sourceIds: ["vmaf", "ffmpeg"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Human review owns meaning, taste, and consequence",
          paragraphs: [
            "Timeline Studio’s inspect-and-diff pattern and Resolve’s additive, reversible guidance make mechanical preparation safer. A dated creator post shows a planned Remotion-and-Claude-Code course broadening into a wider video-production guide as more techniques emerged. That is evidence of an evolving workflow surface—not evidence that an agent replaces an editor.",
            "Human review checks whether cuts preserve intent, B-roll creates false implications, captions change negation or names, humor and emotion land, people are portrayed responsibly, rights are sufficient, and disclosure or platform context is correct.",
          ],
          bullets: ["Technical", "Semantic and factual", "Rights and privacy", "Accessibility", "Editorial and release"],
          sourceIds: ["timeline-studio", "davinci-resolve-mcp", "x-creator-workflow-guide"],
          evidenceMode: "engineering-synthesis",
        },
        {
          heading: "A reviewer loop must know when to stop",
          paragraphs: [
            "Every finding names a version, time range, criterion, observation, expected state, severity, evidence, owner, and proposed action. Only explicit low-risk findings can enter automatic repair.",
            "Set maximum rounds, time, cost, and allowed fixes. If the same high-risk issue survives the limit, preserve the best version and complete failure chain, then escalate; the agent may not lower criteria or relabel failure as a warning.",
          ],
          sourceIds: ["timeline-studio", "davinci-resolve-mcp", "vmaf", "x-creator-workflow-guide"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "Complete a five-layer verification and one controlled repair",
        brief: "Inspect one delivery through technical, semantic, rights/privacy, accessibility, and editorial/release gates, then repair one approved low-risk issue.",
        steps: ["Run technical checks and record configuration.", "Review meaning, facts, B-roll implications, captions, rights, privacy, and platform context.", "Write locatable findings with severity and owners.", "Approve one low-risk repair diff.", "Recheck the finding and run regression checks."],
        artifact: "verification-report.json, repair diff, regression receipt, and approval matrix.",
        reviewGate: "Every critical finding is resolved, accepted by a named accountable owner, or blocks release; no score can waive it.",
        aiBoundary: "The agent may not lower standards, hide failures, retry forever, or automatically resolve facts, rights, portrayal, taste, or release decisions.",
        template: "# Verification finding\n- Artifact version / hash:\n- Layer and criterion:\n- Time range:\n- Observed / expected:\n- Severity:\n- Evidence:\n- Proposed repair and impact:\n- Accountable owner:\n- Status:\n- Regression result:\n- Escalation:",
      },
      checkpoint: {
        question: "The same high-risk content problem survives two allowed repair rounds. What should happen?",
        options: ["Retry forever", "Lower its severity", "Stop, preserve evidence and the best version, and escalate to the accountable human", "Delete the check"],
        correctIndex: 2,
        explanation: "Bounded loops and explicit escalation prevent an agent from manufacturing a completion state.",
      },
      takeaway: "A verifier is a measurement instrument; an accountable editor remains the decision-maker.",
    },
    "production-capstone": {
      kicker: "Verify · Module 10",
      title: "Package a recoverable, human-approved production workflow",
      summary: "Turn one successful cut into a recoverable release candidate with versioned state, runbook, evidence, permissions, and a human-only publish gate.",
      objective: "Assemble a package another operator can relink, dry-run, render, verify, and submit for approval without secrets or hidden state.",
      artifact: "release-package/ + approval-record.json",
      concepts: ["reproducibility evidence", "runbook", "checkpoint", "cloud workflow", "publish permission", "postmortem"],
      sections: [
        {
          heading: "Package decisions, not just a final MP4",
          paragraphs: [
            "A production package links the brief, media manifest, evidence index, canonical edit plan or OTIO, adapter or render code, configuration, versions, execution receipt, captions, outputs, verification, and approval. Large originals may remain external but must be access-controlled and relinkable.",
            "VideoDB Director shows dynamic orchestration; Mosaic exposes a cloud graph and asynchronous run surface. Both reinforce that system state belongs outside a chat transcript and that every stage needs an explicit input, output, failure state, and owner.",
          ],
          bullets: ["Version every stage", "Invalidate downstream approval after upstream change", "Keep secrets outside the package", "Record external services"],
          sourceIds: ["videodb-director", "opentimelineio", "ffmpeg", "mosaic-skills"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Render and publish are different authorities",
          paragraphs: [
            "The Mosaic post’s oEmbed-visible excerpt says a Slack-hosted agent used its API to clip, edit, and post; Mosaic documentation separately describes cloud runs and outputs. Together they establish a product path, not that the footage was cleared, the result independently evaluated, or unattended publication appropriate.",
            "The production design therefore issues separate permissions: render creates a release candidate; publish is a short-lived, human-authorized action after the exact artifact hash, QC, rights summary, warnings, and platform context have been reviewed.",
          ],
          bullets: ["No social token in prompts or repositories", "Human approval binds to one artifact hash", "No response is not consent", "A responsible do-not-publish decision can pass the capstone"],
          sourceIds: ["mosaic-skills", "x-mosaic-slack"],
          evidenceMode: "engineering-synthesis",
        },
        {
          heading: "Rehearse recovery before calling the system production-ready",
          paragraphs: [
            "A runbook states prerequisites, commands, approvals, expected artifacts, common failures, recovery, and escalation. Checkpoints record input versions so a rerun can resume safely rather than repeat paid calls or overwrite human edits.",
            "Provider behavior, model revisions, licenses, and privacy terms can change without the course changing. Any environment or upstream artifact change invalidates downstream preview, verification, and approval until those gates run again.",
          ],
          sourceIds: ["videodb-director", "opentimelineio", "ffmpeg", "mosaic-skills", "x-mosaic-slack"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "Prepare a release candidate another operator can recover",
        brief: "Package the course workflow without source secrets, rehearse a dry-run and interrupted resume, and submit one exact artifact for accountable approval.",
        steps: ["Map artifact and version relationships.", "Write a secret-free environment and dependency manifest.", "Document run, checkpoint, retry, recovery, and escalation steps.", "Have another operator execute a dry-run and resume simulation.", "Submit the exact candidate hash, QC, rights, warnings, and decision form to the approver."],
        artifact: "release-package/, runbook.md, recovery receipt, and approval-record.json.",
        reviewGate: "Only the named human release owner may change candidate to approved; unresolved critical blockers must produce do-not-release.",
        aiBoundary: "The agent may assemble evidence; it may not sign, infer consent, expose credentials, waive blockers, or publish externally on its own.",
        template: "# Release candidate\n- Release ID / artifact hash:\n- Brief, manifest, evidence, plan, render, caption refs:\n- Environment and versions:\n- Checkpoints and recovery:\n- Verification summary:\n- Rights / privacy summary:\n- Unresolved warnings:\n- Decision: publish | do not publish\n- Human approver / role / timestamp:\n- Postmortem:",
      },
      checkpoint: {
        question: "Who may approve external publication of the final video?",
        options: ["The last language model to run", "Anyone who can open the file", "The named accountable human who reviewed the exact version, QC, rights, and unresolved warnings", "The rendering engine"],
        correctIndex: 2,
        explanation: "Publishing has external consequences. An agent can prepare evidence, but authorization belongs to an informed, accountable human.",
      },
      takeaway: "Production readiness is the ability to explain, reproduce, recover, reject, and responsibly approve—not merely to render once.",
    },
  },
  finalAssessment: {
    title: "Final assessment: can you control the cut?",
    summary: "Score at least 80% and answer every critical authority, meaning, and rights question correctly. Passing records knowledge; it does not inspect your external files or authorize release.",
    passPercent: 80,
    questions: [
      { id: "q1", moduleTitle: "Operating loop", critical: false, question: "Which order matches the course control loop?", options: ["Execute → intent → publish", "Prompt → render → publish", "Intent → evidence → plan → preview → execute → verify → approve", "Evidence → publish → plan"], correctIndex: 2, explanation: "Responsibility moves from intent and evidence through a reviewed plan and execution to verification and human approval." },
      { id: "q2", moduleTitle: "System boundary", critical: false, question: "Which statement best describes an agent-ready tool?", options: ["It provides stable inputs, structured outputs, and inspectable errors to a host agent", "It decides the project goal", "It must have chat", "It may bypass approval"], correctIndex: 0, explanation: "A callable contract makes a tool useful to an agent without making the tool an agent." },
      { id: "q3", moduleTitle: "Rights and privacy", critical: true, question: "What is required before sensitive media enters an optional cloud AI feature?", options: ["Fast internet", "Deleting the local copy", "Calling the editor local-first", "A declared data path, authority, retention review, and informed permission"], correctIndex: 3, explanation: "Optional cloud processing needs explicit disclosure and authority; a desktop shell does not prove every feature is local." },
      { id: "q4", moduleTitle: "Evidence", critical: false, question: "How should a low-confidence critical transcript name be handled?", options: ["Auto-complete the common name", "Preserve uncertainty and verify against source audio", "Delete the interview", "Quote it unchanged"], correctIndex: 1, explanation: "Critical transcript content returns to the source and receives human confirmation." },
      { id: "q5", moduleTitle: "Timeline plan", critical: false, question: "Which contract makes a clip decision auditable?", options: ["Filename only", "Color only", "A hash-bound input, rational time base, integer source/timeline frames, evidence, reason, uncertainty, rights, and required human review—with approval in a separate record", "Prompt only"], correctIndex: 2, explanation: "The plan connects each operation to input identity, time, evidence, purpose, uncertainty, rights, and review; an external record binds approval to the frozen plan hash." },
      { id: "q6", moduleTitle: "Execution", critical: false, question: "Why is OTIO timeline data or a bundle still not a final video?", options: ["It represents—or may package—editorial data and media, but still requires a rendering application", "It stores only audio", "It deletes captions", "It only runs in cloud"], correctIndex: 0, explanation: "Core .otio data references media and bundle adapters may package it, but timeline interchange and media rendering remain distinct layers." },
      { id: "q7", moduleTitle: "Semantic integrity", critical: true, question: "An automated removal joins words into a claim the speaker never made. What is the correct outcome?", options: ["Keep it because the duration target passed", "Block the cut and restore truthful context", "Hide the transcript", "Let a visual metric decide"], correctIndex: 1, explanation: "Duration and fluency never authorize semantic distortion." },
      { id: "q8", moduleTitle: "Visual evidence", critical: false, question: "A licensed stock clip implies the wrong place. What should happen?", options: ["Use it because rights are cleared", "Delete location metadata", "Increase saturation", "Omit it, label it as illustration, or request matching authorized footage"], correctIndex: 3, explanation: "Rights clearance and factual or contextual fit are separate checks." },
      { id: "q9", moduleTitle: "Repair loop", critical: false, question: "A high-risk issue reaches its retry limit. What happens?", options: ["Stop, preserve evidence, and escalate to the accountable owner", "Retry forever", "Lower the standard", "Delete the issue"], correctIndex: 0, explanation: "A bounded system stops honestly and escalates instead of manufacturing completion." },
      { id: "q10", moduleTitle: "Release authority", critical: true, question: "When may a separate release record carry decision = approve-release?", options: ["When the agent is silent", "When rendering finishes", "When the named human signs the exact artifact after reviewing QC, rights, destination, and warnings", "When a file is uploaded"], correctIndex: 2, explanation: "Release approval is explicit, informed, version-bound, destination-bound, and accountable." },
    ],
  },
  capstone: {
    title: "The Verified Cut",
    summary: "Turn 5–10 minutes of authorized Chinese or English talking-head material into a 45–60 second 9:16 release candidate. Preserve meaning, use reviewed captions, and stop before external publication.",
    scenario: "A human approver needs a short, accessible video and the complete evidence required to publish—or a defensible recommendation not to publish. The audit trail matters as much as the MP4.",
    artifacts: [
      "Creative brief and observable acceptance criteria",
      "Media manifest with hashes, rights, consent, and network policy",
      "Transcript with reviewed critical names, numbers, and word timing",
      "Shot index and contact-sheet references",
      "Candidate segments with evidence, confidence, and ambiguity",
      "Schema-valid edit plan or OTIO timeline",
      "Plan diff and human plan-approval record",
      "FFmpeg or Remotion source, command, version, and render receipt",
      "Final 45–60 second 9:16 MP4",
      "Verification report covering technical, semantic, captions, rights, privacy, and delivery",
      "Human review checklist and unresolved-risk decisions",
      "Version-bound publish or do-not-publish decision with rationale",
    ],
    completionStatement: "I can point to all twelve artifacts, verified the exact candidate, and understand that this local record neither inspects those files nor authorizes publication.",
    reviewQuestions: [
      "Which expensive failure could earlier evidence have prevented?",
      "Which agent suggestion did a human reject, and on what evidence?",
      "Which steps were agent decisions, tool calls, automation, engine execution, and human authority?",
      "Which license, provider, or data path must be rechecked before a real release?",
      "Which upstream change would invalidate downstream preview, QC, or approval?",
      "What contract, schema, preview, or QC check should improve next—not merely the prompt?",
    ],
  },
} as const satisfies AgenticVideoEditingCourseCopy;
