import type { AgenticVideoEditingCourseCopy } from "../types";

const ui = {
  course: "课程",
  module: "模块",
  modules: "模块",
  minute: "分钟",
  minutes: "学习时间",
  phase: "阶段",
  phases: "阶段",
  sources: "来源",
  sourceAtlas: "来源图谱",
  artifact: "学习产物",
  practice: "应用练习",
  checkpoint: "模块检查点",
  evidence: "证据",
  evidenceMode: "证据模式",
  claimLedger: "原子主张台账",
  atomicClaim: "原子主张",
  exactLocator: "精确定位",
  sourceGrounded: "来源直接支持",
  instructionalSynthesis: "教学综合",
  coursePolicy: "课程政策",
  versionWatch: "版本观察",
  supports: "可以支持",
  boundary: "不能支持",
  rights: "权利处理",
  accessed: "访问日期",
  revision: "版本定位",
  license: "许可证",
  published: "发布日期",
  verification: "核验状态",
  corroboration: "佐证范围",
  tableOfContents: "课程地图",
  onThisPage: "本页内容",
  courseProgress: "你的制作笔记",
  progressLedger: "本地学习台账",
  browserStorageNote: "仅保存在此浏览器中；不需要账户，也不会上传。",
  progressEvidenceBoundary: "此百分比只由当前结构自洽的浏览器记录派生。浏览器不会核验产物字节、重跑命令、认证审核者、证明学习能力或授予发布权。",
  preflight: "P0 非正式预检凭据",
  preflightTitle: "M1 前用 20–30 分钟固定执行边界",
  preflightHelp: "选择 audit-only 或 production lane；声明只读输入、work、cache、receipt 与 output 目录；确认 JSON/YAML 工具；记录 fps、timecode 与 ffprobe 可用性；并写清宿主 secret-store 路径、upload/data path、网络、成本与批准边界。核心 fixture lane 完全离线且不需要 key。这份本地 P0 凭据只用于教学证据，不是生产授权。",
  runPreflight: "记录 P0 预检",
  progressPosition: "已完成 {complete} / {total} 个里程碑",
  complete: "已完成",
  pending: "待完成",
  nextUp: "下一步",
  resetProgress: "重置课程",
  resetConfirm: "要重置第 22 课的模块、产物、测验和综合项目进度吗？",
  resetDone: "第 22 课进度已重置。",
  resetDoneMemory: "本次会话进度已重置；浏览器存储仍不可用。",
  storageUnavailable: "浏览器存储不可用；本次学习记录只在当前标签页保留。",
  courseComplete: "课程记录已完成",
  moduleRecord: "模块记录",
  moduleComplete: "模块凭据记录已完成",
  moduleIncomplete: "完成证据门",
  completionInstruction: "通过检查点、由 validator 验证全部必填 schema 字段，并保存绑定准确 hash 的凭据后，才可完成本模块。",
  checkpointRequirement: "检查点已通过",
  checkpointPending: "检查点尚未通过",
  artifactRequirement: "字段有效且绑定 hash 的凭据已保存",
  artifactPending: "仍待 schema 或 semantic validator 凭据",
  saveArtifact: "保存学习产物",
  artifactSaved: "学习产物已在本地保存。",
  artifactLabel: "可编辑学习产物",
  artifactHint: "草稿区只用于工作；完成度必须来自模块 validator 闭合全部必填字段后签发的准确凭据合同。",
  draftNotCompletion: "保存草稿不计完成；只有 validator 凭据才计入。",
  validatorReceipt: "字段有效的 validator 凭据列表",
  browserReceiptBoundary: "浏览器只检查凭据结构与 lineage，不会重新运行 validator 命令。",
  saveReceipt: "保存 validator 凭据",
  receiptSaved: "凭据结构已在本地保存；浏览器没有重新运行 validator。",
  lineage: "先修凭据 lineage",
  readinessQuiz: "当前 readiness quiz 已通过",
  receiptReady: "凭据有效；通过综合项目门闭合",
  validationPending: "仍待验证",
  artifactLocator: "产物定位符",
  artifactSha256: "产物 SHA-256",
  learnerProjectId: "学习者综合项目 ID",
  reviewState: "复核状态",
  reviewedPass: "已复核：通过",
  reviewedBlocked: "已复核：阻断",
  reviewerId: "具名人工复核人",
  reviewedAt: "复核时间（含时区 ISO 8601）",
  timestampExample: "2026-08-28T00:00:00+08:00",
  capstoneReceipt: "M10 字段有效且绑定 hash 的凭据列表",
  capstoneEvidence: "12 条绑定项目、定位符、hash、复核人和状态的产物记录",
  currentAttempt: "当前作答",
  historicalBestPass: "历史最佳通过记录",
  changedLines: "处实质改写",
  selectAnswer: "请选择一个答案。",
  checkAnswer: "检查答案",
  correct: "回答正确",
  incorrect: "还没有",
  markComplete: "标记模块完成",
  previous: "上一模块",
  next: "下一模块",
  finalAssessment: "期末测验",
  assessmentPass: "通过标准：至少 {percent}%，且所有关键控制题必须正确。",
  submitAssessment: "提交并评分",
  assessmentPassed: "期末测验已通过",
  assessmentRetry: "请复习反馈后再次作答。",
  earlierPassRetained: "之前的通过记录仍保留，但本次作答没有通过。",
  score: "得分",
  criticalMiss: "仍有一道关键控制题回答错误。",
  capstone: "综合项目",
  capstoneInstruction: "只有当你能在发布包中指出对应文件时，才勾选该项。",
  capstoneAttestation: "我已审查准确的发布候选版本，并确认没有隐藏关键阻断项。",
  capstoneComplete: "综合项目记录已完成",
  capstoneStateDraft: "草稿：当前 v2 要求尚未全部完成。",
  capstoneStateCompleted: "已完成：当前 v2 receipt 与证据记录在版本和 lineage 上结构自洽。",
  capstoneStateStale: "已失效：历史完成记录仍保留，但不计入当前证据状态。",
  humanGate: "人工关口",
  aiBoundary: "智能体边界",
  workSequence: "工作顺序",
  sourceRegister: "来源登记",
  openExternal: "打开来源",
  githubRepository: "GitHub 仓库",
  xPost: "有日期的 X 实践信号",
  roleExecutionEngine: "执行引擎",
  roleAnalysisComponent: "分析组件",
  roleCodeDirectedWorkflow: "代码主导工作流",
  roleTimelineContract: "时间线契约",
  roleAgentArchitecture: "智能体架构",
  roleAgentToolSurface: "智能体工具接口",
  roleQualityControl: "质量控制",
  roleFieldSignal: "实践信号",
  oembedComplete: "可见帖文完整",
  oembedTruncated: "可见帖文被截断",
  officialXOembed: "X 官方 oEmbed",
  researchCutoff: "研究截止",
  systemRoles: "系统角色",
  pipeline: "制作闭环",
  pipelineFrame: "证据 → 剪辑",
  principlesLabel: "课程制作原则",
  courseFacts: "课程信息",
  courseBreadcrumb: "课程面包屑导航",
  allCourseModules: "全部课程模块",
  cutPlanLab: "剪辑计划实验",
  adjacentModules: "相邻模块",
  postmortem: "复盘",
  officialDocumentation: "官方文档",
  openStandard: "开放标准",
  legalPolicy: "法律或服务商政策",
  communityIssue: "未经核实的社区 issue",
  distinctions: "不要混淆这五层",
  outcomes: "你将能够交付",
  start: "开始第 22 课",
} as const;

export const AGENTIC_VIDEO_EDITING_ZH_HANS_COPY = {
  meta: {
    title: "如何使用智能体进行视频剪辑：从创作意图到经过验证的成片",
    shortTitle: "智能体视频剪辑",
    kicker: "第 22 课 · 基于 GitHub、开放标准与 X 有界信号的制作课程",
    summary: "把创作意图转化为有证据、可预览、可逆且可追溯的剪辑；最终发布权始终留给可追责的人类。",
    audience: "面向希望把智能体接入真实剪辑流程、同时不放弃编辑控制权的创作者、教师、产品团队与工程师。",
    prerequisite: "核心课程不需要付费账户或 API 密钥；生产练习具备基础命令行和 JSON 阅读能力会更顺利。",
    level: "入门到进阶",
    duration: "750 分钟 · 4 个阶段 · 10 个模块 · 12 个里程碑",
    startCta: "从剪辑契约开始",
    resumeCta: "继续制作笔记",
    translationNote: "此页面显示简体中文 authored candidate bundle。英文与简体中文 bundle 已编写，但具名人工 bundle 审核仍为 pending，发布状态保持 HOLD。",
    evidenceNote: "不可变 GitHub 快照支撑实现主张；官方文档与版本化开放标准支撑协议、无障碍、元数据与来源边界；法律政策与社区 issue 保持更窄的来源类别。X 帖仍只是有日期的实践信号，不能证明质量、速度、成本或普遍效果。",
  },
  ui,
  principles: [
    "意图先于工具",
    "原始素材永远只读",
    "每个主张指向证据",
    "计划先于任何修改",
    "高成本执行前先预览",
    "验证不能冒充批准",
    "发布必须由人授权",
  ],
  outcomes: [
    "编写含可观察验收标准、停止条件与明确批准人的创作简报。",
    "建立本地优先的媒体台账，记录哈希、权利、隐私、网络路径和 provenance。",
    "把 ffprobe、转录、镜头边界、音频与抽样帧观察组织为可查询证据索引。",
    "准确区分智能体系统、agent-ready 工具、代码主导工作流、媒体引擎与人类权限。",
    "产出含源区间、理由、证据引用、置信度、歧义、权利与人审要求的 schema-valid 剪辑计划，再由独立批准记录绑定其冻结 hash。",
    "把批准计划编译为受控的 FFmpeg、Remotion、CLI、MCP 或 NLE 操作，且不覆盖原片。",
    "分别验证技术交付、语义完整性、字幕、授权、隐私和平台语境。",
    "交付可编辑时间线、成片、执行凭据、QC、provenance 与人工发布决定组成的完整项目包。",
  ],
  distinctions: [
    ["智能体系统", "根据目标、状态、工具结果与反馈选择下一步；权限或证据不足时必须停止或升级。"],
    ["Agent-ready 工具", "向宿主智能体提供稳定输入、结构化输出与可检查错误；本身不追求开放式剪辑目标。"],
    ["代码主导工作流", "按编码好的规则或固定顺序执行，例如基于响度的停顿初剪；不会自行重规划。"],
    ["媒体引擎", "按命令、代码或时间线执行；FFmpeg 与 Remotion 不判断含义、权利、品味或发布。"],
    ["人类权限", "这是治理层而非另一种软件类型；知情的人类对编辑、权利、剩余风险与发布决定负责。"],
  ],
  phases: {
    define: {
      title: "定义委托",
      verb: "界定",
      summary: "分析开始前，明确意图、验收、素材权利、网络路径和人工权限。",
    },
    understand: {
      title: "通过证据理解",
      verb: "观察",
      summary: "索引技术事实、文字、镜头与经复核的视觉假设，不把模型输出伪装成真值。",
    },
    edit: {
      title: "通过计划剪辑",
      verb: "编排",
      summary: "把决定写成数据、预览差异，再让有边界的工具执行已批准版本。",
    },
    verify: {
      title: "验证并批准",
      verb: "交付",
      summary: "分别通过技术、语义、可访问性、权利与交付门，最后由人决定是否发布。",
    },
  },
  modules: {
    "agentic-editing-contract": {
      kicker: "定义 · 模块 01",
      title: "把创作意图变成剪辑契约",
      summary: "把模糊需求改写为可观察的制作合同，并诚实分配每个系统角色。",
      objective: "写出受众、核心主张、必须保留的上下文、禁止用途、验收标准、停止条件，以及计划批准人与发布批准人。",
      artifact: "creative-brief.json + 责任图",
      concepts: ["意图", "验收标准", "系统分类", "权限", "停止条件"],
      sections: [
        {
          heading: "发布演示不是运行契约",
          paragraphs: [
            "Video Use 的 X 帖是一个有日期的智能体辅助对镜头讲话工作流发布信号。转录→EDL→渲染及关键控制来自固定 SHA 的仓库，而不是被截断的 oEmbed 片段：先盘点源素材、提出策略、等待批准，然后才执行。演示顺畅不能取代这些关口。",
            "可执行简报必须写清受众、用途、平台、目标时长、核心主张、必须保留的语境、禁用素材与具体检查方法。‘剪得更有感染力’是一种偏好，不是验收测试。",
          ],
          bullets: ["价值判断缺失时先提问", "批准绑定明确角色", "未给出的限制保持未解决"],
          sourceIds: ["video-use"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "把推理与可调用能力分开",
          paragraphs: [
            "VideoDB Director 属于智能体架构，因为推理层根据请求选择能力；Montaj 属于 agent-ready 工具面，小型 schema 操作需要外部宿主智能体决定调用顺序与参数。",
            "正确命名会改变测试：工具测输入输出；自动化测触发与顺序；引擎测受控渲染与媒体一致性；智能体还要测策略、状态、预算、停止、升级与权限。",
          ],
          bullets: ["Agent 选择并重规划", "工具完成一个有边界的操作", "自动化遵循已编码规则", "引擎负责渲染"],
          sourceIds: ["videodb-director", "montaj"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "工具会变，契约要稳定",
          paragraphs: [
            "这些仓库大多仍很年轻，变化很快。课程稳定的主线不是复制某个发布周命令，而是严格区分意图、证据、计划、预览、执行、验证与批准。",
            "真实项目开始前，要重新打开当前 README、release、license 与数据路径。仓库、X 帖或版本号都不能授权客户素材，也不能证明今天的运行行为与课程快照完全相同。",
          ],
          sourceIds: ["video-use", "videodb-director", "montaj", "x-video-use-release"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "把一句需求改写成制作契约",
        brief: "把‘将访谈剪成有感染力的社交视频’改写为另一位编辑无需猜测即可审查的结构化委托。",
        steps: ["定义受众、观看情境、一个核心主张与预期行动。", "列出必须保留、允许压缩与禁止使用的内容。", "写出时长、画幅、字幕、真实性与交付检查。", "标记创意、事实、授权、隐私、安全与技术风险。", "指定计划批准人、发布批准人与停止条件。"],
        artifact: "完整的 creative-brief.json 与一页责任图。",
        reviewGate: "任何媒体分析前，委托人确认目标、红线、检查方法与具体责任人。",
        aiBoundary: "智能体可以发现缺失字段并提出措辞，但不能决定事实、人物形象、政治立场或发布权。",
        template: "# 剪辑契约\n- 受众：\n- 用途与预期行动：\n- 核心主张：\n- 必须保留：\n- 可以删减：\n- 禁止使用：\n- 验收检查：\n- 停止条件：\n- 计划批准人：\n- 发布批准人：\n- 尚待决定的未知项：",
      },
      checkpoint: {
        question: "面对‘剪得更有感染力’这一需求，最先应该做什么？",
        options: ["立即渲染三个成片", "定义受众、预期结果与可观察验收标准", "先增加更多转场", "让模型决定品牌立场"],
        correctIndex: 1,
        explanation: "‘有感染力’本身不可验证。必须先把它转化为受众结果与检查方法。",
      },
      takeaway: "再强的提示词，也比不上带证据、停止条件和明确责任人的简报。",
    },
    "media-ingest-provenance": {
      kicker: "定义 · 模块 02",
      title: "保护原片、权利与 provenance",
      summary: "建立本地优先工作区，把源证据与每个衍生文件、数据披露路径严格分开。",
      objective: "创建含稳定 ID、哈希、技术元数据、权利、隐私、网络政策、衍生关系与隔离状态的媒体清单。",
      artifact: "media-manifest.json + clock-receipt.json",
      concepts: ["只读原片", "ffprobe", "权利台账", "隐私", "provenance"],
      sections: [
        {
          heading: "用完整性证据保存原始素材",
          paragraphs: [
            "在创意理解之前，FFmpeg 与 ffprobe 可以读取时长、流、编解码器、帧率、time base、色彩与声道。把这些观察与稳定 asset ID、SHA-256 一起保存；hash 一致只证明相对于已记录 baseline 的字节身份，不能证明文件由谁创作、内容真实或用途已获授权。",
            "每个代理文件、提取音频、转录、预览与渲染都是有父素材和可复现操作的衍生物。原片保持只读，工作、缓存、分析与版本化渲染分别存放；但只读不等于 WORM 存储或签名审计日志。签名的 C2PA claim 可以保留声明的 provenance 与篡改证据，却不会自动证明内容真伪、同意、所有权或使用权利。",
          ],
          bullets: ["解释前先 probe", "绝不覆盖唯一副本", "代理文件可 relink", "每个输出有版本"],
          sourceIds: ["ffmpeg", "ffprobe-docs", "iptc-vmh-1-7", "c2pa-2-4"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "先检查，再修改",
          paragraphs: [
            "Timeline Studio、QCut 与 Resolve MCP 指南共享一种安全姿态：先 inspect 当前状态，展示拟议变化，保持源素材只读，把分析写入 sidecar，并保留 undo 或恢复路径。",
            "技术上能访问不等于权利已经清除。台账要记录所有权、拍摄同意、肖像、音乐、字体、品牌、第三方片段、改编、商业使用、地域、期限、上传与发布范围；未知必须阻断发布。",
          ],
          bullets: ["变更前 dry-run", "未知授权进入隔离", "渲染权与发布权分开", "人工覆盖要留痕"],
          sourceIds: ["timeline-studio", "qcut", "davinci-resolve-mcp"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "Local-first 不代表所有功能离线",
          paragraphs: [
            "桌面编辑器可以本地导出，但可选分析或生成仍可能把所选媒体发送给服务商。项目必须说明什么离开设备、发往哪里、为何必要、保留多久，以及谁有权同意。",
            "仓库许可证不会自动覆盖模型权重、素材、音乐、字体、服务商输出或人物肖像。要逐层核对，而不能把 GitHub 上的许可证徽章当作通用授权。",
          ],
          sourceIds: ["qcut", "ffmpeg", "davinci-resolve-mcp"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "建立可审计的素材接收包",
        brief: "盘点访谈、品牌片头、音乐与 B-roll，确保授权不明的素材不能进入分析或发布。",
        steps: ["分配 asset ID，记录哈希与 ffprobe 元数据。", "分离 originals、proxies、analysis、cache 与 renders。", "记录每项素材的权利、同意、允许用途、上传政策与到期日。", "所有未知项进入隔离，不能自动推断。", "为一个代理文件创建首条 provenance 事件。"],
        artifact: "media-manifest.json、clock-receipt.json、目录清单与 provenance 事件。",
        reviewGate: "可追责的权利批准人核验每一层适用权利的书面权限，并确认准确的本地或云端数据路径。",
        aiBoundary: "智能体不能把空白权利字段改成已授权，不能上传敏感素材、重命名原片或改写源元数据。",
        template: "# 媒体清单复核\n- Asset ID 与 SHA-256：\n- 来源与所有者：\n- 同意 / 肖像：\n- 允许的改编与平台：\n- 本地或云端处理路径：\n- 技术 probe 摘要：\n- 父子衍生关系：\n- 权利状态：cleared | restricted | unknown\n- 复核人和日期：",
      },
      checkpoint: {
        question: "一段 B-roll 可以播放，但来源与许可无法确认，应该怎么办？",
        options: ["因为能播放就默认可用", "先发布，投诉后再处理", "标记为 unknown、隔离并请求权利决定", "删除 provenance 字段"],
        correctIndex: 2,
        explanation: "未知不是许可。隔离既保留文件，也阻止它进入剪辑与发布链。",
      },
      takeaway: "技术访问、软件许可证、素材权利、隐私许可与发布权限是五项不同检查。",
    },
    "transcripts-shots-index": {
      kicker: "理解 · 模块 03",
      title: "建立带时间码的证据索引",
      summary: "组合媒体探测、转录、词级对齐、镜头边界、音频观察与人工修正，不把测量值混同为意义。",
      objective: "生成可查询索引，并把每个字段标为 measured、model-generated、human-verified 或 creative-inference。",
      artifact: "transcript-shot-index.json + 联系表索引",
      concepts: ["ASR", "词级对齐", "镜头边界", "time base", "证据来源"],
      sections: [
        {
          heading: "解释文字前先检查时间",
          paragraphs: [
            "ffprobe 暴露流时长、time base、声明/平均帧率、声道与编码事实；结合 packet 或 frame 时间戳可以标记潜在 VFR，但仅凭平均与名义帧率不能证明 CFR/VFR。没有这层基础，转录时间戳或切点看似精确，却可能指向错误画面。",
            "Whisper 提供多语言导航层，WhisperX 通过强制对齐给出候选词级时间戳。名字、数字、否定词、重叠语音、口音、音乐与不支持语言都仍需人工复核。",
          ],
          bullets: ["显式声明时间单位", "保留原始 ASR", "标记置信度与不确定性", "引用前回听"],
          sourceIds: ["ffmpeg", "ffprobe-docs", "whisper", "whisperx"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "镜头边界不等于故事场景",
          paragraphs: [
            "PySceneDetect 用 content、adaptive 或 threshold 检测器提出视觉边界；镜头运动、闪光、淡化与静止画面会产生不同误切与漏切，stats 文件用于校准，而不是掩盖阈值选择。",
            "索引连接资产、时间范围、转录片段、镜头、响度观察、联系表帧与经复核描述。‘出现两个人’是观察，‘该镜头表达信任’是解释，两者必须分字段标记。",
          ],
          bullets: ["保留检测方法与阈值", "允许合并、拆分与移动边界", "机器层与人工层分开"],
          sourceIds: ["pyscenedetect", "video-use"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "分析 API 与模型会漂移",
          paragraphs: [
            "ASR、对齐器、镜头检测 API 与依赖都会改变。固定实验环境，记录模型与工具版本，并保留输入哈希，避免未来重建索引时冒充早期证据包。",
            "索引可以显著加速检索，但不能证明引语、说话人身份、场景含义或素材授权。任何关键选段在批准前必须回到源音频与源画面逐项复核。",
          ],
          sourceIds: ["whisper", "whisperx", "pyscenedetect", "video-use"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "在不隐藏不确定性的前提下索引访谈",
        brief: "为一段短访谈创建带时间码的证据包，并人工复核所有关键人名、数字与引语。",
        steps: ["记录 ffprobe 流与 time-base 事实。", "生成机器转录与词级候选对齐。", "生成镜头边界与联系表。", "人工复核三个核心主张、全部人名和数字。", "为每个字段标注证据来源与复核状态。"],
        artifact: "含转录、镜头、probe 与复核记录的 transcript-shot-index.json。",
        reviewGate: "内容负责人回听所有可能进入成片的引语并确认其时间范围与上下文。",
        aiBoundary: "智能体不能为不可见帧编造描述，也不能把低置信人名写成精确引语。",
        template: "# 证据索引\n- Asset / time base：\n- Probe 事实：\n- 转录片段 + 来源 + 置信度：\n- 镜头候选 + 检测器 + 阈值：\n- 联系表引用：\n- 人工修正：\n- 创意解释（明确标记）：\n- 未解决歧义：",
      },
      checkpoint: {
        question: "关键人名的 ASR 置信度较低，正确做法是什么？",
        options: ["自动替换成最常见的人名", "标记不确定、回听源音频并由人确认", "删除整段访谈", "因为转录结束就直接引用"],
        correctIndex: 1,
        explanation: "ASR 是导航与候选证据层；关键名字、数字与引语必须返回源素材。",
      },
      takeaway: "看似精确的时间戳仍是带误差、provenance 与复核状态的测量值。",
    },
    "semantic-analysis-director": {
      kicker: "理解 · 模块 04",
      title: "让模型提案，不让模型宣判",
      summary: "用视觉与语言模型定位候选时刻，同时让精确边界、真实性与编辑含义始终可复核。",
      objective: "设计 planner–executor–reviewer 闭环，每个候选片段都有证据、置信度、歧义与升级路径。",
      artifact: "candidate-segments.json + 智能体系统卡",
      concepts: ["视觉假设", "planner", "executor", "reviewer", "置信度", "升级"],
      sections: [
        {
          heading: "抽样证据，而不是假装模型完整看过",
          paragraphs: [
            "Video Use 展示了一种实际模式：以转录为主要界面，只在歧义区域生成更丰富的视觉时间线。它比把稀疏且不透明的抽样伪装成‘模型看完全文’更可检查。",
            "M4 提供三条输出同一 candidate-segment schema 的 lane：manual review 与 recorded teaching fixture 是不需要 key 的离线核心；optional live-model lane 默认关闭。启用 live 分析前，必须明确服务商、网络、成本上限、upload/data path、模型版本、宿主注入凭据与具名人工批准。Qwen3-VL 的时间戳和标签仍是假设；社区 issue #1761 只是一条未经核验的报告，只能进入 version-watch 回归规划。",
          ],
          bullets: ["公开抽样政策", "引用帧与转录证据", "找不到时返回 not found"],
          sourceIds: ["video-use", "qwen3-vl", "qwen3-vl-issue-1761"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "规划者、执行者与审查者承担不同主张",
          paragraphs: [
            "规划者把简报与证据转为候选；执行者只按有效计划收集或转换证据；审查者依据验收标准指出歧义，而不只是给视觉流畅度打分。",
            "只有当下一步确实依赖观察结果时，才需要 Director 式动态架构。probe、转录或缩略图等固定步骤仍是代码主导工作流，不应加入不必要的模型调用。",
          ],
          bullets: ["规划者无发布权", "执行者不能扩大路径或网络权限", "审查者不能静默改写简报", "含义与人物形象交给人"],
          sourceIds: ["videodb-director", "video-use"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "版本化模型、提示、抽样与证据",
          paragraphs: [
            "仅记录模型名称不足以复现。还要记录服务或本地模型、可用 revision、抽样帧、提示或 rubric 版本、工具参数、证据包哈希与人工修正。",
            "模型输出不能清除权利、建立说话人身份或把创意偏好变成普遍规律。仓库或服务商变化后，要先在冻结的小型 eval set 上重新运行。",
          ],
          sourceIds: ["qwen3-vl", "videodb-director", "qwen3-vl-issue-1761", "x-video-use-release"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "生成有证据的候选片段",
        brief: "让分析智能体为短片提出六个时刻，同时公开它具体看到了什么、哪里仍不确定。",
        steps: ["从批准简报定义共享 candidate-segment schema。", "运行 manual 离线 lane 并记录证据定位。", "重放 recorded fixture lane 并比较同构 schema 输出。", "除非明确服务商、网络、成本、data path、模型版本、密钥注入与批准，否则保持 optional live-model lane 关闭。", "对照源素材核验时间边界，并把歧义交给具名人类。"],
        artifact: "candidate-segments.json 与有边界的智能体系统卡。",
        reviewGate: "编辑确认每个候选都有依据、语境完整且可以进入计划草拟。",
        aiBoundary: "智能体可以提出相关性与视觉含义，但不能把估计写成事实，也不能隐藏缺失帧、转录或上下文。",
        template: "# 候选片段\n- Candidate ID：\n- 目标节拍：\n- Source in / out：\n- 转录证据：\n- 帧 / 镜头证据：\n- 为什么服务简报：\n- 置信度：\n- 歧义：\n- 需要人工复核的原因：\n- 状态：",
      },
      checkpoint: {
        question: "视觉模型给出‘产品揭示’的时间戳，应该如何处理？",
        options: ["当作逐帧真值", "作为候选，并用 probe time base、帧、镜头与音频证据复核", "当作发布批准", "当作授权证明"],
        correctIndex: 1,
        explanation: "视觉定位适合检索，精确剪辑边界仍必须回到显式声明的 time base 与源素材。",
      },
      takeaway: "模型最有价值的状态是提出可检查的候选；最危险的界面则隐藏了它实际看过什么。",
    },
    "declarative-edit-plan": {
      kicker: "剪辑 · 模块 05",
      title: "把时间线表示为可审计数据",
      summary: "把剪辑决定从自由文本 shell 中移到可校验、可 diff、可预览、可拒绝与可编译的计划。",
      objective: "建立 select-only edit-plan.v2，先绑定准确的 M4 候选集产物与所选 lane，再记录稳定 operation、源/时间线区间、理由、证据、置信度、歧义与人审要求；最后由独立批准记录绑定冻结后的计划 hash。",
      artifact: "edit-plan.v2.json + Cut Plan Lab 语义校验凭据",
      concepts: ["时间线数据", "OTIO", "schema", "dry-run", "diff", "幂等"],
      sections: [
        {
          heading: "时间线是一份决策记录",
          paragraphs: [
            "核心 .otio 时间线数据表示剪辑结构并引用媒体；它不内嵌、解码或渲染媒体。OpenTimelineIO v0.18.1 另提供 .otioz/.otiod 文件包适配器，可把 content.otio 与相关媒体一起打包。因此 bundle 可以包含媒体，但 OTIO 仍需执行应用来解码、编码或渲染。",
          ],
          bullets: ["区分源时间与时间线时间", "声明单位与 time base", "保留 adapter 不支持字段", "OTIO 不是成片"],
          sourceIds: ["opentimelineio"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "先校验、dry-run 与 diff，再执行",
          paragraphs: [
            "课程原创 v2 plan 明确是 select-only：它只能选择已批准源区间，不能插入外部媒体、替换音频、添加字幕或标题，也不能发布。它从 M4 消费一个绑定 hash 的候选集引用；每项输入绑定 media ID、预期 hash、probe receipt、权利决定与时长，并声明统一 time base；每个 select operation 记录 ID、track、source media ID、整数 source-frame 区间、timeline start frame、理由、证据、置信度、歧义、权利状态与必须人审。",
            "VEAC 与 video-edit-cli 展示了 agent-readable 合同：检查结构化操作、生成中间表示或 dry-run，并在交给 FFmpeg 前保留理由与 provenance；Timeline Studio 又加入 inspect、diff、事务写入与幂等 operation ID。",
            "JSON Schema 检查形状、必填字段、局部数值范围、枚举和 fail-closed fixture 状态；独立语义 validator 再检查源引用、operation ID 唯一性、正数且不越界的帧区间、时间线算术、目标容差、真实 hash 与路径范围。realpath 与 symlink 检查必须在执行器环境完成。两层都不能判断故事是否成立，这仍是编辑审查。",
          ],
          bullets: ["批准绑定 plan hash", "展示增删移动与区间变化", "重试保持幂等", "保留可逆事实源"],
          sourceIds: ["veac", "video-edit-cli", "timeline-studio"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "把 adapter 与 DSL 当作可替换边缘",
          paragraphs: [
            "OTIO adapter、新兴 DSL 与编辑器 headless 路径分别演化。保留一个 canonical plan，记录每个编译器或 adapter 版本，并明确显示 unmapped 字段，不能静默丢失意图。",
            "必修实验使用原创浏览器 fixture，不依赖第三方 runtime；即使某仓库消失或语法改变，学习者仍能压力测试同一合同。",
          ],
          sourceIds: ["opentimelineio", "veac", "video-edit-cli", "timeline-studio"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "建立并压力测试 60 秒计划",
        brief: "选择已授权访谈片段，为每个保留决定写明理由，并产出任何执行引擎都无需猜测的版本化计划。",
        steps: ["从证据索引选择候选。", "加入源区间、理由、证据、置信度、歧义与权利状态。", "先运行 JSON Schema 形状检查，再做引用、边界、时长、hash 与路径语义检查。", "生成 dry-run 摘要与 plan diff。", "冻结计划字节，把其 SHA-256 写入独立人工批准记录。"],
        artifact: "edit-plan.v2.json、语义校验凭据、dry-run 摘要、plan diff 与独立批准记录。",
        reviewGate: "编辑确认顺序、语境完整性与目标时长；批准记录准确 plan hash。",
        aiBoundary: "智能体不能编造缺失区间、使用未授权素材、执行任意 shell，或运行比批准版本更新的计划。",
        template: "# 剪辑计划版本\nPlan 字段（必须映射到 edit-plan.v2）：\n- Plan ID：\n- 候选集 project / artifact ID / schema / SHA-256 / locator / selected lane：\n- 目标时长（帧）：\n- Operation ID：\n- 源素材 + 预期 input hash：\n- Source-frame start + duration：\n- Timeline start frame / track：\n- 理由与证据引用：\n- 置信度与歧义：\n- 权利状态 / 必须人审：\n外部凭据字段（不是 plan 字段）：\n- 冻结 plan 的 SHA-256 + 校验 / diff 凭据：\n- 画幅与输出版本的 creative brief 或 delivery matrix 引用：\n- 独立 approval-record 引用：",
      },
      checkpoint: {
        question: "OpenTimelineIO 在本工作流中的正确角色是什么？",
        options: ["判断故事真假的模型", "社交发布服务", "表达与交换时间线结构的层，而不是渲染器", "音乐授权数据库"],
        correctIndex: 2,
        explanation: "OTIO 携带剪辑结构与元数据；真正媒体执行仍属于 FFmpeg、NLE、Remotion 或其他引擎。",
      },
      takeaway: "可审查计划是创意推理与高影响媒体操作之间最重要的接缝。",
    },
    "deterministic-rendering": {
      kicker: "剪辑 · 模块 07",
      title: "把固定且已批准的计划编译为受控、留有凭据的渲染",
      summary: "用 FFmpeg 处理媒体、用 Remotion 生成代码驱动图形，并保留命令、代码、版本与输出证据。",
      objective: "生成版本化 render receipt，证明什么命令针对哪些输入、在何种许可敏感的 build 中执行，并记录输出 probe。",
      artifact: "render-receipt.json + 受控渲染计划",
      concepts: ["FFmpeg", "Remotion", "filtergraph", "逐帧时间", "渲染凭据", "build 许可证"],
      sections: [
        {
          heading: "FFmpeg 负责执行，不负责导演",
          paragraphs: [
            "FFmpeg 可以 trim、concat、filter、crop、scale、pad、overlay、mix、caption 与 encode，ffprobe 可以复核结果。代码主导渲染器只能把一个 hash 固定、已校验且通过 M6 permission envelope 的计划编译为 allow-list 调用，不能让 shell 解释不受约束的创意提示。",
            "快速 stream copy 可能只能落在关键帧附近，精确切割通常需要解码与重编码。要记录完整命令、输入哈希、FFmpeg 版本与 configuration、exit code、stderr 摘要和输出 probe。",
          ],
          bullets: ["安全转义参数", "限制输入输出根目录", "默认禁止覆盖", "每个最终产物都 probe"],
          sourceIds: ["ffmpeg", "ffmpeg-docs"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Remotion 让图形成为可审查代码",
          paragraphs: [
            "Remotion 把帧与 React component 变成可检查的标题、字幕、图表、解释动画与品牌模板；Agent Skills 帮助编码智能体创建、预览、渲染和维护项目。",
            "生成代码接受普通工程审查：type/lint、组件预览、帧范围、overflow、字体与资产 provenance，以及完整渲染前的代理版本。代码编译成功不代表品牌或编辑批准。",
          ],
          bullets: ["内容数据与视觉组件分离", "完整渲染前先组件预览", "生成代码照常 code review", "实拍粗剪仍走时间线路线"],
          sourceIds: ["remotion", "remotion-skills"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "许可证也是渲染环境的一部分",
          paragraphs: [
            "FFmpeg 最终二进制许可取决于实际 build 与可选 codec；Remotion 使用特殊许可证，部分较大商业组织需要公司许可证。两者都不能简单概括成‘所有人永久免费’。",
            "生产前重新检查 release note、binary configuration、runtime license、字体、音乐、stock 与组件条款。Skill 仓库许可证不能替代 Remotion runtime 许可证。",
          ],
          sourceIds: ["ffmpeg", "ffmpeg-docs", "remotion", "remotion-skills", "x-remotion-skills"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "创建渲染与复现凭据",
        brief: "把批准计划编译为安全 FFmpeg 操作和一个 Remotion 标题组件，两种引擎都不能自行做编辑决定。",
        steps: ["只解析已批准的素材与区间。", "生成 allow-list FFmpeg 调用与 dry-run 摘要。", "创建并预览参数化 Remotion 标题。", "写入新的版本化输出。", "Probe 输出并记录命令、代码 revision、版本、configuration 与错误。"],
        artifact: "render-receipt.json、命令计划、标题组件引用与输出 probe。",
        reviewGate: "技术复核人确认路径安全与输出有效；编辑另外批准可见结果。",
        aiBoundary: "智能体不能覆盖原片、隐藏命令错误、推断许可证已清除，或把 exit zero 当成内容批准。",
        template: "# 渲染凭据\n- 已批准 plan hash：\n- 输入 asset hash：\n- Engine + version + build config：\n- 命令或代码 revision：\n- 输出路径 + hash：\n- Exit status / stderr 摘要：\n- 输出 probe：\n- 技术复核人：\n- 编辑复核状态：",
      },
      checkpoint: {
        question: "FFmpeg 成功退出可以证明什么？",
        options: ["视频已经获得授权", "故事一定有效", "系统认为进程完成；内容、同步、字幕与权利仍需复核", "智能体可以发布"],
        correctIndex: 2,
        explanation: "执行成功只是一项技术信号，不是语义、审美、法律、可访问性或发布批准。",
      },
      takeaway: "固定输入、build、codec、参数、字体与硬件路径后，记录化渲染可重复执行批准决定；可复现凭据不等于跨环境逐位一致，也不会让编辑决定自动变得明智。",
    },
    "agent-tools-mcp": {
      kicker: "剪辑 · 模块 06",
      title: "安全操作 CLI、Skill、MCP 与可见 NLE",
      summary: "只给智能体狭窄、可检查的能力；网络、文件、生成、导出与工程修改都需要明确权限。",
      objective: "为一种智能体操作的剪辑表面编写 tool allow-list 与 dry-run 合同，覆盖 undo、成本、网络与恢复边界。",
      artifact: "tool-permission-envelope.yaml + 变更 dry-run",
      concepts: ["CLI", "Skill", "MCP", "最小权限", "preview-first", "undo"],
      sections: [
        {
          heading: "小工具才能形成强合同",
          paragraphs: [
            "Montaj 提供 schema-bound 操作与 human-final 生命周期；QCut 让机器可读 CLI 与人类编辑器共享同一工程；Velorn 为普通写操作展示 preview-first 与 undo 模式。",
            "Skill 告诉宿主智能体如何使用能力，MCP 传输工具描述与调用；它们都不提供创意判断。必须明确谁拥有推理、工程状态、文件写入、网络访问与批准。",
          ],
          bullets: ["一个操作一个 schema", "结构化错误状态", "人机共享可见事实源", "写入前先预览"],
          sourceIds: ["montaj", "qcut", "velorn", "mcp-2026-07-28"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "操作专业 NLE 需要更严格的修改规则",
          paragraphs: [
            "Resolve MCP 指南建议源素材只读、分析写 sidecar、工程修改前展示 dry-run、先用一次性测试工程，并明确清理与恢复。工具数量远不如这些控制重要。",
            "把 inspect 与 mutate 分开，再把工程编辑与生成、导出、创建文件、社交发布分开；影响越大的能力越需要独立 permission、timeout、幂等政策与批准人。",
          ],
          bullets: ["先读取当前状态", "优先新增且可撤销的编辑", "先在一次性工程测试", "提供恢复说明"],
          sourceIds: ["davinci-resolve-mcp", "qcut"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "新工具表面必须可替换",
          paragraphs: [
            "Montaj、QCut、Velorn 与 Resolve MCP 都快速演化。把课程合同放在 plan/tool 边界，学习者才能替换工具而不重写意图、证据、QC 与批准逻辑。",
            "使用前重新检查应用版本与 edition、本地或云端路径、license、provider key、生成费用、undo 覆盖，以及动作是否能影响工程根目录以外文件。",
            "绝不把 API key 或 access token 粘贴进 prompt 或 chat。密钥只能由宿主 secret store 或进程环境注入，并采用最小权限、短期凭据；日志与凭据必须脱敏，发生暴露后立即 rotate 或 revoke。仓库、课程包、学习产物、命令 URL、query string 与复制的诊断输出都不能包含 secret。",
          ],
          bullets: ["只允许宿主注入密钥", "最小权限与短有效期", "日志和凭据脱敏", "暴露后轮换或撤销", "仓库、课程包、prompt、chat 与 URL 均不得含密钥"],
          sourceIds: ["montaj", "qcut", "velorn", "davinci-resolve-mcp", "x-davinci-mcp"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "设计最小权限剪辑工具政策",
        brief: "选择 CLI、MCP 或 NLE，明确智能体可以 inspect、preview、change、generate、export 的范围，以及永远不能自行 publish。",
        steps: ["盘点工具类别与副作用。", "区分只读、可逆写、文件创建、网络、付费生成、导出与发布权限。", "定义 schema、根目录、timeout、成本与幂等 key。", "生成准确修改与恢复路径的 dry-run。", "由人只批准最低必要权限。"],
        artifact: "tool-permission-envelope.yaml 与经人工复核的变更 dry-run。",
        reviewGate: "技术负责人批准最小权限，编辑确认每项变更都可见且可恢复。",
        aiBoundary: "智能体不能扩大根目录、暴露密钥、安装服务商、上传媒体、付费生成或绕过独立发布授权。",
        template: "# 工具政策\n- 宿主智能体：\n- Tool surface + version：\n- 只读调用：\n- 可逆写入：\n- 不可撤销动作：\n- 允许根目录：\n- 网络 / 服务商路径：\n- 成本与 timeout：\n- Dry-run 格式：\n- 幂等 key：\n- 恢复路径：\n- 必需批准人：",
      },
      checkpoint: {
        question: "把 MCP server 接入编辑器可以证明什么？",
        options: ["服务器已经有专业品味", "宿主可在配置权限下调用暴露工具；判断与安全仍需显式设计", "所有动作都可撤销", "项目得到编辑器厂商官方背书"],
        correctIndex: 1,
        explanation: "工具访问是一种能力，不等于判断力、官方背书或自动授权。",
      },
      takeaway: "最安全的智能体不是工具最多，而是副作用狭窄、可见、可复核且可恢复。",
    },
    "captions-audio-formats": {
      kicker: "剪辑 · 模块 08",
      title: "在对白、字幕、音频与多画幅中保护含义",
      summary: "把基于转录的粗剪变成可访问、可听清且横竖屏分别审查的交付版本。",
      objective: "建立 delivery matrix，把字幕复核、音频检查、图形与每个画幅视为独立验收表面。",
      artifact: "delivery-matrix.json + variant-receipts.json",
      concepts: ["语义剪切", "字幕", "音频", "画幅", "安全区", "版本 QC"],
      sections: [
        {
          heading: "用文字定位，用声音与画面验证",
          paragraphs: [
            "词级对齐加速搜索，Auto-Editor 可以提出响度或运动删除；二者都看不到停顿、呼吸、重叠、表情或填充词为何属于表演。候选删除必须回到视听源。",
            "切点不能把词语拼成说话者未表达的主张。否定词、数字、限定条件、问题与情绪转折周围要保留语境，并记录人工拒绝自动删除的理由。",
          ],
          bullets: ["转录用于检索", "源媒体用于判断含义", "规则只提案不决定", "保留被拒绝自动化的证据"],
          sourceIds: ["whisperx", "auto-editor"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "字幕与音频都是内容层",
          paragraphs: [
            "字幕需要复核文字、合理断句、可读停留时间、说话人与声音说明、语言标签、安全区和可编辑 sidecar；原始 ASR 只是草稿，翻译字幕还需独立 provenance 与复核人。",
            "音频检查先看可懂度、削波、突变、同步与项目当前交付目标。音乐权利与混音批准仍属于人；自动 ducking 也要试听是否遮蔽语义或产生 pumping。",
          ],
          bullets: ["可编辑字幕 + 烧录预览", "复核人名与数字", "检查峰值与同步", "音乐权利单独记录"],
          sourceIds: ["whisperx", "ffmpeg-docs", "w3c-captions-guidance", "wcag22-captions-prerecorded"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "每个画幅都要重构，而不是盲裁",
          paragraphs: [
            "9:16 会改变构图、多人关系、字幕布局、图形层级与暗示重点；crop window 应按片段保存，并在切点与遮挡附近预览。",
            "Remotion 与 FFmpeg 可以重复生成版本，但每个输出都要有自己的 probe、字幕、安全区与人工批准。横屏通过永远不能自动让竖屏通过。",
          ],
          sourceIds: ["remotion", "ffmpeg", "ffmpeg-docs", "auto-editor"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "审计带字幕的横竖屏版本",
        brief: "从同一批准剪辑建立两个交付计划，不改变说话者含义，也不拿一个版本的成功当作另一个版本的证据。",
        steps: ["对照源媒体复核每项自动对白删除。", "修正字幕文字、断句、时间与安全区。", "记录对白、削波、同步与当前响度检查。", "按片段规划 9:16 crop 与图形。", "每个输出建立独立 QC 行。"],
        artifact: "delivery-matrix.json、variant-receipts.json、经复核字幕文件与音视频检查凭据。",
        reviewGate: "内容、字幕、音频与编辑复核人分别批准准确版本。",
        aiBoundary: "智能体不能为时长改变原意、清除音乐权利、把 ASR 当成已批准字幕，或对整条时间线盲目使用同一 crop。",
        template: "# 交付矩阵\n- Variant ID / aspect / resolution：\n- 已批准 cut hash：\n- Crop plan：\n- 字幕语言 / 复核人：\n- 音频目标 / 测量：\n- 音乐权利引用：\n- 安全区检查：\n- 技术 probe：\n- 未解决 warning：\n- 人工批准：",
      },
      checkpoint: {
        question: "从已批准的 16:9 剪辑制作 9:16 版本，正确方法是什么？",
        options: ["所有镜头使用同一居中裁切且不预览", "横屏通过就自动批准竖屏", "按片段规划构图、重排字幕与图形，并独立预览验证", "删除被裁掉人物的权利记录"],
        correctIndex: 2,
        explanation: "画幅改变会影响构图、可读性与含义，因此每个版本都有自己的计划与审查。",
      },
      takeaway: "可访问性与交付版本是独立编辑表面，不是导出对话框中的勾选项。",
    },
    "verification-human-review": {
      kicker: "验证 · 模块 09",
      title: "运行有边界的 QC，把判断留给人",
      summary: "把机器可检查的交付事实与语义、审美、权利和发布决定分开，并限制每一次修复循环。",
      objective: "生成可行动的 verification report，每项发现都有时间范围、严重等级、证据、责任人、修复状态与升级路径。",
      artifact: "verification-report.json",
      concepts: ["技术 QC", "内容完整性", "VMAF", "修复循环", "人工判断", "升级"],
      sections: [
        {
          heading: "指标只能回答狭窄问题",
          paragraphs: [
            "VMAF 可以比较同一内容经编码或处理后的对齐版本，不能判断叙事、真实性、字幕、音乐或不同剪辑时间线。只有参考与失真序列真正对应时才应使用。",
            "另行定义的技术门可用 ffprobe 与实际可用的 FFmpeg filter 检查解码、时长、流、分辨率、帧率、黑帧/冻结帧和音频信号；同步与字幕边界需要各自声明算法与 fixture。必须先 probe build 能力，并为每项记录 pass、fail、not-checked 或 unavailable。通过绝不表示视频好看或可发布。",
          ],
          bullets: ["指标与主张匹配", "保留输入与配置", "not checked 绝不等于 pass"],
          sourceIds: ["vmaf", "ffprobe-docs", "ffmpeg-docs"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "含义、品味与后果归人类审查",
          paragraphs: [
            "Timeline Studio 的 inspect/diff 与 Resolve 的新增式、可逆操作能降低机械准备风险。一则有日期的创作者帖子显示，原拟的 Remotion×Claude Code 课程随着更多技术出现而扩展成更广的视频制作指南；这只证明工作流表面仍在演化，不能证明智能体取代剪辑师。",
            "人类要检查删减是否保持原意、B-roll 是否制造错误暗示、字幕是否改错否定词或人名、幽默与情绪是否成立、人物形象是否负责、授权是否充分，以及披露和平台语境。",
          ],
          bullets: ["技术", "语义与事实", "权利与隐私", "可访问性", "编辑与发布"],
          sourceIds: ["timeline-studio", "davinci-resolve-mcp"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "审查循环必须知道何时停止",
          paragraphs: [
            "每项发现都要写明版本、时间范围、标准、观察、期望状态、严重等级、证据、责任人和建议动作；只有明确、低风险的问题可以自动修复。",
            "预设最大轮次、时间、成本与允许修复类型。相同高风险问题达到上限后，保留最佳版本和完整失败链并升级；智能体不能降低标准或把 fail 改成 warning。",
          ],
          sourceIds: ["timeline-studio", "davinci-resolve-mcp", "vmaf", "x-creator-workflow-guide"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "完成五层验证与一次受控修复",
        brief: "用技术、语义、权利/隐私、可访问性与编辑/发布五层审查一个交付物，再修复一个获批的低风险问题。",
        steps: ["运行技术检查并记录配置。", "复核含义、事实、B-roll 暗示、字幕、权利、隐私与平台语境。", "写出可定位、带严重等级与责任人的发现。", "批准一个低风险 repair diff。", "复查原问题并运行回归检查。"],
        artifact: "verification-report.json，包含 repair diff 与回归凭据；其中不得包含 release decision。",
        reviewGate: "每个 critical finding 必须已解决、由具名责任人接受风险，或明确阻断发布；分数不能豁免。",
        aiBoundary: "智能体不能降低标准、隐藏失败、无限重试，或自动处理事实、权利、人物形象、品味与发布决定。",
        template: "# 验证发现\n- Artifact version / hash：\n- 层与标准：\n- 时间范围：\n- 观察 / 期望：\n- 严重等级：\n- 证据：\n- 建议修复与影响：\n- 责任人：\n- 状态：\n- 回归结果：\n- 升级：",
      },
      checkpoint: {
        question: "相同高风险内容问题在两轮允许修复后仍存在，应该怎么办？",
        options: ["无限重试", "降低严重等级", "停止、保留证据和最佳版本，并升级给可追责的人", "删除该检查"],
        correctIndex: 2,
        explanation: "有限循环与显式升级可以防止智能体伪造完成状态。",
      },
      takeaway: "验证器是一种测量工具；可追责的编辑仍然是决定者。",
    },
    "production-capstone": {
      kicker: "验证 · 模块 10",
      title: "封装可恢复、由人批准的生产工作流",
      summary: "M1–M9 与 readiness quiz 通过后，把一次成功剪辑变成可恢复的 capstone release candidate，包含版本化状态、runbook、证据、权限与 human-only 发布门。",
      objective: "组装另一位操作员无需秘密或隐藏状态即可 relink、dry-run、渲染、验证并提交批准的项目包。",
      artifact: "production-dossier.json + release-decision.json",
      concepts: ["复现证据", "runbook", "checkpoint", "云工作流", "发布权限", "postmortem"],
      sections: [
        {
          heading: "打包决定，而不只是 final.mp4",
          paragraphs: [
            "M1–M9 guided lineage 是独立的先修记录。Readiness quiz 通过后，M10 必须使用新获授权的学习者媒体和新的 projectId，以同一组 schema 重建全新的链：简报、媒体与时钟凭据、转录/镜头索引、候选片段、canonical select-only edit plan、工具权限 envelope、渲染凭据、delivery matrix 与 variant receipts，以及 verification report。大型原片可外部引用，但必须可控访问并可 relink。",
            "VideoDB Director 展示动态编排，Mosaic 展示云端图与异步运行；两者都说明系统状态不能只藏在 chat transcript 里，每个阶段都要有输入、输出、失败状态与责任人。",
          ],
          bullets: ["每阶段版本化", "上游改变使下游批准失效", "秘密不得进入包、UI、提示、日志、URL 或凭据", "记录外部服务"],
          sourceIds: ["videodb-director", "opentimelineio", "ffmpeg", "mosaic-skills", "mosaic-api-docs", "iptc-vmh-1-7", "c2pa-2-4"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "渲染与发布是两种权限",
          paragraphs: [
            "Mosaic 帖子的 oEmbed 可见片段只说明 Slack 中的智能体用 API clip、edit 与 post；云端运行及输出机制由 Mosaic 文档另行支持。两者共同证明产品路径存在，但不能证明档案素材已授权、结果经过独立评估，或无人值守发布合理。",
            "因此 production design 必须拆分权限：render 只创建 release candidate；publish 是人审准确 artifact hash、QC、权利摘要、warning 与平台语境后的短期授权动作。",
          ],
          bullets: ["社交 token 不进入提示或仓库", "人工批准绑定一个 artifact hash", "未回复不等于同意", "负责任的 do-not-publish 可以通过综合项目"],
          sourceIds: ["mosaic-skills", "mosaic-api-docs", "mosaic-legal-policy"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "称为 production-ready 前先演练恢复",
          paragraphs: [
            "Runbook 写明前置条件、命令、批准、预期产物、常见失败、恢复与升级；checkpoint 记录输入版本，让重跑安全恢复，不重复付费调用或覆盖人工修改。",
            "服务商行为、模型 revision、license 与隐私条款可能变化。环境或上游产物一旦改变，下游 preview、verification 与 approval 都必须重新运行。",
          ],
          sourceIds: ["videodb-director", "opentimelineio", "ffmpeg", "mosaic-skills", "x-mosaic-slack"],
          evidenceMode: "version-watch",
        },
      ],
      practice: {
        title: "准备另一位操作员可以恢复的发布候选",
        brief: "打包课程工作流而不包含源秘密，演练 dry-run 与中断恢复，并提交一个准确 artifact 给可追责批准人。",
        steps: ["绘制产物与版本关系。", "写出不含秘密的环境与依赖清单。", "记录运行、checkpoint、重试、恢复与升级。", "让另一位操作员完成 dry-run 和恢复演练。", "提交准确 candidate hash、QC、权利、warning 与决定表。"],
        artifact: "production-dossier.json、runbook.md、恢复凭据与 release-decision.json。",
        reviewGate: "只有具名人类发布负责人可以把 candidate 改为 approved；未解决关键阻断必须输出 do-not-release。",
        aiBoundary: "智能体可以整理证据，但不能代签、推断同意、暴露凭据、豁免阻断或自行发布。",
        template: "# 发布候选\n- Release ID / artifact hash：\n- 简报、清单、证据、计划、渲染、字幕引用：\n- 环境与版本：\n- Checkpoint 与恢复：\n- 验证摘要：\n- 权利 / 隐私摘要：\n- 未解决 warning：\n- 决定：publish | do not publish\n- 人工批准人 / 角色 / 时间：\n- Postmortem：",
      },
      checkpoint: {
        question: "谁可以批准最终视频对外发布？",
        options: ["最后运行的语言模型", "任何能打开文件的人", "审查准确版本、QC、权利与未解决风险的具名可追责人类", "渲染引擎"],
        correctIndex: 2,
        explanation: "发布会产生外部后果。智能体可以准备证据，授权必须由知情且可追责的人完成。",
      },
      takeaway: "Production-ready 是能够解释、复现、恢复、拒绝并负责任批准，而不只是成功渲染一次。",
    },
  },
  finalAssessment: {
    title: "期末测验：你能控制这条剪辑吗？",
    summary: "至少 80%，并且权限、含义与权利三类关键题全部正确。通过只记录知识，不会检查外部文件，也不授权发布。",
    passPercent: 80,
    questions: [
      { id: "q1", moduleSlug: "agentic-editing-contract", moduleTitle: "制作闭环", critical: false, question: "哪一个顺序符合本课程控制闭环？", options: ["执行→意图→发布", "提示→渲染→发布", "意图→证据→计划→预览→执行→验证→批准", "证据→发布→计划"], correctIndex: 2, explanation: "责任从意图和证据，经受审计划与执行，走向验证与人工批准。" },
      { id: "q2", moduleSlug: "agent-tools-mcp", moduleTitle: "系统边界", critical: false, question: "哪一句最准确描述 agent-ready tool？", options: ["向宿主智能体提供稳定输入、结构化输出与可检查错误", "自行决定项目目标", "必须有聊天界面", "可以绕过批准"], correctIndex: 0, explanation: "可调用合同让工具适合智能体使用，但不会使它本身成为智能体。" },
      { id: "q3", moduleSlug: "media-ingest-provenance", moduleTitle: "权利与隐私", critical: true, question: "敏感素材进入可选云端 AI 功能前必须具备什么？", options: ["足够快的网络", "删除本地副本", "把编辑器称为 local-first", "明确数据路径、权限、保留审查与知情许可"], correctIndex: 3, explanation: "可选云处理需要明确披露与授权；桌面外壳不证明全部功能本地运行。" },
      { id: "q4", moduleSlug: "transcripts-shots-index", moduleTitle: "证据", critical: false, question: "低置信关键人名应该如何处理？", options: ["自动补全常见人名", "保留不确定性并对照源音频复核", "删除访谈", "直接引用"], correctIndex: 1, explanation: "关键转录内容必须返回源素材并由人确认。" },
      { id: "q5", moduleSlug: "declarative-edit-plan", moduleTitle: "时间线计划", critical: false, question: "哪种合同让 clip 决定可审计？", options: ["只有文件名", "只有颜色", "绑定 hash 的输入、有理数 time base、整数源/时间线帧、证据、理由、不确定性、权利与必须人审；批准另存独立记录", "只有提示词"], correctIndex: 2, explanation: "计划把 operation 连接到输入身份、时间、证据、目的、不确定性、权利与人审；外部记录再把批准绑定到冻结 plan hash。" },
      { id: "q6", moduleSlug: "deterministic-rendering", moduleTitle: "执行", critical: false, question: "为什么 OTIO 时间线数据或 bundle 仍不等于最终视频？", options: ["它表示、并可能打包剪辑数据与媒体，但仍需要渲染应用生成成片", "只保存音频", "会删除字幕", "只能在云端运行"], correctIndex: 0, explanation: "核心 .otio 数据引用媒体，bundle adapter 可以打包媒体，但时间线交换与媒体渲染仍是不同层。" },
      { id: "q7", moduleSlug: "captions-audio-formats", moduleTitle: "字幕、音频与语义完整性", critical: true, question: "自动对白剪切及其字幕删掉了否定词，改变了说话者原意；正确结果是什么？", options: ["时长达标就保留", "阻断候选，回到源音频，恢复语境并复核修正后的字幕", "隐藏转录", "让视觉指标决定"], correctIndex: 1, explanation: "时长、流畅度、响度和字幕语法都不能授权语义失真；源音频和无障碍字幕都必须复核。" },
      { id: "q8", moduleSlug: "semantic-analysis-director", moduleTitle: "视觉证据", critical: false, question: "已授权库存画面暗示了错误地点，应该怎么办？", options: ["有授权就直接使用", "删除地点元数据", "提高饱和度", "省略、明确标为示意，或请求匹配且获授权的素材"], correctIndex: 3, explanation: "权利清除与事实/语境匹配是两项独立检查。" },
      { id: "q9", moduleSlug: "verification-human-review", moduleTitle: "修复循环", critical: false, question: "高风险问题达到重试上限后怎么办？", options: ["停止、保留证据并升级给责任人", "无限重试", "降低标准", "删除问题"], correctIndex: 0, explanation: "有边界的系统诚实停止并升级，而不是制造完成状态。" },
      { id: "q10", moduleSlug: "verification-human-review", moduleTitle: "发布权限", critical: true, question: "何时可以让独立 release record 写入 decision = approve-release？", options: ["智能体不再提问", "渲染完成", "具名人类审查准确 artifact、QC、权利、目的地与 warning 后签字", "文件上传后"], correctIndex: 2, explanation: "发布批准必须显式、知情、绑定版本、绑定目的地且可追责。" },
    ],
  },
  capstone: {
    title: "经过验证的成片",
    summary: "M1–M9 字段有效产物与 readiness quiz 通过后，把拥有权利的 5–10 分钟中英文口播素材制作为 45–60 秒 9:16 发布候选；保留原意、使用经复核字幕，并停在外部发布之前。",
    scenario: "人工批准人需要一条短而可访问的视频，以及足以决定发布或不发布的完整证据。审计链与 MP4 同等重要。",
    artifacts: [
      { artifactId: "capstone-creative-brief", label: "创作简报与可观察验收标准" },
      { artifactId: "capstone-media-manifest", label: "含哈希、权利、同意与网络政策的媒体清单" },
      { artifactId: "capstone-clock-receipt", label: "授权媒体的时钟与 time-base 凭据" },
      { artifactId: "capstone-transcript-shot-index", label: "含关键人名、数字、时间与联系表定位的转录—镜头索引" },
      { artifactId: "capstone-candidate-segments", label: "含证据、置信度、歧义与复核状态的候选片段" },
      { artifactId: "capstone-edit-plan", label: "只做选择式剪辑的 edit-plan.v2 及其准确批准 hash" },
      { artifactId: "capstone-tool-permission-envelope", label: "覆盖密钥、网络、成本与修改边界的工具权限包络" },
      { artifactId: "capstone-render-receipt", label: "FFmpeg 或 Remotion 命令、版本、输出 hash 与渲染凭据" },
      { artifactId: "capstone-delivery-matrix", label: "覆盖画幅、字幕、音频、权利与安全区的交付矩阵" },
      { artifactId: "capstone-variant-receipts", label: "包含最终 45–60 秒 9:16 MP4 的版本凭据" },
      { artifactId: "capstone-verification-report", label: "覆盖技术、语义、无障碍、权利、隐私与交付发现的验证报告" },
      { artifactId: "release-decision", label: "具名人类绑定准确版本并说明理由的发布或不发布决定" },
    ],
    completionStatement: "我可以指出全部 12 项产物，复核了准确的发布候选，并理解这项本地记录既不会检查那些文件，也不会授权发布。",
    reviewQuestions: [
      "哪一个昂贵失败本可以通过更早的证据避免？",
      "人类拒绝了智能体哪项建议，依据是什么？",
      "哪些步骤属于智能体决定、工具调用、自动化、引擎执行与人工权限？",
      "真实发布前必须重新核验哪个许可证、服务商或数据路径？",
      "哪个上游变化会使下游预览、QC 或批准失效？",
      "下次应改进哪项契约、schema、预览或 QC，而不仅是提示词？",
    ],
  },
} as const satisfies AgenticVideoEditingCourseCopy;
