import type {
  AgenticVideoEditingCheckpointCopy,
  AgenticVideoEditingClaimCopy,
  AgenticVideoEditingConceptCopy,
  AgenticVideoEditingCourseCopy,
  AgenticVideoEditingFinalQuestionCopy,
  AgenticVideoEditingPracticeCopy,
  AgenticVideoEditingSectionCopy,
} from "../types";
import { AGENTIC_VIDEO_EDITING_MODULE_SLUGS } from "../types";
import { AGENTIC_VIDEO_EDITING_EN_COPY } from "./en";
import type { AgenticVideoEditingUiCopy } from "./en";

const en = AGENTIC_VIDEO_EDITING_EN_COPY;

type NonEmptyClaims = readonly [AgenticVideoEditingClaimCopy, ...AgenticVideoEditingClaimCopy[]];
type NonEmptyStrings = readonly [string, ...string[]];
type ConceptTranslations = readonly [readonly [string, string], ...(readonly [string, string])[]];
type OptionTranslations = readonly [
  readonly [string, string],
  readonly [string, string],
  readonly [string, string],
  readonly [string, string],
];

function localizeClaims(source: NonEmptyClaims, texts: NonEmptyStrings): NonEmptyClaims {
  if (source.length !== texts.length) throw new Error("Course 20 bilingual claim count drift");
  return source.map((claim, index) => ({ ...claim, text: texts[index] })) as unknown as NonEmptyClaims;
}

function localizeSection(
  source: AgenticVideoEditingSectionCopy,
  heading: string,
  paragraphs: NonEmptyStrings,
  bullets?: NonEmptyStrings,
): AgenticVideoEditingSectionCopy {
  if (Boolean(source.bullets) !== Boolean(bullets)) throw new Error(`Course 20 bilingual bullet drift: ${heading}`);
  return {
    ...source,
    heading,
    paragraphs: localizeClaims(source.paragraphs, paragraphs),
    ...(source.bullets && bullets ? { bullets: localizeClaims(source.bullets, bullets) } : {}),
  };
}

function localizeConcepts(
  source: readonly [AgenticVideoEditingConceptCopy, ...AgenticVideoEditingConceptCopy[]],
  translations: ConceptTranslations,
): readonly [AgenticVideoEditingConceptCopy, ...AgenticVideoEditingConceptCopy[]] {
  if (source.length !== translations.length) throw new Error("Course 20 bilingual concept count drift");
  return source.map((concept, index) => ({
    ...concept,
    term: translations[index][0],
    definition: translations[index][1],
  })) as unknown as readonly [AgenticVideoEditingConceptCopy, ...AgenticVideoEditingConceptCopy[]];
}

type PracticeTranslation = Pick<
  AgenticVideoEditingPracticeCopy,
  "title" | "brief" | "steps" | "artifact" | "reviewGate" | "aiBoundary" | "acceptanceChecks"
>;

function localizePractice(
  source: AgenticVideoEditingPracticeCopy,
  translation: PracticeTranslation,
): AgenticVideoEditingPracticeCopy {
  return { ...source, ...translation };
}

function localizeCheckpoint(
  source: AgenticVideoEditingCheckpointCopy,
  question: string,
  options: OptionTranslations,
  explanation: string,
): AgenticVideoEditingCheckpointCopy {
  return {
    ...source,
    question,
    options: source.options.map((option, index) => ({
      ...option,
      label: options[index][0],
      feedback: options[index][1],
    })) as unknown as AgenticVideoEditingCheckpointCopy["options"],
    explanation,
  };
}

function localizeFinalQuestion(
  source: AgenticVideoEditingFinalQuestionCopy,
  _moduleTitle: string,
  question: string,
  options: OptionTranslations,
  explanation: string,
): AgenticVideoEditingFinalQuestionCopy {
  return {
    ...source,
    question,
    options: source.options.map((option, index) => ({
      ...option,
      label: options[index][0],
      feedback: options[index][1],
    })) as unknown as AgenticVideoEditingFinalQuestionCopy["options"],
    explanation,
  };
}

const ui = {
  contentLocale: "zh-Hans",
  course: "课程", module: "模块", modules: "模块", minute: "分钟", minutes: "学习时间", phase: "阶段", phases: "阶段",
  sources: "来源", sourceAtlas: "来源图谱", artifact: "学习产物", practice: "应用练习", checkpoint: "模块检查点",
  evidence: "证据", evidenceMode: "证据模式", sourceGrounded: "来源直接支持", engineeringSynthesis: "工程综合",
  versionWatch: "版本观察", supports: "可以支持", boundary: "不能支持", rights: "权利处理", accessed: "访问日期",
  revision: "版本定位", license: "许可证", published: "发布日期", verification: "核验状态", corroboration: "佐证范围",
  tableOfContents: "课程地图", onThisPage: "本页内容", courseProgress: "你的制作笔记", progressLedger: "本地学习台账",
  backupTools: "备份或迁移本课程",
  backupBoundary: "备份只包含已保存的第 20 课浏览器记录，并原样包含学习者已保存的产物文本；这些文本可能含有你输入的路径、标识符、凭据或其他敏感内容。备份不会自动收集媒体 bytes、浏览器文件 handle 或其他课程记录。当前标签页中尚未提交的产物、测评、Capstone 与 Cut Plan 草稿不会进入备份；请先保存或下载。共享前务必检查并删改 JSON 中的敏感内容。",
  backupExport: "导出第 20 课备份",
  backupRestore: "恢复第 20 课备份",
  backupWorking: "正在检查备份…",
  backupExported: "第 20 课备份已下载。共享文件前，请检查学习者撰写的文本。",
  backupExportFailed: "无法创建备份。浏览器进度未改变。",
  backupTooLarge: "该备份超过 5 MB，因此未读取。",
  backupRestoreConfirm: "是否用该已验证备份替换全部已保存的第 20 课记录？成功恢复还会丢弃当前标签页中尚未提交的产物、测评、Capstone 与 Cut Plan 草稿；其他课程不会改变。",
  backupRestoreCancelled: "已取消恢复。浏览器进度未改变。",
  backupRestored: "第 20 课备份已恢复。Current／stale 状态已重新计算；其他课程已保留。",
  backupRestoredMemory: "由于浏览器存储不可用，第 20 课备份只在当前标签页恢复；原有未提交草稿已保留。",
  backupRestoredScratchWarning: "已恢复第 20 课的保存记录，但无法清除当前标签页中的未提交草稿。请先下载所需草稿，再谨慎重新加载页面。",
  backupRestoreFailed: "该文件未通过第 20 课的版本、inventory 或 checksum 合同。浏览器进度未改变。",
  browserStorageNote: "仅保存在此浏览器中；不需要账户，也不会上传。", progressPosition: "已完成 {complete} / {total} 个里程碑",
  complete: "已完成", pending: "待完成", nextUp: "下一步", resetProgress: "重置课程",
  resetConfirm: "是否删除第 20 课全部已保存的产物文本、旧版草稿、回执、检查点、测评与 Capstone 记录，以及当前标签页中的全部未提交草稿？此操作无法撤销。请先导出备份并下载尚未保存的草稿；其他课程不会改变。", resetDone: "第 20 课进度已重置。",
  resetDoneMemory: "本次会话进度已重置；浏览器存储仍不可用。", storageUnavailable: "浏览器存储不可用；记录只在当前标签页保留。",
  courseComplete: "核心课程已完成", moduleRecord: "模块记录", moduleComplete: "模块已完成", moduleIncomplete: "完成证据门",
  moduleStateCurrent: "当前有效", moduleStateRepair: "需要修复", moduleStateInProgress: "进行中", moduleStateNext: "下一步", moduleStateNotStarted: "尚未开始",
  clearAssessmentAnswers: "清除答案", clearAssessmentConfirm: "是否清除当前标签页中全部尚未提交的测评答案？已保存的模块与课程记录不会改变。", assessmentCleared: "未提交的测评答案已清除；已保存的课程记录未改变。",
  completionInstruction: "通过检查点并保存有效且 current 的产物；阅读与草拟始终开放。",
  checkpointRequirement: "检查点已通过", checkpointPending: "检查点尚未通过", artifactRequirement: "产物有效且 current",
  artifactPending: "产物尚未有效", saveArtifact: "验证并保存产物", artifactSaved: "产物与验证凭据已在本地保存。",
  artifactLabel: "机器可读产物", artifactHint: "字符数只作草稿提示；完成必须通过解析、合同、依赖 hash 与人审检查。",
  localFileHash: "在不上传的情况下计算本地文件 hash",
  localFileHashBoundary: "浏览器只读取所选 bytes 以计算 SHA-256；二进制、路径与文件 handle 不会上传或写入 localStorage。请自行把显示的身份复制到相应 artifact 字段。",
  chooseLocalFile: "选择本地文件",
  localFileHashFailed: "浏览器无法计算该文件的 hash；没有上传或保存任何内容。",
  localFileName: "文件名（不可信显示数据）",
  localFileBytes: "字节数",
  changedLines: "处实质改写", selectAnswer: "请选择一个答案。", checkAnswer: "检查答案", correct: "回答正确", incorrect: "还没有",
  markComplete: "标记模块完成", previous: "上一模块", next: "下一模块", finalAssessment: "期末测验",
  assessmentPass: "通过标准：至少 {percent}%，且所有关键控制题必须正确。", submitAssessment: "提交并评分",
  assessmentPassed: "期末测验已通过", assessmentRetry: "请阅读选项级反馈后再次作答。",
  earlierPassRetained: "之前的知识通过记录仍保留；绑定版本的批准不会保留。", score: "得分",
  criticalMiss: "仍有一道关键控制题回答错误。", capstone: "综合项目",
  capstoneInstruction: "为准确 artifact hash 登记证据；只有布尔值的声明不能完成综合项目。",
  capstoneAttestation: "我已复核准确 package hash，并作出可追责的 do-not-publish 或 approve 决定。",
  capstoneComplete: "综合项目证据 current",
  capstoneRubric: "综合项目量规 · 五个维度，每项 0–3 分",
  capstoneRubricRule: "至少 12/15；权限／权利／隐私与证据／语义完整性各不得低于 2 分；未解决关键 blocker 必须为零。",
  capstoneRubricAuthority: "权限、权利与隐私",
  capstoneRubricEvidence: "证据与语义完整性",
  capstoneRubricTraceability: "计划、工具与执行可追溯性",
  capstoneRubricDelivery: "交付、字幕、音频与无障碍",
  capstoneRubricVerification: "验证、恢复与人工决定",
  capstoneRubricUnscored: "尚未评分",
  capstoneRubricTotal: "量规总分",
  capstoneRubricEvidencePrompt: "请选择当前产物登记表能完整支持的最高等级。",
  capstoneRubricAuthority0: "权限、权利或隐私证据缺失或相互矛盾",
  capstoneRubricAuthority1: "已有部分记录，但所有权、目的或目的地仍未解决",
  capstoneRubricAuthority2: "已记录 current 权限、权利、隐私、目的与目的地",
  capstoneRubricAuthority3: "达到 2 级，且有独立审核、保留、删除与恢复证据",
  capstoneRubricEvidence0: "主张缺少 current 证据，或序列改变了来源含义",
  capstoneRubricEvidence1: "证据不完整、链接弱，或含义审核仍未解决",
  capstoneRubricEvidence2: "每项主张与片段都绑定 current 证据，且含义已审核",
  capstoneRubricEvidence3: "达到 2 级，且有独立质疑、修复轨迹与回归证据",
  capstoneRubricTraceability0: "没有可复现计划、工具边界或执行 receipt",
  capstoneRubricTraceability1: "已有计划，但版本、权限、输入或输出不完整",
  capstoneRubricTraceability2: "Current 计划、已批准工具、固定输入、版本与 receipt 已链接",
  capstoneRubricTraceability3: "达到 2 级，且有独立 dry-run、中断、续传与重新链接证据",
  capstoneRubricDelivery0: "交付、字幕、音频、色彩或无障碍门缺失或失败",
  capstoneRubricDelivery1: "部分检查通过，但必需格式或无障碍决定仍未关闭",
  capstoneRubricDelivery2: "Current 交付、字幕、音频、色彩、构图与无障碍检查均通过",
  capstoneRubricDelivery3: "达到 2 级，且有独立播放、变体与目的地专属审核",
  capstoneRubricVerification0: "没有 current 验证、恢复证据或可问责人工决定",
  capstoneRubricVerification1: "验证不完整，或审核者无法复现与恢复 package",
  capstoneRubricVerification2: "已有 current 验证、恢复演练与绑定 hash 的人工决定",
  capstoneRubricVerification3: "达到 2 级，且有独立复现、有边界修复与批准刷新",
  humanGate: "人工关口", aiBoundary: "智能体边界", workSequence: "工作顺序",
  sourceRegister: "来源登记", openExternal: "打开来源", githubRepository: "GitHub 仓库", xPost: "有日期的 X 实践信号",
  roleExecutionEngine: "执行引擎", roleAnalysisComponent: "分析组件", roleDeterministicAutomation: "规则自动化",
  roleTimelineContract: "时间线契约", roleAgentArchitecture: "智能体架构", roleAgentToolSurface: "智能体工具接口",
  roleQualityControl: "质量控制", roleFieldSignal: "实践信号", oembedComplete: "可见帖文完整",
  roleProtocolSpecification: "协议规范", roleSecurityGuidance: "安全指导", roleAccessibilityStandard: "无障碍标准",
  roleAudioStandard: "音频标准", roleColorManagement: "色彩管理", roleEditorialGuidance: "编辑指导",
  roleLegalGuidance: "特定法域指导", roleMediaProvenance: "媒体来源与流转",
  oembedTruncated: "可见帖文被截断", officialXOembed: "X 官方 oEmbed", researchCutoff: "研究截止",
  systemRoles: "系统角色", pipeline: "制作闭环", distinctions: "不要混淆这五层", outcomes: "你将能够交付",
  start: "开始第 20 课", auditCore: "fixture-safe 浏览器合同", productionPracticum: "fixture-safe 本地媒体实验", coreProgress: "fixture-safe 浏览器合同进度",
  practicumProgress: "fixture-safe 本地实验进度",
  coreCompleteBoundary: "课程完成只表示十个模块 receipt、当前测验 receipt 与十二项 Capstone 证据闭环均为 current；它不是证书、权利证明或发布授权。",
  practicumCompleteBoundary: "本地实验 receipt 路径只覆盖第一方合成 fixture；只有导入 current 实验 receipts 才能声称 synthetic portfolio locally attested。它不是证书、法律许可、服务器认证、production-sandbox 验证或发布授权。",
  readingOpen: "所有课程始终可阅读；只有完成状态会被 current 上游产物软门控。",
  artifactValid: "产物有效", artifactBlocked: "产物被阻断", artifactStale: "产物已过期",
  diagnosticOnly: "十个模块 receipt 及其十二项必需产物全部 current 前，结果只作诊断。",
  approved: "已批准的产物／决定",
  artifactAcceptancePassed: "JSON、语义策略、依赖与绑定人审检查均已通过。",
  artifactNeedsWork: "产物尚未 current-valid",
  artifactSaveFailed: "无法保存产物。草稿仍保留在编辑器中；请检查浏览器存储后重试。",
  artifactStatus: "草稿状态",
  assessmentDiagnostic: "仅作诊断：完成全部十个 current 核心模块后，才能记录通过。",
  assessmentDiagnosticOnly: "当前仅为诊断模式。以下核心模块 current 前，不能记录正式通过：",
  assessmentFormalReady: "所有核心模块均已 current。本次作答可记录正式知识门。",
  assessmentMemoryOnly: "由于浏览器存储不可用，该结果只会在当前标签页保留。",
  assessmentPassStale: "之前保存的通过记录已不再是当前有效状态。请先修复最早的阻断里程碑，再重新参加正式测评。",
  assessmentRequiredReason: "所有核心模块均已 current。记录 Capstone 前仍需通过正式测评。",
  assessmentAnswered: "已作答 {answered} / {total}",
  assessmentIncomplete: "请回答全部题目后再评分。焦点已移至第一道未作答题。",
  assessmentDraftRecovered: "已恢复当前标签页中尚未提交的测评答案。",
  auditCoreProgress: "fixture-safe 浏览器合同进度",
  blocked: "已阻断",
  capstoneChangedDuringSave: "在对登记表进行 hash 时，某项前置条件已改变。未记录任何内容；请刷新 blocker 后重试。",
  capstoneDecisionArtifactBrief: "十个模块 receipt 与 current 测验 receipt 全部存在后，由具名人员为准确 package 记录决定。合成路径必须保持 do-not-publish。",
  capstoneDecisionArtifactTitle: "测验后产物 12 · 绑定版本的发布决定",
  capstoneEvidenceRegistry: "十二项产物证据登记表",
  capstoneHashBound: "已保存决定与每个 current 产物 hash 及 current 正式测评相匹配。",
  capstoneMemoryOnly: "该证据登记表在当前标签页中为 current，但浏览器存储不可用。",
  capstoneRecorded: "已记录 current 证据登记表与 do-not-publish 决定。",
  capstoneRequiredReason: "正式测评已 current。请验证全部十二项稳定产物，并记录绑定版本的人工 do-not-publish 决定。",
  capstoneSaveFailed: "无法记录证据登记表。未创建任何发布权限；请检查浏览器存储后重试。",
  capstoneModuleMissing: "模块里程碑尚未 current。",
  capstoneArtifactMissing: "缺少 current 有效 receipt／hash。",
  capstoneAssessmentMissing: "正式测评缺失或 stale；早期诊断结果不能满足此门。",
  capstoneReviewerMissing: "绑定 hash 的 do-not-publish 决定需要可问责审核者角色。",
  capstoneRubricBlocked: "五维量规总分必须至少为 12/15；权限／权利／隐私与证据／语义完整性各至少为 2 分；且不得留有未解决的关键 blocker。",
  capstoneStoredStale: "已保存 Capstone 记录已被阻断、stale、格式错误，或绑定到旧产物 hash。",
  capstoneDecisionStep1: "确认十个模块 receipt 与测验 receipt 均为 current。",
  capstoneDecisionStep2: "绑定准确的候选与 package SHA-256 值。",
  capstoneDecisionStep3: "记录未解决风险与可问责审核者角色。",
  capstoneDecisionStep4: "保持智能体发布权限为 false。",
  capstoneDecisionStep5: "为合成 fixture 选择 do-not-publish。",
  capstoneDecisionReviewGate: "该产物属于测验后 Capstone，而非 M10 完成状态。任一模块、产物、测验蓝图、package hash 或未解决关键 blocker 改变都会使其失效。",
  capstoneDecisionAiBoundary: "智能体可以准备记录，但不能代替可问责的人工声明，也不能授权发布。",
  capstoneDecisionAcceptance1: "Current package hash 已绑定。",
  capstoneDecisionAcceptance2: "Current 候选 hash 已绑定。",
  capstoneDecisionAcceptance3: "审核者角色与理由明确。",
  capstoneDecisionAcceptance4: "智能体发布权限保持 false。",
  capstoneDecisionAcceptance5: "合成决定为 do-not-publish。",
  verifiedCut: "Verified Cut",
  continueCapstone: "继续前往 Capstone",
  capstoneDraftRecovered: "已恢复当前标签页中尚未提交的 Capstone 量规。",
  unsavedCapstoneConfirm: "你有尚未提交、且不属于已保存课程进度的 Capstone 量规。是否离开此页？返回时，当前标签页会尝试恢复它。",
  checkpointMemoryOnly: "检查点已在当前标签页通过，但浏览器存储不可用。",
  completionBoundary: "课程完成与本地实验进度都不是证书、权利许可、production-sandbox 验证或发布授权。",
  contentHash: "Canonical 内容 SHA-256",
  copyLegacyDraft: "将旧草稿复制到编辑器",
  coursePolicy: "课程 fail-closed 策略",
  current: "当前有效",
  datedObservation: "有日期的观察",
  datedOfficialWeb: "有日期的官方指导",
  datedRepositoryIssue: "未确认的有日期用户报告",
  doNotPublishDecision: "该合成 package 已绑定 do-not-publish。这是成功的安全决定，而非发布失败。",
  downloadJson: "下载已验证产物",
  downloadDraft: "下载草稿",
  jurisdictionGuidance: "依法域而定的指导",
  lawRegulation: "特定法域的法律或法规",
  legacyDraft: "已保留 v1.1 草稿，需要转换",
  legacyProgress: "已保留旧版自由文本草稿。v1.2.0 已清除旧版完成、检查点、测评与 Capstone 状态。",
  moduleCompletionBlocked: "由于必需门已改变，未记录完成状态。请检查 blocker 后重试。",
  moduleCompletionMemoryOnly: "里程碑在当前标签页中为 current，但浏览器存储不可用。",
  moduleCompletionSaved: "已使用 current 产物与检查点记录里程碑。",
  prerequisiteNotCurrent: "前置里程碑尚未 current。",
  submissionMissing: "尚未保存 submission。",
  dependencyHashesStale: "依赖语义 hash 已 stale。",
  checkpointNotPassed: "本模块检查点尚未通过。",
  nextModuleReason: "下一个正式里程碑仍受前置产物、验证器与检查点阻断。",
  notSaved: "未保存",
  officialDocumentation: "官方文档",
  officialStandard: "官方标准",
  prerequisiteRequirement: "前置里程碑 current",
  primaryResearch: "原始研究",
  productionPracticumProgress: "fixture-safe 本地实验进度",
  recordCapstone: "验证并记录登记表",
  regulatoryGuidance: "特定法域的监管指导",
  reviewDecision: "人工审核决定",
  reviewDecisionReviewerRole: "产物审核者角色",
  accountableReviewerRole: "可问责审核者角色",
  savedReceipt: "已保存 receipt",
  selectReviewDecision: "选择明确决定",
  staleInstruction: "内容已保留。请针对 current 上游 hash 重新执行列出的验证、渲染与 QC 步骤。",
  unsavedArtifactChange: "该草稿与已保存证据不同。保存前它不会改变完成状态；保存后会使依赖它的里程碑与 Capstone 失效。",
  unsavedNavigationConfirm: "你有尚未写入课程保存记录的产物更改。是否离开本模块？返回时，当前标签页会尝试恢复这些更改。",
  validating: "正在验证…",
  checkingDraft: "正在检查最新草稿…",
  validationRecoveryAuthority: "请补全权限、权利、隐私或绑定人审证据后重试。",
  validationRecoveryDependency: "请刷新上游产物与依赖 hash，再重新验证。",
  validationRecoveryDelivery: "请按交付、字幕、音频、色彩与无障碍合同修复该字段。",
  validationRecoveryExecution: "请核对 current 计划、时钟、工具边界与执行 receipt 后重试。",
  validationRecoverySecurity: "请将不可信内容保持为数据，收紧权限、路径与网络边界后重试。",
  validationRecoveryStructure: "请按产物 schema 修复结构、必需字段与值后重试。",
  validationRecoveryGeneral: "当前字段未通过合同检查；请根据代码与路径修复后重试。",
  whyBlocked: "完成状态为何被阻断",
  whyCapstoneBlocked: "Capstone 记录为何被阻断",
  workedExample: "已完成示例",
  copyExample: "复制已完成示例",
  copyExampleDone: "已复制完成示例。",
  copySha: "复制 SHA-256",
  copyShaDone: "已复制 SHA-256。",
  copyFailed: "复制失败。请选中文本并手动复制。",
  localFileHashLimit: "为了保持浏览器稳定，此工具最多接受 256 MB 文件。更大媒体请使用可信本地 hash 工具。",
  localFileTooLarge: "该文件超过 256 MB。没有上传或保存任何内容；请改用可信本地 hash 工具。",
  localFileHashing: "正在本地计算所选文件 hash…",
  localFileHashReady: "本地文件 hash 已就绪。没有上传或保存任何内容。",
  recoveredDraft: "已恢复当前标签页中尚未保存的草稿。",
  recoveredDraftConflict: "恢复的草稿基于较旧或未知的保存版本；解决冲突前不能保存。",
  conflictLoadSaved: "载入最新保存版本",
  conflictUseSaved: "已载入最新保存证据，并丢弃恢复的草稿。",
  conflictRebaseDraft: "保留草稿并重新设定基准",
  conflictKeepDraft: "已将恢复的草稿重新设定到最新保存版本；保存前请仔细验证。",
  artifactSaveConflict: "验证草稿期间出现了较新的保存版本。系统未覆盖任何内容；请解决冲突后重试。",
  externalDraftConflict: "另一标签页已更改保存证据。你的未保存草稿仍保留于此；重新验证前，请检查新的保存 receipt。",
} as const satisfies AgenticVideoEditingUiCopy;

const zhCapstone = {
  ...en.capstone.production,
  title: "综合项目 · 十二项证据、候选与决定闭环",
  summary: "闭合十个模块 receipt、十二项 module-completion artifact 与 post-quiz 决定，同时不声称浏览器记录已检查外部文件、验证真实客户素材或授权发布。",
  scenario: "第二位操作员取得原创离线 fixture-safe package，复现准确候选、核对十二项产物与依赖、演练恢复，并确认绑定版本的 do-not-publish 决定。",
  criteria: [
    { ...en.capstone.production.criteria[0], label: "M1 创作简报与责任图" },
    { ...en.capstone.production.criteria[1], label: "M2 媒体清单、provenance、权利、隐私与隔离" },
    { ...en.capstone.production.criteria[2], label: "M3 转录、镜头与源时钟证据索引" },
    { ...en.capstone.production.criteria[3], label: "M4 候选、剪辑语法、含义门与系统卡" },
    { ...en.capstone.production.criteria[4], label: "M5 冻结 edit plan／OTIO derivative、schema 与 semantic receipt" },
    { ...en.capstone.production.criteria[5], label: "M5 plan diff 与独立人工 plan approval" },
    { ...en.capstone.production.criteria[6], label: "M6 获批工具政策与 mutation dry-run" },
    { ...en.capstone.production.criteria[7], label: "M8 render command／code／version、input/output hash、probe 与 receipt" },
    { ...en.capstone.production.criteria[8], label: "45–60 秒 9:16 候选、可编辑 caption sidecar 与 delivery record" },
    { ...en.capstone.production.criteria[9], label: "M9 验证、修复、回归与批准刷新" },
    { ...en.capstone.production.criteria[10], label: "M10 package manifest、runbook、依赖闭包与恢复演练" },
    { ...en.capstone.production.criteria[11], label: "M10 绑定版本的 do-not-publish 决定与 postmortem" },
  ],
  completionStatement: "我可以解析十二项登记产物与 dependency hash、复现并验证准确 sandbox 候选；带 hash 绑定的 do-not-publish（不发布）决定是有效结果。该记录不是证书、权利证明、真实项目生产验证或发布授权。",
  reviewQuestions: ["哪个上游变化会使最大范围证据失效？", "第二位复核人能否只凭 receipts 复现候选？", "修复后哪个实际 hash 改变？", "为什么 do-not-publish 是有效成功？", "使用学习者自有媒体时哪些检查必须重启？"],
} as const satisfies AgenticVideoEditingCourseCopy["capstone"]["production"];

const AGENTIC_VIDEO_EDITING_ZH_HANS_COPY_RAW = {
  ...en,
  meta: {
    ...en.meta,
    title: "如何使用智能体进行视频剪辑：从创作意图到经过验证的成片",
    shortTitle: "智能体视频剪辑",
    kicker: "第 20 课 · 证据驱动的智能体视频制作课程",
    summary: "把一项创作意图与一组有明确权利边界的媒体，转化为另一位操作员可以复现、质疑、修复与验证的候选成片。",
    audience: "面向希望把智能体接入真实剪辑流程、同时保留编辑判断与发布权限的创作者、教师、产品团队和工程师。",
    prerequisite: "fixture-safe 路径无需编码，只需现代浏览器与基本文件操作；本地媒体闭环需要 Node.js、FFmpeg 与 ffprobe。production-sandbox 可能需要 CLI/JSON、本地算力、Remotion 所需 React/TypeScript，或机构批准的 provider 账户；浏览器课程不要求付费服务。",
    level: "中级制作系统课程，内含初学者 readiness primer",
    duration: "十个模块共 750 分钟引导学习 · Final assessment 30 分钟 · 独立 Capstone 约 240 分钟 · 最多 180 分钟可选 fixture-safe 本地实验不计入 750 分钟 · production-sandbox 迁移不计分",
    startCta: "开始模块 1",
    resumeCta: "继续证据链",
    translationNote: "此页面显示经过编辑审校的简体中文课程；English 与简体中文均为长文审校版。",
    evidenceNote: "实现来源支持可检查的技术主张；标准、法律与实践信号各有适用边界，不能证明任意输出质量、权利或发布许可。",
  },
  ui,
  preflight: {
    title: "准备度检查：先选择你真正能支持的证据主张",
    summary: "fixture-safe 路径把浏览器合同练习与第一方合成本地闭环连成一条证据链；production-sandbox 只使用学习者合法控制的媒体、获批工具和具名人审。两条路径都不会扩大发布权限。",
    terms: [
      ["fixture-safe 路径", "浏览器合同练习加离线 122→47 秒第一方合成实验；只能支持本地自证的合成项目 portfolio。"],
      ["production-sandbox 路径", "可选地使用学习者合法控制的媒体、具名人审，并重复权利、隐私、安全、无障碍与发布门。"],
      ["原始素材", "作为字节级证据保存的源记录；只读权限位本身不等于不可变。"],
      ["代理文件", "用于高效或时钟安全操作的衍生物，lineage 与时间映射必须回到原始素材。"],
      ["源时钟", "解释某项素材帧位置与时长的有理 timebase。"],
      ["时间线时钟", "把已选 clip 放入序列的独立有理 timebase。"],
      ["Clip／入点／出点", "Clip 是放在时间线上的源引用；入点与出点标出经复核的源边界，不会改变原始素材。"],
      ["Track", "承载视频、音频、字幕或图形的有序时间线轨道；轨道位置不代表素材所有权。"],
      ["Timebase／frame rate", "Timebase 表示准确有理时间单位；frame rate 表示帧 cadence，不能都折叠成四舍五入的小数秒。"],
      ["Container／codec", "Container 封装 streams 与 metadata；codec 编码某个 stream。文件可播放不能证明合同满足。"],
      ["Render／export", "Render 执行获批媒体计划；export 打包交付变体。两者都不能证明含义、权利、无障碍或发布就绪。"],
      ["人工基线／agent layer", "先建立人类可复现的剪辑与复核基线；智能体只能提议或执行有边界步骤，不能替代可追责判断。"],
      ["候选", "仍需通过下一道人审或验证门的片段、计划或渲染。"],
      ["凭据", "记录实际输入、工具、参数、输出、hash 与状态的版本化证据。"],
      ["批准", "具名人类针对一个准确 artifact hash 与用途作出的决定。"],
      ["发布", "对外披露；课程完成或工具访问永远不构成发布授权。"],
    ],
    auditCore: { title: "fixture-safe 路径", summary: "浏览器 receipts 只证明合同学习；只有另行运行第一方本地实验并导入 current receipts，才能增加更窄的 synthetic portfolio locally attested 声明。两者都不需要付费 API 或真实媒体。" },
    productionPracticum: {
      title: "production-sandbox 路径",
      summary: "只使用学习者合法控制的媒体、本地或明确获批工具和具名独立复核人；真实目的地必须重跑全部权限与交付 preflight。",
      localChecks: ["记录权利、隐私、用途、目的地、保留、删除与训练用途决定。", "本地依赖或明确获批 provider 账户可用并有版本记录。", "具名人类可以独立复核、恢复并决定准确版本。"],
    },
    learnerOwnedExtension: "学习者合法控制的媒体只能进入 production-sandbox；此前必须重做权利、隐私、源时钟、色彩、安全、目的地、无障碍、processor/subprocessor、保留/删除、访问控制与人工批准检查。",
  },
  principles: ["意图先于工具", "把原始素材作为不可变证据保存和对待", "每项主张指向证据", "计划先于修改", "高成本执行前先预览", "验证不能冒充批准", "发布必须由人授权"],
  outcomes: [
    "编写含可观察验收标准、停止条件及彼此分离的计划批准人与发布批准人的创作简报。",
    "建立本地优先媒体台账，记录 hash、权利、隐私、源时钟、衍生 lineage、网络路径与 provenance。",
    "把 probe、转录、镜头、音频、OCR、metadata 与抽样帧组织为可查询证据，同时把嵌入指令视为数据。",
    "运用剪辑语法提出候选，保留上下文依赖，并冻结不会制造说话者含义的 typed、帧级 edit plan。",
    "先约束智能体与 MCP 工具权限并抵御间接 prompt injection，再定义可执行的字幕、音频、无障碍、画幅与色彩义务。",
    "通过留有凭据的 FFmpeg 路径执行获批计划，同时把 Remotion 等集成保留为需要重新 preflight 的 production-sandbox 扩展。",
    "用独立关口验证技术、语义、无障碍、权利、隐私与色彩，并进行有边界修复。",
    "打包十二项闭环产物、演练恢复，并把最终发布或不发布决定留给可追责的人。",
  ],
  distinctions: [
    ["智能体系统", "根据目标、状态、工具结果与反馈选择下一项有边界行动；权限或证据不足时停止或升级。"],
    ["Agent-ready 工具", "向宿主智能体提供稳定输入、结构化输出与可检查错误；本身不追求开放式编辑目标。"],
    ["规则自动化", "按已编码规则或固定顺序执行，例如测得的静音阈值；不会自行重规划。"],
    ["媒体引擎", "按命令、代码或时间线执行；FFmpeg 与 Remotion 不判断含义、权利、品味或发布。"],
    ["人类权限", "治理层而非另一种软件；知情的人类对编辑、权利、剩余风险与发布决定负责。"],
  ],
  phases: {
    define: { title: "定义委托", verb: "界定", summary: "分析前明确意图、权利、源时钟、不可信输入政策与人工权限。" },
    understand: { title: "通过证据理解", verb: "观察", summary: "索引技术事实、文字、镜头与经复核假设，不把模型输出伪装成真值。" },
    edit: { title: "通过合同剪辑", verb: "编排", summary: "批准窄范围计划，约束工具权限，定义交付与无障碍，再渲染一个可检查候选。" },
    verify: { title: "验证、修复并决定", verb: "交付", summary: "把失败路由到致因产物，重新渲染与验证，发布权留给具名人类。" },
  },
  modules: {
    "agentic-editing-contract": {
      ...en.modules["agentic-editing-contract"],
      kicker: "定义 · 模块 01",
      title: "把创作意图变成剪辑合同",
      summary: "把模糊创作请求改写为可观察的委托、角色与停止条件。",
      objective: "建立共享项目身份，明确受众、主张、交付物、红线、验收检查及彼此分离的批准权限。",
      artifact: "creative-brief.json",
      concepts: localizeConcepts(en.modules["agentic-editing-contract"].concepts, [
        ["创作简报", "可审查地说明受众、用途、交付物、红线与验收检查。"],
        ["责任图", "记录谁可以提案、审查、批准、执行与发布。"],
        ["验收测试", "可以通过、失败或保持未解决的可观察条件。"],
        ["停止条件", "预先声明的阻断状态，用于停止自动化并把决定交给人。"],
        ["发布权限", "可追责的人类针对一个准确、已审版本授予对外发布的权限。"],
      ]),
      sections: [
        localizeSection(en.modules["agentic-editing-contract"].sections[0], "演示不是运行合同", [
          "Video Use 记录了转录→EDL→渲染流程，并在执行前暂停等待策略批准；这项实现证据不能证明任意输出都安全或优质。",
          "本课程把该模式变成可证伪合同：一个项目 ID、45–60 秒 9:16 SDR Rec.709 目标、可观察检查、禁止结果与具名决定角色。",
        ], ["价值判断缺失时先提问，不能代填。", "计划批准与发布批准是两项不同决定；编辑准确性仍由人负责。"]),
        localizeSection(en.modules["agentic-editing-contract"].sections[1], "诚实命名每个系统角色", [
          "VideoDB Director 展示由推理层选择能力的智能体架构，Video Use 则记录更有边界的编辑工作流；两者需要不同测试表面。",
          "稳定主线是定义→理解→剪辑→验证。工具会变，但证据、最小权限、可逆执行、编辑准确性与可追责决定仍是课程合同。",
        ]),
      ],
      corePractice: localizePractice(en.modules["agentic-editing-contract"].corePractice, {
        title: "编写另一位操作员可以检查的委托", brief: "把一句请求改写为 canonical 离线 sandbox 简报。",
        steps: ["写明受众与一项预期主张。", "定义 50 秒 9:16 SDR Rec.709 交付物。", "分别指定计划与发布批准人。", "添加停止条件并保持 publication.allowed=false。", "验证并保存 canonical JSON。"],
        artifact: "有效创作简报与责任图。", reviewGate: "权限、交付物或停止条件缺失时保持阻断。",
        aiBoundary: "智能体可以指出遗漏，不能发明意图、同意、人物形象或发布权限。",
        acceptanceChecks: ["JSON 可解析并匹配合同。", "交付物为 45–60 秒、9:16、SDR Rec.709。", "停止条件非空。", "计划与发布批准人为不同具名角色。", "发布能力保持关闭。"],
      }),
      productionPractice: localizePractice(en.modules["agentic-editing-contract"].productionPractice!, {
        title: "Fixture-safe 本地实验：序列化责任图", brief: "把已审简报转换为 sandbox 机器可读委托，不增加权限。",
        steps: ["复用准确项目 ID。", "保留已批准受众、主张与停止条件。", "分开记录执行与复核角色。", "保持发布关闭。", "将本地实验文件与浏览器产物做 diff。"],
        artifact: "本地 creative-brief.json 与 diff 凭据。", reviewGate: "核心简报 hash 改变时扩展立即 stale。",
        aiBoundary: "序列化可以保留已批准意图，不能重新解释。",
        acceptanceChecks: ["项目身份匹配核心产物。", "差异没有增加发布权限。", "发布保持关闭。"],
      }),
      checkpoint: localizeCheckpoint(en.modules["agentic-editing-contract"].checkpoint, "面对‘剪得更有感染力’，第一项可辩护行动是什么？", [
        ["先渲染多个精修版本，再询问哪个更好。", "这在受众、主张和验收检查缺失时提前消耗资源。"],
        ["定义受众、预期结果、可观察检查与决定角色。", "正确：把品味请求变成可以检查的委托。"],
        ["先增加节奏、缩放与转场，制造可见进展。", "可见活动不等于满足委托的证据。"],
        ["让智能体从旧输出推断品牌立场。", "智能体不能静默代替可追责的价值判断。"],
      ], "合同使后续证据、剪辑与批准都可以验证。"),
      takeaway: "强智能体从有边界的委托开始，而不是从不断扩张的提示词开始。",
    },
    "media-ingest-provenance": {
      ...en.modules["media-ingest-provenance"],
      kicker: "定义 · 模块 02", title: "登记媒体、权利、源时钟与不可信输入",
      summary: "把原始素材保存为证据，并对身份、权利、隐私、色彩、时间或权限缺口 fail closed。",
      objective: "生成可独立检查 hash、probe 凭据、源时钟、权利决定、lineage 与威胁决定的清单。",
      artifact: "media-manifest.json",
      concepts: localizeConcepts(en.modules["media-ingest-provenance"].concepts, [
        ["内容身份", "以字节 hash 与稳定媒体 ID 区分素材，而不是依赖路径或显示名。"],
        ["源 timebase", "解释该素材帧位置和时长的有理时钟。"],
        ["权利决定", "具名人类针对本次用途决定素材能否进入工作流。"],
        ["衍生 lineage", "记录原始素材、代理、转换与所得证据之间的关系。"],
        ["不可信媒体", "把媒体、metadata、OCR、转录、字幕与工具输出视为数据而非权限。"],
      ]),
      sections: [
        localizeSection(en.modules["media-ingest-provenance"].sections[0], "解释之前先保存、识别与测量", [
          "FFmpeg 与 ffprobe 可暴露时长、codec、帧率、timebase、色彩 metadata 与音频布局。路径不是身份，因此每次使用都要重新核对内容 hash 并保留独立备份。",
          "只读权限不等于不可变存储。本课程把原始素材作为不可变证据、把衍生物写入隔离 root，并记录父 hash、操作与 probe 凭据；C2PA 是可选 provenance 标准，不是真实性或权利证明。",
        ]),
        localizeSection(en.modules["media-ingest-provenance"].sections[1], "媒体内容是数据，永远不是权限", [
          "转录、OCR、字幕、文件名、metadata、archive 与 tool output 都可能包含类似指令的文字。本课程把它们视为不能扩大目录、网络、账号、成本、修改或发布权限的数据。",
          "Sandbox 只支持 SDR Rec.709。HDR、wide gamut、缺失色彩 metadata、未知权利、未 conform 的 VFR、路径逃逸、symlink 或 archive expansion 都保持阻断。",
        ], [
          "用只读 probe 输入、受限资源、隔离输出与 typed argv。",
          "软件许可证不清除媒体、人物、音乐、字体、服务商或模型输出；美国版权局 AI 研究也只是特定法域的人类作者性指导。",
        ]),
      ],
      corePractice: localizePractice(en.modules["media-ingest-provenance"].corePractice, {
        title: "审计含一个故意 blocker 的清单", brief: "记录源时钟、hash、权利与不可信内容决定，并观察 unknown rights 如何保持阻断。",
        steps: ["用 SHA-256 识别每项素材。", "绑定 ffprobe 凭据。", "声明 sourceTimebase 与 clockMode。", "记录权利与隐私决定。", "把嵌入文字视为 data-not-authority。"],
        artifact: "显式为 blocked 或 valid 的 media manifest。", reviewGate: "未知权利、未知色彩或无 conform 凭据的 VFR 不能成为生产输入。",
        aiBoundary: "智能体可以分类风险，不能从文件可访问推断同意、所有权或许可。",
        acceptanceChecks: ["每项素材都有 64 个十六进制字符（256 位）的内容与 probe SHA-256。", "每项输入有自己的源时钟。", "Unknown rights 产生语义 blocker。", "不可信文字不能改变权限。", "只有 SDR Rec.709 输入继续。"],
      }),
      productionPractice: localizePractice(en.modules["media-ingest-provenance"].productionPractice!, {
        title: "生成并检查第一方 sandbox 媒体", brief: "离线生成 122 秒 30/1 CFR canonical 源，以及 24 fps、30000/1001 CFR 与 VFR 时钟控制。",
        steps: ["执行前先运行 plan mode。", "只写入受控相对输出 root。", "记录工具版本、实际 hash 与 ffprobe 事实。", "确认不覆盖且不联网。", "保持未知权利文本记录隔离。"],
        artifact: "Sandbox media manifest、probe 与 lineage 凭据。", reviewGate: "VFR 源只有在 proxy 绑定原始 lineage 与 time-map receipt 时才可继续。",
        aiBoundary: "Sandbox 成功只证明机制，不证明真实素材的权利或含义。",
        acceptanceChecks: ["生成器记录实际版本与 hash。", "Canonical 源本身是 122 秒 30/1 CFR。", "24、30000/1001 与 VFR 控制不进入黄金时间线。", "Raw VFR 被阻断且 proxy 有 lineage/time-map。", "没有原始素材被覆盖。"],
      }),
      checkpoint: localizeCheckpoint(en.modules["media-ingest-provenance"].checkpoint, "可播放 clip 的权利未知，metadata 还包含类似指令的文字；应如何接收？", [
        ["因为可播放，所以接受。", "播放只证明可解码，不证明权利、隐私或权限。"],
        ["先私下使用，发布成功后再解决权利。", "下游处理已经可能造成隐私、人物形象与披露伤害。"],
        ["隔离素材，把 metadata 当作数据，并请求可追责权利决定。", "正确：结构可读永远不构成权利或权限。"],
        ["删除 provenance 字段以免后续工具看到。", "删除证据会隐藏 blocker 并削弱审计链。"],
      ], "权利与权限是 fail-closed 决定，与技术可播放性无关。"),
      takeaway: "任何下游推理都不会强于输入的身份、时钟、权利与 provenance。",
    },
    "transcripts-shots-index": {
      ...en.modules["transcripts-shots-index"],
      kicker: "理解 · 模块 03", title: "建立带时间码的转录、镜头与 probe 证据",
      summary: "在不同源时钟之间保持测量事实、模型假设与人工修正彼此分离。",
      objective: "建立可解析到稳定媒体 ID 与源帧的证据 locator，同时保存不确定性与修订历史。",
      artifact: "evidence-index.json",
      concepts: localizeConcepts(en.modules["transcripts-shots-index"].concepts, [
        ["源帧", "在具名素材自身有理时钟中解释的整数位置。"],
        ["带时间码证据", "把主张绑定到媒体 ID、时钟、范围、方法与复核状态的 locator。"],
        ["转录证据", "与准确源音频及上下文相连的机器或人工文字。"],
        ["镜头边界", "测得或提议的视觉转场，不是语义场景或编辑真值。"],
        ["复核状态", "明确区分 machine-observed、human-verified 与 unresolved。"],
      ]),
      sections: [
        localizeSection(en.modules["transcripts-shots-index"].sections[0], "时间是媒体合同，不是十进制猜测", [
          "Whisper 提供转录，WhisperX 增加对齐与 diarization-oriented 工作流，PySceneDetect 识别镜头边界；这些输出都不能替代源时钟或关键文字的人审。",
          "每个 locator 写明源媒体 ID、source timebase、整数起始帧与时长、方法和复核状态；24、30000/1001 与 conform 来源不能静默转成浮点秒。",
        ]),
        localizeSection(en.modules["transcripts-shots-index"].sections[1], "证据必须可被推翻", [
          "人名、数字、否定、安全指令与身份主张必须回到源音频；转录与对齐输出在相关片段复核前仍是假设。",
          "PySceneDetect 提出视觉转场而不是故事意义。每个边界保留 detector 与 threshold，让复核人可以复现、合并、拆分或拒绝。",
        ]),
      ],
      corePractice: localizePractice(en.modules["transcripts-shots-index"].corePractice, {
        title: "把每项主张追溯到源帧 locator", brief: "建立含显式方法与复核状态的转录、镜头、视觉和 probe 证据。",
        steps: ["命名源时钟政策。", "记录 frame-based locator。", "分开 measured、model-generated 与 human-verified。", "对照源媒体修正一个关键 token。", "保持一个未解决歧义可见。"],
        artifact: "Current evidence-index.json。", reviewGate: "关键主张只有模型证据时不能继续。", aiBoundary: "智能体可以提议证据，不能把不确定性改写为事实。",
        acceptanceChecks: ["全部 locator 解析到 current manifest media ID。", "范围使用具名源时钟中的整数帧。", "关键语言经过人审。", "未知项保持可见。", "VFR locator 不能绕过 conform lineage。"],
      }),
      productionPractice: localizePractice(en.modules["transcripts-shots-index"].productionPractice!, {
        title: "索引 sandbox 时钟与 QC 场景", brief: "Probe 生成源并定位 black、silence、audio-level、orientation、caption-safe、OCR 与 injection fixture。",
        steps: ["读取生成的 probe 凭据。", "不做十进制强转地索引 canonical 30/1 源与额外 CFR 控制。", "定位 VFR 负例及 proxy 映射。", "记录黑帧与静音区间。", "把 injection 文字标为不可信数据。"],
        artifact: "含源帧 locator 的 sandbox evidence index。", reviewGate: "不能从实际凭据复现的 locator 保持阻断。", aiBoundary: "Golden 结构凭据是 locator，不承诺不同 FFmpeg build 逐位一致。",
        acceptanceChecks: ["证据覆盖 canonical 30/1 源与额外 CFR 控制。", "VFR/proxy 映射明确。", "黑帧与静音事实匹配 probe。", "类似提示的文字不具权限。", "记录实际 receipt hash。"],
      }),
      checkpoint: localizeCheckpoint(en.modules["transcripts-shots-index"].checkpoint, "转录中的关键人名不确定时，应如何处理？", [
        ["替换为最常见写法，使文字更流畅。", "流畅不是证据，还可能制造错误身份。"],
        ["保留不确定性，并检查准确源音频与上下文。", "正确：关键语言必须回到源证据。"],
        ["因为一个 token 不确定而删除全部访谈。", "这逃避调查，也可能不必要地丢弃有效证据。"],
        ["模型报告完成后直接信任转录。", "完成状态不是人类核验事实。"],
      ], "关键证据必须可追溯、可复核，并诚实保留不确定性。"),
      takeaway: "只有当另一位操作员能在正确源时钟中解析它时，时间戳才有价值。",
    },
    "semantic-analysis-director": {
      ...en.modules["semantic-analysis-director"],
      kicker: "理解 · 模块 04", title: "提出候选片段，但不能制造新含义",
      summary: "把证据转成可复核候选，同时保存每个片段保持真实所需的上下文。",
      objective: "建立暴露证据、上下文依赖、歧义、权利、复核状态与序列整体含义的候选片段和系统卡。",
      artifact: "candidate-segments.json",
      concepts: localizeConcepts(en.modules["semantic-analysis-director"].concepts, [
        ["候选片段", "带证据与理由的源范围提案，不是已批准剪辑。"],
        ["上下文依赖", "保持含义所需的铺垫、限定、指代、回应或时序。"],
        ["语义拼接", "把真实片段连接成来源不支持的新主张。"],
        ["剪辑语法", "用 continuity、cut motivation、pacing、J/L cut、reaction、B-roll 与 room tone 帮助理解而不改变真实。"],
        ["修剪与 handles", "区分已选源区间、切点两侧的未用素材，以及 ripple、roll、slip、slide 或 split edit 对序列的影响。"],
        ["有边界的确定性", "明确确定性的对象、依据、方法与复核状态。"],
        ["智能体系统卡", "Production-sandbox 记录 planner、executor、reviewer、工具、状态、预算与升级路径。"],
      ]),
      sections: [
        localizeSection(en.modules["semantic-analysis-director"].sections[0], "候选生成是检索，不是真值", [
          "VideoDB Director 与 Video Use 展示从请求和转录式证据选择能力与规划；输出仍是候选，不是逐帧事实或编辑结论。",
          "J-cut 与 L-cut 可让声音提前进入或延后退出，从而保持对话流动；cut motivation、reaction、B-roll、节奏、连续性与 room tone 仍要由编辑判断上下文和后果。",
          "编辑要区分源区间与时间线位置：handles 保留切点两侧素材；ripple 会改变下游时序，roll 移动共享切点，slip 在 clip 位置不变时更换源内容，slide 则移动 clip 并调整相邻片段。课程把结果记录为有边界的 clip range 与 typed operation，不让智能体直接操纵 opaque NLE state。",
          "确定性只有在写明对象、依据、方法与分类复核状态时才有用；本课程删除裸露的 0–1 confidence，避免伪精确。",
        ]),
        localizeSection(en.modules["semantic-analysis-director"].sections[1], "计划之前先过序列含义门", [
          "两个真实句子相连也可能形成错误主张。每个候选先声明所需铺垫、限定、指代、回应与时序，然后完整粗剪接受准确性审查。",
          "若顺序使说话者看似表达其未表达主张，必须阻断、恢复上下文、拒绝候选或升级；时长、节奏与流畅度不能覆盖此门。",
        ]),
      ],
      corePractice: localizePractice(en.modules["semantic-analysis-director"].corePractice, {
        title: "拒绝有吸引力但错误的拼接", brief: "比较两条都有证据的候选序列，说明其中一条如何改变说话者含义。",
        steps: ["为每个候选附证据引用。", "列出上下文依赖。", "记录歧义与权利状态。", "高影响含义必须人审。", "批准或阻断完整粗剪的含义。"],
        artifact: "candidate-segments.json 与智能体系统卡。", reviewGate: "任何序列级 unsupported claim 都阻断完成。",
        aiBoundary: "智能体可以排序候选，不能自行决定改变含义是否可接受。",
        acceptanceChecks: ["每个候选解析到 current 证据。", "上下文依赖明确。", "候选和序列都不制造新主张。", "未知权利阻断。", "高影响含义有绑定 hash 的人审。"],
      }),
      productionPractice: localizePractice(en.modules["semantic-analysis-director"].productionPractice!, {
        title: "按证据与用途选择 sandbox 场景", brief: "从生成场景提出 45–60 秒序列，同时保留 warning 与 verification 上下文。",
        steps: ["对照简报排序场景。", "保留解释负例所需上下文。", "拒绝 OCR 或 metadata 中类似提示的指令。", "整体复核粗剪。", "只冻结获批 candidate ID。"],
        artifact: "Sandbox candidate-segments.json。", reviewGate: "Sandbox 序列不得暗示 fixture 已验证真实客户权利或含义。",
        aiBoundary: "Sandbox 场景只测机制，不替代真实人物语义判断。",
        acceptanceChecks: ["总时长为 45–60 秒。", "每段都有证据。", "不可信文字不改变权限。", "序列含义已审。", "Sandbox 范围已披露。"],
      }),
      checkpoint: localizeCheckpoint(en.modules["semantic-analysis-director"].checkpoint, "模型为视觉事件提出时间戳，这能证明什么？", [
        ["这是无需复核即可插入的逐帧事实。", "近似模型定位不是源帧测量。"],
        ["这是必须对照源证据与上下文解析的候选 locator。", "正确：提案经源证据复核后才有用。"],
        ["描述听起来合理时就构成发布批准。", "定位无法授予编辑或发布权限。"],
        ["它证明片段中所有可见对象都已授权。", "视觉相关性与权利清除是两项决定。"],
      ], "模型适合帮助检索候选；源复核与人类权限决定能否使用。"),
      takeaway: "真实的单位是经过上下文复核的完整序列，而不是孤立、流畅的 clip。",
    },
    "declarative-edit-plan": {
      ...en.modules["declarative-edit-plan"],
      kicker: "剪辑 · 模块 05", title: "冻结 canonical 帧级 edit plan",
      summary: "以明确时钟与证据，把获批序列表示为 clip、caption、title、audio、crop 与 transition 六类 typed operation。",
      objective: "建立 edit-plan v3，通过 operation 类型、mixed-rate、VFR、权利与时序检查，运行完整序列含义门，并由外部批准绑定 canonical bytes。",
      artifact: "edit-plan.v3.json + plan-approval.json",
      concepts: localizeConcepts(en.modules["declarative-edit-plan"].concepts, [
        ["Edit-plan v3", "课程 canonical 的帧级合同，支持 clip、caption、title、audio、crop 与 transition 六类 typed operation。"],
        ["Typed operation", "可在执行前校验种类、引用、权利、时间线区间与类型特定字段的剪辑操作。"],
        ["有理 timebase", "以分子与分母保存源时钟和时间线时钟身份。"],
        ["Conformed proxy", "保留原始 hash、lineage 与时间映射的 CFR 衍生物。"],
        ["编译合同", "声明渲染还需要 delivery matrix、获批 asset ledger 与 tool policy；edit plan 本身不足以执行。"],
        ["外部计划批准", "独立于计划内容、绑定 canonical hash 的人工记录。"],
      ]),
      sections: [
        localizeSection(en.modules["declarative-edit-plan"].sections[0], "让 canonical 合同刻意保持狭窄", [
          "OpenTimelineIO 表示编辑时间线结构并记录媒体引用与 bundle，但不会把交换数据直接渲染为成片；video-edit-cli 是另一种结构化命令接口示例。",
          "Edit-plan v3 只接受 clip、caption、title、audio、crop 与 transition 六类显式 operation；未知类型 fail closed。编译仍需要 delivery matrix、获批 asset ledger 与 tool policy，因此有效计划并不是可独立执行的 render command。",
        ]),
        localizeSection(en.modules["declarative-edit-plan"].sections[1], "绑定时钟、证据与批准，但不要 self-hash", [
          "每项输入携带内容 hash、probe receipt hash、权利决定、独立 sourceTimebase 与 clockMode。Raw VFR fail closed；CFR proxy 必须有原始 lineage 与 time-map receipt。",
          "Canonical parsed plan 在 envelope 和 hash 字段之外计算 hash；批准、发布决定与 self-hash 都留在计划之外。",
          "批准前再次复核完整粗剪是否存在 unsupported semantic splice；结构有效的计划仍可能在语义上被阻断。",
        ]),
      ],
      corePractice: localizePractice(en.modules["declarative-edit-plan"].corePractice, {
        title: "审计 typed edit-plan v3", brief: "修复 mixed-rate 与 VFR 例子，校验每项 typed operation 与引用，并生成绑定 current 内容的外部批准。",
        steps: ["声明每项源时钟与音频时钟。", "把源帧区间放入独立时间线时钟。", "校验 clip、caption、title、audio、crop 与 transition 的引用和区间。", "运行完整序列含义门与 compile-input 检查。", "把批准绑定 canonical content hash。"],
        artifact: "edit-plan.v3.json 与外部 plan-approval.json。", reviewGate: "Raw VFR、缺 lineage、未声明 gap、stale 证据、未知权利、无效 operation 或错误含义都保持阻断。",
        aiBoundary: "智能体可以提议 typed operation，不能批准自身计划、编造权利，也不能把计划当成缺失的交付、asset 或 tool-policy 合同。",
        acceptanceChecks: ["Schema 与语义验证通过。", "每项 typed operation 的引用和时间线区间有效。", "源、音频与时间线时钟明确。", "Raw VFR 只有带 lineage/time map 的 conform proxy 可用。", "Compile input 已声明，外部批准绑定 current plan hash。"],
      }),
      productionPractice: localizePractice(en.modules["declarative-edit-plan"].productionPractice!, {
        title: "编译获批 sandbox edit plan", brief: "建立 bounded FFmpeg compiler 将与下游合同共同消费的准确 45–60 秒 typed plan。",
        steps: ["使用实际 manifest、rights、candidate 与 evidence ID。", "黄金时间线只使用 canonical 30/1 源。", "24、30000/1001 与 VFR 控制只作显式时钟和 lineage 压力测试。", "预览每项 operation、引用、区间与序列含义。", "为冻结 hash 记录外部批准。"],
        artifact: "Sandbox edit-plan.v3.json 与 plan-approval.json。", reviewGate: "任一上游 hash 改变都会使计划及批准 stale。",
        aiBoundary: "OTIO 可后续衍生，但不能取代 canonical 计划、compile input 或人工批准。",
        acceptanceChecks: ["时长为 45–60 秒。", "实际 input、rights、candidate、evidence 与 receipt 引用解析成功。", "Mixed-rate 映射与所有 typed operation 区间通过。", "Compile input 与完整序列含义获批。", "批准独立且 current。"],
      }),
      checkpoint: localizeCheckpoint(en.modules["declarative-edit-plan"].checkpoint, "OTIO timeline 或 bundle 在本课程中可以扮演什么角色？", [
        ["判断所选语句是否仍真实的模型。", "时间线交换不能判断说话者含义。"],
        ["把获批计划直接发布到社交平台。", "交换数据没有发布权限。"],
        ["它可以是下游交换衍生物，但既不是 canonical 计划，也不是 renderer。", "正确：edit-plan v3 保持 canonical，渲染仍是独立层。"],
        ["通过嵌入 metadata 证明音乐与素材权利。", "Metadata 不能建立权利清除。"],
      ], "保持 canonical 决策数据、交换与媒体执行彼此分离。"),
      takeaway: "有边界的 typed plan 可以严格验证；它仍与 interchange、编译、媒体执行和批准彼此独立。",
    },
    "captions-audio-formats": {
      ...en.modules["captions-audio-formats"],
      kicker: "剪辑 · 模块 07", title: "渲染前定义字幕、音频、色彩与每个交付版本",
      summary: "把无障碍媒体、音频测量、构图、图形与 SDR Rec.709 义务写成独立数据。",
      objective: "建立位于获批 edit plan 下游、工具权限与所有候选渲染上游的 delivery-matrix.json。",
      artifact: "delivery-matrix.json + 经复核字幕 sidecar",
      concepts: localizeConcepts(en.modules["captions-audio-formats"].concepts, [
        ["Closed captions", "与画面同步、可选择的对白、必要说话者身份与关键非语言声音文字。"],
        ["视觉描述决定", "记录重要视觉信息是否需要主音轨整合描述、audio description 或描述性替代。"],
        ["节目响度与 true peak", "对照具名目的地解释的音频测量，而不是通用社交媒体数字。"],
        ["封装、编码与像素格式", "分别记录 stream 封装、编码表示、色度抽样与 bit depth；文件扩展名本身不能证明任何一项。"],
        ["母版与交付编码", "经复核的高质量母版与各目的地 distribution encode 是分别绑定 hash、分别 probe 的输出。"],
        ["色彩管理", "声明 source encoding、working/viewing transform 与交付色彩 tag 的关系。"],
        ["画幅特定版本", "构图、字幕、图形、安全区与批准都单独复核的交付物。"],
        ["高级色彩管线", "超出 fixture-safe SDR 实验的 wider-gamut、HDR 或 ACES production-sandbox 主题。"],
      ]),
      sections: [
        localizeSection(en.modules["captions-audio-formats"].sections[0], "无障碍不等于转录", [
          "在适用情境下，WCAG 要求预录同步媒体提供 captions；caption 包括 spoken content、画面不足以辨认时的说话者，以及有意义的非语言声音。Raw ASR 仍是草稿。",
          "无障碍媒体规划还要考虑 descriptive transcript、重要视觉信息的 integrated description 或 audio description、文字可读性与对比度、闪烁风险及可访问播放器。若口播已说出全部重要信息，可以记录为无需独立 audio description，但不能默认为不需要。",
          "FFmpeg 可以 mux 或 burn caption stream，也能执行 audio、scale、crop 与 color 操作；这些机制不能判断语言准确性、无障碍、构图意图或目的地适配。",
        ]),
        localizeSection(en.modules["captions-audio-formats"].sections[1], "把格式、音频、色彩与构图绑定到目的地", [
          "ITU-R BS.1770 定义 programme loudness 与 true-peak 测量算法；EBU R128 是广播建议，并非所有平台通用目标。Matrix 还要记录目的地规则、对白清晰度、clipping、声道、phase、sync、room tone 与剪点连续性。",
          "Container、video/audio codec、pixel format 与 chroma subsampling、bit depth、raster 与 pixel aspect、frame rate 与 timebase、bitrate 与 GOP、sample rate 与 channel layout，以及 caption carriage 都是独立交付字段；文件能播放仍可能违反目的地合同。",
          "ACES 记录了一种 managed color framework，但并非本课程必需。Fixture-safe 本地实验只允许 SDR Rec.709；缺失、HDR 或 wide-gamut metadata 不得通过猜测 transform 静默修复，production-sandbox 版本须重新批准色彩合同。",
          "每个 9:16、16:9 或其他版本都需要逐段 crop、安全区、字幕、图形、音频、色彩与批准行，因为 reframing 可能移除证据或改变强调。",
        ]),
      ],
      corePractice: localizePractice(en.modules["captions-audio-formats"].corePractice, {
        title: "编写画幅特定的交付与无障碍矩阵", brief: "在工具政策获批后、任何 render 执行前，把‘字幕可读、音频干净’改写为可测量且绑定目的地的行。",
        steps: ["绑定 current plan hash。", "声明 container、codec、pixel format、bit depth、chroma、geometry、pixel aspect、frame rate、timebase、bitrate/GOP 与 SDR Rec.709。", "说明 caption/subtitle、transcript、视觉描述与 caption carriage 决定。", "声明目的地响度、true peak、sample rate、声道、phase、sync 与 intelligibility 检查。", "为每个版本建立逐段 crop、graphics、安全区、contrast 与 flash 检查。"],
        artifact: "delivery-matrix.json 与经复核 caption sidecar。", reviewGate: "无障碍、音频、色彩、geometry、目的地或独立复核证据缺失时阻断 render 执行。",
        aiBoundary: "智能体可以草拟 caption timing、构图与测量，不能认证语言、描述充分性、艺术意图或无障碍 conformance。",
        acceptanceChecks: ["Matrix 绑定 current plan。", "目标为 45–60 秒、1080×1920、SDR Rec.709。", "Container、codec、pixel format、时钟、音频布局与 caption carriage 明确。", "Caption、transcript 与视觉描述适用性已审。", "音频测量与目的地规则明确。", "每个版本有独立构图与无障碍检查。"],
      }),
      productionPractice: localizePractice(en.modules["captions-audio-formats"].productionPractice!, {
        title: "把 sandbox QC 场景绑定到交付检查", brief: "使用 silence、level、orientation 与 caption-safe 场景定义预期渲染事实。",
        steps: ["引用 sandbox caption sidecar。", "声明音频与 no-clipping 目标。", "声明 9:16 crop 与 safe-zone 预期。", "要求 SDR Rec.709 stream facts。", "预览每个正负例。"],
        artifact: "Sandbox delivery-matrix.json。", reviewGate: "泛泛的‘看起来不错’不能取代字段级交付检查。",
        aiBoundary: "该矩阵测试 sandbox 机制，不证明真实语言内容的无障碍。",
        acceptanceChecks: ["预期 probe 事实明确。", "Caption-safe marker 保持可见。", "Silence 与 audio-level 场景有预期结果。", "要求 SDR Rec.709。", "其他格式保持 out of scope。"],
      }),
      checkpoint: localizeCheckpoint(en.modules["captions-audio-formats"].checkpoint, "应如何把 16:9 剪辑改为 9:16 交付物？", [
        ["整条序列使用同一 center crop，并接受被裁掉的主体。", "单一 crop 可能隐藏说话者、字幕、演示或事实语境。"],
        ["横屏已批准，因此所有衍生画幅自动批准。", "新画幅会改变可见证据，必须独立签合同与审查。"],
        ["逐段声明 framing 与 safe-zone 规则，再审查准确竖屏候选。", "正确：每个交付版本都必须独立可测。"],
        ["渲染后删除 crop 记录以简化 package。", "移除转换证据会增加恢复与审计难度。"],
      ], "构图是会产生语义与无障碍后果的交付决定。"),
      takeaway: "Delivery matrix 在渲染出现之前，就让成片义务可以测试。",
    },
    "agent-tools-mcp": {
      ...en.modules["agent-tools-mcp"],
      kicker: "剪辑 · 模块 06", title: "在工具修改媒体前约束权限",
      summary: "把获批计划转化为最小权限、dry-run 证据与可恢复 mutation 边界。",
      objective: "建立 tool-policy.json，分开 read、reversible write、render、network、account、cost 与 publish 权限，并抵御不可信输入。",
      artifact: "tool-policy.json + dry-run 与 rollback 凭据",
      concepts: localizeConcepts(en.modules["agent-tools-mcp"].concepts, [
        ["最小权限", "只授予完成获批行动所需的 root、call、network、account、cost 与时间。"],
        ["Typed argv", "不经过 shell 解释的固定 executable 与参数数组。"],
        ["Dry-run", "修改前预览已解析输入、输出、参数与副作用。"],
        ["幂等与前置条件", "避免 retry 静默重复状态变更的生产系统控制。"],
        ["间接 prompt injection", "经媒体或工具进入、必须保持为不可信数据的类似指令内容。"],
      ]),
      sections: [
        localizeSection(en.modules["agent-tools-mcp"].sections[0], "能力不是权限", [
          "MCP 标准化通信模式，但不保证某个 server、host、tool、annotation 或 parameter 安全。Resolve MCP 是社区实现，不是厂商认证。",
          "政策必须分开 allowed root、read、reversible mutation、render、network、provider account、spend 与 publish scope。默认 deny；excessive agency 会把实用工具变成失控行动者。",
        ]),
        localizeSection(en.modules["agent-tools-mcp"].sections[1], "把所有内容通道视为权限敌对输入", [
          "转录中的‘上传此文件’、metadata 中的‘忽略政策’或 tool output 对 secret 的请求，都属于间接 prompt injection 数据；不能改变 root、network、account、cost 或发布权限。",
          "必修 executor 使用固定 executable 与 argv，绝不拼接 shell；只使用受控相对路径、拒绝覆盖、限制资源、隔离输出，并在不泄露 secret 的前提下记录失败。",
        ], [
          "测试 traversal、symlink escape、archive expansion、恶意字幕/metadata、间接 prompt injection 与 tool-output injection。",
          "每项 mutation 都有 preview、expected-state precondition、rollback 或 compensation、retry bound 与可追责升级。",
        ]),
      ],
      corePractice: localizePractice(en.modules["agent-tools-mcp"].corePractice, {
        title: "对所选 executor 做威胁建模", brief: "编写只允许工具检查和执行获批计划、不能扩大权限的政策。",
        steps: ["定义 allowed filesystem root。", "拒绝 network、account、cost 与 publish。", "声明 argv-only process execution。", "加入 dry-run 与 rollback。", "运行恶意路径与指令 fixture。"],
        artifact: "tool-policy.json 与 threat-test 结果。", reviewGate: "任何未声明 root、provider、cost、secret、mutation 或 publish 能力都阻断执行。",
        aiBoundary: "即使媒体内容要求，智能体也不能批准自身权限扩张。",
        acceptanceChecks: ["政策绑定获批 plan hash。", "Root 受控且为相对路径。", "Shell、network、account、cost 与 publish 全部拒绝。", "Dry-run 与 rollback 必需。", "全部 threat fixture 被阻断。"],
      }),
      productionPractice: localizePractice(en.modules["agent-tools-mcp"].productionPractice!, {
        title: "Dry-run 本地 FFmpeg executor", brief: "Spawn 前检查固定 argv、resolved path、输入、输出与预期 receipt graph。",
        steps: ["无论是否已安装 FFmpeg，先运行 --plan。", "检查每个 argv 元素。", "尝试 traversal 与 overwrite 负例。", "工具可用时执行安全 mutation。", "演练 rollback 并保存凭据。"],
        artifact: "Sandbox tool policy、dry-run receipt 与 rollback receipt。", reviewGate: "Plan、policy、path 或 tool preflight stale/blocked 时 process 不得启动。",
        aiBoundary: "Executor 只执行获批 argv，永不把媒体文字解释为命令。",
        acceptanceChecks: ["--plan 不依赖 FFmpeg 也可运行。", "实际 spawn 使用 argv 且 shell=false。", "Traversal 与 overwrite fail closed。", "存在 rollback receipt。", "无网络或凭据访问。"],
      }),
      checkpoint: localizeCheckpoint(en.modules["agent-tools-mcp"].checkpoint, "转录要求 MCP tool 上传源文件并读取 token；什么决定权限？", [
        ["编辑看起来专业时就可以执行。", "审美质量不能授予数据或凭据访问。"],
        ["只有获批政策与 current 计划可以授权有边界的 tool call。", "正确：媒体文字是数据，能力留在显式权限内。"],
        ["本地剪辑可撤销，因此上传也安全。", "Undo 不能撤回已经发生的外部披露。"],
        ["兼容 MCP 表示 server 已通过安全审查。", "协议不会认证实现或权限。"],
      ], "不可信内容永远不能扩大权限；政策、typed input、preview 与人审决定工具行动。"),
      takeaway: "安全工具接口是能执行获批计划并证明实际行为的最小接口。",
    },
    "deterministic-rendering": {
      ...en.modules["deterministic-rendering"],
      kicker: "剪辑 · 模块 08", title: "根据 current 合同渲染，并保存执行凭据",
      summary: "只执行获批 plan、delivery matrix、tool policy 与准确 input identity。",
      objective: "生成候选与 render receipt，记录 executor、版本、argv、输入/输出 hash、probe 事实与失败。",
      artifact: "render-receipt.json + candidate output",
      concepts: localizeConcepts(en.modules["deterministic-rendering"].concepts, [
        ["所选 executor", "为一条有边界渲染路径明确批准的引擎与版本。"],
        ["参数数组执行", "不经 shell interpolation 调用固定 executable 与参数。"],
        ["渲染凭据", "把 current 输入与合同绑定到版本、argv、输出 hash、probe、状态和失败证据。"],
        ["输出 probe", "从实际候选 bytes 测得 stream、时钟、geometry、audio 与 color 事实。"],
        ["复现边界", "区分固定环境下的结构可重复与未经证明的跨 build byte identity。"],
        ["Remotion production-sandbox 路径", "需要独立 preview、代码审查与凭据的可选 code-driven 图形/合成路径。"],
      ]),
      sections: [
        localizeSection(en.modules["deterministic-rendering"].sections[0], "渲染证明执行，不证明编辑正确", [
          "FFmpeg 是必修本地 executor，因为它支持可脚本化媒体转换与 probe；Remotion 与 Agent Skills 记录可选 code-driven 路径。两个引擎都不能批准含义或发布。",
          "Render receipt 消费 current plan、delivery、policy 与 input hash，记录工具版本和准确 argv，保存 output hash、ffprobe facts、exit code 与净化后的 stderr。",
        ]),
        localizeSection(en.modules["deterministic-rendering"].sections[1], "可复现结构不等于跨 build 字节一致", [
          "Codec library、default、hardware 与 build configuration 都可能改变输出 bytes；sandbox 记录本轮实际 hash 与 stream facts，不承诺不同 FFmpeg build bit-identical。",
          "Remotion production-sandbox 路径属于选修；生成 component 仍需普通代码审查、frame preview、字体与素材 provenance、overflow 检查、proxy render 与同一套下游验证。",
        ]),
      ],
      corePractice: localizePractice(en.modules["deterministic-rendering"].corePractice, {
        title: "信任文件前先审计 render receipt", brief: "判断候选是否来自获批 input 与合同，并把执行成功和编辑批准分开。",
        steps: ["匹配全部 dependency hash。", "检查 executor version 与 argv。", "比较实际 input/output hash。", "阅读 probe 与 failure evidence。", "拒绝从 exit zero 推断权利、含义或发布。"],
        artifact: "render-receipt.json。", reviewGate: "Dependency hash 缺失或 stale 时，凭据与候选失效。",
        aiBoundary: "Executor 可以报告执行了什么，不能认证真实、无障碍、权利或发布。",
        acceptanceChecks: ["Plan、delivery、policy 与 input hash current。", "Executor 与版本明确。", "argv 与 shell boundary 可检查。", "存在 output hash 与 probe facts。", "凭据不声称批准。"],
      }),
      productionPractice: localizePractice(en.modules["deterministic-rendering"].productionPractice!, {
        title: "用 FFmpeg 渲染 sandbox 候选", brief: "通过本地 executor 运行准确 plan，并保存真实候选与凭据。",
        steps: ["验证 tool preflight。", "解析 current contract hash。", "以 shell disabled 执行固定 argv。", "Hash 并 probe 输出。", "若停止，保存净化后的失败证据。"],
        artifact: "candidate.mp4 与 sandbox render receipt。", reviewGate: "Stale hash、不安全路径、覆盖、缺工具或 probe 失败都在验证前停止。",
        aiBoundary: "成功渲染只证明这一次受控执行。",
        acceptanceChecks: ["候选为 45–60 秒、1080×1920。", "记录实际 hash 与版本。", "Probe 确认 SDR Rec.709 policy。", "输出留在受控 root。", "不声称跨 build 字节一致。"],
      }),
      checkpoint: localizeCheckpoint(en.modules["deterministic-rendering"].checkpoint, "FFmpeg process 成功退出可以证明什么？", [
        ["所有输入与可见元素都已获发布许可。", "Process exit 不能建立法律权利。"],
        ["候选准确且有效地讲述预期故事。", "叙事与语义质量需要独立审查。"],
        ["记录化 process 已完成；准确输出仍需独立验证。", "正确：执行证据必要但不充分。"],
        ["Renderer 现在可以发布输出。", "执行永远不会转移发布权限。"],
      ], "凭据说明运行了什么；后续关口决定结果是否可接受。"),
      takeaway: "候选的可信度不会高于产生它的 current 输入、合同与凭据。",
    },
    "verification-human-review": {
      ...en.modules["verification-human-review"],
      kicker: "验证 · 模块 09", title: "验证、路由、修复、重渲染并回归",
      summary: "使用彼此分离的技术、语义、无障碍、权利与交付关口，以及有边界反馈闭环。",
      objective: "生成 verification report，把失败路由到致因上游产物，并用 rerender 与 regression 证明修复。",
      artifact: "verification-report.json + repair/regression receipt",
      concepts: localizeConcepts(en.modules["verification-human-review"].concepts, [
        ["多层 QC", "分开技术、语义、无障碍、权利/隐私与编辑/发布发现。"],
        ["有边界测量", "只回答一项声明问题、绑定输入、配置与限制的 metric。"],
        ["修复路由", "修改真正致因的上游产物，而不是掩盖症状。"],
        ["Retry bound", "预先声明自动修复轮次、成本、时间与允许修改的上限。"],
        ["Regression receipt", "修复后已重新渲染并重复所有受影响检查的证据。"],
      ]),
      sections: [
        localizeSection(en.modules["verification-human-review"].sections[0], "不同失败需要不同证据", [
          "FFmpeg 可以测量 stream facts，VMAF 可做有边界的 full-reference 视觉比较；两者都不判断语义真实性、权利、caption 含义、音频、无障碍或发布。",
          "无障碍验证要在实际编码候选上重新检查 caption 与视觉描述决定，不能假定 timeline state 已完整保留。",
          "音频 QC 记录声明的 BS.1770-compatible 测量与目的地规则；色彩 QC 确认获批 SDR Rec.709 路径。EBU R128 与 ACES 是有边界参考，不是自动批准。",
          "报告区分 pass、fail、not-checked 与 unavailable，并由可追责人复核 chronology、quotation、implication 与 portrayal。",
        ]),
        localizeSection(en.modules["verification-human-review"].sections[1], "把修复路由到原因，而非症状", [
          "权利或输入失败回到 M2；语义失败回到 M4/M5；权限失败回到 M6；caption、audio、frame 或 color 失败回到 M7；执行失败回到 M8。每项修复都触发 rerender、reverify 与 approval refresh。",
          "Retry 有明确上限。高风险问题反复失败时，保存证据并升级给责任人，而不是降低准确性/无障碍标准或伪造完成。",
        ]),
      ],
      corePractice: localizePractice(en.modules["verification-human-review"].corePractice, {
        title: "把五类失败路由到有边界修复闭环", brief: "审计每层各含一个问题的候选，并指出必须修改的准确产物。",
        steps: ["记录技术、语义、无障碍、权利与交付状态。", "命名 critical blocker。", "把每项修复路由上游。", "要求 rerender 与 reverify。", "达到 retry bound 时停止并升级。"],
        artifact: "verification-report.json 与 repair/regression receipt。", reviewGate: "平均分或技术 pass 不能隐藏 critical blocker。",
        aiBoundary: "智能体可以检测和路由；可追责人决定含义、权利、剩余风险与发布。",
        acceptanceChecks: ["全部层使用分类状态。", "每项失败命名有边界上游路由。", "Critical blocker 阻止 verified。", "产物变化要求 rerender/reverify。", "Retry 耗尽后升级。"],
      }),
      productionPractice: localizePractice(en.modules["verification-human-review"].productionPractice!, {
        title: "测量并修复 sandbox 候选", brief: "运行 probe、black、silence、audio-level、geometry、color、caption-safe 与结构检查，并修复一个 seeded failure。",
        steps: ["验证 candidate hash。", "运行确定性测量。", "复核序列与 caption-safe 证据。", "执行一次有边界上游修复。", "Rerender、reverify 并运行 regression。"],
        artifact: "Sandbox verification report、repair 与 regression receipt。", reviewGate: "只有修复后的 JSON、没有新 render receipt 与 candidate hash，仍属 stale。",
        aiBoundary: "Sandbox QC 只证明 fixture 机制，不证明真实人物语义或客户权利。",
        acceptanceChecks: ["Probe/QC 匹配实际候选。", "记录 caption-safe 与序列复核。", "Seeded failure 路由正确模块。", "修复后产生新 render 与 output hash。", "Regression 通过。"],
      }),
      checkpoint: localizeCheckpoint(en.modules["verification-human-review"].checkpoint, "高风险缺陷达到允许的 retry limit 后怎么办？", [
        ["继续 retry，直到智能体生成 passing report。", "无限 retry 会隐藏成本、不确定性与重复失败。"],
        ["候选已经渲染，因此降低 threshold。", "Sunk cost 不能合理化降低 critical control。"],
        ["停止、保存证据并升级给可追责责任人。", "正确：有边界系统诚实报告未解决 blocker。"],
        ["先私下发布，有反馈再修复。", "发布不是有效验证实验。"],
      ], "有边界修复保护证据链，并让未解决风险保持可见。"),
      takeaway: "验证是路由式反馈系统，不是一堵最终 checkbox 墙。",
    },
    "production-capstone": {
      ...en.modules["production-capstone"],
      kicker: "验证 · 模块 10", title: "生产交接与恢复演练",
      summary: "用可 relink package、无 secret runbook、中断／恢复证据与独立 recovery drill 闭合模块依赖链。",
      objective: "建立 package manifest、无 secret runbook、relink map、dry-run receipt、resume receipt、recovery rehearsal 与准确候选的 dependency-closure report。",
      artifact: "release-package.json + 无 secret runbook + relink/resume/recovery receipts",
      concepts: localizeConcepts(en.modules["production-capstone"].concepts, [
        ["Package manifest", "交接所需的 artifact、media reference、hash、version、owner 与 dependency edge 清单。"],
        ["依赖闭包", "证明每项下游产物都绑定全部 current 上游 hash。"],
        ["恢复演练", "第二位操作员无需 hidden state 即可 relink、dry-run、interrupt、resume 与 diagnose。"],
        ["Resume receipt", "证明中断运行从声明状态恢复，未依赖 hidden credential、隐含文件或未批准 mutation。"],
        ["生成媒体披露", "记录 generated/materially manipulated 区域、来源/provenance、同意、provider 条款、人类贡献与目的地审查的 production-sandbox 产物。"],
      ]),
      sections: [
        localizeSection(en.modules["production-capstone"].sections[0], "交接意味着另一位操作员可以恢复", [
          "OpenTimelineIO 可支持时间线交换和 bundle，FFmpeg 则记录实际媒体执行表面；两者都不能替代版本记录、relink 指令、依赖闭包与恢复演练。",
          "第二位操作员应能复现 artifact graph、dry-run executor、中断后恢复，并指出哪个上游 hash 会使每项 receipt 失效。",
        ]),
        localizeSection(en.modules["production-capstone"].sections[1], "交接 package 保留边界，不作后续发布决定", [
          "交接必须把 generated/materially manipulated 区域、source/provider path、同意或肖像状态、provider/output terms、人类贡献与目的地披露审查列为后续可追责决定的显式记录。缺少法域相关证据时继续阻断；本课程不提供法律意见。",
          "C2PA 可携带密码学绑定 provenance assertion，但不证明真实性、权利、同意或编辑准确性；恢复操作员不得把 metadata 提升为许可。",
          "M10 以可复现、权限中立的 handoff 结束。之后才进行正式测验与十二项 Capstone；只有绑定 current 闭包的具名人类决定才能记录 publish 或 do-not-publish。",
        ]),
      ],
      corePractice: localizePractice(en.modules["production-capstone"].corePractice, {
        title: "建立无 secret 交接与恢复演练", brief: "登记十个模块 receipt 背后的十二项 module-completion artifact，证明 dependency closure，从 manifest relink，dry-run、中断／恢复，并由第二位操作员恢复准确候选。",
        steps: ["列出每项 current 模块 artifact 与 content hash。", "证明 dependency closure。", "编写无 secret relink/dry-run runbook。", "从声明状态中断并 resume。", "由第二位操作员恢复并核对 candidate hash。"],
        artifact: "release-package manifest、无 secret runbook、relink map、resume receipt 与独立 recovery receipt。", reviewGate: "缺失、stale、含 secret 或依赖 hidden state 的证据不能完成 M10；之后的 Capstone 才拥有发布／不发布 artifact。",
        aiBoundary: "智能体可以组装并测试 handoff，不能豁免 blocker、推断同意、替后续决定作证或发布。",
        acceptanceChecks: ["全部上游模块 artifact 有效且 current。", "Closure report 命名 current hash。", "Runbook 不含 secret。", "存在 relink 与 resume receipt。", "独立操作员恢复准确 candidate hash。"],
      }),
      productionPractice: localizePractice(en.modules["production-capstone"].productionPractice!, {
        title: "交接并恢复准确 sandbox 候选", brief: "由第二位操作员 dry-run、relink、中断／resume、恢复并核对 final synthetic candidate hash，不依赖 hidden state。",
        steps: ["组装全部 sandbox receipt。", "从 manifest relink。", "模拟中断与 resume。", "重新核对恢复后的 candidate hash。", "登记独立恢复结果与留给后续决定的 blocker。"],
        artifact: "含无 secret runbook、relink/resume receipt、recovery drill 与 media hash 的 sandbox release package。", reviewGate: "任一上游 receipt stale、需要 secret／hidden path，或恢复得到不同 hash 时不完整。",
        aiBoundary: "Production-sandbox 扩展不自动验证真实客户权利，也不授予发布权限。",
        acceptanceChecks: ["上游 sandbox receipt current。", "登记 final media 准确 hash。", "存在 selected-executor receipt。", "第二位操作员恢复成功。", "Package 对之后的 Capstone 决定保持权限中立。"],
      }),
      checkpoint: localizeCheckpoint(en.modules["production-capstone"].checkpoint, "谁可以批准准确候选对外发布？", [
        ["最后运行的模型，因为它拥有最新上下文。", "上下文新旧不会产生法律或组织责任。"],
        ["任何可以打开并播放文件的人。", "访问不等于知情权限。"],
        ["审查准确 hash、证据、目的地与未解决风险的具名可追责人类。", "正确：决定必须知情、绑定目的地、绑定版本并可追责。"],
        ["全部技术检查通过后的 render engine。", "引擎不能承担编辑、权利或发布后果。"],
      ], "发布是对外行动，始终在智能体权限之外。"),
      takeaway: "Production readiness 意味着另一位人可以复现、拒绝、恢复并验证准确版本。",
    },
  },
  finalAssessment: {
    ...en.finalAssessment,
    title: "期末测验：你能控制完整证据链吗？",
    summary: "十题与十个模块一一对应。通过要求至少 80%，且权利/隐私、语义完整性、智能体权限与最终发布四项关键控制全部正确。核心产物未全部 current 前，得分只作诊断。",
    questions: [
      localizeFinalQuestion(en.finalAssessment.questions[0], "M1 · 剪辑合同", "哪项回应能把模糊创作请求变成可检查委托？", [
        ["先渲染，再根据反应推断意图，最后发布最强版本。", "这倒置了证据与权限链。"],
        ["不断改进 prompt，直到出现像成片的候选。", "精致输出不能定义验收或责任。"],
        ["依次定义意图、证据、合同、权限、执行、验证与最终决定。", "正确：每项后续产物都有显式用途与责任人。"],
        ["收集证据、先发布测试，再补写计划。", "发布不能充当缺失的批准门。"],
      ], "运行合同让后续每项行动都可以测试并追责。"),
      localizeFinalQuestion(en.finalAssessment.questions[1], "M2 · 媒体与源时钟", "敏感媒体进入任何可选外部处理路径前需要什么？", [
        ["稳定网络与上传 checksum。", "可靠性不能建立权限、保留或目的。"],
        ["删除本地副本，确保只剩一个版本。", "这会破坏源证据，也不能授权披露。"],
        ["桌面界面，因为桌面产品都会本地处理。", "桌面软件仍可能调用远程服务。"],
        ["明确数据路径、权限、目的、地域、保留、删除与知情许可。", "正确：披露必须显式且获授权。"],
      ], "Local-first 品牌不能替代已核验数据路径与可追责许可。"),
      localizeFinalQuestion(en.finalAssessment.questions[2], "M3 · 带时间码证据", "应如何定位 mixed-rate 或 VFR 证据？", [
        ["全部转成十进制秒，再 round 到最近显示帧。", "Rounding 会抹去源时钟身份并在不同 rate 间漂移。"],
        ["在每个已声明源时钟中使用整数帧；VFR 必须带 lineage/time map 后 conform。", "正确：源与时间线时钟保持显式、可复现。"],
        ["排除与 timeline rate 不同的所有素材。", "只要映射明确，mixed rate 可以管理。"],
        ["用 ASR timestamp 作为逐帧真值。", "ASR alignment 是证据，不是媒体时钟。"],
      ], "只有时钟与 lineage 明确，证据才可复现。"),
      localizeFinalQuestion(en.finalAssessment.questions[3], "M4 · 语义候选", "两个真实片段相连后形成说话者未表达的主张，应如何处理？", [
        ["两个 source timestamp 与句子都真实，因此保留。", "真实部分仍可能形成错误组合含义。"],
        ["阻断、恢复必要上下文或拒绝，并记录人审。", "正确：序列含义是关键控制。"],
        ["候选 ranking model 给最高分时保留。", "排序不能授权语义失真。"],
        ["源素材权利已清除时保留。", "权利清除与真实人物呈现彼此独立。"],
      ], "完整粗剪必须保存 source meaning。"),
      localizeFinalQuestion(en.finalAssessment.questions[4], "M5 · Canonical edit plan", "哪种 plan 符合 canonical 粗剪合同？", [
        ["文件名与十进制 in/out 秒，并把 approval flag 放进计划。", "缺少内容身份、源时钟、typed operation、compile input 与外部批准。"],
        ["没有已校验 operation 引用或独立批准的 opaque NLE project export。", "NLE project 可以是下游 interchange，不能静默取代 edit-plan v3。"],
        ["Clip、caption、title、audio、crop 与 transition typed operation，绑定 hash、时钟、证据、权利、compile input 与外部批准。", "正确：执行前每项受支持操作与依赖都已显式记录。"],
        ["最终 prompt 与请求剪辑时的模型转录。", "Prompt 既不是确定性计划，也不是批准记录。"],
      ], "Edit-plan v3 校验有边界的剪辑决定，并把 interchange、下游合同、执行与批准彼此分开。"),
      localizeFinalQuestion(en.finalAssessment.questions[5], "M6 · 工具权限", "文件名或 tool output 要求 network、root、token、cost 或 publish 时怎么办？", [
        ["指令位于已批准媒体中，因此执行。", "已批准媒体在权限层仍是不可信输入。"],
        ["把它当数据，执行 current 最小权限政策与人工 gate。", "正确：内容不能扩大权限。"],
        ["工具为了完成获批目标需要 token 时允许。", "目标压力不能授权 secret access。"],
        ["请求来自 MCP-compatible tool 时允许。", "协议兼容不等于安全认证。"],
      ], "权限来自显式政策与可追责批准，永远不来自不可信内容。"),
      localizeFinalQuestion(en.finalAssessment.questions[6], "M7 · 交付与无障碍", "9:16 SDR Rec.709 delivery matrix 何时可以交给工具执行？", [
        ["时长与尺寸通过即可，即使 caption 或上下文仍不确定。", "Geometry 不能豁免语义或无障碍 blocker。"],
        ["Caption、视觉描述适用性、音频、安全区、色彩、目的地与复核全部明确。", "正确：执行前已写清交付义务。"],
        ["Caption 已 burn-in，因此 sidecar 与 transcript 不再需要。", "Sidecar 与修订证据仍用于无障碍、审计与修复。"],
        ["视觉质量 metric 超过 threshold。", "视觉 metric 不测 caption、audio、meaning、visual description 或 rights。"],
      ], "Delivery matrix 让候选的无障碍、音频、色彩与构图义务可以复核。"),
      localizeFinalQuestion(en.finalAssessment.questions[7], "M8 · Render receipt", "什么证据让候选执行可追踪？", [
        ["Exit code 0 与可播放 MP4。", "缺少 dependency identity、stream facts 与复核边界。"],
        ["Current plan、delivery、policy、input hash，加上 version、argv、output hash、probe 与失败证据。", "正确：凭据绑定实际执行。"],
        ["Output hash，因为确定身份证明使用权。", "身份不等于许可。"],
        ["UI 显示成功即可，stderr 与 tool version 留在内部。", "隐藏失败证据会破坏复现与诊断。"],
      ], "执行凭据支持验证，但不能取代验证。"),
      localizeFinalQuestion(en.finalAssessment.questions[8], "M9 · 有边界修复", "渲染后发现 caption-safe failure，正确闭环是什么？", [
        ["路由回 M7，更新 matrix，rerender、reverify、regress；达到上限则升级。", "正确：修复遵循因果并刷新依赖证据。"],
        ["不断用新 layout 猜测 rerender，直到通过。", "无限试错会隐藏原因、成本与权限。"],
        ["语义没变，因此放宽 safe-zone threshold。", "已声明标准不能静默豁免。"],
        ["修复 MP4 后删除失败报告。", "失败状态与 repair receipt 属于审计链。"],
      ], "验证是返回致因上游产物的有边界反馈闭环。"),
      localizeFinalQuestion(en.finalAssessment.questions[9], "M10 · 恢复与决定", "Release package 何时可以写 approve？", [
        ["智能体不再有 warning 且停止提问时。", "智能体沉默不是可追责批准。"],
        ["Render、probe 与技术 QC 全部通过时。", "技术成功不能决定权利、含义、目的地或剩余风险。"],
        ["具名人类审查准确 package hash、证据、目的地、权利与未解决风险后。", "正确：批准必须显式、知情、绑定版本并可追责。"],
        ["候选上传成功但仍是 unlisted 时。", "上传已经是外部披露，不能先于权限。"],
      ], "Do-not-publish 也是有效成功；原创 fixture-safe 实验要求该决定。"),
    ],
  },
  capstone: { audit: zhCapstone, production: zhCapstone },
} as const satisfies AgenticVideoEditingCourseCopy;

export const AGENTIC_VIDEO_EDITING_ZH_HANS_COPY = {
  ...AGENTIC_VIDEO_EDITING_ZH_HANS_COPY_RAW,
  modules: Object.fromEntries(
    AGENTIC_VIDEO_EDITING_MODULE_SLUGS.map((slug) => [
      slug,
      AGENTIC_VIDEO_EDITING_ZH_HANS_COPY_RAW.modules[slug],
    ]),
  ),
} as unknown as AgenticVideoEditingCourseCopy;
