import type { CourseKitModuleAuthoringSeed } from "../course-kit/authoring";
import type {
  CourseKitFourOptions,
  CourseKitNonEmpty,
  CourseKitOptionIndex,
} from "../course-kit/types";
import type { MachineLearningSourceId } from "./sources";

interface MachineLearningModuleText {
  readonly title: string;
  readonly summary: string;
  readonly objective: string;
  readonly artifact: string;
  readonly conceptHeading: string;
  readonly conceptParagraph: string;
  readonly boundaryHeading: string;
  readonly boundaryParagraph: string;
  readonly practiceTitle: string;
  readonly practiceBrief: string;
  readonly steps: CourseKitNonEmpty<string>;
  readonly deliverable: string;
  readonly reviewGate: string;
  readonly checkpointQuestion: string;
  readonly checkpointOptions: CourseKitFourOptions;
  readonly checkpointCorrectIndex: CourseKitOptionIndex;
  readonly checkpointExplanation: string;
  readonly takeaway: string;
}

function machineLearningModule<
  const Slug extends string,
  const PhaseId extends string,
  const SourceId extends MachineLearningSourceId,
>(seed: {
  readonly slug: Slug;
  readonly phaseId: PhaseId;
  readonly minutes: number;
  readonly sourceIds: CourseKitNonEmpty<SourceId>;
  readonly en: MachineLearningModuleText;
  readonly zhHans: MachineLearningModuleText;
}): CourseKitModuleAuthoringSeed<Slug, PhaseId, SourceId> {
  const copy = (text: MachineLearningModuleText) => ({
    title: text.title,
    summary: text.summary,
    objective: text.objective,
    artifact: text.artifact,
    sections: [
      {
        heading: text.conceptHeading,
        paragraphs: [text.conceptParagraph],
        sourceIds: seed.sourceIds,
        evidenceMode: "source-grounded" as const,
      },
      {
        heading: text.boundaryHeading,
        paragraphs: [text.boundaryParagraph],
        sourceIds: seed.sourceIds,
        evidenceMode: "instructional-synthesis" as const,
      },
    ] as const,
    practice: {
      title: text.practiceTitle,
      brief: text.practiceBrief,
      steps: text.steps,
      deliverable: text.deliverable,
      reviewGate: text.reviewGate,
    },
    checkpoint: {
      question: text.checkpointQuestion,
      options: text.checkpointOptions,
      correctIndex: text.checkpointCorrectIndex,
      explanation: text.checkpointExplanation,
    },
    takeaway: text.takeaway,
  });
  return {
    slug: seed.slug,
    phaseId: seed.phaseId,
    minutes: seed.minutes,
    sourceIds: seed.sourceIds,
    copy: { en: copy(seed.en), zhHans: copy(seed.zhHans) },
  };
}

export const MACHINE_LEARNING_MODULES = [
  machineLearningModule({
    slug: "framing-baselines-splits",
    phaseId: "supervised-foundations",
    minutes: 60,
    sourceIds: ["sklearn-pitfalls-cv", "ml-test-score"],
    en: {
      title: "Problem framing, baselines and train/validation/test splits",
      summary: "Translate a decision into a prediction-time contract, define a baseline and error costs, then freeze train, validation, and untouched holdout boundaries before modeling.",
      objective: "Write a no-deployment prediction contract and construct a group-aware fixed split in which every feature is available at the stated prediction time.",
      artifact: "Split contract with decision owner, unit, target, prediction time, feature-availability ledger, group boundary, baseline, metrics, and holdout checksum",
      conceptHeading: "The split must simulate the future decision",
      conceptParagraph: "A supervised-learning row links features available at a declared prediction time to a target observed over a declared horizon. Training estimates parameters, validation supports bounded design choices, and an untouched holdout estimates the frozen candidate. A simple prevalence, mean, rule, or last-value baseline tests whether modeling adds value beyond information already available.",
      boundaryHeading: "Random rows are not a universal evaluation design",
      boundaryParagraph: "Learner repeats, household or class groups, temporal ordering, intervention effects, duplicate records, and post-outcome fields can leak information across a random split. The contract must list who or what may cross partitions, when every feature becomes available, how the target is produced, which decisions used validation labels, and why the holdout remains untouched until final review.",
      practiceTitle: "Freeze the prediction and split contract",
      practiceBrief: "Use the fixed fictional fixture to frame a low-stakes analytic exercise while explicitly prohibiting automated student decisions.",
      steps: ["Name the hypothetical decision, human owner, unit, target horizon, action, and no-deployment boundary.", "Create a feature-availability ledger with timestamps and exclude post-target or identifier-derived fields.", "Assign grouped records to train, validation, and holdout with a fixed rule and hash each partition.", "Compute a simple baseline and predeclare primary, secondary, subgroup, and capacity-aware metrics."],
      deliverable: "A frozen split contract whose partitions, availability logic, baseline, and decision limits can be audited before any model is fit",
      reviewGate: "No learner code crosses partitions, no feature uses information after prediction time, and the holdout checksum is fixed before model comparison.",
      checkpointQuestion: "Which split best estimates a model for future learners when each learner has repeated rows?",
      checkpointOptions: ["Randomly split rows so the same learner can appear everywhere", "Keep every learner in one partition and preserve any required time order", "Fit preprocessing on all rows, then split", "Choose the split that gives the highest validation score"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Keeping the unit together prevents repeated-person information from crossing partitions; time order must also reflect the intended future use.",
      takeaway: "Frame the decision and freeze a leakage-aware split before modeling; holdout labels are evidence, not a tuning resource.",
    },
    zhHans: {
      title: "问题框定、基线与数据切分",
      summary: "把决策转成预测时点合同，定义基线与错误成本，并在建模前冻结训练、验证与未触碰留出集边界。",
      objective: "撰写不可部署预测合同，并建立群组感知固定切分，确保每个特征在声明的预测时点可用。",
      artifact: "包含决策负责人、单元、目标、预测时点、特征可用性台账、群组边界、基线、指标与留出集校验和的切分合同",
      conceptHeading: "切分必须模拟未来决策",
      conceptParagraph: "监督学习的一行把声明预测时点可用的特征连接到声明时间范围后观察到的目标。训练用于估计参数，验证用于有边界的设计选择，未触碰留出集用于评估冻结候选。流行率、均值、规则或上一时点等简单基线会检验建模是否真正增加价值。",
      boundaryHeading: "随机行切分不是通用评价设计",
      boundaryParagraph: "学习者重复、家庭或班级群组、时间顺序、干预效应、重复记录与结果后字段，都可能通过随机切分泄漏信息。合同必须列出哪些对象可跨分区、每个特征何时可用、目标如何产生、哪些决定使用了验证标签，以及为何留出集直到最终审查都未触碰。",
      practiceTitle: "冻结预测与切分合同",
      practiceBrief: "使用固定虚构 fixture 框定低风险分析练习，并明确禁止自动化学生决策。",
      steps: ["说明假想决策、人类负责人、单元、目标范围、行动与不可部署边界。", "建立带时间戳的特征可用性台账，排除结果后或标识符衍生字段。", "用固定规则把群组记录分到训练、验证和留出集，并对每个分区哈希。", "计算简单基线，并预先声明主要、次要、子群与容量感知指标。"],
      deliverable: "一份在拟合任何模型前即可审查分区、可用性逻辑、基线与决策限制的冻结切分合同",
      reviewGate: "没有学习者代码跨分区，没有特征使用预测时点后的信息，留出集校验和也在模型比较前固定。",
      checkpointQuestion: "每位学习者有重复记录时，哪种切分最适合估计对未来学习者的表现？",
      checkpointOptions: ["随机切行，让同一学习者出现在各分区", "让每位学习者只属于一个分区，并保留必要时间顺序", "先在全部记录上拟合预处理，再切分", "选择验证分数最高的切分"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "保持分析单元不跨分区可阻止同一人的信息泄漏；时间顺序也必须反映预期未来用途。",
      takeaway: "建模前先框定决策并冻结防泄漏切分；留出集标签是证据，不是调参资源。",
    },
  }),
  machineLearningModule({
    slug: "linear-regression-loss-residuals",
    phaseId: "supervised-foundations",
    minutes: 70,
    sourceIds: ["sklearn-linear-models", "sklearn-pitfalls-cv"],
    en: {
      title: "Linear regression, loss and residuals",
      summary: "Build a mean and linear baseline, connect squared loss to fitted predictions, and inspect residual structure rather than reporting one aggregate score.",
      objective: "Fit a training-only linear pipeline, compare it with a mean baseline, and produce a residual report across range, cohort, and partition.",
      artifact: "Residual report with baseline comparison, coefficient units, residual plots, subgroup tables, influential cases, uncertainty limits, and non-causal interpretation",
      conceptHeading: "Least squares minimizes a defined prediction error",
      conceptParagraph: "Linear regression represents a conditional prediction as an intercept plus weighted features and commonly estimates coefficients by minimizing squared residuals. Mean squared error emphasizes large errors, mean absolute error answers a different loss question, and residual views reveal curvature, changing variance, clusters, and influential points that a single average can hide.",
      boundaryHeading: "Prediction coefficients are not causal effects",
      boundaryParagraph: "A coefficient is conditional on encoding, scale, included variables, collinearity, regularization, sample, and loss. Extrapolation beyond observed feature support can be unstable; heteroskedastic or dependent errors affect uncertainty; and a good average residual score does not show equitable or decision-useful performance across subgroups.",
      practiceTitle: "Audit a linear baseline",
      practiceBrief: "Predict a fictional continuous outcome while keeping all transformations inside the training-only pipeline.",
      steps: ["Define target units and compute the train-set mean baseline on validation and holdout without refitting.", "Fit scaling or encoding and linear regression inside one pipeline using training records only.", "Report MAE and RMSE alongside residuals versus prediction, feature range, and cohort.", "Identify extrapolation, high-influence cases, and why no coefficient receives a causal label."],
      deliverable: "A residual report that shows where the linear model improves on the mean baseline and where its assumptions or support fail",
      reviewGate: "All preprocessing is fit on training data, baseline and model use the same partitions, and every coefficient is labeled with units and a non-causal boundary.",
      checkpointQuestion: "What does a curved residual pattern most directly suggest?",
      checkpointOptions: ["The target is automatically causal", "The linear functional form may be missing systematic structure", "The holdout can now be used for tuning", "The model is calibrated for classification"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Systematic curvature means errors vary with the prediction or feature range, so the chosen linear form may not capture relevant structure.",
      takeaway: "A regression score is incomplete without a baseline, residual diagnostics, support limits, and a clear refusal to read predictive coefficients causally.",
    },
    zhHans: {
      title: "线性回归、损失与残差",
      summary: "建立均值与线性基线，把平方损失连接到拟合预测，并检查残差结构，而不是只报告一个汇总分数。",
      objective: "拟合仅训练数据的线性管线，与均值基线比较，并按范围、队列与分区制作残差报告。",
      artifact: "包含基线比较、系数单位、残差图、子群表、影响点、不确定性限制与非因果解释的残差报告",
      conceptHeading: "最小二乘最小化已定义的预测误差",
      conceptParagraph: "线性回归把条件预测表示为截距加特征加权和，并通常通过最小化平方残差估计系数。均方误差更强调大误差，平均绝对误差回答另一种损失问题，而残差视图会揭示单一平均数可能隐藏的曲率、方差变化、聚类与影响点。",
      boundaryHeading: "预测系数不是因果效应",
      boundaryParagraph: "系数取决于编码、尺度、纳入变量、共线性、正则化、样本与损失。超出观测特征支持范围的外推可能不稳定，异方差或依赖误差会影响不确定性，而良好平均残差分数也不能说明各子群表现公平或对决策有用。",
      practiceTitle: "审计线性基线",
      practiceBrief: "预测一个虚构连续结果，同时把所有转换保留在仅训练数据拟合的管线中。",
      steps: ["定义目标单位，在不重新拟合的情况下把训练集均值基线应用到验证与留出集。", "只用训练记录，在同一管线内拟合缩放或编码与线性回归。", "同时报告 MAE、RMSE，以及残差对预测、特征范围和队列的关系。", "识别外推和高影响案例，并说明为何不给任何系数贴因果标签。"],
      deliverable: "一份展示线性模型在哪些地方优于均值基线、哪些地方违反假设或超出支持范围的残差报告",
      reviewGate: "全部预处理仅在训练数据上拟合，基线和模型使用同一分区，每个系数都标注单位与非因果边界。",
      checkpointQuestion: "弯曲的残差模式最直接说明什么？",
      checkpointOptions: ["目标自动具有因果性", "线性函数形式可能遗漏系统结构", "现在可以用留出集调参", "模型已完成分类校准"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "系统曲率说明误差随预测或特征范围变化，因此所选线性形式可能未捕捉相关结构。",
      takeaway: "没有基线、残差诊断、支持范围限制与明确拒绝因果解读，回归分数并不完整。",
    },
  }),
  machineLearningModule({
    slug: "logistic-regression-classification",
    phaseId: "supervised-foundations",
    minutes: 70,
    sourceIds: ["sklearn-linear-models", "sklearn-metrics", "sklearn-pitfalls-cv"],
    en: {
      title: "Logistic regression and classification",
      summary: "Separate probabilistic estimation, ranking, and class decisions while comparing logistic regression with a prevalence baseline under a frozen label contract.",
      objective: "Fit a logistic pipeline, report probability and ranking behavior, and postpone the operating threshold until costs and review capacity are defined.",
      artifact: "Classifier baseline report with label contract, prevalence baseline, coefficient boundary, probability distribution, ranking metrics, confusion matrices, and threshold non-decision",
      conceptHeading: "A classifier score is not yet an action",
      conceptParagraph: "Logistic regression models log odds as a linear function and produces a score convertible to a probability under its fitted assumptions. Ranking metrics evaluate ordering, probabilistic metrics evaluate numerical estimates, and a threshold converts scores into class labels. These are distinct questions and should be evaluated separately against a simple prevalence or rule baseline.",
      boundaryHeading: "Labels and thresholds encode consequences",
      boundaryParagraph: "An observed label can reflect policy, access, measurement error, prior intervention, or an administrative proxy rather than the construct of interest. A default 0.5 threshold rarely represents actual error costs or review capacity, and apparent coefficient direction remains conditional rather than causal. The exercise therefore prohibits automated action and retains human review authority.",
      practiceTitle: "Separate score, probability, and decision",
      practiceBrief: "Build a fictional completion classifier without turning its output into a student-support action.",
      steps: ["Write the target definition, observation window, label-production process, exclusions, and known proxy risks.", "Fit an encoded logistic pipeline on training data and compare it with prevalence and simple-rule baselines.", "Report log loss or Brier score, ROC/PR summaries, and confusion matrices at several illustrative thresholds.", "Leave the action threshold unset and document the costs, capacity, authority, and evidence needed to choose one."],
      deliverable: "A classifier baseline report that keeps labels, probabilities, rankings, thresholds, and human action authority distinct",
      reviewGate: "No metric or default threshold is presented as an intervention rule, and the label's measurement and policy limitations are visible.",
      checkpointQuestion: "What turns a probability score into a binary prediction?",
      checkpointOptions: ["The feature scaler", "A chosen decision threshold", "The training row order", "The source-code licence"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "The estimator provides a score or probability; a separately chosen threshold creates a binary label and embeds decision tradeoffs.",
      takeaway: "Probability estimation, ranking, and action thresholds are different contracts; a default class label must not silently become a consequential decision.",
    },
    zhHans: {
      title: "逻辑回归与分类",
      summary: "在冻结标签合同下比较逻辑回归与流行率基线，同时分开概率估计、排序与类别决策。",
      objective: "拟合逻辑回归管线，报告概率与排序行为，并把操作阈值推迟到错误成本与审查容量定义之后。",
      artifact: "包含标签合同、流行率基线、系数边界、概率分布、排序指标、混淆矩阵与阈值非决定的分类器基线报告",
      conceptHeading: "分类器分数还不是行动",
      conceptParagraph: "逻辑回归把对数优势建模为线性函数，并在拟合假设下产生可转换为概率的分数。排序指标评价次序，概率指标评价数值估计，阈值则把分数变成类别标签。这是不同问题，应分别与流行率或简单规则基线比较。",
      boundaryHeading: "标签与阈值编码后果",
      boundaryParagraph: "观测标签可能反映政策、机会、测量误差、先前干预或行政代理，而不是目标构念。默认 0.5 阈值很少代表真实错误成本或审查容量，系数方向也仍是条件性而非因果。本练习因此禁止自动行动并保留人类审查权。",
      practiceTitle: "分开分数、概率与决策",
      practiceBrief: "建立虚构完成状态分类器，但不把输出转成学生支持行动。",
      steps: ["写出目标定义、观察窗口、标签生成过程、排除项与已知代理风险。", "只在训练数据拟合编码逻辑管线，并与流行率和简单规则基线比较。", "报告对数损失或 Brier 分数、ROC/PR 汇总，以及多个示例阈值的混淆矩阵。", "不设行动阈值，并记录选择阈值所需的成本、容量、权限与证据。"],
      deliverable: "一份把标签、概率、排序、阈值与人类行动权保持分开的分类器基线报告",
      reviewGate: "没有指标或默认阈值被表述为干预规则，标签的测量与政策限制也保持可见。",
      checkpointQuestion: "什么把概率分数变成二元预测？",
      checkpointOptions: ["特征缩放器", "选定的决策阈值", "训练行顺序", "源代码许可"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "估计器提供分数或概率；另行选择的阈值产生二元标签，并嵌入决策取舍。",
      takeaway: "概率估计、排序与行动阈值是不同合同；默认类别标签不能静默变成后果性决策。",
    },
  }),
  machineLearningModule({
    slug: "optimisation-scaling-features",
    phaseId: "models-and-generalisation",
    minutes: 65,
    sourceIds: ["sklearn-preprocessing", "sklearn-linear-models", "sklearn-pitfalls-cv"],
    en: {
      title: "Optimisation, scaling and features",
      summary: "Connect loss, gradients, convergence, scale, encoding, and feature availability while fitting every learned transformation inside the training partition.",
      objective: "Build a ColumnTransformer pipeline, compare scaled and unscaled optimization behavior, and audit feature units, availability, and learned preprocessing state.",
      artifact: "Feature pipeline receipt with field roles, units, availability times, transformations, fitted-state hashes, convergence diagnostics, and leakage checks",
      conceptHeading: "Optimization follows the surface created by data and model",
      conceptParagraph: "An optimizer changes parameters to reduce a specified objective. Feature scales can make the objective surface poorly conditioned for gradient-based or distance-sensitive methods, while categorical encodings and transformations define the coordinates the estimator sees. A pipeline couples learned preprocessing with the estimator so cross-validation refits both within each training fold.",
      boundaryHeading: "Scaling is method-dependent and cannot repair semantics",
      boundaryParagraph: "Tree splits usually do not require the same scaling as gradient or distance methods, and a converged solver only found a solution to the encoded objective. Scaling an invalid proxy, fitting an imputer on the full dataset, or encoding a category introduced after prediction time still yields leakage or a meaningless feature despite clean convergence.",
      practiceTitle: "Audit a learned feature path",
      practiceBrief: "Compare a scaled linear pipeline with a tree baseline while keeping transformations partition-local.",
      steps: ["Classify every field as numeric, categorical, identifier, target-derived, post-time, or excluded, with units and availability time.", "Build ColumnTransformer branches and place them with the estimator in one pipeline.", "Compare convergence, coefficients, and validation performance with and without appropriate scaling.", "Inspect fitted means, variances, categories, and feature names to prove no validation or holdout state entered training."],
      deliverable: "A feature pipeline receipt that connects each model input to an allowed source field and fold-local fitted transformation",
      reviewGate: "Every learned preprocessing statistic can be traced to training rows only, and excluded identifiers or post-time fields cannot enter the transformed feature matrix.",
      checkpointQuestion: "Where should a learned scaler be fit during cross-validation?",
      checkpointOptions: ["Once on the complete dataset before splitting", "Inside the pipeline on each training fold only", "On the holdout because it is most realistic", "Separately on each individual row"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Fold-local fitting prevents validation information from influencing transformation parameters and mirrors the future prediction path.",
      takeaway: "Optimization diagnostics are meaningful only after feature semantics, availability, units, and fold-local preprocessing have been audited.",
    },
    zhHans: {
      title: "优化、缩放与特征管线",
      summary: "连接损失、梯度、收敛、尺度、编码与特征可用性，并把每项学习型转换限制在训练分区内拟合。",
      objective: "建立 ColumnTransformer 管线，比较缩放与未缩放优化行为，并审计特征单位、可用性与已学习预处理状态。",
      artifact: "包含字段角色、单位、可用时间、转换、拟合状态哈希、收敛诊断与泄漏检查的特征管线收据",
      conceptHeading: "优化沿数据与模型共同形成的曲面进行",
      conceptParagraph: "优化器改变参数以降低已指定目标。特征尺度会使基于梯度或距离的方法面临条件不良的目标曲面，类别编码与转换则定义估计器看到的坐标。管线把学习型预处理与估计器绑定，使交叉验证在每个训练折内重新拟合两者。",
      boundaryHeading: "缩放取决于方法，也无法修复语义",
      boundaryParagraph: "树分裂通常不需要与梯度或距离方法相同的缩放，求解器收敛也只表示找到了编码目标的解。缩放无效代理、在全数据拟合插补器，或编码预测时点后才出现的类别，即使干净收敛也仍是泄漏或无意义特征。",
      practiceTitle: "审计学习型特征路径",
      practiceBrief: "比较缩放线性管线与树基线，同时使转换只在各分区训练部分拟合。",
      steps: ["按数值、类别、标识符、目标衍生、时点后或排除分类每个字段，并记录单位和可用时间。", "建立 ColumnTransformer 分支，并与估计器放入同一管线。", "比较合理缩放前后的收敛、系数与验证表现。", "检查拟合均值、方差、类别和特征名，证明验证或留出状态未进入训练。"],
      deliverable: "一份把每个模型输入连接到获准来源字段与折内拟合转换的特征管线收据",
      reviewGate: "每项学习型预处理统计都只能追溯到训练行，排除的标识符或时点后字段无法进入转换特征矩阵。",
      checkpointQuestion: "交叉验证期间，学习型缩放器应在哪里拟合？",
      checkpointOptions: ["切分前在完整数据上拟合一次", "在管线内部，只对每个训练折拟合", "在留出集上拟合，因为它最真实", "对每一行分别拟合"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "折内拟合可防止验证信息影响转换参数，并模拟未来预测路径。",
      takeaway: "只有先审计特征语义、可用性、单位与折内预处理，优化诊断才有意义。",
    },
  }),
  machineLearningModule({
    slug: "regularisation-bias-variance",
    phaseId: "models-and-generalisation",
    minutes: 70,
    sourceIds: ["sklearn-linear-models", "lasso-paper", "sklearn-pitfalls-cv"],
    en: {
      title: "Regularisation, bias and variance",
      summary: "Use learning curves and nested design choices to diagnose underfit and instability, then compare L1, L2, and complexity controls without claiming automatic feature selection truth.",
      objective: "Run a training-only regularization study with fixed search space, learning curves, repeated validation, stability checks, and one untouched final evaluation.",
      artifact: "Regularization study with predeclared search space, learning curves, validation variability, coefficient stability, selected complexity, and one-shot holdout result",
      conceptHeading: "Regularization changes the fitting objective",
      conceptParagraph: "L2 penalties shrink coefficients smoothly, while L1 penalties can produce exact zeros under some conditions. Complexity control trades fit to the observed training sample against sensitivity to variation, and learning curves compare training and validation behavior as data grows. Hyperparameters are model choices and must be selected without consulting final holdout labels.",
      boundaryHeading: "Sparse coefficients are not a stable causal feature list",
      boundaryParagraph: "With correlated predictors, small sample changes can swap which L1 coefficient remains nonzero, and preprocessing scale changes the effective penalty. Bias and variance are diagnostic concepts rather than directly observed constants. Report selection frequency, validation spread, and alternative models instead of declaring the surviving variables uniquely important or causal.",
      practiceTitle: "Study complexity without spending the holdout",
      practiceBrief: "Compare unregularized, L2, and L1 logistic models using only train and validation partitions.",
      steps: ["Predeclare penalty families, parameter grid, metric, tie rule, and maximum number of comparisons.", "Generate learning curves and repeated validation results with preprocessing inside the pipeline.", "Measure coefficient sign and selection stability across folds or resamples.", "Freeze one candidate, evaluate the holdout once, and report selection uncertainty and non-causal limits."],
      deliverable: "A regularization study that shows the performance-complexity tradeoff and instability rather than hiding search variance",
      reviewGate: "The holdout was evaluated only after the search and tie rule were frozen, and sparse coefficients are accompanied by stability evidence and non-causal language.",
      checkpointQuestion: "What is the safest interpretation of a LASSO coefficient equal to zero?",
      checkpointOptions: ["The variable has no causal effect in the population", "Under this data, preprocessing, objective, penalty, and fit, the optimizer set that coefficient to zero", "The variable can be deleted from every future task", "The feature was measured without error"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "L1 selection is conditional on the fitted problem and can change with scaling, correlated features, samples, and penalty strength.",
      takeaway: "Regularization manages a conditional fit-complexity tradeoff; it does not certify stable variables, causal importance, or future generalization.",
    },
    zhHans: {
      title: "正则化、偏差、方差与模型选择",
      summary: "用学习曲线与嵌套设计选择诊断欠拟合和不稳定，再比较 L1、L2 与复杂度控制，而不宣称自动得到真实特征。",
      objective: "运行仅训练数据的正则化研究，具有固定搜索空间、学习曲线、重复验证、稳定性检查与一次未触碰最终评价。",
      artifact: "包含预声明搜索空间、学习曲线、验证变异、系数稳定性、选定复杂度与一次性留出结果的正则化研究",
      conceptHeading: "正则化会改变拟合目标",
      conceptParagraph: "L2 惩罚平滑收缩系数，L1 惩罚在某些条件下可产生精确零。复杂度控制在拟合观测训练样本与对变异敏感之间取舍，学习曲线则比较数据增加时的训练与验证行为。超参数属于模型选择，不能查看最终留出标签来决定。",
      boundaryHeading: "稀疏系数不是真实稳定的因果特征清单",
      boundaryParagraph: "存在相关预测变量时，小样本变化就可能交换哪个 L1 系数保持非零，预处理尺度也会改变有效惩罚。偏差与方差是诊断概念，不是可直接观察常数。应报告选择频率、验证分布与替代模型，而不是宣称保留变量具有唯一重要性或因果性。",
      practiceTitle: "不消耗留出集地研究复杂度",
      practiceBrief: "只用训练和验证分区比较无正则、L2 与 L1 逻辑模型。",
      steps: ["预先声明惩罚族、参数网格、指标、平局规则与最大比较次数。", "在管线内预处理，生成学习曲线与重复验证结果。", "测量各折或重抽样中的系数符号与选择稳定性。", "冻结一个候选，只评价留出集一次，并报告选择不确定性与非因果限制。"],
      deliverable: "一份展示性能-复杂度取舍与不稳定性，而不隐藏搜索变异的正则化研究",
      reviewGate: "只有在搜索与平局规则冻结后才评价留出集，稀疏系数也附有稳定性证据和非因果表述。",
      checkpointQuestion: "如何最安全地解释等于零的 LASSO 系数？",
      checkpointOptions: ["该变量在总体中没有因果效应", "在此数据、预处理、目标、惩罚与拟合下，优化器把该系数设为零", "该变量可从所有未来任务删除", "该特征测量无误差"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "L1 选择以拟合问题为条件，会随缩放、相关特征、样本与惩罚强度变化。",
      takeaway: "正则化管理条件性的拟合-复杂度取舍；它不认证稳定变量、因果重要性或未来泛化。",
    },
  }),
  machineLearningModule({
    slug: "trees-ensembles",
    phaseId: "models-and-generalisation",
    minutes: 75,
    sourceIds: ["sklearn-ensembles", "random-forest-paper", "sklearn-pitfalls-cv"],
    en: {
      title: "Trees and ensembles",
      summary: "Compare a pruned tree, bagged forest, and boosted model against simpler baselines while accounting for stochasticity, complexity, latency, and unstable importance measures.",
      objective: "Run a controlled ensemble comparison with identical splits and metrics, then document variance, resource cost, error slices, and explanation limits.",
      artifact: "Ensemble comparison with frozen split, baseline, model cards, repeated seeds, complexity and latency table, error slices, and importance stress test",
      conceptHeading: "Ensembles combine varied learners",
      conceptParagraph: "A decision tree partitions feature space through a sequence of splits. Bagging and random forests reduce correlation by fitting varied trees across resampled data and feature subsets, while boosting adds learners sequentially to improve a specified objective. Their benefits must be evaluated against a pruned tree, linear model, and decision-relevant baseline on the same partitions.",
      boundaryHeading: "Importance and accuracy remain conditional",
      boundaryParagraph: "Impurity-based importance can favor high-cardinality or frequently split features, permutation importance changes with correlated predictors and evaluation data, and stochastic fits vary by seed. A stronger average score can hide calibration, subgroup, latency, memory, interpretability, or operational costs, so no ensemble is declared universally best.",
      practiceTitle: "Compare models under one contract",
      practiceBrief: "Evaluate a pruned tree, random forest, and gradient-boosted tree on the same fictional classification task.",
      steps: ["Freeze preprocessing, partitions, baseline, metrics, search budget, and random seeds before fitting.", "Compare validation distributions and holdout results with identical row and threshold rules.", "Record fit time, prediction time, model size, depth, estimator count, and failure cases.", "Stress-test importance rankings across seeds, correlated features, and permutation evaluation."],
      deliverable: "An ensemble comparison that makes predictive, stochastic, explanatory, and operational tradeoffs visible",
      reviewGate: "All candidates use the same evidence contract, repeated seeds expose variation, and importance is never labeled causal or stable without supporting tests.",
      checkpointQuestion: "Why repeat a random-forest fit with several recorded seeds?",
      checkpointOptions: ["To choose the seed with the highest holdout score", "To measure sensitivity of results and importance rankings to stochastic fitting", "To make the model causal", "To eliminate the need for a baseline"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Repeated recorded seeds reveal variation from stochastic training; selecting the best holdout seed would instead overfit the evaluation evidence.",
      takeaway: "Ensembles earn adoption only through controlled comparison across accuracy, stability, calibration, slices, complexity, and operational cost—not reputation.",
    },
    zhHans: {
      title: "树与集成",
      summary: "把剪枝树、bagging 森林与提升模型和简单基线比较，同时考虑随机性、复杂度、延迟与不稳定重要性。",
      objective: "在相同切分和指标下进行受控集成比较，并记录变异、资源成本、错误切片与解释限制。",
      artifact: "包含冻结切分、基线、模型卡、重复种子、复杂度延迟表、错误切片与重要性压力测试的集成比较",
      conceptHeading: "集成组合有差异的学习器",
      conceptParagraph: "决策树通过一系列分裂划分特征空间。Bagging 与随机森林在重抽样数据和特征子集上拟合不同树来降低相关性，boosting 则顺序增加学习器以改进指定目标。其收益必须在同一分区上与剪枝树、线性模型及决策相关基线比较。",
      boundaryHeading: "重要性与准确性仍是条件性的",
      boundaryParagraph: "基于不纯度的重要性可能偏好高基数或频繁分裂特征，置换重要性会随相关预测变量和评价数据变化，随机拟合也随种子变化。更强平均分数可能隐藏校准、子群、延迟、内存、可解释性或运营成本，因此不能把任何集成称为普遍最佳。",
      practiceTitle: "在一个合同下比较模型",
      practiceBrief: "在同一虚构分类任务上评价剪枝树、随机森林与梯度提升树。",
      steps: ["拟合前冻结预处理、分区、基线、指标、搜索预算与随机种子。", "用相同行和阈值规则比较验证分布与留出结果。", "记录拟合时间、预测时间、模型大小、深度、估计器数量与失败案例。", "跨种子、相关特征与置换评价压力测试重要性排序。"],
      deliverable: "一份让预测、随机、解释与运营取舍可见的集成比较",
      reviewGate: "所有候选使用同一证据合同，重复种子暴露变异，而且没有在缺乏支持测试时把重要性标为因果或稳定。",
      checkpointQuestion: "为什么要用多个已记录种子重复随机森林拟合？",
      checkpointOptions: ["选择留出分数最高的种子", "测量结果和重要性排序对随机拟合的敏感性", "使模型具有因果性", "取消基线需求"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "多个已记录种子揭示随机训练带来的变异；选择最佳留出种子反而会过拟合评价证据。",
      takeaway: "集成只能凭准确、稳定、校准、切片、复杂度与运营成本的受控比较赢得采用，而不能凭声誉。",
    },
  }),
  machineLearningModule({
    slug: "imbalanced-data-metrics",
    phaseId: "evaluation-and-decisions",
    minutes: 70,
    sourceIds: ["sklearn-metrics", "precision-recall-paper", "sklearn-pitfalls-cv"],
    en: {
      title: "Imbalanced data and metric selection",
      summary: "Start from prevalence, costs, capacity, and the confusion matrix; evaluate ranking, probabilities, thresholds, and subgroups without hiding denominators behind accuracy.",
      objective: "Create a metric contract and evaluation sheet that connects every reported number to a partition, denominator, threshold, confidence limit, and hypothetical decision consequence.",
      artifact: "Metric contract with prevalence, confusion matrices, ROC and PR views, probability metrics, capacity curves, subgroup counts, uncertainty, and decision-cost table",
      conceptHeading: "Metrics answer different questions",
      conceptParagraph: "Accuracy weights all correct labels equally, precision conditions on predicted positives, recall conditions on observed positives, specificity conditions on observed negatives, and ROC or precision-recall curves summarize rankings across thresholds. Probability scores such as log loss or Brier score address numerical probability quality rather than one thresholded classification.",
      boundaryHeading: "Class imbalance is a decision problem, not a resampling recipe",
      boundaryParagraph: "Precision changes with prevalence, a high recall can overwhelm review capacity, and class weighting or resampling changes the learning problem without inventing real information. Report counts and uncertainty, predefine the positive class, keep any resampling inside training folds, and select metrics from error harms and action constraints rather than whichever score looks best.",
      practiceTitle: "Write the metric before viewing candidates",
      practiceBrief: "Evaluate fictional support flags under a fixed review capacity without treating any flag as an intervention decision.",
      steps: ["Record positive-class meaning, prevalence, error harms, review capacity, and abstention or deferral path.", "Compute the baseline and confusion-matrix quantities with raw counts and denominators.", "Compare ROC, precision-recall, and probability metrics with uncertainty on validation data.", "Show capacity and subgroup slices, then state which metric can and cannot answer the hypothetical decision question."],
      deliverable: "A metric sheet that lets a reviewer reconstruct every denominator and see why no single score authorizes action",
      reviewGate: "Counts, prevalence, partitions, thresholds, uncertainty, and capacity are visible, and any training resampling never touches validation or holdout rows.",
      checkpointQuestion: "Why can precision change when a model moves to a population with different prevalence?",
      checkpointOptions: ["Precision ignores predictions", "Its denominator is predicted positives, whose true/false composition depends on prevalence", "ROC curves force precision to be constant", "Scaling always changes labels"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Even with similar conditional error behavior, a different base rate changes the mixture of true and false positives among flagged cases.",
      takeaway: "Metric choice must follow prevalence, harms, capacity, thresholds, and denominators; class imbalance cannot be solved by reporting a fashionable score.",
    },
    zhHans: {
      title: "不平衡数据与指标合同",
      summary: "从基率、成本、容量与混淆矩阵出发，评价排序、概率、阈值与子群，不用准确率隐藏分母。",
      objective: "建立指标合同与评价表，把每个数字连接到分区、分母、阈值、置信限制与假想决策后果。",
      artifact: "包含基率、混淆矩阵、ROC 与 PR 视图、概率指标、容量曲线、子群数量、不确定性与决策成本表的指标合同",
      conceptHeading: "不同指标回答不同问题",
      conceptParagraph: "准确率同等计算所有正确标签，精确率以预测阳性为条件，召回率以观测阳性为条件，特异度以观测阴性为条件，ROC 或精确率-召回率曲线则汇总跨阈值排序。对数损失或 Brier 分数等概率指标回答数值概率质量，而不是某一个阈值分类。",
      boundaryHeading: "类别不平衡是决策问题，不是重抽样配方",
      boundaryParagraph: "精确率会随基率变化，高召回可能压垮审查容量，类别权重或重抽样会改变学习问题，却不会创造真实信息。应报告数量与不确定性，预定义阳性类，把任何重抽样限制在训练折，并依据错误危害与行动约束选择指标。",
      practiceTitle: "查看候选前先写指标",
      practiceBrief: "在固定审查容量下评价虚构支持标记，同时不把任何标记当作干预决定。",
      steps: ["记录阳性类含义、基率、错误危害、审查容量与弃权或转交路径。", "用原始数量和分母计算基线与混淆矩阵各量。", "在验证数据上比较带不确定性的 ROC、PR 与概率指标。", "展示容量与子群切片，并说明哪些指标能或不能回答假想决策问题。"],
      deliverable: "一份让审查者可重建每个分母并看到为何单一分数不授权行动的指标表",
      reviewGate: "数量、基率、分区、阈值、不确定性与容量可见，任何训练重抽样也从未触及验证或留出行。",
      checkpointQuestion: "为什么模型迁移到不同基率总体时精确率可能变化？",
      checkpointOptions: ["精确率忽略预测", "其分母是预测阳性，而其中真阳性与假阳性的构成取决于基率", "ROC 曲线强制精确率恒定", "缩放总会改变标签"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "即使条件错误行为相似，不同基率也会改变被标记案例中真阳性与假阳性的混合。",
      takeaway: "指标选择必须服从基率、危害、容量、阈值与分母；类别不平衡不能靠报告流行分数解决。",
    },
  }),
  machineLearningModule({
    slug: "calibration-thresholds-error-analysis",
    phaseId: "evaluation-and-decisions",
    minutes: 70,
    sourceIds: ["sklearn-calibration-threshold", "calibration-paper", "sklearn-metrics", "sklearn-pitfalls-cv"],
    en: {
      title: "Calibration, thresholds and error analysis",
      summary: "Evaluate whether probabilities match observed frequencies, tune a hypothetical threshold on separate data, and turn errors into a blinded taxonomy rather than anecdotes.",
      objective: "Produce a calibration and threshold review with reliability evidence, separated tuning and testing, capacity tradeoffs, and a reproducible error-analysis sample.",
      artifact: "Threshold review with calibration plot and scores, tuning-only utility table, frozen threshold, holdout result, blinded error taxonomy, and human-authority boundary",
      conceptHeading: "Probability quality and action policy are separate",
      conceptParagraph: "Calibration asks whether events assigned similar probabilities occur at corresponding frequencies, while discrimination asks whether positives tend to rank above negatives. A threshold then implements an action rule under costs and capacity. Calibration methods themselves learn parameters and must be trained without using the final evaluation labels.",
      boundaryHeading: "Calibration and error review remain local evidence",
      boundaryParagraph: "A globally calibrated model can be miscalibrated for a subgroup or after shift, small reliability bins are uncertain, and tuning a threshold on holdout labels destroys the holdout's role. Error categories should be defined before reading explanations, sampled by a reproducible rule, reviewed blind to model identity when feasible, and connected to fixes that receive fresh evaluation.",
      practiceTitle: "Separate tuning from final evidence",
      practiceBrief: "Calibrate a fictional classifier and choose an illustrative review threshold without granting it real decision authority.",
      steps: ["Fit the base estimator on training data and calibration mapping on a permitted training or calibration partition.", "Report reliability bins, counts, Brier or log loss, and subgroup uncertainty on validation data.", "Choose a hypothetical threshold from validation-only costs and capacity, then freeze it.", "Evaluate once on holdout and code a fixed sample of false positives and false negatives using a predeclared taxonomy."],
      deliverable: "A threshold review that distinguishes probability evidence, policy tuning, final testing, error causes, and retained human authority",
      reviewGate: "Calibration and threshold selection never use holdout labels, sparse bins are identified, and error analysis follows a reproducible sample and taxonomy.",
      checkpointQuestion: "What does good probability calibration establish?",
      checkpointOptions: ["The model is accurate, fair, and useful at every threshold", "Within evaluated conditions, predicted probability levels align with observed frequencies to the reported resolution", "The highest score identifies a causal mechanism", "No subgroup or future shift needs evaluation"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Calibration is a bounded correspondence between probabilities and frequencies; it does not establish ranking, fairness, utility, or stability under shift.",
      takeaway: "Calibrate, tune, and test on separated evidence; a threshold encodes policy and capacity, so it must never inherit authority from a score alone.",
    },
    zhHans: {
      title: "校准、阈值与错误分析",
      summary: "评价概率是否匹配观测频率，在独立数据上调假想阈值，并把错误转成盲法分类而不是轶事。",
      objective: "产出校准与阈值审查，包含可靠性证据、分开的调参与测试、容量取舍与可复现错误分析样本。",
      artifact: "包含校准图和分数、仅调参效用表、冻结阈值、留出结果、盲法错误分类与人类权限边界的阈值审查",
      conceptHeading: "概率质量与行动政策是分开的",
      conceptParagraph: "校准询问被赋予相近概率的事件是否以相应频率发生，区分度则询问阳性是否通常排在阴性前。阈值随后在成本与容量下实现行动规则。校准方法本身也会学习参数，不能使用最终评价标签训练。",
      boundaryHeading: "校准与错误审查仍是局部证据",
      boundaryParagraph: "整体校准模型可能在子群或漂移后失准，小型可靠性分箱具有不确定性，用留出标签调阈值则会破坏留出作用。错误类别应在阅读解释前定义，以可复现规则抽样，在可行时对模型身份盲法审查，并把修复连接到全新评价。",
      practiceTitle: "分开调参与最终证据",
      practiceBrief: "校准虚构分类器并选择示例审查阈值，但不给它真实决策权。",
      steps: ["在训练数据拟合基础估计器，在获准的训练或校准分区拟合校准映射。", "在验证数据报告可靠性分箱、数量、Brier 或对数损失与子群不确定性。", "只依据验证集成本和容量选择假想阈值，然后冻结。", "在留出集评价一次，并按预声明分类编码固定抽样的假阳性和假阴性。"],
      deliverable: "一份区分概率证据、政策调参、最终测试、错误原因与保留人类权限的阈值审查",
      reviewGate: "校准和阈值选择从未使用留出标签，稀疏分箱已识别，错误分析也遵循可复现样本与分类。",
      checkpointQuestion: "良好概率校准能够证明什么？",
      checkpointOptions: ["模型在每个阈值都准确、公平且有用", "在受评条件与报告分辨率内，预测概率水平与观测频率一致", "最高分识别出因果机制", "无需评价任何子群或未来漂移"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "校准是概率与频率间有边界的对应关系；它不证明排序、公平、效用或漂移下稳定。",
      takeaway: "用分开的证据进行校准、调参与测试；阈值编码政策与容量，不能只从分数继承权威。",
    },
  }),
  machineLearningModule({
    slug: "clustering",
    phaseId: "unsupervised-and-recommendation",
    minutes: 65,
    sourceIds: ["sklearn-clustering", "dbscan-paper", "sklearn-preprocessing"],
    en: {
      title: "Clustering",
      summary: "Treat clusters as algorithm-dependent summaries, compare k-means and DBSCAN under explicit scaling and distance choices, and refuse human-type labels without external validation.",
      objective: "Run a stability and interpretation audit across algorithms, parameter ranges, feature sets, and resamples, then document what the partitions do and do not mean.",
      artifact: "Cluster audit with purpose, feature and scale contract, algorithm comparison, parameter sensitivity, stability matrix, exemplar review, and prohibited human-type claims",
      conceptHeading: "Clustering optimizes a chosen notion of similarity",
      conceptParagraph: "K-means seeks compact groups around centroids under squared Euclidean distance, while DBSCAN links density-reachable points and marks some observations as noise. Scaling, distance, feature selection, density parameters, sample composition, and initialization determine the geometry presented to the algorithm and therefore the resulting partition.",
      boundaryHeading: "A cluster label is not discovered ground truth",
      boundaryParagraph: "Internal scores reward particular geometric properties and can disagree with downstream usefulness. Naming a cluster after inspecting averages can reify a fragile pattern, especially for people. The course uses fictional records, neutral cluster identifiers, resampling stability, external task checks, and a prohibition on profiling or allocating support from cluster membership.",
      practiceTitle: "Pressure-test an unsupervised partition",
      practiceBrief: "Compare k-means and DBSCAN on selected fictional behavioral features without claiming learner types.",
      steps: ["State the analytic purpose, excluded identifiers, feature units, scaling, distance, and reasons before fitting.", "Sweep a bounded parameter grid for k-means and DBSCAN without selecting on a preferred narrative.", "Measure assignment stability across bootstrap samples and feature perturbations.", "Review exemplars and distributions, keep neutral IDs, and list decisions that cluster membership cannot support."],
      deliverable: "A cluster audit that shows sensitivity and limited descriptive use without converting partitions into identities",
      reviewGate: "Results include multiple algorithms and perturbations, neutral labels, visible unstable assignments, and no automated or human-targeting action from cluster membership.",
      checkpointQuestion: "What most directly determines DBSCAN's notion of a cluster?",
      checkpointOptions: ["A causal label supplied after fitting", "The distance metric, neighborhood radius, minimum samples, scaling, and observed density", "The test-set class accuracy", "A default probability threshold of 0.5"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "DBSCAN builds density reachability from the metric, radius, minimum-neighbor rule, scale, and sample; those choices define the partition.",
      takeaway: "Clusters are sensitivity-tested summaries under chosen geometry, not discovered learner identities or authorization for differentiated treatment.",
    },
    zhHans: {
      title: "聚类",
      summary: "把聚类视为依赖算法的汇总，在显式缩放与距离选择下比较 k-means 和 DBSCAN，并在缺乏外部验证时拒绝人群类型标签。",
      objective: "跨算法、参数范围、特征集合与重抽样进行稳定性和解释审计，再记录划分的含义与非含义。",
      artifact: "包含目的、特征尺度合同、算法比较、参数敏感性、稳定性矩阵、样例审查与禁止人群类型声明的聚类审计",
      conceptHeading: "聚类优化所选择的相似性概念",
      conceptParagraph: "K-means 在平方欧氏距离下寻找围绕质心的紧凑群组，DBSCAN 则连接密度可达点并把部分观察标为噪声。缩放、距离、特征选择、密度参数、样本构成与初始化共同决定呈现给算法的几何，因此决定最终划分。",
      boundaryHeading: "聚类标签不是被发现的真实标签",
      boundaryParagraph: "内部指标奖励特定几何性质，可能与下游用途不一致。检查均值后给群组命名会把脆弱模式实体化，尤其涉及人时。本课只用虚构记录、中性群组编号、重抽样稳定性与外部任务检查，并禁止依据群组成员资格画像或分配支持。",
      practiceTitle: "压力测试无监督划分",
      practiceBrief: "在选定虚构行为特征上比较 k-means 与 DBSCAN，但不宣称学习者类型。",
      steps: ["拟合前说明分析目的、排除标识符、特征单位、缩放、距离与理由。", "对 k-means 与 DBSCAN 扫描有边界参数网格，不按偏好叙事选结果。", "跨 bootstrap 样本和特征扰动测量分配稳定性。", "审查样例与分布，保留中性编号，并列出群组成员资格不能支持的决定。"],
      deliverable: "一份展示敏感性与有限描述用途、但不把划分变成身份的聚类审计",
      reviewGate: "结果包含多个算法与扰动、中性标签、可见不稳定分配，而且没有依据群组成员资格采取自动或人类目标行动。",
      checkpointQuestion: "什么最直接决定 DBSCAN 的聚类概念？",
      checkpointOptions: ["拟合后提供的因果标签", "距离度量、邻域半径、最小样本数、缩放与观测密度", "测试集类别准确率", "默认 0.5 概率阈值"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "DBSCAN 从度量、半径、最小邻居规则、尺度与样本构建密度可达关系；这些选择定义划分。",
      takeaway: "聚类是在选定几何下经敏感性测试的汇总，不是被发现的学习者身份，也不授权差异化对待。",
    },
  }),
  machineLearningModule({
    slug: "anomaly-detection",
    phaseId: "unsupervised-and-recommendation",
    minutes: 70,
    sourceIds: ["sklearn-outlier", "isolation-forest-paper", "sklearn-preprocessing"],
    en: {
      title: "Anomaly detection",
      summary: "Define unusual relative to a reference distribution, distinguish outlier from novelty settings, and route scores to bounded human review rather than declaring error, fraud, or harm.",
      objective: "Build an anomaly-review experiment with clean reference data, contamination sensitivity, synthetic injected cases, capacity limits, and documented reviewer outcomes.",
      artifact: "Anomaly review with reference-population contract, score-direction checks, contamination sweep, injected-case evaluation, review queue, disposition taxonomy, and no-accusation boundary",
      conceptHeading: "Anomaly scores are relative to a fitted reference",
      conceptParagraph: "Outlier detection assumes training data may contain unusual observations, while novelty detection fits a reference of normal observations and scores new cases. Isolation Forest isolates observations through randomized partition paths; other estimators use local density, support boundaries, or covariance. Score orientation and decision functions differ by implementation and must be tested.",
      boundaryHeading: "Unusual is not synonymous with wrong or harmful",
      boundaryParagraph: "A rare but valid record, data-entry error, new subgroup, distribution shift, or adversarial case can all receive an extreme score. Contamination parameters encode an expected flag rate rather than discovering a true prevalence. Any queue needs capacity, human evidence access, non-punitive disposition categories, appeal, and monitoring for disparate false flags.",
      practiceTitle: "Design a bounded anomaly queue",
      practiceBrief: "Inject transparent fictional data errors and rare valid cases, then test whether an Isolation Forest separates them without making accusations.",
      steps: ["Define the reference period, unit, features, scaling, known clean/uncertain status, and novelty versus outlier setting.", "Verify score direction and sweep contamination or thresholds without using holdout dispositions for tuning.", "Evaluate injected errors, rare valid cases, review workload, and false-flag uncertainty.", "Create reviewer dispositions such as valid-rare, data-error, distribution-shift, unresolved, and no-action, with an appeal path."],
      deliverable: "An anomaly-review package that treats a score as triage evidence and preserves human investigation and no-action outcomes",
      reviewGate: "Every flag retains its raw evidence and uncertainty, review capacity is explicit, and no score is labeled fraud, misconduct, or need without independent evidence.",
      checkpointQuestion: "What does the contamination parameter most directly encode in many anomaly estimators?",
      checkpointOptions: ["A proven rate of harmful people", "An assumed or targeted proportion used to set the decision boundary", "A causal effect of each feature", "A guarantee that every flagged record is wrong"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Contamination helps determine a cutoff or expected proportion; it does not reveal a true harm or error prevalence by itself.",
      takeaway: "Anomaly scores prioritize bounded review against a reference distribution; they never prove wrongdoing, need, or harmfulness on their own.",
    },
    zhHans: {
      title: "异常与新颖性检测",
      summary: "相对参考分布定义异常，区分异常值与新颖性场景，并把分数送往有边界人类审查，而不是宣称错误、欺诈或危害。",
      objective: "建立异常审查实验，包含干净参考数据、contamination 敏感性、合成注入案例、容量限制与已记录审查结果。",
      artifact: "包含参考总体合同、分数方向检查、contamination 扫描、注入案例评价、审查队列、处置分类与禁止指控边界的异常审查",
      conceptHeading: "异常分数相对于拟合参考",
      conceptParagraph: "异常值检测假设训练数据可能包含异常观察，新颖性检测则拟合正常观察参考并给新案例评分。Isolation Forest 通过随机划分路径隔离观察；其他估计器使用局部密度、支持边界或协方差。不同实现的分数方向与决策函数不同，必须测试。",
      boundaryHeading: "罕见不等于错误或有害",
      boundaryParagraph: "罕见但有效记录、录入错误、新子群、分布漂移或对抗案例都可能得到极端分数。contamination 参数编码预期标记率，而不是发现真实发生率。任何队列都需要容量、人类证据访问、非惩罚性处置类别、申诉，以及差异化误标监控。",
      practiceTitle: "设计有边界异常队列",
      practiceBrief: "注入透明的虚构数据错误与罕见有效案例，测试 Isolation Forest 能否区分它们而不作指控。",
      steps: ["定义参考期、单元、特征、缩放、已知干净或不确定状态，以及新颖性或异常值设定。", "验证分数方向并扫描 contamination 或阈值，但不用留出处置结果调参。", "评价注入错误、罕见有效案例、审查工作量与误标不确定性。", "建立有效罕见、数据错误、分布漂移、未解决和不行动等处置，并提供申诉路径。"],
      deliverable: "一份把分数视为分诊证据，并保留人类调查与不行动结果的异常审查包",
      reviewGate: "每个标记保留原始证据与不确定性，审查容量明确，而且没有分数在缺乏独立证据时被标为欺诈、违规或需要。",
      checkpointQuestion: "许多异常估计器中的 contamination 参数最直接编码什么？",
      checkpointOptions: ["已证实的有害人群比例", "用于设置决策边界的假设或目标比例", "每个特征的因果效应", "每条被标记录都错误的保证"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "contamination 帮助确定截点或预期比例，本身不会揭示真实危害或错误发生率。",
      takeaway: "异常分数只用于相对参考分布安排有边界审查；它绝不能单独证明违规、需要或危害。",
    },
  }),
  machineLearningModule({
    slug: "recommender-systems",
    phaseId: "unsupervised-and-recommendation",
    minutes: 65,
    sourceIds: ["matrix-factorization-paper", "ncf-paper", "sklearn-metrics", "hidden-technical-debt"],
    en: {
      title: "Recommender systems",
      summary: "Compare popularity, matrix factorization, and neural collaborative filtering under temporal candidate sets while auditing exposure, cold start, feedback loops, and non-ranking outcomes.",
      objective: "Create a temporal offline recommender evaluation that uses honest candidate sets, strong baselines, user-level splits, coverage and novelty measures, and a no-personalization deployment boundary.",
      artifact: "Recommendation evaluation with interaction contract, temporal split, candidate policy, popularity and MF baselines, NCF comparison, ranking metrics, coverage, cold-start, and feedback-loop risk",
      conceptHeading: "Recommendation learns from selective interaction evidence",
      conceptParagraph: "Matrix factorization represents observed user-item interactions through latent factors, while NCF replaces or augments the interaction function with a neural architecture. Ranking evaluation asks whether held-out relevant items appear near the top among a defined candidate set. Popularity and regularized matrix-factorization baselines are essential because complex models can benefit from evaluation shortcuts.",
      boundaryHeading: "Clicks reflect exposure and policy, not pure preference",
      boundaryParagraph: "A missing interaction can mean no exposure rather than dislike; negative sampling changes the task; random interaction splits leak future behavior; and repeated recommendation creates feedback loops. Offline hit rate does not establish learning benefit, diversity, fairness, wellbeing, or online utility. The exercise therefore reports exposure limits and prohibits real personalization.",
      practiceTitle: "Audit a temporal ranking experiment",
      practiceBrief: "Use fictional interactions to compare popularity, matrix factorization, and an NCF-style candidate without contacting users or serving recommendations.",
      steps: ["Define users, items, events, exposure evidence, observation windows, candidate set, and relevance label.", "Split each fictional user's history temporally and prevent future items or interactions from entering training features.", "Compare popularity, matrix factorization, and NCF under identical candidates, seeds, and ranking cutoffs.", "Report hit or recall at k, coverage, popularity bias, cold-start exclusions, subgroup counts, and feedback-loop risks."],
      deliverable: "A recommender evaluation that exposes candidate construction, baselines, selective exposure, coverage, and non-claims alongside ranking metrics",
      reviewGate: "The same temporal split and candidate set apply to all models, popularity and MF baselines remain visible, and no offline metric is presented as permission to personalize.",
      checkpointQuestion: "Why is a popularity baseline required for a recommender experiment?",
      checkpointOptions: ["It guarantees fairness", "It tests whether a complex model adds value beyond a strong, simple pattern in selective interaction data", "It removes the need for a temporal split", "It converts clicks into causal preferences"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Popularity can be difficult to beat under common offline setups; a complex model must demonstrate value under the same candidates and split.",
      takeaway: "Recommender evidence is conditional on exposure, candidates, time, and baselines; offline ranking gains do not prove human benefit or authorize personalization.",
    },
    zhHans: {
      title: "推荐系统",
      summary: "在时间候选集下比较流行度、矩阵分解与神经协同过滤，同时审计曝光、冷启动、反馈环与非排序结果。",
      objective: "建立时间离线推荐评价，使用诚实候选集、强基线、用户级切分、覆盖与新颖性指标，以及不可部署个性化边界。",
      artifact: "包含交互合同、时间切分、候选政策、流行度与 MF 基线、NCF 比较、排序指标、覆盖、冷启动与反馈环风险的推荐评价",
      conceptHeading: "推荐从选择性互动证据中学习",
      conceptParagraph: "矩阵分解用潜在因子表示观测用户-项目互动，NCF 则用神经架构替换或增强互动函数。排序评价询问在已定义候选集中，被留出的相关项目是否出现在前列。流行度和正则化矩阵分解基线不可缺少，因为复杂模型可能从评价捷径获益。",
      boundaryHeading: "点击反映曝光与政策，而非纯偏好",
      boundaryParagraph: "缺失互动可能表示没有曝光，而非不喜欢；负采样会改变任务；随机互动切分会泄漏未来行为；重复推荐还会创造反馈环。离线命中率不能证明学习收益、多样性、公平、福祉或在线效用，因此本练习报告曝光限制并禁止真实个性化。",
      practiceTitle: "审计时间排序实验",
      practiceBrief: "用虚构互动比较流行度、矩阵分解与 NCF 风格候选，不联系用户，也不提供推荐。",
      steps: ["定义用户、项目、事件、曝光证据、观察窗口、候选集与相关性标签。", "按时间切分每位虚构用户的历史，防止未来项目或互动进入训练特征。", "在相同候选、种子与排序截点下比较流行度、矩阵分解与 NCF。", "报告 k 处命中或召回、覆盖、流行度偏差、冷启动排除、子群数量与反馈环风险。"],
      deliverable: "一份在排序指标之外暴露候选构造、基线、选择性曝光、覆盖与非声明的推荐评价",
      reviewGate: "所有模型使用同一时间切分与候选集，流行度和 MF 基线保持可见，也没有离线指标被表述为个性化许可。",
      checkpointQuestion: "为什么推荐实验必须包含流行度基线？",
      checkpointOptions: ["它保证公平", "它检验复杂模型是否在选择性互动数据中的强简单模式之外增加价值", "它取消时间切分需求", "它把点击转成因果偏好"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "在常见离线设定中，流行度很难被击败；复杂模型必须在同一候选与切分下证明价值。",
      takeaway: "推荐证据以曝光、候选、时间与基线为条件；离线排序提升不证明人类收益，也不授权个性化。",
    },
  }),
  machineLearningModule({
    slug: "leakage-reproducibility-model-card-capstone",
    phaseId: "capstone-assurance",
    minutes: 90,
    sourceIds: ["sklearn-pitfalls-cv", "model-cards-paper", "ml-test-score", "hidden-technical-debt", "nist-ai-rmf"],
    en: {
      title: "Leakage, reproducibility and model-card capstone",
      summary: "Package the complete predictive experiment into a reproducible, adversarially reviewed model card and explicit no-deploy decision with retained human authority.",
      objective: "Deliver eight capstone artifacts that prove split integrity, reproducible execution, baseline comparison, bounded evaluation, subgroup and error review, and a justified no-deploy conclusion.",
      artifact: "Eight-artifact student-support model assurance dossier with independent leakage challenge and signed no-deploy conditions",
      conceptHeading: "Assurance connects every claim to evidence and ownership",
      conceptParagraph: "A model card records intended use, users, evaluation conditions, metrics, limitations, and ethical considerations, while engineering readiness work adds data tests, dependency controls, reproducibility, monitoring assumptions, and ownership. The final dossier links each claim to a frozen input, split receipt, pipeline, test, evaluation table, error sample, reviewer, and expiry or recheck condition.",
      boundaryHeading: "Documentation is not deployment permission",
      boundaryParagraph: "The course fixture is entirely fictional and cannot demonstrate population validity, lawful processing, real subgroup performance, operational safety, or beneficial intervention. A model card can also be complete but inaccurate. The capstone must preserve independent review, appeals and override requirements, unresolved risks, and a no-deploy conclusion rather than simulating approval.",
      practiceTitle: "Run an adversarial release review",
      practiceBrief: "Rebuild the entire experiment from fixed local files, then ask a reviewer to try to invalidate the split, features, metrics, model card, and proposed claims.",
      steps: ["Verify fixture, schema, environment, partitions, pipeline, and output checksums in a clean offline run.", "Complete baseline, model comparison, calibration/threshold, subgroup, error, and ablation evidence without reusing holdout labels for design.", "Map every model-card claim to a file and ask an independent reviewer to inject one leakage or provenance failure.", "Record the failed or passed gates, residual risks, human authority, appeal requirements, and explicit conditions that prohibit deployment."],
      deliverable: "A complete eight-artifact assurance dossier whose evidence graph ends in a justified no-deploy decision rather than a simulated launch",
      reviewGate: "All artifacts are present and reproducible, the leakage challenge is documented, every claim has a source, unresolved risks remain visible, and no real-person use is authorized.",
      checkpointQuestion: "What does a complete model card prove by itself?",
      checkpointOptions: ["That the model is fair, safe, lawful, and ready to deploy", "Only that a reporting artifact exists; its claims and controls still require evidence and independent review", "That holdout labels may be reused for tuning", "That human authority and appeals are unnecessary"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "A model card organizes claims and evidence but cannot independently validate its own truth, coverage, controls, legality, or release decision.",
      takeaway: "Reproducible documentation supports review but never grants authority; this fictional capstone must end in an explicit no-deploy decision.",
    },
    zhHans: {
      title: "泄漏、可复现、模型卡与毕业保证",
      summary: "把完整预测实验打包为可复现、经对抗审查的模型卡，并作出保留人类权限的明确不可部署决定。",
      objective: "交付八项毕业产物，证明切分完整、执行可复现、基线已比较、评价有边界、子群与错误已审查，并合理得出不可部署结论。",
      artifact: "包含独立泄漏挑战与签署不可部署条件的八产物学生支持模型保证档案",
      conceptHeading: "保证把每项声明连接到证据与负责人",
      conceptParagraph: "模型卡记录预期用途、用户、评价条件、指标、限制与伦理考虑，工程准备工作还增加数据测试、依赖控制、可复现性、监控假设与负责人。最终档案把每项声明连接到冻结输入、切分收据、管线、测试、评价表、错误样本、审查者与到期或复核条件。",
      boundaryHeading: "文档不是部署许可",
      boundaryParagraph: "课程 fixture 完全虚构，不能证明总体有效性、合法处理、真实子群表现、运营安全或干预收益。模型卡也可能形式完整但内容错误。毕业项目必须保留独立审查、申诉与覆盖要求、未解决风险和不可部署结论，而不是模拟批准。",
      practiceTitle: "进行对抗式发布审查",
      practiceBrief: "从固定本地文件重建完整实验，再请审查者尝试推翻切分、特征、指标、模型卡与拟议声明。",
      steps: ["在全新离线运行中验证 fixture、schema、环境、分区、管线与输出校验和。", "完成基线、模型比较、校准/阈值、子群、错误与消融证据，不把留出标签再次用于设计。", "把每项模型卡声明映射到文件，并请独立审查者注入一个泄漏或来源故障。", "记录通过或失败门、残余风险、人类权限、申诉要求与明确禁止部署的条件。"],
      deliverable: "一份证据图最终导向合理不可部署决定、而非模拟上线的完整八产物保证档案",
      reviewGate: "全部产物齐全且可复现，泄漏挑战有记录，每项声明有来源，未解决风险保持可见，也没有授权任何真实人群使用。",
      checkpointQuestion: "一份完整模型卡本身能证明什么？",
      checkpointOptions: ["模型公平、安全、合法并可部署", "只能证明存在报告产物；其中声明与控制仍需证据和独立审查", "可以重复使用留出标签调参", "不再需要人类权限与申诉"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "模型卡组织声明与证据，但无法独立验证自身真实性、覆盖、控制、合法性或发布决定。",
      takeaway: "可复现文档支持审查但从不授予权限；这个虚构毕业项目必须以明确不可部署决定结束。",
    },
  }),
] as const;

export type MachineLearningModuleSlug =
  (typeof MACHINE_LEARNING_MODULES)[number]["slug"];
export type MachineLearningPhaseId =
  (typeof MACHINE_LEARNING_MODULES)[number]["phaseId"];
