import type { CourseKitSourceAuthoringSeed } from "../course-kit/authoring";
import {
  COURSE_KIT_SOURCE_SCHEMA_VERSION,
  type CourseKitNonEmpty,
  type CourseKitSourceRecord,
} from "../course-kit/types";

const ACCESSED_ON = "2026-08-26";

export const MACHINE_LEARNING_SOURCE_SEEDS = [
  {
    record: {
      id: "sklearn-pitfalls-cv",
      title: "scikit-learn common pitfalls, pipelines, and cross-validation",
      publisher: "scikit-learn project",
      url: "https://scikit-learn.org/stable/common_pitfalls.html",
      evidenceUrls: [
        "https://scikit-learn.org/stable/",
        "https://scikit-learn.org/stable/common_pitfalls.html",
        "https://scikit-learn.org/stable/modules/cross_validation.html",
        "https://scikit-learn.org/stable/modules/compose.html",
      ],
      accessedOn: ACCESSED_ON,
      revision: "scikit-learn 1.9.x documentation",
      kind: "official-documentation",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "BSD-3-Clause project licence; linked and paraphrased only",
      supports: "Train/test separation, cross-validation, pipelines, inconsistent preprocessing, data leakage, and controlling random state in current scikit-learn workflows.",
      boundary: "Random cross-validation is not valid for every temporal, grouped, repeated-measure, or distribution-shifted task; split logic must follow the prediction decision and available information.",
    },
    zhHans: {
      supports: "支持当前 scikit-learn 工作流中的训练/测试分离、交叉验证、管线、不一致预处理、数据泄漏与随机状态控制。",
      boundary: "随机交叉验证并不适合所有时间、群组、重复测量或分布漂移任务；切分逻辑必须服从预测决策与当时可用信息。",
    },
  },
  {
    record: {
      id: "sklearn-linear-models",
      title: "Linear Models",
      publisher: "scikit-learn project",
      url: "https://scikit-learn.org/stable/modules/linear_model.html",
      evidenceUrls: ["https://scikit-learn.org/stable/modules/linear_model.html"],
      accessedOn: ACCESSED_ON,
      revision: "scikit-learn 1.9.x documentation",
      kind: "official-documentation",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "BSD-3-Clause project licence; linked and paraphrased only",
      supports: "The current linear and logistic model implementations, objectives, penalties, multiclass behavior, and documented solver constraints.",
      boundary: "A predictive coefficient is not automatically a causal effect, a stable mechanism, or a fair explanation; interpretation depends on design, encoding, scale, collinearity, and regularization.",
    },
    zhHans: {
      supports: "支持当前线性与逻辑模型实现、目标函数、惩罚、多分类行为与求解器约束。",
      boundary: "预测系数不自动等于因果效应、稳定机制或公平解释；解释取决于设计、编码、尺度、共线性与正则化。",
    },
  },
  {
    record: {
      id: "sklearn-preprocessing",
      title: "Preprocessing data",
      publisher: "scikit-learn project",
      url: "https://scikit-learn.org/stable/modules/preprocessing.html",
      evidenceUrls: [
        "https://scikit-learn.org/stable/modules/preprocessing.html",
        "https://scikit-learn.org/stable/modules/compose.html",
      ],
      accessedOn: ACCESSED_ON,
      revision: "scikit-learn 1.9.x documentation",
      kind: "official-documentation",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "BSD-3-Clause project licence; linked and paraphrased only",
      supports: "Scaling, encoding, transformations, ColumnTransformer, and composing learned preprocessing with an estimator in a pipeline.",
      boundary: "Every learned transformation must be fit on training data only; scaling benefits depend on the estimator and does not correct invalid features, sampling, or target leakage.",
    },
    zhHans: {
      supports: "支持缩放、编码、转换、ColumnTransformer，以及在管线中组合学习型预处理与估计器。",
      boundary: "所有学习型转换只能在训练数据上拟合；缩放收益取决于估计器，也不会修复无效特征、抽样或目标泄漏。",
    },
  },
  {
    record: {
      id: "lasso-paper",
      title: "Regression Shrinkage and Selection via the Lasso",
      publisher: "Journal of the Royal Statistical Society: Series B",
      url: "https://doi.org/10.1111/j.2517-6161.1996.tb02080.x",
      evidenceUrls: ["https://doi.org/10.1111/j.2517-6161.1996.tb02080.x"],
      accessedOn: ACCESSED_ON,
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "The original LASSO formulation, L1-constrained coefficient shrinkage, and the paper's variable-selection motivation and experiments.",
      boundary: "The original results are study-bounded and do not guarantee stable variable selection, causal discovery, or superior prediction under collinearity, shift, or a new task.",
    },
    zhHans: {
      supports: "支持 LASSO 原始形式、L1 约束系数收缩，以及论文中的变量选择动机与实验。",
      boundary: "原始结果受研究条件限制，不保证在共线性、漂移或新任务下稳定选变量、发现因果或取得更好预测。",
    },
  },
  {
    record: {
      id: "sklearn-ensembles",
      title: "Ensemble methods",
      publisher: "scikit-learn project",
      url: "https://scikit-learn.org/stable/modules/ensemble.html",
      evidenceUrls: ["https://scikit-learn.org/stable/modules/ensemble.html"],
      accessedOn: ACCESSED_ON,
      revision: "scikit-learn 1.9.x documentation",
      kind: "official-documentation",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "BSD-3-Clause project licence; linked and paraphrased only",
      supports: "Current implementations and parameters for bagging, random forests, extremely randomized trees, AdaBoost, and gradient-boosted trees.",
      boundary: "More estimators or complexity do not guarantee better generalization, calibration, subgroup behavior, latency, interpretability, or superiority to a simple baseline.",
    },
    zhHans: {
      supports: "支持 bagging、随机森林、极端随机树、AdaBoost 与梯度提升树的当前实现和参数。",
      boundary: "更多估计器或复杂度不保证更好泛化、校准、子群表现、延迟、可解释性，也不保证胜过简单基线。",
    },
  },
  {
    record: {
      id: "random-forest-paper",
      title: "Random Forests",
      publisher: "Machine Learning",
      url: "https://doi.org/10.1023/A:1010933404324",
      evidenceUrls: ["https://doi.org/10.1023/A:1010933404324"],
      accessedOn: ACCESSED_ON,
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Breiman's random-forest construction, randomized tree ensembles, strength/correlation framing, and experiments reported in the original paper.",
      boundary: "The paper does not establish universal superiority, current-library defaults, causal feature meaning, reliable probability calibration, or safety for a new deployment population.",
    },
    zhHans: {
      supports: "支持 Breiman 的随机森林构造、随机化树集成、强度/相关性框架与原始论文实验。",
      boundary: "论文不证明普遍优越性、当前库默认值、因果特征含义、可靠概率校准或对新部署总体安全。",
    },
  },
  {
    record: {
      id: "sklearn-metrics",
      title: "Metrics and scoring: quantifying the quality of predictions",
      publisher: "scikit-learn project",
      url: "https://scikit-learn.org/stable/modules/model_evaluation.html",
      evidenceUrls: ["https://scikit-learn.org/stable/modules/model_evaluation.html"],
      accessedOn: ACCESSED_ON,
      revision: "scikit-learn 1.9.x documentation",
      kind: "official-documentation",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "BSD-3-Clause project licence; linked and paraphrased only",
      supports: "Current metric definitions, scorers, confusion-matrix quantities, ranking metrics, probabilistic metrics, and multi-output behavior.",
      boundary: "A metric is not a decision objective by itself; prevalence, error costs, abstention, capacity, subgroup impact, and time horizon determine whether it is relevant.",
    },
    zhHans: {
      supports: "支持当前指标定义、scorer、混淆矩阵量、排序指标、概率指标与多输出行为。",
      boundary: "指标本身不是决策目标；患病率或基率、错误成本、弃权、容量、子群影响与时间范围决定其是否相关。",
    },
  },
  {
    record: {
      id: "precision-recall-paper",
      title: "The Precision-Recall Plot Is More Informative than the ROC Plot When Evaluating Binary Classifiers on Imbalanced Datasets",
      publisher: "PLOS ONE",
      url: "https://doi.org/10.1371/journal.pone.0118432",
      evidenceUrls: ["https://doi.org/10.1371/journal.pone.0118432"],
      accessedOn: ACCESSED_ON,
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "licence-noted-no-copy",
      licence: "CC BY 4.0; this course uses an original synthesis and does not copy figures",
      supports: "A primary analysis of ROC and precision-recall visualization under class imbalance and the paper's stated informativeness result for its setting.",
      boundary: "Precision-recall is not automatically the single correct evaluation; its interpretation changes with prevalence and still requires an operating point, costs, and decision context.",
    },
    zhHans: {
      supports: "支持在类别不平衡条件下分析 ROC 与精确率-召回率图，以及论文在其设定中的信息性结论。",
      boundary: "精确率-召回率不自动成为唯一正确评价；它随基率变化，仍需操作点、成本与决策语境。",
    },
  },
  {
    record: {
      id: "sklearn-calibration-threshold",
      title: "Probability calibration and decision-threshold tuning",
      publisher: "scikit-learn project",
      url: "https://scikit-learn.org/stable/modules/calibration.html",
      evidenceUrls: [
        "https://scikit-learn.org/stable/modules/calibration.html",
        "https://scikit-learn.org/stable/modules/classification_threshold.html",
      ],
      accessedOn: ACCESSED_ON,
      revision: "scikit-learn 1.9.x documentation",
      kind: "official-documentation",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "BSD-3-Clause project licence; linked and paraphrased only",
      supports: "Reliability diagrams, calibration estimators, decision thresholds, and separating statistical probability estimation from the action rule.",
      boundary: "Calibration does not imply discrimination, accuracy, fairness, or utility, and a threshold tuned on evaluation labels contaminates the estimate unless tuning and final testing are separated.",
    },
    zhHans: {
      supports: "支持可靠性图、校准估计器、决策阈值，以及把概率估计与行动规则分开。",
      boundary: "校准不代表区分度、准确、公平或效用；若用评估标签调阈值而不另设最终测试，就会污染估计。",
    },
  },
  {
    record: {
      id: "calibration-paper",
      title: "On Calibration of Modern Neural Networks",
      publisher: "Proceedings of Machine Learning Research",
      url: "https://proceedings.mlr.press/v70/guo17a.html",
      evidenceUrls: ["https://proceedings.mlr.press/v70/guo17a.html"],
      accessedOn: ACCESSED_ON,
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "The paper's empirical calibration findings for modern neural networks and temperature scaling under its benchmark tasks and model families.",
      boundary: "The findings and temperature-scaling results are case-bounded and do not establish calibration for every estimator, subgroup, shift, metric, or future dataset.",
    },
    zhHans: {
      supports: "支持论文在其基准任务与模型族中关于现代神经网络校准和温度缩放的实证发现。",
      boundary: "这些发现受案例限制，不证明每个估计器、子群、漂移、指标或未来数据都已校准。",
    },
  },
  {
    record: {
      id: "sklearn-clustering",
      title: "Clustering",
      publisher: "scikit-learn project",
      url: "https://scikit-learn.org/stable/modules/clustering.html",
      evidenceUrls: ["https://scikit-learn.org/stable/modules/clustering.html"],
      accessedOn: ACCESSED_ON,
      revision: "scikit-learn 1.9.x documentation",
      kind: "official-documentation",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "BSD-3-Clause project licence; linked and paraphrased only",
      supports: "Current clustering algorithms, parameters, computational tradeoffs, and internal or external evaluation measures documented by scikit-learn.",
      boundary: "Cluster labels are algorithm-dependent partitions, not discovered human types or ground truth; distance, scaling, density, sample, and parameter choices shape the result.",
    },
    zhHans: {
      supports: "支持 scikit-learn 当前聚类算法、参数、计算取舍与内部或外部评价指标。",
      boundary: "聚类标签是依赖算法的划分，不是被发现的人类类型或真实标签；距离、缩放、密度、样本与参数都会塑造结果。",
    },
  },
  {
    record: {
      id: "dbscan-paper",
      title: "A Density-Based Algorithm for Discovering Clusters in Large Spatial Databases with Noise",
      publisher: "AAAI Press / KDD-96",
      url: "https://aaai.org/papers/kdd96-037-a-density-based-algorithm-for-discovering-clusters-in-large-spatial-databases-with-noise/",
      evidenceUrls: ["https://aaai.org/papers/kdd96-037-a-density-based-algorithm-for-discovering-clusters-in-large-spatial-databases-with-noise/"],
      accessedOn: ACCESSED_ON,
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "The original DBSCAN density-reachability construction, noise designation, parameterization, and experiments reported by the authors.",
      boundary: "DBSCAN's result is scale-, metric-, density-, sample-, and parameter-dependent; it does not establish natural or socially meaningful categories in a new dataset.",
    },
    zhHans: {
      supports: "支持 DBSCAN 原始密度可达构造、噪声标记、参数化与作者报告的实验。",
      boundary: "DBSCAN 结果依赖尺度、度量、密度、样本与参数；它不证明新数据中存在自然或社会上有意义的类别。",
    },
  },
  {
    record: {
      id: "sklearn-outlier",
      title: "Novelty and Outlier Detection",
      publisher: "scikit-learn project",
      url: "https://scikit-learn.org/stable/modules/outlier_detection.html",
      evidenceUrls: ["https://scikit-learn.org/stable/modules/outlier_detection.html"],
      accessedOn: ACCESSED_ON,
      revision: "scikit-learn 1.9.x documentation",
      kind: "official-documentation",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "BSD-3-Clause project licence; linked and paraphrased only",
      supports: "The documented distinction between outlier and novelty detection plus current estimators, score directions, contamination behavior, and evaluation cautions.",
      boundary: "An unusualness score is not proof of error, fraud, harm, or a person needing intervention; labels, review capacity, and downstream consequences require separate evidence.",
    },
    zhHans: {
      supports: "支持异常值检测与新颖性检测的区分，以及当前估计器、分数方向、contamination 行为与评价注意事项。",
      boundary: "异常分数不是错误、欺诈、危害或某人需要干预的证明；标签、审查能力与后果需要独立证据。",
    },
  },
  {
    record: {
      id: "isolation-forest-paper",
      title: "Isolation Forest",
      publisher: "IEEE International Conference on Data Mining",
      url: "https://doi.org/10.1109/ICDM.2008.17",
      evidenceUrls: ["https://doi.org/10.1109/ICDM.2008.17"],
      accessedOn: ACCESSED_ON,
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "The original isolation-based anomaly method, path-length rationale, computational framing, and experiments reported in the paper.",
      boundary: "The paper's benchmark results do not define anomalies for a new domain, select intervention thresholds, or establish that flagged records are erroneous or harmful.",
    },
    zhHans: {
      supports: "支持原始基于隔离的异常方法、路径长度原理、计算框架与论文实验。",
      boundary: "论文基准结果不能替新领域定义异常、选择干预阈值，也不能证明被标记记录错误或有害。",
    },
  },
  {
    record: {
      id: "matrix-factorization-paper",
      title: "Matrix Factorization Techniques for Recommender Systems",
      publisher: "IEEE Computer",
      url: "https://doi.org/10.1109/MC.2009.263",
      evidenceUrls: ["https://doi.org/10.1109/MC.2009.263"],
      accessedOn: ACCESSED_ON,
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Matrix-factorization recommender concepts, latent user/item factors, regularized optimization, implicit information, and the authors' application framing.",
      boundary: "Latent factors are not necessarily interpretable human traits, and offline rating prediction does not establish ranking utility, novelty, fairness, safety, or online benefit.",
    },
    zhHans: {
      supports: "支持矩阵分解推荐概念、潜在用户/项目因子、正则化优化、隐式信息与作者应用框架。",
      boundary: "潜在因子不一定是可解释的人类特质；离线评分预测也不能证明排序效用、新颖性、公平、安全或在线收益。",
    },
  },
  {
    record: {
      id: "ncf-paper",
      title: "Neural Collaborative Filtering",
      publisher: "arXiv primary manuscript",
      url: "https://arxiv.org/abs/1708.05031",
      evidenceUrls: ["https://arxiv.org/abs/1708.05031"],
      accessedOn: ACCESSED_ON,
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "The NCF architecture, implicit-feedback objective, negative sampling, and benchmark comparisons reported by the authors.",
      boundary: "The reported comparisons are tied to particular data, preprocessing, candidate sampling, metrics, and baselines; they do not prove universal superiority over popularity or matrix factorization.",
    },
    zhHans: {
      supports: "支持 NCF 架构、隐式反馈目标、负采样与作者报告的基准比较。",
      boundary: "报告比较依赖特定数据、预处理、候选采样、指标与基线，不能证明普遍胜过流行度或矩阵分解。",
    },
  },
  {
    record: {
      id: "model-cards-paper",
      title: "Model Cards for Model Reporting",
      publisher: "ACM Conference on Fairness, Accountability, and Transparency",
      url: "https://research.google/pubs/model-cards-for-model-reporting/",
      evidenceUrls: [
        "https://research.google/pubs/model-cards-for-model-reporting/",
        "https://doi.org/10.1145/3287560.3287596",
      ],
      accessedOn: ACCESSED_ON,
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "The original proposal for documenting intended use, evaluation conditions, performance, limitations, and ethical considerations in a model card.",
      boundary: "A completed card is a reporting artifact, not independent proof that tests are correct, coverage is sufficient, risks are controlled, or deployment is authorized.",
    },
    zhHans: {
      supports: "支持以模型卡记录预期用途、评价条件、性能、限制与伦理考虑的原始提议。",
      boundary: "完成卡片只是报告产物，不是测试正确、覆盖充分、风险受控或获准部署的独立证明。",
    },
  },
  {
    record: {
      id: "ml-test-score",
      title: "The ML Test Score: A Rubric for ML Production Readiness and Technical Debt Reduction",
      publisher: "Google Research",
      url: "https://research.google/pubs/the-ml-test-score-a-rubric-for-ml-production-readiness-and-technical-debt-reduction/",
      evidenceUrls: ["https://research.google/pubs/the-ml-test-score-a-rubric-for-ml-production-readiness-and-technical-debt-reduction/"],
      accessedOn: ACCESSED_ON,
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "An original engineering rubric for testing data, features, model behavior, infrastructure, and monitoring before production use.",
      boundary: "The rubric is an engineering heuristic, not a certification, legal approval, security guarantee, or substitute for context-specific risk and release review.",
    },
    zhHans: {
      supports: "支持在生产使用前测试数据、特征、模型行为、基础设施与监控的原始工程量规。",
      boundary: "该量规是工程启发式，不是认证、法律批准、安全保证，也不能替代情境化风险与发布审查。",
    },
  },
  {
    record: {
      id: "hidden-technical-debt",
      title: "Hidden Technical Debt in Machine Learning Systems",
      publisher: "Advances in Neural Information Processing Systems",
      url: "https://papers.nips.cc/paper/2015/hash/86df7dcfd896fcaf2674f757a2463eba-Abstract.html",
      evidenceUrls: ["https://papers.nips.cc/paper/2015/hash/86df7dcfd896fcaf2674f757a2463eba-Abstract.html"],
      accessedOn: ACCESSED_ON,
      kind: "research",
      stability: "stable-concept",
      reuseStatus: "link-and-paraphrase-only",
      supports: "Primary engineering analysis of ML-system debt including entanglement, hidden feedback loops, undeclared consumers, data dependencies, and configuration issues.",
      boundary: "The categories are design warnings, not a complete release checklist or empirical guarantee that a system without a listed smell is safe or maintainable.",
    },
    zhHans: {
      supports: "支持关于纠缠、隐藏反馈环、未声明使用者、数据依赖与配置问题等 ML 系统债务的原始工程分析。",
      boundary: "这些类别是设计警示，不是完整发布清单，也不保证没有所列气味的系统就安全或可维护。",
    },
  },
  {
    record: {
      id: "nist-ai-rmf",
      title: "Artificial Intelligence Risk Management Framework (AI RMF 1.0)",
      publisher: "National Institute of Standards and Technology",
      url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf",
      evidenceUrls: [
        "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf",
        "https://www.nist.gov/itl/ai-risk-management-framework",
      ],
      accessedOn: ACCESSED_ON,
      publishedOn: "2023-01-26",
      revision: "NIST AI 100-1",
      kind: "official-guidance",
      stability: "version-pinned",
      reuseStatus: "licence-noted-no-copy",
      licence: "United States government work boundary; third-party material may be separately protected",
      supports: "A voluntary framework for mapping, measuring, managing, and governing AI risks across actors and the lifecycle, including documented residual risk and accountability.",
      boundary: "AI RMF 1.0 is voluntary guidance, not deployment authorization, legal compliance, a complete local risk assessment, or evidence that model performance transfers to a real population.",
    },
    zhHans: {
      supports: "支持在角色与生命周期中映射、测量、管理和治理 AI 风险的自愿框架，包括记录残余风险与问责。",
      boundary: "AI RMF 1.0 是自愿指南，不是部署授权、法律合规、完整本地风险评估，也不证明模型性能可迁移到真实总体。",
    },
  },
] as const satisfies CourseKitNonEmpty<CourseKitSourceAuthoringSeed>;

export type MachineLearningSourceId =
  (typeof MACHINE_LEARNING_SOURCE_SEEDS)[number]["record"]["id"];

export const MACHINE_LEARNING_SOURCES = MACHINE_LEARNING_SOURCE_SEEDS.map(
  ({ record }) => ({ ...record, schemaVersion: COURSE_KIT_SOURCE_SCHEMA_VERSION }),
) as unknown as CourseKitNonEmpty<CourseKitSourceRecord<MachineLearningSourceId>>;

export function getMachineLearningSource(
  sourceId: MachineLearningSourceId,
): CourseKitSourceRecord<MachineLearningSourceId> {
  const source = MACHINE_LEARNING_SOURCES.find((candidate) => candidate.id === sourceId);
  if (!source) throw new Error(`Unknown Machine Learning source: ${sourceId}`);
  return source;
}
