import type {
  CourseKitModuleAuthoringSeed,
} from "../course-kit/authoring";
import type {
  CourseKitFourOptions,
  CourseKitNonEmpty,
  CourseKitOptionIndex,
} from "../course-kit/types";
import type { AiPythonDataSourceId } from "./sources";

interface AiPythonDataModuleText {
  readonly title: string;
  readonly summary: string;
  readonly objective: string;
  readonly artifact: string;
  readonly conceptHeading: string;
  readonly conceptParagraph: string;
  readonly boundaryHeading: string;
  readonly boundaryParagraph: string;
  readonly practiceTitle: string;
  readonly practiceBrief: string;
  readonly steps: CourseKitNonEmpty<string>;
  readonly deliverable: string;
  readonly reviewGate: string;
  readonly checkpointQuestion: string;
  readonly checkpointOptions: CourseKitFourOptions;
  readonly checkpointCorrectIndex: CourseKitOptionIndex;
  readonly checkpointExplanation: string;
  readonly takeaway: string;
}

function aiPythonDataModule<
  const Slug extends string,
  const PhaseId extends string,
  const SourceId extends AiPythonDataSourceId,
>(seed: {
  readonly slug: Slug;
  readonly phaseId: PhaseId;
  readonly minutes: number;
  readonly sourceIds: CourseKitNonEmpty<SourceId>;
  readonly en: AiPythonDataModuleText;
  readonly zhHans: AiPythonDataModuleText;
}): CourseKitModuleAuthoringSeed<Slug, PhaseId, SourceId> {
  const copy = (text: AiPythonDataModuleText) => ({
    title: text.title,
    summary: text.summary,
    objective: text.objective,
    artifact: text.artifact,
    sections: [
      {
        heading: text.conceptHeading,
        paragraphs: [text.conceptParagraph],
        sourceIds: seed.sourceIds,
        evidenceMode: "source-grounded" as const,
      },
      {
        heading: text.boundaryHeading,
        paragraphs: [text.boundaryParagraph],
        sourceIds: seed.sourceIds,
        evidenceMode: "instructional-synthesis" as const,
      },
    ] as const,
    practice: {
      title: text.practiceTitle,
      brief: text.practiceBrief,
      steps: text.steps,
      deliverable: text.deliverable,
      reviewGate: text.reviewGate,
    },
    checkpoint: {
      question: text.checkpointQuestion,
      options: text.checkpointOptions,
      correctIndex: text.checkpointCorrectIndex,
      explanation: text.checkpointExplanation,
    },
    takeaway: text.takeaway,
  });

  return {
    slug: seed.slug,
    phaseId: seed.phaseId,
    minutes: seed.minutes,
    sourceIds: seed.sourceIds,
    copy: { en: copy(seed.en), zhHans: copy(seed.zhHans) },
  };
}

export const AI_PYTHON_DATA_MODULES = [
  aiPythonDataModule({
    slug: "environment-notebooks-seeds-reproducibility",
    phaseId: "reproducible-foundations",
    minutes: 45,
    sourceIds: ["python-venv", "jupyter-docs", "notebook-reproducibility"],
    en: {
      title: "Environment, notebooks, seeds and reproducibility",
      summary: "Turn a notebook from an opaque result into a clean-run experiment with an environment receipt, ordered execution, fixed inputs, and recorded pseudorandom state.",
      objective: "Create a fresh environment, execute a notebook from top to bottom, and record enough context for another person to diagnose any mismatch.",
      artifact: "Clean-run environment receipt with dependency versions, input checksum, seed, execution order, and observed result",
      conceptHeading: "A notebook is a document plus a live execution history",
      conceptParagraph: "A saved notebook records cells, outputs, and execution metadata, while the kernel holds mutable state that may not be visible in the file. Reproducible work therefore begins with a disposable virtual environment, an explicit dependency list, fixed input files, an explicit random generator or seed where randomness is used, and a restart-and-run-all check.",
      boundaryHeading: "Reproducible is an evidence claim, not a magic switch",
      boundaryParagraph: "The same seed can still produce different low-level results when algorithms, package versions, hardware, parallel scheduling, or remote services change. A useful receipt states exactly what was controlled, what remained outside control, and whether the claim is exact equality, tolerance-bounded agreement, or merely the same analytic conclusion.",
      practiceTitle: "Prove a clean run",
      practiceBrief: "Use the course fixture to create a notebook whose result does not depend on an earlier hidden cell.",
      steps: ["Create a new virtual environment and record the Python and package versions.", "Compute and record the fixture checksum before loading it.", "Initialize pseudorandom work explicitly and execute all cells after a kernel restart.", "Record the command, final metric, tolerance, and any platform-dependent boundary."],
      deliverable: "A reproducibility receipt paired with a notebook that passes restart-and-run-all",
      reviewGate: "A reviewer can recreate the environment, identify the exact input, locate the seed, and distinguish exact from tolerance-based claims.",
      checkpointQuestion: "Which evidence best supports a claim that a notebook is reproducible?",
      checkpointOptions: ["It contains many rendered outputs", "It runs from a fresh kernel using recorded dependencies, inputs, commands, and random state", "Its author ran cells until the chart looked right", "It uses the newest package versions without recording them"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "A clean ordered run plus an environment and input receipt exposes hidden state and gives another person a testable reconstruction path.",
      takeaway: "Reproducibility requires a clean execution path and an explicit receipt; a seed or saved notebook alone is insufficient.",
    },
    zhHans: {
      title: "环境、notebook、随机种子与可复现性",
      summary: "用环境收据、顺序执行、固定输入与记录的伪随机状态，把不透明 notebook 结果改造成可全新运行的实验。",
      objective: "创建全新环境，自上而下执行 notebook，并记录足够上下文，使他人能够诊断任何不一致。",
      artifact: "包含依赖版本、输入校验和、随机种子、执行顺序与观测结果的全新运行环境收据",
      conceptHeading: "Notebook 是文档与实时执行历史的组合",
      conceptParagraph: "已保存 notebook 记录单元、输出与执行元数据，而内核持有文件中可能看不见的可变状态。因此，可复现工作应从可丢弃虚拟环境、显式依赖清单、固定输入文件、显式随机生成器或种子，以及重启后全部运行检查开始。",
      boundaryHeading: "可复现是证据声明，不是一个神奇开关",
      boundaryParagraph: "当算法、包版本、硬件、并行调度或远程服务变化时，同一个种子仍可能产生不同底层结果。合格收据要说明控制了什么、什么仍在控制外，以及声明的是逐值相等、容差内一致，还是仅分析结论相同。",
      practiceTitle: "证明全新运行",
      practiceBrief: "使用课程 fixture 建立不依赖早先隐藏单元状态的 notebook。",
      steps: ["创建新虚拟环境并记录 Python 与包版本。", "加载前计算并记录 fixture 校验和。", "显式初始化伪随机工作，在重启内核后执行全部单元。", "记录命令、最终指标、容差与任何平台相关边界。"],
      deliverable: "一份可复现收据，以及通过重启后全部运行检查的 notebook",
      reviewGate: "审查者能够重建环境、识别精确输入、找到种子，并区分精确声明与容差声明。",
      checkpointQuestion: "哪项证据最能支持 notebook 可复现的声明？",
      checkpointOptions: ["其中包含很多已渲染输出", "它使用已记录的依赖、输入、命令和随机状态从全新内核运行", "作者不断运行单元直到图表看起来正确", "它使用最新包版本但不记录版本"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "全新顺序运行加上环境与输入收据，会暴露隐藏状态，并给他人一条可测试的重建路径。",
      takeaway: "可复现需要全新执行路径与显式收据；只有种子或已保存 notebook 并不足够。",
    },
  }),
  aiPythonDataModule({
    slug: "execution-values-functions-state",
    phaseId: "reproducible-foundations",
    minutes: 50,
    sourceIds: ["python-docs"],
    en: {
      title: "Execution, values, functions and state",
      summary: "Trace how names bind to values, isolate transformations in functions, and make mutation and side effects visible before data work grows complicated.",
      objective: "Refactor a stateful sequence into small functions with explicit inputs, returned outputs, documented assumptions, and observable side effects.",
      artifact: "Function notebook with a state trace, explicit interfaces, assertions, and one deliberately isolated side effect",
      conceptHeading: "Names, objects, calls, and returns form the execution model",
      conceptParagraph: "Python evaluates expressions to values, binds names to objects, and executes function bodies when called. A function becomes easier to test when its inputs are arguments, its useful result is returned rather than hidden in a global, and file or display effects occur at a narrow boundary instead of being mixed into every transformation.",
      boundaryHeading: "Readable code still needs explicit data contracts",
      boundaryParagraph: "A short function is not automatically pure or correct: mutable objects can change through aliases, default arguments can retain state when misused, and external files or clocks can make results context-dependent. Record accepted types, units, missing-value policy, and failure behavior rather than relying on a suggestive function name.",
      practiceTitle: "Make state visible",
      practiceBrief: "Refactor a notebook cell that loads, transforms, summarizes, and writes data into a small pipeline.",
      steps: ["Annotate every name before and after the original cell executes.", "Separate loading, transformation, summary, and output into functions with explicit arguments.", "Return values instead of mutating a global table.", "Add assertions for units, row counts, and the one permitted output path."],
      deliverable: "A function notebook whose data flow and one side-effect boundary are visible without reading hidden state",
      reviewGate: "Each transformation can be called twice with the same input without accumulating hidden changes, and the output-writing step is isolated.",
      checkpointQuestion: "Which refactor most improves the testability of a data transformation?",
      checkpointOptions: ["Read and rewrite a global DataFrame inside every helper", "Accept the table as an argument, return a new result, and isolate file output", "Store intermediate values only in notebook display output", "Catch every exception and return an empty table"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Explicit inputs and returned outputs make the transformation callable and comparable, while isolating file output exposes the side effect.",
      takeaway: "Explicit inputs, returned values, and narrow side-effect boundaries make Python data flow reviewable and testable.",
    },
    zhHans: {
      title: "执行、值、函数与状态",
      summary: "追踪名称如何绑定到值，把转换隔离进函数，并在数据工作变复杂前让修改与副作用可见。",
      objective: "把有状态执行序列重构为小函数，具有显式输入、返回输出、已记录假设与可观察副作用。",
      artifact: "包含状态轨迹、显式接口、断言与一个刻意隔离副作用的函数 notebook",
      conceptHeading: "名称、对象、调用与返回构成执行模型",
      conceptParagraph: "Python 把表达式求值为值，将名称绑定到对象，并在调用时执行函数体。当输入通过参数传入、有用结果通过返回值输出而不是藏在全局变量中，文件或显示副作用又被限制在窄边界时，函数更容易测试。",
      boundaryHeading: "可读代码仍需要显式数据合同",
      boundaryParagraph: "短函数不自动等于纯函数或正确函数：可变对象可能通过别名改变，默认参数可能错误保留状态，外部文件或时钟也会使结果依赖上下文。应记录接受的类型、单位、缺失值政策与失败行为，而不是依赖好听的函数名。",
      practiceTitle: "让状态可见",
      practiceBrief: "把同时加载、转换、汇总和写出数据的 notebook 单元重构为小型管线。",
      steps: ["标注原单元执行前后每个名称的状态。", "把加载、转换、汇总与输出分为具有显式参数的函数。", "返回值而不是修改全局表。", "为单位、行数和唯一允许的输出路径增加断言。"],
      deliverable: "一份无需读取隐藏状态即可看清数据流与单一副作用边界的函数 notebook",
      reviewGate: "每个转换在同一输入下调用两次不会累积隐藏变化，写出步骤也已隔离。",
      checkpointQuestion: "哪种重构最能提高数据转换的可测试性？",
      checkpointOptions: ["在每个辅助函数中读取并重写全局 DataFrame", "把表作为参数传入、返回新结果，并隔离文件输出", "只在 notebook 显示输出中存储中间值", "捕获所有异常并返回空表"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "显式输入和返回输出让转换可调用、可比较，而隔离文件输出会暴露副作用。",
      takeaway: "显式输入、返回值与狭窄副作用边界，使 Python 数据流可审查、可测试。",
    },
  }),
  aiPythonDataModule({
    slug: "tests-errors-types-debugging",
    phaseId: "reproducible-foundations",
    minutes: 55,
    sourceIds: ["python-docs", "pytest-docs", "typing-spec"],
    en: {
      title: "Tests, errors, types and debugging",
      summary: "Convert assumptions into assertions, preserve useful failure information, and debug from the smallest reproducible input instead of suppressing exceptions.",
      objective: "Specify an interface with type annotations, write focused happy-path and failure-path tests, and reduce a failing dataset to a diagnostic example.",
      artifact: "Test and debugging log containing typed interfaces, passing assertions, one expected failure, and a minimized reproducer",
      conceptHeading: "A useful failure narrows the search",
      conceptParagraph: "Exceptions communicate that an operation could not honor its contract, while tests preserve examples of what the contract means. Type annotations make interface expectations inspectable before execution; runtime validation checks actual values; and a minimized failing example helps separate the defect from irrelevant rows, cells, or environment state.",
      boundaryHeading: "Green checks cover only what was expressed",
      boundaryParagraph: "Static types do not validate runtime values by default, and tests cannot protect assumptions that were never encoded. Catching a broad exception and returning an empty result destroys evidence. Preserve the exception type, relevant input shape, deterministic reproduction command, and expected versus observed behavior without exposing sensitive data.",
      practiceTitle: "Build a diagnostic ladder",
      practiceBrief: "Introduce one malformed row into the synthetic fixture and turn the resulting failure into a permanent regression test.",
      steps: ["Annotate the transformation interface and state the accepted units and missing-value behavior.", "Write one normal-case assertion and one expected exception assertion.", "Reduce the failing input to the smallest row set that still fails.", "Record the reproduction command, root cause, fix, and regression-test identifier."],
      deliverable: "A test log that reproduces, explains, and guards one data-processing failure",
      reviewGate: "The test fails before the fix, passes after the fix, and would still reveal the defect if unrelated notebook cells were removed.",
      checkpointQuestion: "What does a passing test suite establish?",
      checkpointOptions: ["The entire program is correct for every possible input", "The encoded assertions passed in the tested environment and cases", "The data source is truthful and representative", "The type annotations performed complete runtime validation"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Tests provide bounded evidence about the cases and assertions that actually ran; broader correctness requires additional claims and evidence.",
      takeaway: "Preserve failures as evidence: explicit contracts, minimized reproducers, and regression tests are more useful than swallowed exceptions.",
    },
    zhHans: {
      title: "测试、错误、类型与调试",
      summary: "把假设转成断言，保留有用失败信息，并从最小可复现输入调试，而不是压制异常。",
      objective: "用类型注解说明接口，编写正常与失败路径的聚焦测试，并把失败数据集缩减为诊断案例。",
      artifact: "包含类型接口、通过断言、一个预期失败与最小复现器的测试和调试日志",
      conceptHeading: "有用的失败会缩小搜索范围",
      conceptParagraph: "异常说明操作无法履行合同，测试则保存合同含义的具体例子。类型注解让接口预期在执行前可检查，运行时验证检查实际值，而最小失败示例有助于把缺陷与无关行、单元或环境状态分离。",
      boundaryHeading: "绿色检查只覆盖被表达的内容",
      boundaryParagraph: "静态类型默认不验证运行时值，测试也无法保护从未编码的假设。捕获宽泛异常后返回空结果会销毁证据。应在不泄露敏感数据的前提下保留异常类型、相关输入形状、确定性复现命令以及预期与实际行为。",
      practiceTitle: "建立诊断阶梯",
      practiceBrief: "向合成 fixture 注入一条格式错误记录，并把失败转成永久回归测试。",
      steps: ["标注转换接口，并说明接受的单位与缺失值行为。", "编写一个正常案例断言和一个预期异常断言。", "把失败输入缩减到仍会失败的最小记录集合。", "记录复现命令、根因、修复与回归测试标识。"],
      deliverable: "一份能够复现、解释并防止某个数据处理故障回归的测试日志",
      reviewGate: "测试在修复前失败、修复后通过，而且删除无关 notebook 单元后仍能揭示该缺陷。",
      checkpointQuestion: "测试套件通过能够证明什么？",
      checkpointOptions: ["程序对所有可能输入都完全正确", "已编码断言在受测环境与案例中通过", "数据源真实且具有代表性", "类型注解完成了全部运行时验证"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "测试只对实际运行的案例与断言提供有边界的证据；更广泛的正确性需要额外声明与证据。",
      takeaway: "把失败保留为证据：显式合同、最小复现器与回归测试比吞掉异常更有价值。",
    },
  }),
  aiPythonDataModule({
    slug: "numpy-arrays-vectorisation",
    phaseId: "tabular-engineering",
    minutes: 55,
    sourceIds: ["numpy-arrays-random"],
    en: {
      title: "NumPy arrays and vectorisation",
      summary: "Reason about shape, dtype, axis, broadcasting, masks, and pseudorandom generators before replacing row loops with array operations.",
      objective: "Implement a vectorized calculation, state its shape and dtype contract, and prove it matches a small loop-based reference within a declared tolerance.",
      artifact: "Array lab with shape contracts, a vectorized implementation, a reference implementation, and tolerance-based equivalence checks",
      conceptHeading: "Shape and axis are part of the meaning",
      conceptParagraph: "An ndarray is a homogeneous, multidimensional container whose shape and dtype constrain operations. Vectorization applies compiled elementwise or reduction operations across an axis, while broadcasting compares trailing dimensions to expand compatible shapes without copying a conceptual grid into Python loops.",
      boundaryHeading: "Fast array code can be silently wrong",
      boundaryParagraph: "Broadcasting can produce a valid but unintended shape, integer dtypes can overflow, floating-point reductions can vary slightly, and masks can change denominators. State the expected shape before computation, select axes explicitly, compare against a tiny reference case, and use a defensible numerical tolerance instead of exact float equality.",
      practiceTitle: "Replace a loop with a checked vector operation",
      practiceBrief: "Compute cohort-normalized practice rates from a small numeric matrix without losing the meaning of rows and columns.",
      steps: ["Write the row, column, unit, shape, and dtype contract.", "Implement a transparent loop-based reference on four rows.", "Implement the vectorized calculation with explicit axes and masks.", "Compare shape, finite values, and numerical agreement using a stated tolerance."],
      deliverable: "A checked array lab showing semantic and numerical equivalence between reference and vectorized calculations",
      reviewGate: "Changing one dimension to an incompatible or unintended shape triggers a check instead of silently changing the result.",
      checkpointQuestion: "Before accepting a broadcasted result, what should be checked first?",
      checkpointOptions: ["Only whether the code ran faster", "Whether the resulting shape and axis semantics match the intended observations and variables", "Whether Python displayed no warning", "Whether every value is an integer"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Broadcasting can be syntactically valid while applying the wrong comparison; shape and axis meaning must be verified.",
      takeaway: "Vectorization is trustworthy only when shape, dtype, axis, masks, and numerical tolerance are explicit and tested.",
    },
    zhHans: {
      title: "NumPy 数组与向量化",
      summary: "在用数组运算替代逐行循环前，先推理形状、数据类型、轴、广播、掩码与伪随机生成器。",
      objective: "实现向量化计算，说明其形状与类型合同，并证明它在声明容差内匹配小型循环参考实现。",
      artifact: "包含形状合同、向量化实现、参考实现与容差等价检查的数组实验",
      conceptHeading: "形状与轴是含义的一部分",
      conceptParagraph: "ndarray 是同质多维容器，形状和数据类型会约束操作。向量化沿轴应用编译后的逐元素或归约操作，广播则比较尾部维度来扩展兼容形状，而无需在 Python 循环中复制概念网格。",
      boundaryHeading: "快速数组代码也可能静默出错",
      boundaryParagraph: "广播可能产生合法但非预期的形状，整数类型可能溢出，浮点归约可能有细小差异，掩码也可能改变分母。计算前应声明预期形状、显式选择轴、与微型参考案例比较，并采用合理数值容差而非浮点精确相等。",
      practiceTitle: "用受检向量运算替换循环",
      practiceBrief: "从小型数值矩阵计算队列标准化练习率，同时保留行列含义。",
      steps: ["写出行、列、单位、形状与数据类型合同。", "在四行数据上实现透明循环参考。", "使用显式轴与掩码实现向量化计算。", "用已声明容差比较形状、有限值与数值一致性。"],
      deliverable: "一份展示参考计算与向量化计算在语义和数值上等价的受检数组实验",
      reviewGate: "把某一维改成不兼容或非预期形状时，会触发检查而不是静默改变结果。",
      checkpointQuestion: "接受广播结果前，首先应检查什么？",
      checkpointOptions: ["只检查代码是否更快", "结果形状与轴语义是否匹配预期的观察和变量", "Python 是否没有显示警告", "每个值是否都是整数"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "广播在语法上可能合法，却执行了错误比较；必须核验形状与轴的含义。",
      takeaway: "只有明确并测试形状、类型、轴、掩码与数值容差，向量化才值得信任。",
    },
  }),
  aiPythonDataModule({
    slug: "pandas-tidy-tabular-data",
    phaseId: "tabular-engineering",
    minutes: 65,
    sourceIds: ["pandas-tabular", "tidy-data-paper", "ceds-v13"],
    en: {
      title: "Pandas and tidy tabular data",
      summary: "Define the observational unit, variable meanings, keys, dtypes, units, and table grain before filtering, grouping, reshaping, or aggregating.",
      objective: "Transform the synthetic fixture into a tidy analysis table with an explicit data dictionary, row-grain statement, and key checks.",
      artifact: "Tidy analysis table plus data dictionary, row-grain statement, key audit, and transformation receipt",
      conceptHeading: "Table shape follows the analytic unit",
      conceptParagraph: "For many analytic workflows, each variable belongs in a column, each observation in a row, and each observational unit in a table. pandas supplies labeled selection, reshaping, grouping, and aggregation, but the analyst must first decide what one row represents, which fields identify it, which units and categories each variable uses, and whether repeated measurements require a separate table.",
      boundaryHeading: "A tidy-looking table can still be semantically invalid",
      boundaryParagraph: "Column labels and dtypes do not prove that two sources use the same definition, reporting period, population, or unit. An education standard such as CEDS can help compare terms, but local collection rules and operational meanings still require a project-owned data dictionary and evidence from the actual data producer.",
      practiceTitle: "Declare the grain before reshaping",
      practiceBrief: "Reshape the course fixture into one learner-period row without mixing event-level and learner-level measures.",
      steps: ["State the observational unit and candidate key before loading the table.", "Create a data dictionary with definition, dtype, unit, allowed missingness, and source for every field.", "Reshape and aggregate only after assigning each column to a table grain.", "Assert key uniqueness, row count, units, and category levels after transformation."],
      deliverable: "A tidy table whose row grain, keys, variables, units, and transformation lineage are inspectable",
      reviewGate: "A reviewer can explain what one row means and trace every aggregated value to a declared source column and rule.",
      checkpointQuestion: "What should be decided before grouping a table?",
      checkpointOptions: ["The chart color palette", "The observational unit, key, variable definitions, and units", "The number of notebook headings", "Whether every column name is short"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Grouping changes table grain; without an explicit observational unit, key, definitions, and units, the result can mix incompatible quantities.",
      takeaway: "Tidy structure begins with a declared observational unit and data dictionary, not with a convenient pandas operation.",
    },
    zhHans: {
      title: "pandas 与整洁表格数据",
      summary: "在筛选、分组、变形或聚合前，先定义观察单元、变量含义、键、类型、单位与表粒度。",
      objective: "把合成 fixture 转换为整洁分析表，并附显式数据字典、行粒度声明与键检查。",
      artifact: "整洁分析表及其数据字典、行粒度声明、键审计与转换收据",
      conceptHeading: "表结构应服从分析单元",
      conceptParagraph: "对许多分析流程而言，每个变量占一列、每个观察占一行、每类观察单元占一张表。pandas 提供带标签的选择、变形、分组与聚合，但分析者必须先决定一行代表什么、哪些字段识别它、每个变量使用何种单位和类别，以及重复测量是否需要独立表。",
      boundaryHeading: "外观整洁的表仍可能语义无效",
      boundaryParagraph: "列标签和数据类型不能证明两个来源采用同一定义、报告期、总体或单位。CEDS 等教育标准可以帮助比较术语，但本地采集规则与运营含义仍需项目自有数据字典和实际数据生产者证据。",
      practiceTitle: "变形前声明粒度",
      practiceBrief: "把课程 fixture 重构为每学习者每周期一行，同时避免混合事件级和学习者级指标。",
      steps: ["加载表前声明观察单元与候选键。", "为每个字段建立包含定义、类型、单位、允许缺失与来源的数据字典。", "给每列分配表粒度后再进行变形和聚合。", "转换后断言键唯一性、行数、单位与类别水平。"],
      deliverable: "一张行粒度、键、变量、单位与转换血缘均可检查的整洁表",
      reviewGate: "审查者能解释一行代表什么，并把每个聚合值追溯到已声明来源列与规则。",
      checkpointQuestion: "对表进行分组前，应先决定什么？",
      checkpointOptions: ["图表颜色方案", "观察单元、键、变量定义与单位", "notebook 标题数量", "是否每个列名都很短"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "分组会改变表粒度；若没有显式观察单元、键、定义和单位，结果可能混合不可比数量。",
      takeaway: "整洁结构始于已声明的观察单元与数据字典，而不是某个方便的 pandas 操作。",
    },
  }),
  aiPythonDataModule({
    slug: "cleaning-missingness-validation-provenance",
    phaseId: "tabular-engineering",
    minutes: 65,
    sourceIds: ["pandas-missing", "frictionless-specs", "ceds-v13"],
    en: {
      title: "Cleaning, missingness, validation and provenance",
      summary: "Profile defects before changing them, distinguish kinds of absence, encode validation rules, and preserve a row-level cleaning ledger and source receipt.",
      objective: "Produce a deterministic cleaning function with pre/post validation, an explicit missingness policy, and a ledger that preserves every material change.",
      artifact: "Cleaning ledger with defect profile, missingness decisions, validation results, row-level changes, and source checksum",
      conceptHeading: "Cleaning is a sequence of reviewable decisions",
      conceptParagraph: "Missing markers, impossible ranges, duplicate keys, inconsistent categories, and unit conflicts require different responses. Profile the raw input first, preserve an immutable copy and checksum, define field-level constraints, then apply deterministic rules that record the affected records, old and new representations, reason, rule version, and reviewer rather than silently overwriting the evidence.",
      boundaryHeading: "Valid does not mean true, neutral, or representative",
      boundaryParagraph: "Dropping incomplete records can change the population, filling a value can understate uncertainty, and schema validation only checks encoded structure and constraints. Provenance must distinguish the original source, the project's synthetic or transformed resource, the transformation code, its licence, and claims that remain unverified.",
      practiceTitle: "Clean without erasing the trail",
      practiceBrief: "Resolve the intentional missing values and category inconsistency in the fixture using a declared policy.",
      steps: ["Hash and profile the untouched fixture, including missingness by field and cohort.", "Classify each absence as structural, not observed, not applicable, or unresolved when evidence permits.", "Apply deterministic rules while recording row identifiers, old and new values, reasons, and rule version.", "Run post-cleaning schema, key, range, and distribution checks and report unresolved issues."],
      deliverable: "A cleaning ledger that permits reconstruction of both the raw input and every material transformation decision",
      reviewGate: "No raw value is silently overwritten, each rule has a reason, and validation failures remain visible instead of being converted to empty output.",
      checkpointQuestion: "What should happen before missing values are dropped or filled?",
      checkpointOptions: ["Choose the fastest method", "Profile the pattern, state the meaning and consequence, preserve raw data, and record the decision", "Replace every absence with zero", "Delete the column name so the issue is less visible"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Missing-value handling changes the analytic population or distribution, so its meaning, evidence, and consequences must be reviewed and logged first.",
      takeaway: "Cleaning must preserve provenance and uncertainty; schema-valid output is not evidence that the underlying records are true or unbiased.",
    },
    zhHans: {
      title: "清洗、缺失性、验证与来源",
      summary: "修改前先剖析缺陷，区分不同缺失类型，编码验证规则，并保留行级清洗台账与来源收据。",
      objective: "产出确定性清洗函数，具有前后验证、显式缺失政策，以及保留每项重大修改的台账。",
      artifact: "包含缺陷概况、缺失决定、验证结果、行级修改与来源校验和的清洗台账",
      conceptHeading: "清洗是一系列可审查决定",
      conceptParagraph: "缺失标记、不可能范围、重复键、不一致类别与单位冲突需要不同处理。应先剖析原始输入，保留不可变副本和校验和，定义字段约束，再应用确定性规则，记录受影响记录、旧新表示、理由、规则版本与审查者，而不是静默覆盖证据。",
      boundaryHeading: "有效不等于真实、中性或具有代表性",
      boundaryParagraph: "删除不完整记录可能改变总体，填补值可能低估不确定性，模式验证也只检查已编码结构和约束。来源记录必须区分原始来源、项目的合成或转换资源、转换代码及其许可，并列出仍未核实的声明。",
      practiceTitle: "清洗但不抹去轨迹",
      practiceBrief: "使用已声明政策解决 fixture 中刻意设置的缺失值与类别不一致。",
      steps: ["对未改动 fixture 计算哈希并剖析，包括按字段和队列统计缺失。", "在证据允许时，把缺失分类为结构性、未观察、不适用或未解决。", "应用确定性规则，同时记录行标识、旧值、新值、理由与规则版本。", "执行清洗后模式、键、范围与分布检查，并报告未解决问题。"],
      deliverable: "一份可重建原始输入与每项重大转换决定的清洗台账",
      reviewGate: "没有原值被静默覆盖，每条规则都有理由，验证失败保持可见而不是被转为空输出。",
      checkpointQuestion: "删除或填补缺失值前应做什么？",
      checkpointOptions: ["选择最快的方法", "剖析模式、说明含义与后果、保留原始数据并记录决定", "把所有缺失替换为零", "删除列名以降低问题可见性"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "缺失值处理会改变分析总体或分布，因此必须先审查并记录其含义、证据与后果。",
      takeaway: "清洗必须保留来源和不确定性；通过模式验证的输出并不证明底层记录真实或无偏。",
    },
  }),
  aiPythonDataModule({
    slug: "descriptive-statistics-sampling-uncertainty",
    phaseId: "analysis-and-pipelines",
    minutes: 55,
    sourceIds: ["nist-statistics", "scipy-bootstrap", "numpy-arrays-random"],
    en: {
      title: "Descriptive statistics, sampling and uncertainty",
      summary: "Connect every summary to its population, sampling process, denominator, dependence structure, and uncertainty rather than treating an API result as inference.",
      objective: "Write a statistical note that reports distribution-aware summaries and a bootstrap interval while stating the target population and assumptions.",
      artifact: "Statistical note with population and sample definitions, descriptive table, bootstrap design, interval, assumptions, and non-claims",
      conceptHeading: "A statistic is computed from a sample under a design",
      conceptParagraph: "Counts, proportions, medians, means, spread, quantiles, and grouped summaries describe different features of observed data. Inference to a population requires a defensible relationship between the sample and target, while a bootstrap approximates sampling variability by resampling according to an explicit scheme and statistic.",
      boundaryHeading: "Precision cannot repair selection or dependence",
      boundaryParagraph: "A narrow interval can coexist with a biased sample, repeated observations from the same learner violate an independent-row assumption, and exploratory subgroup comparisons invite multiplicity. State the sampling unit, clustering or pairing, missingness, estimand, resampling unit, confidence level, and why the interval is or is not population-relevant.",
      practiceTitle: "Attach uncertainty to a bounded claim",
      practiceBrief: "Estimate the median study minutes in the synthetic fixture without pretending the fixture represents real learners.",
      steps: ["Define the observed records, target quantity, and explicit synthetic-data boundary.", "Report count, missingness, median, quartiles, and a distribution view before interval estimation.", "Choose the resampling unit and random generator, then compute a bootstrap interval.", "Write what the interval measures and three claims it cannot support."],
      deliverable: "A statistical note that keeps descriptive evidence, resampling assumptions, and population limits separate",
      reviewGate: "The note names the sampling unit and target quantity, reproduces the interval from a recorded random state, and does not generalize synthetic records to people.",
      checkpointQuestion: "What is required before interpreting a bootstrap confidence interval?",
      checkpointOptions: ["Only a large number of resamples", "A justified statistic, resampling unit, dependence assumption, sample-to-population relationship, and random-state receipt", "A normal-looking histogram", "Removal of every unusual observation"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Bootstrap computation is conditional on the sample, statistic, and resampling scheme; interpretation also needs a defensible population relationship.",
      takeaway: "Uncertainty quantification inherits the sample and design; more resamples do not cure biased selection or incorrect independence assumptions.",
    },
    zhHans: {
      title: "描述性统计、抽样与不确定性",
      summary: "把每项汇总连接到总体、抽样过程、分母、依赖结构与不确定性，而不是把 API 结果直接当作推断。",
      objective: "撰写统计说明，报告适合分布的汇总与 bootstrap 区间，同时说明目标总体和假设。",
      artifact: "包含总体与样本定义、描述表、自助法设计、区间、假设与非声明的统计说明",
      conceptHeading: "统计量是在某种设计下从样本计算的",
      conceptParagraph: "计数、比例、中位数、均值、离散度、分位数与分组汇总描述观测数据的不同特征。向总体推断需要样本与目标之间有合理关系，而 bootstrap 则依据显式重抽样方案与统计量，近似抽样变异。",
      boundaryHeading: "精确度无法修复选择偏差或依赖",
      boundaryParagraph: "窄区间可以与偏差样本并存，同一学习者的重复观察违反独立行假设，探索性子群比较也会带来多重性。应说明抽样单元、聚类或配对、缺失、估计目标、重抽样单元、置信水平，以及区间为何可以或不可以用于总体。",
      practiceTitle: "给有边界的声明附上不确定性",
      practiceBrief: "估计合成 fixture 的学习时长中位数，同时不假装它代表真实学习者。",
      steps: ["定义观测记录、目标量与明确的合成数据边界。", "估计区间前先报告数量、缺失、中位数、四分位数与分布视图。", "选择重抽样单元和随机生成器，再计算 bootstrap 区间。", "写明区间衡量什么，以及它不能支持的三项声明。"],
      deliverable: "一份把描述证据、重抽样假设与总体限制分开的统计说明",
      reviewGate: "说明写明抽样单元与目标量，能从记录的随机状态复现区间，也没有把合成记录推广到真实人群。",
      checkpointQuestion: "解释 bootstrap 置信区间前需要什么？",
      checkpointOptions: ["只需要大量重抽样", "合理统计量、重抽样单元、依赖假设、样本与总体关系，以及随机状态收据", "看起来正态的直方图", "删除每个异常观察"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Bootstrap 计算以样本、统计量和重抽样方案为条件；解释还需要合理的总体关系。",
      takeaway: "不确定性量化继承样本与设计；增加重抽样次数不能修复选择偏差或错误独立性假设。",
    },
  }),
  aiPythonDataModule({
    slug: "visualisation-honest-charts",
    phaseId: "analysis-and-pipelines",
    minutes: 50,
    sourceIds: ["matplotlib-quickstart", "nist-statistics"],
    en: {
      title: "Visualisation and honest charts",
      summary: "Design a chart as a claim with a visible denominator, scale, aggregation, uncertainty, missingness, comparison, and source—not as decoration.",
      objective: "Create an accessible original chart and a chart receipt that explains the analytic question, transformation, encoding, limitations, and alternative view.",
      artifact: "Accessible original chart with data receipt, denominator, uncertainty note, alt text, and a documented misleading alternative",
      conceptHeading: "Encoding choices determine what readers compare",
      conceptParagraph: "A chart maps data to position, length, color, shape, and facets within a coordinate system. Clear titles, axis labels, units, legends, annotations, and source notes help a reader reconstruct the comparison, while direct labels, color-independent cues, and descriptive alternative text keep the main finding available beyond vision or color perception.",
      boundaryHeading: "The plotting library does not enforce honesty",
      boundaryParagraph: "Truncated axes, unequal bins, dual axes, hidden denominators, omitted groups, inappropriate smoothing, and suppressed uncertainty can create a persuasive but false impression. Keep the raw-to-chart transformation inspectable, show missingness and sample size when relevant, and compare the chosen view with at least one plausible alternative.",
      practiceTitle: "Build and pressure-test a chart claim",
      practiceBrief: "Visualize completion status by cohort from the synthetic fixture and expose how denominator choice changes the story.",
      steps: ["Write the one-sentence question and define numerator, denominator, population, and exclusions.", "Create an original chart with labels, units, sample sizes, color-independent cues, and alt text.", "Produce a deliberately misleading variant by hiding one material design choice.", "Annotate the failure, restore the honest design, and attach the transformation and source receipt."],
      deliverable: "An accessible chart package that shows both the defensible visualization and a diagnosed misleading alternative",
      reviewGate: "A reviewer can recompute every plotted value, identify the denominator and exclusions, and understand the finding without relying on color alone.",
      checkpointQuestion: "Which chart practice most directly protects the comparison from a hidden denominator?",
      checkpointOptions: ["Use a more saturated color", "State and display the population, numerator, denominator, exclusions, and group counts", "Remove axis labels to reduce clutter", "Choose the chart with the largest visual difference"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Visible population, denominator, exclusions, and counts let a reader reconstruct the rate and detect selective comparisons.",
      takeaway: "An honest chart exposes its denominator, transformation, uncertainty, missingness, and accessible comparison; attractive rendering is not evidence.",
    },
    zhHans: {
      title: "可视化与诚实图表",
      summary: "把图表设计成具有可见分母、尺度、聚合、不确定性、缺失、比较与来源的声明，而不是装饰。",
      objective: "制作无障碍原创图表及图表收据，解释分析问题、转换、编码、限制与替代视图。",
      artifact: "包含数据收据、分母、不确定性说明、替代文本与已记录误导版本的无障碍原创图表",
      conceptHeading: "编码选择决定读者比较什么",
      conceptParagraph: "图表在坐标系统中把数据映射到位置、长度、颜色、形状与分面。清楚的标题、坐标标签、单位、图例、注释与来源说明帮助读者重建比较；直接标签、不依赖颜色的线索和描述性替代文本，使主要发现不局限于视觉或颜色感知。",
      boundaryHeading: "绘图库不会强制诚实",
      boundaryParagraph: "截断坐标轴、不等宽区间、双轴、隐藏分母、遗漏群组、不当平滑与压制不确定性，都可能制造有说服力但错误的印象。应让原始数据到图表的转换可检查，在相关时显示缺失与样本量，并把所选视图与至少一种合理替代方案比较。",
      practiceTitle: "建立并压力测试图表声明",
      practiceBrief: "用合成 fixture 按队列可视化完成状态，并暴露分母选择如何改变叙事。",
      steps: ["写出一句话问题，并定义分子、分母、总体与排除项。", "制作带标签、单位、样本量、不依赖颜色线索和替代文本的原创图。", "隐藏一项重大设计选择，制作一个刻意误导的版本。", "标注故障、恢复诚实设计，并附转换与来源收据。"],
      deliverable: "一份同时展示合理可视化与经诊断误导替代版的无障碍图表包",
      reviewGate: "审查者能够重算每个绘图值、识别分母与排除项，并在不只依赖颜色时理解发现。",
      checkpointQuestion: "哪项图表实践最直接防止隐藏分母造成误导比较？",
      checkpointOptions: ["使用更饱和颜色", "说明并显示总体、分子、分母、排除项与各组数量", "删除坐标标签以减少杂乱", "选择视觉差异最大的图"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "可见总体、分母、排除项与数量让读者能够重建比率并发现选择性比较。",
      takeaway: "诚实图表会暴露分母、转换、不确定性、缺失与无障碍比较；漂亮渲染本身不是证据。",
    },
  }),
  aiPythonDataModule({
    slug: "files-apis-joins-reproducible-pipelines",
    phaseId: "analysis-and-pipelines",
    minutes: 60,
    sourceIds: ["csvw-recommendation", "json-rfc8259", "http-rfc9110", "pandas-merge", "frictionless-specs"],
    en: {
      title: "Files, APIs, joins and reproducible pipelines",
      summary: "Treat every external resource and join as a versioned contract with status checks, schema checks, key cardinality, provenance, retries, and immutable outputs.",
      objective: "Build an idempotent local pipeline that reads fixed CSV/JSON inputs, validates their contracts, performs an audited join, and emits a checksummed package.",
      artifact: "Pipeline receipt with input URLs or paths, HTTP/file metadata, schemas, key audit, merge diagnostics, output checksum, and rerun command",
      conceptHeading: "Transport, representation, schema, and meaning are separate layers",
      conceptParagraph: "HTTP communicates request and response semantics, JSON and CSV describe representation syntax, schemas constrain fields, and pandas performs joins. A defensible pipeline checks each layer explicitly: response status and content type, byte checksum, parser behavior, required fields, key uniqueness or expected multiplicity, unmatched rows, output path, and transformation version.",
      boundaryHeading: "Successful parsing and joining do not prove semantic correctness",
      boundaryParagraph: "A 200 response can contain stale or partial data, valid JSON can violate a domain contract, and a many-to-many merge can multiply rows. pandas also matches null join keys to each other, unlike usual SQL behavior. Inspect nulls, use merge validation and indicators, reconcile counts, and never retry a side-effecting request merely because a transport attempt was ambiguous.",
      practiceTitle: "Build a rerunnable join pipeline",
      practiceBrief: "Join the synthetic CSV to a small local JSON lookup without network dependence or silent row multiplication.",
      steps: ["Record input paths, media types, versions, licences, and SHA-256 checksums.", "Validate CSV and JSON structure before constructing analysis objects.", "Audit nulls and key cardinality, then merge with validate and indicator enabled.", "Reconcile matched and unmatched counts, write to a new versioned path, hash the output, and rerun to verify stability."],
      deliverable: "A local pipeline package whose inputs, join behavior, output, and rerun result are independently auditable",
      reviewGate: "A duplicate or null key, missing field, changed checksum, or unmatched record causes a visible diagnostic instead of silent acceptance.",
      checkpointQuestion: "What does pandas merge validate check?",
      checkpointOptions: ["Whether join keys have the correct business meaning", "Whether observed key multiplicity matches the declared one-to-one or one-to-many contract", "Whether the source licence permits redistribution", "Whether all null keys should represent the same entity"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "The validate argument checks join cardinality. Meaning, rights, null semantics, and completeness require separate evidence and review.",
      takeaway: "A reproducible pipeline validates transport, bytes, schema, keys, join cardinality, lineage, and outputs separately; parsing success is not truth.",
    },
    zhHans: {
      title: "文件、API、连接与可复现管线",
      summary: "把每项外部资源和连接视为版本化合同，包含状态检查、模式检查、键基数、来源、重试与不可变输出。",
      objective: "建立幂等本地管线，读取固定 CSV/JSON 输入、验证合同、执行受审计连接并输出带校验和的数据包。",
      artifact: "包含输入 URL 或路径、HTTP/文件元数据、模式、键审计、连接诊断、输出校验和与重跑命令的管线收据",
      conceptHeading: "传输、表示、模式与含义是不同层",
      conceptParagraph: "HTTP 传达请求响应语义，JSON 与 CSV 描述表示语法，模式约束字段，pandas 执行连接。合理管线会分别检查响应状态与内容类型、字节校验和、解析行为、必需字段、键唯一性或预期多重性、未匹配行、输出路径与转换版本。",
      boundaryHeading: "成功解析和连接不证明语义正确",
      boundaryParagraph: "200 响应可能包含过期或不完整数据，合法 JSON 可能违反领域合同，多对多连接也可能成倍增加行数。pandas 还会相互匹配空键，这不同于通常 SQL 行为。应检查空值、使用 merge validate 与 indicator、核对数量，并且不能因传输结果不明确就盲目重试带副作用请求。",
      practiceTitle: "建立可重跑连接管线",
      practiceBrief: "把合成 CSV 与小型本地 JSON 查找表连接，不依赖网络，也不静默增加行。",
      steps: ["记录输入路径、媒体类型、版本、许可与 SHA-256 校验和。", "构造分析对象前验证 CSV 与 JSON 结构。", "审计空键和键基数，再启用 validate 与 indicator 执行连接。", "核对匹配和未匹配数量，写入新版本路径，对输出哈希，并重跑验证稳定性。"],
      deliverable: "一份输入、连接行为、输出与重跑结果均可独立审查的本地管线包",
      reviewGate: "重复或空键、缺失字段、校验和变化或未匹配记录会触发可见诊断，而不是静默接受。",
      checkpointQuestion: "pandas merge 的 validate 检查什么？",
      checkpointOptions: ["连接键的业务含义是否正确", "观测到的键多重性是否符合声明的一对一或一对多合同", "来源许可是否允许再分发", "所有空键是否应代表同一实体"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "validate 参数检查连接基数；含义、权利、空值语义与完整性需要独立证据和审查。",
      takeaway: "可复现管线要分别验证传输、字节、模式、键、连接基数、血缘与输出；解析成功不等于真实。",
    },
  }),
  aiPythonDataModule({
    slug: "education-data-audit-capstone",
    phaseId: "capstone-audit",
    minutes: 100,
    sourceIds: ["ceds-v13", "frictionless-specs", "notebook-reproducibility", "nist-statistics", "matplotlib-quickstart"],
    en: {
      title: "Education-data audit capstone",
      summary: "Assemble the environment, data contract, cleaning ledger, validation, statistics, visualization, and provenance into one reviewable no-deployment audit package.",
      objective: "Audit the fixed synthetic education fixture end to end and issue a bounded analysis memo that separates verified observations, assumptions, unresolved defects, and prohibited claims.",
      artifact: "Eight-part education-data audit dossier with an executable notebook and signed evidence-boundary attestation",
      conceptHeading: "An audit package connects claims to transformations and evidence",
      conceptParagraph: "A defensible dossier links each reported number or chart to the exact input checksum, schema, cleaning rule, tested transformation, statistical definition, and output file. The data dictionary names field meanings and units; the provenance manifest identifies authorship and licence; and the review memo lists what was observed, inferred under assumptions, left unresolved, and intentionally not claimed.",
      boundaryHeading: "Synthetic analysis is a skills assessment, not evidence about learners",
      boundaryParagraph: "The included records are original fictional data released for education, not a sample of any school or population. A complete dossier therefore cannot establish real-world effectiveness, disparity, causal impact, privacy compliance, or deployment readiness. Any use with real records requires separate authorization, data governance, sampling review, security controls, and domain oversight.",
      practiceTitle: "Issue an evidence-bounded audit",
      practiceBrief: "Run the full course workflow on the fixed fixture and make every material claim traceable to a file, check, or explicit assumption.",
      steps: ["Freeze the environment and verify every input checksum against provenance.", "Create the data dictionary, raw profile, missingness policy, cleaning ledger, and validation test report.", "Produce a bounded statistical note and accessible chart with reconstructable transformations.", "Package all eight required artifacts, list unresolved defects and non-claims, then verify a clean rerun before attesting."],
      deliverable: "A complete eight-artifact audit dossier that another reviewer can rerun without network access",
      reviewGate: "All eight artifacts are present, checksums and tests agree, every claim has a traceable computation, and the memo explicitly refuses real-world or deployment conclusions.",
      checkpointQuestion: "What can a complete audit of this synthetic fixture establish?",
      checkpointOptions: ["The effectiveness of a real student-support program", "That the submitted transformations and bounded claims are reproducible against the fixed fictional input", "That processing real learner data is legally authorized", "That the analysis is ready for automated deployment"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "The fixture can demonstrate an auditable workflow against fictional records, but it cannot supply population evidence, legal authorization, or deployment assurance.",
      takeaway: "A strong audit dossier proves traceability of a bounded workflow; it does not turn synthetic records into claims about real people or authorize deployment.",
    },
    zhHans: {
      title: "教育数据审计毕业项目",
      summary: "把环境、数据合同、清洗台账、验证、统计、可视化与来源整合成一份可审查、不可部署的审计包。",
      objective: "端到端审计固定合成教育 fixture，并提交有边界分析备忘录，分开已验证观察、假设、未解决缺陷与禁止声明。",
      artifact: "包含可执行 notebook 与证据边界签署声明的八部分教育数据审计档案",
      conceptHeading: "审计包把声明连接到转换与证据",
      conceptParagraph: "合理档案会把每个报告数字或图表连接到精确输入校验和、模式、清洗规则、受测转换、统计定义与输出文件。数据字典说明字段含义和单位，来源清单识别作者与许可，审查备忘录列出观测内容、在假设下推断内容、未解决内容与刻意不作的声明。",
      boundaryHeading: "合成数据分析是技能评估，不是关于学习者的证据",
      boundaryParagraph: "所含记录是为教学发布的原创虚构数据，不是任何学校或总体的样本。因此，完整档案也不能证明现实效果、差异、因果影响、隐私合规或部署准备度。任何真实记录使用都需要独立授权、数据治理、抽样审查、安全控制与领域监督。",
      practiceTitle: "发布有证据边界的审计",
      practiceBrief: "在固定 fixture 上运行完整课程流程，让每项重大声明可追溯到文件、检查或显式假设。",
      steps: ["冻结环境，并按 provenance 验证每个输入校验和。", "建立数据字典、原始概况、缺失政策、清洗台账与验证测试报告。", "制作有边界统计说明与转换可重建的无障碍图表。", "打包八项必需产物，列出未解决缺陷与非声明，在签署前验证全新重跑。"],
      deliverable: "一份另一位审查者无需网络即可重跑的完整八产物审计档案",
      reviewGate: "八项产物齐全、校验和与测试一致、每项声明都有可追溯计算，而且备忘录明确拒绝现实总体或部署结论。",
      checkpointQuestion: "对这个合成 fixture 的完整审计能够证明什么？",
      checkpointOptions: ["真实学生支持项目的效果", "提交的转换与有边界声明能针对固定虚构输入复现", "处理真实学习者数据已获法律授权", "分析已经可以自动部署"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "fixture 可以展示针对虚构记录的可审查流程，但不能提供总体证据、法律授权或部署保证。",
      takeaway: "强审计档案证明有边界流程的可追溯性；它不会把合成记录变成关于真实人的声明，也不授权部署。",
    },
  }),
] as const;

export type AiPythonDataModuleSlug =
  (typeof AI_PYTHON_DATA_MODULES)[number]["slug"];
export type AiPythonDataPhaseId =
  (typeof AI_PYTHON_DATA_MODULES)[number]["phaseId"];
