import type { CursorSourceId, CursorSourceRecord } from "./types";

const accessedOn = "2026-08-23";
// Verification was recorded at date precision; do not invent a midnight time.
const verifiedAt = accessedOn;

type Draft = Omit<CursorSourceRecord, "accessedOn" | "verifiedAt" | "exactAnchor" | "claimIds" | "reuseMode"> & {
  readonly exactAnchor?: string;
  readonly claimIds: readonly string[];
  readonly reuseMode?: CursorSourceRecord["reuseMode"];
};

function source(input: Draft): CursorSourceRecord {
  return {
    ...input,
    accessedOn,
    verifiedAt,
    exactAnchor: input.exactAnchor ?? input.url,
    reuseMode: input.reuseMode ?? "paraphrased",
  };
}

/**
 * Cursor-owned pages establish product behaviour. GitHub repositories show
 * inspectable practitioner patterns only: they do not establish productivity
 * gains, correctness, or official endorsement.
 */
export const CURSOR_SOURCES = [
  source({ id: "cursor-quickstart", tier: "primary", kind: "official-doc", title: "Quickstart", publisher: "Cursor", url: "https://cursor.com/docs/get-started/quickstart", claimIds: ["open-agent", "bounded-first-task", "review-and-check", "plan-mode"], note: "Current first-party sequence: understand the workspace, make a small change, review the diff, and run project checks." }),
  source({ id: "cursor-download", tier: "primary", kind: "official-doc", title: "Cursor Download", publisher: "Cursor", url: "https://cursor.com/download", claimIds: ["desktop-current-version", "desktop-platforms", "desktop-cli-distinction"], note: "Current first-party download page. Desktop 3.17 is marked Latest in the 2026-08-23 snapshot; the course records this executable target instead of assuming that a future release has the same UI." }),
  source({ id: "cursor-cli", tier: "primary", kind: "official-doc", title: "Cursor CLI", publisher: "Cursor", url: "https://cursor.com/docs/cli/overview", claimIds: ["terminal-agent", "interactive-and-print", "cli-modes", "cli-sandbox"], note: "Current CLI overview. The course explicitly scopes its executable interface practice to Cursor Desktop 3.17 and directs CLI users to the separate current installation, mode, sandbox, and approval documentation." }),
  source({ id: "cursor-data-use", tier: "primary", kind: "official-doc", title: "Data Use & Privacy Overview", publisher: "Cursor", url: "https://cursor.com/data-use", claimIds: ["privacy-mode", "server-processing", "indexing-metadata", "byok-routing", "abuse-investigation-exception", "non-zdr-opt-in"], note: "Authoritative privacy reference updated 2026-07-15. Privacy Mode is not local-only processing; the page also documents abuse-investigation retention exceptions and designated or admin-opted non-ZDR models." }),
  source({ id: "cursor-tab", tier: "primary", kind: "official-doc", title: "Cursor Tab", publisher: "Cursor", url: "https://cursor.com/tab", claimIds: ["next-action-prediction", "multiline-suggestion", "tab-accept"], reuseMode: "asset-reused", note: "Current Tab product page; dated model names and performance numbers are excluded from assessed content." }),
  source({ id: "cursor-inline-edit", tier: "primary", kind: "official-doc", title: "Inline Edit", publisher: "Cursor", url: "https://cursor.com/help/ai-features/inline-edit", supportingAnchors: ["https://cursor.com/docs/rules#faq"], claimIds: ["inline-edit", "selection-boundary", "cmd-ctrl-k", "user-rules-excluded"], note: "Current help reference for a small selected edit. Cursor's current Rules FAQ states that User Rules are not applied to Inline Edit (Cmd/Ctrl+K)." }),
  source({ id: "cursor-agent-overview", tier: "primary", kind: "official-doc", title: "Agent overview", publisher: "Cursor", url: "https://cursor.com/docs/agent/overview", exactAnchor: "https://cursor.com/docs/agent/overview#checkpoints", supportingAnchors: ["https://cursor.com/docs/agent/overview"], claimIds: ["agent-tools", "clarification", "checkpoints-not-git"], note: "Current Agent capabilities and checkpoint semantics. Checkpoints are convenience snapshots, not version control." }),
  source({ id: "cursor-agent-security", tier: "primary", kind: "official-doc", title: "Agent Security", publisher: "Cursor", url: "https://cursor.com/docs/agent/security", claimIds: ["workspace-edits-save-immediately", "terminal-approval-default", "auto-reload-risk"], note: "Current security reference. Ordinary workspace edits can save without an approval prompt; terminal approval and other controls are separate boundaries." }),
  source({ id: "cursor-agents-window", tier: "primary", kind: "official-doc", title: "Agents Window", publisher: "Cursor", url: "https://cursor.com/docs/agent/agents-window", claimIds: ["agents-window", "editor-coexistence", "local-worktree-cloud-ssh"], reuseMode: "asset-reused", note: "Current agent-first interface reference and source for two authentic UI figures." }),
  source({ id: "cursor-prompting", tier: "primary", kind: "official-doc", title: "Prompting agents", publisher: "Cursor", url: "https://cursor.com/docs/agent/prompting", claimIds: ["selective-context", "at-mentions", "context-ring", "agent-search"], note: "Current guidance for known context, dynamic search, terminals, chats, diffs, Browser, and context inspection." }),
  source({ id: "cursor-planning", tier: "primary", kind: "official-doc", title: "Plan Mode", publisher: "Cursor", url: "https://cursor.com/docs/agent/plan-mode", claimIds: ["repository-research", "clarifying-questions", "editable-plan", "approval-before-build"], note: "Current Plan Mode contract. A plan is reviewable preparation, not a correctness guarantee." }),
  source({ id: "cursor-shell", tier: "primary", kind: "official-doc", title: "Terminal tool", publisher: "Cursor", url: "https://cursor.com/docs/agent/tools/terminal", claimIds: ["integrated-terminal", "command-review", "terminal-evidence"], note: "Current local terminal behaviour; approval and sandbox policy is governed by Run Modes." }),
  source({ id: "cursor-run-modes", tier: "primary", kind: "official-doc", title: "Run Modes", publisher: "Cursor", url: "https://cursor.com/docs/agent/security/run-modes", claimIds: ["auto-review", "allowlist", "run-everything", "classifier-not-boundary"], reuseMode: "asset-reused", note: "Current labels are Auto-review, Allowlist, and Run Everything. Older YOLO and Ask Every Time labels are excluded." }),
  source({ id: "cursor-security-hardening", tier: "primary", kind: "official-doc", title: "Security and Privacy Hardening", publisher: "Cursor", url: "https://cursor.com/docs/enterprise/security-hardening", exactAnchor: "https://cursor.com/docs/enterprise/security-hardening#agent-runtime-and-deterministic-controls", claimIds: ["cursorignore-boundary", "terminal-sandbox", "mcp-access", "defence-in-depth"], note: "Current first-party hardening summary. .cursorignore limits built-in Agent context, but is not by itself a complete terminal or MCP boundary; pair it with sandboxing, approvals, and file permissions." }),
  source({ id: "cursor-agent-review", tier: "primary", kind: "official-doc", title: "Agent Review", publisher: "Cursor", url: "https://cursor.com/docs/agent/agent-review", claimIds: ["local-review", "quick-deep", "agent-review-command", "human-triage"], note: "Current local review workflow; deliberately distinguished from the enterprise Security Review product." }),
  source({ id: "cursor-debugging", tier: "primary", kind: "official-doc", title: "Debug Mode", publisher: "Cursor", url: "https://cursor.com/docs/agent/debug-mode", claimIds: ["reproduce", "hypotheses", "instrumentation", "root-cause"], note: "Current Debug Mode guidance paired with deterministic reproduction and regression checks." }),
  source({ id: "cursor-rules", tier: "primary", kind: "official-doc", title: "Rules", publisher: "Cursor", url: "https://cursor.com/docs/rules", exactAnchor: "https://cursor.com/docs/rules#rule-file-structure", supportingAnchors: ["https://cursor.com/docs/rules#rule-anatomy", "https://cursor.com/docs/rules#agentsmd", "https://cursor.com/docs/rules#faq"], claimIds: ["mdc-project-rules", "agents-md", "activation-semantics", "rule-scope", "user-rules-excluded"], reuseMode: "asset-reused", note: "Current rule paths, types, activation semantics, and FAQ. Plain .md in .cursor/rules is ignored, User Rules are not applied to Inline Edit, and legacy .cursorrules is not taught." }),
  source({ id: "cursor-skills", tier: "primary", kind: "official-doc", title: "Skills", publisher: "Cursor", url: "https://cursor.com/docs/skills", claimIds: ["agent-skills-standard", "cursor-skills", "agents-skills", "manual-invocation"], reuseMode: "asset-reused", note: "Current portable Skills packaging. Slash Commands remain supported." }),
  source({ id: "cursor-subagents", tier: "primary", kind: "official-doc", title: "Subagents", publisher: "Cursor", url: "https://cursor.com/docs/subagents", exactAnchor: "https://cursor.com/docs/subagents#isolated-project-copies", supportingAnchors: ["https://cursor.com/docs/subagents"], claimIds: ["context-isolation", "parallel-execution", "shared-checkout-default", "isolated-project-copies", "readonly-subagents", "inherited-mcp-tools"], note: "Current Subagents reference. Separate context does not imply file isolation, and readonly local mutation does not remove inherited write-capable MCP or external tools." }),
  source({ id: "cursor-hooks", tier: "primary", kind: "official-doc", title: "Hooks", publisher: "Cursor", url: "https://cursor.com/docs/hooks", claimIds: ["hook-events", "command-hook-denial", "prompt-hook-model-evaluation", "fail-open-default", "fail-closed-option", "cloud-hook-limitations"], note: "Current Hooks reference. Only command-based pre-action Hooks provide deterministic deny decisions; prompt Hooks are model-evaluated. Failures are fail-open by default, and Hook availability differs in Cloud Agents." }),
  source({ id: "cursor-mcp", tier: "primary", kind: "official-doc", title: "Model Context Protocol", publisher: "Cursor", url: "https://cursor.com/docs/mcp", claimIds: ["mcp-tools", "external-systems", "tool-trust"], reuseMode: "asset-reused", note: "Current MCP reference. Third-party tools are treated as executable trust boundaries." }),
  source({ id: "cursor-cloud-agents", tier: "primary", kind: "official-doc", title: "Cloud Agents", publisher: "Cursor", url: "https://cursor.com/docs/cloud-agent", claimIds: ["isolated-vm", "parallel-agents", "branch-handoff", "cloud-security-surface"], note: "Current term and architecture. Background Agent appears only as historical terminology." }),
  source({ id: "cursor-cloud-builds", tier: "primary", kind: "official-doc", title: "Cloud Agent Builds", publisher: "Cursor", url: "https://cursor.com/docs/cloud-agent/builds", exactAnchor: "https://cursor.com/docs/cloud-agent/builds#manage-builds", supportingAnchors: ["https://cursor.com/docs/cloud-agent/builds#debug-a-build"], claimIds: ["build-status", "build-logs", "build-commits", "agent-build-provenance"], note: "Current Cloud Agent Builds reference for status, start time, details, logs, repository commits, and the exact Build used by an agent run." }),
  source({ id: "cursor-cloud-best-practices", tier: "primary", kind: "official-doc", title: "Cloud Agent best practices", publisher: "Cursor", url: "https://cursor.com/docs/cloud-agent/best-practices", claimIds: ["environment-first", "local-testability", "rules-and-skills", "least-lived-credentials"], note: "Current preparation guidance for reproducible cloud runs and explicit environment access." }),
  source({ id: "cursor-automations", tier: "primary", kind: "official-doc", title: "Cloud Agent automations", publisher: "Cursor", url: "https://cursor.com/docs/cloud-agent/automations", claimIds: ["scheduled-task", "default-pr-creation", "persistent-memory", "computer-use", "external-tools", "review-destination"], note: "Current automation reference. Repo-backed Automations can begin with consequential defaults, so the course requires a synthetic dry run, least privilege, and explicit human review." }),
  source({ id: "cursor-google-workspace", tier: "primary", kind: "official-blog", title: "Google Workspace Plugins", publisher: "Cursor", url: "https://cursor.com/changelog/google-workspace-plugins", claimIds: ["drive-gmail-calendar-plugins", "integration-entitlement"], note: "Dated 2026-08-03 announcement. Availability must be rechecked; the core office exercise works without it." }),
  source({ id: "cursor-browser", tier: "primary", kind: "official-doc", title: "Browser tool", publisher: "Cursor", url: "https://cursor.com/docs/agent/tools/browser", exactAnchor: "https://cursor.com/docs/agent/tools/browser#automated-testing", supportingAnchors: ["https://cursor.com/docs/agent/tools/browser#browser-capabilities", "https://cursor.com/docs/agent/tools/browser#tool-approval", "https://cursor.com/docs/agent/tools/browser#origin-allowlist"], claimIds: ["browser-tool", "origin-allowlist", "persistent-workspace-browser-state", "visual-verification"], reuseMode: "asset-reused", note: "Current Browser capabilities, testing uses, approval model, persistent per-workspace browser state, and enterprise Origin Allowlist. Manual approval is the default learner path; the allowlist is optional and best-effort." }),
  source({ id: "cursor-plugins", tier: "primary", kind: "official-doc", title: "Plugins", publisher: "Cursor", url: "https://cursor.com/docs/plugins", claimIds: ["plugin-bundles", "plugin-install-scope", "plugin-supply-chain"], note: "Current plugin reference. Plugins can bundle several executable customization surfaces, so installation and updates require component-level review." }),
  source({ id: "cursor-side-chat", tier: "primary", kind: "official-blog", title: "Side Chat", publisher: "Cursor", url: "https://cursor.com/changelog/side-chat", claimIds: ["side-chat-tangent", "reference-back-to-primary-chat"], reuseMode: "asset-reused", note: "Dated first-party Side Chat announcement and figure source. The course uses the durable tangent-and-reference workflow, not the dated chrome." }),
  source({ id: "cursor-students", tier: "primary", kind: "official-doc", title: "Cursor for Students", publisher: "Cursor", url: "https://cursor.com/students", claimIds: ["student-program", "education-context"], note: "Official education page. Teaching practice is grounded separately in inspectable practitioner evidence." }),
  source({ id: "cursor-plan-mode-blog", tier: "primary", kind: "official-blog", title: "Plan Mode", publisher: "Cursor", url: "https://cursor.com/blog/plan-mode", claimIds: ["plan-mode-history", "editable-plan", "shift-tab"], reuseMode: "asset-reused", note: "Published 2025-10-07. The concept remains current; the visual chrome is explicitly date-stamped." }),
  source({ id: "cursor-changelog-2026-08", tier: "primary", kind: "official-blog", title: "Custom Modes, VM subagents, subscriptions, and /goal", publisher: "Cursor", url: "https://cursor.com/changelog/08-19-26", claimIds: ["custom-modes", "vm-subagents", "goal-command", "rolling-release"], reuseMode: "asset-reused", note: "Published 2026-08-19. Advanced rolling features are not prerequisites for the course." }),
  source({ id: "cursor-product", tier: "primary", kind: "official-doc", title: "Cursor product", publisher: "Cursor", url: "https://cursor.com/product", claimIds: ["agent-first-editor", "tab-agent-cloud"], note: "Current product positioning; volatile pricing, quotas, and model catalogues are excluded from assessed content." }),
  source({ id: "cursor-learn-understand", tier: "primary", kind: "official-doc", title: "Understanding your codebase", publisher: "Cursor Learn", url: "https://cursor.com/learn/understanding-your-codebase", claimIds: ["agentic-search", "codebase-orientation", "read-before-write"], reuseMode: "asset-reused", note: "First-party lesson and media used for an editorial UI still demonstrating repository search." }),
  source({ id: "cursor-learn-features", tier: "primary", kind: "official-doc", title: "Creating features", publisher: "Cursor Learn", url: "https://cursor.com/learn/creating-features", claimIds: ["feature-contract", "plan-before-build", "bounded-implementation"], reuseMode: "asset-reused", note: "First-party lesson and media used for a dated editorial UI still." }),
  source({ id: "cursor-learn-debug", tier: "primary", kind: "official-doc", title: "Finding and fixing bugs", publisher: "Cursor Learn", url: "https://cursor.com/learn/finding-fixing-bugs", claimIds: ["reproduce-first", "hypothesis", "regression-check"], note: "First-party debugging lesson; assessment requires evidence, not model confidence." }),
  source({ id: "cursor-learn-review", tier: "primary", kind: "official-doc", title: "Reviewing and testing code", publisher: "Cursor Learn", url: "https://cursor.com/learn/reviewing-testing", claimIds: ["diff-review", "testing", "feedback-loop"], note: "First-party review lesson paired with repository-specific checks and human approval." }),
  source({ id: "cursor-worktrees", tier: "primary", kind: "official-doc", title: "Worktrees", publisher: "Cursor", url: "https://cursor.com/docs/configuration/worktrees", claimIds: ["isolated-git-checkout", "agents-window-worktrees", "worktree-skill"], note: "Current worktree reference. A worktree isolates files and branch state; it does not remove the need for integration review." }),

  source({ id: "course-capstone-fixture", tier: "corroborating", kind: "course-artifact", title: "Course 4 capstone fixture and verifier contract", publisher: "aicourse.top", url: "https://aicourse.top/courses/cursor/CAPSTONE_CONTRACT.md", exactAnchor: "https://aicourse.top/courses/cursor/CAPSTONE_CONTRACT.md", supportingAnchors: ["https://aicourse.top/courses/cursor/aicourse-cursor-demo-v1.zip", "https://aicourse.top/courses/cursor/aicourse-cursor-demo-v1.sha256"], claimIds: ["receipt-schema", "fixture-hash", "declared-check-results", "stale-receipt-removal", "unsigned-non-attestation"], reuseMode: "link-only", note: "Versioned course-owned contract for the local self-check schema and verifier behavior. It is not Cursor product evidence, an execution attestation, or identity proof." }),

  source({ id: "github-domain-agent", tier: "corroborating", kind: "community-github", title: "alexmihalache/cursor_domain_agent", publisher: "Alex Mihalache", url: "https://github.com/alexmihalache/cursor_domain_agent", exactAnchor: "https://github.com/alexmihalache/cursor_domain_agent/blob/9add613d301e0f3ba980174a2c39b37291802d0c/documentation/ARTICLE_v2.md#L68-L166", supportingAnchors: ["https://github.com/alexmihalache/cursor_domain_agent/blob/9add613d301e0f3ba980174a2c39b37291802d0c/documentation/ARTICLE_v2.md#L31-L49", "https://github.com/alexmihalache/cursor_domain_agent/blob/9add613d301e0f3ba980174a2c39b37291802d0c/documentation/ARTICLE_v2.md#L168-L205"], claimIds: ["artifact-first-research", "sanity-leakage-gates", "negative-results", "run-metadata"], reuseMode: "link-only", license: "MIT; educational/research and no-financial-advice disclaimer", revision: "9add613d301e0f3ba980174a2c39b37291802d0c", note: "Cursor-specific research workflow evidence, not evidence of scientific or financial validity." }),
  source({ id: "github-product-managers", tier: "corroborating", kind: "community-github", title: "jinjin1/Cursor-for-Product-Managers", publisher: "Jinjin", url: "https://github.com/jinjin1/Cursor-for-Product-Managers", exactAnchor: "https://github.com/jinjin1/Cursor-for-Product-Managers/blob/21a835d4a2736210f304df59633944e22c1eee31/README.md#L33-L75", supportingAnchors: ["https://github.com/jinjin1/Cursor-for-Product-Managers/blob/21a835d4a2736210f304df59633944e22c1eee31/README.md#L185-L200"], claimIds: ["interview-evidence", "synthesis-separation", "prd-workflow", "skills-migration"], reuseMode: "link-only", license: "Apache-2.0", revision: "21a835d4a2736210f304df59633944e22c1eee31", note: "Current Cursor-native office workflow pattern; generated recommendations still need human validation." }),
  source({ id: "github-strapi-docs", tier: "corroborating", kind: "community-github", title: "strapi/documentation", publisher: "Strapi", url: "https://github.com/strapi/documentation", exactAnchor: "https://github.com/strapi/documentation/blob/ede5b50b7a9ca89b5ccb49ca6d28c7d3985554f3/AGENTS.md#L85-L155", supportingAnchors: ["https://github.com/strapi/documentation/blob/13e6d3c1623837362bf8e45f3c782e34cd261e53/.cursor/rules/strapi-docs-integrity-checker.mdc#L76-L125", "https://github.com/strapi/documentation/blob/6656e5133b45272f6b2706c4a6699a77bdc61dff/.cursor/rules/strapi-docs-style-checker.mdc#L31-L114"], claimIds: ["outline-draft-style-integrity", "verified-unverified-falsified", "publication-gates"], reuseMode: "link-only", license: "MIT for covered repository content; exceptions may apply", revision: "ede5b50b7a9ca89b5ccb49ca6d28c7d3985554f3", note: "Production documentation evidence. Its large organisation rules are not copied wholesale." }),
  source({ id: "github-metamask-design", tier: "corroborating", kind: "community-github", title: "MetaMask/metamask-design-system", publisher: "MetaMask", url: "https://github.com/MetaMask/metamask-design-system", exactAnchor: "https://github.com/MetaMask/metamask-design-system/blob/e98ccb94827bf9370fd80d505a0be1d9b3c734f9/.cursor/rules/pr.mdc#L9-L49", supportingAnchors: ["https://github.com/MetaMask/metamask-design-system/pull/793"], claimIds: ["draft-pr", "diff-and-template"], reuseMode: "link-only", license: "No repository license detected; citation only", revision: "e98ccb94827bf9370fd80d505a0be1d9b3c734f9", note: "Historical adopted workflow that creates a draft PR before asking the user to review it. It is not evidence for pre-creation approval; its frontmatter is stale under current rule semantics, and its video is excluded." }),
  source({ id: "github-alibaba-hooks", tier: "corroborating", kind: "community-github", title: "alibaba/hooks", publisher: "Alibaba", url: "https://github.com/alibaba/hooks", exactAnchor: "https://github.com/alibaba/hooks/blob/2b3a0afd67c9e92fa4542b485a711cd113668942/.cursor/rules/git.mdc#L1-L15", supportingAnchors: ["https://github.com/alibaba/hooks/blob/2b3a0afd67c9e92fa4542b485a711cd113668942/.cursor/rules/git.mdc#L58-L89"], claimIds: ["branch-pr-review-ci", "tests-docs-gates", "team-policy"], reuseMode: "link-only", license: "MIT", revision: "2b3a0afd67c9e92fa4542b485a711cd113668942", note: "Mature team-policy evidence. Its wording is local policy, not a Cursor requirement." }),
  source({ id: "github-tutor", tier: "corroborating", kind: "community-github", title: "kevinnio/tutor", publisher: "Kevin Nio", url: "https://github.com/kevinnio/tutor", exactAnchor: "https://github.com/kevinnio/tutor/blob/88ffe9ac5e3e41962393f8eb14b080a6c039ed40/README.md#L5-L26", supportingAnchors: ["https://github.com/kevinnio/tutor/blob/88ffe9ac5e3e41962393f8eb14b080a6c039ed40/README.md#L73-L130", "https://github.com/kevinnio/tutor/blob/88ffe9ac5e3e41962393f8eb14b080a6c039ed40/README.md#L180-L197"], claimIds: ["productive-struggle", "one-action-per-turn", "read-only-verification", "pin-third-party-skills"], reuseMode: "link-only", license: "MIT", revision: "88ffe9ac5e3e41962393f8eb14b080a6c039ed40", note: "Current teaching Skill; learners inspect and pin third-party instructions before use." }),
  source({ id: "github-cursor-workshop", tier: "corroborating", kind: "community-github", title: "dotdc/cursor-workshop", publisher: "dotdc", url: "https://github.com/dotdc/cursor-workshop", exactAnchor: "https://github.com/dotdc/cursor-workshop/blob/ad5504f734016e54a5603946c75edbfc4d993ad4/typescript-workshop/README.md#L33-L84", supportingAnchors: ["https://github.com/dotdc/cursor-workshop/blob/ad5504f734016e54a5603946c75edbfc4d993ad4/typescript-workshop/README.md#L117-L138"], claimIds: ["small-quests", "observable-task", "tests-and-docs"], reuseMode: "link-only", license: "MIT for main repository; separate media excluded", revision: "ad5504f734016e54a5603946c75edbfc4d993ad4", note: "Workshop pattern only. Its 2025 UI and separately hosted media are not reused." }),
  source({ id: "github-plaintext-crm", tier: "corroborating", kind: "community-github", title: "anthroos/plaintext-crm", publisher: "Anthroos", url: "https://github.com/anthroos/plaintext-crm", exactAnchor: "https://github.com/anthroos/plaintext-crm/blob/eaf2fb30af68e7a08c9b29c041e6edf50bacd837/README.md#L34-L70", supportingAnchors: ["https://github.com/anthroos/plaintext-crm/blob/eaf2fb30af68e7a08c9b29c041e6edf50bacd837/README.md#L188-L211"], claimIds: ["plain-text-office-data", "schema-validation", "versioned-artifacts"], reuseMode: "link-only", license: "MIT", revision: "eaf2fb30af68e7a08c9b29c041e6edf50bacd837", note: "Portable office pattern with medium Cursor specificity. The course independently requires synthetic practice data; the repository is not cited for that safety rule." }),
  source({ id: "github-spec-kit", tier: "corroborating", kind: "community-github", title: "github/spec-kit", publisher: "GitHub", url: "https://github.com/github/spec-kit", exactAnchor: "https://github.com/github/spec-kit/blob/27f50f7e6b618ea14d74dd4037f9e7c60218b16c/spec-driven.md", claimIds: ["specify-clarify-plan-tasks-implement", "phase-separation"], reuseMode: "link-only", license: "MIT", revision: "27f50f7e6b618ea14d74dd4037f9e7c60218b16c", note: "Cross-tool phase-separation pattern pinned to the 2026-08-23 main revision, not Cursor product evidence." }),
  source({ id: "github-superpowers", tier: "corroborating", kind: "community-github", title: "obra/superpowers", publisher: "obra", url: "https://github.com/obra/superpowers", exactAnchor: "https://github.com/obra/superpowers/blob/b36e0829c6d0140e93cfef2ca599b1b07d4a7797/skills/systematic-debugging/SKILL.md", claimIds: ["root-cause-first", "red-green", "fresh-verification"], reuseMode: "link-only", license: "MIT", revision: "b36e0829c6d0140e93cfef2ca599b1b07d4a7797", note: "Cross-tool debugging corroboration pinned to the 2026-08-23 main revision; popularity is not correctness evidence." }),
  source({ id: "github-agents-md", tier: "corroborating", kind: "community-github", title: "agentsmd/agents.md", publisher: "agentsmd", url: "https://github.com/agentsmd/agents.md", exactAnchor: "https://github.com/agentsmd/agents.md/blob/d1ac7f063d20e70015ed6732664049ae4ba9d74e/README.md", claimIds: ["agents-md-format", "cross-tool-instructions"], reuseMode: "link-only", license: "MIT", revision: "d1ac7f063d20e70015ed6732664049ae4ba9d74e", note: "Cross-tool corroboration for readable repository instructions, pinned to the 2026-08-23 main revision. Nested Cursor rule behavior is supported by Cursor's Rules documentation instead." }),
] as const satisfies readonly CursorSourceRecord[];

export const CURSOR_SOURCE_BY_ID = Object.fromEntries(
  CURSOR_SOURCES.map((item) => [item.id, item]),
) as unknown as Readonly<Record<CursorSourceId, CursorSourceRecord>>;
