import type { MathAnimationCodeExample } from "./types";

const sceneContract = [
  "# Scene contract: secant becomes tangent",
  "",
  "## Mathematical truth",
  "- Function: f: [-3, 3] -> R, f(x) = x^2.",
  "- Fixed x-coordinate: a = 1; P = (a, f(a)) = (1, 1).",
  "- Moving point: Q_h = (a+h, f(a+h)), where positive h decreases from 2 to 0.08 and h never equals 0.",
  "- Secant slope: m_h = (f(a+h) - f(a)) / h = 2a + h for every nearby h != 0.",
  "- The motion depicts h -> 0+. Because the identity also holds for h < 0, the algebra establishes the two-sided limit lim(h->0) m_h = 2a.",
  "",
  "## Scene grammar",
  "1. Establish axes, curve, and fixed point.",
  "2. Introduce the moving point and secant line.",
  "3. Decrease h while the line and numeric slope update together.",
  "4. Freeze at h = 0.08, label the motion as h -> 0+, then state that the algebra establishes the two-sided limit.",
  "",
  "## Acceptance checks",
  "- Render and review responsive 16:9 and 9:16 outputs separately; a center crop is not portrait acceptance.",
  "- Labels remain inside the safe area of each separately rendered output.",
  "- The displayed slope equals 2a+h within 0.01 at every sampled checkpoint.",
  "- Identity is preserved: the same two dots transform; they are not replaced invisibly.",
  "- A still frame and a reduced-motion explanation communicate the same conclusion.",
].join("\n");

const manimFirstScene = [
  "from manim import *",
  "",
  "",
  "class SquareToCircle(Scene):",
  "    def construct(self):",
  "        square = Square(color=BLUE).set_fill(BLUE, opacity=0.25)",
  "        circle = Circle(color=TEAL).set_fill(TEAL, opacity=0.25)",
  "        title = Text(\"Preserve identity; change the representation\", font_size=30)",
  "        title.to_edge(UP)",
  "",
  "        self.play(Write(title), Create(square))",
  "        self.play(Transform(square, circle), run_time=1.4)",
  "        self.wait(0.4)",
].join("\n");

const manimTransform = [
  "from manim import *",
  "",
  "",
  "class CompleteTheSquare(Scene):",
  "    def construct(self):",
  "        start = MathTex(r\"x^2 + 6x + 5 = 0\")",
  "        step_1 = MathTex(r\"x^2 + 6x + 9 = 4\")",
  "        step_2 = MathTex(r\"(x+3)^2 = 4\")",
  "        result = MathTex(r\"x = -3 \\pm 2\")",
  "",
  "        self.play(Write(start))",
  "        self.play(TransformMatchingTex(start, step_1))",
  "        self.play(TransformMatchingTex(step_1, step_2))",
  "        self.play(TransformMatchingTex(step_2, result))",
  "        self.wait()",
].join("\n");

const manimGraph = [
  "from pathlib import Path",
  "import sys",
  "",
  "import numpy as np",
  "",
  "# Keep the pure truth module importable when Manim loads this file by path.",
  "SCENE_DIRECTORY = Path(__file__).resolve().parent",
  "if str(SCENE_DIRECTORY) not in sys.path:",
  "    sys.path.insert(0, str(SCENE_DIRECTORY))",
  "",
  "from manim import *",
  "from math_truth import format_slope, function, secant_state",
  "",
  "# The CLI's -r option changes pixels but does not recalculate the logical frame.",
  "# Set the logical width before Manim instantiates the scene camera.",
  "config.frame_width = config.frame_height * config.pixel_width / config.pixel_height",
  "",
  "",
  "class SecantToTangent(Scene):",
  "    def construct(self):",
  "        vertical = config.pixel_height > config.pixel_width",
  "        axes = Axes(",
  "            x_range=[-3, 3, 1],",
  "            y_range=[0, 9, 1],",
  "            x_length=3.8 if vertical else 7,",
  "            y_length=3.5 if vertical else 4.5,",
  "            tips=False,",
  "        )",
  "        if vertical:",
  "            axes.shift(UP * 0.6)",
  "        graph = axes.plot(function, x_range=[-3, 3], color=BLUE)",
  "        h = ValueTracker(2.0)",
  "        a = 1.0",
  "",
  "        def state():",
  "            return secant_state(a, h.get_value())",
  "",
  "        fixed_point = Dot(axes.c2p(*state().fixed_point), color=YELLOW)",
  "        moving_point = Dot(axes.c2p(*state().moving_point), color=TEAL)",
  "        moving_point.add_updater(",
  "            lambda point: point.move_to(axes.c2p(*state().moving_point))",
  "        )",
  "        def secant_line():",
  "            fixed = np.array(axes.c2p(*state().fixed_point))",
  "            moving = np.array(axes.c2p(*state().moving_point))",
  "            direction = moving - fixed",
  "            length = np.linalg.norm(direction)",
  "            unit_direction = direction / length",
  "            extension = max(0.5, (3.6 - length) / 2)",
  "            return Line(",
  "                fixed - unit_direction * extension,",
  "                moving + unit_direction * extension,",
  "                color=WHITE,",
  "            )",
  "",
  "        secant = always_redraw(secant_line)",
  "",
  "        def slope_readout():",
  "            readout = VGroup(",
  "                Text(\"h\", font_size=22),",
  "                Text(f\"{h.get_value():.2f}\", font_size=22),",
  "                Text(\"secant slope\", font_size=22),",
  "                Text(format_slope(a, h.get_value()), font_size=22),",
  "            ).arrange(RIGHT)",
  "            return (",
  "                readout.next_to(axes, DOWN, buff=0.25)",
  "                if vertical",
  "                else readout.to_corner(UR)",
  "            )",
  "",
  "        slope = always_redraw(slope_readout)",
  "",
  "        self.play(Create(axes), Create(graph))",
  "        self.play(FadeIn(fixed_point, moving_point), Create(secant), FadeIn(slope))",
  "        self.play(h.animate.set_value(0.08), run_time=4, rate_func=smooth)",
  "        limit_statement = Text(",
  "            \"h -> 0+; slope -> 2\"",
  "            if vertical",
  "            else \"motion: h -> 0+; algebra: slope -> 2\",",
  "            font_size=22 if vertical else 24,",
  "        ).to_edge(DOWN, buff=0.45)",
  "        if vertical and limit_statement.width > config.frame_width - 0.6:",
  "            limit_statement.scale_to_fit_width(config.frame_width - 0.6)",
  "        self.play(FadeIn(limit_statement))",
  "        self.wait(0.5)",
].join("\n");

const agentInstructions = [
  "# AGENTS.md / CLAUDE.md: animation project contract",
  "",
  "- Read SCENE_CONTRACT.md before changing code.",
  "- Use the installed engine and its local documentation; do not mix ManimCE and ManimGL APIs.",
  "- Render a low-quality preview after each semantic beat.",
  "- Sample the mathematical invariant at t = 0, 0.25, 0.5, 0.75, 1.0.",
  "- Preserve object identity across transformations unless the storyboard says otherwise.",
  "- Do not invent logos, music, fonts, quotations, or licenses.",
  "- Stop and report if LaTeX, FFmpeg, fonts, or a repository version is missing.",
  "- Before completion: run tests, render the final frame, inspect three keyframes, and report output paths.",
].join("\n");

const motionCanvasScene = [
  "import {Circle, Line, makeScene2D} from '@motion-canvas/2d';",
  "import {createSignal, easeInOutCubic, Vector2} from '@motion-canvas/core';",
  "",
  "export default makeScene2D(function* (view) {",
  "  const theta = createSignal(0);",
  "  const radius = 220;",
  "  const circleOrigin = new Vector2(-420, 0);",
  "  const graphStart = 0;",
  "  const graphWidth = 700;",
  "  const point = () => circleOrigin.add(new Vector2(",
  "    radius * Math.cos(theta()),",
  "    -radius * Math.sin(theta()),",
  "  ));",
  "  const graphPoint = () => new Vector2(",
  "    graphStart + (theta() / (Math.PI * 2)) * graphWidth,",
  "    -radius * Math.sin(theta()),",
  "  );",
  "  const trace = () => Array.from({length: 91}, (_, index) => {",
  "    const sample = Math.min(theta(), (index / 90) * Math.PI * 2);",
  "    return new Vector2(",
  "      graphStart + (sample / (Math.PI * 2)) * graphWidth,",
  "      -radius * Math.sin(sample),",
  "    );",
  "  });",
  "",
  "  view.add(",
  "    <>",
  "      <Circle position={circleOrigin} size={radius * 2} stroke={'#2458a6'} lineWidth={8} />",
  "      <Line points={() => [circleOrigin, point()]} stroke={'#1d2635'} lineWidth={5} />",
  "      <Line points={() => [point(), new Vector2(point().x, 0)]} stroke={'#2458a6'} lineWidth={4} />",
  "      <Circle position={point} size={28} fill={'#2458a6'} />",
  "      <Line points={[[graphStart, 0], [graphStart + graphWidth, 0]]} stroke={'#68758b'} lineWidth={3} />",
  "      <Line points={trace} stroke={'#2458a6'} lineWidth={7} />",
  "      <Line points={() => [new Vector2(graphPoint().x, 0), graphPoint()]} stroke={'#2458a6'} lineWidth={4} />",
  "      <Circle position={graphPoint} size={26} fill={'#2458a6'} />",
  "    </>,",
  "  );",
  "",
  "  yield* theta(Math.PI * 2, 8, easeInOutCubic);",
  "});",
].join("\n");

const ffmpegExport = [
  "#!/usr/bin/env sh",
  "set -eu",
  "input=${1:-media/videos/scene/480p15/SecantToTangent.mp4}",
  "output_dir=${2:-output}",
  "test -f \"$input\" || { echo \"Input video not found: $input\" >&2; exit 2; }",
  "mkdir -p \"$output_dir/keyframes\"",
  "output_video=\"$output_dir/math-animation.mp4\"",
  "",
  "# Normalize the rendered MP4 to broadly compatible H.264/yuv420p.",
  "ffmpeg -y -i \"$input\" -map 0:v:0 -map \"0:a?\" \\",
  "  -c:v libx264 -pix_fmt yuv420p -movflags +faststart -c:a aac \"$output_video\"",
  "duration=$(ffprobe -v error -show_entries format=duration \\",
  "  -of default=noprint_wrappers=1:nokey=1 \"$output_video\")",
  "",
  "for sample in start:0.14 quarter:0.30 midpoint:0.50 three-quarter:0.72 final:0.96; do",
  "  name=${sample%%:*}; fraction=${sample#*:}",
  "  timestamp=$(awk -v d=\"$duration\" -v f=\"$fraction\" \\",
  "    'BEGIN { printf \"%.3f\", d * f }')",
  "  ffmpeg -y -ss \"$timestamp\" -i \"$output_video\" -frames:v 1 -update 1 \\",
  "    \"$output_dir/keyframes/$name.png\"",
  "done",
  "",
  "ffprobe -v error -show_entries format=duration \\",
  "  -show_entries stream=codec_name,width,height,r_frame_rate \\",
  "  -of json \"$output_video\"",
].join("\n");

const qaScript = [
  "from math import isclose",
  "",
  "from math_truth import CHECKPOINTS, format_slope, secant_state",
  "",
  "",
  "# Positive checkpoints match the depicted motion; negative samples verify the two-sided algebra.",
  "for checkpoint in (*CHECKPOINTS, -0.08, -0.5, -1.0):",
  "    state = secant_state(1.0, checkpoint)",
  "    line_slope = (",
  "        (state.moving_point[1] - state.fixed_point[1])",
  "        / (state.moving_point[0] - state.fixed_point[0])",
  "    )",
  "    displayed_value = float(format_slope(1.0, checkpoint))",
  "    expected = 2.0 + checkpoint",
  "    assert isclose(state.slope, expected, abs_tol=1e-9), (",
  "        checkpoint,",
  "        state.slope,",
  "        expected,",
  "    )",
  "    assert isclose(line_slope, state.slope, abs_tol=1e-9)",
  "    assert isclose(displayed_value, state.slope, abs_tol=0.01)",
  "",
  "print(\"mathematical invariant: pass\")",
].join("\n");

export const MATH_ANIMATION_CODE_EXAMPLES = {
  "scene-contract": {
    id: "scene-contract",
    language: "markdown",
    filename: "SCENE_CONTRACT.md",
    code: sceneContract,
  },
  "manim-first-scene": {
    id: "manim-first-scene",
    language: "python",
    filename: "scenes/first_scene.py",
    code: manimFirstScene,
  },
  "manim-transform": {
    id: "manim-transform",
    language: "python",
    filename: "scenes/complete_the_square.py",
    code: manimTransform,
  },
  "manim-graph": {
    id: "manim-graph",
    language: "python",
    filename: "manim/scene.py",
    code: manimGraph,
  },
  "agent-instructions": {
    id: "agent-instructions",
    language: "markdown",
    filename: "AGENTS.md / CLAUDE.md",
    code: agentInstructions,
  },
  "motion-canvas-scene": {
    id: "motion-canvas-scene",
    language: "typescript",
    filename: "src/scenes/unit-circle.tsx",
    code: motionCanvasScene,
  },
  "ffmpeg-export": {
    id: "ffmpeg-export",
    language: "shell",
    filename: "scripts/export.sh",
    code: ffmpegExport,
  },
  "qa-script": {
    id: "qa-script",
    language: "python",
    filename: "manim/test_math_truth.py",
    code: qaScript,
  },
} as const satisfies Readonly<Record<string, MathAnimationCodeExample>>;
