import type {
  MathAnimationRepositoryEvaluation,
  MathAnimationSourceId,
  MathAnimationSourceRecord,
} from "./types";

export const MATH_ANIMATION_SOURCES = [
  {
    id: "github-manim-ce",
    title: "Manim Community",
    publisher: "Manim Community Developers",
    url: "https://github.com/ManimCommunity/manim",
    kind: "github-repository",
    role: "core-implementation",
    accessedOn: "2026-08-26",
    versionOrRevision: "v0.21.0; commit 1dc796e9652273950d9863b35746c7329888e384",
    versionAnchorUrl: "https://github.com/ManimCommunity/manim/commit/1dc796e9652273950d9863b35746c7329888e384",
    claimEvidenceUrls: [
      "https://github.com/ManimCommunity/manim",
      "https://github.com/ManimCommunity/manim/releases/tag/v0.21.0",
      "https://github.com/ManimCommunity/manim/blob/1dc796e9652273950d9863b35746c7329888e384/README.md#license",
      "https://github.com/ManimCommunity/manim/blob/1dc796e9652273950d9863b35746c7329888e384/LICENSE",
      "https://github.com/ManimCommunity/manim/blob/1dc796e9652273950d9863b35746c7329888e384/LICENSE.community",
      "https://docs.manim.community/en/stable/guides/using_text.html",
    ],
    licenseOrRights: "MIT License. The pinned README identifies separate MIT notices for 3Blue1Brown LLC and Manim Community Developers; course examples are original.",
    licenseOrRightsZhHans: "固定修订采用 MIT 许可证，并含 3Blue1Brown LLC 与 Manim Community Developers 两份许可通知；课程示例为原创。",
    licenseUrl: "https://github.com/ManimCommunity/manim/blob/1dc796e9652273950d9863b35746c7329888e384/README.md#license",
    supports: "Primary Python engine for semantic mathematical objects, transformations, graphs, geometry, text, formulas, stills, and multiple video formats.",
    supportsZhHans: "支持带语义的数学对象、变换、函数图像、几何、文本、公式、静帧与多种视频格式，是课程主 Python 引擎。",
    boundary: "The repository warns that a major refactor is in progress. Version 0.x APIs may drift, and MathTex still requires an external typesetting toolchain.",
    boundaryZhHans: "仓库提示正在进行较大重构。0.x API 仍可能漂移，MathTex 也需要外部排版工具链。",
  },
  {
    id: "docs-manim-quickstart",
    title: "Manim Community quickstart and text guides",
    publisher: "Manim Community Developers",
    url: "https://docs.manim.community/en/stable/tutorials/quickstart.html",
    kind: "official-documentation",
    role: "core-implementation",
    accessedOn: "2026-08-26",
    versionOrRevision: "stable documentation snapshot aligned with v0.21.0",
    claimEvidenceUrls: [
      "https://docs.manim.community/en/stable/tutorials/quickstart.html",
      "https://docs.manim.community/en/stable/guides/using_text.html",
      "https://docs.manim.community/en/stable/reference/manim._config.utils.ManimConfig.html",
    ],
    licenseOrRights: "Documentation linked for instruction; no documentation text or branded gallery media is redistributed.",
    licenseOrRightsZhHans: "仅链接文档用于教学；不再分发文档正文或带品牌的图库媒体。",
    supports: "Controls the documented Manim Community scene, command-line preview, formula, text, configuration, and export claims used in the core path.",
    supportsZhHans: "控制主路线中的 Manim Community 场景、命令行预览、公式、文本、配置与导出声明。",
    boundary: "The stable documentation can change after the course snapshot. It does not prove that a learner's native dependencies or renderer are correctly installed.",
    boundaryZhHans: "stable 文档会在课程快照之后变化，也不能证明学习者的原生依赖或渲染器已正确安装。",
  },
  {
    id: "github-manimgl",
    title: "ManimGL",
    publisher: "3Blue1Brown",
    url: "https://github.com/3b1b/manim",
    kind: "github-repository",
    role: "core-implementation",
    accessedOn: "2026-08-26",
    versionOrRevision: "v1.7.2; commit 9d57bcf9edea2486f214e190931de2a5537f23c1",
    versionAnchorUrl: "https://github.com/3b1b/manim/commit/9d57bcf9edea2486f214e190931de2a5537f23c1",
    claimEvidenceUrls: [
      "https://github.com/3b1b/manim",
      "https://github.com/3b1b/manim/releases/tag/v1.7.2",
    ],
    licenseOrRights: "MIT License; the 3Blue1Brown name, marks, visual identity, and videos are not course assets.",
    licenseOrRightsZhHans: "MIT 许可证；3Blue1Brown 的名称、标志、视觉识别与视频不属于课程资产。",
    licenseUrl: "https://github.com/3b1b/manim/blob/9d57bcf9edea2486f214e190931de2a5537f23c1/LICENSE.md",
    supports: "Advanced ManimGL and OpenGL production reference with interactive development, presenter workflows, camera control, and the direct 3Blue1Brown code lineage.",
    supportsZhHans: "提供进阶 ManimGL 与 OpenGL 制作参考，包含交互开发、演示模式、镜头控制与 3Blue1Brown 源码脉络。",
    boundary: "Its commands and APIs are incompatible with Manim Community. The latest tagged release is older than current main-branch activity and old videos may not run unchanged.",
    boundaryZhHans: "其命令与 API 不兼容 Manim Community。最新 tag 早于当前主分支活动，旧视频代码也可能无法原样运行。",
  },
  {
    id: "github-3b1b-videos-claude",
    title: "3Blue1Brown videos project guidance for Claude Code",
    publisher: "3Blue1Brown",
    url: "https://github.com/3b1b/videos/blob/master/CLAUDE.md",
    kind: "github-repository",
    role: "workflow",
    accessedOn: "2026-08-26",
    versionOrRevision: "commit 674b966fbb6cf0307590d27744d186165e8b6a76",
    versionAnchorUrl: "https://github.com/3b1b/videos/blob/674b966fbb6cf0307590d27744d186165e8b6a76/CLAUDE.md",
    claimEvidenceUrls: [
      "https://github.com/3b1b/videos/blob/master/CLAUDE.md",
      "https://github.com/3b1b/videos/blob/674b966fbb6cf0307590d27744d186165e8b6a76/CLAUDE.md",
      "https://github.com/3b1b/videos/blob/674b966fbb6cf0307590d27744d186165e8b6a76/LICENSE.txt",
    ],
    licenseOrRights: "At the pinned revision, the repository carries a root Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) license file. This course only links to CLAUDE.md and does not copy its code or media; any reuse requires a separate scope and license-compliance review.",
    licenseOrRightsZhHans: "固定修订的仓库根目录载有 CC BY-NC-SA 4.0（署名—非商业性使用—相同方式共享）许可文件。课程仅链接 CLAUDE.md，不复制其代码或媒体；任何复用都须另行确认适用范围并遵守许可条件。",
    licenseUrl: "https://github.com/3b1b/videos/blob/674b966fbb6cf0307590d27744d186165e8b6a76/LICENSE.txt",
    supports: "A real project-level Claude Code instruction example that names its ManimGL environment, project commands, conventions, and review expectations.",
    supportsZhHans: "这是实际的 Claude Code 项目说明案例，明确写出 ManimGL 环境、项目命令、约定与审核期待。",
    boundary: "The file belongs to a specific ManimGL production repository. It does not authorize copying engine-specific commands into Manim Community or reusing the associated video assets.",
    boundaryZhHans: "该文件属于特定 ManimGL 制作仓库，不能据此把专用命令复制到 Manim Community，也不授权复用相关视频资产。",
  },
  {
    id: "github-manim-slides",
    title: "Manim Slides",
    publisher: "Jérome Eertmans and contributors",
    url: "https://github.com/jeertmans/manim-slides",
    kind: "github-repository",
    role: "core-implementation",
    accessedOn: "2026-08-26",
    versionOrRevision: "v5.6.0; commit 1549ef4ffdf9b145875178519a471eedd8f273ae",
    versionAnchorUrl: "https://github.com/jeertmans/manim-slides/commit/1549ef4ffdf9b145875178519a471eedd8f273ae",
    claimEvidenceUrls: [
      "https://github.com/jeertmans/manim-slides",
      "https://github.com/jeertmans/manim-slides/releases/tag/v5.6.0",
      "https://github.com/jeertmans/manim-slides/blob/1549ef4ffdf9b145875178519a471eedd8f273ae/docs/source/reference/sharing.md",
      "https://manim-slides.eertmans.be/latest/features_table.html",
      "https://manim-slides.eertmans.be/latest/reference/sharing.html",
    ],
    licenseOrRights: "MIT License; generated course slides and the course's own scene code remain separate original assets.",
    licenseOrRightsZhHans: "MIT 许可证；课程生成的幻灯片与课程自有场景代码均为独立原创资产。",
    licenseUrl: "https://github.com/jeertmans/manim-slides/blob/1549ef4ffdf9b145875178519a471eedd8f273ae/LICENSE.md",
    supports: "Adds slide boundaries, presenter control, RevealJS HTML, offline single-file export, experimental PPTX, and a static PDF backup that loses animation.",
    supportsZhHans: "为现有 Manim 场景添加幻灯片边界、演示控制、RevealJS、离线单文件、实验性 PPTX，以及会丢失动画的静态 PDF 备份。",
    boundary: "It is an extension, not a standalone mathematical animation engine. PPTX support is experimental with uncertain PowerPoint or LibreOffice compatibility, while PDF is static; the selected Manim dependency still controls scene compatibility.",
    boundaryZhHans: "它是扩展而不是独立数学动画引擎。PPTX 仍属实验功能，PowerPoint 或 LibreOffice 兼容范围不确定；PDF 只有静态备份，场景兼容性仍由所选 Manim 依赖决定。",
  },
  {
    id: "github-manim-voiceover",
    title: "Manim Voiceover",
    publisher: "Manim Community Developers",
    url: "https://github.com/ManimCommunity/manim-voiceover",
    kind: "github-repository",
    role: "core-implementation",
    accessedOn: "2026-08-26",
    versionOrRevision: "v0.4.0; commit 3dc0d95d2f1d9d0937872b3dd68c7b38c4dfc96a",
    versionAnchorUrl: "https://github.com/ManimCommunity/manim-voiceover/commit/3dc0d95d2f1d9d0937872b3dd68c7b38c4dfc96a",
    claimEvidenceUrls: [
      "https://github.com/ManimCommunity/manim-voiceover",
      "https://github.com/ManimCommunity/manim-voiceover/commit/3dc0d95d2f1d9d0937872b3dd68c7b38c4dfc96a",
      "https://github.com/ManimCommunity/manim-voiceover/releases/tag/v0.4.0",
    ],
    licenseOrRights: "MIT License; provider terms, generated voices, recordings, and credentials require separate rights and privacy review.",
    licenseOrRightsZhHans: "MIT 许可证；服务提供商条款、生成语音、录音与凭据仍须单独进行权利和隐私审查。",
    licenseUrl: "https://github.com/ManimCommunity/manim-voiceover/blob/3dc0d95d2f1d9d0937872b3dd68c7b38c4dfc96a/LICENSE",
    supports: "Adds recorded or generated narration, timing trackers, and optional word-level alignment to an existing Manim Community production workflow.",
    supportsZhHans: "为现有 Manim Community 制作流程加入录音或生成旁白、时间追踪与可选逐词同步。",
    boundary: "It remains an alpha extension. Provider credentials, SoX, audio capture, transcription, cost, consent, and voice rights are outside the core install.",
    boundaryZhHans: "它仍是 alpha 扩展。provider 凭据、SoX、录音、转录、费用、同意与声音权利都不属于核心安装。",
  },
  {
    id: "github-motion-canvas",
    title: "Motion Canvas",
    publisher: "Motion Canvas",
    url: "https://github.com/motion-canvas/motion-canvas",
    kind: "github-repository",
    role: "core-implementation",
    accessedOn: "2026-08-26",
    versionOrRevision: "scaffold 3.17.2; commit 7b91435c301d530351dcf5ebb91dd139c002e405",
    versionAnchorUrl: "https://github.com/motion-canvas/motion-canvas/commit/7b91435c301d530351dcf5ebb91dd139c002e405",
    claimEvidenceUrls: [
      "https://github.com/motion-canvas/motion-canvas",
      "https://motioncanvas.io/docs/quickstart/",
      "https://motioncanvas.io/docs/rendering/",
    ],
    licenseOrRights: "MIT License; course TypeScript examples are original and do not copy project showcase media.",
    licenseOrRightsZhHans: "MIT 许可证；课程 TypeScript 示例为原创，未复制项目展示媒体。",
    licenseUrl: "https://github.com/motion-canvas/motion-canvas/blob/7b91435c301d530351dcf5ebb91dd139c002e405/LICENSE",
    supports: "TypeScript generator scenes, a browser editor, deterministic timelines, vector animation, built-in MathJax-based LaTeX nodes, and image or FFmpeg export paths.",
    supportsZhHans: "支持 TypeScript 生成器场景、浏览器编辑器、确定时间轴、矢量动画、基于 MathJax 的公式节点与导出流程。",
    boundary: "It is not a math-specific engine. The tested 3.17.2 scaffold built, but current main failed a monorepo build and both dependency sets reported security advisories.",
    boundaryZhHans: "它不是数学专用引擎。实测 3.17.2 脚手架可构建，但当前 main 的 monorepo 构建失败，两套依赖也报告安全告警。",
  },
  {
    id: "docs-motion-canvas-quickstart",
    title: "Motion Canvas quickstart and rendering guides",
    publisher: "Motion Canvas",
    url: "https://motioncanvas.io/docs/quickstart/",
    kind: "official-documentation",
    role: "core-implementation",
    accessedOn: "2026-08-26",
    versionOrRevision: "live documentation snapshot; scaffold resolved to 3.17.2",
    claimEvidenceUrls: [
      "https://motioncanvas.io/docs/quickstart/",
      "https://motioncanvas.io/docs/rendering/",
      "https://motioncanvas.io/docs/rendering/video/",
    ],
    licenseOrRights: "Documentation is linked for instruction; the course does not redistribute documentation prose or showcase media.",
    licenseOrRightsZhHans: "仅链接文档用于教学；课程不再分发文档正文或项目展示媒体。",
    supports: "Controls the current scaffold, TypeScript generator, preview, image sequence, and FFmpeg exporter claims used in the browser-native module.",
    supportsZhHans: "控制网页原生模块所用的脚手架、TypeScript 生成器、预览、图像序列与 FFmpeg 导出声明。",
    boundary: "The documentation is live and may describe a version newer than the tested scaffold. Browser preview success does not establish final video export success.",
    boundaryZhHans: "在线文档可能描述比实测脚手架更新的版本，浏览器预览成功也不能证明最终视频导出成功。",
  },
  {
    id: "github-remotion",
    title: "Remotion",
    publisher: "Remotion",
    url: "https://github.com/remotion-dev/remotion",
    kind: "github-repository",
    role: "core-implementation",
    accessedOn: "2026-08-26",
    versionOrRevision: "v4.0.517; commit 7aee2f4b3d5c05c77761f2dc6ec5aeac701dcce8",
    versionAnchorUrl: "https://github.com/remotion-dev/remotion/commit/7aee2f4b3d5c05c77761f2dc6ec5aeac701dcce8",
    claimEvidenceUrls: [
      "https://github.com/remotion-dev/remotion",
      "https://github.com/remotion-dev/remotion/releases/tag/v4.0.517",
      "https://www.remotion.dev/docs/encoding",
      "https://www.remotion.dev/docs/player",
      "https://www.remotion.dev/docs/ai/skills",
    ],
    licenseOrRights: "Custom Remotion License. At the pinned revision, individuals, for-profit organizations with up to three employees, nonprofits or not-for-profits, and noncommercial evaluators qualify for free use; all other entities require a Company License.",
    licenseOrRightsZhHans: "Remotion 自定义许可证。固定修订的免费资格包括个人、员工不超过 3 人的营利组织、非营利组织及非商业评估者；其他主体须取得 Company License。",
    licenseUrl: "https://github.com/remotion-dev/remotion/blob/7aee2f4b3d5c05c77761f2dc6ec5aeac701dcce8/LICENSE.md",
    supports: "Agent-readable React video composition with Studio preview, broad codecs, media assembly, Player embedding, and documented skills for Codex and Claude Code.",
    supportsZhHans: "提供适合代理维护的 React 视频合成、Studio 预览、多种编码、媒体装配、Player 嵌入，以及 Codex 与 Claude Code skills。",
    boundary: "It is not a semantic mathematics engine and does not use a universal MIT license. Formula tokens, geometry, invariants, and commercial rights need separate handling.",
    boundaryZhHans: "它不是带语义的数学引擎，也不是通用 MIT 许可。公式 token、几何、不变量与商业权利必须另行处理。",
  },
  {
    id: "github-remotion-skills",
    title: "Remotion Agent Skills",
    publisher: "Remotion",
    url: "https://github.com/remotion-dev/skills",
    kind: "github-repository",
    role: "workflow",
    accessedOn: "2026-08-26",
    versionOrRevision: "commit 7c5c10caa5294d01b168a08c9648b4deef717274",
    versionAnchorUrl: "https://github.com/remotion-dev/skills/tree/7c5c10caa5294d01b168a08c9648b4deef717274",
    claimEvidenceUrls: [
      "https://github.com/remotion-dev/skills",
      "https://www.remotion.dev/docs/ai/skills",
    ],
    licenseOrRights: "No standalone LICENSE file or package license declaration was found at the pinned revision; link or install only after code and rights review.",
    licenseOrRightsZhHans: "固定修订未发现独立 LICENSE 文件或包级许可证声明；仅在完成代码与权利审查后链接或安装。",
    supports: "Provides current Remotion-specific Agent Skills and installation guidance that explicitly includes Claude Code, Codex, and other coding agents.",
    supportsZhHans: "提供当前 Remotion 专用 Agent Skills 与安装说明，明确列出 Claude Code、Codex 等编码代理。",
    boundary: "Skill availability is not mathematical validation. Its absent standalone license means the course links to it but does not copy or redistribute the skill package.",
    boundaryZhHans: "Skill 可用不等于数学已验证；独立许可证缺失，因此课程只链接，不复制或再分发该 skill 包。",
  },
  {
    id: "github-mafs",
    title: "Mafs",
    publisher: "Steven Petryk and contributors",
    url: "https://github.com/stevenpetryk/mafs",
    kind: "github-repository",
    role: "core-implementation",
    accessedOn: "2026-08-26",
    versionOrRevision: "v0.21.0; commit e74a3ef465f4ddc98704814d2ae18b73a6cd9dae",
    versionAnchorUrl: "https://github.com/stevenpetryk/mafs/commit/e74a3ef465f4ddc98704814d2ae18b73a6cd9dae",
    claimEvidenceUrls: [
      "https://github.com/stevenpetryk/mafs",
      "https://github.com/stevenpetryk/mafs/releases/tag/v0.21.0",
    ],
    licenseOrRights: "MIT License; course interaction code is original and no project examples are redistributed.",
    licenseOrRightsZhHans: "MIT 许可证；课程交互代码为原创，不再分发项目示例。",
    licenseUrl: "https://github.com/stevenpetryk/mafs/blob/e74a3ef465f4ddc98704814d2ae18b73a6cd9dae/LICENSE",
    supports: "React and TypeScript mathematical interaction components with coordinates, plots, vectors, gestures, and a testable browser integration surface.",
    supportsZhHans: "提供 React 与 TypeScript 数学交互组件，包括坐标、函数图、向量、手势与可测试网页集成。",
    boundary: "It is an interactive companion rather than a video renderer. Its tagged release and default-branch activity lag behind the core course engines.",
    boundaryZhHans: "它是交互配套组件而非视频渲染器，tag 与默认分支活动也落后于课程核心引擎。",
  },
  {
    id: "github-jsxgraph",
    title: "JSXGraph",
    publisher: "JSXGraph contributors",
    url: "https://github.com/jsxgraph/jsxgraph",
    kind: "github-repository",
    role: "core-implementation",
    accessedOn: "2026-08-26",
    versionOrRevision: "v1.13.2; commit 02b2fd492dcc4249d0ab5d24b98d427788f2ab1e",
    versionAnchorUrl: "https://github.com/jsxgraph/jsxgraph/releases/tag/v1.13.2",
    claimEvidenceUrls: [
      "https://github.com/jsxgraph/jsxgraph",
      "https://github.com/jsxgraph/jsxgraph/releases/tag/v1.13.2",
    ],
    licenseOrRights: "Dual licensed under MIT OR LGPL-3.0-or-later; adopters must choose and comply with the selected license path.",
    licenseOrRightsZhHans: "可选择 MIT 或 LGPL-3.0-or-later 许可证；采用者须选定并遵守其中一条许可路径。",
    licenseUrl: "https://github.com/jsxgraph/jsxgraph/blob/02b2fd492dcc4249d0ab5d24b98d427788f2ab1e/README.md#license",
    supports: "A maintained browser mathematics system for dynamic geometry, functions, charts, 2D and 3D views, touch interaction, keyboard access, SVG, and Canvas.",
    supportsZhHans: "持续维护的网页数学系统，支持动态几何、函数、图表、2D 与 3D、触控、键盘、SVG 与 Canvas。",
    boundary: "It does not provide an authored video timeline or native media encoding. Video output requires a separate capture or composition pipeline and an explicit MIT or LGPL-3.0-or-later license choice.",
    boundaryZhHans: "它不提供作者控制的视频时间轴或原生媒体编码；视频输出需要额外捕获或合成管线，并且必须明确选择 MIT 或 LGPL-3.0-or-later 许可路径。",
  },
  {
    id: "openai-codex-use-cases",
    title: "Codex project instructions, subagents, review, skills, and worktrees",
    publisher: "OpenAI",
    url: "https://learn.chatgpt.com/docs/agent-configuration/agents-md",
    kind: "official-documentation",
    role: "workflow",
    accessedOn: "2026-08-26",
    versionOrRevision: "live official documentation snapshot 2026-08-26",
    claimEvidenceUrls: [
      "https://learn.chatgpt.com/docs/agent-configuration/agents-md",
      "https://learn.chatgpt.com/docs/agent-configuration/subagents",
      "https://learn.chatgpt.com/docs/code-review",
      "https://learn.chatgpt.com/docs/build-skills",
      "https://learn.chatgpt.com/docs/environments/git-worktrees",
      "https://learn.chatgpt.com/use-cases/iterate-on-difficult-problems",
    ],
    licenseOrRights: "Official product documentation linked for current workflow guidance; no documentation prose is redistributed.",
    licenseOrRightsZhHans: "仅链接官方产品文档用于当前工作流指导；不再分发文档正文。",
    supports: "Supports repository-grounded Codex workflows for starting projects, implementing changes, inspecting work, and using goals or parallel work where appropriate.",
    supportsZhHans: "支持基于仓库的 Codex 项目启动、改动实现、工作检查，以及在合适时使用目标或并行工作的流程。",
    boundary: "It does not document a native Manim integration or establish that Codex output is mathematically correct without project-level tests and review.",
    boundaryZhHans: "它没有说明原生 Manim 集成，也不能在缺少项目测试与审核时证明 Codex 输出数学正确。",
  },
  {
    id: "openai-model-guidance",
    title: "OpenAI latest model guidance",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/latest-model",
    kind: "official-documentation",
    role: "workflow",
    accessedOn: "2026-08-26",
    versionOrRevision: "live official documentation snapshot 2026-08-26",
    claimEvidenceUrls: ["https://developers.openai.com/api/docs/guides/latest-model"],
    licenseOrRights: "Official documentation linked to ground task-contract and verification guidance; no model output is treated as source evidence.",
    licenseOrRightsZhHans: "仅链接官方文档作为任务契约与验证指导依据；不把模型输出视为来源证据。",
    supports: "Provides current official guidance for instructing and evaluating OpenAI models without binding the course to an undocumented model-specific trick.",
    supportsZhHans: "提供当前 OpenAI 官方的指令与评估指南，使课程不依赖未经文档支持的模型技巧。",
    boundary: "Model and prompting guidance can change. It cannot replace repository instructions, deterministic tests, rendered-frame inspection, or domain-expert review.",
    boundaryZhHans: "模型与提示指南会变化，不能代替仓库说明、确定性测试、关键帧检查与领域专家审核。",
  },
  {
    id: "anthropic-claude-code-overview",
    title: "Claude Code quickstart and best practices",
    publisher: "Anthropic",
    url: "https://code.claude.com/docs/en/quickstart",
    kind: "official-documentation",
    role: "workflow",
    accessedOn: "2026-08-26",
    versionOrRevision: "live official documentation snapshot 2026-08-26",
    claimEvidenceUrls: [
      "https://code.claude.com/docs/en/quickstart",
      "https://code.claude.com/docs/en/best-practices",
      "https://code.claude.com/docs/en/sub-agents",
    ],
    licenseOrRights: "Official product documentation linked for current workflow guidance; no documentation copy or brand media is redistributed.",
    licenseOrRightsZhHans: "仅链接官方产品文档用于当前工作流指导；不再分发文档副本或品牌媒体。",
    supports: "Supports repository exploration, concrete tasks, plan and implement loops, independent review, tests, builds, and screenshot-based verification in Claude Code.",
    supportsZhHans: "支持 Claude Code 中的仓库探索、具体任务、规划与实现循环、独立审核、测试、构建与截图验证。",
    boundary: "Anthropic does not document a native Manim integration. The course describes Claude generating and reviewing external Manim code, not an official Manim feature.",
    boundaryZhHans: "Anthropic 没有记录原生 Manim 集成。课程描述的是 Claude 生成和审核外部 Manim 代码，不是官方 Manim 功能。",
  },
  {
    id: "anthropic-claude-memory",
    title: "Claude Code memory and skills",
    publisher: "Anthropic",
    url: "https://code.claude.com/docs/en/memory",
    kind: "official-documentation",
    role: "workflow",
    accessedOn: "2026-08-26",
    versionOrRevision: "live official documentation snapshot 2026-08-26",
    claimEvidenceUrls: [
      "https://code.claude.com/docs/en/memory",
      "https://code.claude.com/docs/en/skills",
      "https://www.anthropic.com/engineering/equipping-agents-for-the-real-world-with-agent-skills",
    ],
    licenseOrRights: "Official documentation and engineering guidance are linked; third-party skills remain subject to their own code and rights audit.",
    licenseOrRightsZhHans: "仅链接官方文档与工程指南；第三方 skills 仍须分别审计其代码与权利。",
    supports: "Controls claims about CLAUDE.md project context, reusable skills, progressive loading, deterministic scripts, evaluation, and third-party skill review.",
    supportsZhHans: "控制 CLAUDE.md 项目上下文、可复用 skill、渐进加载、确定性脚本、评估与第三方 skill 审核等声明。",
    boundary: "Natural-language project instructions are context, not enforcement. Hard mathematical and release guarantees must still live in tests, scripts, and review gates.",
    boundaryZhHans: "自然语言项目说明是上下文而不是强制机制，数学与发布硬保证仍须由测试、脚本与审核门槛承担。",
  },
  {
    id: "x-remotion-agent-skills",
    title: "Remotion announces Agent Skills",
    publisher: "Remotion on X",
    url: "https://x.com/Remotion/status/2013626968386765291",
    kind: "x-post",
    role: "discovery-signal",
    accessedOn: "2026-08-26",
    versionOrRevision: "post 2013626968386765291; published 2026-01-20 UTC",
    claimEvidenceUrls: ["https://x.com/Remotion/status/2013626968386765291"],
    licenseOrRights: "Linked social post only. The post media is not embedded, downloaded, or redistributed in the course.",
    licenseOrRightsZhHans: "仅链接社交帖子；课程不嵌入、下载或再分发帖子媒体。",
    supports: "A dated official announcement that Remotion Agent Skills can be installed and used in a Claude Code video workflow, corroborated by the current skills repository.",
    supportsZhHans: "有日期的官方公告，说明 Remotion Agent Skills 可安装并用于 Claude Code 视频工作流，且当前 skills 仓库能够交叉核验。",
    boundary: "It is a workflow announcement, not a mathematical animation case, compatibility guarantee for every agent, license grant, or evidence of learning effectiveness.",
    boundaryZhHans: "它是工作流公告，不是数学动画案例，也不能证明所有代理兼容、授予许可证或证明学习效果。",
  },
  {
    id: "x-minchoi-claude-manim",
    title: "Claude 3 and a Manim neural-network animation",
    publisher: "Min Choi on X",
    url: "https://x.com/minchoi/status/1770105075043647495",
    kind: "x-post",
    role: "discovery-signal",
    accessedOn: "2026-08-26",
    versionOrRevision: "post 1770105075043647495; published 2024-03-19 UTC",
    claimEvidenceUrls: ["https://x.com/minchoi/status/1770105075043647495"],
    licenseOrRights: "Linked creator post only. The attached video is not embedded, downloaded, or reused in the course.",
    licenseOrRightsZhHans: "仅链接创作者帖子；课程不嵌入、下载或复用所附视频。",
    supports: "The verified post text records a creator claiming to use Claude 3 to generate a Manim animation explaining a neural-network architecture.",
    supportsZhHans: "经核验的帖子正文记录了创作者声称使用 Claude 3 生成解释神经网络结构的 Manim 动画。",
    boundary: "The original prompt and code were not independently reproduced. The post does not prove mathematical accuracy, pedagogy, full model authorship, or native Anthropic integration.",
    boundaryZhHans: "原始提示与代码未独立复现，帖子不能证明数学准确、教学效果、完全由模型生成或 Anthropic 原生集成。",
  },
  {
    id: "x-cintas-claude-pythagoras",
    title: "Claude 3 and a Pythagorean-theorem animation",
    publisher: "Alvaro Cintas on X",
    url: "https://x.com/dr_cintas/status/1767569938217087199",
    kind: "x-post",
    role: "discovery-signal",
    accessedOn: "2026-08-26",
    versionOrRevision: "post 1767569938217087199; published 2024-03-12 UTC",
    claimEvidenceUrls: ["https://x.com/dr_cintas/status/1767569938217087199"],
    licenseOrRights: "Linked creator post only. The attached video is not embedded, downloaded, or reused in the course.",
    licenseOrRightsZhHans: "仅链接创作者帖子；课程不嵌入、下载或复用所附视频。",
    supports: "The verified post text records a creator claiming to ask Claude 3 for an animation explaining the Pythagorean theorem and attaching the result.",
    supportsZhHans: "经核验的帖子正文记录了创作者要求 Claude 3 制作勾股定理解释动画，并附上结果。",
    boundary: "No complete prompt or source code accompanies the post. It is a motivation example, not a reproducible tutorial or mathematical correctness record.",
    boundaryZhHans: "帖子没有完整提示或源码，只适合作为动机案例，不能作为可复现教程或数学正确记录。",
  },
  {
    id: "x-dhruv-math-animation-thread",
    title: "Claude 3 mathematical-animation examples",
    publisher: "Dhruv on X",
    url: "https://x.com/_dhruvvvvv_/status/1770019681749049840",
    kind: "x-post",
    role: "discovery-signal",
    accessedOn: "2026-08-26",
    versionOrRevision: "thread posts published 2024-03-19 UTC",
    claimEvidenceUrls: [
      "https://x.com/_dhruvvvvv_/status/1770019681749049840",
      "https://x.com/_dhruvvvvv_/status/1770020014600695986",
      "https://x.com/_dhruvvvvv_/status/1770020691179634794",
      "https://x.com/_dhruvvvvv_/status/1770021078087389628",
    ],
    licenseOrRights: "Linked creator posts only. The attached media is not embedded, downloaded, or redistributed in the course.",
    licenseOrRightsZhHans: "仅链接创作者帖子；课程不嵌入、下载或再分发所附媒体。",
    supports: "Verified post text identifies Claude 3 math-animation attempts involving a sphere theorem, distance formula, and Riemann sums, including reference-image prompting signals.",
    supportsZhHans: "经核验的正文记录 Claude 3 数学动画尝试，涉及球面定理、距离公式与黎曼和，并出现参考图像提示信号。",
    boundary: "The posts do not prove accuracy or reproducibility. The author's phrase about Manim support is not evidence that Anthropic shipped an official native integration.",
    boundaryZhHans: "帖子不能证明准确或可复现；作者所说的 Manim 支持也不能证明 Anthropic 发布了官方原生集成。",
  },
  {
    id: "x-tobi-manim-skill",
    title: "A /manim_video skill example in another agent system",
    publisher: "Tobi Lütke on X",
    url: "https://x.com/tobi/status/2041719844920283326",
    kind: "x-post",
    role: "discovery-signal",
    accessedOn: "2026-08-26",
    versionOrRevision: "post 2041719844920283326; published 2026-04-08 UTC",
    claimEvidenceUrls: ["https://x.com/tobi/status/2041719844920283326"],
    licenseOrRights: "Linked creator post only. The attached video and third-party skill are not copied or redistributed.",
    licenseOrRightsZhHans: "仅链接创作者帖子；不复制或再分发所附视频及第三方 skill。",
    supports: "A dated example of packaging a Manim video workflow as a reusable domain skill, useful for comparing one prompt, project instructions, and a reusable skill.",
    supportsZhHans: "有日期的案例，把 Manim 视频工作流包装成可复用领域 skill，可用于比较单次提示、项目说明与 skill 三个层级。",
    boundary: "The example uses Hermes Agent, not Codex or Claude. It supports the cross-agent architecture idea but establishes no capability claim for either course agent.",
    boundaryZhHans: "该案例使用 Hermes Agent，而不是 Codex 或 Claude，只能支持跨代理架构思路，不能证明课程代理能力。",
  },
  {
    id: "w3c-animation-interactions",
    title: "Understanding Success Criterion 2.3.3: Animation from Interactions",
    publisher: "W3C Web Accessibility Initiative",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/animation-from-interactions.html",
    kind: "web-standard",
    role: "quality-boundary",
    accessedOn: "2026-08-26",
    versionOrRevision: "WCAG 2.2 SC 2.3.3 Level AAA informative understanding document snapshot 2026-08-26",
    claimEvidenceUrls: [
      "https://www.w3.org/WAI/WCAG22/Understanding/animation-from-interactions.html",
      "https://www.w3.org/TR/mediaqueries-5/",
    ],
    licenseOrRights: "Public web standard and explanatory document linked for accessibility guidance; course visuals are original.",
    licenseOrRightsZhHans: "仅链接 W3C 规范与解释性文档用于无障碍指导；课程视觉素材为原创。",
    supports: "SC 2.3.3 at Level AAA requires a way to disable nonessential interaction-triggered motion and supports the reduced-motion media-query implementation boundary.",
    supportsZhHans: "WCAG 2.2 的 AAA 级 SC 2.3.3 要求可关闭非必要的交互动效，并为 reduced-motion 媒体查询实现提供标准边界。",
    boundary: "The Understanding page is informative rather than normative, and Level AAA is not an A or AA requirement. This criterion is not a complete animation-accessibility checklist; captions, transcripts, contrast, keyboard access, and equivalent learning content require additional review.",
    boundaryZhHans: "Understanding 页面属于解释性资料而非规范正文，AAA 级也不是 A 或 AA 的要求。该准则并非完整动画无障碍清单；字幕、transcript、对比度、键盘与等价学习内容仍需额外审核。",
  },
  {
    id: "ffmpeg-general",
    title: "FFmpeg general documentation",
    publisher: "FFmpeg Project",
    url: "https://www.ffmpeg.org/general.html",
    kind: "official-documentation",
    role: "quality-boundary",
    accessedOn: "2026-08-26",
    versionOrRevision: "FFmpeg 8.1.1 local binary; live documentation snapshot 2026-08-26",
    claimEvidenceUrls: [
      "https://www.ffmpeg.org/general.html",
      "https://ffmpeg.org/ffprobe.html",
    ],
    licenseOrRights: "Official technical documentation linked for media inspection; generated course commands and reports are original.",
    licenseOrRightsZhHans: "仅链接官方技术文档用于媒体检查；课程生成的命令与报告为原创。",
    supports: "Grounds frame-sequence encoding and final-media inspection of duration, codecs, frame rate, dimensions, and streams through FFmpeg and ffprobe.",
    supportsZhHans: "支持通过 FFmpeg 与 ffprobe 编码帧序列，并检查最终媒体的时长、编码、帧率、尺寸与媒体流。",
    boundary: "Media probing proves properties of the file, not the mathematical correctness, pedagogical clarity, accessibility, or rights status of its contents.",
    boundaryZhHans: "媒体探测只证明文件属性，不能证明内容的数学正确、教学清晰、无障碍或权利状态。",
  },
] as const satisfies readonly MathAnimationSourceRecord[];

export const MATH_ANIMATION_REPOSITORIES = [
  {
    sourceId: "github-manim-ce",
    verdict: "core",
    score: 95,
    breakdown: { mathSemantics: 20, deterministicTimeline: 15, agentReadable: 14, iterationPreview: 8, renderOutput: 10, maintenance: 10, licenseClarity: 10, accessibility: 3, ecosystem: 5 },
    bestFor: "The default route for semantic equations, graphs, geometry, transformations, and reproducible mathematical video.",
    bestForZhHans: "制作带语义的公式、函数图像、几何、变换与可复现数学视频的默认路线。",
    primaryLimit: "Native Cairo, Pango, FFmpeg, and formula-toolchain setup adds environment cost; 0.x APIs still require a pin.",
    primaryLimitZhHans: "Cairo、Pango、FFmpeg 与公式工具链带来原生环境成本；0.x API 仍必须固定版本。",
    testedRevision: "1dc796e9652273950d9863b35746c7329888e384",
    smokeStatus: "rendered",
    smokeEvidence: "v0.21.0 rendered SquareToCircle to a 3.000 s H.264 MP4 at 854x480 and 15 fps; a separate MathTex stress scene was correctly blocked by the missing latex binary.",
    smokeEvidenceZhHans: "v0.21.0 已把 SquareToCircle 渲染为 3.000 秒、854×480、15 fps 的 H.264 MP4；单独的 MathTex 压力场景因缺少 latex 二进制文件而如实受阻。",
    adoptionSnapshot: { stars: 40459, defaultBranchHeadDate: "2026-08-25", latestRelease: "v0.21.0", latestReleasePublishedOn: "2026-08-10", capturedOn: "2026-08-26" },
  },
  {
    sourceId: "github-manimgl",
    verdict: "advanced",
    score: 87,
    breakdown: { mathSemantics: 20, deterministicTimeline: 15, agentReadable: 10, iterationPreview: 9, renderOutput: 10, maintenance: 7, licenseClarity: 10, accessibility: 2, ecosystem: 4 },
    bestFor: "Advanced study of the 3Blue1Brown production lineage, OpenGL scenes, presenter mode, interactive development, and camera craft.",
    bestForZhHans: "进阶研究 3Blue1Brown 制作体系、OpenGL 场景、演示模式、交互开发与镜头语言。",
    primaryLimit: "Commands and APIs are incompatible with Manim Community, the tagged release is older, and historical video scenes may drift.",
    primaryLimitZhHans: "命令与 API 不兼容 Manim Community；已发布版本较旧，历史视频场景可能发生漂移。",
    testedRevision: "9d57bcf9edea2486f214e190931de2a5537f23c1",
    smokeStatus: "rendered",
    smokeEvidence: "v1.7.2 installed in an isolated Python 3.12 environment and rendered a two-animation SmokeCircle scene to a 2.000 s H.264 MP4 at 854x480 and 30 fps.",
    smokeEvidenceZhHans: "v1.7.2 已安装到隔离的 Python 3.12 环境，并把含两个动画的 SmokeCircle 场景渲染为 2.000 秒、854×480、30 fps 的 H.264 MP4。",
    adoptionSnapshot: { stars: 92037, defaultBranchHeadDate: "2026-08-18", latestRelease: "v1.7.2", latestReleasePublishedOn: "2024-12-13", capturedOn: "2026-08-26" },
  },
  {
    sourceId: "github-manim-slides",
    verdict: "extension",
    score: 84,
    breakdown: { mathSemantics: 16, deterministicTimeline: 13, agentReadable: 11, iterationPreview: 10, renderOutput: 9, maintenance: 9, licenseClarity: 10, accessibility: 3, ecosystem: 3 },
    bestFor: "Turning a verified Manim scene into a paced classroom presentation or offline RevealJS file, with experimental PPTX and static PDF only as secondary delivery paths.",
    bestForZhHans: "把已验证的 Manim 场景转成有节奏的课堂演示或离线 RevealJS 文件；实验性 PPTX 与静态 PDF 仅作为次要交付路径。",
    primaryLimit: "It depends on Manim Community or ManimGL and cannot replace the underlying scene engine. PPTX compatibility is experimental and uncertain, while PDF output is static and loses animation.",
    primaryLimitZhHans: "它依赖 Manim Community 或 ManimGL，不能替代底层场景引擎；PPTX 兼容性仍属实验且不确定，PDF 则为会丢失动画的静态输出。",
    testedRevision: "1549ef4ffdf9b145875178519a471eedd8f273ae",
    smokeStatus: "rendered",
    smokeEvidence: "v5.6.0 rendered BasicExample with three slides, wrote slide JSON and MP4, then converted it to an 868 KB self-contained offline RevealJS HTML file.",
    smokeEvidenceZhHans: "v5.6.0 已渲染含三张幻灯片的 BasicExample，生成 slide JSON 与 MP4，并转换成 868 KB 的自包含离线 RevealJS HTML。",
    adoptionSnapshot: { stars: 920, defaultBranchHeadDate: "2026-08-21", latestRelease: "v5.6.0", latestReleasePublishedOn: "2026-04-15", capturedOn: "2026-08-26" },
  },
  {
    sourceId: "github-manim-voiceover",
    verdict: "extension",
    score: 77,
    breakdown: { mathSemantics: 14, deterministicTimeline: 12, agentReadable: 12, iterationPreview: 6, renderOutput: 8, maintenance: 8, licenseClarity: 10, accessibility: 4, ecosystem: 3 },
    bestFor: "Optional narration, timing trackers, transcription, and word-level synchronization after the core mathematical scene passes.",
    bestForZhHans: "核心数学场景通过后，再选择性加入旁白、时间追踪、转录与逐词同步。",
    primaryLimit: "Alpha status plus SoX, capture, transcription, provider credentials, cost, consent, and voice-rights dependencies.",
    primaryLimitZhHans: "仍处于 alpha，并依赖 SoX、录音、转录、provider 凭据、费用、同意与声音权利。",
    testedRevision: "3dc0d95d2f1d9d0937872b3dd68c7b38c4dfc96a",
    smokeStatus: "validated",
    smokeEvidence: "v0.4.0 and VoiceoverScene imported successfully in the shared Manim environment; the check reported missing SoX and deliberately avoided paid or credentialed TTS calls.",
    smokeEvidenceZhHans: "v0.4.0 与 VoiceoverScene 已在共用 Manim 环境成功导入；检查报告缺少 SoX，并刻意没有调用付费或需凭据的 TTS。",
    adoptionSnapshot: { stars: 314, defaultBranchHeadDate: "2026-06-15", latestRelease: "v0.4.0", latestReleasePublishedOn: "2026-06-14", capturedOn: "2026-08-26" },
  },
  {
    sourceId: "github-motion-canvas",
    verdict: "advanced",
    score: 81,
    breakdown: { mathSemantics: 14, deterministicTimeline: 15, agentReadable: 13, iterationPreview: 10, renderOutput: 8, maintenance: 5, licenseClarity: 10, accessibility: 2, ecosystem: 4 },
    bestFor: "TypeScript teams that prioritize browser preview, generator timelines, web integration, and MathJax-based formula rendering.",
    bestForZhHans: "重视浏览器预览、生成器时间轴、网页集成与 MathJax 公式渲染的 TypeScript 团队。",
    primaryLimit: "Not math-specific; release drift and dependency advisories require review, and the tested current monorepo did not complete its full build.",
    primaryLimitZhHans: "不是数学专用引擎；release 漂移与依赖告警需要审核，实测当前 monorepo 也未完成完整构建。",
    testedRevision: "7b91435c301d530351dcf5ebb91dd139c002e405",
    smokeStatus: "validated",
    smokeEvidence: "The included synchronized unit-circle and sine scene type-checked and built inside a fresh official 3.17.2 scaffold, whose Vite build transformed 1084 modules; no final video export is claimed, while current main separately failed 2d:build.",
    smokeEvidenceZhHans: "课程所含单位圆与正弦同步场景已在全新官方 3.17.2 脚手架中通过类型检查与构建，Vite 转换 1084 个模块；未宣称完成最终视频导出，当前 main 的 2d:build 则另行失败。",
    adoptionSnapshot: { stars: 19005, defaultBranchHeadDate: "2026-07-02", latestRelease: "v3.17.2", latestReleasePublishedOn: "2024-12-14", capturedOn: "2026-08-26" },
  },
  {
    sourceId: "github-remotion",
    verdict: "extension",
    score: 80,
    breakdown: { mathSemantics: 8, deterministicTimeline: 15, agentReadable: 15, iterationPreview: 10, renderOutput: 10, maintenance: 10, licenseClarity: 4, accessibility: 3, ecosystem: 5 },
    bestFor: "Agent-native React post-production, captions, audio, titles, multiple aspect ratios, product embedding, and broad final encoding.",
    bestForZhHans: "适合代理维护的 React 后期制作、字幕、音频、标题、多画幅、产品嵌入与广泛最终编码。",
    primaryLimit: "It lacks semantic mathematics and uses a custom commercial license that requires organization-specific review.",
    primaryLimitZhHans: "缺少数学语义层，并采用需要按组织情境审核的自定义商业许可证。",
    testedRevision: "7aee2f4b3d5c05c77761f2dc6ec5aeac701dcce8",
    smokeStatus: "rendered",
    smokeEvidence: "v4.0.517 scaffold installation, lint, type check, bundle, and render succeeded, producing a 60-frame H.264 plus AAC MP4 at 1280x720 and 30 fps after a documented browser download.",
    smokeEvidenceZhHans: "v4.0.517 脚手架的安装、lint、类型检查、打包与渲染均通过；在记录浏览器下载副作用后，生成 60 帧、1280×720、30 fps 的 H.264 + AAC MP4。",
    adoptionSnapshot: { stars: 57328, defaultBranchHeadDate: "2026-08-25", latestRelease: "v4.0.517", latestReleasePublishedOn: "2026-08-25", capturedOn: "2026-08-26" },
  },
  {
    sourceId: "github-remotion-skills",
    verdict: "extension",
    score: 35,
    breakdown: { mathSemantics: 2, deterministicTimeline: 4, agentReadable: 15, iterationPreview: 0, renderOutput: 0, maintenance: 8, licenseClarity: 2, accessibility: 1, ecosystem: 3 },
    bestFor: "Reusable Remotion instructions and task patterns for Claude Code, Codex, Cursor, and other coding agents.",
    bestForZhHans: "为 Claude Code、Codex、Cursor 等编码代理提供可复用的 Remotion 说明与任务模式。",
    primaryLimit: "It is guidance rather than a renderer, and no standalone repository license was found at the pinned revision.",
    primaryLimitZhHans: "它是工作流说明而非渲染器，且固定版本中没有找到独立仓库许可证。",
    testedRevision: "7c5c10caa5294d01b168a08c9648b4deef717274",
    smokeStatus: "validated",
    smokeEvidence: "The current README and official Remotion Agent Skills documentation were cross-checked at the pinned commit; the support list includes Codex, but the package was not copied because standalone redistribution rights were not found.",
    smokeEvidenceZhHans: "已在固定提交交叉核对当前 README 与官方 Remotion Agent Skills 文档；支持列表包含 Codex，但因未找到独立再分发权利而没有复制该包。",
    adoptionSnapshot: { stars: 4409, defaultBranchHeadDate: "2026-08-25", latestRelease: null, latestReleasePublishedOn: null, capturedOn: "2026-08-26" },
  },
  {
    sourceId: "github-mafs",
    verdict: "companion",
    score: 65,
    breakdown: { mathSemantics: 15, deterministicTimeline: 3, agentReadable: 13, iterationPreview: 10, renderOutput: 2, maintenance: 5, licenseClarity: 10, accessibility: 4, ecosystem: 3 },
    bestFor: "Embedding learner-controlled React plots, coordinates, vectors, gestures, and interactive mathematical exploration beside the course.",
    bestForZhHans: "在课程旁嵌入由学习者控制的 React 函数图、坐标、向量、手势与交互数学探索。",
    primaryLimit: "It is not a video timeline or encoder, and its current release and default-branch activity trail the primary engines.",
    primaryLimitZhHans: "它不是视频时间轴或编码器，当前 release 与默认分支活动也落后于主要引擎。",
    testedRevision: "e74a3ef465f4ddc98704814d2ae18b73a6cd9dae",
    smokeStatus: "validated",
    smokeEvidence: "Repository and package contracts were inspected at the pinned commit, including React and Node ranges, TypeScript, unit, Playwright, and visual-regression surfaces; no standalone video render was claimed.",
    smokeEvidenceZhHans: "已在固定提交检查仓库与 package 契约，包括 React/Node 范围、TypeScript、单元测试、Playwright 与视觉回归面；未宣称完成独立视频渲染。",
    adoptionSnapshot: { stars: 3427, defaultBranchHeadDate: "2025-03-30", latestRelease: "v0.21.0", latestReleasePublishedOn: "2024-10-20", capturedOn: "2026-08-26" },
  },
  {
    sourceId: "github-jsxgraph",
    verdict: "companion",
    score: 70,
    breakdown: { mathSemantics: 17, deterministicTimeline: 4, agentReadable: 10, iterationPreview: 10, renderOutput: 2, maintenance: 10, licenseClarity: 9, accessibility: 4, ecosystem: 4 },
    bestFor: "Dynamic geometry, functions, sliders, touch and keyboard interaction, and maintained browser mathematics outside a narrated video timeline.",
    bestForZhHans: "适合动态几何、函数、滑杆、触控与键盘交互，以及叙事视频时间轴之外持续维护的网页数学。",
    primaryLimit: "It needs a separate authoring, capture, or composition pipeline for video and requires an explicit MIT or LGPL-3.0-or-later license choice.",
    primaryLimitZhHans: "视频需要独立的创作、捕获或合成管线，并且必须明确选择 MIT 或 LGPL-3.0-or-later 许可路径。",
    testedRevision: "02b2fd492dcc4249d0ab5d24b98d427788f2ab1e",
    smokeStatus: "validated",
    smokeEvidence: "Repository metadata, current release, dual license, browser capabilities, and accessibility-facing interaction claims were checked at the pinned revision; no native video output was claimed.",
    smokeEvidenceZhHans: "已在固定版本检查仓库元数据、当前 release、双许可证、浏览器能力与无障碍交互声明；未宣称原生视频输出。",
    adoptionSnapshot: { stars: 1427, defaultBranchHeadDate: "2026-08-17", latestRelease: "v1.13.2", latestReleasePublishedOn: "2026-08-17", capturedOn: "2026-08-26" },
  },
] as const satisfies readonly MathAnimationRepositoryEvaluation[];

const SOURCE_BY_ID = new Map<MathAnimationSourceId, MathAnimationSourceRecord>(
  MATH_ANIMATION_SOURCES.map((source) => [source.id, source]),
);

export function getMathAnimationSource(id: MathAnimationSourceId): MathAnimationSourceRecord {
  const source = SOURCE_BY_ID.get(id);
  if (!source) throw new Error(`Unknown math-animation source: ${id}`);
  return source;
}
