import {
  MAKE_MONEY_WITH_CODEX_COURSE_ID,
  MAKE_MONEY_WITH_CODEX_COURSE_VERSION,
  MAKE_MONEY_WITH_CODEX_LEVEL,
  type CodexIncomeCourse,
  type CodexIncomeLesson,
  type CodexIncomeUnit,
} from "./types";

export const MAKE_MONEY_WITH_CODEX_UNITS = [
  {
    id: "value",
    order: 1,
    title: "Value before code",
    summary: "Choose a payer, a costly job, and a narrow offer before asking Codex to build anything.",
    lessonSlugs: ["money-not-magic", "choose-market-wedge", "validate-before-building"],
  },
  {
    id: "pilot",
    order: 2,
    title: "Build a paid pilot",
    summary: "Translate demand into an executable contract, protect client work, and produce a reviewable result.",
    lessonSlugs: ["write-commercial-spec", "protect-client-work", "build-verified-pilot"],
  },
  {
    id: "sell",
    order: 3,
    title: "Price, sell, and deliver",
    summary: "Model the economics, sell with honest proof, and hand off work with clear controls.",
    lessonSlugs: ["price-for-margin", "sell-with-proof", "deliver-with-control"],
  },
  {
    id: "scale",
    order: 4,
    title: "Productise without losing control",
    summary: "Reuse what survived delivery, add responsible recurring work, and launch an evidence-based experiment.",
    lessonSlugs: ["productize-reuse", "retain-and-automate", "launch-capstone"],
  },
] as const satisfies readonly CodexIncomeUnit[];

export const MAKE_MONEY_WITH_CODEX_LESSONS = [
  {
    slug: "money-not-magic",
    order: 1,
    unitId: "value",
    minutes: 35,
    title: "Codex is leverage, not a money button",
    summary: "Build the value chain that sits between an AI task and collected revenue.",
    outcome: "A one-page money map with a named payer, valuable outcome, proof standard, cost boundary, and stop condition.",
    objectives: [
      "Separate Codex capability from demand, distribution, trust, and payment.",
      "Read every case using the course's five evidence classes.",
      "Distinguish gross revenue, contribution margin, profit, and internal time savings.",
    ],
    evidenceClasses: ["commercial-signal", "business-process", "official-workflow", "scope-exclusion"],
    sourceIds: ["academy-builders", "academy-goliath", "academy-contractor-exclusion", "openai-community", "x-este-productivity"],
    sections: [
      {
        eyebrow: "The governing equation",
        heading: "Capacity is only one part of a business",
        body: [
          "Codex can help you investigate a repository, plan work, create software or documents, run checks, and prepare a handoff. Those capabilities can increase production capacity. They do not identify a willing payer, earn trust, create a distribution channel, collect payment, or remove delivery risk.",
          "The commercial chain is: named payer + costly job + credible outcome + safe delivery + proof + distribution + accepted purchase + collected revenue greater than total delivery cost. Model collection risk, refunds, fees, and all delivery obligations separately. If any link is missing, faster production can simply create more unsold work.",
        ],
        bullets: [
          "Customer revenue: cash actually collected for an accepted outcome.",
          "Contribution margin: collected revenue minus payment fees, variable tools, hosting, refunds, and delivery or support labour.",
          "Profit: contribution margin after the remaining overhead and tax obligations relevant to the business.",
          "Internal value: measured capacity or quality improvement. It is not automatically cash savings or revenue.",
        ],
        figureId: "fig-1",
      },
      {
        eyebrow: "Evidence discipline",
        heading: "Read the claim, then read its boundary",
        body: [
          "The strongest commercial source in this course is still a reported case, not audited financial evidence. OpenAI Academy reports that a Goliath Data prospect asked for a $10,000-per-month contract after seeing a tailored feature. The same story gives a company estimate of compute and growth. It does not confirm that the contract was signed, paid, profitable, or typical.",
          "A GitHub repository can prove that an artefact exists. An X post can prove that its author made a statement. A product page can prove that a price is offered. None of those facts alone proves sales or profit. That is why every source card states both what it supports and what it cannot support.",
        ],
        example: {
          label: "Corrected claim",
          title: "From hype to defensible evidence",
          text: "Do not write: 'Codex turned $40 into $120,000.' Write: 'An OpenAI Academy case reports that a prospect requested a $10,000-per-month contract after a tailored feature demo, while the company estimated about $40 of compute. The article does not confirm collected revenue or profit.'",
        },
        warning: "No lesson in this course promises earnings, a passive-income system, or a typical financial return.",
      },
      {
        eyebrow: "Your decision",
        heading: "Define success as evidence, not money theatre",
        body: [
          "Your first success is not a revenue screenshot. It is a small, real-world experiment that can falsify the offer: a payer takes a meeting, supplies a sample input, agrees to acceptance criteria, signs a paid pilot, or declines for a reason you can learn from.",
          "Set a stop condition before you build. Examples include five relevant interviews with no repeated urgent problem, no reachable budget owner, a review burden that erases the margin, or data access that cannot be made lawful and safe.",
        ],
      },
    ],
    practice: {
      id: "practice-money-not-magic",
      lessonSlug: "money-not-magic",
      title: "Draft your money map",
      brief: "Choose one real capability you can responsibly deliver and connect it to a payer and measurable outcome.",
      prompt: "Act as a skeptical offer analyst. I will provide my skills, reachable customers, time budget, and risk limits. Return a table with payer, costly job, current alternative, outcome, acceptance proof, distribution path, delivery cost categories, evidence gaps, and stop condition. Label every number observed, quoted, estimated, or unknown. Do not invent demand or earnings.",
      steps: [
        "List three skills or workflows you can personally review and support.",
        "Name a reachable payer for each, not a generic market persona.",
        "Write one observable result and one credible proof artefact per payer.",
        "Reject any option whose data, legal, safety, or support burden exceeds your authority.",
      ],
      deliverables: ["One selected money map", "Two rejected alternatives with reasons", "One explicit stop condition"],
      guardrail: "Never put real credentials, private client records, or invented revenue numbers into the exercise.",
    },
    checkpoint: {
      question: "Why is a public product built with Codex not evidence of a profitable business?",
      answer: "It can establish that an artefact exists and perhaps that a creator used Codex. Profit additionally requires collected revenue, full costs, support burden, refunds, overhead, and an appropriate time period. Those facts need separate evidence.",
    },
    takeaway: "Codex can increase capacity. Your business still has to earn demand, trust, acceptance, and margin.",
  },
  {
    slug: "choose-market-wedge",
    order: 2,
    unitId: "value",
    minutes: 45,
    title: "Choose a narrow market wedge",
    summary: "Compare service, product, prototype, automation, and maintenance paths using reachable evidence.",
    outcome: "A scored opportunity shortlist and one deliberately narrow monetisation lane.",
    objectives: [
      "Compare seven monetisation lanes without treating any lane as automatically superior.",
      "Score pain, frequency, customer access, budget evidence, review burden, and risk.",
      "Choose a thin wedge that can produce customer evidence quickly.",
    ],
    evidenceClasses: ["official-workflow", "business-process", "paid-offer"],
    sourceIds: ["academy-small-business", "academy-proaction", "academy-marco", "github-tokengauge-discussion", "github-tokengauge-repo", "x-devzero-reader"],
    sections: [
      {
        eyebrow: "Seven lanes",
        heading: "Pick the business shape before the tech stack",
        body: [
          "A fixed-scope service usually reaches evidence fastest because you can sell an outcome before building a platform. A productised service adds a repeatable intake and quality gate. A sales prototype helps a team validate a customer workflow. A niche product or micro-SaaS can scale, but it adds distribution, hosting, support, privacy, and retention work.",
          "Internal automation can create career or organisational value even when no external customer pays. A maintenance retainer can create recurring revenue, but it also creates recurring response obligations. A reusable workflow or implementation package sits between services and software, with revenue depending on who can buy and safely use it.",
        ],
        bullets: [
          "Fixed-scope service: one buyer, one outcome, one acceptance gate.",
          "Productised service: repeated intake, template, review rubric, and bounded variations.",
          "Sales prototype: synthetic data, visible demo boundary, and a production-gap list.",
          "Niche product: one recurring job and one success event before broad features.",
          "Internal automation: measured baseline, human gate, adoption, and failure costs.",
          "Maintenance retainer: transparent obligations, response times, and escalation.",
          "Reusable package: versioned instructions, fixtures, evidence, and support limits.",
        ],
        figureId: "fig-7",
      },
      {
        eyebrow: "Score what matters",
        heading: "A good wedge has a payer you can reach",
        body: [
          "Score each candidate from zero to five on problem pain, frequency, access to a buyer, budget evidence, evidence strength, speed to reviewable proof, and repeatability. Subtract points for data or regulatory risk, support burden, and external dependencies you cannot control.",
          "A high score is a prioritisation aid, not market proof. Keep the raw evidence beside every score. When two lanes are close, prefer the one that can generate a paid or falsifying signal with less capital and lower downside.",
        ],
        example: {
          label: "Thin wedge",
          title: "From 'AI automation agency' to an inspectable offer",
          text: "Too broad: 'I automate business operations.' Better hypothesis: 'For small property managers using one approved spreadsheet export, I produce a reviewed weekly exception brief with source-linked rows and a two-business-day turnaround.'",
        },
      },
      {
        eyebrow: "Do not confuse signals",
        heading: "Interest, use, and payment answer different questions",
        body: [
          "The TokenGauge discussion documents a working product, a free surface, and optional paid tiers. That is clear productisation evidence. The public source does not disclose sales. Marco Salsiccia's Academy case documents shipped apps and user reach, not monetisation. The EPUB reader post documents an experimental product, not demand.",
          "Use each signal for the decision it can support. A working artefact supports technical feasibility. Repeated interviews support problem relevance. A paid pilot or purchase supports willingness to pay. Retention and contribution margin support a more durable business case.",
        ],
      },
    ],
    practice: {
      id: "practice-choose-market-wedge",
      lessonSlug: "choose-market-wedge",
      title: "Score three real wedges",
      brief: "Run the interactive scorecard once for each of three candidates, save each result, then compare the evidence behind the scores.",
      prompt: "Compare these three monetisation lanes using problem pain, frequency, access to a buyer, budget evidence, evidence strength, speed to reviewable proof, repeatability, data or regulatory risk, support burden, and external dependency risk. Return the strongest counterargument for each option and recommend a smallest paid experiment. A no-go recommendation is allowed.",
      steps: [
        "Choose one service, one product, and one internal or retainer idea.",
        "Enter each candidate name and every score only after writing its supporting observation or source.",
        "Run a downside pass that raises support and dependency risks and lowers speed-to-proof; record the evidence behind every changed score.",
        "Select one wedge and state what new evidence could reverse your choice.",
      ],
      deliverables: ["Three saved scorecards", "Factor-level evidence notes", "One selected thin wedge"],
      guardrail: "Do not treat followers, stars, views, or compliments as payment evidence.",
    },
    checkpoint: {
      question: "When is a lower-scoring opportunity still the better first experiment?",
      answer: "When its evidence can be gathered faster or with much less downside. A score summarises assumptions; experiment cost, reversibility, and access to a real payer can make the lower score more informative.",
    },
    takeaway: "Choose the smallest commercial wedge that can teach you whether a real payer values a real outcome.",
  },
  {
    slug: "validate-before-building",
    order: 3,
    unitId: "value",
    minutes: 50,
    title: "Validate before building",
    summary: "Use Codex to organise market evidence without allowing it to invent customers or demand.",
    outcome: "A problem-evidence ledger, interview guide, and go, revise, or stop decision.",
    objectives: [
      "Separate public pain signals from purchase intent.",
      "Conduct falsifiable interviews without pitching too early.",
      "Define the minimum evidence needed before a pilot build.",
    ],
    evidenceClasses: ["business-process", "official-workflow"],
    sourceIds: ["academy-proaction", "academy-account-brief", "openai-prompting", "x-fka-demo"],
    sections: [
      {
        eyebrow: "Problem evidence",
        heading: "Ask about the last real event",
        body: [
          "A useful interview reconstructs the last time the problem occurred: trigger, current workflow, people involved, elapsed time, errors, consequences, existing tools, and who approved spending. Avoid asking whether someone likes your idea. Hypothetical enthusiasm is cheap and often misleading.",
          "Codex can turn authorised notes into a structured ledger, identify contradictions, and propose unanswered questions. It must not invent quotations, fill missing budget information, scrape personal data without permission, or silently merge different customer segments.",
        ],
        bullets: [
          "Observation: what happened in a named past event.",
          "Interpretation: your explanation of why it happened.",
          "Hypothesis: what may be valuable enough to change.",
          "Payment signal: a deposit, signed pilot, purchase, or equivalent authorised commitment.",
        ],
      },
      {
        eyebrow: "Prototype with a boundary",
        heading: "Use a demo to learn, not to impersonate production",
        body: [
          "The Proaction Academy case is a useful pattern: customer conversations informed a tailored sandbox using demo data, and the output became transcripts, screenshots, and a working prototype for engineering. The prototype was explicitly not the secure production system.",
          "A fast visual demo can reveal misunderstandings, but the original Three.js creator explicitly described the result as unpolished. Add a visible demo label, synthetic data, reset controls, and a production-gap list. Never imply that a mocked integration is live.",
        ],
        figureId: "fig-6",
      },
      {
        eyebrow: "Decision gate",
        heading: "A well-supported no-go is a successful result",
        body: [
          "Before building, set a validation threshold such as three independent, repeated pain accounts, access to a budget owner, one sample input, and agreement on an acceptance test. Adjust the threshold for risk. Health, finance, employment, education, accessibility, or sensitive-data workflows need stronger domain review and authority.",
          "Preserve negative evidence. If a current workaround is good enough, the budget owner is unreachable, the workflow is too rare, or review costs erase the value, stop or narrow the offer. Codex should summarise that decision, not pressure you into a positive story.",
        ],
        warning: "Do not automate cold outreach, scrape private data, or present generated personas as research participants.",
      },
    ],
    practice: {
      id: "practice-validate-before-building",
      lessonSlug: "validate-before-building",
      title: "Build a falsifiable evidence ledger",
      brief: "Analyse a small set of authorised notes and public signals, including evidence against the idea.",
      prompt: "Create a problem-evidence ledger from these authorised materials. For each row, record the source, exact locator, observed problem, frequency, current workaround, consequence, budget evidence, contradictory evidence, and what the source does not prove. Keep unknown values unknown. End with go, revise, or stop and list five questions that could falsify the recommendation.",
      steps: [
        "Gather at least three independent evidence channels.",
        "Redact personal or confidential details before importing notes.",
        "Separate direct observations from your interpretations.",
        "Write a decision and the smallest next evidence step.",
      ],
      deliverables: ["Problem-evidence ledger", "Five falsifying questions", "Go, revise, or stop decision"],
      guardrail: "Publicly visible pain does not grant permission to contact, profile, or repurpose personal information.",
    },
    checkpoint: {
      question: "What is the difference between a GitHub issue and willingness to pay?",
      answer: "An issue can show that a problem exists for a user or project. Willingness to pay requires separate evidence that an authorised buyer values the proposed outcome enough to exchange money or another meaningful commitment.",
    },
    takeaway: "Let evidence kill a weak idea before fast implementation makes it expensive.",
  },
  {
    slug: "write-commercial-spec",
    order: 4,
    unitId: "pilot",
    minutes: 55,
    title: "Write the commercial task contract",
    summary: "Convert a customer outcome into scope that Codex can execute and a buyer can accept.",
    outcome: "A one-page offer, statement-of-work draft, and executable Codex task contract.",
    objectives: [
      "Define the buyer's outcome separately from the implementation method.",
      "Write binary or observable acceptance tests.",
      "Declare inputs, exclusions, review gates, and stop conditions.",
    ],
    evidenceClasses: ["business-process", "official-workflow"],
    sourceIds: ["openai-prompting", "academy-small-business", "academy-bootcamp", "github-openai-codex", "x-kr0der-plan"],
    sections: [
      {
        eyebrow: "Two linked contracts",
        heading: "The customer buys an outcome; Codex receives an execution brief",
        body: [
          "The commercial scope explains buyer, problem, deliverables, acceptance, milestones, responsibilities, exclusions, revision limits, change control, data handling, handoff, support, and payment assumptions. The Codex task contract translates the approved scope into repository context, allowed changes, prohibited changes, required commands, evidence, and stop conditions.",
          "Do not copy legal language you do not understand. Scope and AI-disclosure templates in this course are educational examples, not jurisdiction-specific legal advice. Use appropriate professional review for contracts, privacy, tax, intellectual property, or regulated work.",
        ],
        figureId: "fig-3",
      },
      {
        eyebrow: "Acceptance",
        heading: "Make done visible to someone other than the builder",
        body: [
          "Good acceptance criteria operate on customer-observable behaviour or an auditable artefact. 'Make it better' and 'modern UI' are not acceptance tests. 'At 390px and 1440px, the quote form submits valid data, shows an accessible error for invalid email, writes no secrets to the browser console, and passes the named test command' is inspectable.",
          "Include non-goals. A prototype may exclude production identity, live payments, migration, monitoring, and regulated advice. A report may exclude causal inference and data not present in the approved inputs. Explicit exclusion protects both quality and margin.",
        ],
        example: {
          label: "Task contract",
          title: "Seven fields that prevent silent scope drift",
          text: "Outcome; authorised inputs; relevant context; allowed changes; constraints and non-goals; acceptance and verification; evidence and handoff. Add a stop condition whenever authority or required data is missing.",
        },
      },
      {
        eyebrow: "Change control",
        heading: "Treat a new request as a decision, not a favour",
        body: [
          "When a buyer asks for a new integration, workflow, or revision, classify it as clarification, defect against acceptance, or scope change. Clarifications and defects may already be included. New outcomes, inputs, or risks should trigger a written impact on time, price, and verification.",
          "Ask Codex to explain the impact from repository evidence, then make the commercial decision yourself. Do not allow fast code generation to hide extra review, deployment, support, or compliance work.",
        ],
      },
    ],
    practice: {
      id: "practice-write-commercial-spec",
      lessonSlug: "write-commercial-spec",
      title: "Turn a vague request into a paid pilot",
      brief: "Rewrite 'build an AI dashboard for my business' as one bounded, reviewable pilot.",
      prompt: "Turn this customer request into two aligned documents. First, write a one-page pilot scope with buyer outcome, required inputs, deliverables, five acceptance tests, non-goals, responsibilities, milestones, change control, handoff, and support boundary. Second, write a Codex task contract with repository context, allowed and prohibited changes, verification commands, evidence, and stop conditions. Mark legal or commercial assumptions for human review.",
      steps: [
        "Choose one user, one decision, one approved data source, and one core flow.",
        "Write five acceptance tests a non-author can inspect.",
        "List at least five non-goals, including high-risk production actions.",
        "Ask a peer to find ambiguity before implementation.",
      ],
      deliverables: ["One-page offer", "Pilot scope", "Codex task contract", "Peer ambiguity notes"],
      guardrail: "Never promise universal compliance, perfect security, or defect-free software.",
    },
    checkpoint: {
      question: "Why should a rapid Codex implementation not automatically lower the price?",
      answer: "A responsible price reflects customer value, risk, market alternatives, review, support, and the full delivery obligation. Generation time is only one cost input and does not remove accountability.",
    },
    takeaway: "Sell a bounded outcome, then give Codex a contract precise enough to produce inspectable evidence.",
  },
  {
    slug: "protect-client-work",
    order: 5,
    unitId: "pilot",
    minutes: 50,
    title: "Protect client work",
    summary: "Use least privilege, synthetic data, isolation, and explicit human authority before touching customer systems.",
    outcome: "A client safety plan covering data, access, secrets, intellectual property, review, and incident handling.",
    objectives: [
      "Choose local, worktree, or cloud execution from the risk profile.",
      "Minimise data and permissions before importing client context.",
      "Define which external actions always remain human-approved.",
    ],
    evidenceClasses: ["official-workflow", "business-process"],
    sourceIds: ["openai-app", "openai-auth", "openai-security", "openai-worktrees", "academy-proaction", "academy-account-brief", "x-flavio-app"],
    sections: [
      {
        eyebrow: "Workspace choice",
        heading: "Isolation is part of the deliverable",
        body: [
          "Use a disposable or synthetic project for discovery and demos. Use a worktree or separate branch for client changes that must remain isolated and reviewable. Use cloud work only when repository access, network policy, secrets, and account requirements are authorised. Record the chosen environment in the delivery log.",
          "OpenAI documents distinct authentication paths: ChatGPT-plan access and API-key usage-based billing on local surfaces, while cloud work requires ChatGPT sign-in. Features, limits, and prices can change. Verify the current official account and pricing pages before estimating costs or promising a surface.",
        ],
        figureId: "fig-2",
      },
      {
        eyebrow: "Data and secrets",
        heading: "Import the minimum evidence needed for the approved outcome",
        body: [
          "Classify inputs as public, synthetic, internal, confidential, personal, regulated, or secret. Replace real names and transactions in practice and sales prototypes. Keep credentials out of prompts, repositories, screenshots, logs, and deliverables. Prefer short-lived, scoped credentials when authorised use is unavoidable.",
          "Ask who owns the source code, training materials, images, libraries, generated assets, and final work. Inspect licences and attribution obligations. An AI-generated suggestion does not guarantee that an asset is original, licensed, or safe to publish.",
        ],
        bullets: [
          "Read-only before write access.",
          "Staging before production.",
          "Synthetic or redacted data before real customer data.",
          "Explicit client approval before external sending, publishing, charging, deleting, or deploying.",
          "Rollback and incident contact before an irreversible action.",
        ],
      },
      {
        eyebrow: "Human authority",
        heading: "Codex can execute; accountable people authorise",
        body: [
          "A sandbox and approval policy reduce risk, but they do not authorise work. The client and provider must still decide what systems, data, actions, and review standards are in scope. Untrusted instructions inside a repository, issue, email, or document should be treated as data, not automatically obeyed as authority.",
          "Define an escalation path for missing access, suspected secrets, destructive operations, security findings, personal data, and acceptance failures. A safe stop with an evidence note is a successful run.",
        ],
        warning: "Never test systems you do not own or have explicit permission to test.",
      },
    ],
    practice: {
      id: "practice-protect-client-work",
      lessonSlug: "protect-client-work",
      title: "Threat-model a synthetic client pilot",
      brief: "Map data, permissions, external actions, and failure paths before opening the project in Codex.",
      prompt: "Review this pilot scope as a cautious delivery lead. Produce a data inventory, permission matrix, secret-handling plan, third-party rights checklist, external-action approval list, rollback plan, and escalation triggers. Recommend the least-privileged Codex environment. Do not assume authority that the scope does not state.",
      steps: [
        "Replace every real identity or transaction with a synthetic fixture.",
        "List required capabilities and remove unnecessary write or network access.",
        "Name every action that requires a human approval checkpoint.",
        "Test one missing-permission and one malformed-input failure.",
      ],
      deliverables: ["Data inventory", "Permission matrix", "Approval gates", "Rollback and escalation plan"],
      guardrail: "Do not paste credentials, signed URLs, private keys, customer records, or production logs into this exercise.",
    },
    checkpoint: {
      question: "Does a worktree make an unreviewed client change safe?",
      answer: "No. It isolates filesystem changes and supports review, but the change still needs the relevant tests, security and domain review, client acceptance, and authorised integration.",
    },
    takeaway: "Commercial speed is valuable only when client trust, authority, data, and rollback remain intact.",
  },
  {
    slug: "build-verified-pilot",
    order: 6,
    unitId: "pilot",
    minutes: 60,
    title: "Build a verified pilot",
    summary: "Use Codex to implement, test, inspect, and hand off one thin customer outcome.",
    outcome: "A working pilot plus an evidence receipt that another person can review.",
    objectives: [
      "Run the inspect, plan, implement, verify, review, and handoff loop.",
      "Test the happy path, a failure path, and a fresh-input path.",
      "Keep the difference between prototype and production visible.",
    ],
    evidenceClasses: ["official-workflow", "business-process"],
    sourceIds: ["academy-bootcamp", "academy-builders", "academy-small-business", "openai-code-review", "x-billy-dashboard", "x-rudrank-fix", "x-devzero-reader", "x-pedro-build-time"],
    sections: [
      {
        eyebrow: "The delivery loop",
        heading: "Make each stage leave evidence",
        body: [
          "Ask Codex to inspect the repository and relevant instructions before planning. Review the plan against the commercial scope. Implement in small checkpoints. Run the named tests and manual smoke path. Inspect the diff for unrelated changes, secrets, dependency drift, and missing error handling. End with a handoff that lists changed files, verification, limitations, and decisions.",
          "A summary that says a root cause was found is not enough. The real evidence is the diff, reproduced failure, passing fix, relevant regression tests, and an acceptance path that still works with a fresh input.",
        ],
        figureId: "fig-4",
      },
      {
        eyebrow: "Artefact versus proof",
        heading: "A screenshot proves appearance, not correctness",
        body: [
          "The community dashboard, EPUB reader, and other product images show concrete artefacts built with Codex. They are useful inspiration. They cannot show hidden error states, data safety, accessibility, deployment reliability, demand, or profitability.",
          "Your pilot evidence should include commands and results, a short manual test record, viewport or device coverage where relevant, source reconciliation for data work, and explicit open risks. Show at least one failure state rather than curating only a perfect screen.",
        ],
        figureId: "fig-5",
      },
      {
        eyebrow: "Fresh verification",
        heading: "Re-run the final gate after the final change",
        body: [
          "A test from before the last revision is stale evidence. Run the full agreed gate after the final content, configuration, dependency, or code change. If exact verification cannot run in your environment, state that boundary and give the client the precise command or manual step required.",
          "Do not claim an inaccessible platform or package executed. A reimplementation or simulation can support reasoning, but it must be labelled as such and should not replace the client-required environment.",
        ],
      },
    ],
    practice: {
      id: "practice-build-verified-pilot",
      lessonSlug: "build-verified-pilot",
      title: "Complete a synthetic paid-pilot sprint",
      brief: "Deliver one core flow from an approved synthetic brief and collect the full evidence receipt.",
      prompt: "Inspect this project and the approved pilot scope. Before editing, map the relevant files and propose a plan tied to each acceptance test. Implement only the agreed core flow. Run the named tests, one fresh-input smoke test, one failure-path test, and a diff review. Stop if required authority or data are missing. Finish with changed files, commands and results, screenshots or artefact paths, limitations, and client decisions.",
      steps: [
        "Create a clean checkpoint and confirm the allowed files.",
        "Review the plan against every acceptance criterion.",
        "Implement in small, reversible changes and steer when scope drifts.",
        "Run the final gate after the final edit and package the evidence receipt.",
      ],
      deliverables: ["Working pilot", "Test and review receipt", "Known-limits register", "Handoff note"],
      guardrail: "A pilot must remain visibly non-production until the production gap has been reviewed and funded.",
    },
    checkpoint: {
      question: "What is the most important evidence after Codex reports that a task is complete?",
      answer: "The evidence tied to the agreed acceptance criteria: inspected changes, fresh commands and results, manual behaviour, limitations, and an accountable review decision.",
    },
    takeaway: "The sellable unit is not generated code. It is an accepted outcome with an inspectable evidence trail.",
  },
  {
    slug: "price-for-margin",
    order: 7,
    unitId: "sell",
    minutes: 55,
    title: "Price for margin and risk",
    summary: "Use your own current costs and measured labour to calculate a defensible floor, scenario, and quote.",
    outcome: "A three-scenario price model with a floor, target, downside, and explicit assumptions.",
    objectives: [
      "Calculate a sustainable hourly and project floor from learner-entered inputs.",
      "Separate quoted price, collected revenue, contribution margin, and estimated operational value.",
      "Use value context without fabricating guaranteed savings or earnings.",
    ],
    evidenceClasses: ["commercial-signal", "paid-offer", "business-process", "official-workflow"],
    sourceIds: ["academy-goliath", "openai-auth", "openai-pricing", "github-tokengauge-discussion", "github-tokengauge-repo"],
    sections: [
      {
        eyebrow: "Course-authored planning heuristic",
        heading: "Count the work Codex does not remove",
        body: [
          "Start with desired take-home compensation, working capacity, realistic billable utilisation, overhead reserve, tax reserve, direct tools, hosting, payment fees, discovery, review, deployment, support, and risk buffer. A faster implementation can reduce one input, but may increase review or support if the scope is unclear.",
          "The formulas below and the calculator on this lesson are course-authored planning heuristics, not formulas established by the cited OpenAI or practitioner sources and not tax, accounting, or legal advice. They deliberately use your current inputs rather than a hardcoded Codex price. Official prices, quotas, models, and plan entitlements change, so record the date and live source used for every quoted tool cost.",
        ],
        bullets: [
          "Revenue requirement = desired take-home divided by one minus overhead and reserve rates.",
          "Hourly floor = revenue requirement divided by realistic annual billable hours.",
          "Project floor = hourly floor times expected delivery hours, plus direct costs grossed up for revenue allocations, then the risk buffer.",
          "Contribution margin scenario = collected price minus variable delivery, review, support, fees, and tool costs.",
        ],
      },
      {
        eyebrow: "Value context",
        heading: "Anchor to a verified outcome, never an invented percentage",
        body: [
          "Ask the buyer what the current problem costs in time, error, delay, lost opportunity, or risk. Use documented ranges and scenario math. Do not promise that your fee will return a fixed multiple or that time saved becomes cash profit.",
          "The Goliath case is memorable precisely because it reports a large contract request and small compute estimate. It should not be used as a markup formula. Full labour, discovery, data, review, support, acquisition, and business costs are not captured by the compute number, and the article does not confirm collected revenue.",
        ],
        example: {
          label: "Responsible quote",
          title: "Price the approved outcome, not the prompt",
          text: "State a fixed pilot price, included scope, payment milestones, change rate, assumptions, and evidence. Keep a separate internal cost model. Do not expose a fake 'AI cost plus 1000x' formula to the customer.",
        },
      },
      {
        eyebrow: "Three scenarios",
        heading: "Model downside before accepting the work",
        body: [
          "Create base, downside, and severe-review scenarios. Increase human review, revisions, support, API or tool costs, and schedule risk. If the downside becomes unacceptable, narrow the scope, increase the price, add a paid discovery phase, or decline.",
          "Track actual time and direct cost after delivery. Update the model from evidence rather than preserving an attractive but false estimate. Never call gross revenue profit.",
        ],
        warning: "Do not quote tax, regulatory, or legal treatment without qualified local advice.",
      },
    ],
    practice: {
      id: "practice-price-for-margin",
      lessonSlug: "price-for-margin",
      title: "Calculate a three-scenario quote",
      brief: "Use the interactive margin calculator and your current costs to decide whether the pilot is viable.",
      prompt: "Audit my project price assumptions. Separate desired compensation, billable capacity, overhead, reserve, direct tool and hosting costs, payment fees, discovery, delivery, review, revisions, support, and risk. Return base, downside, and severe-review scenarios. Flag category errors and unknowns. Do not infer current Codex pricing; require a dated official source or a manual input.",
      steps: [
        "Enter your target, capacity, reserve, and billable-utilisation assumptions.",
        "Estimate every human stage, including sales and support.",
        "Double review and revision time for the downside scenario.",
        "Set a floor, target price, and a condition under which you decline.",
      ],
      deliverables: ["Base scenario", "Downside scenario", "Target quote", "Decline condition"],
      guardrail: "Do not present the calculator as financial advice or a guarantee that a customer will accept the quote.",
    },
    checkpoint: {
      question: "Why is estimated time saved not the same as profit?",
      answer: "Time may be unused, reallocated, or require review and adoption. Profit requires collected revenue or actual cash savings minus all relevant costs. Those are different quantities and need different evidence.",
    },
    takeaway: "A sustainable quote covers the whole accountable delivery system, not just model or compute time.",
  },
  {
    slug: "sell-with-proof",
    order: 8,
    unitId: "sell",
    minutes: 45,
    title: "Sell with proof, not promises",
    summary: "Use a tailored demo, traceable portfolio, and honest proposal to reduce buyer uncertainty.",
    outcome: "A five-minute proof demo, one-page proposal, and portfolio evidence card.",
    objectives: [
      "Build a demo that traces each feature to customer evidence.",
      "Write portfolio claims that state source, measurement, and boundary.",
      "Design the next buyer decision instead of pressuring for a close.",
    ],
    evidenceClasses: ["business-process", "paid-offer", "commercial-signal"],
    sourceIds: ["academy-proaction", "academy-goliath", "academy-marco", "x-ashe-productized", "x-fka-demo", "openai-community"],
    sections: [
      {
        eyebrow: "Proof stack",
        heading: "Show the problem, the artefact, and the evidence receipt",
        body: [
          "A credible five-minute demo starts with the buyer's current job, uses a synthetic or authorised input, completes one core outcome, shows one failure or limit, and ends with the evidence and production gap. It does not tour every feature or hide assumptions.",
          "The Proaction case shows why a tailored sandbox can make customer conversations concrete while secure production remains with engineering. Use that as a workflow example, not as proof that tailored demos always close deals.",
        ],
        figureId: "fig-6",
      },
      {
        eyebrow: "Portfolio truth",
        heading: "Write only what the evidence can survive",
        body: [
          "A portfolio card should name the context, your role, approved inputs, artefact, acceptance checks, measured result, remaining limitations, and source date. If the work is simulated, label it. If a result is self-reported by a client, say so. If no one paid, do not imply a client engagement or sale.",
          "Do not fabricate testimonials, logos, revenue, user counts, before-and-after metrics, or screenshots. Do not convert the ashebytes productisation post into a sales claim or Marco's user reach into profit. Those sources support narrower statements.",
        ],
        example: {
          label: "Evidence card",
          title: "A claim with a built-in audit trail",
          text: "'Synthetic pilot: converted a 120-row fixture into a source-linked exception brief; all 14 golden-row checks passed on 2026-08-23. No real customer data or commercial result is claimed.'",
        },
      },
      {
        eyebrow: "Proposal",
        heading: "Ask for a reversible next decision",
        body: [
          "A proposal should repeat the agreed problem, outcome, scope, acceptance, timeline, responsibilities, price, exclusions, risks, and next step. The next step might be paid discovery, a fixed pilot, access to a sample input, or a technical review. It should be easy for the buyer to say no or ask a concrete question.",
          "Use Codex to assemble the proposal from approved facts and flag unsupported statements. A human should review all customer-facing copy, prices, legal terms, and claims before sending.",
        ],
      },
    ],
    practice: {
      id: "practice-sell-with-proof",
      lessonSlug: "sell-with-proof",
      title: "Build the proof-led sales pack",
      brief: "Turn your validated pilot into a transparent demo, evidence card, and proposal.",
      prompt: "Using only the approved discovery notes, pilot evidence receipt, and pricing assumptions, draft a five-minute demo script, one portfolio evidence card, and one-page proposal. Trace each claim to its source. Label simulations and self-reported outcomes. Include the production gap, exclusions, risks, and a reversible next decision. Do not invent a testimonial, customer, metric, revenue, or legal term.",
      steps: [
        "Select the buyer's one most important job and one proof path.",
        "Add a visible synthetic-data or demo label where needed.",
        "Rehearse the demo against a failure case and a strict five-minute limit.",
        "Ask a reviewer to challenge every metric and implied claim.",
      ],
      deliverables: ["Demo script", "Portfolio evidence card", "One-page proposal", "Claim-review notes"],
      guardrail: "Never imply a testimonial, sale, production integration, or metric that the evidence does not show.",
    },
    checkpoint: {
      question: "What does a tailored sales prototype prove?",
      answer: "It can make requirements concrete and show that a workflow may be feasible. It does not by itself prove production readiness, security, customer acceptance, or a sale.",
    },
    takeaway: "The strongest sales story reduces uncertainty with traceable proof and honest limits.",
  },
  {
    slug: "deliver-with-control",
    order: 9,
    unitId: "sell",
    minutes: 55,
    title: "Deliver with control",
    summary: "Turn generated work into an accountable handoff, acceptance decision, and clean closeout.",
    outcome: "A versioned delivery pack, client acceptance record, and safe closeout checklist.",
    objectives: [
      "Review diffs and findings before integrating work.",
      "Classify defects, clarifications, and change requests consistently.",
      "Close access, archive evidence, and transfer operational ownership.",
    ],
    evidenceClasses: ["official-workflow", "business-process"],
    sourceIds: ["openai-code-review", "openai-worktrees", "github-codex-action", "x-nate-review", "x-steipete-pr", "academy-small-business"],
    sections: [
      {
        eyebrow: "Reviewable change",
        heading: "A clean diff is a customer communication tool",
        body: [
          "Separate unrelated changes, keep commits understandable, and explain why each change exists. Review for hidden configuration changes, secrets, generated files, dependency changes, data migrations, and behaviour outside scope. Run the full gate after resolving review comments.",
          "The community review examples are useful because they show human verification and separated commits. They are not accuracy benchmarks. Your delivery standard comes from the client's acceptance and risk profile.",
        ],
        figureId: "fig-8",
      },
      {
        eyebrow: "Acceptance and change",
        heading: "Let the contract decide what happens next",
        body: [
          "Walk through every acceptance criterion and record pass, fail, deferred, or not applicable with evidence. A failure against an agreed criterion is a defect. A changed preference may be a clarification. A new outcome or integration is a change request with impact on price, schedule, and risk.",
          "Do not use Codex speed to silently absorb scope. Hidden extra work distorts your unit economics and trains the client to bypass review. Present options and let an authorised person decide.",
        ],
        figureId: "fig-9",
      },
      {
        eyebrow: "Closeout",
        heading: "Remove access and leave the client able to operate",
        body: [
          "Deliver source or editable artefacts as agreed, setup and rollback instructions, version and dependency notes, test evidence, known limits, support boundary, and next maintenance date. Confirm ownership and third-party licensing. Revoke temporary credentials and remove local client data according to the agreement.",
          "Archive an approved evidence packet without secrets. Record final actual time, direct cost, revisions, support obligations, and learning. This closes the feedback loop for the next quote.",
        ],
      },
    ],
    practice: {
      id: "practice-deliver-with-control",
      lessonSlug: "deliver-with-control",
      title: "Run a formal client handoff",
      brief: "Use a seeded change request to practice review, acceptance, scope classification, and closeout.",
      prompt: "Audit this delivery against the approved scope. Review the diff for unrelated changes, secrets, dependency and configuration changes, missing error paths, and acceptance coverage. Classify each client comment as defect, clarification, or change request and explain the impact. Produce a handoff with commands and results, limitations, rollback, ownership, support boundary, access-revocation list, and final decisions.",
      steps: [
        "Review the final diff and separate unrelated work.",
        "Re-run the complete acceptance gate after the final revision.",
        "Record the client's decision for every acceptance item.",
        "Revoke temporary access and preserve only the agreed evidence packet.",
      ],
      deliverables: ["Review findings", "Acceptance record", "Versioned handoff", "Access closeout receipt"],
      guardrail: "Never retain client data, credentials, or access beyond the agreed delivery purpose.",
    },
    checkpoint: {
      question: "Why is a client request after the demo not automatically included work?",
      answer: "It may introduce a new outcome, input, integration, risk, or support obligation. The scope and acceptance criteria determine whether it is a defect, clarification, or paid change.",
    },
    takeaway: "Professional delivery makes decisions, evidence, ownership, and remaining risk visible.",
  },
  {
    slug: "productize-reuse",
    order: 10,
    unitId: "scale",
    minutes: 45,
    title: "Productise what survived delivery",
    summary: "Turn a successful workflow into versioned instructions, fixtures, templates, and quality gates.",
    outcome: "A reusable delivery package that passes two distinct synthetic clients and one failure fixture.",
    objectives: [
      "Identify the stable core and variable client layer.",
      "Encode reusable constraints in AGENTS.md, a skill, template, or script.",
      "Test cross-client isolation and safe failure.",
    ],
    evidenceClasses: ["business-process", "official-workflow", "paid-offer"],
    sourceIds: ["openai-agents-md", "openai-skills", "academy-bootcamp", "github-openai-codex", "github-tokengauge-discussion", "x-ashe-productized", "x-devzero-reader"],
    sections: [
      {
        eyebrow: "Stable versus variable",
        heading: "Reuse the process, not the previous client's data",
        body: [
          "The stable core may include intake schema, folder structure, test commands, accessibility rules, evidence format, redaction checks, handoff template, and failure behaviour. The variable layer contains each client's approved inputs, brand, requirements, systems, acceptance, and commercial terms.",
          "Never turn a client repository, data export, prompt history, or proprietary logic into a template without permission. Test the package against unrelated synthetic clients to expose accidental leakage and hidden assumptions.",
        ],
        figureId: "fig-7",
      },
      {
        eyebrow: "Codex reuse",
        heading: "Put stable constraints where Codex can discover them",
        body: [
          "Use AGENTS.md for repository-wide or nested instructions that every relevant task should follow. Use a skill for a focused, repeatable workflow with its own references, templates, or scripts. Keep instructions concise, versioned, and testable. Do not store secrets or volatile prices in reusable instructions.",
          "Include a sample fixture, expected output, quality rubric, failure fixture, and changelog. A package is not productised merely because it has a prompt. It should accept defined inputs, create an inspectable artefact, fail visibly, and preserve human gates.",
        ],
      },
      {
        eyebrow: "Commercial boundary",
        heading: "Productised does not mean sold or passive",
        body: [
          "The TokenGauge and ashebytes sources show explicit productisation or paid-offer intent. They do not disclose public sales results. Keep the same distinction in your own portfolio: offering a tier proves an offer exists, while customers, collected revenue, retention, and margin require separate records.",
          "A reusable workflow may reduce marginal delivery time, but support, exceptions, updates, quality review, security, and customer acquisition remain active work.",
        ],
        warning: "Do not promise identical outcomes across customers simply because the same template passed twice.",
      },
    ],
    practice: {
      id: "practice-productize-reuse",
      lessonSlug: "productize-reuse",
      title: "Package one delivered workflow",
      brief: "Create a reusable, versioned service core and pressure-test it against two clients and one malformed input.",
      prompt: "Extract the stable, reusable parts of this completed delivery without copying client-specific or confidential material. Propose an AGENTS.md rule set, optional focused skill, intake schema, templates, fixtures, quality rubric, failure behaviour, changelog, and human approval gate. Run a cross-client leakage check and list every assumption that must remain configurable.",
      steps: [
        "Separate stable process rules from client-specific inputs and decisions.",
        "Create two unrelated synthetic fixtures and one malformed fixture.",
        "Run the same rubric on both valid outputs and confirm no cross-client leakage.",
        "Version the package and record current dependencies and fallback paths.",
      ],
      deliverables: ["Reusable package", "Two valid test receipts", "Failure receipt", "Cross-client leakage check"],
      guardrail: "Never reuse a client's private data, code, brand, or proprietary workflow without explicit permission.",
    },
    checkpoint: {
      question: "What makes a reusable workflow stronger than a saved prompt?",
      answer: "Defined inputs, stable instructions, fixtures, expected outputs, verification, failure behaviour, versioning, human gates, and a clear boundary for client-specific variation.",
    },
    takeaway: "Productise only the parts that proved repeatable, reviewable, and safe in real delivery.",
  },
  {
    slug: "retain-and-automate",
    order: 11,
    unitId: "scale",
    minutes: 45,
    title: "Earn recurring value responsibly",
    summary: "Design maintenance or operations work with real obligations, measured operational value, and safe automation.",
    outcome: "A transparent retainer or internal automation plan with a baseline, service gate, escalation, and monthly evidence report.",
    objectives: [
      "Distinguish recurring revenue from passive income.",
      "Report internal operational value from measured adoption, reliability, review, failure cost, and any observed cash effect without collapsing them into an invented ROI.",
      "Schedule only workflows that have safe inputs, permissions, review, and escalation.",
    ],
    evidenceClasses: ["official-workflow", "business-process", "commercial-signal"],
    sourceIds: ["openai-automations", "github-codex-action", "academy-business-ops", "academy-goliath", "academy-account-brief", "x-steipete-pr"],
    sections: [
      {
        eyebrow: "Retainer truth",
        heading: "Recurring payment creates recurring accountability",
        body: [
          "A maintenance retainer can include dependency updates, bug triage, monitoring review, documentation, content or data refresh, analytics, accessibility checks, security review on authorised systems, or a fixed improvement budget. Each tier needs included work, exclusions, service targets, review gates, escalation, cancellation, and handoff.",
          "It is not passive income. You retain responsibility for response, quality, data, tools, updates, and client communication. Price the obligation, not the existence of an automated task.",
        ],
        figureId: "fig-9",
      },
      {
        eyebrow: "Course-authored operational-value worksheet",
        heading: "Measure capacity without pretending it is cash",
        body: [
          "Record a baseline manual time and error rate, then run the assisted workflow on known fixtures. Report verified hours saved, the dated fully loaded labour-cost assumption, actual adoption, error and rework rates, human review, reliability, maintenance, build and operating cost, expected failure cost, and any observed cash-flow change as separate fields. Do not hide uncertainty inside an invented quality multiplier or collapse unlike measures into one ROI percentage.",
          "This is a course-authored measurement worksheet, not a formula established by OpenAI or the cited cases and not accounting, tax, or financial advice. Without a verified cash-flow change, describe the result only as estimated operational value, not cash savings, profit, revenue, or realised ROI.",
        ],
      },
      {
        eyebrow: "Safe scheduling",
        heading: "Start read-only, run in shadow mode, and route exceptions to a person",
        body: [
          "Test the prompt manually with valid and malformed fixtures. Schedule a read-only or draft-producing task first. Define approved sources, environment, cadence, output destination, permissions, timeout, idempotency, failure signal, escalation contact, and review before any external action.",
          "The Goliath case reports a scheduled Codex agent that detected and helped resolve an overnight problem. That is a company-reported example, not permission to give an agent broad production access. Your own automation needs the client's controls and an incident plan.",
        ],
        warning: "External sending, publishing, charging, deleting, deploying, or high-risk merging should remain explicitly authorised and reviewable.",
      },
    ],
    practice: {
      id: "practice-retain-and-automate",
      lessonSlug: "retain-and-automate",
      title: "Design one responsible recurring workflow",
      brief: "Choose either a retainer obligation or an internal recurring artefact and build its control plan.",
      prompt: "Design a recurring Codex workflow from this approved process. Include baseline measures, inputs, cadence, least-privileged environment, output, quality gate, human approval, failure and malformed-input behaviour, escalation, rollback, evidence log, monthly report, and full cost categories. Separate time saved, avoided cost, capacity, collected revenue, and profit.",
      steps: [
        "Measure the current process on at least three runs or documented cases.",
        "Test valid, missing, stale, and malformed inputs manually.",
        "Run the workflow in shadow mode with no external action.",
        "Write transparent service or operational-value reporting and a cancellation path.",
      ],
      deliverables: ["Baseline", "Automation or retainer control plan", "Failure test", "Monthly evidence report template"],
      guardrail: "Never describe a retainer as passive or time saved as guaranteed profit.",
    },
    checkpoint: {
      question: "When is a scheduled task ready to perform an external action?",
      answer: "Only after explicit authority, least-privileged access, valid and failure-path testing, human review design, auditability, rollback, and an escalation path appropriate to the action's risk.",
    },
    takeaway: "Recurring value comes from reliable obligations and measurable outcomes, not unattended activity.",
  },
  {
    slug: "launch-capstone",
    order: 12,
    unitId: "scale",
    minutes: 90,
    title: "Launch a proof-based revenue pilot",
    summary: "Package one lane into a seven-day evidence experiment and make an honest go, revise, or stop decision.",
    outcome: "A complete Codex Revenue Evidence Pack and one reviewed launch decision.",
    objectives: [
      "Combine problem, offer, artefact, proof, economics, trust, and acquisition evidence.",
      "Run a small real or consent-based simulated commercialisation experiment.",
      "Publish only claims that survive the source and boundary audit.",
    ],
    evidenceClasses: ["commercial-signal", "paid-offer", "business-process"],
    sourceIds: ["academy-goliath", "academy-proaction", "academy-marco", "academy-business-ops", "openai-community", "github-tokengauge-discussion", "x-ashe-productized", "x-este-productivity"],
    sections: [
      {
        eyebrow: "Choose a track",
        heading: "One experiment, one decision",
        body: [
          "Choose a fixed-scope service, sales prototype, niche product, internal automation, maintenance retainer, or reusable implementation package. Keep the experiment narrow enough to complete and review. The goal is not to perform success online; it is to gather evidence that changes a decision.",
          "A real sale or redacted payment receipt is optional and never required for course completion. If no one paid, say so. A simulated client must be visibly labelled. Fabricated revenue, testimonials, customers, screenshots, or citations are automatic capstone failures.",
        ],
        figureId: "fig-1",
      },
      {
        eyebrow: "Evidence pack",
        heading: "Thirteen artefacts make the experiment auditable",
        body: [
          "Submit the problem ledger; named payer; offer and scope; commercial task contract; working artefact; test and review receipt; privacy, security, accessibility, and rights checklist; acceptance or stakeholder record; three-scenario economics; proposal; handoff or deployment runbook; acquisition experiment; and go, revise, or stop rule.",
          "End with a retrospective: what Codex inspected, created, tested, and summarised; what the human authorised, verified, decided, disclosed, and remained accountable for.",
        ],
        bullets: [
          "Problem and payer evidence",
          "Offer, scope, and acceptance",
          "Working core flow or decision artefact",
          "Fresh verification and a visible failure state",
          "Trust, rights, and data controls",
          "Measured economics with downside",
          "Honest portfolio and next decision",
        ],
      },
      {
        eyebrow: "Seven-day experiment",
        heading: "Acquire evidence, not vanity metrics",
        body: [
          "Plan five evidence-gathering contacts or observations, three consent-based conversations or structured reviews, one working demo or deliverable, one proposal or internal decision memo, two feedback rounds, and one final decision. Follow applicable communication rules and platform terms. Do not automate spam.",
          "Grade the capstone on traceability, artefact quality, verification, trust, economics, and decision quality. A stop decision can earn full credit. A sale with fabricated proof cannot.",
        ],
        example: {
          label: "Pass condition",
          title: "Credible commercialisation experiment",
          text: "The core outcome works with fresh input; evidence is traceable; claims stay inside their boundaries; the economics include review and downside; risks are controlled; and the final decision follows the agreed threshold.",
        },
        warning: "Course completion demonstrates a reviewable commercialisation experiment. It does not prove product-market fit, future income, or universal compliance.",
      },
    ],
    practice: {
      id: "practice-launch-capstone",
      lessonSlug: "launch-capstone",
      title: "Complete the Codex Revenue Evidence Pack",
      brief: "Use the capstone checklist on this lesson to assemble, review, and score the full experiment.",
      prompt: "Audit my Codex Revenue Evidence Pack as a skeptical buyer, delivery lead, and evidence reviewer. Check problem and payer evidence, offer and acceptance, working artefact, test and review receipt, privacy, security, accessibility, rights, economics, proposal, handoff, acquisition experiment, and decision rule. Label every commercial statement by evidence class. Reject fabricated, unsupported, or out-of-scope claims. A go, revise, or stop result is acceptable.",
      steps: [
        "Choose one track and freeze the success and stop criteria.",
        "Complete the working artefact and fresh evidence receipt.",
        "Run the claim audit, risk audit, economics downside, and peer review.",
        "Make and document the final go, revise, or stop decision.",
      ],
      deliverables: ["Thirteen-part evidence pack", "Claim audit", "Capstone rubric", "Final decision and retrospective"],
      guardrail: "No earnings guarantee, fabricated commercial evidence, unauthorised data, unlabelled prototype, nonconsensual outreach, or unsupported compliance claim.",
    },
    checkpoint: {
      question: "Can a capstone pass without a sale?",
      answer: "Yes. The capstone evaluates whether you ran a credible, safe, evidence-based commercialisation experiment. A well-supported revise or stop decision is better than a fabricated or uneconomic sale story.",
    },
    takeaway: "Make money claims the way you make production claims: bounded, tested, sourced, and open to a no-go result.",
  },
] as const satisfies readonly CodexIncomeLesson[];

export const MAKE_MONEY_WITH_CODEX_QUIZ = [
  {
    id: "q1",
    lessonSlug: "money-not-magic",
    question: "What can a public Codex-built product establish by itself?",
    options: ["Guaranteed profit", "That an artefact exists", "A typical customer price", "Product-market fit"],
    correctIndex: 1,
    explanation: "A public artefact can show existence or feasibility. Profit, price acceptance, and product-market fit require separate commercial evidence.",
    sourceIds: ["openai-community", "github-tokengauge-repo"],
  },
  {
    id: "q2",
    lessonSlug: "choose-market-wedge",
    question: "Which is the best first monetisation wedge?",
    options: ["The one with the most features", "The one trending on X", "The smallest safe experiment with a reachable payer", "The one with the lowest model cost"],
    correctIndex: 2,
    explanation: "A reachable payer, falsifiable evidence, low downside, and a narrow outcome matter more than feature count or attention.",
    sourceIds: ["academy-small-business", "academy-proaction"],
  },
  {
    id: "q3",
    lessonSlug: "validate-before-building",
    question: "Which is the strongest willingness-to-pay evidence?",
    options: ["A GitHub star", "A compliment", "A generated persona", "A prospect explicitly requests a $10,000-per-month contract"],
    correctIndex: 3,
    explanation: "The Academy case reports the prospect's contract request, which is stronger stated intent than the other options. It does not establish that the contract was signed, paid, renewed, profitable, or typical.",
    sourceIds: ["academy-goliath"],
  },
  {
    id: "q4",
    lessonSlug: "write-commercial-spec",
    question: "Which criterion is most inspectable?",
    options: ["Make it modern", "Improve quality", "The form shows a named error and passes the named test", "Use best practices"],
    correctIndex: 2,
    explanation: "Observable behaviour and a named verification step let a customer or reviewer decide pass or fail.",
    sourceIds: ["openai-prompting"],
  },
  {
    id: "q5",
    lessonSlug: "protect-client-work",
    question: "What does a worktree provide?",
    options: ["Legal authorisation", "Change isolation", "Automatic production safety", "A security warranty"],
    correctIndex: 1,
    explanation: "A worktree isolates changes. Authorisation, testing, security, review, and acceptance remain separate duties.",
    sourceIds: ["openai-worktrees", "openai-security"],
  },
  {
    id: "q6",
    lessonSlug: "build-verified-pilot",
    question: "When is verification evidence fresh?",
    options: ["When it ran before the final edit", "When Codex says done", "When the final agreed gate ran after the final change", "When the screenshot looks correct"],
    correctIndex: 2,
    explanation: "The final change can invalidate earlier evidence. Re-run the agreed gate after it.",
    sourceIds: ["openai-code-review", "academy-bootcamp"],
  },
  {
    id: "q7",
    lessonSlug: "price-for-margin",
    question: "Under the course-authored planning heuristic, what belongs in a project floor?",
    options: ["Only model tokens", "Only coding time", "All accountable delivery, direct cost, and risk", "A competitor's revenue"],
    correctIndex: 2,
    explanation: "Course-authored planning heuristic: discovery, implementation, review, revisions, support, tools, fees, and risk all affect sustainable delivery economics. The cited sources support variable tool cost and evidence boundaries, not this particular formula.",
    sourceIds: ["openai-auth", "openai-pricing", "academy-goliath"],
  },
  {
    id: "q8",
    lessonSlug: "sell-with-proof",
    question: "How should a simulated portfolio project be presented?",
    options: ["As a client result", "Without mentioning simulation", "As a visibly labelled simulation with real verification", "With an invented testimonial"],
    correctIndex: 2,
    explanation: "A simulation can demonstrate capability when it is labelled and its technical evidence is real. It must not imply a customer or sale.",
    sourceIds: ["academy-proaction", "openai-community"],
  },
  {
    id: "q9",
    lessonSlug: "deliver-with-control",
    question: "Under this course's scope-control policy, a request for a new integration is usually what?",
    options: ["Always a free defect fix", "A potential scope change to assess", "Automatically approved", "Proof the original work failed"],
    correctIndex: 1,
    explanation: "Course policy: a new integration changes inputs, risk, verification, support, or outcome and should be assessed through change control. The cited sources support technical scoping and review, not the commercial change-control rule.",
    sourceIds: ["academy-small-business", "openai-code-review"],
  },
  {
    id: "q10",
    lessonSlug: "productize-reuse",
    question: "Under this course's confidentiality policy, what is required before reusing a client workflow?",
    options: ["A copied prompt history", "Permission and removal of client-specific material", "A public screenshot", "No changes"],
    correctIndex: 1,
    explanation: "Course policy: obtain permission, respect ownership and confidentiality, and separate the stable process from client-specific inputs and decisions. The cited OpenAI docs support scoped reusable instructions, not the legal permission rule.",
    sourceIds: ["openai-agents-md", "openai-skills"],
  },
  {
    id: "q11",
    lessonSlug: "retain-and-automate",
    question: "Under this course's retained-service model, why is a retainer not passive income?",
    options: ["It has no customer", "It creates continuing delivery and response obligations", "It cannot be recurring", "Codex cannot run tasks"],
    correctIndex: 1,
    explanation: "Course policy: the provider remains accountable for maintenance, review, incidents, communication, data, and support. The cited sources establish recurring workflows and review needs, not the complete commercial retainer model.",
    sourceIds: ["openai-automations", "academy-business-ops"],
  },
  {
    id: "q12",
    lessonSlug: "launch-capstone",
    question: "Which capstone result can earn full credit?",
    options: ["A fabricated sale", "A no-go decision supported by evidence", "An unlabelled demo", "An earnings guarantee"],
    correctIndex: 1,
    explanation: "The course rewards decision quality and evidence. A defensible no-go prevents waste and preserves trust.",
    sourceIds: ["academy-goliath", "academy-proaction", "github-tokengauge-discussion"],
  },
] as const;

export const MAKE_MONEY_WITH_CODEX_COURSE = {
  id: MAKE_MONEY_WITH_CODEX_COURSE_ID,
  version: MAKE_MONEY_WITH_CODEX_COURSE_VERSION,
  level: MAKE_MONEY_WITH_CODEX_LEVEL,
  publishedOn: "2026-08-23",
  verifiedOn: "2026-08-24",
  title: "How to make money with Codex",
  kicker: "Course 11 · Evidence-led commercialisation",
  summary: "Find a paid problem, build a verified pilot, price the full obligation, sell with honest proof, and productise only what survives delivery.",
  audience: "Builders, freelancers, consultants, operators, founders, and employed professionals who can already review or responsibly supervise the work they deliver.",
  promise: "You will finish with a working commercialisation experiment, a defensible offer, measurable economics, and an auditable evidence pack.",
  nonPromise: "This course does not promise earnings, passive income, product-market fit, or legal, tax, security, or financial compliance.",
  passingScore: 10,
  units: MAKE_MONEY_WITH_CODEX_UNITS,
  lessons: MAKE_MONEY_WITH_CODEX_LESSONS,
  quiz: MAKE_MONEY_WITH_CODEX_QUIZ,
} as const satisfies CodexIncomeCourse;

export const MAKE_MONEY_WITH_CODEX_TOTAL_MINUTES = MAKE_MONEY_WITH_CODEX_LESSONS.reduce(
  (total, lesson) => total + lesson.minutes,
  0,
);

export const MAKE_MONEY_WITH_CODEX_LESSON_BY_SLUG = Object.fromEntries(
  MAKE_MONEY_WITH_CODEX_LESSONS.map((lesson) => [lesson.slug, lesson]),
) as Record<string, CodexIncomeLesson>;
