import type { CodexIncomeFigure } from "./types";

const sourcePage = "https://developers.openai.com/community";
const verifiedOn = "2026-08-23";
const rightsBasis = "first-party-original" as const;
const captureMethod = "first-party-synthetic-capture" as const;
const rightsEvidencePath = "evidence/course-audits/make-money-with-codex/first-party-captures/rights-record.md";

export const MAKE_MONEY_WITH_CODEX_FIGURES = [
  {
    id: "fig-1",
    src: "/courses/make-money-with-codex/figures/fig-01-codex-app-start.png",
    webp: "/courses/make-money-with-codex/figures/fig-01-codex-app-start.webp",
    width: 2000,
    height: 910,
    sha256: "7ebd735a3d41bdce81495efc1da7f36ca17d1660d67f93f4a91dffd513a0c20d",
    webpSha256: "91a6cc63ea0b310433f40ec671238df7ff46ad81d048e741040a480b396ee287",
    sourceUrl: "https://x.com/EstePrimeWorld/status/2081217288414409071",
    sourcePage,
    sourceAuthor: "Course 11 production team; practitioner context from @EstePrimeWorld",
    sourceDate: "2026-08-23",
    verifiedOn,
    surface: "codex-app",
    captureMethod,
    alt: "Current Codex desktop start panel asking what to build in the disposable course11-codex-demo workspace.",
    caption: "Current first-party Codex desktop capture from a disposable synthetic workspace. Begin client work by confirming the workspace, desired outcome, and required evidence before implementation.",
    boundary: "This crop verifies a dated Codex app interface and a safe starting context. It does not verify productivity, customer demand, sales, or income.",
    rightsBasis,
    rightsEvidencePath,
    visiblePublicIdentifiers: ["course11-codex-demo"],
    privacyReview: "The crop excludes the account name, sidebar, unrelated projects, task history, and notifications. Only the invented workspace name course11-codex-demo is visible; no credentials or customer data appear.",
  },
  {
    id: "fig-2",
    src: "/courses/make-money-with-codex/figures/fig-02-codex-app-context.png",
    webp: "/courses/make-money-with-codex/figures/fig-02-codex-app-context.webp",
    width: 1910,
    height: 250,
    sha256: "7e174bbcf508b626f78c1b04ffa59263133d82f5de947a1cc476189a12ff2cb8",
    webpSha256: "fa0ce13d9e4efd38acfab8640fa42b07626a8d9d8b25ffb769cfee8e020541c4",
    sourceUrl: "https://x.com/flavioAd/status/2018423646314807569",
    sourcePage,
    sourceAuthor: "Course 11 production team; practitioner context from @flavioAd",
    sourceDate: "2026-08-23",
    verifiedOn,
    surface: "codex-app",
    captureMethod,
    alt: "Current Codex desktop composer controls showing the disposable course11-codex-demo folder, Local execution, and demo acceptance-first branch.",
    caption: "Current first-party Codex desktop context controls. Confirm the intended folder, execution context, and branch before a client task so work lands in the reviewable place you agreed.",
    boundary: "The capture documents dated controls in one app build. It does not establish that every plan or environment exposes the same labels, so current official documentation governs when it differs.",
    rightsBasis,
    rightsEvidencePath,
    visiblePublicIdentifiers: ["course11-codex-demo", "demo/acceptance-first"],
    privacyReview: "The crop excludes the account name, sidebar, task history, and unrelated windows. The workspace and branch names were invented for the course; no credentials, person names, or customer data appear.",
  },
  {
    id: "fig-3",
    src: "/courses/make-money-with-codex/figures/fig-03-codex-cli-composer.jpg",
    webp: "/courses/make-money-with-codex/figures/fig-03-codex-cli-composer.webp",
    width: 1600,
    height: 1003,
    sha256: "9551ca2e724aaef4288e35e9084ae4b89923339d4964d84371bda6af1ba457b1",
    webpSha256: "29e8b697f6b27b4fbcda612ed9dbe4a39903cd060f982a7eb7115c57eade83ad",
    sourceUrl: "https://github.com/openai/codex/blob/343074d4207d572809bd8cea15f4be1d09d98e0b/.github/codex-cli-splash.png",
    sourcePage: "https://github.com/openai/codex/tree/343074d4207d572809bd8cea15f4be1d09d98e0b",
    sourceAuthor: "OpenAI on GitHub",
    verifiedOn,
    surface: "codex-cli",
    captureMethod: "official-repository-image",
    alt: "Official Codex CLI image showing an explain-codebase request, repository inspection reasoning, and an updated four-step plan.",
    caption: "Authentic Codex CLI illustration from the OpenAI Codex repository at immutable commit 343074d. It shows a plan as a reviewable control surface before deeper exploration.",
    boundary: "The image is historical. Its visible v0.0.0, model label, directory, and interface state do not promise current availability, behaviour, pricing, or plan entitlement.",
    rightsBasis: "apache-2.0-pinned-source",
    visiblePublicIdentifiers: ["codex-rs", "gpt-5.2-codex", "historical v0.0.0 label"],
    privacyReview: "The official repository image contains no credentials, account identifiers, customer data, or personal names. Its visible repository and model labels are public historical context.",
  },
  {
    id: "fig-4",
    src: "/courses/make-money-with-codex/figures/fig-04-codex-cli-preflight.png",
    webp: "/courses/make-money-with-codex/figures/fig-04-codex-cli-preflight.webp",
    width: 1600,
    height: 900,
    sha256: "b257ccc36242d50722e79245c2b0a4c5a0890ceb6ef47bae02203a52a755d08c",
    webpSha256: "3bdc02e86c1a66820b7ad9c0cfce2f33a2d9e670b190861aa21e00174173c152",
    sourceUrl: "https://x.com/rudrank/status/2015694268929909129",
    sourcePage,
    sourceAuthor: "Course 11 production team; practitioner context from @rudrank",
    sourceDate: "2026-08-23",
    verifiedOn,
    surface: "codex-cli",
    captureMethod,
    alt: "Rendered transcript from an actual Codex CLI read-only preflight showing scope, risks, verification steps, and a revise decision for a synthetic project.",
    caption: "Actual Codex CLI transcript from a read-only, ephemeral run, rendered into a first-party teaching figure for legibility. The decision remains revise until every acceptance checkbox has reviewable evidence.",
    boundary: "The run inspected two tiny synthetic files. It demonstrates an evidence-first preflight, not implementation quality, general model accuracy, time saved, or a commercial result.",
    rightsBasis,
    rightsEvidencePath,
    visiblePublicIdentifiers: ["/tmp/course11-codex-demo", "gpt-5.6-sol", "OpenAI Codex v0.149.0-alpha.4"],
    privacyReview: "The disposable path, model label, and CLI version are visible. Transport warnings, plugin warnings, token count, and the ephemeral session ID were omitted; no credentials, account identifiers, or customer data appear.",
  },
  {
    id: "fig-5",
    src: "/courses/make-money-with-codex/figures/fig-05-delivery-dashboard.png",
    webp: "/courses/make-money-with-codex/figures/fig-05-delivery-dashboard.webp",
    width: 1600,
    height: 900,
    sha256: "8b86e9590b0a14df123b066aab8d611980a1238f3afe44f4b8ded11ba2ab3ec1",
    webpSha256: "5b2af9979c69453d61ee1b7de7157d1eb391fa9a1aaeeee5bd3ee8faf7994bb3",
    sourceUrl: "https://x.com/billyjhowell/status/2082824949195022403",
    sourcePage,
    sourceAuthor: "Course 11 production team; practitioner context from @billyjhowell",
    sourceDate: "2026-08-23",
    verifiedOn,
    surface: "product-output",
    captureMethod,
    alt: "Synthetic Northstar Ops client delivery dashboard showing accepted, in-review, and blocked milestones beside an acceptance-evidence checklist.",
    caption: "First-party synthetic client dashboard. It models a useful delivery surface: milestone status, missing evidence, a stop rule, and the current human decision in one view.",
    boundary: "This fixture contains invented data and proves only that the teaching pattern exists. It does not establish correctness, a paying customer, demand, or revenue.",
    rightsBasis,
    rightsEvidencePath,
    visiblePublicIdentifiers: ["Northstar Ops"],
    privacyReview: "Northstar Ops and every milestone are invented course data. No third-party interface pixels, credentials, account identifiers, person names, or customer records appear.",
  },
  {
    id: "fig-6",
    src: "/courses/make-money-with-codex/figures/fig-06-proof-of-value.png",
    webp: "/courses/make-money-with-codex/figures/fig-06-proof-of-value.webp",
    width: 1600,
    height: 900,
    sha256: "5dd3a59c21fd5ff630ad7d2bbbfaf8f97df9f6e16894341b9e5db47511a554d1",
    webpSha256: "b992073cf6c21f157b347dae804410f1520454174c3512de9c6f7eb49a744fe0",
    sourceUrl: "https://x.com/fkadev/status/2082567881171050496",
    sourcePage,
    sourceAuthor: "Course 11 production team; practitioner context from @fkadev",
    sourceDate: "2026-08-23",
    verifiedOn,
    surface: "product-output",
    captureMethod,
    alt: "Synthetic Signal Triage proof-of-value prototype showing approved input, rule-based triage, human review, a named receipt, and explicit next-test evidence.",
    caption: "First-party synthetic proof-of-value prototype. It turns a buyer hypothesis into a concrete review flow, records what was observed, and names the next falsifiable test.",
    boundary: "This illustrative workflow does not prove demand, production readiness, correctness, time saved, sales, or income.",
    rightsBasis,
    rightsEvidencePath,
    visiblePublicIdentifiers: ["Signal Triage"],
    privacyReview: "Signal Triage, its records, and its findings are invented course data. No external brand artwork, credentials, account identifiers, person names, or customer data appear.",
  },
  {
    id: "fig-7",
    src: "/courses/make-money-with-codex/figures/fig-07-digital-product.png",
    webp: "/courses/make-money-with-codex/figures/fig-07-digital-product.webp",
    width: 1600,
    height: 900,
    sha256: "e0fc4fb37a67cd6874d979931b24168ef820c457342920b583314d73ac5bc16e",
    webpSha256: "a2da2117f919132fb8e04ca4e3307720556e1911b1023a59e6ad04eee17ac310",
    sourceUrl: "https://x.com/devze_ro/status/2082886427600457833",
    sourcePage,
    sourceAuthor: "Course 11 production team; practitioner context from @devze_ro",
    sourceDate: "2026-08-23",
    verifiedOn,
    surface: "product-output",
    captureMethod,
    alt: "Synthetic Delivery Economics Playbook reader with a table of contents, base, upside, and downside price-floor examples, and an evidence-ceiling note.",
    caption: "First-party synthetic digital-product fixture. It shows how reusable knowledge can package worked scenarios while keeping assumptions and the evidence ceiling visible.",
    boundary: "The amounts are fictional worked examples, not prices, market rates, sales, income forecasts, or evidence that anyone purchased the product.",
    rightsBasis,
    rightsEvidencePath,
    visiblePublicIdentifiers: ["Delivery Economics Playbook", "fictional dollar examples"],
    privacyReview: "The title, reader text, and dollar examples were written for the course. No third-party book text, credentials, account identifiers, person names, or customer data appear.",
  },
  {
    id: "fig-8",
    src: "/courses/make-money-with-codex/figures/fig-08-review-receipt.png",
    webp: "/courses/make-money-with-codex/figures/fig-08-review-receipt.webp",
    width: 1600,
    height: 900,
    sha256: "d9dfc98a56aa4925730f30ab47a18421da6498118d034f7ea9b44a25382e624e",
    webpSha256: "89b02b8f53769a91f4480ffa2169b3ebda86f23da0358bd4ad22108bb1739075",
    sourceUrl: "https://x.com/nateberkopec/status/2015977728621871370",
    sourcePage,
    sourceAuthor: "Course 11 production team; practitioner context from @nateberkopec",
    sourceDate: "2026-08-23",
    verifiedOn,
    surface: "repository-handoff",
    captureMethod,
    alt: "Synthetic repository review receipt with two reproduced findings, boundary-case verification, review scope, and an explicit human decision.",
    caption: "First-party synthetic review receipt. The sellable outcome is not an automated finding alone; it is a reproduced issue linked to test evidence, scope, and a human decision.",
    boundary: "The fixture is not an external repository or public platform capture. It does not establish a general Codex accuracy rate, a defect-free delivery, or a commercial result.",
    rightsBasis,
    rightsEvidencePath,
    visiblePublicIdentifiers: ["demo/quote-hardening", "demo/quote.ts", "demo/ledger.ts"],
    privacyReview: "The branch, file names, defects, and test results are invented for the course. No external repository interface, handle, avatar, credentials, or customer data appear.",
  },
  {
    id: "fig-9",
    src: "/courses/make-money-with-codex/figures/fig-09-delivery-receipt.png",
    webp: "/courses/make-money-with-codex/figures/fig-09-delivery-receipt.webp",
    width: 1600,
    height: 900,
    sha256: "16f4e99fa8d0ebb57f2926f417ff4670be112ec96b553294e5cbff2588b99a13",
    webpSha256: "f8ed3a111d23ab9f6c0611da593d5c759b6f1f6c087702c216a87353830379ea",
    sourceUrl: "https://x.com/steipete/status/2010895856338088212",
    sourcePage,
    sourceAuthor: "Course 11 production team; practitioner context from @steipete",
    sourceDate: "2026-08-23",
    verifiedOn,
    surface: "repository-handoff",
    captureMethod,
    alt: "Synthetic repository delivery receipt listing three separated commits, passed checks, rollback instructions, next review, and a not-merged status.",
    caption: "First-party synthetic repository handoff. Small commits, named checks, rollback instructions, and a next-review owner make a Codex-assisted delivery inspectable and reversible.",
    boundary: "The fixture is not a GitHub screenshot or proof of deployment, time saved, safety in another repository, demand, sales, or income.",
    rightsBasis,
    rightsEvidencePath,
    visiblePublicIdentifiers: ["demo/acceptance-first", "a31f6c2", "c84a19e", "f16d5b0"],
    privacyReview: "The branch, commit hashes, messages, checks, rollback plan, and review state are invented for the course. No external repository interface, handle, avatar, credentials, or customer data appear.",
  },
] as const satisfies readonly CodexIncomeFigure[];

export const MAKE_MONEY_WITH_CODEX_FIGURE_BY_ID = Object.fromEntries(
  MAKE_MONEY_WITH_CODEX_FIGURES.map((figure) => [figure.id, figure]),
) as Record<string, CodexIncomeFigure>;
