import type { CodexIncomeSource, EvidenceClass } from "./types";

export const EVIDENCE_LABELS: Record<EvidenceClass, {
  readonly short: string;
  readonly title: string;
  readonly meaning: string;
}> = {
  "commercial-signal": {
    short: "Reported signal",
    title: "Reported commercial signal",
    meaning: "A named source reports a contract request, growth, or another commercial event. It is not an audited profit claim and does not establish a typical return.",
  },
  "paid-offer": {
    short: "Offer / intent",
    title: "Paid offer or productisation intent",
    meaning: "A creator publicly offers a paid tier or says the work was productised. The source does not confirm sales, revenue, or profit.",
  },
  "business-process": {
    short: "Process evidence",
    title: "Business process or output evidence",
    meaning: "A source shows a demo, released product, time saving, reach, or delivery workflow. It is useful operational evidence, not earnings evidence.",
  },
  "official-workflow": {
    short: "Official guidance",
    title: "Official Codex workflow guidance",
    meaning: "OpenAI documentation establishes a feature or recommended workflow. It makes no promise that using the feature will generate income.",
  },
  "scope-exclusion": {
    short: "Excluded",
    title: "Scope exclusion",
    meaning: "The source is useful for correcting a tempting mistake, but it is not evidence that Codex caused a commercial result.",
  },
};

const accessedOn = "2026-08-23";
const officialDocsAccessedOn = "2026-08-24";

export const CODEX_INCOME_SOURCES = [
  {
    id: "academy-builders",
    title: "Codex for Builders",
    publisher: "OpenAI Academy",
    kind: "openai-academy",
    evidenceClass: "official-workflow",
    url: "https://academy.openai.com/public/clubs/builders-etkn1/resources/codex-for-builders",
    accessedOn,
    publishedOn: "2025-08-07",
    updatedOn: "2026-06-02",
    supports: "Codex surfaces and suitable work such as codebase orientation, documentation, debugging, migrations, features, and CI/CD automation.",
    boundary: "This is product education. It supports workflow claims, not income claims.",
  },
  {
    id: "academy-bootcamp",
    title: "Codex Bootcamp",
    publisher: "OpenAI Academy",
    kind: "openai-academy",
    evidenceClass: "official-workflow",
    url: "https://academy.openai.com/en/public/clubs/builders-etkn1/resources/codex-bootcamp-2026-07-18",
    accessedOn,
    publishedOn: "2026-07-18",
    supports: "Plan mode, shared context, approvals, sandboxing, skills, worktrees, automation, subagents, the SDK, CI, security, and review.",
    boundary: "The bootcamp teaches capabilities and controls. It does not validate a business model or a price.",
  },
  {
    id: "academy-small-business",
    title: "A practical introduction to Codex for developers at small businesses",
    publisher: "OpenAI Academy",
    kind: "openai-academy",
    evidenceClass: "official-workflow",
    url: "https://academy.openai.com/public/clubs/small-business-ipf4m/events/a-practical-introduction-to-codex-for-developers-at-small-businesses-3jb04hi07p",
    accessedOn,
    eventOn: "2026-08-27",
    supports: "An upcoming event description, as of the course's 2026-08-23 research cutoff, presents a review-first path from customer need to scoped plan, tested change, and human handoff for lean teams and agencies.",
    boundary: "This is prospective event-description evidence, not evidence that a session occurred or that any service will sell.",
  },
  {
    id: "academy-goliath",
    title: "Goliath Data: From Three People to 20 in Chattanooga",
    publisher: "OpenAI Academy",
    kind: "openai-academy",
    evidenceClass: "commercial-signal",
    url: "https://academy.openai.com/public/blogs/goliath-data-from-three-people-to-20-in-chattanooga",
    accessedOn,
    publishedOn: "2026-08-14",
    supports: "The case reports that a prospect requested a $10,000 per month contract after a tailored feature demo; Goliath estimated about $40 of compute and reported other growth and operational outcomes.",
    boundary: "These are Academy-published company reports. The article does not confirm signed or collected revenue, isolate Codex as the cause, audit profit, or establish a typical return.",
  },
  {
    id: "academy-proaction",
    title: "How Colin Knudsen uses Codex to turn customer conversations into working demos",
    publisher: "OpenAI Academy",
    kind: "openai-academy",
    evidenceClass: "business-process",
    url: "https://academy.openai.com/public/blogs/colin-knudsen-proaction-codex-customer-demos",
    accessedOn,
    publishedOn: "2026-08-05",
    supports: "A five-person startup used sandboxed, customer-specific demos and handed engineers transcripts, screenshots, and a working prototype.",
    boundary: "The account reports movement to the front of an 18-vendor evaluation. It does not report a sale, price, revenue, or profit caused by Codex.",
  },
  {
    id: "academy-marco",
    title: "Marco Salsiccia builds accessible apps with Codex",
    publisher: "OpenAI Academy",
    kind: "openai-academy",
    evidenceClass: "business-process",
    url: "https://academy.openai.com/public/blogs/marco-salsiccia-builds-accessible-apps-with-codex",
    accessedOn,
    publishedOn: "2026-08-14",
    supports: "The creator reports shipping multiple native apps, reaching more than 11,500 users with one app, and converting a web app to iOS in less than a day while retaining human accessibility testing.",
    boundary: "Shipping, reach, and reported speed are not sales or profit. The article does not disclose monetisation results.",
  },
  {
    id: "academy-contractor-exclusion",
    title: "How ChatGPT Built a Contractor's Back Office",
    publisher: "OpenAI Academy",
    kind: "openai-academy",
    evidenceClass: "scope-exclusion",
    url: "https://academy.openai.com/public/blogs/how-chatgpt-became-a-contractors-back-office-2026-05-07",
    accessedOn,
    publishedOn: "2026-05-08",
    supports: "A boundary example for distinguishing ChatGPT results from future plans to use Codex.",
    boundary: "The reported time, inbound, and revenue outcomes concern ChatGPT workflows, not Codex. This course does not count them as Codex income evidence.",
  },
  {
    id: "academy-business-ops",
    title: "How business operations teams use Codex [Recording]",
    publisher: "OpenAI Academy",
    kind: "openai-academy",
    evidenceClass: "business-process",
    url: "https://academy.openai.com/en/public/clubs/work-users-ynjqu/videos/how-business-operations-teams-use-codex-2026-06-17",
    accessedOn,
    publishedOn: "2026-06-18",
    supports: "Operational patterns such as dashboards, weekly updates, decision briefs, and recurring workflows.",
    boundary: "A useful business workflow can still have negative economics. Measure the before and after process before pricing it.",
  },
  {
    id: "academy-account-brief",
    title: "Turn scattered account updates into shared team context",
    publisher: "OpenAI Academy",
    kind: "openai-academy",
    evidenceClass: "official-workflow",
    url: "https://academy.openai.com/public/clubs/champions-ecqup/resources/turn-scattered-account-updates-into-shared-team-context-2026-06-12",
    accessedOn,
    publishedOn: "2026-06-12",
    supports: "A scoped business workflow using approved sources, explicit planning, and human review before broader access or deployment.",
    boundary: "The example is a control pattern. It does not justify connecting to client systems without authorisation.",
  },
  {
    id: "openai-app",
    title: "ChatGPT desktop app",
    publisher: "OpenAI",
    kind: "openai-doc",
    evidenceClass: "official-workflow",
    url: "https://learn.chatgpt.com/docs/app",
    accessedOn: officialDocsAccessedOn,
    supports: "Selecting Codex and choosing a chat, project, or folder as the working context in the desktop app.",
    boundary: "Interface labels and model choices can change. Follow the current product UI when it differs from a dated figure.",
  },
  {
    id: "openai-auth",
    title: "Authentication",
    publisher: "OpenAI",
    kind: "openai-doc",
    evidenceClass: "official-workflow",
    url: "https://learn.chatgpt.com/docs/auth",
    accessedOn: officialDocsAccessedOn,
    supports: "The distinction between ChatGPT-plan access and usage-based API-key billing for local surfaces, plus the cloud sign-in requirement.",
    boundary: "Pricing, quotas, models, and plan entitlements can change. Verify the live account and official pricing pages before quoting a client.",
  },
  {
    id: "openai-pricing",
    title: "Pricing",
    publisher: "OpenAI",
    kind: "openai-doc",
    evidenceClass: "official-workflow",
    url: "https://learn.chatgpt.com/docs/pricing",
    accessedOn: officialDocsAccessedOn,
    supports: "The plan, surface, API-key, pricing, credit, and usage-limit information displayed by OpenAI on the recorded observation date.",
    boundary: "Prices, credits, limits, models, regions, workspace policies, and plan entitlements are time-sensitive. Recheck the live official page and the actual account on every quote date.",
  },
  {
    id: "openai-prompting",
    title: "Prompting",
    publisher: "OpenAI",
    kind: "openai-doc",
    evidenceClass: "official-workflow",
    url: "https://learn.chatgpt.com/docs/prompting",
    accessedOn: officialDocsAccessedOn,
    supports: "Writing requests with a concrete outcome, relevant context, constraints, and verification criteria.",
    boundary: "A strong task specification reduces ambiguity but does not replace customer validation or professional review.",
  },
  {
    id: "openai-security",
    title: "Agent approvals & security",
    publisher: "OpenAI",
    kind: "openai-doc",
    evidenceClass: "official-workflow",
    url: "https://learn.chatgpt.com/docs/agent-approvals-security",
    accessedOn: officialDocsAccessedOn,
    supports: "Sandbox and approval controls, least privilege, and caution with untrusted inputs.",
    boundary: "Tool controls reduce risk but do not transfer legal responsibility away from the service provider or client.",
  },
  {
    id: "openai-worktrees",
    title: "Worktrees",
    publisher: "OpenAI",
    kind: "openai-doc",
    evidenceClass: "official-workflow",
    url: "https://learn.chatgpt.com/docs/environments/git-worktrees",
    accessedOn: officialDocsAccessedOn,
    supports: "Isolated local work, handoff, and combined verification before integration.",
    boundary: "Isolation helps avoid collisions. It does not make an unreviewed change production-safe.",
  },
  {
    id: "openai-agents-md",
    title: "Custom instructions with AGENTS.md",
    publisher: "OpenAI",
    kind: "openai-doc",
    evidenceClass: "official-workflow",
    url: "https://learn.chatgpt.com/docs/agent-configuration/agents-md",
    accessedOn: officialDocsAccessedOn,
    supports: "Repository instructions, root-to-leaf precedence, and nested scope.",
    boundary: "Reusable instructions should contain stable constraints, not customer secrets or unsupported business promises.",
  },
  {
    id: "openai-skills",
    title: "Build skills",
    publisher: "OpenAI",
    kind: "openai-doc",
    evidenceClass: "official-workflow",
    url: "https://learn.chatgpt.com/docs/build-skills",
    accessedOn: officialDocsAccessedOn,
    supports: "Focused reusable instructions with progressive disclosure for repeatable workflows.",
    boundary: "Reuse can improve consistency. Every client context still needs its own authorisation and acceptance checks.",
  },
  {
    id: "openai-automations",
    title: "Scheduled tasks",
    publisher: "OpenAI",
    kind: "openai-doc",
    evidenceClass: "official-workflow",
    url: "https://learn.chatgpt.com/docs/automations",
    accessedOn: officialDocsAccessedOn,
    supports: "Testing and scheduling durable prompts for recurring local or web tasks.",
    boundary: "Unattended work raises permission and failure-handling risk. Start read-only, test manually, and define escalation paths.",
  },
  {
    id: "openai-code-review",
    title: "Code review",
    publisher: "OpenAI",
    kind: "openai-doc",
    evidenceClass: "official-workflow",
    url: "https://learn.chatgpt.com/docs/code-review",
    accessedOn: officialDocsAccessedOn,
    supports: "Reviewing a change, reporting findings, and verifying or reverting before delivery.",
    boundary: "Automated review supplements accountable human review. It is not a warranty that a deliverable is defect-free.",
  },
  {
    id: "github-openai-codex",
    title: "openai/codex",
    publisher: "OpenAI on GitHub",
    kind: "openai-github",
    evidenceClass: "official-workflow",
    url: "https://github.com/openai/codex",
    accessedOn,
    supports: "The first-party Codex CLI implementation, installation guidance, configuration, and release history.",
    boundary: "Repository capabilities and releases change. Pin versions in production delivery and re-run the client's verification gates.",
  },
  {
    id: "github-codex-action",
    title: "openai/codex-action",
    publisher: "OpenAI on GitHub",
    kind: "openai-github",
    evidenceClass: "official-workflow",
    url: "https://github.com/openai/codex-action",
    accessedOn,
    supports: "A first-party GitHub Action for controlled, least-privilege automation and review workflows.",
    boundary: "A CI action should receive only the permissions and secrets needed for the approved task.",
  },
  {
    id: "github-tokengauge-discussion",
    title: "Built with Codex: quality-adjusted LLM API cost comparisons across nine providers",
    publisher: "fablgen-agent in openai/codex Discussions",
    kind: "community-github",
    evidenceClass: "paid-offer",
    url: "https://github.com/openai/codex/discussions/38815",
    accessedOn,
    publishedOn: "2026-08-16",
    supports: "A creator describes using Codex for research, typed data, calculators, tests, browser verification, and a product with optional one-time paid tiers.",
    boundary: "The discussion discloses a paid offer, not the number of customers, revenue, profit, or the counterfactual without Codex.",
  },
  {
    id: "github-tokengauge-repo",
    title: "fablgen-agent/tokengauge",
    publisher: "fablgen-agent on GitHub",
    kind: "community-github",
    evidenceClass: "business-process",
    url: "https://github.com/fablgen-agent/tokengauge",
    accessedOn,
    supports: "Inspectable source and releases for the TokenGauge product described in the Codex discussion.",
    boundary: "Source code confirms an artefact exists. It does not independently confirm the commercial outcome of the offer.",
  },
  {
    id: "openai-community",
    title: "Codex community",
    publisher: "OpenAI Developers",
    kind: "openai-doc",
    evidenceClass: "business-process",
    url: "https://developers.openai.com/community",
    accessedOn,
    supports: "An OpenAI-curated index of original community posts and media used as figure locators in this course.",
    boundary: "Curation does not independently verify every practitioner's timing, quality, business, or causal claim.",
  },
  {
    id: "x-ashe-productized",
    title: "Productized video hub built with Codex",
    publisher: "@ashebytes on X",
    kind: "x-post",
    evidenceClass: "paid-offer",
    url: "https://x.com/ashebytes/status/2029374748061516164",
    accessedOn,
    publishedOn: "2026-03-05",
    supports: "The creator says interest led them to productise a video hub made with Codex.",
    boundary: "The post does not disclose price, customers, collected revenue, cost, or profit.",
  },
  {
    id: "x-pedro-build-time",
    title: "Tuist clean-build migration with Codex",
    publisher: "@pepicrft on X",
    kind: "x-post",
    evidenceClass: "business-process",
    url: "https://x.com/pepicrft/status/2019079104029442206",
    accessedOn,
    publishedOn: "2026-02-04",
    supports: "A practitioner reports a Codex-assisted migration that reduced a clean build from 110.8 seconds to 22.3 seconds and took a few agent hours.",
    boundary: "This is a self-reported engineering outcome. It is not a revenue claim and does not establish the same result in another repository.",
  },
  {
    id: "x-este-productivity",
    title: "Codex desktop productivity and MVP workflow",
    publisher: "@EstePrimeWorld on X",
    kind: "x-post",
    evidenceClass: "business-process",
    url: "https://x.com/EstePrimeWorld/status/2081217288414409071",
    accessedOn,
    publishedOn: "2026-07-26",
    supports: "A practitioner reports higher productivity and building features and MVPs with Codex; the post includes a real Codex desktop view.",
    boundary: "The post offers no objective productivity measurement or commercial result.",
  },
  {
    id: "x-fka-demo",
    title: "Three.js product demo built with Codex",
    publisher: "@fkadev on X",
    kind: "x-post",
    evidenceClass: "business-process",
    url: "https://x.com/fkadev/status/2082567881171050496",
    accessedOn,
    publishedOn: "2026-07-29",
    supports: "A creator shows a Codex-built Three.js demo and reports an approximately 20-minute build.",
    boundary: "The post explicitly says the work is not polished. It does not show a sale, production readiness, or reproducible timing.",
  },
  {
    id: "x-billy-dashboard",
    title: "Creator-reported five-minute 3D-printer dashboard build",
    publisher: "@billyjhowell on X",
    kind: "x-post",
    evidenceClass: "business-process",
    url: "https://x.com/billyjhowell/status/2082824949195022403",
    accessedOn,
    publishedOn: "2026-07-30",
    supports: "The creator shows a working dashboard and reports that it was live about five minutes after an on-a-whim request.",
    boundary: "The image is output evidence, not proof of correctness, safety, demand, or earnings.",
  },
  {
    id: "x-devzero-reader",
    title: "Experimental EPUB reader built with Codex",
    publisher: "@devze_ro on X",
    kind: "x-post",
    evidenceClass: "business-process",
    url: "https://x.com/devze_ro/status/2082886427600457833",
    accessedOn,
    publishedOn: "2026-07-30",
    supports: "A creator shows an open-source EPUB reader written in C and built with Codex.",
    boundary: "The creator calls the app experimental and under heavy development. The post makes no commercial claim.",
  },
  {
    id: "x-nate-review",
    title: "Codex code-review findings manually verified",
    publisher: "@nateberkopec on X",
    kind: "x-post",
    evidenceClass: "business-process",
    url: "https://x.com/nateberkopec/status/2015977728621871370",
    accessedOn,
    publishedOn: "2026-01-27",
    supports: "A practitioner shows a GitHub review in which two Codex findings were manually checked and accepted as correct.",
    boundary: "One reviewed change does not establish a universal defect-detection rate or replace human verification.",
  },
  {
    id: "x-flavio-app",
    title: "Codex desktop app workspace view",
    publisher: "@flavioAd on X",
    kind: "x-post",
    evidenceClass: "business-process",
    url: "https://x.com/flavioAd/status/2018423646314807569",
    accessedOn,
    publishedOn: "2026-02-02",
    supports: "A real Codex desktop image showing projects, tasks, workspace choices, automations, and skills at that date.",
    boundary: "The image documents a dated interface. It does not establish product quality or business impact.",
  },
  {
    id: "x-kr0der-plan",
    title: "Codex CLI plan mode",
    publisher: "@kr0der on X",
    kind: "x-post",
    evidenceClass: "business-process",
    url: "https://x.com/kr0der/status/2015711721092948064",
    accessedOn,
    publishedOn: "2026-01-26",
    supports: "A dated Codex CLI screenshot and practitioner account of plan mode.",
    boundary: "Context usage and perceived thoroughness are anecdotal. Use current official documentation for current commands.",
  },
  {
    id: "x-rudrank-fix",
    title: "Codex CLI root-cause and fix output",
    publisher: "@rudrank on X",
    kind: "x-post",
    evidenceClass: "business-process",
    url: "https://x.com/rudrank/status/2015694268929909129",
    accessedOn,
    publishedOn: "2026-01-26",
    supports: "A real Codex CLI completion excerpt describing a root cause and implementation change.",
    boundary: "A completion summary is not independent proof that the fix passed its full acceptance suite.",
  },
  {
    id: "x-steipete-pr",
    title: "Codex separates fixes from a messy pull request",
    publisher: "@steipete on X",
    kind: "x-post",
    evidenceClass: "business-process",
    url: "https://x.com/steipete/status/2010895856338088212",
    accessedOn,
    publishedOn: "2026-01-13",
    supports: "A practitioner shows a GitHub handoff with three separated commits and reports adopting the workflow.",
    boundary: "The post does not quantify saved time or establish that the changes were safe for another client or repository.",
  },
] as const satisfies readonly CodexIncomeSource[];

export const CODEX_INCOME_SOURCE_BY_ID = Object.fromEntries(
  CODEX_INCOME_SOURCES.map((source) => [source.id, source]),
) as Record<string, CodexIncomeSource>;
