import {
  PRODUCT_MANAGEMENT_CONTENT_LOCALE,
  PRODUCT_MANAGEMENT_COURSE_ID,
  type ProductManagementCourseManifest,
  type ProductManagementModuleManifest,
  type ProductManagementPhaseManifest,
} from "./types";

export const PRODUCT_MANAGEMENT_PHASES = [
  {
    id: "imagine",
    order: 1,
    moduleSlugs: [
      "product-judgment-operating-model",
      "vision-strategy-business-model",
      "customer-market-discovery",
      "synthesis-opportunity-definition",
    ],
  },
  {
    id: "decide",
    order: 2,
    moduleSlugs: [
      "outcomes-metrics-analytics",
      "prioritization-roadmaps-portfolio",
      "solution-discovery-experiments",
      "product-design-experience-systems",
      "requirements-prd-decisions",
    ],
  },
  {
    id: "build",
    order: 3,
    moduleSlugs: [
      "ai-capability-architecture",
      "delivery-engineering-ai-agents",
      "quality-safety-governance",
    ],
  },
  {
    id: "launch",
    order: 4,
    moduleSlugs: [
      "launch-go-to-market-growth",
      "experimentation-operations-leadership",
    ],
  },
] as const satisfies readonly ProductManagementPhaseManifest[];

export const PRODUCT_MANAGEMENT_MODULES = [
  {
    slug: "product-judgment-operating-model",
    order: 1,
    phaseId: "imagine",
    minutes: 50,
    sourceIds: [
      "pmaker-home",
      "pmaker-role",
      "pmaker-workflow",
      "gitlab-product-handbook",
      "scrum-guide",
      "github-awesome-product-management",
      "google-pair-guidebook",
      "atlassian-daci",
    ],
    conceptDomainIds: ["role-leadership", "delivery-collaboration", "operations-leadership"],
  },
  {
    slug: "vision-strategy-business-model",
    order: 2,
    phaseId: "imagine",
    minutes: 60,
    sourceIds: [
      "pmaker-product-types",
      "pmaker-industry-map",
      "pmaker-business-models",
      "atlassian-product-strategy",
      "strategyzer-value-proposition",
      "gitlab-tiering-guidance",
      "rumelt-strategy-kernel",
      "sba-market-research",
    ],
    conceptDomainIds: ["strategy-business", "definition-scope", "launch-growth"],
  },
  {
    slug: "customer-market-discovery",
    order: 3,
    phaseId: "imagine",
    minutes: 65,
    sourceIds: [
      "pmaker-need",
      "pmaker-need-sources",
      "pmaker-real-vs-fake",
      "pmaker-interview",
      "nng-user-interviews",
      "govuk-user-research",
      "govuk-user-research-consent",
      "govuk-research-privacy",
    ],
    conceptDomainIds: ["discovery-research", "definition-scope"],
  },
  {
    slug: "synthesis-opportunity-definition",
    order: 4,
    phaseId: "imagine",
    minutes: 60,
    sourceIds: [
      "pmaker-definition",
      "pmaker-scene-anchor",
      "pmaker-worth-doing",
      "product-talk-opportunity-tree",
      "wcag-quickref",
    ],
    conceptDomainIds: ["discovery-research", "definition-scope", "strategy-business"],
  },
  {
    slug: "outcomes-metrics-analytics",
    order: 5,
    phaseId: "decide",
    minutes: 60,
    sourceIds: [
      "pmaker-metrics-system",
      "pmaker-north-star",
      "google-heart",
      "scrum-guide",
      "whatmatters-okr",
      "google-analytics-funnel",
      "google-analytics-cohort",
    ],
    conceptDomainIds: ["metrics-analytics", "experimentation", "operations-leadership"],
  },
  {
    slug: "prioritization-roadmaps-portfolio",
    order: 6,
    phaseId: "decide",
    minutes: 55,
    sourceIds: [
      "pmaker-backlog-priority",
      "pmaker-roadmap-blueprint",
      "github-product-manager-skills",
      "github-projects-docs",
      "github-public-roadmap",
      "gitlab-product-development-budgeting",
      "intercom-rice",
      "safe-wsjf",
      "agilebusiness-moscow",
    ],
    conceptDomainIds: ["prioritization-roadmaps", "strategy-business", "delivery-collaboration"],
  },
  {
    slug: "solution-discovery-experiments",
    order: 7,
    phaseId: "decide",
    minutes: 65,
    sourceIds: [
      "pmaker-worth-doing",
      "pmaker-five-second-test",
      "product-talk-opportunity-tree",
      "svpg-product-discovery",
    ],
    conceptDomainIds: ["experimentation", "discovery-research", "design-experience"],
  },
  {
    slug: "product-design-experience-systems",
    order: 8,
    phaseId: "decide",
    minutes: 70,
    sourceIds: [
      "pmaker-information-architecture",
      "pmaker-user-journey",
      "pmaker-four-states",
      "pmaker-design-system",
      "wcag-quickref",
    ],
    conceptDomainIds: ["design-experience", "requirements-technical", "risk-governance"],
  },
  {
    slug: "requirements-prd-decisions",
    order: 9,
    phaseId: "decide",
    minutes: 70,
    sourceIds: [
      "pmaker-workflow",
      "pmaker-data-model-first",
      "pmaker-three-part-prompt",
      "github-prd-development",
      "atlassian-prd",
    ],
    conceptDomainIds: ["requirements-technical", "definition-scope", "delivery-collaboration"],
  },
  {
    slug: "ai-capability-architecture",
    order: 10,
    phaseId: "build",
    minutes: 75,
    sourceIds: [
      "pmaker-model-selection",
      "pmaker-context-rag",
      "pmaker-agent-evaluation",
      "google-pair-guidebook",
      "openai-evals-guide",
      "google-rules-of-ml",
      "anthropic-effective-agents",
      "anthropic-agent-evals",
      "microsoft-foundry-rag",
      "microsoft-rag-information-retrieval",
      "microsoft-rag-evaluators",
      "aws-rag-evaluation-metrics",
      "google-sre-slo",
      "openai-ai-scorecard",
    ],
    conceptDomainIds: ["ai-products", "requirements-technical", "metrics-analytics"],
  },
  {
    slug: "delivery-engineering-ai-agents",
    order: 11,
    phaseId: "build",
    minutes: 70,
    sourceIds: [
      "pmaker-spec-before-code",
      "pmaker-one-thing-at-a-time",
      "pmaker-prototype-to-code",
      "pmaker-three-part-prompt",
      "github-projects-docs",
      "scrum-guide",
      "kanban-guide",
      "github-actions",
      "google-sre-canary",
      "github-copilot-agent-risks",
      "openai-codex-security",
    ],
    conceptDomainIds: ["delivery-collaboration", "requirements-technical", "ai-products"],
  },
  {
    slug: "quality-safety-governance",
    order: 12,
    phaseId: "build",
    minutes: 75,
    sourceIds: [
      "pmaker-launch-checklist",
      "pmaker-ai-code-check",
      "pmaker-prompt-injection",
      "nist-ai-rmf",
      "microsoft-hax",
      "owasp-llm-top-ten",
      "owasp-prompt-injection",
      "owasp-excessive-agency",
      "microsoft-foundry-rag",
      "anthropic-containment",
      "anthropic-agent-evals",
      "google-cloud-ai-operations",
      "eu-ai-act",
      "eu-ai-act-consolidated",
      "nist-genai-profile",
    ],
    conceptDomainIds: ["risk-governance", "ai-products", "requirements-technical"],
  },
  {
    slug: "launch-go-to-market-growth",
    order: 13,
    phaseId: "launch",
    minutes: 65,
    sourceIds: [
      "pmaker-lifecycle",
      "pmaker-business-models",
      "gitlab-product-marketing-handbook",
      "gitlab-tiering-guidance",
      "gitlab-deprecations-removals",
      "gitlab-product-development-flow",
      "google-cloud-ai-operations",
      "dave-mcclure-aarrr",
      "reforge-product-led-growth",
      "reforge-growth-loops",
    ],
    conceptDomainIds: ["launch-growth", "strategy-business", "metrics-analytics"],
  },
  {
    slug: "experimentation-operations-leadership",
    order: 14,
    phaseId: "launch",
    minutes: 70,
    sourceIds: [
      "pmaker-three-layers-validation",
      "pmaker-track-before-launch",
      "pmaker-real-data",
      "microsoft-experimentation-platform",
      "microsoft-experiment-pre",
      "microsoft-experiment-during",
      "gitlab-product-handbook",
      "gitlab-product-development-budgeting",
      "gitlab-tiering-guidance",
      "gitlab-deprecations-removals",
      "productboard-product-operations",
      "openai-evals-guide",
      "anthropic-agent-evals",
      "google-cloud-ai-operations",
    ],
    conceptDomainIds: [
      "experimentation",
      "operations-leadership",
      "role-leadership",
      "launch-growth",
    ],
  },
] as const satisfies readonly ProductManagementModuleManifest[];

export const PRODUCT_MANAGEMENT_COURSE_MANIFEST = {
  id: PRODUCT_MANAGEMENT_COURSE_ID,
  version: "1.0.0",
  displayNumber: 14,
  publishedOn: "2026-08-23",
  contentLocale: PRODUCT_MANAGEMENT_CONTENT_LOCALE,
  phases: PRODUCT_MANAGEMENT_PHASES,
  modules: PRODUCT_MANAGEMENT_MODULES,
} as const satisfies ProductManagementCourseManifest;
