import type { ProductManagementSourceRecord } from "./types";

const ACCESSED_ON = "2026-08-23";

export const PRODUCT_MANAGEMENT_SOURCES = [
  {
    id: "pmaker-home",
    title: "How products are imagined, designed, and built — in the age of AI",
    publisher: "PMaker",
    url: "https://pmaker.space/en/",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "The course's imagine–design–build–learn spine and its emphasis on judgment when building becomes faster.",
    boundary: "PMaker is the requested anchor and a practitioner curriculum, not a universal standard or an empirical effectiveness study.",
  },
  {
    id: "pmaker-role",
    title: "What a product manager does",
    publisher: "PMaker",
    url: "https://pmaker.space/en/basics/what-pm-does.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "The distinction between product judgment and the adjacent work of project management, analysis, design, and engineering.",
    boundary: "Role boundaries differ by organization, product type, seniority, and regulatory context.",
  },
  {
    id: "pmaker-workflow",
    title: "The product workflow",
    publisher: "PMaker",
    url: "https://pmaker.space/en/basics/product-workflow.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "A lifecycle in which every stage produces evidence or an artifact needed by the next stage, even when AI compresses execution time.",
    boundary: "The described workflow is a teaching model; real teams loop, overlap stages, and tailor artifacts to risk.",
  },
  {
    id: "pmaker-product-types",
    title: "Product types",
    publisher: "PMaker",
    url: "https://pmaker.space/en/basics/product-types.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "How product type changes users, buying motion, constraints, feedback speed, and the PM's work.",
    boundary: "Type labels are lenses rather than mutually exclusive categories.",
  },
  {
    id: "pmaker-industry-map",
    title: "Map an industry",
    publisher: "PMaker",
    url: "https://pmaker.space/en/basics/industry-map.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Mapping actors, value flows, power, substitutes, and constraints before selecting a product position.",
    boundary: "An industry map is a hypothesis that must be refreshed with current market evidence.",
  },
  {
    id: "pmaker-business-models",
    title: "Business models",
    publisher: "PMaker",
    url: "https://pmaker.space/en/basics/business-models.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Connecting who receives value, who pays, how revenue is captured, and where costs accumulate.",
    boundary: "A business-model pattern does not establish willingness to pay or unit economics for a specific product.",
  },
  {
    id: "pmaker-need",
    title: "What a need is",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/what-is-need.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Separating a user's stated feature request from the situation, desired state, motivation, and possible solutions.",
    boundary: "The three-layer distinction is a framing tool; claims about prevalence still need research and behavioral evidence.",
  },
  {
    id: "pmaker-need-sources",
    title: "Where product needs come from",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/need-sources.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Triangulating interviews, observation, support, sales, usage data, market change, and strategic constraints.",
    boundary: "No channel is automatically representative; sampling and incentive effects remain.",
  },
  {
    id: "pmaker-real-vs-fake",
    title: "Real versus weak demand signals",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/real-vs-fake.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Ranking observed behavior and costly commitments above compliments, opinions, and hypothetical intent.",
    boundary: "A signal's strength depends on context; absence of purchase is not decisive where users are not the buyers.",
  },
  {
    id: "pmaker-interview",
    title: "How to run a user interview",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/interview.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Reconstructing recent behavior with neutral prompts, artifacts, follow-up questions, and separate fact–inference columns.",
    boundary: "Interviews reveal mechanisms and language but do not estimate population frequency without an appropriate sampling design.",
  },
  {
    id: "pmaker-definition",
    title: "A product definition has three parts",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/definition-three-parts.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Defining a concrete target user, comparative core value, and explicit in-scope and out-of-scope boundaries.",
    boundary: "A crisp definition is a decision contract, not proof that the chosen opportunity is valuable.",
  },
  {
    id: "pmaker-scene-anchor",
    title: "Anchor the problem in a scene",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/scene-anchor.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Writing problems around a person, trigger, current behavior, friction, and desired progress.",
    boundary: "A vivid scenario can still be atypical; retain provenance and frequency evidence.",
  },
  {
    id: "pmaker-worth-doing",
    title: "Decide whether a problem is worth solving",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/worth-doing.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Testing importance, frequency, alternatives, willingness to switch, feasibility, and strategic fit before solution commitment.",
    boundary: "A screening canvas narrows uncertainty but does not replace experiments or financial analysis.",
  },
  {
    id: "pmaker-backlog-priority",
    title: "Backlog and priority",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/backlog-priority.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Keeping provenance with each opportunity, using Kano as a classification lens, and making prioritization assumptions discussable.",
    boundary: "Kano and scoring formulas support judgment; they do not produce an objectively correct order.",
  },
  {
    id: "pmaker-roadmap-blueprint",
    title: "Product evolution blueprint",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/roadmap-blueprint.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Sequencing falsifiable product hypotheses, minimum test scope, one decision metric, and a precommitted threshold.",
    boundary: "A three-horizon blueprint is useful for uncertainty; contractual delivery contexts may also require dates and dependencies.",
  },
  {
    id: "pmaker-metrics-system",
    title: "How to build a metrics system",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/metrics-system.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "A metric tree from product direction to diagnostic and actionable measures, plus explicit metric definitions.",
    boundary: "Metric trees encode hypotheses about causality; changes still require interpretation or experimentation.",
  },
  {
    id: "pmaker-north-star",
    title: "Choose one North Star",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/north-star.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Selecting a value-linked, influenceable, leading, understandable North Star and protecting it with guardrails.",
    boundary: "No single metric captures every stakeholder, externality, or phase of a product's lifecycle.",
  },
  {
    id: "pmaker-five-second-test",
    title: "The five-second test",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/five-second-test.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "A lightweight check of first-impression comprehension during solution discovery.",
    boundary: "It tests immediate comprehension, not usability, value, retention, or business viability.",
  },
  {
    id: "pmaker-information-architecture",
    title: "What information architecture is",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/what-is-ia.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Separating product structure, information grouping, navigation, and labels from screen decoration.",
    boundary: "Information architecture must be tested with representative content and users.",
  },
  {
    id: "pmaker-user-journey",
    title: "Map the user journey",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/user-journey.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Mapping triggers, steps, decisions, exits, emotions, recovery, and handoffs across an end-to-end job.",
    boundary: "A journey map is a model; observed paths and accessibility needs can contradict the workshop version.",
  },
  {
    id: "pmaker-four-states",
    title: "Design all four interface states",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/four-states.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Treating normal, empty, loading, and error states as requirements rather than polish.",
    boundary: "Complex products may require additional offline, partial, permission, stale, and conflict states.",
  },
  {
    id: "pmaker-design-system",
    title: "Build a minimal design system",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/design-system.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Using shared tokens and components to make product behavior and visual decisions consistent.",
    boundary: "A design system is an operating product with governance, not just a token list.",
  },
  {
    id: "pmaker-data-model-first",
    title: "Model the data before the interface",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/data-model-first.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Deriving entities, relationships, permissions, states, and lifecycle rules before committing to screens.",
    boundary: "A conceptual model is not a production database schema and needs engineering review.",
  },
  {
    id: "pmaker-three-part-prompt",
    title: "The three-part AI task contract",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/three-part-prompt.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Expressing an AI-assisted build task as an outcome, constraints, and testable acceptance criteria with edge cases.",
    boundary: "A strong prompt reduces ambiguity but does not replace domain review, testing, or secure engineering.",
  },
  {
    id: "pmaker-model-selection",
    title: "Model selection and fallbacks",
    publisher: "PMaker",
    url: "https://pmaker.space/en/learn/model-selection.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Choosing models by task-level quality, latency, cost, deployment, and fallback needs rather than a single leaderboard.",
    boundary: "Model capabilities, prices, and policies change; production choices require current benchmark and contract checks.",
  },
  {
    id: "pmaker-context-rag",
    title: "Retrieval-augmented generation",
    publisher: "PMaker",
    url: "https://pmaker.space/en/learn/rag.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "The retrieval–context–generation pipeline and the distinction between model memory and product knowledge.",
    boundary: "RAG is one architecture; it does not guarantee relevance, correctness, freshness, or authorization.",
  },
  {
    id: "pmaker-agent-evaluation",
    title: "Evaluate an agent",
    publisher: "PMaker",
    url: "https://pmaker.space/en/learn/agent-eval.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Evaluating task completion, trajectory, tool use, safety, latency, and cost rather than judging a demo transcript.",
    boundary: "An eval set is only as representative as its cases, graders, environment, and maintenance process.",
  },
  {
    id: "pmaker-spec-before-code",
    title: "Specification before code",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/spec-before-code.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Using AI first to expose assumptions, structure a change, and agree on acceptance before implementation.",
    boundary: "Up-front specification should remain lightweight and revisable as evidence changes.",
  },
  {
    id: "pmaker-one-thing-at-a-time",
    title: "One change at a time",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/one-thing-at-a-time.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Slicing AI-assisted work into reviewable, testable changes with bounded context.",
    boundary: "Tiny slices still need a coherent architecture and end-to-end release plan.",
  },
  {
    id: "pmaker-prototype-to-code",
    title: "Prototype to code",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/prototype-to-code.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Separating look-and-flow validation, real data wiring, edge states, and production hardening.",
    boundary: "A prototype validates selected assumptions only; it is not evidence of scalable or secure implementation.",
  },
  {
    id: "pmaker-launch-checklist",
    title: "Launch checklist",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/launch-checklist.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "A cross-functional release check spanning function, experience, data, security, recovery, and ownership.",
    boundary: "Release gates must be tailored to impact, regulation, deployment architecture, and rollback cost.",
  },
  {
    id: "pmaker-ai-code-check",
    title: "Security checks for AI-generated code",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/ai-code-check.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Checking secrets, authorization, injection paths, dependencies, and unsafe trust in generated output.",
    boundary: "A checklist is not a threat model, security review, dependency audit, or penetration test.",
  },
  {
    id: "pmaker-prompt-injection",
    title: "Prompt injection",
    publisher: "PMaker",
    url: "https://pmaker.space/en/learn/prompt-injection.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Treating untrusted instructions as data and bounding tool permissions and downstream actions.",
    boundary: "No single filter solves prompt injection; mitigations must be layered and tested against the actual system.",
  },
  {
    id: "pmaker-lifecycle",
    title: "The product lifecycle",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/lifecycle.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Adapting goals, metrics, investment, and product tactics across introduction, growth, maturity, and decline.",
    boundary: "Lifecycle stages are diagnostic abstractions; products and segments can occupy different stages simultaneously.",
  },
  {
    id: "pmaker-three-layers-validation",
    title: "Usable, useful, and used",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/three-layers-of-validation.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Separating usability, problem/solution value, and sustained behavior as different validation claims.",
    boundary: "The three layers do not by themselves establish business viability, fairness, safety, or causal impact.",
  },
  {
    id: "pmaker-track-before-launch",
    title: "Instrument before launch",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/track-before-launch.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Defining decision questions, events, properties, owners, and dashboards before release.",
    boundary: "Instrumentation must follow consent, minimization, retention, and data-quality requirements.",
  },
  {
    id: "pmaker-real-data",
    title: "Judge with real data",
    publisher: "PMaker",
    url: "https://pmaker.space/en/patterns/real-data.html",
    accessedOn: ACCESSED_ON,
    kind: "primary-course",
    supports: "Using production behavior and representative samples rather than internal enthusiasm as post-launch evidence.",
    boundary: "Observational data can be biased and confounded; it does not automatically identify causal effects.",
  },
  {
    id: "gitlab-product-handbook",
    title: "Product handbook",
    publisher: "GitLab",
    url: "https://handbook.gitlab.com/handbook/product/",
    accessedOn: ACCESSED_ON,
    kind: "open-source",
    license: "CC BY-SA 4.0",
    supports: "A transparent, versioned example of product principles, PM responsibilities, indicators, planning, and cross-functional operating practice.",
    boundary: "GitLab's handbook documents one company's operating model and should be adapted rather than copied as a universal process.",
  },
  {
    id: "gitlab-product-development-budgeting",
    title: "Product Development Budgeting Process",
    publisher: "GitLab",
    url: "https://handbook.gitlab.com/handbook/product-development/how-we-work/product-development-flow/product-development-budgeting/",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    license: "CC BY-SA 4.0",
    supports: "A current public example of preparing, vetting, prioritizing, budgeting, and communicating portfolio investment cases across product, engineering, design, research, and leadership.",
    boundary: "GitLab's investment and budgeting process is company-specific; teams need their own capital constraints, decision rights, accounting rules, and evidence thresholds.",
  },
  {
    id: "gitlab-tiering-guidance",
    title: "Tiering Strategy and Guidance for Product Managers",
    publisher: "GitLab",
    url: "https://handbook.gitlab.com/handbook/product/product-processes/tiering-guidance-for-features/",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    license: "CC BY-SA 4.0",
    supports: "A current public example of connecting buyer, value, feature maturity, packaging, product tier, pricing-change governance, adoption, and revenue considerations.",
    boundary: "GitLab's open-core tiers and pricing governance are one business-model implementation, not a universal pricing or willingness-to-pay method.",
  },
  {
    id: "gitlab-deprecations-removals",
    title: "Deprecations and Removals Policy",
    publisher: "GitLab",
    url: "https://handbook.gitlab.com/handbook/product/categories/gitlab-the-product/#deprecations--removals-policy",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    license: "CC BY-SA 4.0",
    supports: "A current public example of defining breaking changes, deprecation and removal states, customer-impact checks, migration communication, usage tracking, release windows, and accountable product ownership.",
    boundary: "GitLab's release cadence and deprecation policy fit its own products; notice periods, contractual support, migration duties, and legal obligations vary by product and customer.",
  },
  {
    id: "github-product-manager-skills",
    title: "PM-Skills",
    publisher: "Product on Purpose contributors",
    url: "https://github.com/product-on-purpose/pm-skills",
    accessedOn: ACCESSED_ON,
    kind: "open-source",
    license: "Apache-2.0",
    supports: "Versioned playbooks and templates for discovery, positioning, opportunity trees, prioritization, roadmaps, stories, and PRDs in AI-assisted work.",
    boundary: "Repository templates are practical scaffolds, not empirical evidence; verify current license and tailor every artifact to the decision.",
  },
  {
    id: "github-prd-development",
    title: "PRD development skill",
    publisher: "Product on Purpose contributors",
    url: "https://github.com/product-on-purpose/pm-skills/tree/main/skills/deliver-prd",
    accessedOn: ACCESSED_ON,
    kind: "open-source",
    license: "Apache-2.0",
    supports: "A Git-based, inspectable workflow connecting problem framing, evidence, solution scope, metrics, stories, and review.",
    boundary: "A template can create alignment only when inputs are evidence-grounded and the document remains live.",
  },
  {
    id: "github-projects-docs",
    title: "About Projects",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Connecting issues, pull requests, fields, views, iteration, and automation in a versioned delivery system.",
    boundary: "Tool features do not determine a team's product strategy, discovery quality, or governance model.",
  },
  {
    id: "github-awesome-product-management",
    title: "Awesome Product Management",
    publisher: "dend and contributors",
    url: "https://github.com/dend/awesome-product-management",
    accessedOn: ACCESSED_ON,
    kind: "open-source",
    license: "CC0-1.0",
    supports: "A broad, openly curated index spanning product foundations, research, strategy, collaboration, metrics, growth, and career practice.",
    boundary: "A curated index helps test coverage; each linked claim still needs evaluation at its original source.",
  },
  {
    id: "github-public-roadmap",
    title: "GitHub public roadmap",
    publisher: "GitHub",
    url: "https://github.com/github/roadmap",
    accessedOn: ACCESSED_ON,
    kind: "open-source",
    license: "CC BY 4.0",
    supports: "A real public artifact for examining release phases, product areas, deployment targets, feedback, and the boundary between direction and commitment.",
    boundary: "The repository exposes selected roadmap information, not GitHub's full strategy, prioritization evidence, or internal capacity model.",
  },
  {
    id: "gitlab-product-marketing-handbook",
    title: "Product and solution marketing handbook",
    publisher: "GitLab",
    url: "https://handbook.gitlab.com/handbook/marketing/brand-and-product-marketing/product-and-solution-marketing/",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "A public operating example for positioning, messaging, launch collaboration, sales enablement, and market feedback.",
    boundary: "This is a company-specific B2B operating model, not a complete GTM standard for every market.",
  },
  {
    id: "atlassian-product-strategy",
    title: "Product development strategy",
    publisher: "Atlassian",
    url: "https://www.atlassian.com/agile/product-management/product-development-strategy",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "Linking market research, business goals, concept testing, development, and launch in a product strategy.",
    boundary: "Vendor guidance is a useful overview and should be triangulated with research and the team's context.",
  },
  {
    id: "atlassian-prd",
    title: "Product requirements template",
    publisher: "Atlassian",
    url: "https://www.atlassian.com/software/confluence/templates/product-requirements",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "A concise collaborative PRD pattern for assumptions, options, requirements, questions, and supporting evidence.",
    boundary: "The template is tool-adjacent guidance; the course adds non-functional, data, AI-eval, and release contracts.",
  },
  {
    id: "strategyzer-value-proposition",
    title: "The Value Proposition Canvas",
    publisher: "Strategyzer",
    url: "https://www.strategyzer.com/library/the-value-proposition-canvas",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "Making explicit the relationship among customer jobs, pains, gains, and a proposed value proposition.",
    boundary: "Canvas completion is not validation; evidence is required for each claimed job, pain, gain, and fit.",
  },
  {
    id: "nng-user-interviews",
    title: "User interviews: How, when, and why to conduct them",
    publisher: "Nielsen Norman Group",
    url: "https://www.nngroup.com/articles/user-interviews/",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "Planning and conducting qualitative interviews while choosing methods suited to the research question.",
    boundary: "Interview findings require careful recruitment, synthesis, and triangulation; they are not population estimates.",
  },
  {
    id: "govuk-user-research",
    title: "User research in government services",
    publisher: "GOV.UK Service Manual",
    url: "https://www.gov.uk/service-manual/user-research",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Continuous user research, inclusive recruitment, research planning, ethical handling, and evidence throughout discovery, alpha, beta, and live service.",
    boundary: "The guidance is designed for UK public services; research governance and delivery constraints vary by domain and jurisdiction.",
  },
  {
    id: "product-talk-opportunity-tree",
    title: "Opportunity Solution Trees",
    publisher: "Product Talk",
    url: "https://www.producttalk.org/opportunity-solution-trees/",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "Connecting an outcome to evidence-backed opportunities, multiple solutions, and assumption tests.",
    boundary: "A tree improves traceability but can still encode weak research or prematurely selected outcomes.",
  },
  {
    id: "svpg-product-discovery",
    title: "The Four Big Risks",
    publisher: "Silicon Valley Product Group",
    url: "https://www.svpg.com/four-big-risks/",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "Testing value, usability, feasibility, and business viability before scaling delivery investment.",
    boundary: "SVPG guidance reflects a particular product operating model; regulated and contract-driven environments may need additional gates.",
  },
  {
    id: "google-heart",
    title: "Measuring the User Experience on a Large Scale",
    publisher: "Google Research",
    url: "https://research.google/pubs/measuring-the-user-experience-on-a-large-scale-user-centered-metrics-for-web-applications/",
    accessedOn: ACCESSED_ON,
    kind: "research",
    supports: "The HEART categories and the goals–signals–metrics process for user-centered product measurement.",
    boundary: "HEART is a framework for selecting measures, not a guarantee that a metric is valid or causally affected by a feature.",
  },
  {
    id: "wcag-quickref",
    title: "How to Meet WCAG 2.2: Quick Reference",
    publisher: "W3C Web Accessibility Initiative",
    url: "https://www.w3.org/WAI/WCAG22/quickref/",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Testable accessibility success criteria and implementation guidance across perception, operation, understanding, and robustness.",
    boundary: "Conformance checks are necessary but do not replace usability research with disabled people.",
  },
  {
    id: "google-pair-guidebook",
    title: "People + AI Guidebook",
    publisher: "Google People + AI Research",
    url: "https://pair.withgoogle.com/guidebook-v2/",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    license: "CC BY-NC-SA 4.0",
    supports: "Methods and patterns for deciding when AI adds value, data practices, explainability, control, trust calibration, and failure recovery.",
    boundary: "Patterns need contextual research and do not certify a product as safe, fair, or legally compliant.",
  },
  {
    id: "openai-evals-guide",
    title: "Evaluation best practices",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/evaluation-best-practices",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Task-specific evaluation objectives, representative datasets, explicit metrics and rubrics, typical, edge, and adversarial cases, human calibration of automated scoring, and continuous evaluation.",
    boundary: "The methodology remains useful, but OpenAI's legacy Evals dashboard and API are deprecated: existing evals become read-only on 31 October 2026 and the dashboard and API are scheduled to shut down on 30 November 2026. Keep implementation vendor-portable and consult the current deprecations page.",
  },
  {
    id: "google-rules-of-ml",
    title: "Rules of Machine Learning",
    publisher: "Google for Developers",
    url: "https://developers.google.com/machine-learning/guides/rules-of-ml",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Starting with a reliable end-to-end baseline, defining objectives and instrumentation, and adding model complexity only when it earns its operational cost.",
    boundary: "The rules are experienced engineering guidance, not a checklist that fits every generative-AI or regulated use case.",
  },
  {
    id: "anthropic-effective-agents",
    title: "Building effective agents",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/engineering/building-effective-agents",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Distinguishing fixed workflows from autonomous agents and selecting the simplest pattern that meets the task's flexibility needs.",
    boundary: "Provider examples are architectural guidance; claims about quality, cost, latency, and safety require product-specific evaluation.",
  },
  {
    id: "nist-ai-rmf",
    title: "Artificial Intelligence Risk Management Framework (AI RMF 1.0)",
    publisher: "U.S. National Institute of Standards and Technology",
    url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "The voluntary Govern, Map, Measure, and Manage functions for lifecycle AI-risk management across organizations and use contexts.",
    boundary: "AI RMF 1.0 is not a certification, legal safe harbor, or exhaustive control catalog. NIST states that version 1.0 is being revised; teams must check the current framework and apply applicable law, policy, and domain controls.",
  },
  {
    id: "microsoft-hax",
    title: "Microsoft HAX Toolkit",
    publisher: "Microsoft",
    url: "https://www.microsoft.com/en-us/haxtoolkit/",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Evidence-based human–AI interaction guidelines, failure planning, recovery, expectation-setting, and cross-functional requirements.",
    boundary: "HAX supports interaction design and planning; it is not a complete model-risk, security, or compliance framework.",
  },
  {
    id: "owasp-llm-top-ten",
    title: "2025 Top 10 Risk & Mitigations for LLMs and Gen AI Apps",
    publisher: "OWASP Gen AI Security Project",
    url: "https://genai.owasp.org/llm-top-10/",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    license: "CC BY-SA 4.0",
    supports: "The versioned 2025 awareness taxonomy for prompt injection, sensitive-information disclosure, supply-chain risk, data and model poisoning, improper output handling, excessive agency, system-prompt leakage, vector and embedding weaknesses, misinformation, and unbounded consumption.",
    boundary: "A versioned awareness list, not a complete threat model or proof of compliance. Risk names and numbers differ from 2023–24; product controls still require scoped testing, ownership, monitoring, and incident response.",
  },
  {
    id: "anthropic-agent-evals",
    title: "Demystifying evals for AI agents",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Designing agent task suites, graders, transcript inspection, capability and regression evaluation, and representative failure analysis.",
    boundary: "Agent-eval patterns need independent human calibration and must be adapted to the system's tools, users, and potential side effects.",
  },
  {
    id: "google-cloud-ai-operations",
    title: "Deploy and operate generative AI applications",
    publisher: "Google Cloud Architecture Center",
    url: "https://docs.cloud.google.com/architecture/deploy-operate-generative-ai-applications",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Versioning, end-to-end observability, lineage, continuous evaluation, drift monitoring, latency, staged deployment, and rollback for generative-AI systems.",
    boundary: "Cloud-specific implementation advice must be translated to the selected architecture and does not replace product-level incident ownership.",
  },
  {
    id: "eu-ai-act",
    title: "Regulation (EU) 2024/1689 — Artificial Intelligence Act, initial authentic act",
    publisher: "Official Journal of the European Union",
    url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A32024R1689",
    accessedOn: ACCESSED_ON,
    kind: "law",
    supports: "The initial authentic legal act establishing the EU Artificial Intelligence Act's risk framework, provider and deployer obligations, transparency duties, governance, and high-risk-system requirements.",
    boundary: "This is the original 2024 act, not the full current consolidated text. The course is not legal advice; amendments, applicability, transition dates, standards, delegated acts, and national enforcement require qualified current review.",
  },
  {
    id: "scrum-guide",
    title: "The Scrum Guide",
    publisher: "Ken Schwaber and Jeff Sutherland",
    url: "https://scrumguides.org/scrum-guide.html",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    license: "CC BY-SA 4.0",
    supports: "Accurate definitions of Product Goal, Product Backlog, Product Owner accountabilities, empiricism, and Scrum events.",
    boundary: "Scrum is a delivery framework, not a complete product discovery, strategy, design, GTM, or governance system.",
  },
  {
    id: "microsoft-experimentation-platform",
    title: "Experimentation Platform",
    publisher: "Microsoft Research",
    url: "https://www.microsoft.com/en-us/research/group/experimentation-platform-exp/",
    accessedOn: ACCESSED_ON,
    kind: "research",
    supports: "Embedding trustworthy controlled experimentation into product development and measuring real-world impact.",
    boundary: "Randomized experiments require adequate power, valid metrics, no harmful interference, and ethical deployment; not every decision can be randomized.",
  },
  {
    id: "atlassian-daci",
    title: "DACI: a decision-making framework",
    publisher: "Atlassian Team Playbook",
    url: "https://www.atlassian.com/team-playbook/plays/daci",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "The Driver, Approver, Contributors, and Informed roles in DACI, together with the related Responsible, Accountable, Consulted, and Informed roles in RACI.",
    boundary: "Responsibility frameworks clarify a decision's participation and authority; they do not resolve weak evidence, power dynamics, trust, or the need to adapt roles to context.",
  },
  {
    id: "rumelt-strategy-kernel",
    title: "The perils of bad strategy",
    publisher: "McKinsey & Company",
    url: "https://www.mckinsey.com/capabilities/strategy-and-corporate-finance/our-insights/the-perils-of-bad-strategy",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "Richard Rumelt's strategy kernel: diagnosis of the challenge, a guiding policy, and coherent actions that reinforce one another.",
    boundary: "The kernel structures strategic reasoning but does not establish that the diagnosis is correct; customer, market, technical, operational, and economic assumptions still require evidence.",
  },
  {
    id: "sba-market-research",
    title: "Market research and competitive analysis",
    publisher: "U.S. Small Business Administration",
    url: "https://www.sba.gov/business-guide/plan-your-business/market-research-competitive-analysis",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Making market demand, market size, economic indicators, location, saturation, pricing, strengths, weaknesses, barriers, and competitors explicit in a market analysis.",
    boundary: "The guidance supports transparent market-research inputs, not a universal TAM, SAM, and SOM formula or proof that a forecasted market is reachable.",
  },
  {
    id: "govuk-user-research-consent",
    title: "Getting informed consent for user research",
    publisher: "GOV.UK Service Manual",
    url: "https://www.gov.uk/service-manual/user-research/getting-users-consent-for-research",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Obtaining informed and voluntary research consent by explaining participation, recording, data use, confidentiality, withdrawal, and the choices available to participants.",
    boundary: "This is UK public-service guidance, not a universal legal template. Applicable legal bases, safeguarding duties, accessibility needs, and consent language vary by jurisdiction and context.",
  },
  {
    id: "govuk-research-privacy",
    title: "Managing user research data and participant privacy",
    publisher: "GOV.UK Service Manual",
    url: "https://www.gov.uk/service-manual/user-research/managing-user-research-data-participant-privacy",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Minimizing participant information and managing access, storage, retention, deletion, identity separation, and privacy throughout user research.",
    boundary: "This is UK public-service guidance and not legal advice. Teams must apply applicable law and policy and must not assume pseudonymization eliminates re-identification risk.",
  },
  {
    id: "whatmatters-okr",
    title: "OKR Glossary",
    publisher: "What Matters",
    url: "https://www.whatmatters.com/resources/okr-glossary",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "The distinction between a qualitative Objective and measurable, verifiable Key Results, and between OKRs, action items, metrics, and routine work.",
    boundary: "This is one practitioner articulation of OKRs rather than a universal standard. A Key Result may be a metric target, but achieving it does not establish product value, causality, or strategic validity.",
  },
  {
    id: "google-analytics-funnel",
    title: "[GA4] Funnel exploration",
    publisher: "Google Analytics Help",
    url: "https://support.google.com/analytics/answer/9327974?hl=en",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Defining a sequence of user steps and analyzing completion, abandonment, and open or closed funnel behavior across those steps.",
    boundary: "The documentation describes a Google Analytics implementation. Funnel results depend on event definitions, eligibility, identity, filters, and time windows and are not causal evidence by themselves.",
  },
  {
    id: "google-analytics-cohort",
    title: "[GA4] Cohort exploration",
    publisher: "Google Analytics Help",
    url: "https://support.google.com/analytics/answer/9670133?hl=en",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Grouping users who share a defined inclusion criterion or start event and comparing their retention or behavior over time.",
    boundary: "Cohort analysis is descriptive; selection, seasonality, exposure, instrumentation, and confounding can explain observed differences, so it does not identify causal impact by itself.",
  },
  {
    id: "intercom-rice",
    title: "RICE Prioritization Framework for Product Managers",
    publisher: "Intercom",
    url: "https://www.intercom.com/blog/rice-simple-prioritization-for-product-managers/",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "The RICE inputs and formula—Reach × Impact × Confidence ÷ Effort—including reach within a defined period, confidence as an uncertainty adjustment, and effort in a consistent unit.",
    boundary: "RICE is a comparison aid, not an algorithmic strategy or delivery promise. Scores require consistent population, period, impact scale, and effort units and do not override obligations, dependencies, safety, accessibility, or strategy.",
  },
  {
    id: "safe-wsjf",
    title: "Weighted Shortest Job First",
    publisher: "Scaled Agile, Inc.",
    url: "https://framework.scaledagile.com/wsjf/",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "SAFe's relative WSJF method for sequencing work using relative Cost of Delay divided by relative job duration.",
    boundary: "This is a SAFe-specific relative-estimation technique, not a universal optimization rule. Its judgmental inputs do not displace legal, safety, accessibility, dependency, or portfolio constraints.",
  },
  {
    id: "agilebusiness-moscow",
    title: "What is MoSCoW Prioritization?",
    publisher: "Agile Business Consortium",
    url: "https://www.agilebusiness.org/resource/what-is-moscow-prioritization/",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "The Must Have, Should Have, Could Have, and Won't Have this time categories and their use within a stated scope and timebox.",
    boundary: "MoSCoW classifies commitments rather than value. Category definitions and acceptance criteria must be explicit, and no allocation heuristic is a universal ratio.",
  },
  {
    id: "kanban-guide",
    title: "The Kanban Guide",
    publisher: "Kanban Guides",
    url: "https://kanbanguides.org/the-kanban-guide/",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Managing knowledge-work flow through an explicit Definition of Workflow, work-in-progress control and pull, a Service Level Expectation, and core flow measures.",
    boundary: "Kanban helps teams understand and improve flow; it does not supply product strategy, discovery, prioritization, or outcome validation, and forecasts remain probabilistic.",
  },
  {
    id: "github-actions",
    title: "Understanding GitHub Actions",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/actions/get-started/understand-github-actions",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Automating CI/CD build, test, and deployment pipelines through event-triggered workflows composed of jobs, runners, steps, and reusable actions.",
    boundary: "This is a GitHub-specific mechanism. A successful workflow does not establish product quality, accessibility, security, model quality, or release readiness.",
  },
  {
    id: "google-sre-canary",
    title: "Canarying Releases",
    publisher: "Google Site Reliability Engineering",
    url: "https://sre.google/workbook/canarying-releases/",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "A canary as a partial, time-limited production deployment evaluated against a control, with representative exposure, health metrics, staged rollout, pause, and rollback.",
    boundary: "Canarying reduces blast radius but cannot detect every defect; weak metrics, shared dependencies, overlapping changes, unrepresentative traffic, or short duration can contaminate the signal.",
  },
  {
    id: "github-copilot-agent-risks",
    title: "Risks and mitigations for GitHub Copilot cloud agent",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/copilot/concepts/agents/cloud-agent/risks-and-mitigations",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Coding-agent safeguards including restricted branches and permissions, human pull-request review and merge, code and secret scanning, dependency scrutiny, and network controls.",
    boundary: "These are GitHub-specific controls and do not guarantee secure code. Repository policy, threat modeling, testing, review, supply-chain controls, and release governance remain necessary.",
  },
  {
    id: "openai-codex-security",
    title: "Introducing upgrades to Codex",
    publisher: "OpenAI",
    url: "https://openai.com/index/introducing-upgrades-to-codex/",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Sandboxed coding-agent operation, network restrictions, inspectable outputs, and the boundary that automated review complements rather than replaces human review.",
    boundary: "Provider behavior and controls are version- and configuration-dependent. Teams must verify the current product, workspace permissions, network policy, and review requirements.",
  },
  {
    id: "microsoft-foundry-rag",
    title: "Retrieval-augmented generation and indexes",
    publisher: "Microsoft Learn",
    url: "https://learn.microsoft.com/en-us/azure/foundry/concepts/retrieval-augmented-generation",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "RAG as adding retrieved information from a data source to model input, optional keyword, semantic, vector, or hybrid retrieval components, authorization controls, evaluation layers, and the RAG–fine-tuning distinction.",
    boundary: "This is Azure-oriented architecture guidance. RAG does not guarantee relevance, authorization, freshness, grounding, or safety, and retrieved content must still be treated as untrusted external input.",
  },
  {
    id: "google-sre-slo",
    title: "Service Level Objectives",
    publisher: "Google Site Reliability Engineering",
    url: "https://sre.google/sre-book/service-level-objectives/",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Defining service indicators over explicit populations and windows and using latency distributions and percentiles rather than relying only on averages.",
    boundary: "Percentiles require precise start and end points, eligible observations, window, and failure treatment; p95 is not a universal service-level objective.",
  },
  {
    id: "openai-ai-scorecard",
    title: "A scorecard for the AI age",
    publisher: "OpenAI",
    url: "https://openai.com/index/a-scorecard-for-the-ai-age/",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "Evaluating AI work by successful outcomes and defining cost per successful task to include the full cost of attempts rather than only the cost of successful runs.",
    boundary: "This is a provider-authored operational framework, not an accounting standard. Teams must define task success, eligible attempts, included costs, review, rework, and infrastructure for their own product.",
  },
  {
    id: "nist-genai-profile",
    title: "Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile (NIST AI 600-1)",
    publisher: "U.S. National Institute of Standards and Technology",
    url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Generative-AI-specific lifecycle actions involving governance, pre-deployment testing, provenance, human oversight, monitoring, incident disclosure, and deactivation.",
    boundary: "This voluntary companion profile is not an exhaustive control catalog, certification, or statement of legal compliance; actions must be selected and tailored to the product context and impacts.",
  },
  {
    id: "owasp-prompt-injection",
    title: "LLM01:2025 Prompt Injection",
    publisher: "OWASP Gen AI Security Project",
    url: "https://genai.owasp.org/llmrisk/llm01-prompt-injection/",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    license: "CC BY-SA 4.0",
    supports: "Direct and indirect prompt-injection risk, including untrusted external and retrieved content that attempts to change model behavior or trigger actions.",
    boundary: "No single filter or prompt eliminates injection risk. Product-specific least privilege, authorization, isolation, validation, testing, monitoring, and recovery remain necessary.",
  },
  {
    id: "owasp-excessive-agency",
    title: "LLM06:2025 Excessive Agency",
    publisher: "OWASP Gen AI Security Project",
    url: "https://genai.owasp.org/llmrisk/llm062025-excessive-agency/",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    license: "CC BY-SA 4.0",
    supports: "Limiting an agent's functionality, permissions, and autonomy, enforcing downstream authorization, and requiring appropriate approval for consequential actions.",
    boundary: "This addresses one risk category rather than complete assurance. Teams must test identities, permission scopes, tool boundaries, side effects, reversibility, logging, and recovery in the deployed environment.",
  },
  {
    id: "eu-ai-act-consolidated",
    title: "Consolidated text of Regulation (EU) 2024/1689 — version of 27 July 2026",
    publisher: "EUR-Lex",
    url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02024R1689-20260727",
    accessedOn: ACCESSED_ON,
    kind: "law",
    supports: "The current consolidated documentation view of the EU Artificial Intelligence Act, incorporating amendments through 27 July 2026.",
    boundary: "The consolidated text is a documentation tool without independent legal effect; authentic acts in the Official Journal control. Applicability, dates, standards, delegated acts, and enforcement require qualified current review.",
  },
  {
    id: "gitlab-product-development-flow",
    title: "Product Development Flow",
    publisher: "GitLab",
    url: "https://handbook.gitlab.com/handbook/product-development/how-we-work/product-development-flow/",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    license: "CC BY-SA 4.0",
    supports: "A public example of selecting experimental, beta, limited-availability, or general-availability status according to product context rather than requiring every stage for every feature.",
    boundary: "GitLab's release labels and process are company-specific. Every product needs risk-proportionate evidence, eligibility, support, monitoring, exit, rollback, and legal criteria.",
  },
  {
    id: "dave-mcclure-aarrr",
    title: "Startup Metrics for Pirates",
    publisher: "Dave McClure",
    url: "https://www.slideshare.net/slideshow/startup-metrics-for-pirates-long-version/89026",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "The original AARRR sequence: Acquisition, Activation, Retention, Referral, and Revenue, as a startup-oriented lifecycle measurement lens.",
    boundary: "AARRR is a historical startup heuristic, not a universal customer lifecycle or causal growth model. Each stage needs product-specific events, eligibility, windows, and success definitions.",
  },
  {
    id: "reforge-product-led-growth",
    title: "Product-Led Growth Is a Major Growth Motion",
    publisher: "Reforge",
    url: "https://www.reforge.com/blog/product-led-growth",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "Product-led growth as a growth motion in which product use performs substantial acquisition, activation, qualification, retention, or expansion work.",
    boundary: "PLG is not synonymous with a free plan, self-service-only sales, or a growth loop, and its suitability depends on product, market, economics, and buying context.",
  },
  {
    id: "reforge-growth-loops",
    title: "Growth Loops Are the New Funnels",
    publisher: "Reforge",
    url: "https://www.reforge.com/blog/growth-loops",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "A growth loop as a closed system in which an output can be reinvested as an input into a subsequent cycle.",
    boundary: "Loop diagrams encode hypotheses. They require valid events, cohort and quality measures, constraints, and guardrails and do not establish sustainable or causal growth by themselves.",
  },
  {
    id: "microsoft-experiment-during",
    title: "Patterns of Trustworthy Experimentation: During-Experiment Stage",
    publisher: "Microsoft Research",
    url: "https://www.microsoft.com/en-us/research/articles/patterns-of-trustworthy-experimentation-during-experiment-stage/",
    accessedOn: ACCESSED_ON,
    kind: "research",
    supports: "Pre-set duration; monitoring of data quality, outcomes, diagnostics, and guardrails; sample-ratio checks; and statistical treatment of repeated measurement, multiple testing, and early peeking.",
    boundary: "This documents Microsoft practice rather than a universal protocol. Teams must pre-specify analysis and stopping rules, distinguish safety monitoring from efficacy peeking, and address interference, ethics, multiplicity, and heterogeneous effects.",
  },
  {
    id: "productboard-product-operations",
    title: "Product Operations",
    publisher: "Productboard",
    url: "https://www.productboard.com/glossary/product-operations/",
    accessedOn: ACCESSED_ON,
    kind: "industry-practice",
    supports: "Product Operations as a capability spanning shared process, tools, data, cross-functional alignment, and systems that make product work more consistent and scalable.",
    boundary: "This is a vendor-authored industry definition rather than a standard. A searchable repository is one Product Ops implementation, not the entire discipline.",
  },
  {
    id: "microsoft-rag-information-retrieval",
    title: "Information retrieval for RAG",
    publisher: "Microsoft Azure Architecture Center",
    url: "https://learn.microsoft.com/en-us/azure/architecture/ai-ml/guide/rag/rag-information-retrieval",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Evaluating retrieval with labeled positive and negative examples and metrics such as Precision@K, Recall@K, and mean reciprocal rank.",
    boundary: "Retrieval metrics depend on labels, query distribution, corpus version, K, and relevance policy; good retrieval does not by itself establish grounded generation or end-to-end task success.",
  },
  {
    id: "microsoft-rag-evaluators",
    title: "RAG evaluators",
    publisher: "Microsoft Foundry",
    url: "https://learn.microsoft.com/en-us/azure/foundry/concepts/evaluation-evaluators/rag-evaluators",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Separating retrieval and generation evaluation and assessing groundedness, relevance, response completeness, and document retrieval quality.",
    boundary: "These are provider-specific evaluator definitions. Teams must validate metrics and graders against domain-expert labels and must not treat a composite score as proof of safety or task success.",
  },
  {
    id: "aws-rag-evaluation-metrics",
    title: "Metrics for RAG evaluation jobs",
    publisher: "Amazon Web Services",
    url: "https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base-evaluation-metrics.html",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "RAG metrics for faithfulness, correctness, completeness, refusal, citation precision, citation coverage, and retrieval context relevance and coverage.",
    boundary: "These are Amazon Bedrock evaluator definitions rather than universal measures. Citation presence or a provider score does not establish claim-level support without calibrated review.",
  },
  {
    id: "anthropic-containment",
    title: "How we contain Claude across products",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/engineering/how-we-contain-claude",
    accessedOn: ACCESSED_ON,
    kind: "official-guidance",
    supports: "Defense-in-depth containment through sandbox and virtual-machine boundaries, filesystem controls, network or egress restrictions, permission design, and mitigation of approval fatigue.",
    boundary: "This describes one provider's containment architecture. Product teams must threat-model and test their own identities, tools, network, data, approval, logging, and recovery boundaries.",
  },
  {
    id: "microsoft-experiment-pre",
    title: "Patterns of Trustworthy Experimentation: Pre-Experiment Stage",
    publisher: "Microsoft Research",
    url: "https://www.microsoft.com/en-us/research/group/experimentation-platform-exp/articles/patterns-of-trustworthy-experimentation-pre-experiment-stage/",
    accessedOn: ACCESSED_ON,
    kind: "research",
    supports: "Predefining hypotheses, eligible population and randomization, metrics, significance level, target power, minimum detectable effect, baseline assumptions, sample size or duration, and analysis before exposure.",
    boundary: "This documents Microsoft experimentation practice rather than a universal design. Power, MDE, variance, sample size, duration, interference, novelty, ethics, and business risk remain context-dependent.",
  },
] as const satisfies readonly ProductManagementSourceRecord[];

export const PRODUCT_MANAGEMENT_SOURCE_BY_ID = Object.fromEntries(
  PRODUCT_MANAGEMENT_SOURCES.map((source) => [source.id, source]),
) as Record<string, ProductManagementSourceRecord>;

export function getProductManagementSource(id: string): ProductManagementSourceRecord {
  const source = PRODUCT_MANAGEMENT_SOURCE_BY_ID[id];
  if (!source) throw new Error(`Unknown product-management source: ${id}`);
  return source;
}
