import type { SoftwareEngineeringMediaRecord } from "./types";

const githubCommit = "4f8c3170cea7f72cf41fc976f5dbf4e8a0b8567f";

export const SOFTWARE_ENGINEERING_MEDIA = [
  {
    id: "codex-plan-ui",
    title: "Codex CLI plan and progress surface",
    product: "OpenAI Codex",
    lessonSlugs: ["agentic-engineering-system", "repository-context", "agent-evaluation"],
    src: "/courses/software-engineering/figures/codex-cli-plan.png",
    webpSrc: "/courses/software-engineering/figures/codex-cli-plan-1600.webp",
    width: 1898,
    height: 1190,
    sha256: "15b86fa9c0790a779ecdd84f1e7dee029ab79bfb093bd3c4876998696925b013",
    webpWidth: 1600,
    webpHeight: 1004,
    webpSha256: "3abc328ec5ecd76814fe44bd371f7d4f68d89f87e9508d73dcb7af7a5601df88",
    sourceUrl: "https://github.com/openai/codex/blob/343074d4207d572809bd8cea15f4be1d09d98e0b/.github/codex-cli-splash.png",
    immutableSourceUrl: "https://raw.githubusercontent.com/openai/codex/343074d4207d572809bd8cea15f4be1d09d98e0b/.github/codex-cli-splash.png",
    sourceCommit: "343074d4207d572809bd8cea15f4be1d09d98e0b",
    provenance: "licensed-repository",
    licence: "Apache-2.0",
    licenceUrl: "https://github.com/openai/codex/blob/343074d4207d572809bd8cea15f4be1d09d98e0b/LICENSE",
    observedOn: "2026-08-23",
    privacyReviewed: true,
    alt: "Official Codex command-line interface showing the request ‘Explain this code base to me,’ reasoning text, and an Updated Plan checklist.",
    caption: "Authentic Codex CLI illustration from the OpenAI Codex repository at commit 343074d. Read the plan as a control surface: scope, inspect, verify, and report. Labels visible in the historical image are observations, not current model or plan promises.",
    transcript: [
      "The header identifies OpenAI Codex, a model label, and the codex-rs working directory; these labels document this captured interface, not a current availability promise.",
      "The user request reads ‘Explain this code base to me.’",
      "The visible reasoning says the repository will be inspected with commands such as ls and rg --files without making modifications.",
      "The Updated Plan contains four unchecked tasks; the first is highlighted, and an ‘Explored’ heading appears below. No completed step or token meter is visible in the image.",
    ],
    rightsNote: "Reused from Apache-2.0 source with notice. Apache-2.0 does not grant trademark rights or imply OpenAI endorsement.",
  },
  {
    id: "claude-cowork-ui",
    title: "Claude Desktop Cowork workspace control",
    product: "Claude",
    lessonSlugs: ["repository-context", "teams-governance"],
    src: "/courses/claude-income/figures/fig-02-cowork-composer.png",
    webpSrc: "/courses/claude-income/figures/fig-02-cowork-composer-960.webp",
    width: 720,
    height: 300,
    sha256: "92d671632af8bd8e85a316e603fcce9939c6d02882343f55b5d624a325d458c8",
    webpWidth: 720,
    webpHeight: 300,
    webpSha256: "cfd8cdec2698aafd72e3f173cfcd74153077441dd2141be266c569d04b8801f2",
    sourceUrl: "https://aicourse.top/courses/claude-income/figures/fig-02-cowork-composer.png",
    provenance: "course-authored-capture",
    licence: "Editorial capture",
    licenceUrl: "https://aicourse.top/courses/software-engineering/NOTICE.md",
    observedOn: "2026-08-23",
    privacyReviewed: true,
    alt: "Real Claude Desktop Cowork composer with Cowork selected and Project or folder and permission-mode controls below the prompt.",
    caption: "Course-authored capture of the real Claude Desktop Cowork interface. Select a bounded project or folder and review the visible permission mode before delegating work; the interface state is evidence of configuration, not proof that the task is safe or complete.",
    transcript: [
      "Cowork is selected beside the Chat option in a blank Claude Desktop composer.",
      "A Project or folder control appears below the composer so a learner can inspect the workspace boundary before starting.",
      "A visible permission-mode control reads Skip in this dated capture; labels and defaults may change, and the learner must verify its current meaning rather than infer authority from the screenshot.",
    ],
    rightsNote: "Course-authored capture reproduced for identification, commentary, and instruction. Claude interface rights and marks remain Anthropic's; no affiliation or endorsement is implied.",
  },
  {
    id: "claude-artifact-workspace-ui",
    title: "Claude Desktop artifact workspace",
    product: "Claude",
    lessonSlugs: ["agent-evaluation", "capstone-safe-change"],
    src: "/courses/claude-income/figures/fig-06-artifact-workspace.png",
    webpSrc: "/courses/claude-income/figures/fig-06-artifact-workspace-960.webp",
    width: 1322,
    height: 768,
    sha256: "81b155f3632b27c46365dafd8692ce4b5c1f63ad1649ea67888f208f7fc2e2ab",
    webpWidth: 960,
    webpHeight: 558,
    webpSha256: "2fbf7aa9530eb81834b3eb17c88106485d3bcc33f471bfa3d00b876ff2bc7b32",
    sourceUrl: "https://aicourse.top/courses/claude-income/figures/fig-06-artifact-workspace.png",
    provenance: "course-authored-capture",
    licence: "Editorial capture",
    licenceUrl: "https://aicourse.top/courses/software-engineering/NOTICE.md",
    observedOn: "2026-08-23",
    privacyReviewed: true,
    alt: "Real Claude Desktop artifact workspace processing a course-authored request to build a web page, with Progress, Outputs, and Context panels visible.",
    caption: "Course-authored capture of a real Claude Desktop artifact build in progress. Progress, Outputs, and Context are useful evidence locations, but this frame shows neither a finished artifact nor independent tests, accessibility review, publication success, or release authorization.",
    transcript: [
      "The course-authored prompt asks Claude to ask clarifying questions, build a web-page artifact, and publish it.",
      "The response is still in progress; no completed page, test result, or publication result is visible.",
      "A side panel exposes Progress, Outputs, and Context sections, while the composer shows Manual mode in this dated interface.",
      "The screen itself warns that Claude can make mistakes and responses should be checked; Course 8 operationalizes that warning with independent engineering evidence.",
    ],
    rightsNote: "Course-authored capture reproduced for identification, commentary, and instruction. Claude interface rights and marks remain Anthropic's; no affiliation or endorsement is implied.",
  },
  {
    id: "github-project-ui",
    title: "GitHub Project table",
    product: "GitHub",
    lessonSlugs: ["planning-estimation-risk"],
    src: "/courses/github/figures/12-project-table.png",
    webpSrc: "/courses/github/figures/12-project-table.webp",
    width: 3532,
    height: 704,
    sha256: "5e8eb80ece0e464dbd65d4db352a42600b4db7aaff072b92d1d9db2394561b27",
    webpWidth: 3532,
    webpHeight: 704,
    webpSha256: "b3f179976db3efc02e80dec77cfee2492eed341d1d7ba9a1511a64fa65b8d1f9",
    sourceUrl: "https://docs.github.com/assets/cb-96059/images/help/issues/quickstart-projects-table-view.png",
    immutableSourceUrl: `https://raw.githubusercontent.com/github/docs/${githubCommit}/assets/images/help/issues/quickstart-projects-table-view.png`,
    sourceCommit: githubCommit,
    provenance: "licensed-repository",
    licence: "CC-BY-4.0",
    licenceUrl: "https://github.com/github/docs/blob/4f8c3170cea7f72cf41fc976f5dbf4e8a0b8567f/LICENSE-CONTENT",
    observedOn: "2026-08-23",
    privacyReviewed: true,
    alt: "GitHub Projects table with four work items and visible Title, Assignees, Status, Labels, and Notes fields.",
    caption: "A visible backlog is a coordination boundary. Break work into independently reviewable outcomes, expose ownership and status, and limit work in progress before adding parallel agents.",
    transcript: [
      "Rows represent work items rather than model conversations.",
      "Visible fields make titles, assignees, status, labels, and notes inspectable by the team.",
      "A project board coordinates work; it does not replace a task contract or acceptance criteria.",
    ],
    rightsNote: "GitHub Docs image reused under CC BY 4.0 with source, commit, and licence attribution.",
  },
  {
    id: "github-branch-ui",
    title: "GitHub branching model",
    product: "GitHub",
    lessonSlugs: ["git-environments-worktrees"],
    src: "/courses/github/figures/04-branching.png",
    webpSrc: "/courses/github/figures/04-branching.webp",
    width: 2098,
    height: 528,
    sha256: "73042f69d246dc19f411aff82e0d0be5c894c0feed09df19923cc0b6a90e0785",
    webpWidth: 2098,
    webpHeight: 528,
    webpSha256: "8f8177906b41dc716cdbd313b0d4c54afa30e575d1b18d7bd58986d8fa7b30ad",
    sourceUrl: "https://docs.github.com/assets/cb-23923/images/help/repository/branching.png",
    immutableSourceUrl: `https://raw.githubusercontent.com/github/docs/${githubCommit}/assets/images/help/repository/branching.png`,
    sourceCommit: githubCommit,
    provenance: "licensed-repository",
    licence: "CC-BY-4.0",
    licenceUrl: "https://github.com/github/docs/blob/4f8c3170cea7f72cf41fc976f5dbf4e8a0b8567f/LICENSE-CONTENT",
    observedOn: "2026-08-23",
    privacyReviewed: true,
    alt: "Diagram of a feature branch diverging from the default branch, receiving commits, and returning through a pull request and merge.",
    caption: "A branch separates change history for review and merge. Concurrent agents also need distinct worktrees or checkouts; a branch name alone does not prevent them from overwriting the same working directory.",
    transcript: [
      "A feature branch diverges from the default branch.",
      "Several commits accumulate on the branch.",
      "A pull request and merge reconnect the reviewed change to the default branch.",
    ],
    rightsNote: "GitHub Docs image reused under CC BY 4.0 with source, commit, and licence attribution.",
  },
  {
    id: "github-diff-ui",
    title: "GitHub source diff",
    product: "GitHub",
    lessonSlugs: ["construction-quality", "debugging-root-cause"],
    src: "/courses/github/figures/06-diff.png",
    webpSrc: "/courses/github/figures/06-diff.webp",
    width: 1434,
    height: 516,
    sha256: "a0c89344736c2456d962c7c550330ea18e6cd18eb8b63044f0fcd695f3167421",
    webpWidth: 1434,
    webpHeight: 516,
    webpSha256: "179f3ac7fe42777a2b954eae76a7815fd1379e69a586c2f76865a95a9d134db5",
    sourceUrl: "https://docs.github.com/assets/cb-32937/images/help/repository/diffs.png",
    immutableSourceUrl: `https://raw.githubusercontent.com/github/docs/${githubCommit}/assets/images/help/repository/diffs.png`,
    sourceCommit: githubCommit,
    provenance: "licensed-repository",
    licence: "CC-BY-4.0",
    licenceUrl: "https://github.com/github/docs/blob/4f8c3170cea7f72cf41fc976f5dbf4e8a0b8567f/LICENSE-CONTENT",
    observedOn: "2026-08-23",
    privacyReviewed: true,
    alt: "GitHub code diff with removed lines in red, added lines in green, file context, and line numbers.",
    caption: "The diff—not the agent's narrative—is the primary review artifact. Check scope, behavior, tests, generated files, dependency changes, and unintended deletions.",
    transcript: [
      "Removed lines and added lines are visually separated.",
      "File context and line numbers let a reviewer connect claims to exact changes.",
      "A small diff is easier to reason about, but still needs executable verification.",
    ],
    rightsNote: "GitHub Docs image reused under CC BY 4.0 with source, commit, and licence attribution.",
  },
  {
    id: "github-review-ui",
    title: "GitHub review comment composer",
    product: "GitHub",
    lessonSlugs: ["review-refactoring-debt", "teams-governance"],
    src: "/courses/github/figures/08-review-suggestion.png",
    webpSrc: "/courses/github/figures/08-review-suggestion.webp",
    width: 1378,
    height: 514,
    sha256: "42e6833ab90cf65663270c06514fee5b2df051a26ae7f360ddf994ab7b724418",
    webpWidth: 1378,
    webpHeight: 514,
    webpSha256: "83bdc21e96be2a2aeb0f81db43398aee6147126a37f3f16a7bcb323438efc00c",
    sourceUrl: "https://docs.github.com/assets/cb-26289/images/help/pull_requests/suggestion-block.png",
    immutableSourceUrl: `https://raw.githubusercontent.com/github/docs/${githubCommit}/assets/images/help/pull_requests/suggestion-block.png`,
    sourceCommit: githubCommit,
    provenance: "licensed-repository",
    licence: "CC-BY-4.0",
    licenceUrl: "https://github.com/github/docs/blob/4f8c3170cea7f72cf41fc976f5dbf4e8a0b8567f/LICENSE-CONTENT",
    observedOn: "2026-08-23",
    privacyReviewed: true,
    alt: "GitHub pull-request review comment composer with Write and Preview tabs, an empty comment field, formatting controls, and Start a review button.",
    caption: "Review should challenge intent, risk, and evidence. Agents may draft suggestions, but the author, verifier, and approver roles should not collapse into one probabilistic actor.",
    transcript: [
      "The composer is on its Write tab and the comment field is empty.",
      "Formatting controls include a highlighted suggestion-control icon, headings, code, links, lists, mentions, and undo.",
      "The visible actions are Cancel, Add single comment, and Start a review; this crop does not show a written suggestion or an applied code change.",
    ],
    rightsNote: "GitHub Docs image reused under CC BY 4.0 with source, commit, and licence attribution.",
  },
  {
    id: "github-actions-ui",
    title: "GitHub Actions workflow result",
    product: "GitHub",
    lessonSlugs: ["cicd-release", "security-privacy-supply-chain"],
    src: "/courses/github/figures/20-actions-workflow.png",
    webpSrc: "/courses/github/figures/20-actions-workflow.webp",
    width: 2194,
    height: 474,
    sha256: "6423f6ca4525830027d69e7d9bb515a6f04487f126e9a7d9af6805ed057a0846",
    webpWidth: 2194,
    webpHeight: 474,
    webpSha256: "7b8c174c94a474a26bca3f3944b9701366ffcf643371c9abb81b5bf87e0bff38",
    sourceUrl: "https://docs.github.com/assets/cb-64036/images/help/repository/actions-quickstart-workflow-sidebar.png",
    immutableSourceUrl: `https://raw.githubusercontent.com/github/docs/${githubCommit}/assets/images/help/repository/actions-quickstart-workflow-sidebar.png`,
    sourceCommit: githubCommit,
    provenance: "licensed-repository",
    licence: "CC-BY-4.0",
    licenceUrl: "https://github.com/github/docs/blob/4f8c3170cea7f72cf41fc976f5dbf4e8a0b8567f/LICENSE-CONTENT",
    observedOn: "2026-08-23",
    privacyReviewed: true,
    alt: "GitHub Actions All workflows page listing a successful workflow run with its commit, branch, actor, time, and duration.",
    caption: "A green workflow is bounded evidence: it proves the configured checks passed on a particular revision. Protect the workflow, test fixtures, credentials, and deployment authority from the agent being evaluated.",
    transcript: [
      "The sidebar lists All workflows and named workflow files or workflows, including GitHub Actions Demo.",
      "The run list shows a green status for ‘octocat is testing out GitHub Actions,’ together with commit 9861173, actor octocat, branch octocat-patch-1, time, and 17-second duration.",
      "Individual jobs, steps, logs, and check definitions are not visible in this crop; a green list status is therefore bounded evidence, not a complete verification record.",
    ],
    rightsNote: "GitHub Docs image reused under CC BY 4.0 with source, commit, and licence attribution.",
  },
  {
    id: "github-release-ui",
    title: "GitHub release surface",
    product: "GitHub",
    lessonSlugs: ["cicd-release", "documentation-knowledge"],
    src: "/courses/github/figures/17-release-link.png",
    webpSrc: "/courses/github/figures/17-release-link.webp",
    width: 1072,
    height: 1220,
    sha256: "4cbf2ca3b3d748ccaf087a323945cca5dc30774145fc6944c4ceee1813fdee27",
    webpWidth: 1072,
    webpHeight: 1220,
    webpSha256: "df0a5d61d889e43a8992b42916e7b18f78655e16a22d75a175622911a8e4db7c",
    sourceUrl: "https://docs.github.com/assets/cb-90524/images/help/releases/release-link.png",
    immutableSourceUrl: `https://raw.githubusercontent.com/github/docs/${githubCommit}/assets/images/help/releases/release-link.png`,
    sourceCommit: githubCommit,
    provenance: "licensed-repository",
    licence: "CC-BY-4.0",
    licenceUrl: "https://github.com/github/docs/blob/4f8c3170cea7f72cf41fc976f5dbf4e8a0b8567f/LICENSE-CONTENT",
    observedOn: "2026-08-23",
    privacyReviewed: true,
    alt: "GitHub repository sidebar showing a Releases link and release count.",
    caption: "A release is a versioned, attributable product event—not merely the final agent turn. Bind artifacts to commits, document changes, verify provenance, and preserve rollback instructions.",
    transcript: [
      "The repository About panel shows documentation and policy links plus repository activity counts.",
      "The Releases section shows a count of 140 and identifies GitHub CLI 2.39.2 as Latest, with a link to 139 more releases.",
      "This repository link exposes versioned releases, but the crop does not show release notes, assets, deployment success, or operational health.",
    ],
    rightsNote: "GitHub Docs image reused under CC BY 4.0 with source, commit, and licence attribution.",
  },
] as const satisfies readonly SoftwareEngineeringMediaRecord[];

export const SOFTWARE_ENGINEERING_MEDIA_BY_ID = SOFTWARE_ENGINEERING_MEDIA.reduce<
  Partial<Record<SoftwareEngineeringMediaRecord["id"], SoftwareEngineeringMediaRecord>>
>((figures, figure) => {
  figures[figure.id] = figure;
  return figures;
}, {}) as Readonly<
  Record<SoftwareEngineeringMediaRecord["id"], SoftwareEngineeringMediaRecord>
>;
