import {
  SOFTWARE_ENGINEERING_COURSE_ID,
  SOFTWARE_ENGINEERING_SOURCE_SNAPSHOT_ON,
} from "./types";
import { SOFTWARE_ENGINEERING_LESSONS, SOFTWARE_ENGINEERING_UNITS } from "./curriculum";

export const SOFTWARE_ENGINEERING_COURSE_MANIFEST = {
  id: SOFTWARE_ENGINEERING_COURSE_ID,
  sequence: 8,
  version: "1.0.1",
  publishedOn: SOFTWARE_ENGINEERING_SOURCE_SNAPSHOT_ON,
  sourceSnapshotOn: SOFTWARE_ENGINEERING_SOURCE_SNAPSHOT_ON,
  contentLocale: "en",
  units: SOFTWARE_ENGINEERING_UNITS,
  lessons: SOFTWARE_ENGINEERING_LESSONS,
  progressMilestones: 20,
} as const;
