export const SOFTWARE_ENGINEERING_OVERVIEW = {
  kicker: "Course 8 · Evidence-first engineering",
  title: "Software Engineering with Agentic AI",
  summary: "Learn to direct Claude, Codex, and other coding agents through a controlled software-delivery system: specify, inspect, plan, implement, test, review, integrate, deploy, observe, and improve.",
  audience: "For developers, technical leads, researchers, and students who want more than prompt recipes. You should be able to read code and use Git; the course supplies the engineering control system around the agent.",
  duration: "Approximately 16–20 hours including eighteen evidence-producing labs, a stratified final assessment, and an issue-to-operations capstone.",
  principles: [
    "Agent output is a proposal",
    "Authority boundaries are independently enforced",
    "Humans own consequential authority",
  ],
  lifecycle: [
    "Specify",
    "Inspect",
    "Plan",
    "Implement",
    "Test",
    "Review",
    "Integrate",
    "Deploy",
    "Observe",
    "Learn",
  ],
  lifecycleTitle: "The controlled delivery loop",
  lifecycleNote: "Agents can accelerate steps inside this loop. They do not remove the loop, its evidence, or the accountable human decision at a consequential boundary.",
  curriculumIntro: "Each lesson produces a reviewable engineering artifact. Completion means you can show the specification, diff, test, decision, trace, or release evidence—not that an agent said it was done.",
  coverageTitle: "All eighteen SWEBOK knowledge areas are oriented and mapped",
  coverageIntro: "The mapping is a breadth and traceability contract: every knowledge area receives explicit orientation and links to relevant teaching, practice, assessment, and capstone evidence. It is not an exhaustive treatment of every topic in the much larger SWEBOK guide. Agent evaluation and human–agent interaction are additional cross-cutting layers.",
  integrityTitle: "Evidence, currency, and media boundaries",
  capstone: {
    summary: "Complete all eight evidence packages, score the rubric honestly, review every release gate, attest the safety boundary, and record a release decision. A well-supported do-not-release decision can pass; a score can never waive a blocker.",
    artifactsIntro: "Check an artifact only after another engineer could inspect and reproduce its evidence.",
    gatesTitle: "Release-gate review",
    gatesIntro: "Review each gate against the submitted evidence. Record failures in the release decision; this checklist is not an authorization control.",
    safetyTitle: "Safety-boundary attestation",
    scoreLabel: "Self-assessed rubric score",
    decisionLabel: "Recorded release decision",
    selectDecision: "Select a decision",
  },
  integrity: "Course claims are linked at lesson level to official Academy material, current vendor documentation, standards, reproducible research, or clearly labeled maintainer practice. Product behavior is dated. User reports are never presented as prevalence evidence. A source can support a workflow without proving productivity, security, or production readiness.",
  mediaIntegrity: "Every bundled interface figure is authentic, local, reviewed for privacy risk, hash-verified, and accompanied by a text transcript. Course 8 uses an Apache-2.0 Codex repository image, two privacy-safe course-authored captures of real Claude Desktop, and pinned CC BY 4.0 GitHub Docs figures. The older Claude Platform screenshot with visible browser, workspace, and session identifiers is excluded from Course 8, as are Claude Academy images whose republication rights remain unclear.",
} as const;
