import {
  SOFTWARE_ENGINEERING_SOURCE_SNAPSHOT_ON,
  type SoftwareEngineeringSourceRecord,
} from "./types";

const on = SOFTWARE_ENGINEERING_SOURCE_SNAPSHOT_ON;

export const SOFTWARE_ENGINEERING_SOURCES = [
  {
    id: "openai-academy-codex-builders",
    tier: "primary",
    kind: "official-academy",
    title: "Codex for Builders",
    publisher: "OpenAI Academy",
    url: "https://academy.openai.com/public/clubs/builders-etkn1/resources/codex-for-builders",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Official overview of Codex across codebase understanding, planning, debugging, migrations, tests, refactoring, and multiple working surfaces.",
    caveat: "Product surfaces and entitlements change; the course teaches durable controls rather than plan-specific availability.",
  },
  {
    id: "openai-academy-codex-bootcamp",
    tier: "primary",
    kind: "official-academy",
    title: "Codex Bootcamp",
    publisher: "OpenAI Academy",
    url: "https://academy.openai.com/en/public/clubs/builders-etkn1/resources/codex-bootcamp-2026-07-18",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Official learning progression from context, steering, and review to approvals, skills, subagents, permissions, SDK use, and automation.",
    caveat: "Dated resource page verified reachable on 2026-08-23; details should be rechecked before a future course release.",
  },
  {
    id: "openai-codex-best-practices",
    tier: "primary",
    kind: "official-doc",
    title: "Codex best practices",
    publisher: "OpenAI",
    url: "https://learn.chatgpt.com/guides/best-practices",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Task scoping, repository guidance, plan/execute/review loops, verification, and long-running work.",
    caveat: "Operational guidance is product-specific and can evolve independently of this snapshot.",
  },
  {
    id: "openai-codex-approvals",
    tier: "primary",
    kind: "official-doc",
    title: "Codex security and permissions",
    publisher: "OpenAI",
    url: "https://developers.openai.com/codex/security/",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Sandbox, approval, network, and least-privilege guidance for agent execution.",
    caveat: "Sandbox behavior varies by surface and operating system; authorization remains a human responsibility.",
  },
  {
    id: "openai-codex-app",
    tier: "primary",
    kind: "official-doc",
    title: "Introducing the Codex app",
    publisher: "OpenAI",
    url: "https://openai.com/index/introducing-the-codex-app/",
    accessedOn: on,
    licence: "site terms; text link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Official description of parallel agents, worktrees, diff review, skills, and automation.",
    caveat: "A product announcement is evidence of intended capability, not independent evidence of quality or productivity.",
  },
  {
    id: "openai-harness-engineering",
    tier: "primary",
    kind: "practitioner-guide",
    title: "Harness engineering: leveraging Codex in an agent-first world",
    publisher: "OpenAI",
    url: "https://openai.com/index/harness-engineering/",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Case study of humans steering agents through repository legibility, tests, CI, documentation, observability, and enforceable feedback.",
    caveat: "First-party organizational case study; do not generalize its workflow or results to every team.",
  },
  {
    id: "openai-codex-action",
    tier: "primary",
    kind: "official-github",
    title: "OpenAI Codex GitHub Action",
    publisher: "OpenAI",
    url: "https://github.com/openai/codex-action",
    accessedOn: on,
    licence: "Apache-2.0",
    reuse: "paraphrase-and-link",
    evidenceUse: "Concrete CI patterns for restricted users, trigger allowlists, output schemas, and platform-specific sandbox limits.",
    caveat: "A safe default on one runner does not establish equivalent isolation on another runner or deployment environment.",
  },
  {
    id: "openai-codex-repository",
    tier: "primary",
    kind: "official-github",
    title: "OpenAI Codex",
    publisher: "OpenAI",
    url: "https://github.com/openai/codex/tree/343074d4207d572809bd8cea15f4be1d09d98e0b",
    accessedOn: on,
    licence: "Apache-2.0",
    reuse: "asset-reused-with-attribution",
    evidenceUse: "Immutable source for the authentic Codex CLI figure and approval/rollout implementation references.",
    caveat: "The screenshot illustrates an interface pattern at a pinned revision, not the current model menu, version, or plan entitlement.",
  },
  {
    id: "anthropic-academy-code-tutorials",
    tier: "primary",
    kind: "official-academy",
    title: "Claude Code tutorials",
    publisher: "Anthropic Academy",
    url: "https://academy.claude.com/code/tutorials",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Official entry point for Claude Code learning resources.",
    caveat: "Academy screenshots are not reused because a clear republication licence was not found.",
  },
  {
    id: "anthropic-academy-desktop-code",
    tier: "primary",
    kind: "official-academy",
    title: "Navigating the Claude desktop app",
    publisher: "Anthropic Academy",
    url: "https://academy.claude.com/tutorials/navigating-the-claude-desktop-app",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Official explanation of local and remote Code work, terminal activity, file changes, diffs, and Git context.",
    caveat: "Linked for product context only; no Academy image is bundled in Course 8.",
  },
  {
    id: "anthropic-code-best-practices",
    tier: "primary",
    kind: "official-doc",
    title: "Claude Code best practices",
    publisher: "Anthropic",
    url: "https://code.claude.com/docs/en/best-practices",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Explore-plan-code loops, verifiable outcomes, concise repository guidance, steering, subagents, and checkpoints.",
    caveat: "Recommendations describe a product workflow; independently controlled tests, CI, and permissions are still required.",
  },
  {
    id: "anthropic-code-agent-loop",
    tier: "primary",
    kind: "official-doc",
    title: "How Claude Code works",
    publisher: "Anthropic",
    url: "https://code.claude.com/docs/en/how-claude-code-works",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Official gather-context, act, verify loop plus steering, sessions, compaction, checkpoints, permissions, and worktrees.",
    caveat: "The loop describes product operation; it does not transfer accountability or establish that a reported completion is correct.",
  },
  {
    id: "anthropic-context-engineering",
    tier: "primary",
    kind: "practitioner-guide",
    title: "Effective context engineering for AI agents",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Context as a constrained attention budget, with progressive disclosure, just-in-time retrieval, compaction, structured notes, and decomposition.",
    caveat: "First-party engineering guidance; teams should evaluate context strategies on their own repositories and tasks.",
  },
  {
    id: "anthropic-code-permissions",
    tier: "primary",
    kind: "official-doc",
    title: "Claude Code permissions",
    publisher: "Anthropic",
    url: "https://code.claude.com/docs/en/permissions",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Permission modes, allow/deny rules, managed settings, and approval boundaries.",
    caveat: "Permission configuration is one layer; it does not make an unsafe instruction or destructive command authorized.",
  },
  {
    id: "anthropic-code-features",
    tier: "primary",
    kind: "official-doc",
    title: "Claude Code features overview",
    publisher: "Anthropic",
    url: "https://code.claude.com/docs/en/features-overview",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Distinguishes repository memory, skills, MCP, subagents, teams, and lifecycle hooks.",
    caveat: "Feature availability and labels are time-sensitive; a hook trigger can be predictable while a prompt- or agent-based handler remains probabilistic.",
  },
  {
    id: "anthropic-code-subagents",
    tier: "primary",
    kind: "official-doc",
    title: "Claude Code subagents",
    publisher: "Anthropic",
    url: "https://code.claude.com/docs/en/sub-agents",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Scoped delegation, context isolation, tool restriction, foreground/background execution, and resumption.",
    caveat: "Parallel agents add coordination and integration cost; they are not automatically faster.",
  },
  {
    id: "openai-exec-plans",
    tier: "primary",
    kind: "official-doc",
    title: "Using PLANS.md for multi-hour problem solving",
    publisher: "OpenAI Cookbook",
    url: "https://developers.openai.com/cookbook/articles/codex_exec_plans",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Self-contained living design documents with milestones, progress, discoveries, decisions, verification, and recovery context.",
    caveat: "An execution plan reduces coordination ambiguity but remains a proposal that must be revised when evidence changes.",
  },
  {
    id: "openai-codex-code-review",
    tier: "primary",
    kind: "official-doc",
    title: "Code review with Codex",
    publisher: "OpenAI",
    url: "https://learn.chatgpt.com/docs/code-review",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Read-only review scopes, line feedback, staging and reverting, and review of branches, commits, or uncommitted changes.",
    caveat: "Agent review is an additional signal, not a substitute for independent checks and accountable approval.",
  },
  {
    id: "openai-codex-worktrees",
    tier: "primary",
    kind: "official-doc",
    title: "Git worktrees in Codex",
    publisher: "OpenAI",
    url: "https://learn.chatgpt.com/docs/environments/git-worktrees",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Independent conversations and checkouts sharing Git history, with branch, pull-request, and handoff workflows.",
    caveat: "Worktrees isolate files, not organizational responsibility; overlapping changes still require coordination and integration.",
  },
  {
    id: "openai-agent-evals",
    tier: "primary",
    kind: "official-doc",
    title: "Agent evals",
    publisher: "OpenAI",
    url: "https://developers.openai.com/api/docs/guides/agent-evals",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Trace grading, datasets, repeatable evaluation runs, tool calls, guardrails, and handoff evaluation.",
    caveat: "Evaluation infrastructure supports evidence collection; task representativeness and release thresholds remain engineering decisions.",
  },
  {
    id: "human-eval-pass-at-k",
    tier: "primary",
    kind: "research-preprint",
    title: "Evaluating Large Language Models Trained on Code",
    publisher: "OpenAI researchers",
    url: "https://arxiv.org/abs/2107.03374",
    accessedOn: on,
    licence: "arXiv paper; link and paraphrase only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Primary definition and estimator for HumanEval pass@k: whether at least one of k sampled programs passes the bounded unit tests.",
    caveat: "Pass@k is a sampling-based functional-correctness metric for a bounded benchmark. Its unbiased estimator has sample-count assumptions and does not establish production quality, security, maintainability, or reliability.",
  },
  {
    id: "tau-bench-pass-power-k",
    tier: "primary",
    kind: "peer-reviewed",
    title: "τ-bench: A Benchmark for Tool-Agent-User Interaction in Real-World Domains",
    publisher: "ICLR 2025",
    url: "https://proceedings.iclr.cc/paper_files/paper/2025/hash/1b126cc38b8638e07bef37e7b2bb72bf-Abstract-Conference.html",
    accessedOn: on,
    licence: "conference paper; link and paraphrase only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Primary peer-reviewed source for pass^k, which measures whether all k trials of a task succeed and therefore emphasizes repeated reliability.",
    caveat: "The published benchmark uses simulated users, domain tools, and database-state graders. Pass^k depends on the trial protocol and should not be calculated by naïvely exponentiating one noisy observed success rate.",
  },
  {
    id: "anthropic-code-hooks",
    tier: "primary",
    kind: "official-doc",
    title: "Claude Code hooks",
    publisher: "Anthropic",
    url: "https://code.claude.com/docs/en/hooks",
    accessedOn: on,
    licence: "site terms; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Lifecycle interception using command, HTTP, MCP-tool, prompt, or agent handlers, including event-specific blocking behavior.",
    caveat: "Triggering and handler outcomes are different guarantees: prompt and agent handlers are probabilistic, local hooks may be disabled or misconfigured, and Stop blocking is capped. Critical authority needs protected permissions, CI, branch/environment controls, or managed policy rather than a hook alone.",
  },
  {
    id: "anthropic-claude-action-security",
    tier: "primary",
    kind: "official-github",
    title: "Claude Code Action security guide",
    publisher: "Anthropic",
    url: "https://github.com/anthropics/claude-code-action/blob/main/docs/security.md",
    accessedOn: on,
    licence: "MIT",
    reuse: "paraphrase-and-link",
    evidenceUse: "Prompt injection, actor allowlists, short-lived tokens, sanitization limits, and least-privilege workflow permissions.",
    caveat: "Sanitization reduces risk but cannot be treated as a complete prompt-injection boundary.",
  },
  {
    id: "swebok-v4",
    tier: "primary",
    kind: "official-standard",
    title: "Guide to the Software Engineering Body of Knowledge, version 4.0a",
    publisher: "IEEE Computer Society",
    url: "https://ieeecs-media.computer.org/media/education/swebok/swebok-v4.pdf",
    accessedOn: on,
    licence: "copyrighted standard; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Coverage backbone for all eighteen SWEBOK v4.0a knowledge areas, including the three foundations areas; the course maps them without reproducing the Guide.",
    caveat: "The course synthesizes and maps knowledge areas; it does not reproduce the guide.",
  },
  {
    id: "sei-quality-attribute-scenarios",
    tier: "primary",
    kind: "official-doc",
    title: "Eliciting and Specifying Quality Attribute Requirements",
    publisher: "Carnegie Mellon Software Engineering Institute",
    url: "https://resources.sei.cmu.edu/asset_files/Webinar/2013_018_101_60984.pdf",
    accessedOn: on,
    licence: "copyrighted educational material; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Canonical six-part quality-attribute scenario: source, stimulus, environment, artifact, response, and response measure.",
    caveat: "The scenario structure helps make quality requirements testable; it does not choose an architecture or prove that a quality target is achievable.",
  },
  {
    id: "scrum-guide-2020",
    tier: "primary",
    kind: "official-doc",
    title: "The 2020 Scrum Guide",
    publisher: "Ken Schwaber and Jeff Sutherland",
    url: "https://scrumguides.org/scrum-guide.html",
    accessedOn: on,
    licence: "Scrum Guide terms; link and paraphrase only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Official definition of Scrum accountabilities, events, artifacts, commitments, and event timeboxes.",
    caveat: "Scrum is one process framework. Its terminology does not establish that it fits a particular organization, regulatory context, or agentic workflow.",
  },
  {
    id: "nist-ssdf",
    tier: "primary",
    kind: "official-standard",
    title: "Secure Software Development Framework (SP 800-218)",
    publisher: "NIST",
    url: "https://csrc.nist.gov/Projects/ssdf",
    accessedOn: on,
    licence: "U.S. government work / site terms",
    reuse: "paraphrase-and-link",
    evidenceUse: "Outcome-oriented secure development practices spanning people, process, protection, production, and vulnerability response.",
    caveat: "SSDF is a framework to tailor, not a prescriptive checklist that proves a product secure.",
  },
  {
    id: "nist-ai-rmf",
    tier: "primary",
    kind: "official-standard",
    title: "AI Risk Management Framework",
    publisher: "NIST",
    url: "https://www.nist.gov/itl/ai-risk-management-framework",
    accessedOn: on,
    licence: "U.S. government work / site terms",
    reuse: "paraphrase-and-link",
    evidenceUse: "Govern, map, measure, and manage structure for agent evaluation, accountability, and risk treatment.",
    caveat: "Applying the vocabulary does not itself establish compliance or acceptable residual risk.",
  },
  {
    id: "dora-continuous-delivery",
    tier: "primary",
    kind: "official-doc",
    title: "Continuous delivery",
    publisher: "DORA",
    url: "https://dora.dev/capabilities/continuous-delivery/",
    accessedOn: on,
    licence: "CC-BY-4.0 documentation",
    reuse: "paraphrase-and-link",
    evidenceUse: "Fast, safe, sustainable delivery through version control, automated testing, deployment automation, and small changes.",
    caveat: "Capability guidance must be interpreted in the team and system context; metrics are not targets in isolation.",
  },
  {
    id: "dora-ai-report-2025",
    tier: "corroborating",
    kind: "practitioner-guide",
    title: "State of AI-assisted Software Development 2025",
    publisher: "DORA",
    url: "https://dora.dev/research/2025/dora-report/",
    accessedOn: on,
    licence: "CC-BY-4.0 documentation",
    reuse: "paraphrase-and-link",
    evidenceUse: "System-level interpretation that AI amplifies the delivery environment it enters.",
    caveat: "Organizational research is correlational and should not be reduced to a universal productivity promise.",
  },
  {
    id: "wcag-22",
    tier: "primary",
    kind: "official-standard",
    title: "Web Content Accessibility Guidelines 2.2",
    publisher: "W3C",
    url: "https://www.w3.org/TR/WCAG22/",
    accessedOn: on,
    licence: "W3C document licence",
    reuse: "paraphrase-and-link",
    evidenceUse: "Accessibility requirements and verification beyond visually plausible UI output.",
    caveat: "Conformance requires evaluating the complete page against normative success criteria, not a single automated scan.",
  },
  {
    id: "google-sre-book",
    tier: "primary",
    kind: "official-doc",
    title: "Site Reliability Engineering",
    publisher: "Google",
    url: "https://sre.google/sre-book/table-of-contents/",
    accessedOn: on,
    licence: "CC-BY-NC-ND 4.0; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "SLIs, SLOs, error budgets, monitoring, incident response, and operational engineering concepts.",
    caveat: "Google-scale examples require adaptation; this course does not reproduce book text or diagrams.",
  },
  {
    id: "green-software-sci",
    tier: "primary",
    kind: "official-standard",
    title: "Software Carbon Intensity specification (ISO/IEC 21031:2024)",
    publisher: "Green Software Foundation",
    url: "https://greensoftware.foundation/standards/sci/",
    accessedOn: on,
    licence: "GSF source-page/repository terms; ISO edition © ISO; link and paraphrase only",
    reuse: "paraphrase-and-link",
    evidenceUse: "A functional-unit method for measuring operational energy emissions, location-based grid carbon intensity, and embodied hardware emissions attributable to software.",
    caveat: "SCI is a measurement method, not proof that a particular optimization lowers lifecycle impact; define the functional unit and measurement boundary and preserve service quality.",
  },
  {
    id: "slsa-provenance",
    tier: "primary",
    kind: "official-standard",
    title: "SLSA provenance",
    publisher: "Open Source Security Foundation",
    url: "https://slsa.dev/spec/v1.2/provenance",
    accessedOn: on,
    licence: "Community Specification License 1.0",
    reuse: "paraphrase-and-link",
    evidenceUse: "Build provenance and supply-chain integrity for artifacts produced through automated and agentic workflows.",
    caveat: "Provenance records how an artifact was produced; it does not prove the artifact is vulnerability-free.",
  },
  {
    id: "owasp-llm-top10",
    tier: "primary",
    kind: "practitioner-guide",
    title: "2025 Top 10 Risk & Mitigations for LLMs and Gen AI Apps",
    publisher: "OWASP Foundation",
    url: "https://genai.owasp.org/llm-top-10/",
    accessedOn: on,
    licence: "CC-BY-SA-4.0",
    reuse: "paraphrase-and-link",
    evidenceUse: "Threat vocabulary for prompt injection, sensitive information disclosure, excessive agency, and supply-chain risk.",
    caveat: "A top-ten list supports threat discovery but is not a complete threat model or control catalogue.",
  },
  {
    id: "metr-productivity-study",
    tier: "corroborating",
    kind: "replication-package",
    title: "Measuring early-2025 AI on experienced open-source developers",
    publisher: "METR",
    url: "https://github.com/METR/Measuring-Early-2025-AI-on-Exp-OSS-Devs",
    accessedOn: on,
    licence: "no recognized repository licence; link only",
    reuse: "paraphrase-and-link",
    evidenceUse: "Controlled evidence that perceived speed and measured completion time can diverge, motivating local multidimensional evaluation.",
    caveat: "Sixteen experienced maintainers, mature repositories, and early-2025 tools; do not generalize the reported slowdown to all developers or tasks.",
  },
  {
    id: "swe-chat",
    tier: "corroborating",
    kind: "research-preprint",
    title: "SWE-chat: Coding Agent Interactions From Real Users in the Wild",
    publisher: "SALT-NLP",
    url: "https://arxiv.org/abs/2604.20779",
    accessedOn: on,
    licence: "CC BY 4.0 paper; ODC-BY dataset with access conditions",
    reuse: "paraphrase-and-link",
    evidenceUse: "Observational evidence for steering, discarded generated code, and evaluating accepted artifacts rather than generation volume.",
    caveat: "Unreviewed arXiv preprint. Public-repository sessions are observational and not representative of every professional setting; the gated living dataset can change, and static-analysis findings are signals rather than confirmed vulnerabilities.",
  },
  {
    id: "coding-agents-wild",
    tier: "corroborating",
    kind: "replication-package",
    title: "Coding Agents in the Wild",
    publisher: "Research replication package",
    url: "https://github.com/mahdhindi/coding-agents-wild",
    accessedOn: on,
    licence: "MIT code; paper CC-BY-4.0",
    reuse: "paraphrase-and-link",
    evidenceUse: "Agent-authored pull-request outcomes and the importance of specification fit, tests, documentation, and reviewer evidence.",
    caveat: "Failure classification covers the commented rejection subset and uses an imperfect classifier; associations are not causal.",
  },
  {
    id: "microsoft-security-debt",
    tier: "corroborating",
    kind: "replication-package",
    title: "When developer aid becomes security debt",
    publisher: "Microsoft Research",
    url: "https://github.com/microsoft/coding-agent-security-debt",
    accessedOn: on,
    licence: "MIT",
    reuse: "paraphrase-and-link",
    evidenceUse: "Evidence that insecure actions can occur during setup/configuration trajectories, extending review beyond the final code diff.",
    caveat: "One harness, 93 tasks, historical model snapshots, and a detector with limited recall; absence of a detected action does not establish safety.",
  },
  {
    id: "agent-library-usage",
    tier: "corroborating",
    kind: "peer-reviewed",
    title: "A study of library usage in agent-authored pull requests",
    publisher: "MSR 2026 authors",
    url: "https://github.com/itsluketwist/agent-library-usage",
    accessedOn: on,
    licence: "CC-BY-4.0",
    reuse: "paraphrase-and-link",
    evidenceUse: "Dependency additions as explicit architecture, security, licensing, and maintenance decisions.",
    caveat: "Observational aggregate data do not establish that a particular dependency choice is safe or unsafe.",
  },
  {
    id: "context-files-study",
    tier: "corroborating",
    kind: "replication-package",
    title: "Do context files help coding agents?",
    publisher: "Independent researchers",
    url: "https://github.com/codeprakhar25/context-files-coding-agents",
    accessedOn: on,
    licence: "MIT",
    reuse: "paraphrase-and-link",
    evidenceUse: "Ablation evidence from 291 raw runs, 288 of which entered the correctness analysis, supporting local evaluation of context files rather than assumed benefit.",
    caveat: "Small, underpowered sample across three Python repositories. The reported repository-specific process differences were exploratory and post hoc; treat them as hypotheses for replication, not general improvements.",
  },
  {
    id: "swe-bench",
    tier: "primary",
    kind: "official-github",
    title: "SWE-bench",
    publisher: "Princeton NLP",
    url: "https://github.com/SWE-bench/SWE-bench",
    accessedOn: on,
    licence: "MIT",
    reuse: "paraphrase-and-link",
    evidenceUse: "Containerized issue-resolution evaluation, fail-to-pass and pass-to-pass tests, and evaluator-integrity lessons.",
    caveat: "A harness pass covers a bounded issue task, not production readiness, maintainability, accessibility, security, deployment, or operations.",
  },
  {
    id: "swe-agent-trajectories",
    tier: "primary",
    kind: "official-github",
    title: "SWE-agent trajectories",
    publisher: "SWE-agent project",
    url: "https://github.com/SWE-agent/SWE-agent/blob/main/docs/usage/trajectories.md",
    accessedOn: on,
    licence: "MIT",
    reuse: "paraphrase-and-link",
    evidenceUse: "Run records containing tool interactions, configuration, predictions, logs, exit status, and inspectable evidence; a generated configuration can support a repeated run.",
    caveat: "The inspector visualizes and navigates recorded trajectories; it does not replay them. A repeated run can diverge because model output, services, dependencies, credentials, environment, or repository state changed.",
  },
  {
    id: "vscode-agent-instructions",
    tier: "corroborating",
    kind: "maintainer-policy",
    title: "VS Code copilot instructions",
    publisher: "Microsoft VS Code maintainers",
    url: "https://github.com/microsoft/vscode/blob/main/.github/copilot-instructions.md",
    accessedOn: on,
    licence: "MIT",
    reuse: "paraphrase-and-link",
    evidenceUse: "Production example of architecture boundaries, dependency direction, canonical commands, testing, localization, and cleanup conventions.",
    caveat: "A maintained instruction file is practitioner evidence, not controlled proof that every instruction changes agent outcomes.",
  },
  {
    id: "github-agentic-workflows",
    tier: "primary",
    kind: "official-github",
    title: "GitHub Agentic Workflows security architecture",
    publisher: "GitHub",
    url: "https://github.com/github/gh-aw/blob/main/docs/src/content/docs/introduction/architecture.mdx",
    accessedOn: on,
    licence: "MIT",
    reuse: "paraphrase-and-link",
    evidenceUse: "Read-only agent jobs, structured safe outputs, separated write authority, egress controls, sanitization, and independent scanning.",
    caveat: "Threat detection includes probabilistic components and is explicitly not a security guarantee.",
  },
  {
    id: "pytest-ai-policy",
    tier: "corroborating",
    kind: "maintainer-policy",
    title: "pytest contribution policy for AI/LLM-assisted changes",
    publisher: "pytest maintainers",
    url: "https://github.com/pytest-dev/pytest/blob/main/CONTRIBUTING.rst",
    accessedOn: on,
    licence: "MIT",
    reuse: "paraphrase-and-link",
    evidenceUse: "Human submitter accountability, understanding, review participation, and rejection of unattended output.",
    caveat: "Normative community policy, not a causal productivity study.",
  },
  {
    id: "qiskit-ai-policy",
    tier: "corroborating",
    kind: "maintainer-policy",
    title: "Qiskit contribution policy for generative AI",
    publisher: "Qiskit maintainers",
    url: "https://github.com/Qiskit/qiskit/blob/1977d1aa7d0a3a9212c07707929453a73788d8b0/CONTRIBUTING.md#use-of-generative-ai",
    accessedOn: on,
    licence: "Apache-2.0",
    reuse: "paraphrase-and-link",
    evidenceUse: "Disclosure of substantial generative-AI use, human-driven repository interaction, contributor review, understanding and explanation, original authorship and CLA responsibility, and third-party licence and tool-term compliance.",
    caveat: "Project-specific governance should inform—not be copied blindly into—another repository's policy. This record pins the policy revision current on the observation date because the mutable main-branch policy has changed before.",
  },
] as const satisfies readonly SoftwareEngineeringSourceRecord[];

export const SOFTWARE_ENGINEERING_SOURCE_BY_ID = Object.fromEntries(
  SOFTWARE_ENGINEERING_SOURCES.map((source) => [source.id, source]),
) as Readonly<Record<string, SoftwareEngineeringSourceRecord>>;
