import type { CourseKitModuleAuthoringSeed } from "../course-kit/authoring";
import type {
  CourseKitFourOptions,
  CourseKitNonEmpty,
  CourseKitOptionIndex,
} from "../course-kit/types";
import type { ProductionAiSourceId } from "./sources";

interface ProductionAiModuleText {
  readonly title: string;
  readonly summary: string;
  readonly objective: string;
  readonly artifact: string;
  readonly conceptHeading: string;
  readonly concept: string;
  readonly methodHeading: string;
  readonly method: string;
  readonly boundaryHeading: string;
  readonly boundary: string;
  readonly practiceTitle: string;
  readonly practiceBrief: string;
  readonly steps: CourseKitNonEmpty<string>;
  readonly deliverable: string;
  readonly reviewGate: string;
  readonly checkpointQuestion: string;
  readonly checkpointOptions: CourseKitFourOptions;
  readonly checkpointCorrectIndex: CourseKitOptionIndex;
  readonly checkpointExplanation: string;
  readonly takeaway: string;
}

function productionAiModule<
  const Slug extends string,
  const PhaseId extends string,
  const SourceId extends ProductionAiSourceId,
>(seed: {
  readonly slug: Slug;
  readonly phaseId: PhaseId;
  readonly minutes: number;
  readonly sourceIds: CourseKitNonEmpty<SourceId>;
  readonly en: ProductionAiModuleText;
  readonly zhHans: ProductionAiModuleText;
}): CourseKitModuleAuthoringSeed<Slug, PhaseId, SourceId> {
  const copy = (text: ProductionAiModuleText) => ({
    title: text.title,
    summary: text.summary,
    objective: text.objective,
    artifact: text.artifact,
    sections: [
      {
        heading: text.conceptHeading,
        paragraphs: [text.concept],
        sourceIds: seed.sourceIds,
        evidenceMode: "source-grounded" as const,
      },
      {
        heading: text.methodHeading,
        paragraphs: [text.method],
        sourceIds: seed.sourceIds,
        evidenceMode: "instructional-synthesis" as const,
      },
      {
        heading: text.boundaryHeading,
        paragraphs: [text.boundary],
        sourceIds: seed.sourceIds,
        evidenceMode: "source-grounded" as const,
      },
    ] as const,
    practice: {
      title: text.practiceTitle,
      brief: text.practiceBrief,
      steps: text.steps,
      deliverable: text.deliverable,
      reviewGate: text.reviewGate,
    },
    checkpoint: {
      question: text.checkpointQuestion,
      options: text.checkpointOptions,
      correctIndex: text.checkpointCorrectIndex,
      explanation: text.checkpointExplanation,
    },
    takeaway: text.takeaway,
  });

  return {
    slug: seed.slug,
    phaseId: seed.phaseId,
    minutes: seed.minutes,
    sourceIds: seed.sourceIds,
    copy: { en: copy(seed.en), zhHans: copy(seed.zhHans) },
  };
}

export const PRODUCTION_AI_MODULES = [
  productionAiModule({
    slug: "production-contract-slis-slos",
    phaseId: "contracts-and-lineage",
    minutes: 60,
    sourceIds: ["pa01-slos", "ml11-production-readiness"],
    en: {
      title: "Production contract, SLIs and SLOs",
      summary: "Translate user outcomes into measurable operating promises for a classifier and a retrieval-generation service without collapsing distinct failure modes into one score.",
      objective: "Define versioned SLIs, SLOs, windows, denominators, error budgets, owners, alerts, and degradation actions for two different AI services.",
      artifact: "Dual-system SLO sheet with outcome, quality, latency, availability, cost, and safety signals plus owners and stop actions",
      conceptHeading: "A production contract begins with the user-visible outcome",
      concept: "An SLI is a precisely computed observation; an SLO is a target over a declared population and window. Model quality, successful-task latency, availability, cost, citation support, harmful-output signals, and human escalation answer different questions. Error budgets turn repeated misses into an operating decision rather than a decorative dashboard number.",
      methodHeading: "Write every numerator, denominator, window, and consequence",
      method: "For both services, define the request boundary, eligible population, exclusion rule, success event, measurement source, latency clock, label delay, missing-data treatment, target, review cadence, owner, alert, and degrade/hold/rollback action. Test each formula against empty traffic, retries, timeouts, partial responses, and delayed labels.",
      boundaryHeading: "Objectives are not contracts with the world",
      boundary: "An internal SLO is not an SLA, legal duty, safety certification, or promise of zero downtime. A high aggregate value can conceal a severe slice failure, a cost breach, or unsupported generated content; 100 percent targets can also prevent meaningful risk-based operation.",
      practiceTitle: "Specify two non-interchangeable service contracts",
      practiceBrief: "Use the original dual-system fixture to define a classifier contract and a retrieval-generation contract.",
      steps: ["Declare the user task, request boundary, eligible denominator, and excluded traffic for each system.", "Define at least five separately owned SLIs and exact formulas, windows, targets, and missing-data rules.", "Inject a retry storm and a citation failure; show which metrics change and which stay silent.", "Record hold, degrade, rollback, and human escalation actions for each breached objective."],
      deliverable: "A versioned dual-system SLO contract with worked denominator tests and named owners",
      reviewGate: "A reviewer can recompute every SLI from fixture events and each breached target resolves to a specific human-owned action rather than automatic deployment approval.",
      checkpointQuestion: "What makes an SLO operationally reviewable?",
      checkpointOptions: ["A target percentage without a measurement window", "An exact population, numerator, denominator, window, data source, owner, and consequence", "A claim that availability will always be 100 percent", "One average combining quality, latency, cost, and safety"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "A target becomes auditable only when its calculation boundary and the decision triggered by a miss are explicit.",
      takeaway: "SLIs and SLOs organize bounded operating decisions; they are not SLAs, legal guarantees, or evidence that an AI service is safe.",
    },
    zhHans: {
      title: "生产合同、SLI 与 SLO",
      summary: "把用户结果转化为分类服务与检索生成服务的可测运行承诺，同时不把不同故障压成一个分数。",
      objective: "为两种 AI 服务定义版本化 SLI、SLO、窗口、分母、错误预算、负责人、告警与降级动作。",
      artifact: "包含结果、质量、延迟、可用性、成本与安全信号以及负责人和停止动作的双系统 SLO 表",
      conceptHeading: "生产合同从用户可见结果开始",
      concept: "SLI 是精确定义的观测，SLO 是针对已声明群体和窗口的目标。模型质量、成功任务延迟、可用性、成本、引文支持、有害输出信号与人工升级回答不同问题。错误预算把反复失约转化为运行决定，而不是仪表板装饰数字。",
      methodHeading: "写出每个分子、分母、窗口与后果",
      method: "对两个服务分别定义请求边界、合格群体、排除规则、成功事件、测量来源、延迟时钟、标签延迟、缺失处理、目标、审查周期、负责人、告警和降级/暂停/回滚动作。用空流量、重试、超时、部分响应与延迟标签测试每个公式。",
      boundaryHeading: "目标不是对现实世界的保证",
      boundary: "内部 SLO 不是 SLA、法律义务、安全认证或零停机承诺。高总体值可能掩盖严重切片失败、成本超限或无支持生成内容；100% 目标也可能阻碍有意义的风险运行。",
      practiceTitle: "定义两个不可互换的服务合同",
      practiceBrief: "使用原创双系统 fixture 定义分类器合同与检索生成合同。",
      steps: ["声明每个系统的用户任务、请求边界、合格分母与排除流量。", "定义至少五项分别负责的 SLI，以及精确公式、窗口、目标与缺失规则。", "注入重试风暴与引文失败，说明哪些指标变化、哪些保持沉默。", "为每项目标违约记录暂停、降级、回滚与人工升级动作。"],
      deliverable: "一份含分母演算测试与具名负责人的版本化双系统 SLO 合同",
      reviewGate: "审查者可从 fixture event 重算每项 SLI，且每项违约都解析到具体人类负责动作，而不是自动批准部署。",
      checkpointQuestion: "什么使 SLO 可供运行审查？",
      checkpointOptions: ["没有测量窗口的目标百分比", "精确群体、分子、分母、窗口、数据源、负责人和后果", "声称可用性永远为 100%", "把质量、延迟、成本与安全合成一个平均值"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "只有计算边界和失约触发的决定明确时，目标才可审计。",
      takeaway: "SLI/SLO 组织有边界的运行决定；它们不是 SLA、法律保证或 AI 服务安全证明。",
    },
  }),
  productionAiModule({
    slug: "data-training-pipelines",
    phaseId: "contracts-and-lineage",
    minutes: 70,
    sourceIds: ["pa02-tfx-pipelines", "pa03-mlmd", "ml11-production-readiness"],
    en: {
      title: "Data and training pipelines",
      summary: "Represent training as a typed component graph whose inputs, outputs, validations, cache keys, executions, and failure receipts can be reconstructed.",
      objective: "Build and challenge a train–evaluate–bless DAG that refuses stale caches, schema breaks, missing artifacts, and undeclared external state.",
      artifact: "Typed pipeline DAG with artifact contracts, execution receipts, cache policy, validation gates, and injected-failure report",
      conceptHeading: "A pipeline is a graph of artifact-producing executions",
      concept: "Components consume declared artifacts and parameters, execute under an environment, and emit versioned artifacts and metadata events. Dependencies determine ordering; validation gates decide whether an output may advance; cache identity must include every state element capable of changing the result.",
      methodHeading: "Make the happy path and failure path equally explicit",
      method: "For ingest, validate, transform, train, evaluate, bless, and package nodes, specify schemas, hashes, code and environment versions, cache inputs, retry semantics, timeout behavior, resource ceilings, outputs, owners, and evidence. Replay the graph after changing only schema and after hiding an external dependency.",
      boundaryHeading: "Green orchestration does not prove correct machine learning",
      boundary: "A DAG may finish while reading the wrong snapshot, reusing a stale cache, leaking validation data, suppressing a failure, or producing a semantically invalid model. Retrying a non-idempotent component can duplicate side effects, and an orchestrator cannot capture state that was never declared or instrumented.",
      practiceTitle: "Break and repair a training DAG",
      practiceBrief: "Build a fixture-backed graph, then inject one stale-cache fault and one incompatible schema revision.",
      steps: ["Declare each node's typed inputs, outputs, version, cache key, retry rule, timeout, owner, and validation condition.", "Execute the original graph and preserve artifact–execution receipts for every node.", "Change a schema without changing the naive cache key; demonstrate the incorrect reuse and strengthen invalidation.", "Make one external state dependency explicit, rerun from clean state, and record remaining reproduction limits."],
      deliverable: "A pipeline DAG, per-node receipts, two failing traces, and corrected cache and schema gates",
      reviewGate: "A reviewer can trace every promoted artifact to a generating execution and both injected faults stop promotion before the registry.",
      checkpointQuestion: "What does a successful orchestration run establish?",
      checkpointOptions: ["All data and model semantics are correct", "Only that the orchestrator completed its declared steps; correctness still requires artifact, schema, leakage, and evidence checks", "The run can reproduce across all platforms", "Every retry was exactly-once"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Orchestration status describes workflow execution, not the validity of undeclared assumptions or produced ML artifacts.",
      takeaway: "Pipeline success is execution evidence, not correctness or reproducibility proof; every mutable input and side effect must enter the contract.",
    },
    zhHans: {
      title: "数据与训练管线",
      summary: "把训练表示为有类型的组件图，使输入、输出、验证、cache key、执行与失败收据都可重建。",
      objective: "构建并挑战 train–evaluate–bless DAG，使其拒绝 stale cache、schema break、缺失产物与未声明外部状态。",
      artifact: "包含产物合同、执行收据、缓存政策、验证门禁与注入故障报告的 typed pipeline DAG",
      conceptHeading: "管线是生成产物的执行图",
      concept: "组件消费已声明产物与参数，在某个环境中执行，并输出版本化产物与 metadata event。依赖关系决定顺序；验证门禁决定输出能否推进；cache identity 必须包含所有会改变结果的状态元素。",
      methodHeading: "同样明确地写出成功与失败路径",
      method: "为 ingest、validate、transform、train、evaluate、bless 与 package 节点定义 schema、哈希、代码和环境版本、缓存输入、重试语义、超时、资源上限、输出、负责人和证据。只改 schema 后重放，再隐藏一个外部依赖重放。",
      boundaryHeading: "绿色编排不能证明机器学习正确",
      boundary: "DAG 可能在读取错误 snapshot、复用 stale cache、泄漏验证数据、压下失败或生成语义无效模型时仍然完成。重试非幂等组件可能重复副作用，orchestrator 也无法捕获从未声明或接入的状态。",
      practiceTitle: "破坏并修复训练 DAG",
      practiceBrief: "构建 fixture 驱动的图，再注入一个 stale-cache 故障和一个不兼容 schema revision。",
      steps: ["声明每个节点的 typed 输入输出、版本、cache key、重试规则、超时、负责人和验证条件。", "执行原始图并保留每个节点的 artifact–execution 收据。", "修改 schema 但不改简陋 cache key，演示错误复用并强化失效规则。", "显式化一个外部状态依赖，从干净状态重跑并记录剩余复现限制。"],
      deliverable: "一份 pipeline DAG、逐节点收据、两条失败 trace 与修正后的缓存/schema 门禁",
      reviewGate: "审查者可把每个推进的产物追溯到生成执行，且两项注入故障都在进入 registry 前停止推进。",
      checkpointQuestion: "成功的编排运行能够证明什么？",
      checkpointOptions: ["所有数据和模型语义正确", "只证明 orchestrator 完成已声明步骤；正确性仍需产物、schema、泄漏与证据检查", "运行可在所有平台复现", "每次重试都是 exactly-once"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "编排状态说明 workflow 执行，不验证未声明假设或所生产 ML 产物的有效性。",
      takeaway: "管线成功是执行证据，不是正确或复现证明；每个可变输入与副作用都必须进入合同。",
    },
  }),
  productionAiModule({
    slug: "dataset-feature-lineage-versioning",
    phaseId: "contracts-and-lineage",
    minutes: 70,
    sourceIds: ["pa03-mlmd", "pa04-openlineage"],
    en: {
      title: "Dataset, feature and lineage versioning",
      summary: "Trace production outputs backward to exact training inputs and propagate a changed or deleted input forward to every affected artifact and service.",
      objective: "Create a bidirectional lineage manifest covering raw and processed data, schemas, features, code, parameters, executions, models, indexes, and serving outputs.",
      artifact: "Bidirectional lineage graph and manifest with immutable identifiers, hashes, ownership, rights boundary, and impact-query evidence",
      conceptHeading: "Lineage connects artifacts through executions and contexts",
      concept: "Useful lineage distinguishes an artifact's identity and version from the execution that generated or consumed it. A training example, feature table, model, retrieval index, prompt template, evaluation set, image, deployment configuration, and prediction can form separate nodes with explicit typed edges.",
      methodHeading: "Test backward explanation and forward impact",
      method: "Assign content hashes and semantic versions, record locations and retention, link every transform to code, configuration, environment and parent artifacts, and state rights and deletion obligations. Starting from one production event, trace backward; starting from one source deletion, enumerate downstream rebuild, disable, notification, and evidence tasks.",
      boundaryHeading: "A complete-looking graph may still omit the decisive state",
      boundary: "Git, object versions, MLMD, or OpenLineage alone cannot capture every query result, mutable API, human approval, feature-store clock, access rule, or data right. A version identifier proves neither byte immutability nor quality, permission, causal contribution, or successful deletion from downstream artifacts.",
      practiceTitle: "Run two lineage impact queries",
      practiceBrief: "Trace a classifier prediction and a RAG answer backward, then simulate deletion of a source record.",
      steps: ["Inventory data, features, documents, embeddings, models, indexes, prompts, configs, evaluations, deployments, and outputs as typed artifacts.", "Connect each artifact to executions, contexts, code, parameters, environments, owners, rights, hashes, and retention state.", "Trace one output backward until every input and approval is identified or explicitly unknown.", "Delete one source in the fixture and produce a forward rebuild, disable, notice, and verification plan."],
      deliverable: "A versioned lineage manifest, two rendered paths, and a deletion-impact action record",
      reviewGate: "No unknown edge is silently treated as complete, and deletion impact reaches both models/indexes and already-produced external outcomes where applicable.",
      checkpointQuestion: "What does a dataset version identifier establish by itself?",
      checkpointOptions: ["The data is lawful and high quality", "Only the declared identity under that versioning scheme; bytes, lineage completeness, rights, and semantics need separate evidence", "All downstream copies were deleted", "The model can reproduce on any platform"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Versioning is a locator and change-control mechanism, not proof of completeness, rights, quality, or reproduction.",
      takeaway: "Lineage is only as complete as its instrumentation; version numbers never substitute for byte identity, rights, quality, or forward-impact verification.",
    },
    zhHans: {
      title: "数据集、特征与 lineage 版本化",
      summary: "把生产输出反向追溯到确切训练输入，并把变更或删除的输入向前传播到每个受影响产物与服务。",
      objective: "创建覆盖原始/处理数据、schema、feature、代码、参数、执行、模型、索引与服务输出的双向 lineage manifest。",
      artifact: "含不可变标识、哈希、所有权、权利边界与 impact query 证据的双向 lineage 图和 manifest",
      conceptHeading: "Lineage 通过执行与 context 连接产物",
      concept: "有用的 lineage 会区分产物身份和版本与生成或消费它的执行。训练样本、feature table、模型、检索索引、prompt template、评测集、镜像、部署配置与 prediction 都可以成为具有显式 typed edge 的独立节点。",
      methodHeading: "测试反向解释与正向影响",
      method: "分配内容哈希与语义版本，记录位置和保留期，把每项 transform 连接到代码、配置、环境和父产物，并说明权利与删除义务。从一个生产 event 反向追踪；从一个源删除正向枚举重建、禁用、通知与验证任务。",
      boundaryHeading: "看似完整的图仍可能遗漏决定性状态",
      boundary: "Git、对象版本、MLMD 或 OpenLineage 单独都无法捕获每个查询结果、可变 API、人类批准、feature-store 时钟、访问规则或数据权利。版本标识既不证明 byte 不变，也不证明质量、许可、因果贡献或下游成功删除。",
      practiceTitle: "执行两次 lineage impact query",
      practiceBrief: "反向追踪一个分类预测和一个 RAG 答案，再模拟删除一条源记录。",
      steps: ["把数据、feature、文档、embedding、模型、索引、prompt、配置、评测、部署与输出清点为 typed artifact。", "把每个 artifact 连接到 execution、context、代码、参数、环境、负责人、权利、哈希与保留状态。", "从一个输出反向追踪，直到识别每项输入与批准，或明确标为未知。", "删除 fixture 中一个来源，并生成向前的重建、禁用、通知与验证计划。"],
      deliverable: "一份版本化 lineage manifest、两条渲染路径与删除影响行动记录",
      reviewGate: "没有未知 edge 被默认为完整，删除影响同时覆盖模型/索引以及适用时已产生的外部结果。",
      checkpointQuestion: "数据集版本标识本身能证明什么？",
      checkpointOptions: ["数据合法且高质量", "只证明该版本方案下声明的身份；bytes、lineage 完整性、权利与语义需要另行证据", "所有下游副本已删除", "模型可在任意平台复现"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "版本化是定位与变更控制机制，不是完整性、权利、质量或复现证明。",
      takeaway: "Lineage 的完整度取决于 instrumentation；版本号绝不能替代 byte identity、权利、质量或正向影响核验。",
    },
  }),
  productionAiModule({
    slug: "experiment-tracking-reproducibility",
    phaseId: "evidence-and-release",
    minutes: 70,
    sourceIds: ["pa05-mlflow-tracking"],
    en: {
      title: "Experiment tracking and reproducibility",
      summary: "Turn every successful, repeated, and failed run into a reconstructable evidence record rather than a leaderboard row.",
      objective: "Design an experiment record that binds code, data, environment, configuration, seed, metrics, definitions, artifacts, parent runs, failures, and resource receipts.",
      artifact: "Versioned experiment record set with a clean-room replay, deliberate unlocked-dependency failure, and discrepancy report",
      conceptHeading: "Tracking locates evidence; reproduction tests it",
      concept: "A run record should connect parameters, code and data versions, environment, random state, metric observations, artifacts, lineage, time, resources, and ownership. Repetition estimates variability under the declared process; clean-room reproduction tests whether another environment and operator can reconstruct that process and interpret its outputs.",
      methodHeading: "Preserve losing runs and metric semantics",
      method: "Define metric formula, aggregation, unit, direction, population, window, label version, and uncertainty beside its value. Log child runs, retries, failures, stdout/stderr, resource ceilings, artifact hashes, and deletion state. Reproduce from an empty environment, then deliberately leave one dependency unlocked and diagnose the divergence without rewriting history.",
      boundaryHeading: "A populated tracking server is not reproducibility",
      boundary: "Two metrics with the same name can use different populations or formulas; an artifact URI can resolve to changed or unavailable bytes; seeds do not eliminate nondeterminism across libraries, hardware, kernels, or concurrency. Deleting failed runs creates selection bias and breaks the audit trail.",
      practiceTitle: "Reproduce a run that was designed to fail",
      practiceBrief: "Create three related fixture runs, hide one dependency lock, and conduct a clean-room replay.",
      steps: ["Define a run schema covering code, data, environment, configuration, random state, metrics, artifacts, lineage, time, cost, status, and owner.", "Record a baseline, a repetition, and a failed child run without deleting or renaming evidence.", "Replay in a clean environment, compare hashes and tolerances, and isolate the unlocked dependency.", "Write a discrepancy report that separates exact matches, tolerated variance, unexplained variance, and unsupported claims."],
      deliverable: "Three linked experiment records, immutable artifacts, replay transcript, and signed discrepancy report",
      reviewGate: "A new operator can reconstruct the declared run or precisely locate why they cannot, and no metric value is accepted without its semantic definition.",
      checkpointQuestion: "Which record is necessary for a defensible reproduction claim?",
      checkpointOptions: ["Only the best metric and model file", "Code, data, environment, configuration, seed, metric definition, artifacts, failures, commands, and observed variance", "A tracking-server screenshot", "A run name that contains the date"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Reproduction depends on the full executable and interpretive context, including failures and variance—not a model artifact alone.",
      takeaway: "Tracking makes evidence locatable; only a clean-room replay with semantic and byte-level checks can support a bounded reproducibility claim.",
    },
    zhHans: {
      title: "实验追踪与可复现性",
      summary: "把每次成功、重复与失败运行变成可重建证据记录，而不是排行榜中的一行。",
      objective: "设计绑定代码、数据、环境、配置、种子、指标定义、产物、parent run、失败与资源收据的实验记录。",
      artifact: "包含 clean-room 重放、故意未锁依赖故障与差异报告的版本化实验记录集",
      conceptHeading: "Tracking 定位证据，复现检验证据",
      concept: "run 记录应连接参数、代码和数据版本、环境、随机状态、指标观测、产物、lineage、时间、资源与所有权。重复运行估计声明过程下的变异；clean-room 复现测试另一环境与操作者能否重建该过程并解释输出。",
      methodHeading: "保留失败运行与指标语义",
      method: "在指标值旁定义公式、聚合、单位、方向、群体、窗口、标签版本与不确定性。记录 child run、重试、失败、stdout/stderr、资源上限、artifact 哈希与删除状态。从空环境复现，再故意保留一个未锁依赖并诊断差异，且不改写历史。",
      boundaryHeading: "有内容的 tracking server 不等于可复现",
      boundary: "同名指标可能使用不同群体或公式；artifact URI 可能解析到已改变或不可用 bytes；种子不能消除跨 library、硬件、kernel 或并发的 nondeterminism。删除失败运行会制造选择偏差并破坏审计轨迹。",
      practiceTitle: "复现一个被设计为失败的运行",
      practiceBrief: "创建三次关联 fixture run，隐藏一个依赖锁，并执行 clean-room 重放。",
      steps: ["定义覆盖代码、数据、环境、配置、随机状态、指标、产物、lineage、时间、成本、状态与负责人的 run schema。", "记录 baseline、重复和失败 child run，不删除或改名证据。", "在干净环境重放，比较哈希与容差，并隔离未锁依赖。", "撰写差异报告，区分精确匹配、允许变异、未解释变异与不受支持声明。"],
      deliverable: "三份关联实验记录、不可变产物、重放记录与已签署差异报告",
      reviewGate: "新操作者能重建声明运行或精确定位为何不能，且任何指标值都不会脱离其语义定义被接受。",
      checkpointQuestion: "哪种记录是可辩护复现声明所必需？",
      checkpointOptions: ["只有最佳指标与模型文件", "代码、数据、环境、配置、种子、指标定义、产物、失败、命令与观测变异", "tracking server 截图", "包含日期的 run 名称"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "复现依赖完整可执行与解释情境，包括失败和变异，而不只是模型产物。",
      takeaway: "Tracking 让证据可定位；只有含语义与 byte 检查的 clean-room 重放才能支持有边界复现声明。",
    },
  }),
  productionAiModule({
    slug: "model-registry-approval-cards",
    phaseId: "evidence-and-release",
    minutes: 70,
    sourceIds: ["pa06-mlflow-registry", "ra12-model-cards", "ml11-production-readiness"],
    en: {
      title: "Model registry, approval and cards",
      summary: "Separate immutable model identity, technical evidence, risk review, accountable authorization, release alias, and rollback target.",
      objective: "Design a registry entry and four-stage gate in which tests, risk review, named owner approval, and deployment are distinct, rejectable events.",
      artifact: "Immutable registry entry, evidence-linked model/service card, four-gate decision log, and verified rollback target",
      conceptHeading: "A registry coordinates identity and workflow, not authority by itself",
      concept: "A useful entry binds content-addressed model bytes to code, data, environment, training and evaluation records, intended and excluded uses, limitations, owners, expiry, dependencies, aliases, and rollback targets. Evidence checks and human decisions should be separate timestamped events with reasons and revocation paths.",
      methodHeading: "Make rejection and expiry first-class states",
      method: "Define four gates: automated integrity and performance tests; independent risk and rights review; named accountable owner decision; and release execution. At each gate record evidence version, reviewer, decision, rationale, conditions, expiry, appeal or escalation, and next allowed action. Prove that a rejected version cannot inherit an old approval through an alias change.",
      boundaryHeading: "Production labels do not authorize deployment",
      boundary: "A registry stage, alias, tag, or green test is metadata, not governance approval. Cards can be incomplete or stale; approvers can lack authority; referenced evidence can expire. Approval of model bytes also does not automatically approve a new dataset, prompt, index, container, threshold, market, or use case.",
      practiceTitle: "Operate a four-gate registry",
      practiceBrief: "Register two fixture versions, reject one for missing evidence, and demonstrate safe alias and rollback behavior.",
      steps: ["Bind each version to immutable model, code, data, environment, evaluation, card, and dependency identifiers.", "Run technical tests and a separate rights/risk review; preserve the failed evidence and rejection reason.", "Require a named owner to approve or reject with conditions and expiry rather than auto-promoting on tests.", "Change the serving alias, verify the deployed digest, then rollback to an independently verified target."],
      deliverable: "Two registry entries, full card, four-gate audit log, rejected decision, and rollback verification receipt",
      reviewGate: "No alias or test result impersonates human authorization, expired evidence blocks promotion, and rollback points to verified bytes plus compatible dependencies.",
      checkpointQuestion: "When may a registry version be treated as deployment-authorized?",
      checkpointOptions: ["Whenever it carries a Production alias", "Only after the declared technical, rights/risk, and named human-approval gates pass for the exact model and deployment context", "Whenever its metric is highest", "As soon as an automated test writes PASS"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Registry metadata coordinates workflow, but authority requires the exact declared evidence and accountable human decision for the actual context.",
      takeaway: "Registry metadata and technical PASS never substitute for current evidence, scoped risk review, and a named human deployment decision.",
    },
    zhHans: {
      title: "模型 registry、批准门禁与 card",
      summary: "分开不可变模型身份、技术证据、风险审查、责任授权、release alias 与 rollback target。",
      objective: "设计 registry entry 与四阶段门禁，使测试、风险审查、具名负责人批准与部署成为彼此独立且可拒绝的事件。",
      artifact: "不可变 registry entry、证据链接 model/service card、四门禁决定日志与已验证回滚目标",
      conceptHeading: "Registry 协调身份与 workflow，本身不产生决定权",
      concept: "有用 entry 把内容寻址模型 bytes 与代码、数据、环境、训练/评测记录、预期和排除用途、限制、负责人、到期、依赖、alias 与回滚目标绑定。证据检查和人类决定应成为带理由与撤销路径的独立时间戳事件。",
      methodHeading: "把拒绝与到期作为一等状态",
      method: "定义四门禁：自动完整性/性能测试、独立风险与权利审查、具名责任人决定、release 执行。每门记录证据版本、审查者、决定、理由、条件、到期、申诉或升级与下一允许动作。证明 rejected version 不能通过 alias 变更继承旧批准。",
      boundaryHeading: "Production 标签不授权部署",
      boundary: "registry stage、alias、tag 或绿色测试都是 metadata，不是治理批准。card 可能不完整或过期；批准者可能无权限；引用证据可能失效。批准模型 bytes 也不会自动批准新数据集、prompt、index、container、threshold、市场或用途。",
      practiceTitle: "运行四门禁 registry",
      practiceBrief: "登记两个 fixture 版本，因证据缺失拒绝一个，并演示安全 alias 与回滚行为。",
      steps: ["把每个版本绑定到不可变模型、代码、数据、环境、评测、card 与依赖标识。", "运行技术测试和独立权利/风险审查，保留失败证据与拒绝理由。", "要求具名负责人带条件和期限批准或拒绝，而不是测试后自动推进。", "切换 serving alias、验证部署 digest，再回滚到已独立验证目标。"],
      deliverable: "两份 registry entry、完整 card、四门禁审计日志、拒绝决定与回滚验证收据",
      reviewGate: "没有 alias 或测试结果冒充人类授权，过期证据会阻止推进，回滚同时指向已验证 bytes 与兼容依赖。",
      checkpointQuestion: "何时可把 registry version 视为获得部署授权？",
      checkpointOptions: ["只要带有 Production alias", "只有针对确切模型与部署情境通过已声明技术、权利/风险和具名人工批准门禁后", "只要指标最高", "自动测试写入 PASS 后立即"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Registry metadata 协调 workflow，但权限需要针对实际情境的确切证据与责任人类决定。",
      takeaway: "Registry metadata 与技术 PASS 永远不能替代当前证据、有范围风险审查与具名人类部署决定。",
    },
  }),
  productionAiModule({
    slug: "batch-online-serving",
    phaseId: "evidence-and-release",
    minutes: 75,
    sourceIds: ["pa07-kserve", "pa08-tf-serving"],
    en: {
      title: "Batch and online serving",
      summary: "Give batch jobs and online requests separate latency, freshness, throughput, consistency, retry, backfill, and side-effect contracts around the same versioned model.",
      objective: "Specify and test a batch manifest and online API with schemas, idempotency keys, deduplication, model/version receipts, fallbacks, and outcome reconciliation.",
      artifact: "Versioned batch manifest and online serving contract with duplicate, timeout, partial-failure, backfill, and compatibility tests",
      conceptHeading: "Serving mode changes the failure contract",
      concept: "Batch processing optimizes bounded throughput and replay while online serving optimizes per-request latency and freshness. Both need typed inputs and outputs, model and dependency identity, request/job IDs, authentication, quotas, timeouts, retries, observability, and downstream-effect tracking, but their clocks and recovery mechanisms differ.",
      methodHeading: "Design for ambiguous completion and duplicate delivery",
      method: "Define operation IDs, deduplication horizon, retryable errors, timeout behavior, atomicity boundary, partial-result semantics, backfill selection, version compatibility, and acknowledgement. Inject a response lost after commit and a batch failure after partial output; reconcile from durable receipts rather than guessing whether work happened.",
      boundaryHeading: "Fresh, fast, and served do not mean correct",
      boundary: "Online data can be fresher but wrong; batch replay can duplicate irreversible actions; a server version policy cannot guarantee schema compatibility or rollback safety. Networked execution is not exactly-once by default, and returning 200 does not establish that a user outcome was appropriate.",
      practiceTitle: "Reconcile two ambiguous outcomes",
      practiceBrief: "Serve the fixture through both modes and inject a lost response plus partial batch failure.",
      steps: ["Declare batch and online schemas, version negotiation, identity, authentication, quotas, latency/freshness targets, and downstream side-effect boundary.", "Implement operation IDs and a durable request/job ledger with model, index, configuration, result, and status hashes.", "Inject commit-then-timeout online and partial-write batch failures; retry using the declared idempotency policy.", "Reconcile outcomes, identify any non-reversible effects, and update the rollback/backfill plan."],
      deliverable: "Paired serving contracts, conformance tests, durable operation ledger, and ambiguous-outcome reconciliation report",
      reviewGate: "Retries never silently duplicate declared effects, exact model/config versions are returned, and unknown completion becomes a human-visible reconciliation state.",
      checkpointQuestion: "What is the safest response to a timeout after a request may have committed?",
      checkpointOptions: ["Blindly repeat the request until it succeeds", "Query the durable operation ID and reconcile the authoritative outcome before any retry with side effects", "Assume nothing happened", "Switch model versions and send again"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Ambiguous completion requires an idempotent operation identity and reconciliation; blind retry or assumption can duplicate or lose effects.",
      takeaway: "Serving is not exactly-once: batch and online systems need explicit identity, compatibility, side-effect, retry, and reconciliation contracts.",
    },
    zhHans: {
      title: "Batch 与 online serving",
      summary: "围绕同一个版本化模型，为 batch job 与 online request 分别定义延迟、新鲜度、吞吐、一致性、重试、回填与副作用合同。",
      objective: "定义并测试带 schema、idempotency key、去重、模型/版本收据、fallback 与结果核对的 batch manifest 和 online API。",
      artifact: "包含重复、超时、部分失败、回填与兼容性测试的版本化 batch manifest 与 online serving 合同",
      conceptHeading: "Serving mode 改变故障合同",
      concept: "Batch 处理优化有边界吞吐与重放，online serving 优化逐请求延迟与新鲜度。两者都需要 typed 输入输出、模型和依赖身份、request/job ID、认证、quota、timeout、retry、observability 与下游影响追踪，但时钟与恢复机制不同。",
      methodHeading: "为模糊完成与重复投递而设计",
      method: "定义 operation ID、去重窗口、可重试错误、timeout 行为、原子边界、部分结果语义、回填选择、版本兼容与 acknowledgement。注入 commit 后响应丢失与部分输出后的 batch 失败；从 durable receipt 核对，而不是猜测工作是否发生。",
      boundaryHeading: "新鲜、快速、已服务不等于正确",
      boundary: "Online 数据可能更新但错误；batch 重放可能重复不可逆动作；server version policy 不能保证 schema 兼容或回滚安全。网络执行默认不是 exactly-once，返回 200 也不能证明用户结果适当。",
      practiceTitle: "核对两个模糊结果",
      practiceBrief: "用两种模式服务 fixture，并注入响应丢失和部分 batch 失败。",
      steps: ["声明 batch 与 online schema、版本协商、身份、认证、quota、延迟/新鲜度目标与下游副作用边界。", "实现 operation ID 与 durable request/job ledger，记录模型、索引、配置、结果和状态哈希。", "注入 commit-then-timeout online 故障和 partial-write batch 故障；按已声明幂等政策重试。", "核对结果、识别不可逆影响，并更新回滚/回填计划。"],
      deliverable: "成对 serving 合同、conformance test、durable operation ledger 与模糊结果核对报告",
      reviewGate: "重试不会静默重复已声明影响，返回确切模型/config 版本，未知完成进入人类可见核对状态。",
      checkpointQuestion: "请求可能已 commit 后发生 timeout，最安全的响应是什么？",
      checkpointOptions: ["盲目重复请求直到成功", "用 durable operation ID 查询并核对权威结果，再进行任何有副作用重试", "假设什么都没发生", "切换模型版本后再发送"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "模糊完成需要幂等 operation identity 与核对；盲目重试或假设都可能重复或丢失影响。",
      takeaway: "Serving 不是 exactly-once：batch 与 online 系统都需显式身份、兼容、副作用、重试与核对合同。",
    },
  }),
  productionAiModule({
    slug: "packaging-security-secrets",
    phaseId: "secure-rollout-and-observability",
    minutes: 65,
    sourceIds: ["pa09-oci-image", "pa10-slsa", "pa11-nist-ssdf", "pa12-owasp-secrets"],
    en: {
      title: "Packaging, security and secrets",
      summary: "Bind deployable bytes to a pinned build and provenance record while minimizing privileges and keeping secrets out of images, logs, telemetry, prompts, and model context.",
      objective: "Audit a synthetic OCI package and build attestation, block a planted fake secret, and define rotation, revocation, deployment identity, and least-privilege evidence.",
      artifact: "Image and dependency manifest, build-provenance attestation, secret-scan failure, least-privilege matrix, and rotation/revocation receipt",
      conceptHeading: "Packaging identity and runtime trust are separate controls",
      concept: "Content-addressed image manifests identify layers and configuration; build provenance describes how an artifact was produced; secure-development controls organize risks across preparation, production, protection, and response. Secrets require their own lifecycle from creation and scoped access through rotation, revocation, audit, backup, and recovery.",
      methodHeading: "Verify from source to running identity",
      method: "Pin base image, dependencies, build instructions, builder, source digest, outputs, scanner policy, signature or attestation, deployer identity, network/file permissions, and runtime configuration. Plant a clearly fake secret in a log-producing path, require the gate to fail, purge every derivative copy, rotate it, and prove the old credential cannot authenticate.",
      boundaryHeading: "Containers and attestations are not security proofs",
      boundary: "A container shares a host kernel unless stronger isolation is provided. A valid SLSA attestation can faithfully describe a vulnerable build; a scan can miss a secret or vulnerability; a secret manager cannot recover values already written to logs, traces, prompts, artifacts, caches, backups, or clients.",
      practiceTitle: "Stop a compromised package before release",
      practiceBrief: "Package the fixture service, insert a fake secret, and execute block, purge, rotation, and re-verification paths.",
      steps: ["Create an OCI-style manifest and provenance record binding source, builder, dependencies, commands, outputs, identities, and hashes.", "Declare least-privilege runtime capabilities, network paths, files, secret scopes, expiry, and rotation owner.", "Plant a nonfunctional fake secret, run source/image/log scans, and require a fail-closed release gate.", "Purge derivatives, rotate and revoke the value, verify old access fails, and record residual exposure assumptions."],
      deliverable: "A pinned package dossier, failed secret gate, purge ledger, revoked credential test, and signed residual-risk record",
      reviewGate: "The running digest resolves to reviewed provenance, the planted secret blocks release and is purged from derivatives, and no attestation is described as proof of vulnerability-free software.",
      checkpointQuestion: "What does a valid supply-chain attestation establish?",
      checkpointOptions: ["The application has no vulnerabilities", "The declared provenance statement verifies under its policy; application security and runtime configuration still require separate evidence", "The container is a complete sandbox", "No secret appears in any downstream system"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Provenance evidence can support artifact origin and build claims, but it does not certify the application or runtime as safe.",
      takeaway: "Pinned packaging and provenance improve traceability; they do not replace vulnerability, privilege, secret-lifecycle, runtime, and incident controls.",
    },
    zhHans: {
      title: "打包、供应链安全与 secret",
      summary: "把可部署 bytes 绑定到钉定 build 与 provenance，同时最小化权限并阻止 secret 进入镜像、日志、telemetry、prompt 与模型 context。",
      objective: "审计合成 OCI package 与 build attestation，拦截植入的假 secret，并定义轮换、撤销、部署身份与最小权限证据。",
      artifact: "镜像/依赖 manifest、build-provenance attestation、secret scan 失败、最小权限矩阵与轮换/撤销收据",
      conceptHeading: "打包身份与 runtime 信任是不同控制",
      concept: "内容寻址 image manifest 标识 layer 与配置；build provenance 描述产物如何生成；安全开发控制组织准备、生产、保护与响应风险。Secret 需要自己的生命周期，从创建和范围化访问到轮换、撤销、审计、备份与恢复。",
      methodHeading: "从 source 验证到 running identity",
      method: "钉定 base image、依赖、build instruction、builder、source digest、输出、scanner policy、signature/attestation、deployer identity、网络/文件权限与 runtime 配置。把明显虚构 secret 植入会产生日志的路径，要求门禁失败，清除所有衍生副本，轮换并证明旧 credential 无法认证。",
      boundaryHeading: "Container 与 attestation 不是安全证明",
      boundary: "除非有更强隔离，container 与 host 共享 kernel。有效 SLSA attestation 可能如实描述含漏洞 build；scan 可能漏掉 secret 或漏洞；secret manager 也无法收回已写入日志、trace、prompt、artifact、cache、backup 或 client 的值。",
      practiceTitle: "在 release 前停止受损 package",
      practiceBrief: "打包 fixture 服务，插入假 secret，并执行阻断、清理、轮换与重新验证。",
      steps: ["创建 OCI 风格 manifest 与 provenance，绑定 source、builder、依赖、命令、输出、身份与哈希。", "声明最小权限 runtime capability、网络路径、文件、secret scope、到期与轮换负责人。", "植入无功能假 secret，运行 source/image/log scan，并要求 fail-closed release gate。", "清理衍生物、轮换和撤销，验证旧访问失败并记录剩余暴露假设。"],
      deliverable: "钉定 package 档案、失败 secret gate、清理 ledger、撤销 credential 测试与已签署剩余风险记录",
      reviewGate: "running digest 解析到已审 provenance，植入 secret 阻止 release 并从衍生物清除，且没有把 attestation 描述为无漏洞证明。",
      checkpointQuestion: "有效供应链 attestation 能证明什么？",
      checkpointOptions: ["应用没有漏洞", "声明的 provenance statement 按政策验证通过；应用安全与 runtime 配置仍需独立证据", "container 是完整 sandbox", "任何下游系统都没有 secret"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Provenance 证据可支持产物来源与 build 声明，但不会认证应用或 runtime 安全。",
      takeaway: "钉定打包与 provenance 提升可追溯性；它们不能替代漏洞、权限、secret 生命周期、runtime 与事件控制。",
    },
  }),
  productionAiModule({
    slug: "shadow-canary-feature-flags",
    phaseId: "secure-rollout-and-observability",
    minutes: 70,
    sourceIds: ["pa13-canary-openfeature", "pa01-slos"],
    en: {
      title: "Shadow, canary and feature-flag rollout",
      summary: "Advance through dark, shadow, small canary, larger canary, hold, release, or rollback states using predeclared evidence and an always-available kill switch.",
      objective: "Implement a rollout state machine whose transition checks cover quality, latency, errors, cost, safety, privacy, capacity, sample sufficiency, and human authorization.",
      artifact: "Auditable rollout state machine with flag contract, cohort rules, hold points, kill switch, rollback target, and simulated transition receipts",
      conceptHeading: "Rollout stages expose different evidence without equal user impact",
      concept: "Dark deployment tests packaging without serving decisions. Shadow duplicates selected traffic while keeping the incumbent outcome authoritative. A canary exposes a small real cohort and compares predeclared indicators with a control. Feature flags separate code release from activation and provide scoped, reversible control when their evaluation contract is versioned and observable.",
      methodHeading: "Precommit transitions and stop conditions",
      method: "Define state, allowed predecessor, cohort selection, sample and duration floor, comparison metrics, guardrails, data permission, capacity ceiling, owner, approval, timeout, next state, and rollback action. Simulate dark to shadow to one percent to ten percent, inject a rare harm and a cost spike, and prove that hold and kill-switch paths work without editing code.",
      boundaryHeading: "Limited exposure does not mean limited responsibility",
      boundary: "Shadow traffic may still expose sensitive data and load dependencies; canaries can miss rare or delayed harm and can create unequal treatment. Flags are not access control or governance authorization, stale flags accumulate risk, and rollback cannot erase decisions already shown or data already disclosed.",
      practiceTitle: "Operate a fail-closed rollout",
      practiceBrief: "Use fixture events to exercise success, hold, rollback, and unauthorized-transition paths.",
      steps: ["Specify dark, shadow, canary, hold, release, rollback, and disabled states with allowed transitions and exact evidence.", "Define deterministic cohort assignment, exclusions, minimum duration/sample, guardrails, privacy boundary, owners, and expiry.", "Inject rare harmful output and cost saturation; verify the state holds or rolls back even when average quality improves.", "Attempt an unauthorized flag transition, activate the kill switch, reconcile exposed outcomes, and retire the flag."],
      deliverable: "A versioned rollout state machine, four transition receipts, kill-switch test, and post-rollback reconciliation",
      reviewGate: "Every expansion requires current evidence and named approval, rare critical failure blocks the transition, and rollback includes external-consequence reconciliation.",
      checkpointQuestion: "What must happen when a critical canary guardrail fails despite a better average score?",
      checkpointOptions: ["Expand traffic to collect more users", "Hold or rollback according to the predeclared rule and require named human review before any new exposure", "Delete the failing metric", "Rename the canary cohort"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Critical guardrails are meaningful only when they stop automatic expansion and route the decision to accountable review.",
      takeaway: "Shadow, canary, and flags reduce blast radius but do not confer authorization; critical failures require a real hold or rollback plus human review.",
    },
    zhHans: {
      title: "Shadow、canary 与 feature-flag rollout",
      summary: "依据预先声明证据，在 dark、shadow、小 canary、大 canary、hold、release 或 rollback 状态间推进，并保持 kill switch 始终可用。",
      objective: "实现 rollout state machine，使 transition 检查覆盖质量、延迟、错误、成本、安全、隐私、容量、样本充分性与人类授权。",
      artifact: "含 flag 合同、cohort 规则、hold point、kill switch、rollback target 与模拟 transition 收据的可审计 rollout state machine",
      conceptHeading: "Rollout 阶段以不同用户影响暴露不同证据",
      concept: "Dark deployment 测试打包但不提供决定。Shadow 复制选定流量，同时保留 incumbent 结果为权威。Canary 暴露小型真实 cohort，并按预先声明指标与 control 比较。Feature flag 把代码 release 与 activation 分离；当 evaluation 合同版本化且可观测时，可提供有范围可逆控制。",
      methodHeading: "预先承诺 transition 与停止条件",
      method: "定义 state、允许 predecessor、cohort selection、样本/时长下限、比较指标、guardrail、数据许可、容量上限、负责人、批准、timeout、下一 state 与 rollback action。模拟 dark→shadow→1%→10%，注入稀有伤害与成本尖峰，并证明 hold 与 kill-switch 无需改代码即可工作。",
      boundaryHeading: "有限暴露不等于有限责任",
      boundary: "Shadow 流量仍可能暴露敏感数据并增加依赖负载；canary 会漏掉稀有或延迟伤害，也可能造成不平等待遇。Flag 不是访问控制或治理授权，陈旧 flag 会积累风险，rollback 也不能抹去已展示决定或已披露数据。",
      practiceTitle: "运行 fail-closed rollout",
      practiceBrief: "使用 fixture event 演练成功、hold、rollback 与未授权 transition 路径。",
      steps: ["定义 dark、shadow、canary、hold、release、rollback 与 disabled 状态，以及允许 transition 和确切证据。", "定义确定性 cohort 分配、排除、最小时长/样本、guardrail、隐私边界、负责人和到期。", "注入稀有有害输出与成本饱和；即使平均质量提高，也验证系统 hold 或 rollback。", "尝试未授权 flag transition，启动 kill switch，核对已暴露结果并退役 flag。"],
      deliverable: "一份版本化 rollout state machine、四份 transition 收据、kill-switch 测试与回滚后核对",
      reviewGate: "每次扩大都需要当前证据与具名批准，稀有关键失败会阻断 transition，rollback 还包含外部后果核对。",
      checkpointQuestion: "Canary 的关键 guardrail 失败但平均分更好时，必须怎样做？",
      checkpointOptions: ["扩大流量以收集更多用户", "按预先声明规则 hold 或 rollback，并在任何新暴露前要求具名人工审查", "删除失败指标", "重命名 canary cohort"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "关键 guardrail 只有在能停止自动扩大并把决定交给责任审查时才有意义。",
      takeaway: "Shadow、canary 与 flag 缩小爆炸半径但不授予权限；关键失败需要真实 hold/rollback 与人工审查。",
    },
  }),
  productionAiModule({
    slug: "monitoring-performance-cost",
    phaseId: "secure-rollout-and-observability",
    minutes: 75,
    sourceIds: ["pa14-observability", "pa01-slos"],
    en: {
      title: "Monitoring, performance and cost",
      summary: "Connect traces, metrics, logs, evaluation records, and audit events without confusing operational observability with model or user-outcome evaluation.",
      objective: "Design a dual-system dashboard and trace waterfall covering task success, latency, errors, saturation, model quality, retrieval/generation evidence, resources, and cost per successful task.",
      artifact: "Dual-system telemetry map, trace waterfall, SLI dashboard, alert rationale, redaction test, and cost-per-success reconciliation",
      conceptHeading: "Signals serve different diagnostic and accountability roles",
      concept: "Metrics aggregate measurements over time; traces connect timed operations across a request; logs record selected events; evaluation records bind inputs, outputs, labels, rubrics, and judgments; audit events record decisions and identities. Correlation identifiers and version attributes let an operator move between these surfaces without merging their meanings.",
      methodHeading: "Observe the whole successful-task denominator",
      method: "Instrument queue, preprocessing, feature or retrieval, model, postprocessing, policy, human escalation, and downstream commit spans. Record model/index/prompt/config versions, cache state, retries, errors, token and infrastructure cost, redacted payload class, and outcome. Define alerts from user symptoms and capacity limits, then reconcile request cost against successful tasks rather than traffic alone.",
      boundaryHeading: "Telemetry is neither ground truth nor harmless exhaust",
      boundary: "A trace shows execution, not answer correctness or user benefit; a metric anomaly may reflect instrumentation failure rather than harm; absence of alerts may reflect missing coverage. Logs and spans can leak prompts, documents, secrets, identifiers, or sensitive outcomes, and retention increases that exposure.",
      practiceTitle: "Diagnose a misleading green dashboard",
      practiceBrief: "Trace a slow classifier and a cheap but unsupported RAG answer through the original fixture.",
      steps: ["Map each telemetry and evaluation signal to purpose, schema, owner, version, retention, redaction, and SLO.", "Create correlated spans for both systems with dependency, cache, retry, model/index/prompt, cost, and outcome attributes.", "Inject missing evaluation events and secret-like text; require completeness and redaction checks to fail.", "Compute cost per request and per successful task, diagnose the difference, and document alert and no-alert cases."],
      deliverable: "A telemetry contract, two annotated traces, dashboard, redaction/completeness failures, and cost reconciliation",
      reviewGate: "A reviewer can distinguish execution from evaluation, reproduce every aggregate denominator, and verify that sensitive fixture fields never enter retained telemetry.",
      checkpointQuestion: "What does a complete request trace prove about a generated answer?",
      checkpointOptions: ["The answer is factually correct", "Only the instrumented execution path and recorded attributes; answer quality needs separate evaluation evidence", "The user benefited", "No sensitive content was logged"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Tracing reconstructs execution; correctness, benefit, safety, and redaction require their own tests and evidence.",
      takeaway: "Observability explains instrumented execution; model quality, user outcomes, cost denominators, and sensitive-data controls remain separate evidence contracts.",
    },
    zhHans: {
      title: "性能、可靠性与成本监控",
      summary: "连接 trace、metric、log、评测记录与 audit event，同时不把运行 observability 混同为模型或用户结果评测。",
      objective: "设计覆盖任务成功、延迟、错误、饱和、模型质量、检索/生成证据、资源与每成功任务成本的双系统 dashboard 和 trace waterfall。",
      artifact: "双系统 telemetry map、trace waterfall、SLI dashboard、告警理由、redaction 测试与每成功任务成本核对",
      conceptHeading: "不同 signal 承担不同诊断与问责角色",
      concept: "Metric 随时间聚合测量；trace 连接一个请求中的定时操作；log 记录选定 event；评测记录绑定输入、输出、标签、rubric 与 judgment；audit event 记录决定和身份。Correlation ID 与版本属性让操作者在这些界面间移动，而不合并其含义。",
      methodHeading: "观察完整的成功任务分母",
      method: "为 queue、preprocessing、feature/retrieval、model、postprocessing、policy、人工升级与 downstream commit 建立 span。记录 model/index/prompt/config 版本、cache 状态、retry、error、token/infra 成本、已 redacted payload 类别与结果。按用户症状和容量限制定义告警，再把 request 成本与成功任务而不只是流量核对。",
      boundaryHeading: "Telemetry 既非 ground truth，也非无害废气",
      boundary: "Trace 显示执行，不证明答案正确或用户受益；指标异常可能来自 instrumentation 故障而非伤害；没有告警可能只是 coverage 缺失。Log 和 span 可能泄漏 prompt、document、secret、identifier 或敏感结果，保留期会增加暴露。",
      practiceTitle: "诊断误导性的绿色 dashboard",
      practiceBrief: "用原创 fixture 追踪一个慢分类器与一个便宜但无支持的 RAG 答案。",
      steps: ["把每项 telemetry 与 evaluation signal 映射到目的、schema、负责人、版本、保留、redaction 与 SLO。", "为两个系统创建相关 span，包含依赖、cache、retry、model/index/prompt、成本与结果属性。", "注入缺失 evaluation event 与类似 secret 的文本，要求完整性与 redaction 检查失败。", "计算每 request 与每成功 task 成本，诊断差异并记录告警和不告警案例。"],
      deliverable: "一份 telemetry 合同、两条注释 trace、dashboard、redaction/完整性失败与成本核对",
      reviewGate: "审查者可区分执行与评测，重算每个聚合分母，并验证敏感 fixture 字段从未进入保留 telemetry。",
      checkpointQuestion: "完整 request trace 能证明生成答案的什么？",
      checkpointOptions: ["答案事实正确", "只证明已接入的执行路径与记录属性；答案质量需要独立评测证据", "用户获得收益", "没有敏感内容被记录"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Tracing 重建执行；正确性、收益、安全与 redaction 各自需要测试和证据。",
      takeaway: "Observability 解释已接入执行；模型质量、用户结果、成本分母与敏感数据控制仍是独立证据合同。",
    },
  }),
  productionAiModule({
    slug: "data-concept-drift-continuous-evaluation",
    phaseId: "evaluation-and-response",
    minutes: 75,
    sourceIds: ["pa15-tfdv", "pa14-observability"],
    en: {
      title: "Data drift, concept drift and continuous evaluation",
      summary: "Distinguish schema break, data-quality failure, training-serving skew, distribution shift, label shift, and measured task-performance degradation before choosing an action.",
      objective: "Build a versioned reference/current-window evaluation plan with tests, thresholds, label delay, uncertainty, critical slices, owners, and scenario-specific responses.",
      artifact: "Three-scenario drift dossier with reference/current receipts, detector definitions, delayed-label evaluation, action rules, and false-alarm analysis",
      conceptHeading: "Different change signals answer different questions",
      concept: "Schema validation checks structural expectations; data-quality rules check values and relationships; skew compares environments or stages; distribution detectors compare observed feature or output distributions; concept drift concerns a changed relationship between inputs and target; labeled continuous evaluation measures task outcomes after their labels become available.",
      methodHeading: "Bind each detector to evidence and action",
      method: "Freeze reference and current window definitions, sampling and missingness rules, detector/version, metric, threshold, uncertainty, minimum sample, multiplicity treatment, critical slices, label source and delay. Simulate covariate shift without performance loss, label-prior shift, and genuine performance degradation; require a distinct hold, investigate, recalibrate, retrain, rollback, or no-action rationale.",
      boundaryHeading: "Drift scores do not reveal ground-truth harm",
      boundary: "A distribution test can flag benign seasonality or miss a damaging conditional change; without labels it cannot prove task degradation. Labels can be delayed, selectively observed, corrupted by previous model decisions, or ethically unavailable. Automatic retraining can amplify feedback loops and must never replace authorization and regression gates.",
      practiceTitle: "Decide across three non-equivalent shifts",
      practiceBrief: "Evaluate fixture windows representing benign covariate change, label shift, and true degradation.",
      steps: ["Version reference/current populations, time windows, schemas, sampling, exclusions, label source, delay, and detector implementation.", "Compute data-quality, skew, distribution, and delayed performance evidence with uncertainty and critical slices.", "Apply predeclared action rules to all three scenarios and document why one detector cannot decide them all.", "Test a false alert and a missed harm, then route retraining or rollback through named approval and regression gates."],
      deliverable: "A versioned three-scenario evaluation dossier, decision table, false-alarm/miss report, and approved action record",
      reviewGate: "Every detector has a bounded interpretation, no unlabeled drift score is called task degradation, and retraining cannot begin without declared evidence and human approval.",
      checkpointQuestion: "What may an unlabeled feature-distribution alert establish?",
      checkpointOptions: ["The model's task performance definitely declined", "A measured distribution difference under the declared detector; performance impact needs labels or other outcome evidence", "The causal mechanism of change", "Automatic retraining is safe"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Distribution shift is evidence of difference, not by itself evidence of concept change, outcome degradation, cause, or safe remediation.",
      takeaway: "A drift alert is a bounded difference signal; only appropriate outcome evidence and accountable review can justify retraining, rollback, or continued operation.",
    },
    zhHans: {
      title: "数据漂移、概念漂移与持续评测",
      summary: "在选择行动前，区分 schema break、数据质量失败、training-serving skew、分布变化、label shift 与已测任务性能退化。",
      objective: "建立版本化 reference/current-window 评测计划，包含测试、阈值、标签延迟、不确定性、关键切片、负责人与情境特定响应。",
      artifact: "包含 reference/current 收据、detector 定义、延迟标签评测、行动规则与误报分析的三情境 drift 档案",
      conceptHeading: "不同变化 signal 回答不同问题",
      concept: "Schema validation 检查结构预期；数据质量规则检查值与关系；skew 比较环境或阶段；分布 detector 比较观测 feature 或输出分布；concept drift 指输入与目标关系改变；带标签持续评测在标签可用后测量任务结果。",
      methodHeading: "把每个 detector 绑定到证据与行动",
      method: "冻结 reference/current 窗口定义、抽样和缺失规则、detector/version、metric、threshold、不确定性、最小样本、多重比较处理、关键切片、标签来源与延迟。模拟无性能损失的 covariate shift、label-prior shift 与真实性能下降；分别要求 hold、investigate、recalibrate、retrain、rollback 或 no-action 理由。",
      boundaryHeading: "Drift 分数不会揭示 ground-truth harm",
      boundary: "分布测试可能标记良性季节性或漏掉有害条件变化；没有标签时不能证明任务退化。标签可能延迟、选择性可见、被先前模型决定污染，或因伦理原因不可取得。自动 retraining 可能放大 feedback loop，绝不能替代授权与 regression gate。",
      practiceTitle: "在三个不等价 shift 中决策",
      practiceBrief: "评估代表良性 covariate change、label shift 与真实 degradation 的 fixture window。",
      steps: ["版本化 reference/current 群体、时间窗口、schema、抽样、排除、标签来源、延迟与 detector 实现。", "计算数据质量、skew、分布与延迟性能证据，并报告不确定性与关键切片。", "把预先声明行动规则应用到三种情境，并说明为何一个 detector 不能决定全部。", "测试误报与漏报，再使 retraining/rollback 经过具名批准和 regression gate。"],
      deliverable: "一份版本化三情境评测档案、决定表、误报/漏报报告与获批准行动记录",
      reviewGate: "每个 detector 都有有边界解释，没有把无标签 drift 分数称为任务退化，且未经已声明证据与人工批准不能开始 retraining。",
      checkpointQuestion: "无标签 feature 分布告警可以证明什么？",
      checkpointOptions: ["模型任务性能肯定下降", "在已声明 detector 下测得分布差异；性能影响需要标签或其他结果证据", "变化的因果机制", "自动 retraining 是安全的"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "分布变化是差异证据，本身不是概念变化、结果退化、成因或安全修复的证据。",
      takeaway: "Drift alert 是有边界差异 signal；只有适当结果证据与责任审查才能支持 retraining、rollback 或继续运行。",
    },
  }),
  productionAiModule({
    slug: "incident-response-rollback-postmortem",
    phaseId: "evaluation-and-response",
    minutes: 80,
    sourceIds: ["pa16-incident-postmortem", "pa17-nist-incident", "pa13-canary-openfeature"],
    en: {
      title: "Incident response, rollback and postmortem",
      summary: "Coordinate severity, command, evidence, communication, containment, rollback or degradation, recovery validation, consequence repair, and learning for AI-specific incidents.",
      objective: "Run a tabletop covering a wrong model alias and contaminated retrieval index, including ambiguous actions, human authority, notification, reprocessing, and rollback limitations.",
      artifact: "Timestamped incident timeline, evidence-preservation log, alert runbook, rollback/degrade receipt, outcome reconciliation, and blameless postmortem",
      conceptHeading: "Incident response manages service and consequences",
      concept: "A response needs declared severity, incident commander, operations and communications roles, secure evidence, containment, decision logs, rollback or degradation targets, recovery criteria, stakeholder channels, legal and sector escalation, and follow-up owners. Postmortems examine contributing system conditions and control improvements rather than assigning simplistic individual blame.",
      methodHeading: "Reconcile what rollback cannot reverse",
      method: "Start from an alert, establish a shared timestamped record, preserve model/index/config/request evidence, classify affected outcomes, disable or degrade safely, verify running digests and dependencies, and re-evaluate service. Separately identify decisions already delivered, data disclosed, queued messages, cached answers, financial or educational effects, notices, corrections, and reprocessing obligations.",
      boundaryHeading: "Restored service is not repaired harm",
      boundary: "Rollback may fail because a target is incompatible, unavailable, vulnerable, or dependent on contaminated state. It cannot recall an exposed secret, retract every user decision, remove every cached response, or satisfy all notification law. NIST and Google guidance provide frameworks, not jurisdiction-specific legal conclusions.",
      practiceTitle: "Tabletop two coupled AI incidents",
      practiceBrief: "Respond to a wrong classifier alias and a poisoned retrieval index, including one ambiguous rollback command.",
      steps: ["Declare severity, commander, roles, channels, evidence rules, authority, safety constraints, and regulatory/legal escalation trigger.", "Preserve exact model, index, prompt, config, lineage, telemetry, decision, and affected-outcome evidence before changing state.", "Execute degrade and rollback paths, reconcile an ambiguous command using operation identity, and verify service plus model quality.", "Account for external consequences, write a blameless postmortem, assign corrective controls, owners, dates, and effectiveness tests."],
      deliverable: "A complete incident packet with timeline, preserved evidence, rollback verification, consequence ledger, notices, and owned postmortem actions",
      reviewGate: "Rollback identity is independently verified, unknown completion is reconciled, restored service is separated from repaired outcomes, and a named human closes or extends the incident.",
      checkpointQuestion: "What must happen after a technically successful rollback?",
      checkpointOptions: ["Close the incident automatically", "Verify service and model behavior, then reconcile prior decisions, disclosures, queues, caches, notices, and other external consequences under human authority", "Delete the old logs", "Assume every affected user outcome was undone"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Rollback changes current technical state; it does not automatically undo past external effects or establish recovery and repair.",
      takeaway: "Rollback changes running state, not history; recovery requires verified service plus human-owned reconciliation and repair of external consequences.",
    },
    zhHans: {
      title: "事件响应、回滚与复盘",
      summary: "针对 AI 特定事件协调严重度、指挥、证据、沟通、遏制、回滚/降级、恢复验证、后果修复与学习。",
      objective: "演练错误模型 alias 与受污染检索 index，覆盖模糊操作、人类决定权、通知、重处理与 rollback 限制。",
      artifact: "带时间戳事件 timeline、证据保全 log、alert runbook、rollback/degrade 收据、结果核对与无责 postmortem",
      conceptHeading: "事件响应同时管理服务与后果",
      concept: "响应需要已声明严重度、incident commander、运行/沟通角色、安全证据、遏制、决定日志、rollback/degradation target、恢复标准、stakeholder channel、法律与行业升级及后续负责人。Postmortem 检查促成事件的系统条件与控制改进，而不是简单归咎个人。",
      methodHeading: "核对 rollback 无法逆转的事项",
      method: "从告警开始，建立共享带时间戳记录，保全 model/index/config/request 证据，分类受影响结果，安全禁用或降级，验证 running digest 与依赖并重新评估服务。另行识别已送达决定、已披露数据、queued message、cached answer、财务或教育影响、通知、更正与重处理义务。",
      boundaryHeading: "服务恢复不等于伤害修复",
      boundary: "Rollback 可能因 target 不兼容、不可用、有漏洞或依赖受污染状态而失败。它无法收回已暴露 secret、撤销每项用户决定、移除每个缓存响应或满足所有通知法律。NIST 与 Google 指导提供框架，不是特定法域法律结论。",
      practiceTitle: "桌面演练两个耦合 AI 事件",
      practiceBrief: "响应错误分类器 alias 与受污染 retrieval index，包括一次模糊 rollback command。",
      steps: ["声明严重度、指挥、角色、channel、证据规则、权限、安全约束与法规/法律升级触发。", "改变状态前保全确切 model、index、prompt、config、lineage、telemetry、decision 与受影响结果证据。", "执行 degrade 与 rollback，用 operation identity 核对模糊命令，并验证服务与模型质量。", "核算外部后果，撰写无责 postmortem，指定纠正控制、负责人、日期与 effectiveness test。"],
      deliverable: "包含 timeline、证据保全、回滚验证、后果 ledger、通知与有负责人复盘行动的完整事件包",
      reviewGate: "独立验证 rollback identity，核对未知完成，把服务恢复与结果修复分开，并由具名人类关闭或延长事件。",
      checkpointQuestion: "技术上成功回滚后必须做什么？",
      checkpointOptions: ["自动关闭事件", "验证服务和模型行为，再在人类决定权下核对先前决定、披露、队列、缓存、通知与其他外部后果", "删除旧日志", "假设所有受影响用户结果都已撤销"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "Rollback 改变当前技术状态，不会自动撤销过去外部影响，也不会证明恢复与修复完成。",
      takeaway: "Rollback 改变运行状态而非历史；恢复需要验证服务，并由人类负责核对和修复外部后果。",
    },
  }),
  productionAiModule({
    slug: "dual-system-production-capstone",
    phaseId: "evaluation-and-response",
    minutes: 120,
    sourceIds: ["pa01-slos", "pa03-mlmd", "pa05-mlflow-tracking", "pa06-mlflow-registry", "pa07-kserve", "pa10-slsa", "pa13-canary-openfeature", "pa14-observability", "pa15-tfdv", "pa16-incident-postmortem", "pa17-nist-incident", "ra12-model-cards"],
    en: {
      title: "Dual-system production capstone",
      summary: "Operate one conventional prediction service and one retrieval-generation service through shared identity, lineage, evidence, release, observability, evaluation, rollback, incident, and human-approval controls.",
      objective: "Assemble and exercise the complete ten-artifact production dossier, including a shadow-to-canary release, critical failure, rollback, consequence reconciliation, and signed go/no-go decision.",
      artifact: "Ten-artifact dual-system production dossier with architecture, evidence graph, rollout and incident execution, and scoped human authorization",
      conceptHeading: "Shared controls do not erase system-specific quality evidence",
      concept: "Both systems need reproducible artifacts, service identity, data rights, SLOs, least privilege, observability, approval, rollback, and incident response. The classifier needs label- and slice-based predictive evaluation; the retrieval-generation service needs corpus/index/prompt identity, retrieval evidence, citation support, output safety, and human-use boundaries. One average cannot represent both.",
      methodHeading: "Exercise the dossier as an operating system",
      method: "Verify original fixture and schema hashes, instantiate the lineage and experiment records, register exact artifacts, package with provenance, configure serving and telemetry, precommit SLO and continuous-evaluation gates, run shadow and canary, inject an unsupported generated answer plus a wrong classifier alias, roll back, reconcile outcomes, and convene independent review.",
      boundaryHeading: "A local capstone PASS is not a production deployment",
      boundary: "Citation presence does not prove answer correctness; registry labels and dashboards do not authorize use; rollback does not erase prior outcomes; synthetic tests do not establish performance, fairness, safety, data rights, compliance, or reliability for real people. No capstone milestone may auto-issue deployment authority.",
      practiceTitle: "Defend a human go/no-go decision",
      practiceBrief: "Use only the original fictional fixture to run the complete release and incident sequence for both services.",
      steps: ["Verify fixture, schema, environment, source, build, model/index/prompt/config, evaluation, registry, and rollback-target identity.", "Complete all ten artifacts and trace each service/card/SLO claim to exact evidence, owner, version, expiry, and boundary.", "Run shadow and canary, inject both failures, activate hold/rollback, verify current state, and reconcile every prior outcome and disclosure.", "Ask independent reviewers to challenge reproducibility, security, drift, rollback, rights, and human authority; record scoped go, revise, no-go, or no-deploy."],
      deliverable: "A reviewer-signed ten-artifact dossier, replayable release/incident trace, consequence ledger, and explicit scoped go/no-go record",
      reviewGate: "All artifact hashes and evidence links resolve, both systems retain distinct quality gates, the injected critical failures block automatic release, rollback consequences are reconciled, and only named humans decide next use.",
      checkpointQuestion: "What can successful completion of the dual-system capstone authorize?",
      checkpointOptions: ["Automatic deployment with real user data", "Only completion of the bounded educational exercise; any real deployment requires new contextual evidence, rights review, security review, and named human authority", "A claim of universal reliability", "Skipping incident and rollback tests"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "The synthetic local exercise demonstrates course artifacts and controls under fixed conditions; it cannot authorize a materially different real deployment.",
      takeaway: "A model running is not a responsibly operated service; production authority remains scoped, evidence-dependent, revocable, and human-held.",
    },
    zhHans: {
      title: "双系统生产毕业项目",
      summary: "让一个传统预测服务与一个检索生成服务在共享身份、lineage、证据、release、observability、评测、rollback、incident 与人类批准控制下运行。",
      objective: "组装并演练完整十产物生产档案，包括 shadow-to-canary release、关键失败、rollback、后果核对与签署 go/no-go 决定。",
      artifact: "包含架构、证据图、rollout/incident 执行与有范围人类授权的十产物双系统生产档案",
      conceptHeading: "共享控制不会抹去系统特定质量证据",
      concept: "两个系统都需要可复现产物、服务身份、数据权利、SLO、最小权限、observability、批准、rollback 与事件响应。分类器需要基于标签与切片的预测评测；检索生成服务需要 corpus/index/prompt 身份、检索证据、引文支持、输出安全与人类使用边界。一个平均值无法代表两者。",
      methodHeading: "把档案作为运行系统演练",
      method: "验证原创 fixture 与 schema 哈希，建立 lineage 和实验记录，登记确切产物，以 provenance 打包，配置 serving/telemetry，预先承诺 SLO 与持续评测门禁，运行 shadow/canary，注入无支持生成答案与错误分类器 alias，回滚、核对结果并召开独立审查。",
      boundaryHeading: "本地 capstone PASS 不是生产部署",
      boundary: "有引文不证明答案正确；registry label 与 dashboard 不授权使用；rollback 不抹去先前结果；合成测试不证明对真实人的性能、公平、安全、数据权利、合规或可靠性。任何 capstone 里程碑都不能自动发放部署权限。",
      practiceTitle: "为人类 go/no-go 决定辩护",
      practiceBrief: "只使用原创虚构 fixture，为两个服务运行完整 release 与 incident 序列。",
      steps: ["验证 fixture、schema、环境、source、build、model/index/prompt/config、evaluation、registry 与 rollback-target 身份。", "完成十项产物，并把每项 service/card/SLO 声明追溯到确切证据、负责人、版本、到期与边界。", "运行 shadow 与 canary，注入两个故障，启动 hold/rollback，验证当前状态并核对每项先前结果与披露。", "请独立审查者挑战复现、安全、drift、rollback、权利与人类决定权；记录有范围 go、revise、no-go 或 no-deploy。"],
      deliverable: "经审查者签署的十产物档案、可重放 release/incident trace、后果 ledger 与显式有范围 go/no-go 记录",
      reviewGate: "所有 artifact 哈希和证据链接可解析，两系统保留不同质量门禁，注入关键失败阻止自动 release，rollback 后果已核对，且只有具名人类决定下一用途。",
      checkpointQuestion: "成功完成双系统毕业项目可以授权什么？",
      checkpointOptions: ["自动使用真实用户数据部署", "只代表完成有边界教学练习；任何现实部署都需要新的情境证据、权利审查、安全审查与具名人类权限", "声明普遍可靠", "跳过 incident 与 rollback 测试"],
      checkpointCorrectIndex: 1,
      checkpointExplanation: "合成本地练习只展示固定条件下的课程产物与控制，不能授权实质不同的现实部署。",
      takeaway: "模型能运行不等于服务被负责任运营；生产权限始终有范围、依赖证据、可撤销并由人类持有。",
    },
  }),
] as const;

export type ProductionAiModuleSlug =
  (typeof PRODUCTION_AI_MODULES)[number]["slug"];
