import {
  AGENTIC_TEACHING_COURSE_ID,
  AGENTIC_TEACHING_DISPLAY_NUMBER,
  AGENTIC_TEACHING_LOCALES,
  AGENTIC_TEACHING_PUBLISHED_ON,
  AGENTIC_TEACHING_REVIEWED_LOCALES,
  AGENTIC_TEACHING_VERSION,
  type AgenticTeachingCourseManifest,
} from "./types";

export const AGENTIC_TEACHING_COURSE_MANIFEST = {
  id: AGENTIC_TEACHING_COURSE_ID,
  version: AGENTIC_TEACHING_VERSION,
  displayNumber: AGENTIC_TEACHING_DISPLAY_NUMBER,
  publishedOn: AGENTIC_TEACHING_PUBLISHED_ON,
  locales: AGENTIC_TEACHING_LOCALES,
  reviewedLocales: AGENTIC_TEACHING_REVIEWED_LOCALES,
  phases: [
    {
      id: "frame",
      order: 1,
      moduleSlugs: [
        "agentic-teaching-boundaries",
        "learning-design-task-contracts",
      ],
    },
    {
      id: "design",
      order: 2,
      moduleSlugs: [
        "teacher-copilot-workflows",
        "tutoring-feedback-agents",
        "multi-agent-inquiry",
        "knowledge-tools-mcp",
      ],
    },
    {
      id: "govern",
      order: 3,
      moduleSlugs: ["k12-safeguards", "higher-ed-integrity"],
    },
    {
      id: "prove",
      order: 4,
      moduleSlugs: ["evals-learning-evidence", "pilot-capstone"],
    },
  ],
  modules: [
    {
      slug: "agentic-teaching-boundaries",
      order: 1,
      phaseId: "frame",
      minutes: 55,
      sourceIds: ["S01", "S09", "S13"],
      audiences: ["k12", "higher-ed"],
      scenarios: {
        k12: "Turn a teacher-selected practice routine into a low-authority coaching loop.",
        "higher-ed": "Triage office-hour questions without making academic decisions.",
      },
      humanApprovalPoints: ["educator-approves-purpose", "educator-sets-stop-condition"],
      noGoActions: ["autonomous-teaching-replacement", "unreviewed-high-impact-output"],
    },
    {
      slug: "learning-design-task-contracts",
      order: 2,
      phaseId: "frame",
      minutes: 60,
      sourceIds: ["S01", "S15", "S16"],
      audiences: ["k12", "higher-ed"],
      scenarios: {
        k12: "Write an age-appropriate contract for a teacher-owned lesson objective.",
        "higher-ed": "Write a contract for a course assistant that respects the syllabus and assessment policy.",
      },
      humanApprovalPoints: ["educator-signs-task-contract", "data-owner-approves-inputs"],
      noGoActions: ["undefined-authority", "silent-policy-change"],
    },
    {
      slug: "teacher-copilot-workflows",
      order: 3,
      phaseId: "design",
      minutes: 65,
      sourceIds: ["S06", "S07", "S15"],
      audiences: ["k12", "higher-ed"],
      scenarios: {
        k12: "Draft a 45-minute lesson pack from approved curriculum resources for teacher revision.",
        "higher-ed": "Prepare an evidence-linked seminar plan and accessibility pass for faculty approval.",
      },
      humanApprovalPoints: ["teacher-verifies-curriculum-fit", "teacher-publishes-materials"],
      noGoActions: ["invented-standard-alignment", "automatic-student-release"],
    },
    {
      slug: "tutoring-feedback-agents",
      order: 4,
      phaseId: "design",
      minutes: 75,
      sourceIds: ["S07", "S09", "S10", "S11", "S16"],
      audiences: ["k12", "higher-ed"],
      scenarios: {
        k12: "Offer a diagnostic and three-level hint ladder after the learner attempts a problem.",
        "higher-ed": "Draft editable feedback only after a TA has completed the academic judgement.",
      },
      humanApprovalPoints: ["educator-verifies-hint-strategy", "educator-signs-feedback-release"],
      noGoActions: ["answer-first-tutoring", "autonomous-final-grade"],
    },
    {
      slug: "multi-agent-inquiry",
      order: 5,
      phaseId: "design",
      minutes: 70,
      sourceIds: ["S05", "S08", "S12", "S14"],
      audiences: ["k12", "higher-ed"],
      scenarios: {
        k12: "Compare one-agent and specialist review of a teacher-owned inquiry pack.",
        "higher-ed": "Run parallel source, pedagogy or method, accessibility and safety reviews with an explicit join contract.",
      },
      humanApprovalPoints: ["educator-approves-role-boundaries", "educator-resolves-agent-conflict"],
      noGoActions: ["agent-majority-as-truth", "complexity-without-baseline"],
    },
    {
      slug: "knowledge-tools-mcp",
      order: 6,
      phaseId: "design",
      minutes: 65,
      sourceIds: ["S02", "S06"],
      audiences: ["k12", "higher-ed"],
      scenarios: {
        k12: "Expose a small, approved, read-only curriculum collection with provenance.",
        "higher-ed": "Connect a versioned course-resource index without exposing the whole drive or LMS.",
      },
      humanApprovalPoints: ["owner-approves-resource-scope", "operator-approves-each-write-tool"],
      noGoActions: ["unreviewed-public-server", "broad-drive-or-lms-access"],
    },
    {
      slug: "k12-safeguards",
      order: 7,
      phaseId: "govern",
      minutes: 70,
      sourceIds: ["S03", "S04", "S09", "S15", "S16"],
      audiences: ["k12", "higher-ed"],
      scenarios: {
        k12: "Complete a child-rights and data-flow review before any learner-facing pilot.",
        "higher-ed": "Apply the same safeguards to minors, dual-enrolment students and sensitive support contexts.",
      },
      humanApprovalPoints: ["institution-approves-data-path", "adult-handles-escalation"],
      noGoActions: ["identifiable-data-in-personal-account", "companion-dependency-design", "automated-crisis-response"],
    },
    {
      slug: "higher-ed-integrity",
      order: 8,
      phaseId: "govern",
      minutes: 65,
      sourceIds: ["S10", "S11", "S15", "S16"],
      audiences: ["k12", "higher-ed"],
      scenarios: {
        k12: "Translate authorship and disclosure rules into age-appropriate classroom routines.",
        "higher-ed": "Align an agent workflow with syllabus policy, appeals, accessibility and research ethics.",
      },
      humanApprovalPoints: ["instructor-decides-academic-judgement", "learner-can-appeal-or-opt-out"],
      noGoActions: ["automated-misconduct-finding", "hidden-ai-authorship", "unreviewed-research-advice"],
    },
    {
      slug: "evals-learning-evidence",
      order: 9,
      phaseId: "prove",
      minutes: 80,
      sourceIds: ["S01", "S05", "S07", "S09", "S10", "S11"],
      audiences: ["k12", "higher-ed"],
      scenarios: {
        k12: "Measure an age-appropriate no-AI transfer task, safety failures and teacher takeovers.",
        "higher-ed": "Separate trace quality, output quality, learning transfer and operational cost in an evaluation set.",
      },
      humanApprovalPoints: ["educator-validates-rubric", "review-board-reads-failure-samples"],
      noGoActions: ["trace-equals-evaluation", "assisted-completion-equals-learning"],
    },
    {
      slug: "pilot-capstone",
      order: 10,
      phaseId: "prove",
      minutes: 115,
      sourceIds: ["S01", "S02", "S03", "S04", "S05", "S06", "S07", "S08", "S09", "S10", "S11", "S15", "S16"],
      audiences: ["k12", "higher-ed"],
      scenarios: {
        k12: "Move from shadow mode to a small teacher-supervised cohort only after child and data gates pass.",
        "higher-ed": "Run a reversible course pilot with opt-out, appeal, audit and a no-AI comparison task.",
      },
      humanApprovalPoints: ["named-owner-makes-release-decision", "named-owner-can-stop-pilot"],
      noGoActions: ["whole-school-big-bang", "release-without-exit-criteria", "capstone-as-professional-certification"],
    },
  ],
} as const satisfies AgenticTeachingCourseManifest;

export const AGENTIC_TEACHING_TOTAL_MINUTES =
  AGENTIC_TEACHING_COURSE_MANIFEST.modules.reduce(
    (total, module) => total + module.minutes,
    0,
  );
