import { RESPONSIBLE_AI_CROSS_COURSE_RUBRIC_ZH_HANS } from "../../course-kit/responsible-ai-rubric";

export const AI_RESEARCH_ZH_HANS_COURSE_COPY = {
  meta: {
    title: "证据扎根的 AI 研究",
    kicker: "课程 17 · 让每项主张都可追溯",
    summary: "把 AI 当作有边界的研究助手，同时保留协议、检索、筛选、抽取、分析、引文、披露与复现证据。RAG 片段和模型摘要只用于定位，不是最终证据。",
    audience: "需要让 AI 辅助研究保持可检查、可复核与可复现的学生、研究者、评审者、分析师、馆员和研究软件建设者。",
    prerequisite: "具备基础检索与引文素养；技术工作室建议先修课程 18，涉及检索辅助核验时也建议先修 RAG。",
    level: "初级到中级",
    duration: "10 个模块 · 10 小时 50 分钟",
    startCta: "先写研究协议",
    resumeCta: "继续证据台账",
    fallbackNotice: "本课程提供经过审核的简体中文正文；其他尚未审核的语言会明确回退到英文。",
    evidenceNote: "方法以报告标准、官方手册、研究基础设施文档和原始方法研究为依据。课程绝不把搜索摘要、RAG 片段或生成的引文当作来源证据。",
  },
  principles: [
    "在查看吸引人的结果前，先冻结研究问题、资格逻辑与分析意图。",
    "保存足够的检索与筛选证据，使另一位研究者能重建每项纳入决定。",
    "把每项实质主张返回到原始 PDF 页、表格、数据集、代码或其他一手记录。",
    "分开抽取、计算、解释与综合，避免错误在层与层之间静默传播。",
    "披露 AI 帮助了什么、无法验证什么、哪里失败以及人类核验了什么。",
  ],
  outcomes: [
    "为有界综述问题编写协议与可预注册的决策日志。",
    "运行并记录透明检索，保存数据库、查询、日期、限制与导出收据。",
    "用明确纳入/排除理由筛选记录，并保留分歧解决过程。",
    "维护区分证据质量、直接性和报告缺口的主张—来源台账。",
    "以页码和单元格级 provenance 抽取 PDF 文字、表格、数字与方法。",
    "用 RAG 定位候选段落，再到一手来源核验引文。",
    "遵守定量与定性推断边界，并保留不确定性。",
    "交付包含复现包、引文审计、AI 披露与失败日志的可审查小型综述。",
  ],
  quiz: {
    title: "证据扎根研究终测",
    intro: "系统从 30 道双语题中确定性抽取 12 题。至少答对 10 题，并答对所有被抽中的 provenance、一手来源与禁止编造关键题。",
  },
  capstone: {
    title: "可审查小型综述毕业项目",
    intro: "完成一项小型综述，使提交包能够重建全部决定与主张。只有流畅叙述而没有台账和来源收据，仍然不完整。",
    instructions: [
      "使用范围狭窄的问题和数量可控、取得方式合法的来源集。",
      "在协议、检索、筛选、抽取、主张、分析与引文中持续使用稳定 ID。",
      "逐项回到原始来源核验最终主张；无法访问或未报告的内容必须记为缺口，不得猜测。",
    ],
    responsibleAiRubric: RESPONSIBLE_AI_CROSS_COURSE_RUBRIC_ZH_HANS,
    attestation: "我已针对一手记录核验最终主张，报告未解决证据缺口，并且没有把生成文本、搜索摘要或 RAG 片段表述为来源证据。",
  },
} as const;

export const AI_RESEARCH_ZH_HANS_MODULES = {
  "question-protocol-preregistration": {
    title: "研究问题、协议与预注册",
    summary: "把研究兴趣转成范围和决定经得住后续证据检验的问题。",
    objective: "编写包含问题结构、资格条件、结果、来源、筛选、抽取、综合、偏离与停止规则的协议。",
    artifact: "协议与决策日志",
    sections: [
      { heading: "让问题可操作", paragraphs: ["界定人群或语料、暴露或现象、必要时的比较、结果、情境、日期、语言、出版类型和分析单位。现在的模糊会在稍后变成任意选择。"], sourceIds: ["prisma-2020"], evidenceMode: "source-grounded" },
      { heading: "预先承诺关键决定", paragraphs: ["在看到答案前，写明资格、检索源、去重、筛选角色、抽取字段、偏倚风险方法、分析计划和停止规则。预注册不禁止改变；它让改变的时间和理由可见。"], sourceIds: ["osf-preregistration"], evidenceMode: "source-grounded" },
      { heading: "记录偏离", paragraphs: ["现实需要修改时，保存旧规则、新规则、日期、理由、受影响记录和对解释的影响。不要事后重写协议，让它看起来像早已预见结果。"], sourceIds: ["prisma-2020"], evidenceMode: "instructional-synthesis" },
    ],
    practice: { title: "冻结首版协议", brief: "写下会改变哪些证据进入综述的问题与决定。", steps: ["打开原创虚构语料 /courses/ai-research/mini-review-corpus-synthetic-v1.json，并先阅读同目录 NOTICE，再把任何记录当作练习证据。", "把问题、资格、流程、分析和停止规则操作化。", "在筛选前建立编号偏离日志。"], deliverable: "版本化协议与空白偏离日志。", reviewGate: "另一位评审者无需追问含义即可应用标准。" },
    checkpoint: { question: "证据综述中预注册的核心作用是什么？", options: ["显示哪些关键决定在结果出现前作出，并记录后续偏离", "禁止所有合理协议修改", "保证结论无偏", "取代最终方法部分"], correctIndex: 0, explanation: "预注册为意图加时间戳并让偏离可检查，但不会消除判断或保证效度。" },
    takeaway: "协议是你与未来那个已经看过结果的自己之间的合同。",
  },
  "transparent-search-search-log": {
    title: "透明检索策略与检索日志",
    summary: "把发现过程转成可复现的数据库、查询、日期、限制与导出序列。",
    objective: "设计概念块，在不同检索系统中准确转换，并保存完整检索收据。",
    artifact: "检索策略与检索日志",
    sections: [
      { heading: "先设计概念，再写语法", paragraphs: ["把问题拆为概念、同义词、受控词、变体和已知哨兵记录。有意识地平衡召回率与精确率，再把同一概念策略翻译为各数据库语法。"], sourceIds: ["cochrane-search"], evidenceMode: "source-grounded" },
      { heading: "记录真正运行的查询", paragraphs: ["保存平台和数据库、完整查询、字段、过滤器、日期时间、结果数、导出格式与文件哈希。‘我们检索了文献’这类叙述无法重跑。"], sourceIds: ["prisma-search"], evidenceMode: "source-grounded" },
      { heading: "把 AI 建议当候选", paragraphs: ["模型可以建议同义词或查询变体，但每个词都要用学科、数据库词表和返回记录核验。生成的书目在逐条解析为真实来源前不得引用。"], sourceIds: ["prisma-search"], evidenceMode: "instructional-synthesis" },
    ],
    practice: { title: "建立双数据库检索", brief: "把一个概念策略翻译到两个检索系统并保存两份收据。", steps: ["建立概念与同义词块。", "运行、检查哨兵记录，并透明修订。", "保存完整查询、日期、数量、导出与哈希。"], deliverable: "带可复现查询字符串和导出收据的检索日志。", reviewGate: "另一位研究者无需解释截图即可重跑检索。" },
    checkpoint: { question: "哪类记录能使检索可复现？", options: ["数据库、平台、完整查询、字段、过滤器、运行日期、结果数和导出收据", "筛选后回忆出的关键词", "结果第一页截图", "模型对检索的摘要"], correctIndex: 0, explanation: "复现需要真正执行的语法与上下文，不是事后描述。" },
    takeaway: "无法重跑准确检索，就无法审计证据基础。",
  },
  "screening-inclusion-exclusion": {
    title: "筛选、纳入与排除",
    summary: "从去重到全文排除，让每条记录的决定都可追溯。",
    objective: "运行包含稳定 ID、独立判断、理由、分歧和流程数量的筛选台账。",
    artifact: "纳入与排除台账",
    sections: [
      { heading: "保留记录身份", paragraphs: ["去重前先分配稳定 ID，保存来源数据库、导入标识、重复簇和保留记录。静默删除会让流程数量和后续修正无法重建。"], sourceIds: ["prisma-2020"], evidenceMode: "source-grounded" },
      { heading: "在正确阶段应用标准", paragraphs: ["标题摘要阶段只有在信息充分时才排除；全文排除必须给出一项具体且符合协议的理由。‘不相关’会隐藏决定规则。"], sourceIds: ["cochrane-selection"], evidenceMode: "source-grounded" },
      { heading: "让分歧保持可见", paragraphs: ["若设计有多位筛选者，应保存独立决定、冲突状态、讨论结果和裁决人。一致性统计不能代替对系统性误解的检查。"], sourceIds: ["cochrane-selection"], evidenceMode: "instructional-synthesis" },
    ],
    practice: { title: "筛选校准集", brief: "在扩大筛选前，先对一小组共享记录应用协议。", steps: ["保留 lineage 地去重。", "记录独立决定与具体理由。", "解决冲突，并通过有日志的协议修订澄清歧义。"], deliverable: "筛选台账与流程数量核对。", reviewGate: "每项全文排除有一个可审查理由，所有数量能够核对。" },
    checkpoint: { question: "哪一项是合格的全文排除理由？", options: ["具体协议标准，例如人群不符或没有合格结果", "不相关", "摘要很难读", "AI 筛选器分数较低"], correctIndex: 0, explanation: "具体且符合协议的理由支持审计、计数和一致应用。" },
    takeaway: "筛选质量存在于逐记录理由中，而不只在最终纳入数量中。",
  },
  "evidence-hierarchy-claim-source-ledger": {
    title: "证据层级与主张—来源台账",
    summary: "为每项主张匹配设计、直接性与报告质量合适的证据。",
    objective: "建立分开记录来源存在、研究设计、偏倚风险、直接性、结果与主张强度的台账。",
    artifact: "主张—证据矩阵",
    sections: [
      { heading: "先问设计能证明什么", paragraphs: ["证据层级取决于问题。随机研究、观察研究、定性叙述、技术评测、标准和案例报告回答不同问题。不要把关联写成因果，也不要把设计建议写成观测效果。"], sourceIds: ["grade-book-current"], evidenceMode: "source-grounded" },
      { heading: "单独记录报告缺口", paragraphs: ["来源可能真实存在，却没有报告抽样、子群、方差、实施、代码或局限。应标‘未报告’，而不是推断有利取值；缺少证据不同于没有效应的证据。"], sourceIds: ["cochrane-bias"], evidenceMode: "source-grounded" },
      { heading: "校准主张", paragraphs: ["为每项文稿主张连接来源 ID、准确位置、抽取发现、警示和允许措辞。更强措辞需要更强且更直接的证据。"], sourceIds: ["grade-book-current"], evidenceMode: "instructional-synthesis" },
    ],
    practice: { title: "建立主张台账", brief: "把一段草稿拆成原子主张并检查每条证据链接。", steps: ["分配稳定主张 ID。", "记录来源位置、设计、发现、质量和报告缺口。", "重写超出证据边界的主张。"], deliverable: "带校准措辞的主张—证据矩阵。", reviewGate: "没有任何引文被要求支持超出其设计和报告结果的内容。" },
    checkpoint: { question: "研究没有报告子群结果，台账应如何记录？", options: ["子群结果未报告；不支持子群主张", "没有子群差异", "子群已平衡", "总体结果同样适用于所有群体"], correctIndex: 0, explanation: "没有报告不能转化为零差异或公平结果。" },
    takeaway: "台账防止真实引文被用来支撑虚假主张。",
  },
  "pdf-table-extraction-boundaries": {
    title: "PDF、表格与抽取边界",
    summary: "在保留页、表、单元格、单位和转换 provenance 的前提下抽取原文报告内容。",
    objective: "创建受 schema 控制的抽取表，保存原始位置、规范化字段、不确定性和双重检查规则。",
    artifact: "抽取表与核验日志",
    sections: [
      { heading: "把抽取当作数据生产", paragraphs: ["抽取前定义字段、类型、允许值、单位、缺失编码和 provenance。分开保存原文值与规范化值，使转换始终可检查。"], sourceIds: ["cochrane-data-collection"], evidenceMode: "source-grounded" },
      { heading: "返回渲染后的来源", paragraphs: ["OCR 与表格工具可能重排列、丢负号、合并单元格或误认脚注。必须在渲染后的 PDF 页或权威表格核验关键文字与数字，并记录页、表、行、列和注释。"], sourceIds: ["pdf-2-spec", "grobid-evaluation"], evidenceMode: "instructional-synthesis" },
      { heading: "限定派生计算", paragraphs: ["把重新计算的统计、单位转换、读图值和插补标为转换，保留代码与输入，不得把派生值写成文章直接报告。"], sourceIds: ["cochrane-data-collection"], evidenceMode: "instructional-synthesis" },
    ],
    practice: { title: "抽取一张复杂表", brief: "抽取至少包含脚注、缺失值或单位转换之一的表格。", steps: ["定义抽取 schema 与缺失编码。", "保存准确页和单元格 provenance。", "用代码重算一个值并标为派生。"], deliverable: "符合 schema 的抽取表与转换收据。", reviewGate: "审查者能从保存的输入重现每个转换值。" },
    checkpoint: { question: "从论文表格重新计算的值应怎样记录？", options: ["标为派生值，并保存代码、输入、公式、单位和来源单元格", "标为直接报告结果", "删除原始值以减少杂乱", "只写进叙述"], correctIndex: 0, explanation: "原文报告层和派生层必须保持可区分且可复现。" },
    takeaway: "只有位置和转换在复制后仍然存在，抽取才算忠实。",
  },
  "citation-verification-rag-locator": {
    title: "引文核验与 RAG 定位",
    summary: "用检索寻找候选，再到一手记录核验身份与支持关系。",
    objective: "审计书目身份、来源位置、主张支持和引文准确性，不信任生成引文。",
    artifact: "引文审计",
    sections: [
      { heading: "先解析身份", paragraphs: ["在被引记录和来源本身之间核对题名、作者、来源、年份、卷期页和 DOI 等持久标识。搜索或 metadata API 能加速定位，但冲突 metadata 必须调查。"], sourceIds: ["crossref-rest"], evidenceMode: "source-grounded" },
      { heading: "片段只用于导航", paragraphs: ["RAG 片段可能遗漏限定语、表格、标题、页界或周围方法。把它当定位器；接受主张前必须打开原始 PDF 页、表格、数据或代码。"], sourceIds: ["rag-original"], evidenceMode: "instructional-synthesis" },
      { heading: "审计支持关系，而非只查存在", paragraphs: ["真实论文仍可能被误引。记录准确主张、来源位置、允许措辞、边界、引文核对与状态。无法访问时要标记，不得把二手引文洗成一手证据。"], sourceIds: ["crossref-rest", "niso-jats"], evidenceMode: "instructional-synthesis" },
    ],
    practice: { title: "审计十条引文", brief: "核验一组含至少一项故意错配的书目身份与主张支持。", steps: ["解析持久标识和书目字段。", "在相关页或对象打开一手记录。", "记录支持、边界、引文与访问状态。"], deliverable: "带页级证据的引文审计。", reviewGate: "每条保留引文支持相邻准确主张；RAG 片段只作为定位器。" },
    checkpoint: { question: "RAG 片段可以在最终综述中证明什么？", options: ["候选段落在哪里；最终主张仍需核验一手来源", "无需打开来源即可证明主张真实", "证明全部生成引文存在", "证明省略上下文不重要"], correctIndex: 0, explanation: "分块和检索会移除上下文；权威支持必须在一手记录核验。" },
    takeaway: "检索找到门；打开门之后，研究证据才开始。",
  },
  "quantitative-analysis-boundaries": {
    title: "定量分析边界",
    summary: "让设计、假设、代码、多重性、不确定性与解释保持一致。",
    objective: "编写并执行有边界的分析计划，不让软件输出压过设计局限。",
    artifact: "定量分析计划与运行收据",
    sections: [
      { heading: "从 estimand 开始", paragraphs: ["选择模型前先写人群、处理或暴露、结果、对比、时间、单位和目标量。方便获得的系数未必回答研究问题。"], sourceIds: ["asa-pvalues"], evidenceMode: "instructional-synthesis" },
      { heading: "保存假设与多重性", paragraphs: ["记录缺失处理、转换、排除、聚类、依赖、诊断、多重检验、稳健性检查和偏离。p 值不衡量效应大小、重要性、真伪或复现概率。"], sourceIds: ["asa-pvalues"], evidenceMode: "source-grounded" },
      { heading: "让代码与表格能够核对", paragraphs: ["适当使用 tidy 且有键的数据结构与脚本化表格。把每个报告数字绑定到数据、代码、环境和输出收据；在写叙述前解决不一致。"], sourceIds: ["tidy-data"], evidenceMode: "instructional-synthesis" },
    ],
    practice: { title: "复现一项结果", brief: "从可用数据或课程 fixture 重新计算一项报告结果。", steps: ["写明 estimand 与假设。", "用版本化脚本和诊断运行。", "把输出与文稿主张核对并解释差异。"], deliverable: "分析脚本、环境收据与解释说明。", reviewGate: "结论报告效应、不确定性、假设和设计局限，而不只显著性。" },
    checkpoint: { question: "一个很小的 p 值本身能证明什么？", options: ["只说明在特定模型和假设下观测数据的兼容程度；不证明重要性或真实性", "效应很大且重要", "研究一定复现", "所有模型假设都成立"], correctIndex: 0, explanation: "解释必须同时包含设计、效应、不确定性、假设和多重性。" },
    takeaway: "统计软件在假设下计算；它不会替你选择可辩护主张。",
  },
  "qualitative-synthesis-boundaries": {
    title: "定性综合边界",
    summary: "保留情境、研究者决定、反证，以及参与者声音与综合之间的区别。",
    objective: "建立透明编码与综合轨迹，不编造饱和、共识或参与者意义。",
    artifact: "定性综合备忘录与审计轨迹",
    sections: [
      { heading: "定义分析对象", paragraphs: ["写明综合的是发现、参与者引语、作者解释、主题、案例还是机制。保留研究情境，不把措辞相同但现象不同的标签强行合并。"], sourceIds: ["entreq"], evidenceMode: "source-grounded" },
      { heading: "让解释可追溯", paragraphs: ["把编码和主题连接到来源摘录与位置，记录码本变化、负例、分歧、反思决定和确信度。AI 可以建议候选分组，但不能静默变成分析者或参与者。"], sourceIds: ["coreq"], evidenceMode: "instructional-synthesis" },
      { heading: "限定综合主张", paragraphs: ["报告差异和情境，避免无依据的比例语言，并区分原研究作者主张与综述团队推断。COREQ 只覆盖访谈/焦点小组；SRQR 更广，但两者都不证明分析可信。"], sourceIds: ["entreq", "srqr"], evidenceMode: "source-grounded" },
    ],
    practice: { title: "建立透明主题", brief: "综合一小组摘录，并纳入至少一个反例。", steps: ["定义单位与编码目的。", "把编码、修订与主题主张连接到摘录。", "写明情境、差异、反证、反思与确信度。"], deliverable: "主题矩阵与综合备忘录。", reviewGate: "审查者能区分来源声音、原作者解释与综述者综合。" },
    checkpoint: { question: "AI 建议的定性主题应怎样处理？", options: ["把它当候选解释，由人类用摘录、情境、反例和审计轨迹检验", "只要听起来连贯就作为最终主题", "把它当参与者证词", "把它当出现率证据"], correctIndex: 0, explanation: "综合需要由可问责的人类解释，并扎根来源语料和分析决定。" },
    takeaway: "主题听起来连贯还不够；从来源到解释的路径必须可见。",
  },
  "reproducibility-uncertainty-ai-disclosure": {
    title: "可复现性、不确定性与 AI 披露",
    summary: "打包材料、环境、决定、失败与 AI 协助，让他人能检查发生了什么。",
    objective: "建立复现包与披露，区分可用、受限、生成、已核验和失败步骤。",
    artifact: "复现包与披露",
    sections: [
      { heading: "绑定研究对象", paragraphs: ["打包协议、检索导出、台账、抽取 schema、数据或合法访问说明、代码、环境、输出和 README。尽量使用稳定路径、版本、校验和与单条命令或清晰步骤。"], sourceIds: ["acm-artifact-review", "fair-principles"], evidenceMode: "source-grounded" },
      { heading: "按功能披露 AI", paragraphs: ["记录工具与已知版本、日期、任务、输入边界、输出用途、人工核验、被拒输出和重要局限。不要把机密提示或专有内容贴进公开披露。"], sourceIds: ["icmje-ai"], evidenceMode: "version-watch" },
      { heading: "报告不确定性与失败", paragraphs: ["列出无法访问的来源、模糊资格、抽取失败、无法复现计算、缺失代码、不稳定工具和结论敏感性。失败日志是流程边界的证据，不是应该删除的尴尬。"], sourceIds: ["acm-artifact-review"], evidenceMode: "instructional-synthesis" },
    ],
    practice: { title: "运行洁净复现", brief: "请另一人或全新环境复现一张表和一项主张。", steps: ["打包输入、环境、代码、输出与说明。", "记录每个人工与 AI 辅助步骤。", "记录失败、修复包，并从洁净状态重跑。"], deliverable: "复现包、AI 披露与失败日志。", reviewGate: "全新环境能够得到声明输出，或产生明确记录的阻断因素。" },
    checkpoint: { question: "AI 使用披露应包含什么？", options: ["已知工具/版本、日期、任务、输入边界、输出用途、人工核验、失败与局限", "只写使用过 AI", "逐字公开全部机密提示", "声称人工复核已消除所有错误"], correctIndex: 0, explanation: "按功能和边界披露，读者才能判断 AI 在哪里影响研究过程。" },
    takeaway: "可复现性包括失败路径与人工判断，而不只最终脚本。",
  },
  "auditable-mini-review-capstone": {
    title: "可审查小型综述毕业项目",
    summary: "把协议、检索、筛选、抽取、分析、引文与披露整合为可重建综述。",
    objective: "交付八项相互连接的产物，并使每项实质主张都能解析到一手证据。",
    artifact: "可审查小型综述包",
    sections: [
      { heading: "核对各台账", paragraphs: ["每个纳入来源都应按需出现在筛选、抽取、主张和引文记录中。流程数量、ID、文件名与参考文献必须一致；处理孤立主张和未使用的纳入记录。"], sourceIds: ["prisma-2020"], evidenceMode: "instructional-synthesis" },
      { heading: "从矩阵写作", paragraphs: ["从已核验证据行起草主张，而不是依赖模型文案或记忆。写明异质性、质量、未报告、访问限制，以及哪些综合属于解释而非直接报告。"], sourceIds: ["grade-book-current"], evidenceMode: "instructional-synthesis" },
      { heading: "审计提交包", paragraphs: ["运行 schema、链接、引文、计算、隐私、许可和洁净复现检查。冻结版本化收据；保留未解决阻断，而不是修改报告直到警告消失。"], sourceIds: ["acm-artifact-review", "fair-principles"], evidenceMode: "source-grounded" },
    ],
    practice: { title: "提交并答辩小型综述", brief: "把提交包交给未参与建设的评审者。", steps: ["在八项产物中核对稳定 ID 与数量。", "把抽样主张返回到页、表、数据与代码。", "运行洁净复现并记录全部未解决局限。"], deliverable: "小型综述、八项产物与验证收据。", reviewGate: "评审者无需索取隐藏文件即可重建纳入并核验抽样主张。" },
    checkpoint: { question: "一项综述主张的合格最终证据链是什么？", options: ["主张 ID → 已核验抽取 → 准确的一手页/表/数据/代码 → 引文与边界", "主张 → RAG 片段 → 生成书目", "主张 → 搜索摘要 → 文章题名", "主张 → 模型置信分"], correctIndex: 0, explanation: "最终主张必须回到带位置和证据边界的一手记录。" },
    takeaway: "另一人能够审计时，综述才算完成；文案听起来完成还不够。",
  },
} as const;
