import type { CourseKitUiCopy } from "./types";

export const COURSE_KIT_UI_EN = {
  catalog: "Course catalog",
  course: "Course",
  module: "Module",
  modules: "Modules",
  phases: "Phases",
  duration: "Duration",
  level: "Level",
  audience: "Audience",
  prerequisite: "Prerequisite",
  minutes: "minutes",
  startCourse: "Start course",
  resumeCourse: "Resume course",
  courseMap: "Course map",
  curriculum: "Curriculum",
  curriculumIntro: "Work through the modules in order, then pass the final assessment and complete the capstone.",
  learningOutcomes: "Learning outcomes",
  principles: "Working principles",
  evidenceRegister: "Evidence register",
  evidenceNote: "Course claims are bounded by the cited source, version, jurisdiction, and access date.",
  source: "Source",
  sources: "Sources",
  sourceSupports: "Supports",
  sourceBoundary: "Boundary",
  sourceConceptDomain: "Concept domain",
  sourceTransformation: "Transformation",
  sourceRightsBoundary: "Rights boundary",
  sourceLicence: "Licence",
  evidenceModeLabels: {
    "source-grounded": "Source-grounded",
    "instructional-synthesis": "Instructional synthesis",
    "version-watch": "Version watch",
  },
  sourceKindLabels: {
    "normative-standard": "Normative standard",
    "law-or-regulation": "Law or regulation",
    "official-guidance": "Official guidance",
    "official-documentation": "Official documentation",
    research: "Research",
    "technical-report": "Technical report",
    "case-study": "Case study",
    "github-repository": "GitHub repository",
    "social-post": "Primary X post",
  },
  sourceStabilityLabels: {
    "stable-concept": "Stable concept",
    "current-documentation": "Current documentation",
    "version-pinned": "Version pinned",
    "jurisdiction-and-date-bound": "Jurisdiction and date bound",
    historical: "Historical",
  },
  accessedOn: "Accessed",
  objective: "Objective",
  artifact: "Artifact",
  practice: "Practice",
  steps: "Steps",
  deliverable: "Deliverable",
  reviewGate: "Review gate",
  checkpoint: "Checkpoint",
  checkAnswer: "Check answer",
  correct: "Correct.",
  incorrect: "Not yet correct.",
  tryAgain: "Try again",
  takeaway: "Takeaway",
  courseProgress: "Course progress",
  progressPosition: "{completed} of {total} milestones complete",
  milestonePosition: "Milestone {current} of {total}",
  storageUnavailable: "Browser storage is unavailable. Progress will remain in memory for this tab.",
  browserStorageNote: "Progress is stored in this browser.",
  resetProgress: "Reset course progress",
  resetConfirm: "Reset the saved progress for this course?",
  resetDone: "Course progress was reset.",
  resetDoneMemory: "In-memory course progress was reset. Browser storage remains unavailable.",
  markModuleComplete: "Mark module complete",
  markedModuleComplete: "Module marked complete",
  moduleComplete: "Complete",
  completeCheckpointFirst: "Answer the module checkpoint correctly before marking this module complete.",
  evidenceReceiptLabel: "Structured evidence receipt",
  evidenceReceiptPlaceholder: "Paste an aicourse.evidence-receipt.v1 JSON receipt",
  evidenceReceiptHelp: "The receipt must bind this course ID, course version, module artifact ID and module-artifact kind, then include a safe relative path, SHA-256, passing validator and date, reviewer decision, and limitations. Valid structure is reviewable evidence, not automatic proof.",
  completeReceiptFirst: "Add a valid structured evidence receipt before marking this module complete.",
  savedInBrowser: "Saved in this browser.",
  savedInMemory: "Saved in memory for this tab only.",
  finalAssessment: "Final assessment",
  submitQuiz: "Submit assessment",
  retryQuiz: "Retry assessment",
  quizPassed: "Assessment passed. The score gate and every critical question were satisfied.",
  quizNotPassed: "Assessment not passed. Meet the score gate and answer every critical question correctly.",
  answerAllQuestions: "Answer every selected question before submitting.",
  criticalQuestion: "Critical question",
  criticalGateFailed: "One or more critical questions were incorrect.",
  questionPosition: "Question {current} of {total}",
  scorePosition: "Score: {score} of {total}; {required} required",
  bestScorePosition: "Best score: {score} of {total}",
  quizDraftRestored: "Your saved answer draft was restored from this browser.",
  clearQuizDraft: "Clear answer draft",
  capstone: "Capstone",
  capstoneArtifacts: "Required artifacts",
  responsibleAiGate: "Required Responsible AI gate",
  responsibleAiAssessmentIds: "assessment",
  responsibleAiArtifactIds: "artifacts",
  capstoneEvidenceContract: "Versioned capstone evidence contract",
  downloadArtifactSchema: "Download artifact schema",
  downloadValidator: "Download offline validator",
  validatorCommand: "Validator command",
  artifactDraftLabel: "Local evidence note",
  artifactDraftPlaceholder: "Add a path, hash, receipt, or reviewer note",
  artifactDraftHelp: "Saved only in this browser. Do not paste personal data, credentials, API keys, or confidential research material.",
  artifactReceiptHelp: "Paste one aicourse.evidence-receipt.v1 receipt bound to this course ID, course version, capstone artifact ID and capstone-artifact kind, with a relative path, SHA-256, passing validator, reviewer decision and limitations. Schema validity makes the claim reviewable, not proven.",
  capstoneAttestation: "I have produced and reviewed every required artifact.",
  markCapstoneComplete: "Mark capstone complete",
  capstoneComplete: "Capstone complete",
  completeArtifactsFirst: "Complete every artifact and confirm the attestation before marking the capstone complete.",
  previous: "Previous",
  next: "Next",
  backToCourse: "Back to course",
  modulePosition: "Module {current} of {total}",
  phasePosition: "Phase {current} of {total}",
  openCourseMap: "Open course map",
  fallbackLanguageLabel: "Content language",
  dismissLanguageNotice: "Dismiss language notice",
} as const satisfies CourseKitUiCopy;

export const COURSE_KIT_UI_ZH_HANS = {
  catalog: "课程目录",
  course: "课程",
  module: "模块",
  modules: "模块",
  phases: "阶段",
  duration: "时长",
  level: "难度",
  audience: "适合人群",
  prerequisite: "先修要求",
  minutes: "分钟",
  startCourse: "开始课程",
  resumeCourse: "继续课程",
  courseMap: "课程地图",
  curriculum: "课程结构",
  curriculumIntro: "请按顺序完成各模块，然后通过期末测验并完成结课项目。",
  learningOutcomes: "学习成果",
  principles: "工作原则",
  evidenceRegister: "证据登记表",
  evidenceNote: "课程主张受所引来源、版本、司法管辖区和访问日期的边界约束。",
  source: "来源",
  sources: "来源",
  sourceSupports: "可支持",
  sourceBoundary: "证据边界",
  sourceConceptDomain: "概念域",
  sourceTransformation: "转化方式",
  sourceRightsBoundary: "权利边界",
  sourceLicence: "许可",
  evidenceModeLabels: {
    "source-grounded": "来源支持",
    "instructional-synthesis": "教学综合",
    "version-watch": "版本观察",
  },
  sourceKindLabels: {
    "normative-standard": "规范性标准",
    "law-or-regulation": "法律或法规",
    "official-guidance": "官方指引",
    "official-documentation": "官方文档",
    research: "研究论文",
    "technical-report": "技术报告",
    "case-study": "案例研究",
    "github-repository": "GitHub 仓库",
    "social-post": "X 一手原帖",
  },
  sourceStabilityLabels: {
    "stable-concept": "稳定概念",
    "current-documentation": "当前文档",
    "version-pinned": "固定版本",
    "jurisdiction-and-date-bound": "受法域与日期约束",
    historical: "历史材料",
  },
  accessedOn: "访问日期",
  objective: "学习目标",
  artifact: "学习产物",
  practice: "实践任务",
  steps: "步骤",
  deliverable: "交付物",
  reviewGate: "审核门槛",
  checkpoint: "知识检查",
  checkAnswer: "检查答案",
  correct: "回答正确。",
  incorrect: "尚未答对。",
  tryAgain: "再试一次",
  takeaway: "核心要点",
  courseProgress: "课程进度",
  progressPosition: "已完成 {completed}/{total} 个里程碑",
  milestonePosition: "第 {current}/{total} 个里程碑",
  storageUnavailable: "浏览器存储不可用。本标签页将仅在内存中保留进度。",
  browserStorageNote: "进度保存在此浏览器中。",
  resetProgress: "重置课程进度",
  resetConfirm: "是否重置本课程已保存的进度？",
  resetDone: "课程进度已重置。",
  resetDoneMemory: "内存中的课程进度已重置；浏览器存储仍不可用。",
  markModuleComplete: "标记模块为已完成",
  markedModuleComplete: "模块已标记为完成",
  moduleComplete: "已完成",
  completeCheckpointFirst: "请先正确回答本模块的知识检查，再将模块标记为完成。",
  evidenceReceiptLabel: "结构化证据收据",
  evidenceReceiptPlaceholder: "粘贴一份 aicourse.evidence-receipt.v1 JSON 收据",
  evidenceReceiptHelp: "收据必须绑定本课程 ID、课程版本、本模块产物 ID 与 module-artifact 类型，并包含安全相对路径、SHA-256、通过的校验及日期、审核决定和局限。结构有效只表示证据可评审，不代表自动证明。",
  completeReceiptFirst: "请先添加有效的结构化证据收据，再将模块标记为完成。",
  savedInBrowser: "已保存在此浏览器。",
  savedInMemory: "仅保存在当前标签页的内存中。",
  finalAssessment: "期末测验",
  submitQuiz: "提交测验",
  retryQuiz: "重新测验",
  quizPassed: "测验通过：已达到分数门槛，且所有关键题均回答正确。",
  quizNotPassed: "测验尚未通过：请达到分数门槛，并正确回答所有关键题。",
  answerAllQuestions: "提交前请回答本次抽取的全部题目。",
  criticalQuestion: "关键题",
  criticalGateFailed: "一项或多项关键题回答错误。",
  questionPosition: "第 {current}/{total} 题",
  scorePosition: "得分：{score}/{total}；通过要求为 {required} 分",
  bestScorePosition: "最佳得分：{score}/{total}",
  quizDraftRestored: "已从此浏览器恢复你的答题草稿。",
  clearQuizDraft: "清除答题草稿",
  capstone: "结课项目",
  capstoneArtifacts: "必需产物",
  responsibleAiGate: "必需的负责任 AI 验收门",
  responsibleAiAssessmentIds: "测验题",
  responsibleAiArtifactIds: "产物",
  capstoneEvidenceContract: "版本化结课项目证据合同",
  downloadArtifactSchema: "下载产物 schema",
  downloadValidator: "下载离线校验器",
  validatorCommand: "校验命令",
  artifactDraftLabel: "本地证据备注",
  artifactDraftPlaceholder: "填写路径、哈希、运行收据或审核备注",
  artifactDraftHelp: "仅保存在此浏览器中。请勿粘贴个人数据、凭据、API 密钥或机密研究材料。",
  artifactReceiptHelp: "请粘贴一份绑定本课程 ID、课程版本、结课产物 ID 与 capstone-artifact 类型的 aicourse.evidence-receipt.v1 收据，并包含相对路径、SHA-256、通过的校验、审核决定与局限。Schema 有效只表示主张可评审，不代表已证明。",
  capstoneAttestation: "我已完成并审核所有必需产物。",
  markCapstoneComplete: "标记结课项目为已完成",
  capstoneComplete: "结课项目已完成",
  completeArtifactsFirst: "请完成所有产物并确认声明，再将结课项目标记为完成。",
  previous: "上一模块",
  next: "下一模块",
  backToCourse: "返回课程",
  modulePosition: "第 {current}/{total} 个模块",
  phasePosition: "第 {current}/{total} 个阶段",
  openCourseMap: "打开课程地图",
  fallbackLanguageLabel: "内容语言",
  dismissLanguageNotice: "关闭语言提示",
} as const satisfies CourseKitUiCopy;

export function formatCourseKitCopy(
  template: string,
  values: Readonly<Record<string, string | number>>,
): string {
  return template.replace(/\{([a-zA-Z][a-zA-Z0-9]*)\}/g, (match, key) =>
    Object.hasOwn(values, key) ? String(values[key]) : match,
  );
}
