import type {
  ClaudeIncomeCourse,
  ClaudeIncomeLesson,
  ClaudeIncomeUnit,
} from "./types";

export const CLAUDE_INCOME_UNITS = [
  {
    id: "prove-value",
    order: 1,
    title: "Prove value before you build",
    summary: "Choose a buyer, verify an expensive problem, and turn the problem into a bounded offer.",
    outcome: "A priced pilot hypothesis backed by customer evidence and explicit stop rules.",
    lessonSlugs: [
      "choose-a-money-path",
      "validate-paid-demand",
      "scope-and-price-the-offer",
    ],
  },
  {
    id: "deliver-value",
    order: 2,
    title: "Deliver work a client can inspect",
    summary: "Use Claude as part of a controlled service workflow with specifications, isolated context, citations, and human review.",
    outcome: "A repeatable delivery packet with source evidence, acceptance checks, and a client-safe handoff.",
    lessonSlugs: [
      "write-a-delivery-spec",
      "run-client-projects",
      "sell-citation-grade-research",
    ],
  },
  {
    id: "systemize-value",
    order: 3,
    title: "Turn delivery into an operating system",
    summary: "Create editable files, reusable Skills, least-privilege connections, and testable prototypes without hiding the operator.",
    outcome: "A versioned workflow that another qualified person can run, verify, and roll back.",
    lessonSlugs: [
      "deliver-files-that-survive-review",
      "standardize-with-skills-and-connectors",
      "prototype-with-artifacts",
    ],
  },
  {
    id: "sell-responsibly",
    order: 4,
    title: "Build, sell, and retain responsibly",
    summary: "Move from prototype to software only when evidence supports it, then sell with truthful proof and accountable operations.",
    outcome: "A seven-day demand experiment and a go, revise, or stop decision grounded in evidence.",
    lessonSlugs: [
      "build-software-with-claude",
      "earn-trust-and-retainers",
      "capstone-seven-day-demand-test",
    ],
  },
] as const satisfies readonly ClaudeIncomeUnit[];

export const CLAUDE_INCOME_LESSONS = [
  {
    slug: "choose-a-money-path",
    order: 1,
    unitId: "prove-value",
    minutes: 65,
    title: "Choose a money path that starts with expertise",
    kicker: "Lesson 01 · Offer strategy",
    summary: "Separate services, managed workflows, and software so you can choose the smallest credible way to solve one buyer's problem.",
    objective: "Choose one buyer, one painful job, one outcome, and one Claude-assisted delivery path without treating Claude itself as the offer.",
    sections: [
      {
        heading: "Claude is leverage, not demand",
        paragraphs: [
          "Clients do not pay for prompt volume. They pay for a decision, artifact, workflow, or result that is valuable enough to buy and safe enough to use. Claude can reduce the cost of research, drafting, analysis, prototyping, and iteration, but it cannot supply your reputation, access to buyers, domain judgment, or final accountability.",
          "Start with a knowledge wedge: a task you understand well enough to notice a plausible-looking mistake. If you cannot define what good work looks like, faster generation increases review risk instead of profit.",
        ],
        bullets: [
          "Service: you deliver a bounded result, such as a cited competitor brief or an editable reporting pack.",
          "Managed workflow: you operate a recurring process, such as a weekly insight report with approval checkpoints.",
          "Software: a user operates a product that must earn trust through reliability, security, support, and clear economics.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["academy-work", "commercial-terms"],
      },
      {
        heading: "Select the shortest path to evidence",
        paragraphs: [
          "A service is usually the fastest way to learn because the provider can compensate for rough edges with judgment. A managed workflow follows when the input, output, and review cycle repeat. Software belongs last, after the workflow has repeat buyers and stable acceptance criteria.",
          "A public repository or social post can reveal a workflow pattern, but it cannot tell you whether the pattern will work for your buyer. Treat practitioner examples as leads for investigation, not forecasts.",
        ],
        bullets: [
          "Choose a service when the work is variable and expert review carries most of the value.",
          "Choose a managed workflow when the same decision repeats on a schedule.",
          "Choose software only when users repeat the workflow and self-service reduces a real constraint.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["github-marketingskills", "github-seo-audit", "github-open-saas"],
      },
      {
        heading: "Write a falsifiable money thesis",
        paragraphs: [
          "Your first thesis should be easy to disprove. Name the buyer, triggering event, current workaround, cost of the problem, promised deliverable, review owner, and evidence that would make you stop. Do not put a monthly income target in the thesis. Put a customer decision in it.",
          "A strong thesis sounds like a test: three operations leads with a recurring board-report bottleneck will agree to inspect a sample and at least one will discuss a paid pilot. A weak thesis sounds like a fantasy: businesses will pay for AI automation.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["github-shotgun-case"],
      },
    ],
    workflow: [
      "List three tasks where you can independently judge quality.",
      "For each task, name a buyer and the event that makes the task urgent.",
      "Choose service, managed workflow, or software based on how repeatable and self-service-ready the task is.",
      "Write one falsifiable buyer and outcome thesis.",
      "Define the evidence that will make you continue, revise, or stop.",
    ],
    promptTemplate: `Act as a skeptical offer strategist.\n\nBuyer: [specific role and market]\nTrigger: [event that creates urgency]\nCurrent workaround: [how the buyer handles it now]\nMy expertise: [what I can independently verify]\nCandidate outcome: [decision or artifact]\n\nAsk me one question at a time until you can produce:\n1. a service version,\n2. a managed-workflow version,\n3. a software version,\n4. the riskiest assumption in each,\n5. a seven-day test that could disprove the best option.\n\nDo not estimate revenue. Flag missing evidence explicitly.`,
    economics: "Contribution per delivery = collected fee - Claude and tool cost - contractor cost - acquisition cost - refund allowance - value of operator time.",
    qualityGate: [
      "The buyer is a role you can contact, not a broad industry.",
      "The outcome is observable by the buyer.",
      "You have the expertise or reviewer needed to catch material errors.",
      "The thesis includes a stop condition.",
    ],
    redFlags: [
      "The offer is described as access to Claude or prompts.",
      "The plan depends on mass unsolicited outreach.",
      "The income claim is extrapolated from one screenshot or post.",
      "The work enters legal, medical, financial, hiring, or other high-risk decisions without qualified safeguards.",
    ],
    practice: {
      title: "Create a one-page money-path memo",
      brief: "Compare three commercialization paths for one domain problem and choose the smallest credible experiment.",
      estimatedMinutes: 30,
      steps: [
        "Write the buyer, trigger, current workaround, and measurable outcome.",
        "Describe service, managed-workflow, and software versions in one sentence each.",
        "Score each version from 1 to 5 for demand evidence, delivery risk, time to first proof, and your verification ability.",
        "Choose one path and write the strongest reason it could fail.",
        "Set a seven-day evidence threshold and a stop rule.",
      ],
      deliverables: [
        "One comparison table",
        "One falsifiable money thesis",
        "One stop rule",
      ],
      doneWhen: [
        "A stranger can identify the buyer and outcome without asking what the offer means.",
        "The chosen path can be tested without building a full product.",
      ],
      safety: "Use no confidential client information. Do not select a regulated or high-risk decision unless a qualified professional owns the review and applicable safeguards.",
    },
    checkpoint: {
      prompt: "Why is a narrower service often a better first money path than a Claude-powered SaaS?",
      answer: "A narrow service reaches buyer evidence faster and lets expert review compensate for unstable workflow details. Software adds reliability, security, support, and acquisition work before demand is proven.",
    },
    takeaway: "Choose the path that produces customer evidence fastest, not the path that looks most automated.",
    figureIds: ["fig-01-chat-composer"],
    sourceIds: [
      "academy-work",
      "commercial-terms",
      "github-marketingskills",
      "github-seo-audit",
      "github-open-saas",
      "github-shotgun-case",
    ],
  },
  {
    slug: "validate-paid-demand",
    order: 2,
    unitId: "prove-value",
    minutes: 60,
    title: "Validate paid demand before automating",
    kicker: "Lesson 02 · Customer evidence",
    summary: "Replace likes and compliments with problem interviews, sample reviews, and a clearly bounded paid-pilot decision.",
    objective: "Run a small demand test that distinguishes curiosity, workflow pain, willingness to review, and willingness to pay.",
    sections: [
      {
        heading: "Use a ladder of evidence",
        paragraphs: [
          "Evidence gets stronger as the buyer gives up something scarce. A like costs almost nothing. A detailed interview costs time. Sharing a sanitized sample costs trust. Reviewing a tailored deliverable costs attention. Signing a paid pilot creates a commercial commitment.",
          "Do not call interest validation. Record the exact behavior and preserve rejected hypotheses. Your goal is not to persuade every interviewee. It is to discover whether one painful workflow is frequent, consequential, and reachable.",
        ],
        bullets: [
          "Weak: views, likes, generic compliments, waitlist entries with no qualifying question.",
          "Useful: named workflow, frequency, current workaround, consequence, owner, and budget route.",
          "Strong: approved sample, scheduled review, written pilot scope, or payment under clear terms.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["github-shotgun-case"],
      },
      {
        heading: "Interview the past, not the imagined future",
        paragraphs: [
          "Ask about the last time the problem occurred. Request the sequence, artifacts, handoffs, delays, and rework. Avoid asking whether the person would buy an AI solution. Hypothetical enthusiasm encourages agreement and hides the cost of changing behavior.",
          "Use Claude after the interview to structure notes, surface contradictions, and draft follow-up questions. Keep the recording or transcript only with consent, separate facts from interpretation, and verify every attributed statement.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["academy-work", "aup"],
      },
      {
        heading: "Offer a manual concierge sample",
        paragraphs: [
          "Build the smallest sample that demonstrates the buying decision. A two-page source matrix can validate a research offer. One annotated spreadsheet can validate a reporting offer. A clickable Artifact can validate a workflow concept. The sample should be intentionally limited and marked as a demonstration.",
          "Measure whether the buyer can evaluate it, what must change, who owns approval, and whether the next step is a paid pilot. A request for many free revisions is not the same as demand.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["help-artifacts", "github-seo-audit"],
      },
    ],
    workflow: [
      "Recruit five people who recently experienced the target workflow.",
      "Ask for the last real example, not a hypothetical preference.",
      "Code each note as fact, quote, interpretation, or unanswered question.",
      "Create one limited concierge sample using synthetic or client-approved data.",
      "Ask for a concrete next action: review, introduction, pilot scoping, or decline.",
    ],
    promptTemplate: `You are a research assistant, not a salesperson.\n\nBelow are de-identified interview notes. Do not invent missing facts.\n\n[PASTE NOTES]\n\nCreate a table with:\n- observed past behavior,\n- verbatim statement,\n- current workaround,\n- frequency,\n- consequence,\n- decision owner,\n- evidence strength,\n- contradiction,\n- unanswered question.\n\nThen propose three follow-up questions. Label every inference as an inference.`,
    economics: "Expected pilot value is a hypothesis. Test whether the cost of the current problem is large enough to support your delivery cost and the buyer's switching cost.",
    qualityGate: [
      "Every claim in the insight table maps to interview evidence.",
      "The sample uses synthetic or expressly approved data.",
      "The buyer knows the sample is limited and reviewable.",
      "The next action is behavioral, not a satisfaction score.",
    ],
    redFlags: [
      "Only friends or creators selling AI services were interviewed.",
      "Questions asked whether AI sounded useful instead of examining past behavior.",
      "The sample was customized repeatedly without a paid-pilot boundary.",
      "Private notes were uploaded without consent or redaction.",
    ],
    practice: {
      title: "Run five problem interviews",
      brief: "Collect and code recent workflow evidence, then test one limited sample with at least two participants.",
      estimatedMinutes: 90,
      steps: [
        "Write six neutral questions about the last occurrence of the problem.",
        "Conduct five 15-minute interviews with consent.",
        "Create an evidence matrix that distinguishes facts, quotes, and inferences.",
        "Build one concierge sample from synthetic or approved inputs.",
        "Record each participant's concrete next action and your continue, revise, or stop decision.",
      ],
      deliverables: [
        "Interview guide",
        "De-identified evidence matrix",
        "Limited sample",
        "Demand decision memo",
      ],
      doneWhen: [
        "At least three interviews describe a recent occurrence with a consequential workaround.",
        "At least two people inspect the sample and take a recorded next action, even if that action is decline.",
      ],
      safety: "Obtain consent, collect the minimum data required, remove personal identifiers, and honor deletion requests. Do not fabricate quotes or backfill missing answers with Claude.",
    },
    checkpoint: {
      prompt: "Which is stronger evidence: 100 waitlist signups or one signed paid pilot?",
      answer: "The paid pilot is usually stronger because it requires a commercial commitment. Waitlist signups can still help recruit interviews, but they do not establish willingness to pay or delivery fit by themselves.",
    },
    takeaway: "Automate only after buyers reveal a recurring workflow and commit to a concrete next step.",
    figureIds: [],
    sourceIds: [
      "academy-work",
      "help-artifacts",
      "github-shotgun-case",
      "github-seo-audit",
      "aup",
    ],
  },
  {
    slug: "scope-and-price-the-offer",
    order: 3,
    unitId: "prove-value",
    minutes: 70,
    title: "Scope and price an offer you can deliver",
    kicker: "Lesson 03 · Commercial design",
    summary: "Turn customer evidence into an acceptance-tested pilot, calculate a price floor, and contain revision and tool-cost risk.",
    objective: "Write a scope that defines inputs, outputs, review, exclusions, change control, and a price hypothesis without inventing value claims.",
    sections: [
      {
        heading: "Sell an acceptance-tested deliverable",
        paragraphs: [
          "A useful scope makes disagreement visible before work begins. Define the buyer, decision supported, client inputs, deliverable format, evidence standard, review owner, revision rounds, delivery date, and exclusions. If the buyer cannot inspect the result, the output is not yet a professional deliverable.",
          "Do not promise outcomes you cannot control, such as ranking, revenue, funding, or legal approval. Promise the process and artifact you can verify.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["commercial-terms", "github-seo-audit"],
      },
      {
        heading: "Calculate the floor before discussing value",
        paragraphs: [
          "Your price floor must cover acquisition, setup, Claude and connected-tool costs, qualified review time, delivery, revisions, overhead, and a refund or error allowance. Your initial estimate should use a range for uncertain work and an explicit assumption log.",
          "Value-based context can help you understand the buyer's ceiling, but it is not permission to invent savings. Use buyer-provided baseline data, show the calculation, and label scenarios as hypothetical until measured.",
        ],
        bullets: [
          "Floor: the minimum fee that leaves acceptable contribution after realistic costs.",
          "Reference point: the buyer's verified cost of the current workaround or delay.",
          "Hypothesis price: a testable fee for the defined pilot, not an income promise.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["docs-cost"],
      },
      {
        heading: "Use change control to protect both sides",
        paragraphs: [
          "A scope is not a wall. It is a mechanism for making new information explicit. When inputs, stakeholders, data volume, output format, or acceptance criteria change, write a short change note with the effect on price, timing, and risk. Get approval before proceeding.",
          "A pilot should also state the ownership of source data, generated files, reusable methods, and confidential material. Anthropic's Commercial Terms allocate output rights only as between Anthropic and the customer and to the extent permitted by applicable law. They do not guarantee copyrightability, originality, accuracy, non-infringement, or rights in third-party material. Your client agreement still needs its own allocation and review.",
        ],
        claimClass: "current-plan-or-policy",
        sourceIds: ["commercial-terms"],
      },
    ],
    workflow: [
      "Convert the chosen demand signal into one pilot decision and one deliverable.",
      "List required inputs and the owner of each input.",
      "Write acceptance criteria that can be checked without trusting Claude's confidence.",
      "Estimate a low, likely, and high delivery-cost scenario.",
      "Set the fee, revision boundary, payment milestone, and change-control rule.",
    ],
    promptTemplate: `Act as a skeptical delivery manager. Review this draft pilot scope.\n\nBuyer decision: [decision]\nInputs: [inputs and owners]\nDeliverables: [files or workflow]\nAcceptance criteria: [checks]\nExclusions: [not included]\nTimeline: [milestones]\nPrice hypothesis: [fee and assumptions]\n\nReturn:\n1. every ambiguous term,\n2. hidden dependencies,\n3. missing acceptance checks,\n4. likely scope-creep triggers,\n5. a revised scope table,\n6. assumptions that require buyer confirmation.\n\nDo not provide legal advice or invent market rates.`,
    economics: "Price floor = acquisition + setup + model and tool cost + review labor + delivery labor + revision allowance + overhead + risk allowance.",
    qualityGate: [
      "Each deliverable has a format, owner, due point, and acceptance check.",
      "The price model includes human review and revisions.",
      "The scope distinguishes measured facts from hypothetical value.",
      "Client and provider know what is excluded and how changes are approved.",
    ],
    redFlags: [
      "Unlimited revisions or undefined data volume.",
      "Payment depends entirely on an outcome outside your control.",
      "The fee ignores operator review, acquisition, refunds, or connected-tool costs.",
      "The contract treats model output as automatically accurate, original, or non-infringing.",
    ],
    practice: {
      title: "Write a two-page paid-pilot scope",
      brief: "Create a pilot offer with inspectible acceptance criteria and a three-scenario cost model.",
      estimatedMinutes: 50,
      steps: [
        "Write the buyer decision, input list, deliverable, timeline, and review owner.",
        "Define five acceptance checks and two explicit exclusions.",
        "Calculate low, likely, and high cost scenarios including your review time.",
        "Choose a price hypothesis and state every assumption.",
        "Ask a peer to identify ambiguity, then issue version 1.1 with a change log.",
      ],
      deliverables: [
        "Pilot scope version 1.1",
        "Cost model with assumptions",
        "Change-control paragraph",
      ],
      doneWhen: [
        "A reviewer can mark each acceptance check pass or fail.",
        "The high-cost scenario does not make the agreed fee economically impossible.",
      ],
      safety: "Use a qualified attorney for contract, employment, tax, privacy, intellectual-property, or regulated-service questions. Course templates are operational prompts, not legal advice.",
    },
    checkpoint: {
      prompt: "Why should review time be included in a Claude-assisted price floor?",
      answer: "The provider remains accountable for detecting errors, validating sources, checking formats, and approving the handoff. Omitting review time turns apparent automation savings into hidden unpaid labor and quality risk.",
    },
    takeaway: "Price the verified delivery system, including human review, not the speed of the first draft.",
    figureIds: [],
    sourceIds: ["commercial-terms", "docs-cost", "github-seo-audit"],
  },
  {
    slug: "write-a-delivery-spec",
    order: 4,
    unitId: "deliver-value",
    minutes: 60,
    title: "Write a delivery spec, not a magic prompt",
    kicker: "Lesson 04 · Prompt operations",
    summary: "Translate a client scope into a reusable task contract with evidence rules, an output schema, and a separate verification pass.",
    objective: "Create a prompt package that another qualified operator can run and review against the same acceptance criteria.",
    sections: [
      {
        heading: "Move the contract into the prompt",
        paragraphs: [
          "A professional prompt is an execution specification. It carries the audience, decision, authorized inputs, definitions, constraints, required evidence, output schema, refusal conditions, and acceptance checks from the commercial scope into the work session.",
          "Keep stable instructions separate from case-specific inputs. This makes the workflow easier to test, version, and inspect. It also prevents one client's details from silently becoming part of the next client's template.",
        ],
        bullets: [
          "Stable layer: role, process, definitions, output schema, quality checks, and prohibited actions.",
          "Case layer: buyer-approved documents, dates, entities, questions, and delivery context.",
          "Review layer: independent checks, discrepancy log, approval owner, and handoff status.",
        ],
        claimClass: "verified-capability",
        sourceIds: ["docs-prompting", "academy-work"],
      },
      {
        heading: "Require uncertainty to stay visible",
        paragraphs: [
          "Tell Claude to preserve missing evidence, contradictions, and confidence limits. An empty field marked not found is safer than a fluent guess. Ask for source pointers beside material claims and define what counts as adequate support.",
          "Examples can stabilize format, but examples also create anchoring risk. Use at least one normal fixture and one adversarial fixture that contains missing, conflicting, or out-of-scope information.",
        ],
        claimClass: "verified-capability",
        sourceIds: ["docs-prompting", "commercial-terms"],
      },
      {
        heading: "Separate generation from acceptance",
        paragraphs: [
          "Do not ask the same response to declare itself correct. Run a second pass against the original inputs and acceptance checklist. For important work, use a human reviewer who understands the domain and can reject the output.",
          "Preserve the prompt version, input manifest, output, verification result, and correction note. This small audit trail turns a clever conversation into a service process you can improve.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["commercial-terms"],
      },
    ],
    workflow: [
      "Copy acceptance criteria from the paid-pilot scope.",
      "Split stable instructions from case-specific inputs.",
      "Define an exact output schema and an explicit not-found behavior.",
      "Run a normal fixture and an adversarial fixture.",
      "Verify the output independently and log every correction.",
    ],
    promptTemplate: `Task contract version: [version]\n\nAudience and decision:\n[audience, decision supported]\n\nAuthorized inputs:\n[list each input and its owner]\n\nDefinitions and exclusions:\n[terms, boundaries, prohibited actions]\n\nRequired process:\n1. inventory the inputs,\n2. identify missing or conflicting evidence,\n3. perform the requested analysis,\n4. map each material claim to a source pointer,\n5. return the output schema below.\n\nOutput schema:\n[headings, fields, tables, file type]\n\nIf evidence is absent, write NOT FOUND. Do not infer a missing fact.\n\nAcceptance checklist:\n[observable pass or fail checks]`,
    economics: "Prompt reuse creates margin only when it reduces setup and correction time without reducing acceptance quality. Track both first-pass time and verified-delivery time.",
    qualityGate: [
      "The prompt includes the decision, authorized inputs, output schema, and refusal behavior.",
      "Every material claim can point back to an input or approved source.",
      "An adversarial fixture tests missing or contradictory evidence.",
      "A reviewer other than the generating response approves the handoff.",
    ],
    redFlags: [
      "The prompt contains a real client's secret in the reusable layer.",
      "The prompt asks Claude to be accurate without defining checks.",
      "A confidence score is accepted without evidence.",
      "The output is delivered directly because it looks polished.",
    ],
    practice: {
      title: "Build a versioned delivery-spec pack",
      brief: "Turn your pilot scope into a stable prompt, two fixtures, and an independent review checklist.",
      estimatedMinutes: 45,
      steps: [
        "Extract the audience, decision, input boundary, deliverables, and acceptance rules from your scope.",
        "Write stable instructions and a separate case-input form.",
        "Create one representative fixture with synthetic data.",
        "Create one adversarial fixture with a contradiction and a missing field.",
        "Run both, review the output, and publish version 1.1 with a correction log.",
      ],
      deliverables: [
        "Stable prompt version 1.1",
        "Case-input form",
        "Normal and adversarial fixtures",
        "Independent review checklist",
      ],
      doneWhen: [
        "The adversarial run leaves unsupported fields visibly unresolved.",
        "A second reviewer can reach the same pass or fail decision from the checklist.",
      ],
      safety: "Use synthetic fixtures. Store client-specific data outside the reusable prompt and follow the client's approved retention and deletion rules.",
    },
    checkpoint: {
      prompt: "What makes a delivery spec more valuable than a long one-off prompt?",
      answer: "A delivery spec links the commercial scope to repeatable instructions, fixtures, evidence behavior, and an independent acceptance check. It can be versioned and audited instead of relying on one conversation.",
    },
    takeaway: "The commercially defensible asset is not a secret phrase. It is a testable delivery contract.",
    figureIds: ["fig-01-chat-composer"],
    sourceIds: ["docs-prompting", "academy-work", "commercial-terms"],
  },
  {
    slug: "run-client-projects",
    order: 5,
    unitId: "deliver-value",
    minutes: 70,
    title: "Run client work in isolated Projects",
    kicker: "Lesson 05 · Context and privacy",
    summary: "Create one outcome-bounded Project per client, minimize folder access, and prevent context leakage across engagements.",
    objective: "Set up a client workspace with an approved input manifest, a least-privilege folder boundary, and a clean handoff and deletion plan.",
    sections: [
      {
        heading: "Use one client, one outcome, one boundary",
        paragraphs: [
          "Projects can organize chats and project knowledge around a body of work. That convenience does not replace information governance. Name the client outcome, list approved inputs, and keep unrelated material outside the Project.",
          "Current official help describes Projects on all Claude plans. As reviewed on 2026-08-23, Free users can create up to five Projects, while enhanced retrieval is a paid-plan feature. These are high-volatility facts. Confirm the current help page before advising a client to purchase or change a plan.",
        ],
        claimClass: "current-plan-or-policy",
        sourceIds: ["help-projects"],
      },
      {
        heading: "Treat folder access as production access",
        paragraphs: [
          "Cowork sessions run in Anthropic's cloud, and local files that Cowork accesses are processed there. Grant a dedicated engagement folder, not a desktop, home directory, shared drive root, or multi-client archive. The folder should contain only approved copies and a manifest, never the only copy of important material.",
          "Approval behavior depends on the selected mode and tool. Skip all approvals does not check actions, and computer use does not receive the same ordinary per-action tool checks, although permanent deletion still requires explicit permission. Use the highest practical review level for destructive, external, financial, account, or publishing actions.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["academy-cowork", "help-cowork-safety", "aup"],
      },
      {
        heading: "Design the exit before the first upload",
        paragraphs: [
          "Record who owns each source, derived file, reusable method, and final deliverable. At completion, provide the editable outputs, source map, known limitations, and client-facing operating note. Then archive or delete working copies according to the agreement.",
          "If a client asks you to mix confidential work into a public Skill, repository, portfolio, or example, stop and obtain explicit permission for the specific material and use.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["commercial-terms", "aup"],
      },
    ],
    workflow: [
      "Create a dedicated Project named for the client outcome, not a vague client bucket.",
      "Create an approved engagement folder containing copies and an input manifest.",
      "Add only the minimum knowledge needed for the scoped decision.",
      "Set approval behavior based on action risk and test with synthetic input first.",
      "At handoff, export editable outputs, limitations, source map, and a retention log.",
    ],
    promptTemplate: `Project operating note\n\nClient outcome: [outcome]\nAuthorized audience: [people]\nApproved inputs: [manifest]\nExcluded data: [categories and paths]\nAllowed actions: [read, create, edit, research]\nActions requiring approval: [external, destructive, financial, publishing]\nOutput folder: [dedicated path]\nAcceptance owner: [name or role]\nRetention rule: [archive or deletion date]\n\nBefore each task, confirm the requested input is in the approved manifest. If not, stop and request approval.`,
    economics: "Client isolation adds setup time but reduces the expected cost of rework, confidentiality incidents, and disputed handoffs. Include setup and closeout in the offer.",
    qualityGate: [
      "The Project name and goal identify one client outcome.",
      "The folder contains only approved copies and an input manifest.",
      "External, destructive, publishing, and financial actions require explicit review.",
      "The engagement has an owner, retention rule, and client-safe export path.",
    ],
    redFlags: [
      "A shared Project holds multiple clients' confidential material.",
      "Claude receives a broad folder because selecting files is inconvenient.",
      "The provider cannot list what was uploaded or derived.",
      "Client content is reused in marketing or a Skill without specific permission.",
    ],
    practice: {
      title: "Build a synthetic client Project pack",
      brief: "Practice the complete setup and closeout workflow with a fictional client and synthetic files.",
      estimatedMinutes: 45,
      steps: [
        "Create a fictional client outcome and a dedicated local folder.",
        "Add three synthetic source files and an input manifest with owners and permissions.",
        "Write the Project goal and operating note.",
        "Run one bounded task and inspect every created file.",
        "Produce the editable handoff, limitations note, and deletion log.",
      ],
      deliverables: [
        "Synthetic engagement folder",
        "Input manifest",
        "Project operating note",
        "Handoff and retention log",
      ],
      doneWhen: [
        "No source or output exists outside the dedicated test folder.",
        "A reviewer can reconstruct what Claude accessed and what the provider approved.",
      ],
      safety: "Do not use a real client as the practice case. Never grant a broad directory to save setup time, and never keep secrets or credentials in the engagement folder.",
    },
    checkpoint: {
      prompt: "Why is one Project per client outcome safer than one Project for an entire agency?",
      answer: "It minimizes context mixing, makes the approved input boundary inspectible, simplifies handoff and deletion, and reduces the chance that one client's material influences another client's output.",
    },
    takeaway: "Convenient context becomes professional context only when its boundary is explicit.",
    figureIds: ["fig-02-cowork-composer", "fig-04-new-project"],
    sourceIds: ["help-projects", "academy-cowork", "help-cowork-safety", "commercial-terms", "aup"],
  },
  {
    slug: "sell-citation-grade-research",
    order: 6,
    unitId: "deliver-value",
    minutes: 75,
    title: "Deliver citation-grade research briefs",
    kicker: "Lesson 06 · Research service",
    summary: "Use Research and Web search to accelerate discovery while you verify source identity, claim fit, dates, and quotation accuracy.",
    objective: "Create a decision brief with a claim-to-source matrix, uncertainty register, and human verification record.",
    sections: [
      {
        heading: "Sell the decision packet, not the search session",
        paragraphs: [
          "A buyer may pay for a decision-ready competitor scan, vendor landscape, policy monitor, grant opportunity brief, or evidence map. The value comes from the question, source standard, synthesis, and review, not from the number of pages or links.",
          "As reviewed on 2026-08-23, Research is available on paid Claude plans, requires Web search, and is opened from the chat composer's plus button. It performs iterative investigation and returns citations. Treat plan eligibility and control location as dated product facts, not permanent instructions.",
        ],
        claimClass: "current-plan-or-policy",
        sourceIds: ["help-research"],
      },
      {
        heading: "Verify four links in the evidence chain",
        paragraphs: [
          "For every material claim, verify source identity, source content, claim fit, and current relevance. Open the cited page. Confirm the publisher and date. Read enough context to know whether the source supports the wording. Record whether the claim is fact, practitioner report, inference, or hypothetical example.",
          "Do not use a citation merely because it looks authoritative. A correct link can still fail to support the claim. A practitioner post can support what the person reports, but not the general effectiveness or earnings of a workflow.",
        ],
        bullets: [
          "Identity: is this the claimed publisher, author, document, and version?",
          "Content: does the cited page contain the relevant information?",
          "Fit: does it support the exact wording and scope of the claim?",
          "Currency: is the date adequate for the decision and volatility of the topic?",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["help-research", "commercial-terms"],
      },
      {
        heading: "Package uncertainty as part of the product",
        paragraphs: [
          "A serious brief includes an executive answer, source matrix, method, contradictions, unanswered questions, sensitivity to changing facts, and a recommended next verification step. Make a boundary visible when evidence is missing.",
          "Do not sell Claude-generated legal, medical, financial, hiring, or safety conclusions as professional advice. For higher-risk decisions, use qualified review and the safeguards required by policy and law.",
        ],
        claimClass: "current-plan-or-policy",
        sourceIds: ["aup", "commercial-terms"],
      },
    ],
    workflow: [
      "Write the buyer's decision and the source inclusion rules before searching.",
      "Use Research for discovery and preserve the returned source trail.",
      "Open and verify every source supporting a material claim.",
      "Classify each claim and record contradictions or missing evidence.",
      "Deliver the brief, source matrix, method note, and verification log together.",
    ],
    promptTemplate: `Research question: [decision question]\nDecision owner: [role]\nGeography and date boundary: [scope]\nInclude: [primary and authoritative source rules]\nExclude: [source types or conflicts]\n\nReturn a claim matrix with:\n- claim,\n- claim class,\n- source title,\n- direct URL,\n- publisher,\n- date,\n- exact support,\n- limitation,\n- verification status.\n\nDo not present a practitioner report as a general result. Mark every unsupported or conflicting point as unresolved.`,
    economics: "Research margin depends on narrowing the decision, limiting source scope, and pricing verification time. A citation-bearing draft is an intermediate artifact, not the finished product.",
    qualityGate: [
      "Every material claim has an opened and checked source.",
      "Claim class and limitation are visible in the matrix.",
      "Dates match the volatility of the decision.",
      "The buyer receives an editable source matrix and an unresolved-questions register.",
    ],
    redFlags: [
      "The brief cites search snippets, aggregator summaries, or inaccessible pages as if verified.",
      "A direct quote was copied without checking the original page and context.",
      "Self-reported income or time savings are converted into expected results.",
      "The brief gives regulated professional advice without qualified oversight.",
    ],
    practice: {
      title: "Create a five-claim decision brief",
      brief: "Research one non-regulated business decision and build a fully verified source matrix.",
      estimatedMinutes: 60,
      steps: [
        "Write the decision, scope, date boundary, and inclusion rules.",
        "Use Research and Web search to collect candidate evidence.",
        "Choose five material claims and open every cited source.",
        "Record identity, content, fit, currency, limitation, and claim class.",
        "Write a one-page answer plus an unresolved-questions register.",
      ],
      deliverables: [
        "One-page decision brief",
        "Five-row verified claim matrix",
        "Method and uncertainty note",
      ],
      doneWhen: [
        "Another reviewer can reproduce each claim from the linked source.",
        "Every practitioner example is explicitly labeled self-reported and non-representative.",
      ],
      safety: "Choose a low-risk business question for practice. Do not upload confidential search strategy, credentials, or personal data, and do not provide professional advice outside your qualifications.",
    },
    checkpoint: {
      prompt: "Does a working citation link make a claim verified?",
      answer: "No. You must still confirm source identity, relevant content, fit with the wording, and currency for the decision. A link can be real and still fail to support the claim.",
    },
    takeaway: "A paid research brief earns trust by making both support and uncertainty inspectible.",
    figureIds: ["fig-03-tools-menu"],
    sourceIds: ["help-research", "commercial-terms", "aup", "academy-work"],
  },
  {
    slug: "deliver-files-that-survive-review",
    order: 7,
    unitId: "systemize-value",
    minutes: 70,
    title: "Deliver files that survive review",
    kicker: "Lesson 07 · Professional artifacts",
    summary: "Match the file format to the buyer's next action, preserve editable structure, and verify calculations, layout, sources, and network boundaries.",
    objective: "Produce a client handoff pack that remains useful after Claude and the provider leave the room.",
    sections: [
      {
        heading: "Choose the format from the next action",
        paragraphs: [
          "A spreadsheet should expose formulas and assumptions. A document should remain editable and use real heading structure. A presentation should have a clear narrative and readable charts. A PDF can preserve a fixed view, but it should not be the only handoff when the client needs to update the work.",
          "The observed Claude Desktop dialog describes spreadsheet, PDF, presentation, and document output examples. The same dialog warns that limited network access increases security risk. Treat output format and external access as two parts of the delivery decision.",
        ],
        claimClass: "verified-capability",
        sourceIds: ["academy-work"],
      },
      {
        heading: "Audit the file, not the conversation",
        paragraphs: [
          "A polished preview can hide broken formulas, clipped tables, missing fonts, stale citations, inaccessible color choices, or an empty exported page. Open the actual file in the target application, recalculate, inspect key cells or objects, and render every page or slide at the expected viewing size.",
          "Maintain a source tab or appendix for any material external claim. If a number is hypothetical, label the assumption in the file, not only in the message that created it.",
        ],
        bullets: [
          "Spreadsheet: formulas, units, rounding, source cells, input validation, and error states.",
          "Document: heading hierarchy, editable tables, citations, page breaks, and tracked reviewer decisions.",
          "Slides: narrative order, chart labels, contrast, overflow, speaker notes, and source footers.",
          "PDF: page count, text extraction, links, crop, accessibility, and print rendering.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["commercial-terms"],
      },
      {
        heading: "Package a handoff that can be maintained",
        paragraphs: [
          "Deliver the editable master, an optional fixed export, an input and source manifest, a version and change log, a known-limitations note, and short operating instructions. Remove temporary data, comments, hidden sheets, speaker notes, and metadata that the client did not approve.",
          "If Claude installed packages or used network access, record what ran, which domains were allowed, and what the client must review before rerunning it.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["academy-cowork", "aup"],
      },
    ],
    workflow: [
      "Ask what the buyer will do next with the deliverable.",
      "Choose an editable master format and define the output schema.",
      "Generate or assemble the file from approved inputs.",
      "Open, recalculate, render, and inspect the actual file in its target application.",
      "Deliver the master, export, manifest, change log, limitations, and operating note.",
    ],
    promptTemplate: `Create an editable [XLSX, DOCX, PPTX, or other] deliverable for [audience].\n\nDecision supported: [decision]\nApproved inputs: [manifest]\nRequired structure: [sheets, headings, slides, fields]\nSource behavior: [where every external claim is recorded]\nAccessibility requirements: [contrast, headings, alt text, reading order]\nAcceptance checks: [file-specific tests]\n\nDo not flatten formulas, tables, charts, or text into images. Mark hypothetical inputs visibly. Return a validation checklist with the file.`,
    economics: "Verified file delivery includes generation, application-level inspection, correction, and handoff documentation. Price all four stages, not only generation time.",
    qualityGate: [
      "The editable master opens without repair warnings in the target application.",
      "Calculations, links, citations, charts, and page or slide rendering were inspected.",
      "Assumptions and unresolved items are visible inside the deliverable.",
      "The client receives a manifest, change log, limitation note, and operating instructions.",
    ],
    redFlags: [
      "The only deliverable is a screenshot or flattened PDF.",
      "A spreadsheet number has no inspectible formula or source.",
      "A deck is accepted from the editor preview without rendering every slide.",
      "Network or package access is enabled without a client-approved boundary.",
    ],
    practice: {
      title: "Build and audit a client-ready file pack",
      brief: "Create one editable business deliverable from synthetic data and run a format-specific acceptance test.",
      estimatedMinutes: 55,
      steps: [
        "Choose a buyer action and the best editable file format.",
        "Create a small synthetic input manifest and visible assumption list.",
        "Generate the deliverable and save a versioned master.",
        "Open it in the target application and complete ten format-specific checks.",
        "Correct defects and package the master, export, manifest, change log, and limitations note.",
      ],
      deliverables: [
        "Editable master file",
        "Fixed export if useful",
        "Ten-check QA record",
        "Handoff manifest and limitations note",
      ],
      doneWhen: [
        "A second person can edit the file and locate every assumption and source.",
        "The rendered output has no clipped, blank, broken, or inaccessible content.",
      ],
      safety: "Use synthetic data and remove hidden metadata before sharing. Do not enable external network access for a file task unless the approved source boundary requires it.",
    },
    checkpoint: {
      prompt: "Why is a polished on-screen preview insufficient acceptance evidence?",
      answer: "The actual file can contain broken formulas, inaccessible structure, layout overflow, hidden content, or export defects that the preview does not reveal. Acceptance requires opening and inspecting the deliverable itself.",
    },
    takeaway: "A professional deliverable stays editable, traceable, and useful after handoff.",
    figureIds: ["fig-05-file-outputs"],
    sourceIds: ["academy-work", "academy-cowork", "commercial-terms", "aup"],
  },
  {
    slug: "standardize-with-skills-and-connectors",
    order: 8,
    unitId: "systemize-value",
    minutes: 75,
    title: "Standardize with Skills and least-privilege Connectors",
    kicker: "Lesson 08 · Reusable operations",
    summary: "Package stable know-how as a versioned Skill, connect only approved systems, and test the complete workflow before using it in paid delivery.",
    objective: "Create a reusable operating package with an owner, license review, fixture test, permission map, and rollback path.",
    sections: [
      {
        heading: "Turn repeated corrections into delivery IP",
        paragraphs: [
          "A Skill can package repeatable instructions and resources. The useful asset is the reviewed workflow: definitions, sequence, output schema, examples, error handling, acceptance checks, and domain judgment. A folder of generic prompts is not yet an operating system.",
          "Current official help lists Skills for Free, Pro, Max, Team, and Enterprise, but use requires Code execution and file creation to be enabled. Team and Enterprise access can also depend on organization and administrator settings. Use the Help Center page reviewed on the course date and recheck it before advising a buyer.",
        ],
        claimClass: "current-plan-or-policy",
        sourceIds: ["help-skills", "github-anthropic-skills"],
      },
      {
        heading: "Review authorship, version, and license",
        paragraphs: [
          "The observed Skills settings exposes author and update date, both useful review signals. Record the exact Skill version used for each delivery. Before adapting a public Skill, inspect the license at the specific directory and revision. A repository-level assumption can be wrong when subdirectories use different terms.",
          "Practitioner skill libraries demonstrate how delivery knowledge can become reusable, but their existence does not prove representative client demand or income. Evaluate the workflow against your own buyer and fixtures.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["github-anthropic-skills", "github-marketingskills", "github-claude-marketing"],
      },
      {
        heading: "Map every Connector permission",
        paragraphs: [
          "Connectors can extend Claude with approved external context and actions under the permissions of the connected account. That means the human operator must map data read, data written, external side effects, credential ownership, revocation, logs, and client consent.",
          "Start read-only when possible. Use a dedicated test account and synthetic records. Separate research from action. Require human approval before sending messages, publishing, changing records, making purchases, or touching customer accounts.",
        ],
        claimClass: "verified-capability",
        sourceIds: ["help-connectors", "aup"],
      },
    ],
    workflow: [
      "Collect the stable instructions and repeated correction patterns from three deliveries.",
      "Create a Skill with a version, owner, fixtures, output schema, and rollback note.",
      "Review the license of every borrowed file at the actual directory and revision.",
      "Map each Connector's read, write, and external-action permissions.",
      "Test with synthetic records, then run a supervised pilot and log corrections.",
    ],
    promptTemplate: `Skill review contract\n\nSkill name and version: [name, version]\nOwner: [person]\nBuyer outcome: [outcome]\nAuthorized inputs: [types]\nOutput schema: [schema]\nFixture set: [normal, missing, contradictory, adversarial]\nConnector permission map: [read, write, external action]\nHuman approvals: [actions]\nKnown limitations: [list]\nRollback version: [version]\nLicense evidence: [file and revision]\n\nRun the fixtures and return a discrepancy log. Do not perform an external action during testing.`,
    economics: "Standardization can improve margin when setup and correction time fall across repeated deliveries. Include Skill maintenance, regression testing, Connector administration, and incident response in recurring cost.",
    qualityGate: [
      "The Skill has an owner, version, fixtures, limitation note, and rollback path.",
      "Every borrowed component has directory-level license evidence.",
      "Connector permissions are mapped and minimized.",
      "Synthetic regression tests pass before client data or external actions are allowed.",
    ],
    redFlags: [
      "A public Skill is copied because the repository appears open source, without checking its directory license.",
      "A Connector receives broad write access for a read-only analysis.",
      "The workflow can send, publish, buy, or modify records without human approval.",
      "A Skill update is deployed to client work without fixture comparison.",
    ],
    practice: {
      title: "Package one workflow as a tested Skill spec",
      brief: "Create a Skill package and Connector permission map without connecting a real client system.",
      estimatedMinutes: 60,
      steps: [
        "Choose a workflow repeated in at least three examples or test runs.",
        "Write the Skill instructions, output schema, owner, version, and known limitations.",
        "Create four synthetic fixtures, including one adversarial input.",
        "Draft a permission map for one optional Connector and start read-only.",
        "Run the fixtures, log discrepancies, and publish version 1.1 with a rollback note.",
      ],
      deliverables: [
        "Versioned Skill specification",
        "Four synthetic fixtures",
        "Regression and discrepancy log",
        "Connector permission map",
      ],
      doneWhen: [
        "A second operator can run the fixtures and reproduce the acceptance decision.",
        "No external action or real client data is required to validate the Skill.",
      ],
      safety: "Do not connect a production system for this exercise. Never include credentials, client secrets, copyrighted examples without permission, or hidden external actions in a Skill package.",
    },
    checkpoint: {
      prompt: "Why must a public Skill's license be checked at the directory level?",
      answer: "A repository can contain components under different terms. The license governing one directory or file may differ from the repository's most visible license, so reuse must be supported by evidence at the actual component and revision.",
    },
    takeaway: "A reusable workflow earns its margin through tests, permissions, and maintenance, not through prompt secrecy.",
    figureIds: ["fig-07-skills-settings"],
    sourceIds: [
      "help-skills",
      "help-connectors",
      "github-anthropic-skills",
      "github-marketingskills",
      "github-claude-marketing",
      "aup",
    ],
  },
  {
    slug: "prototype-with-artifacts",
    order: 9,
    unitId: "systemize-value",
    minutes: 70,
    title: "Prototype the buyer's decision with Artifacts",
    kicker: "Lesson 09 · Product discovery",
    summary: "Build a reviewable calculator, dashboard, report, or interaction to test a workflow without confusing publication with a business.",
    objective: "Use an Artifact to learn whether a real user can complete one valuable task and define the evidence required before further investment.",
    sections: [
      {
        heading: "Prototype the decision, not the feature list",
        paragraphs: [
          "Artifacts can make documents, code, web pages, SVG graphics, diagrams, React components, and some AI-powered apps reviewable inside Claude. Current official help says Code execution and file creation must be enabled for Artifacts to work. Start with one user, one input, one transformation, and one decision.",
          "A calculator that exposes assumptions can test pricing logic. A dashboard can test whether a manager notices the right exception. A report builder can test a recurring handoff. The prototype should answer a learning question, not display every possible feature.",
        ],
        claimClass: "verified-capability",
        sourceIds: ["help-artifacts"],
      },
      {
        heading: "Publishing is not distribution or payment",
        paragraphs: [
          "Official help describes ways to iterate, download, and publish Artifacts, with options that can vary by plan and current product behavior. Publishing does not create a marketplace listing, customer acquisition channel, checkout system, support process, privacy program, or production service-level commitment.",
          "Use a published or shared Artifact as a test surface only when its data and access model are appropriate. Do not place secrets, customer data, or unlicensed content in a public prototype.",
        ],
        claimClass: "verified-capability",
        sourceIds: ["help-artifacts", "commercial-terms", "aup"],
      },
      {
        heading: "Observe behavior and decide what not to build",
        paragraphs: [
          "Give five target users a task without coaching. Record whether they can start, understand the input, complete the workflow, interpret the result, and identify the next action. Capture errors and workarounds. Ask what they would replace, not whether the design looks good.",
          "Advance only if the prototype resolves a repeated problem and users commit to a stronger next step. Otherwise revise the workflow or stop. Code is cheaper than maintaining the wrong product.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["github-shotgun-case", "github-open-saas"],
      },
    ],
    workflow: [
      "Write one user task and the decision the prototype must support.",
      "Ask three discovery questions before requesting an Artifact.",
      "Build one input-to-decision path with synthetic data and visible assumptions.",
      "Observe five target users attempting the task without coaching.",
      "Choose advance, revise, or stop using a prewritten evidence threshold.",
    ],
    promptTemplate: `I need a reviewable Artifact prototype, not a production product.\n\nTarget user: [role]\nTask: [single task]\nDecision after using it: [decision]\nInput: [synthetic input]\nTransformation: [rule or process]\nOutput: [result]\nAssumptions to expose: [list]\nAccessibility requirements: [list]\n\nFirst ask me three questions about the user's current workflow. Then propose the smallest testable interaction. Do not add authentication, payment, integrations, or unrelated features.`,
    economics: "Prototype return = value of a faster evidence decision - build and test cost. Do not count hypothetical future revenue as prototype return.",
    qualityGate: [
      "The Artifact supports one named user task and decision.",
      "All data is synthetic or approved for the prototype's access level.",
      "Assumptions and limitations are visible inside the experience.",
      "Five users are observed against a prewritten advance threshold.",
    ],
    redFlags: [
      "A published URL is treated as proof of distribution or demand.",
      "The prototype collects personal, client, payment, or secret data.",
      "Positive design comments replace task-completion evidence.",
      "The team begins authentication, billing, or integrations before validating the core task.",
    ],
    practice: {
      title: "Run a five-user Artifact test",
      brief: "Build the smallest Artifact that supports one business decision and observe real task behavior.",
      estimatedMinutes: 75,
      steps: [
        "Write the target user, task, decision, synthetic input, and evidence threshold.",
        "Ask Claude to question the workflow before building.",
        "Create one accessible input-to-output path with visible assumptions.",
        "Observe five target users without coaching and record behavior.",
        "Write an advance, revise, or stop memo with the evidence.",
      ],
      deliverables: [
        "Artifact prototype using synthetic data",
        "Five-session observation log",
        "Advance, revise, or stop memo",
      ],
      doneWhen: [
        "Users can attempt the task without receiving an explanation from the creator.",
        "The decision memo uses behavior and commitments, not visual preference alone.",
      ],
      safety: "Use synthetic inputs and a low-risk workflow. Do not publish client data, personal data, credentials, payment details, or unlicensed media in an Artifact.",
    },
    checkpoint: {
      prompt: "What does publishing an Artifact prove?",
      answer: "It proves that a shareable prototype exists in that observed product context. It does not prove demand, payment, security, reliability, support readiness, or representative business results.",
    },
    takeaway: "A good prototype buys evidence about a decision before you buy complexity.",
    figureIds: ["fig-06-artifact-workspace"],
    sourceIds: ["help-artifacts", "commercial-terms", "aup", "github-shotgun-case", "github-open-saas"],
  },
  {
    slug: "build-software-with-claude",
    order: 10,
    unitId: "sell-responsibly",
    minutes: 95,
    title: "Build software only after the workflow earns it",
    kicker: "Lesson 10 · Claude Code and API economics",
    summary: "Convert validated workflow evidence into a tested software slice, keep a human-owned repository contract, and model unit cost before scaling.",
    objective: "Plan and verify one narrow software slice with tests, security boundaries, observability, and a current-price unit-economics worksheet.",
    sections: [
      {
        heading: "Research the repository and the workflow first",
        paragraphs: [
          "Claude Code can assist with software work, but the first task is not write the app. Document the validated user task, inspect the repository and architecture, identify existing patterns, and write the smallest acceptance-tested change. A mature SaaS template can accelerate infrastructure, but a payment button is not proof of demand, security, or operational readiness.",
          "Use a plan file, a bounded branch or worktree, small diffs, and explicit commands for tests and review. Preserve a durable task brief and result log so another operator can resume the work without guessing.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["academy-code-101", "github-open-saas"],
      },
      {
        heading: "Autonomy changes the permission question",
        paragraphs: [
          "Anthropic announced that, starting 2026-08-14, new Claude Code sessions on Pro, Max, and Team plans default to Auto mode unless a user or organization has configured another default. A current default is not a permanent fact, blanket authorization, or permission to skip review. Repository boundaries, credentials, external services, destructive commands, and production deployment still require human ownership.",
          "Treat generated billing, authentication, authorization, migrations, and destructive operations as high-risk changes. One practitioner reports that a customer was billed three times for a total of $240 and attributes the defect to billing code written with Claude Code. The available post text does not identify the payment provider or establish a refund outcome. This self-report is not a failure-rate estimate.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["blog-auto-mode", "x-elvissun", "commercial-terms"],
      },
      {
        heading: "Model API cost per accepted outcome",
        paragraphs: [
          "If a product calls the Claude API, measure the cost of an accepted outcome, not only one request. Include input and output tokens, retries, tools, retrieval, storage, observability, moderation, failed runs, and human escalation. Add latency and quality thresholds beside cost.",
          "Official documentation describes model selection, prompt caching, token discipline, batch processing, and spend controls as cost levers. As reviewed on 2026-08-23, the Batch API offers 50% off eligible token usage in exchange for results that may arrive within 24 hours. That is not a 50% reduction in total business cost or evidence of higher profit. Exact models, prices, discounts, and limits change, so pull current official pricing into a dated worksheet at decision time.",
        ],
        bullets: [
          "Cost per accepted outcome = total variable run cost divided by accepted outcomes.",
          "Gross contribution = collected revenue minus variable delivery and support cost.",
          "Quality guardrail = acceptance rate, material-error rate, escalation rate, and refund rate.",
        ],
        claimClass: "verified-capability",
        sourceIds: ["docs-cost"],
      },
      {
        heading: "Ship a narrow slice with an incident path",
        paragraphs: [
          "Release one validated path behind explicit limits. Log model and prompt version, input class, cost, latency, tool actions, review result, and user-visible error. Set spend limits and a kill switch. Define who responds when output is wrong or an external action misfires.",
          "Do not call the slice production-ready until security review, privacy review, accessibility, backup and rollback, billing tests, and failure-state tests match its actual risk.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["docs-cost", "commercial-terms", "aup"],
      },
    ],
    workflow: [
      "Convert validated user behavior into one acceptance-tested software slice.",
      "Research the repository and write a plan before changing code.",
      "Implement in a bounded branch or worktree with tests and human review.",
      "Build a dated unit-economics model from current official pricing and measured runs.",
      "Release behind spend limits, logs, rollback, and an incident owner.",
    ],
    promptTemplate: `Software task contract\n\nValidated user task: [task and evidence]\nRepository boundary: [directories and exclusions]\nSmallest release slice: [one path]\nAcceptance tests: [behavior, failure, security, accessibility]\nCommands allowed: [read, edit, test]\nCommands requiring approval: [install, migrate, external, destructive, deploy]\nSecrets rule: never print, copy, or commit secrets.\nUnit metrics: [accepted outcome, cost, latency, escalation]\nRollback: [method and owner]\n\nFirst inspect the repository and propose a plan with evidence. Do not edit until the plan names files, tests, risks, and assumptions.`,
    economics: "Cost per accepted outcome = model + tool + retrieval + retry + observability + support + human-escalation cost, divided by accepted outcomes. Recalculate from measured runs and current official prices.",
    qualityGate: [
      "The software slice maps to validated user behavior and one acceptance decision.",
      "Repository scope, secrets, external actions, and destructive commands have explicit boundaries.",
      "Tests cover normal, missing, adversarial, billing, and failure behavior appropriate to risk.",
      "Unit economics use current dated prices, measured run data, and accepted outcomes.",
      "Spend limit, logs, rollback, and incident ownership exist before release.",
    ],
    redFlags: [
      "The product begins with authentication, billing, and integrations before validating the core task.",
      "Generated tests merely copy the implementation's assumptions.",
      "A successful demo is treated as security or production evidence.",
      "Revenue is shown without model, support, acquisition, refund, and review costs.",
      "Production secrets or customer data appear in prompts, logs, fixtures, or commits.",
    ],
    practice: {
      title: "Specify and cost one software slice",
      brief: "Create a repository-ready task contract and a measured unit-economics worksheet. Implementation is optional; acceptance evidence is required.",
      estimatedMinutes: 90,
      steps: [
        "Choose one workflow step already supported by user evidence.",
        "Write the repository boundary, behavior tests, risk tests, approval rules, and rollback.",
        "If you implement, use a bounded branch and preserve the plan, diff, and test output.",
        "Run at least ten representative synthetic cases and record cost, latency, acceptance, retry, and escalation.",
        "Build low, likely, and high unit-economics scenarios using a dated official-price input.",
      ],
      deliverables: [
        "Software task contract",
        "Test and review record",
        "Ten-run measurement table",
        "Dated unit-economics worksheet",
        "Release and rollback checklist",
      ],
      doneWhen: [
        "The acceptance result can be reproduced without trusting the demo.",
        "The high-cost scenario has an explicit response, such as a limit, price revision, model change, or stop decision.",
      ],
      safety: "Use synthetic data and a non-production environment. Do not use real credentials, charge a payment method, contact external users, deploy, or run a destructive migration for this exercise.",
    },
    checkpoint: {
      prompt: "Why should API cost be measured per accepted outcome instead of per request?",
      answer: "A useful outcome can require retries, tools, retrieval, failed runs, moderation, and human escalation. Per-request cost hides the variable work required to deliver an accepted result.",
    },
    takeaway: "Claude can accelerate software work, but demand, tests, security, and unit economics decide whether the software deserves to exist.",
    figureIds: [],
    sourceIds: [
      "academy-code-101",
      "blog-auto-mode",
      "docs-cost",
      "commercial-terms",
      "aup",
      "github-open-saas",
      "github-lastsaas",
      "x-elvissun",
    ],
  },
  {
    slug: "earn-trust-and-retainers",
    order: 11,
    unitId: "sell-responsibly",
    minutes: 65,
    title: "Earn trust, proof, and recurring work",
    kicker: "Lesson 11 · Ethical sales and retention",
    summary: "Sell with inspectible samples and measured case evidence, avoid spam and inflated screenshots, and make recurring work depend on recurring value.",
    objective: "Create a truthful proof pack and a retention review that distinguishes revenue, profit, time saved, quality, and buyer outcomes.",
    sections: [
      {
        heading: "Build a proof ladder",
        paragraphs: [
          "Begin with what can be inspected: a synthetic sample, method, source matrix, acceptance checklist, before-and-after process measure, and client-approved case evidence. Move from artifact proof to process proof to outcome proof only when measurement supports the step.",
          "A repository shows what exists. A finished Remotion animation shows an output. A social post shows what an author reports. None of these alone establishes profit, representative time savings, or repeatable demand. The cited Remotion post does not itself establish any Claude contribution, so attribute only what its public text supports.",
        ],
        bullets: [
          "Artifact proof: the deliverable can be opened and inspected.",
          "Process proof: the workflow, controls, and acceptance record can be reproduced.",
          "Outcome proof: a buyer-approved baseline and follow-up measure show a relevant change.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["github-lastsaas", "x-wcandillon", "x-codyschneider"],
      },
      {
        heading: "Sell to a fit signal, not a scraped list",
        paragraphs: [
          "Use warm introductions, permission-based research, communities where offers are allowed, partner channels, and tailored outreach to a small number of clearly relevant buyers. Reference an observable workflow signal and offer a bounded sample or question, not an automated claim about their business.",
          "Anthropic's Usage Policy prohibits deceptive and abusive uses. X automation rules restrict spammy, duplicative, unsolicited, and unauthorized automation, and currently require prior written and explicit X approval to deploy or operate an AI reply bot. Platform evasion, fake personas, mass AI replies, and fabricated testimonials are not growth tactics for this course.",
        ],
        claimClass: "current-plan-or-policy",
        sourceIds: ["aup", "x-automation-policy"],
      },
      {
        heading: "Retainers renew for recurring decisions",
        paragraphs: [
          "A retainer should have a recurring trigger, defined decision, input owner, delivery calendar, service level, acceptance measure, and quarterly stop or redesign review. Do not convert a one-time setup into a vague monthly AI fee.",
          "At each review, show volume, accepted outputs, correction rate, turnaround, cost, buyer use, incidents, and unresolved constraints. Revenue is not profit. Time saved is not customer value unless the saved capacity changes a decision or outcome the buyer cares about.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["github-seo-audit", "docs-cost"],
      },
    ],
    workflow: [
      "Create a synthetic sample and expose its method and acceptance checklist.",
      "Write a claim ledger that separates facts, practitioner reports, inference, and hypotheticals.",
      "Ask a small number of fit-qualified buyers for permission to inspect the sample.",
      "For recurring work, define the trigger, calendar, inputs, service level, and stop review.",
      "Report revenue, cost, acceptance, correction, and buyer-use measures separately.",
    ],
    promptTemplate: `Audit this sales or case-study draft for evidence quality.\n\n[DRAFT]\n\nFor every claim, return:\n- exact claim,\n- class: verified fact, client-approved measurement, practitioner report, inference, or hypothetical,\n- source or baseline,\n- missing cost or denominator,\n- risk of misleading a buyer,\n- narrower accurate wording.\n\nReject guaranteed income, unverifiable superlatives, fabricated testimonials, undisclosed AI personas, spam tactics, and projections presented as achieved results.`,
    economics: "Recurring contribution = collected recurring fee - recurring model and tool cost - operator and support time - acquisition allocation - refund and incident cost. Report it separately from gross revenue.",
    qualityGate: [
      "Every public claim has a class, source, denominator, period, and limitation.",
      "Client evidence has explicit permission for the named use and wording.",
      "Outreach is fit-qualified, truthful, and compliant with current platform rules.",
      "The retainer has a recurring decision, service level, measures, and stop review.",
    ],
    redFlags: [
      "A revenue screenshot omits costs, time period, refunds, and acquisition context.",
      "A creator's projected total is presented as an expected monthly result.",
      "Outreach uses scraped personal data, fake accounts, evasive proxies, or unsolicited automated replies.",
      "A retainer renews because the workflow runs, even though the buyer does not use the output.",
    ],
    practice: {
      title: "Publish a truthful proof pack",
      brief: "Create an evidence-bounded sample, case-study skeleton, and permission-based outreach sequence.",
      estimatedMinutes: 50,
      steps: [
        "Choose one synthetic or client-approved deliverable and expose its acceptance checklist.",
        "Create a claim ledger with evidence class and limitation for every statement.",
        "Draft a one-page case-study skeleton with blanks for unmeasured outcomes.",
        "Write three tailored permission-based messages for known fit signals.",
        "Design a quarterly retainer review with contribution, quality, use, and stop measures.",
      ],
      deliverables: [
        "Inspectable sample and acceptance checklist",
        "Claim ledger",
        "Evidence-bounded case-study skeleton",
        "Three fit-qualified outreach drafts",
        "Retainer review scorecard",
      ],
      doneWhen: [
        "No claim implies guaranteed income or representative results.",
        "A skeptical buyer can identify what is measured, self-reported, inferred, and still unknown.",
      ],
      safety: "Do not contact anyone as part of the exercise without permission. Never fabricate a testimonial, identity, result, or affiliation, and never reproduce a social-media image without rights clearance.",
    },
    checkpoint: {
      prompt: "Why is a public finished artifact weaker proof than a client-approved before-and-after measure?",
      answer: "The artifact proves that an output exists. A well-designed before-and-after measure can show whether the buyer's relevant process or outcome changed, provided the baseline, period, denominator, and limitations are disclosed.",
    },
    takeaway: "Trust compounds when every proof claim is narrower than the evidence, not larger than it.",
    figureIds: [],
    sourceIds: [
      "aup",
      "x-automation-policy",
      "github-seo-audit",
      "github-lastsaas",
      "x-codyschneider",
      "x-wcandillon",
      "docs-cost",
    ],
  },
  {
    slug: "capstone-seven-day-demand-test",
    order: 12,
    unitId: "sell-responsibly",
    minutes: 120,
    title: "Capstone: run a seven-day demand test",
    kicker: "Lesson 12 · Evidence before scale",
    summary: "Assemble the course artifacts into one ethical demand experiment and make a documented go, revise, or stop decision.",
    objective: "Complete a buyer-evidence sprint with an offer, sample, verification trail, economics, outreach review, and decision rubric.",
    sections: [
      {
        heading: "Define the experiment before Day 1",
        paragraphs: [
          "Choose a low-risk problem you can independently evaluate. Freeze the buyer, trigger, sample, evidence threshold, budget, privacy boundary, and stop rule before contacting anyone. A valid result can be stop. Protecting a week from an unsupported idea is a useful outcome.",
          "Do not set an income target. Set behavioral thresholds such as completed interviews, sample reviews, pilot-scoping conversations, and explicit declines. Record the denominator so silence does not disappear from the story.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["academy-work", "aup"],
      },
      {
        heading: "Run the seven-day sequence",
        paragraphs: [
          "Day 1 defines the thesis and source boundary. Day 2 collects problem evidence. Day 3 creates the scoped sample and acceptance checks. Day 4 tests and corrects the workflow. Day 5 asks fit-qualified people for permission to review. Day 6 records behavior and economics. Day 7 audits the evidence and decides go, revise, or stop.",
          "Use Claude for structured notes, drafts, source matrices, test fixtures, and prototype iteration. Keep the human operator responsible for consent, source verification, quality, outreach, pricing, and the final decision.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["docs-prompting", "commercial-terms", "help-research"],
      },
      {
        heading: "Score evidence, quality, economics, and integrity",
        paragraphs: [
          "A go decision requires more than interest. Score buyer evidence, delivery acceptance, operator fit, unit economics, privacy and policy compliance, and the next paid commitment. A revise decision names one testable change. A stop decision archives the evidence and prevents sunk-cost storytelling.",
          "The final portfolio should make limitations easy to find. Include the source and claim ledger, practitioner caveats, captured-interface observation dates, client-data boundary, and no-guaranteed-income notice.",
        ],
        bullets: [
          "Go: strong recent problem evidence, accepted sample, viable cost range, compliant route, and a concrete paid next step.",
          "Revise: one major assumption remains testable within a bounded second experiment.",
          "Stop: weak pain, inaccessible buyer, unsafe workflow, failed acceptance, or impossible economics.",
        ],
        claimClass: "course-synthesis",
        sourceIds: ["docs-cost", "commercial-terms", "aup"],
      },
    ],
    workflow: [
      "Freeze the thesis, evidence threshold, budget, data boundary, and stop rule.",
      "Collect recent buyer evidence and preserve facts, quotes, inferences, and declines.",
      "Build a bounded sample with a delivery spec and independent acceptance check.",
      "Request permission-based review from a small fit-qualified group.",
      "Audit evidence, economics, quality, policy, and rights, then decide go, revise, or stop.",
    ],
    promptTemplate: `Capstone decision audit\n\nBuyer and trigger: [definition]\nProblem evidence: [facts and denominator]\nSample and acceptance result: [links or record]\nReview behavior: [accepted, revised, declined, silent]\nPrice and cost scenarios: [assumptions]\nPrivacy, policy, and rights review: [status]\nUnresolved risks: [list]\nPrewritten threshold and stop rule: [rules]\n\nReturn a decision table for go, revise, or stop. Cite only the evidence supplied. Treat silence and declines as data. Do not convert interest into revenue or project future income.`,
    economics: "Capstone decision = buyer evidence + accepted delivery + viable contribution range + compliant operating path. A single missing critical condition can justify revise or stop.",
    qualityGate: [
      "The thesis and thresholds were written before the result was known.",
      "The evidence log includes the full denominator, silence, declines, and corrections.",
      "The sample passes a documented acceptance check and uses approved data.",
      "The cost model includes review, acquisition, support, tools, refunds, and risk allowance.",
      "Sources, interface dates, rights, privacy, policy, and practitioner caveats are visible.",
      "The final decision is go, revise, or stop with a named reason and next action.",
    ],
    redFlags: [
      "The threshold is rewritten after seeing weak results.",
      "Likes, views, or compliments are counted as paid demand.",
      "A sample is sent as finished client work without acceptance review.",
      "The experiment uses automated spam, fake proof, unlicensed screenshots, or private data.",
      "The decision reports revenue without profit, denominator, time period, or uncertainty.",
    ],
    practice: {
      title: "Complete the Course 12 evidence portfolio",
      brief: "Run the seven-day demand test or a fully simulated version using synthetic data and real, consented interviews. Submit the audit packet, not a revenue claim.",
      estimatedMinutes: 120,
      steps: [
        "Day 1: freeze the buyer thesis, thresholds, budget, source rules, data boundary, and stop rule.",
        "Day 2: collect at least five recent-problem interviews or document why recruitment failed.",
        "Day 3: create the two-page scope, delivery spec, and bounded sample.",
        "Day 4: test normal and adversarial fixtures, correct the sample, and log changes.",
        "Day 5: request permission-based review from at least five fit-qualified people.",
        "Day 6: record review behavior, cost, quality, corrections, and any concrete next step.",
        "Day 7: complete the source, rights, privacy, policy, and economics audit, then decide go, revise, or stop.",
      ],
      deliverables: [
        "One-page money thesis and stop rule",
        "De-identified customer-evidence matrix with denominator",
        "Two-page scope and cost scenarios",
        "Versioned delivery spec and fixtures",
        "Inspectable sample and acceptance record",
        "Permission-based outreach log",
        "Source and claim ledger",
        "Rights, privacy, policy, and unit-economics audit",
        "Go, revise, or stop memo",
      ],
      doneWhen: [
        "Every score in the rubric points to a portfolio artifact.",
        "A skeptical reviewer can reproduce the decision without trusting an income claim.",
        "The decision preserves negative evidence and unresolved risks.",
      ],
      safety: "Use only consented interviews, synthetic or approved data, and permission-based outreach. Do not contact scraped lists, automate replies, give regulated advice, publish client material, or claim an outcome you did not measure.",
    },
    checkpoint: {
      prompt: "Can a stop decision receive a high capstone score?",
      answer: "Yes. The capstone evaluates evidence quality, delivery controls, economics, integrity, and decision discipline. A well-supported stop decision can demonstrate stronger judgment than an unsupported launch.",
    },
    takeaway: "The course ends when evidence chooses the next move, including the courage to stop.",
    figureIds: ["fig-03-tools-menu", "fig-06-artifact-workspace"],
    sourceIds: [
      "academy-work",
      "docs-prompting",
      "help-research",
      "docs-cost",
      "commercial-terms",
      "aup",
      "x-automation-policy",
    ],
  },
] as const satisfies readonly ClaudeIncomeLesson[];

export const CLAUDE_INCOME_COURSE: ClaudeIncomeCourse = {
  id: "claude-income",
  displayNumber: 12,
  version: "1.0.1",
  researchedOn: "2026-08-23",
  reviewedOn: "2026-08-24",
  contentLanguage: "en",
  title: "How to Make Money with Claude",
  shortTitle: "Claude Income",
  summary: "Build useful Claude-assisted offers, validate demand, deliver with evidence, control costs, and earn trust without hype or guaranteed-income claims.",
  audience: "Independent professionals, agency operators, consultants, creators, and product builders who can independently judge the quality of at least one business workflow.",
  prerequisite: "Basic Claude familiarity, one domain skill you can verify, and access to potential users for ethical customer discovery. A paid Claude plan is not required for every lesson.",
  disclaimer: "This course teaches practical ways to use Claude in services, workflows, software, and product experiments. It does not promise income or business success. Results depend on your expertise, market demand, sales, execution, quality control, costs, and compliance with applicable terms and law. Verify Claude's outputs before using or selling them.",
  practitionerDisclaimer: "Practitioner examples are attributed, self-reported, and not representative outcome evidence. Revenue screenshots, follower reactions, and projected totals are not audits of profit or repeatable demand.",
  independentProjectNotice: "Claude and Anthropic are trademarks of Anthropic PBC. aicourse.top is an independent educational project. It is not affiliated with, sponsored by, or endorsed by Anthropic. Claude names and the underlying interface remain associated with their respective rights holders and are shown for identification and instruction. Interface details can change after the stated observation date.",
  units: CLAUDE_INCOME_UNITS,
  lessons: CLAUDE_INCOME_LESSONS,
};
