import type { ClaudeIncomeQuizQuestion } from "./types";

export const CLAUDE_INCOME_QUIZ_BANK = [
  {
    id: "q01-path",
    unitId: "prove-value",
    lessonSlug: "choose-a-money-path",
    prompt: "A designer can verify sales-deck quality but has no evidence that buyers want a self-service app. What is the strongest first money path?",
    options: [
      "Build a full SaaS with billing before speaking to buyers",
      "Offer a bounded, reviewed deck service and study repeated workflow needs",
      "Sell access to a secret Claude prompt",
      "Project monthly revenue from one creator post",
    ],
    correctIndex: 1,
    explanation: "A bounded service reaches buyer evidence quickly and uses the designer's verification skill. Software should follow repeated demand and stable acceptance criteria.",
    sourceIds: ["academy-work", "github-shotgun-case"],
  },
  {
    id: "q02-thesis",
    unitId: "prove-value",
    lessonSlug: "choose-a-money-path",
    prompt: "Which statement is a falsifiable money thesis?",
    options: [
      "AI automation is the future",
      "Claude will create passive income",
      "At least one of five operations leads with a recent board-report delay will scope a paid pilot after reviewing a sample",
      "Businesses need content",
    ],
    correctIndex: 2,
    explanation: "The statement names a buyer, recent problem, sample, denominator, behavior, and testable threshold.",
    sourceIds: ["github-shotgun-case"],
    critical: true,
  },
  {
    id: "q03-demand",
    unitId: "prove-value",
    lessonSlug: "validate-paid-demand",
    prompt: "Which is the strongest demand evidence?",
    options: [
      "A post receives 500 likes",
      "A friend says the idea is clever",
      "A relevant buyer signs a bounded paid-pilot scope",
      "Claude says the market is large",
    ],
    correctIndex: 2,
    explanation: "A paid pilot creates a concrete commercial commitment. Likes and compliments are useful for reach, not proof of willingness to pay.",
    sourceIds: ["github-shotgun-case"],
  },
  {
    id: "q04-interview",
    unitId: "prove-value",
    lessonSlug: "validate-paid-demand",
    prompt: "Which interview question is least likely to create hypothetical agreement?",
    options: [
      "Would you buy an AI tool for this?",
      "How useful would automation be?",
      "Tell me about the last time this workflow failed and what happened next",
      "Would a dashboard save you money?",
    ],
    correctIndex: 2,
    explanation: "A recent concrete event reveals the actual sequence, consequence, workaround, and owner.",
    sourceIds: ["academy-work"],
  },
  {
    id: "q05-floor",
    unitId: "prove-value",
    lessonSlug: "scope-and-price-the-offer",
    prompt: "Which cost belongs in a Claude-assisted offer's price floor?",
    options: [
      "Only the subscription fee",
      "Only first-draft generation time",
      "Review, revisions, acquisition, tools, delivery, overhead, and risk allowance",
      "A competitor's unverified revenue claim",
    ],
    correctIndex: 2,
    explanation: "The provider must cover the full delivery system, including human review and realistic correction risk.",
    sourceIds: ["docs-cost"],
  },
  {
    id: "q06-scope",
    unitId: "prove-value",
    lessonSlug: "scope-and-price-the-offer",
    prompt: "A client doubles the data volume and adds a presentation after signing. What is the professional response?",
    options: [
      "Absorb it silently to protect the relationship",
      "Ask Claude to work faster",
      "Issue a change note covering price, timing, risk, and approval",
      "Deliver the original work and ignore the request",
    ],
    correctIndex: 2,
    explanation: "Change control makes new scope explicit and protects both buyer and provider from hidden tradeoffs.",
    sourceIds: ["commercial-terms"],
  },
  {
    id: "q07-spec",
    unitId: "deliver-value",
    lessonSlug: "write-a-delivery-spec",
    prompt: "What belongs in the stable layer of a delivery spec?",
    options: [
      "A client's confidential source documents",
      "Process, definitions, output schema, error behavior, and acceptance checks",
      "An unverifiable request to be accurate",
      "The final price and payment credentials",
    ],
    correctIndex: 1,
    explanation: "Stable instructions define the repeatable workflow. Client-specific inputs belong in a separate case layer.",
    sourceIds: ["docs-prompting"],
  },
  {
    id: "q08-verification",
    unitId: "deliver-value",
    lessonSlug: "write-a-delivery-spec",
    prompt: "Why should generation and acceptance be separate?",
    options: [
      "It makes the prompt longer",
      "A response should not be the only judge of its own unsupported assumptions",
      "It guarantees originality",
      "It removes the need for domain expertise",
    ],
    correctIndex: 1,
    explanation: "Independent review checks the output against inputs and acceptance criteria instead of trusting fluency or self-assessment.",
    sourceIds: ["commercial-terms"],
    critical: true,
  },
  {
    id: "q09-project",
    unitId: "deliver-value",
    lessonSlug: "run-client-projects",
    prompt: "Which Project setup best limits cross-client leakage?",
    options: [
      "One agency-wide Project containing every client's files",
      "One Project per client outcome with an approved input manifest",
      "A shared desktop folder with all engagements",
      "A public Skill containing client examples",
    ],
    correctIndex: 1,
    explanation: "Outcome-bounded Projects and input manifests make context, handoff, and deletion easier to inspect.",
    sourceIds: ["help-projects", "academy-cowork"],
  },
  {
    id: "q10-folder",
    unitId: "deliver-value",
    lessonSlug: "run-client-projects",
    prompt: "Which folder should Cowork receive for a client pilot?",
    options: [
      "The user's home directory",
      "A multi-client archive",
      "A dedicated engagement folder containing approved copies and a manifest",
      "Any folder if the model is trusted",
    ],
    correctIndex: 2,
    explanation: "A dedicated folder enforces the smallest practical data boundary and preserves an audit of approved inputs.",
    sourceIds: ["academy-cowork", "aup"],
    critical: true,
  },
  {
    id: "q11-citation",
    unitId: "deliver-value",
    lessonSlug: "sell-citation-grade-research",
    prompt: "A citation link opens successfully. What must happen before the claim is accepted?",
    options: [
      "Nothing, because the link works",
      "Check publisher identity, content, claim fit, date, and limitations",
      "Ask Claude whether the citation is credible",
      "Count the number of sources",
    ],
    correctIndex: 1,
    explanation: "A real link can still be irrelevant, outdated, or too narrow for the wording of the claim.",
    sourceIds: ["help-research", "commercial-terms"],
  },
  {
    id: "q12-practitioner",
    unitId: "deliver-value",
    lessonSlug: "sell-citation-grade-research",
    prompt: "What can an X post about a creator's workflow directly support?",
    options: [
      "Expected earnings for all learners",
      "A general causal claim about productivity",
      "That the named author publicly reported that workflow, with stated limitations",
      "A guarantee that the workflow complies with every platform rule",
    ],
    correctIndex: 2,
    explanation: "A practitioner post supports an attributed report. It is not representative outcome evidence.",
    sourceIds: ["x-codyschneider"],
  },
  {
    id: "q13-file",
    unitId: "systemize-value",
    lessonSlug: "deliver-files-that-survive-review",
    prompt: "A client must update calculations monthly. Which primary handoff is strongest?",
    options: [
      "A screenshot of the table",
      "A flattened PDF only",
      "An editable spreadsheet with formulas, sources, assumptions, and QA record",
      "A chat transcript containing the numbers",
    ],
    correctIndex: 2,
    explanation: "The editable file lets the client inspect and maintain calculations while preserving source and assumption context.",
    sourceIds: ["academy-work"],
  },
  {
    id: "q14-render",
    unitId: "systemize-value",
    lessonSlug: "deliver-files-that-survive-review",
    prompt: "Why render every slide or page before delivery?",
    options: [
      "Rendering proves every claim is true",
      "The editor preview can hide overflow, blank output, broken links, or accessibility defects",
      "Rendering removes the need for an editable master",
      "It reduces acquisition cost",
    ],
    correctIndex: 1,
    explanation: "The actual output can fail differently from the authoring view, so acceptance includes target-format inspection.",
    sourceIds: ["commercial-terms"],
  },
  {
    id: "q15-skill",
    unitId: "systemize-value",
    lessonSlug: "standardize-with-skills-and-connectors",
    prompt: "What makes a custom Skill ready for supervised paid delivery?",
    options: [
      "A memorable name",
      "Many instructions but no test data",
      "An owner, version, fixtures, acceptance checks, limitations, and rollback",
      "A creator's follower count",
    ],
    correctIndex: 2,
    explanation: "Operational readiness comes from ownership, repeatable tests, known limits, and recovery, not from prompt volume.",
    sourceIds: ["help-skills", "github-anthropic-skills"],
  },
  {
    id: "q16-connector",
    unitId: "systemize-value",
    lessonSlug: "standardize-with-skills-and-connectors",
    prompt: "A workflow only needs to read approved CRM records. Which Connector setup is strongest?",
    options: [
      "Full administrator access",
      "Read-only access to the minimum records, tested with synthetic data",
      "A shared employee credential",
      "Write access in case it becomes useful later",
    ],
    correctIndex: 1,
    explanation: "Least privilege limits the effect of mistakes and makes the authorization match the scoped task.",
    sourceIds: ["help-connectors", "aup"],
    critical: true,
  },
  {
    id: "q17-artifact",
    unitId: "systemize-value",
    lessonSlug: "prototype-with-artifacts",
    prompt: "What does a published Artifact establish?",
    options: [
      "That a shareable prototype exists in the observed product context",
      "That customers will pay",
      "That payment and support are production-ready",
      "That the interface is secure for client secrets",
    ],
    correctIndex: 0,
    explanation: "Publishing makes a prototype shareable. It does not establish demand, payment, security, reliability, or support readiness.",
    sourceIds: ["help-artifacts"],
  },
  {
    id: "q18-prototype",
    unitId: "systemize-value",
    lessonSlug: "prototype-with-artifacts",
    prompt: "Which test gives the strongest product evidence?",
    options: [
      "The creator explains every step while users click",
      "Five target users attempt one defined task without coaching and behavior is recorded",
      "The team votes on visual preference",
      "Claude generates more features",
    ],
    correctIndex: 1,
    explanation: "Uncoached task behavior reveals whether the workflow can be understood and completed by the intended user.",
    sourceIds: ["github-shotgun-case"],
  },
  {
    id: "q19-code",
    unitId: "sell-responsibly",
    lessonSlug: "build-software-with-claude",
    prompt: "What should Claude Code do first in an unfamiliar repository?",
    options: [
      "Install dependencies and rewrite the architecture",
      "Deploy a demo",
      "Inspect the repository, identify patterns, and propose a bounded plan with tests",
      "Add billing because every product needs it",
    ],
    correctIndex: 2,
    explanation: "Repository research and a bounded task contract reduce unintended changes and align tests to the validated workflow.",
    sourceIds: ["academy-code-101"],
  },
  {
    id: "q20-unit-cost",
    unitId: "sell-responsibly",
    lessonSlug: "build-software-with-claude",
    prompt: "Which denominator best supports API unit economics?",
    options: [
      "Number of requests sent",
      "Number of accepted outcomes delivered",
      "Number of tokens in one successful demo",
      "Number of models available",
    ],
    correctIndex: 1,
    explanation: "Accepted outcomes incorporate retries, failures, tools, escalation, and review required to deliver useful work.",
    sourceIds: ["docs-cost"],
  },
  {
    id: "q21-proof",
    unitId: "sell-responsibly",
    lessonSlug: "earn-trust-and-retainers",
    prompt: "Which proof claim is most defensible?",
    options: [
      "This workflow will save every company 80 percent",
      "The creator posted a revenue screenshot, so the model is proven",
      "In this client-approved pilot, the measured review cycle changed from X to Y under the stated conditions",
      "AI services are guaranteed to grow",
    ],
    correctIndex: 2,
    explanation: "A bounded, client-approved measure with a baseline, period, and conditions is narrower than a universal or screenshot-based claim.",
    sourceIds: ["commercial-terms"],
  },
  {
    id: "q22-outreach",
    unitId: "sell-responsibly",
    lessonSlug: "earn-trust-and-retainers",
    prompt: "Which outreach method fits this course?",
    options: [
      "Automated unsolicited replies from rotating fake accounts",
      "A small, truthful, permission-based request tied to an observable fit signal",
      "Mass direct messages using scraped personal data",
      "Fabricated testimonials to create social proof",
    ],
    correctIndex: 1,
    explanation: "Fit-qualified, truthful, permission-based outreach respects buyers and reduces spam and platform-policy risk.",
    sourceIds: ["aup", "x-automation-policy"],
    critical: true,
  },
  {
    id: "q23-capstone",
    unitId: "sell-responsibly",
    lessonSlug: "capstone-seven-day-demand-test",
    prompt: "A capstone receives five explicit declines and no sample reviews. What is the strongest response?",
    options: [
      "Hide the denominator and extend the projection",
      "Rewrite the threshold after the test",
      "Preserve the evidence and make a stop or narrowly justified revise decision",
      "Build the full product to prove commitment",
    ],
    correctIndex: 2,
    explanation: "Negative evidence is useful when the threshold was prewritten. The decision should follow the evidence rather than sunk cost.",
    sourceIds: ["github-shotgun-case"],
    critical: true,
  },
  {
    id: "q24-stop",
    unitId: "sell-responsibly",
    lessonSlug: "capstone-seven-day-demand-test",
    prompt: "Can a stop decision demonstrate mastery?",
    options: [
      "No, only revenue counts",
      "Yes, when evidence, quality, economics, rights, privacy, and policy justify it",
      "Only if Claude recommends stopping",
      "Only if the prototype was never built",
    ],
    correctIndex: 1,
    explanation: "The capstone evaluates disciplined evidence and accountable judgment. Stopping an unsupported or unsafe path can be the strongest result.",
    sourceIds: ["commercial-terms", "aup", "docs-cost"],
  },
] as const satisfies readonly ClaudeIncomeQuizQuestion[];

export const CLAUDE_INCOME_FINAL_QUIZ = {
  bankVersion: "2026-08-23.v1",
  questionCount: 16,
  questionsPerUnit: 4,
  passingCorrectAnswers: 13,
  requireAllCritical: true,
  bestScoreStorageKey: "claude-income.quiz.best",
  passedStorageKey: "claude-income.quiz.passed",
  versionStorageKey: "claude-income.quiz.version",
} as const;
