import type { ClaudeIncomeSource } from "./types";

export const CLAUDE_INCOME_SOURCES = [
  {
    id: "academy-work",
    kind: "academy",
    title: "Claude for Work",
    publisher: "Anthropic Academy",
    url: "https://academy.claude.com/collections/claude-for-work",
    accessedOn: "2026-08-23",
    evidenceGrade: "A",
    claimClass: "verified-capability",
    supports: "Official learning collection for applying Claude to workplace tasks.",
    limitations: "The collection teaches capabilities and workflows. It does not establish business demand or earnings.",
    volatility: "medium",
    rightsStatus: "official-link",
  },
  {
    id: "academy-tutorials",
    kind: "academy",
    title: "Claude Academy tutorials",
    publisher: "Anthropic Academy",
    url: "https://academy.claude.com/tutorials",
    accessedOn: "2026-08-23",
    evidenceGrade: "A",
    claimClass: "verified-capability",
    supports: "Official tutorials for current Claude workflows and product surfaces.",
    limitations: "Tutorial availability and interface details can change.",
    volatility: "high",
    rightsStatus: "official-link",
  },
  {
    id: "academy-code-101",
    kind: "academy",
    title: "Claude Code 101",
    publisher: "Anthropic Academy",
    url: "https://academy.claude.com/courses/claude-code-101",
    accessedOn: "2026-08-23",
    evidenceGrade: "A",
    claimClass: "verified-capability",
    supports: "Official learning path for using Claude Code in software work.",
    limitations: "A coding workflow is not evidence that a product will sell or be secure.",
    volatility: "medium",
    rightsStatus: "official-link",
  },
  {
    id: "academy-cowork",
    kind: "academy",
    title: "Get started in Claude Cowork in three steps",
    publisher: "Anthropic Academy",
    url: "https://academy.claude.com/tutorials/get-started-in-claude-cowork-in-three-steps",
    accessedOn: "2026-08-24",
    evidenceGrade: "A",
    claimClass: "verified-capability",
    supports: "Official orientation to Cowork and folder-based task execution.",
    limitations: "Local access and approval settings still require operator judgment.",
    volatility: "high",
    rightsStatus: "official-link",
  },
  {
    id: "help-cowork-safety",
    kind: "official-help",
    title: "Use Claude Cowork safely",
    publisher: "Anthropic Help Center",
    url: "https://support.claude.com/en/articles/13364135-use-claude-cowork-safely",
    accessedOn: "2026-08-24",
    evidenceGrade: "A",
    claimClass: "current-plan-or-policy",
    supports: "Current official guidance explains Cowork's cloud processing, prompt-injection risk, approval modes, computer-use boundary, and special handling of permanent deletion.",
    limitations: "Approval behavior differs by mode and tool. Skip all approvals does not check actions, and computer use does not provide the same per-action checks as ordinary tool use. Recheck the live guidance before handling sensitive files.",
    volatility: "high",
    rightsStatus: "official-link",
  },
  {
    id: "help-projects",
    kind: "official-help",
    title: "What are Projects?",
    publisher: "Anthropic Help Center",
    url: "https://support.claude.com/en/articles/9517075-what-are-projects",
    accessedOn: "2026-08-23",
    evidenceGrade: "A",
    claimClass: "current-plan-or-policy",
    supports: "Projects organize chats and knowledge around a bounded body of work. The current help page describes availability and plan differences.",
    limitations: "Plan limits and enhanced retrieval features are high-volatility facts. Recheck before purchase advice.",
    volatility: "high",
    rightsStatus: "official-link",
  },
  {
    id: "help-artifacts",
    kind: "official-help",
    title: "What are Artifacts and how do I use them?",
    publisher: "Anthropic Help Center",
    url: "https://support.claude.com/en/articles/9487310-what-are-artifacts-and-how-do-i-use-them",
    accessedOn: "2026-08-24",
    evidenceGrade: "A",
    claimClass: "verified-capability",
    supports: "Artifacts can create and iterate on documents, code, web pages, SVG graphics, diagrams, React components, and some AI-powered apps. Current official help says Code execution and file creation must be enabled.",
    limitations: "Publishing an Artifact is not a payment system, a marketplace listing, or proof of product quality. Availability also depends on the required setting and any applicable organization controls; these can change.",
    volatility: "high",
    rightsStatus: "official-link",
  },
  {
    id: "help-skills",
    kind: "official-help",
    title: "Use Skills in Claude",
    publisher: "Anthropic Help Center",
    url: "https://support.claude.com/en/articles/12512180-use-skills-in-claude",
    accessedOn: "2026-08-24",
    evidenceGrade: "A",
    claimClass: "current-plan-or-policy",
    supports: "The current help page lists Skills for Free, Pro, Max, Team, and Enterprise and explains how users add or manage them. Use requires Code execution and file creation to be enabled.",
    limitations: "Team and Enterprise access can depend on organization settings and administrator controls. Older Academy material can show different availability, so the current Help Center page takes precedence for this review date.",
    volatility: "high",
    rightsStatus: "official-link",
  },
  {
    id: "help-connectors",
    kind: "official-help",
    title: "Use connectors to extend Claude's capabilities",
    publisher: "Anthropic Help Center",
    url: "https://support.claude.com/en/articles/11176164-use-connectors-to-extend-claude-s-capabilities",
    accessedOn: "2026-08-23",
    evidenceGrade: "A",
    claimClass: "verified-capability",
    supports: "Connectors can let Claude access other services under the permissions granted to the connected account.",
    limitations: "A connector inherits meaningful data and action risk. Availability and setup vary by plan, workspace, and service.",
    volatility: "high",
    rightsStatus: "official-link",
  },
  {
    id: "help-research",
    kind: "official-help",
    title: "Use Research on Claude",
    publisher: "Anthropic Help Center",
    url: "https://support.claude.com/en/articles/11088861-use-research-on-claude",
    accessedOn: "2026-08-23",
    evidenceGrade: "A",
    claimClass: "current-plan-or-policy",
    supports: "Research performs iterative, citation-bearing investigation and currently depends on web search.",
    limitations: "Research is plan-dependent and citations still need human source checking. The control location can move as the interface changes.",
    volatility: "high",
    rightsStatus: "official-link",
  },
  {
    id: "docs-prompting",
    kind: "official-docs",
    title: "Prompting best practices",
    publisher: "Anthropic Platform Documentation",
    url: "https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices",
    accessedOn: "2026-08-23",
    evidenceGrade: "A",
    claimClass: "verified-capability",
    supports: "Clear instructions, context, examples, structured inputs, and explicit output formats improve task specification.",
    limitations: "Prompt quality does not eliminate model errors or replace domain review.",
    volatility: "medium",
    rightsStatus: "official-link",
  },
  {
    id: "docs-cost",
    kind: "official-docs",
    title: "Optimizing for cost and intelligence",
    publisher: "Anthropic Platform Documentation",
    url: "https://platform.claude.com/docs/en/about-claude/models/optimizing-for-cost-and-intelligence",
    accessedOn: "2026-08-23",
    evidenceGrade: "A",
    claimClass: "verified-capability",
    supports: "Model selection, prompt caching, token discipline, batch processing, and spend controls can affect API unit economics.",
    limitations: "Published comparisons are directional and prices, models, discounts, and limits can change. Recalculate using current official pricing.",
    volatility: "high",
    rightsStatus: "official-link",
  },
  {
    id: "blog-auto-mode",
    kind: "official-docs",
    title: "Auto mode is now the default in Claude Code",
    publisher: "Anthropic",
    url: "https://claude.com/blog/auto-mode-default-in-claude-code",
    accessedOn: "2026-08-23",
    evidenceGrade: "A",
    claimClass: "current-plan-or-policy",
    supports: "Anthropic announced Auto mode as the default for new Claude Code sessions on specified plans beginning in August 2026.",
    limitations: "Defaults can change and do not remove the need for repository permissions, tests, review, and security controls.",
    volatility: "high",
    rightsStatus: "official-link",
  },
  {
    id: "commercial-terms",
    kind: "official-legal",
    title: "Commercial Terms of Service",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/legal/commercial-terms",
    accessedOn: "2026-08-23",
    evidenceGrade: "A",
    claimClass: "current-plan-or-policy",
    supports: "The commercial terms govern eligible commercial use and describe rights between Anthropic and the customer for inputs and outputs.",
    limitations: "The terms do not certify accuracy, originality, non-infringement, or fitness for a client's use. Account, region, and service context matter. This course is not legal advice.",
    volatility: "high",
    rightsStatus: "official-link",
  },
  {
    id: "aup",
    kind: "official-legal",
    title: "Usage Policy",
    publisher: "Anthropic",
    url: "https://www.anthropic.com/legal/aup",
    accessedOn: "2026-08-23",
    evidenceGrade: "A",
    claimClass: "current-plan-or-policy",
    supports: "The policy prohibits deceptive, fraudulent, privacy-invasive, and other harmful uses and sets safeguards for higher-risk contexts.",
    limitations: "Policy text changes. Users must check the current version and applicable law for their own activity.",
    volatility: "high",
    rightsStatus: "official-link",
  },
  {
    id: "github-anthropic-skills",
    kind: "github",
    title: "anthropics/skills",
    publisher: "Anthropic on GitHub",
    url: "https://github.com/anthropics/skills",
    accessedOn: "2026-08-23",
    evidenceGrade: "A",
    claimClass: "verified-capability",
    supports: "Inspectible examples show how repeatable instructions and resources can be packaged as Skills.",
    limitations: "Licensing varies inside the repository. Review the license in each folder before reuse. The repository does not prove income.",
    volatility: "medium",
    license: "Mixed by directory",
    pinnedRevision: "3b3fad96af16a10759d930941b4520ba0c40edae",
    immutableUrl: "https://github.com/anthropics/skills/tree/3b3fad96af16a10759d930941b4520ba0c40edae",
    rightsStatus: "licensed-code",
  },
  {
    id: "github-marketingskills",
    kind: "github",
    title: "coreyhaines31/marketingskills",
    publisher: "Corey Haines on GitHub",
    url: "https://github.com/coreyhaines31/marketingskills",
    accessedOn: "2026-08-23",
    evidenceGrade: "B",
    claimClass: "practitioner-report",
    supports: "A public skill library illustrates turning delivery know-how into reusable operational intellectual property.",
    limitations: "Repository quality and the creator's surrounding business do not establish that a new user will acquire clients or earn a given amount.",
    volatility: "medium",
    license: "MIT",
    pinnedRevision: "3df87f97621e18fbed7f6aa684edba54f49779a7",
    immutableUrl: "https://github.com/coreyhaines31/marketingskills/tree/3df87f97621e18fbed7f6aa684edba54f49779a7",
    rightsStatus: "licensed-code",
  },
  {
    id: "github-claude-marketing",
    kind: "github",
    title: "thatrebeccarae/claude-marketing",
    publisher: "Rebecca Rae on GitHub",
    url: "https://github.com/thatrebeccarae/claude-marketing",
    accessedOn: "2026-08-23",
    evidenceGrade: "B",
    claimClass: "practitioner-report",
    supports: "The repository provides an inspectible marketing skill collection reported to have originated in client delivery work.",
    limitations: "The client-origin statement is self-reported. The repository does not disclose representative revenue or outcome data.",
    volatility: "medium",
    license: "MIT",
    pinnedRevision: "a8a63ec1341f05ec9c1e9cb52b4edeb14e3bdcba",
    immutableUrl: "https://github.com/thatrebeccarae/claude-marketing/tree/a8a63ec1341f05ec9c1e9cb52b4edeb14e3bdcba",
    rightsStatus: "licensed-code",
  },
  {
    id: "github-seo-audit",
    kind: "github",
    title: "houtini-ai/seo-audit",
    publisher: "Houtini AI on GitHub",
    url: "https://github.com/houtini-ai/seo-audit",
    accessedOn: "2026-08-23",
    evidenceGrade: "B",
    claimClass: "practitioner-report",
    supports: "A structured checklist and report workflow demonstrates how an audit can become a scoped, repeatable service artifact.",
    limitations: "Reported time savings are not independently audited. Search performance still depends on implementation and market conditions.",
    volatility: "medium",
    license: "Apache-2.0",
    pinnedRevision: "dbacd51934da0bfa0dc62ebaae69d231a057d146",
    immutableUrl: "https://github.com/houtini-ai/seo-audit/tree/dbacd51934da0bfa0dc62ebaae69d231a057d146",
    rightsStatus: "licensed-code",
  },
  {
    id: "github-open-saas",
    kind: "github",
    title: "wasp-lang/open-saas",
    publisher: "Wasp on GitHub",
    url: "https://github.com/wasp-lang/open-saas",
    accessedOn: "2026-08-23",
    evidenceGrade: "B",
    claimClass: "course-synthesis",
    supports: "A mature SaaS template makes common product infrastructure inspectible and can shorten prototyping work.",
    limitations: "Boilerplate, payments, and deployment do not create demand, guarantee security, or make a business production-ready.",
    volatility: "medium",
    license: "MIT",
    pinnedRevision: "cbd30162b05d798b3a3f955ab5781940b67bec89",
    immutableUrl: "https://github.com/wasp-lang/open-saas/tree/cbd30162b05d798b3a3f955ab5781940b67bec89",
    rightsStatus: "licensed-code",
  },
  {
    id: "github-lastsaas",
    kind: "github",
    title: "jonradoff/lastsaas",
    publisher: "Jon Radoff on GitHub",
    url: "https://github.com/jonradoff/lastsaas",
    accessedOn: "2026-08-23",
    evidenceGrade: "B",
    claimClass: "practitioner-report",
    supports: "An inspectible product artifact is reported by its creator as built with Claude Code.",
    limitations: "The repository is evidence of an artifact, not verified revenue, demand, correctness, or security.",
    volatility: "medium",
    license: "MIT",
    pinnedRevision: "c692923ed98ee503f2de61180ff530a5b05f71a6",
    immutableUrl: "https://github.com/jonradoff/lastsaas/tree/c692923ed98ee503f2de61180ff530a5b05f71a6",
    rightsStatus: "licensed-code",
  },
  {
    id: "github-shotgun-case",
    kind: "case-study",
    title: "Shotgun case study",
    publisher: "Shotgun on GitHub",
    url: "https://github.com/shotgun-sh/shotgun/blob/main/docs/CASE_STUDY.md",
    accessedOn: "2026-08-23",
    evidenceGrade: "C",
    claimClass: "practitioner-report",
    supports: "The vendor-authored case describes a research-first path before custom software implementation.",
    limitations: "Time, revenue, and productivity figures are vendor-authored and not independently audited. Treat them as a design story only.",
    volatility: "medium",
    license: "MIT repository; verify document scope before reuse",
    pinnedRevision: "4d344d5a46aafc815de441ff670d4131187f33e6",
    immutableUrl: "https://github.com/shotgun-sh/shotgun/blob/4d344d5a46aafc815de441ff670d4131187f33e6/docs/CASE_STUDY.md",
    rightsStatus: "licensed-code",
  },
  {
    id: "x-degensing",
    kind: "x-post",
    title: "Unavailable B2B SaaS workflow post",
    publisher: "Degen Sing on X",
    url: "https://x.com/degensing/status/2026578817016566047",
    accessedOn: "2026-08-24",
    evidenceGrade: "D",
    claimClass: "practitioner-report",
    supports: "The attributed public post URL remains identifiable, but the current official oEmbed response exposes only a media link and no usable claim text.",
    limitations: "Blocked from lesson and assessment evidence. Do not reconstruct worktree, testing, review, cost, security, customer, or income details from earlier summaries or inaccessible media.",
    volatility: "medium",
    rightsStatus: "link-only",
  },
  {
    id: "x-codyschneider",
    kind: "x-post",
    title: "Reported team AI data analyst workflow",
    publisher: "Cody Schneider on X",
    url: "https://x.com/codyschneider/status/2026009180763554234",
    accessedOn: "2026-08-23",
    evidenceGrade: "C",
    claimClass: "practitioner-report",
    supports: "The author reports giving a marketing team an AI data analyst available across Claude Code, Cowork, and iOS, with access to the team's data sources and claimed dashboard, sales-forecasting, and blog-post-content improvement uses.",
    limitations: "X's official oEmbed output verifies only this attributed public self-report and truncates additional context. It does not establish return on investment, correctness, data governance, or representative results. Attached media is not reproduced or used as evidence.",
    volatility: "medium",
    rightsStatus: "link-only",
  },
  {
    id: "x-samrags",
    kind: "x-post",
    title: "Partially available Claude onboarding post",
    publisher: "Sam Ragsdale on X",
    url: "https://x.com/samrags_/status/2016267562057662745",
    accessedOn: "2026-08-24",
    evidenceGrade: "D",
    claimClass: "practitioner-report",
    supports: "The current official oEmbed response confirms an attributed post about onboarding non-engineers to Claude Code and Cowork, but truncates before the claimed durable-handoff details.",
    limitations: "Blocked from lesson and assessment evidence. The available text does not support claims about explicit goal files, output files, one-objective-per-chat practice, comparative delivery, or income.",
    volatility: "medium",
    rightsStatus: "link-only",
  },
  {
    id: "x-elvissun",
    kind: "x-post",
    title: "Reported duplicate-billing incident",
    publisher: "Elvis Sun on X",
    url: "https://x.com/elvissun/status/2025044631407468689",
    accessedOn: "2026-08-23",
    evidenceGrade: "C",
    claimClass: "practitioner-report",
    supports: "The author reports that one customer was billed three times for a total of $240 and attributes the defect to billing code previously written with Claude Code.",
    limitations: "The incident is self-reported and not independently reproduced. The currently recoverable text does not identify Stripe or establish a refund outcome. It supports caution, not a failure-rate estimate.",
    volatility: "medium",
    rightsStatus: "link-only",
  },
  {
    id: "x-wcandillon",
    kind: "x-post",
    title: "Reported Remotion animation output",
    publisher: "William Candillon on X",
    url: "https://x.com/wcandillon/status/2015345960491069718",
    accessedOn: "2026-08-23",
    evidenceGrade: "C",
    claimClass: "practitioner-report",
    supports: "The author reports that the displayed creative output was made entirely with Remotion.",
    limitations: "The currently recoverable post text does not mention Claude or establish how Claude contributed. A finished output is portfolio evidence only, with no verified revenue or client outcome.",
    volatility: "medium",
    rightsStatus: "link-only",
  },
  {
    id: "x-adiix-caution",
    kind: "x-post",
    title: "Blocked automation-income anecdote",
    publisher: "AdiiX on X",
    url: "https://x.com/adiix_official/status/2034730013283512381",
    accessedOn: "2026-08-23",
    evidenceGrade: "D",
    claimClass: "practitioner-report",
    supports: "The current audit verified the attributed post link but recovered no usable public text that could support a factual lesson claim.",
    limitations: "Blocked from lesson and assessment evidence. The course does not reconstruct its alleged price, outcome, projection, or account-risk details from a screenshot, prior summary, or inaccessible context.",
    volatility: "medium",
    rightsStatus: "link-only",
  },
  {
    id: "x-automation-policy",
    kind: "platform-policy",
    title: "X automation rules",
    publisher: "X Help Center",
    url: "https://help.x.com/en/rules-and-policies/x-automation",
    accessedOn: "2026-08-23",
    evidenceGrade: "A",
    claimClass: "current-plan-or-policy",
    supports: "X restricts spammy, duplicative, unsolicited, and unauthorized automated activity.",
    limitations: "Platform rules change. Check the current policy and obtain any required approval before automation.",
    volatility: "high",
    rightsStatus: "official-link",
  },
] as const satisfies readonly ClaudeIncomeSource[];

export const CLAUDE_INCOME_SOURCE_BY_ID = new Map<string, ClaudeIncomeSource>(
  CLAUDE_INCOME_SOURCES.map((source) => [source.id, source] as const),
);

export function getClaudeIncomeSourceHref(source: ClaudeIncomeSource): string {
  return source.immutableUrl ?? source.url;
}

export function getClaudeIncomeSource(id: string): ClaudeIncomeSource {
  const source = CLAUDE_INCOME_SOURCE_BY_ID.get(id);
  if (!source) throw new Error(`Unknown Claude income source: ${id}`);
  return source;
}
