import { AGENTIC_VIDEO_EDITING_SOURCES } from "./sources";
import type {
  AgenticVideoEditingClaimRecord,
  AgenticVideoEditingModuleSlug,
} from "./types";

function evidenceUrl(sourceId: string, index = 0): string {
  const source = AGENTIC_VIDEO_EDITING_SOURCES.find((candidate) => candidate.id === sourceId);
  const url = source?.claimEvidenceUrls[index];
  if (!url) throw new Error(`Missing Course 22 claim evidence URL: ${sourceId}[${index}]`);
  return url;
}

/**
 * Atomic Course 22 claim ledger.
 *
 * Section-level source lists describe the reading set. This ledger is the
 * narrower publication contract: each paragraph-level atomic claim declares
 * its own evidence mode, exact source URL and file/section locator, or is
 * visibly owned by course policy/instructional synthesis without pretending a
 * source said it.
 */
export const AGENTIC_VIDEO_EDITING_CLAIMS: readonly AgenticVideoEditingClaimRecord[] = [
  {
    id: "c22-m1-p1-video-use-workflow",
    moduleSlug: "agentic-editing-contract",
    sectionIndex: 0,
    paragraphIndex: 0,
    evidenceMode: "source-grounded",
    claim: "The pinned Video Use workflow inventories sources, proposes a strategy, waits for approval, then builds and renders an edit.",
    claimZhHans: "固定版本的 Video Use 工作流先盘点来源、提出策略并等待批准，随后才建立与渲染剪辑。",
    sourceId: "video-use",
    evidenceUrl: evidenceUrl("video-use", 0),
    locator: "SKILL.md — workflow phases: inventory, strategy approval, EDL, render, review",
    boundary: "This documents one young repository workflow, not universal quality, speed, cost, reliability, or authorization for learner media.",
    boundaryZhHans: "这只记录一个较新仓库的工作流，不能证明普遍质量、速度、成本、可靠性，也不授权学习者媒体。",
  },
  {
    id: "c22-m1-p2-course-acceptance-policy",
    moduleSlug: "agentic-editing-contract",
    sectionIndex: 0,
    paragraphIndex: 1,
    evidenceMode: "course-policy",
    claim: "The course requires an executable brief to replace untestable preferences with observable acceptance criteria.",
    claimZhHans: "课程要求用可执行简报与可观察验收标准替代无法测试的偏好。",
    locator: "Course 22 v2 policy — M1 creative-brief contract",
    boundary: "This is the course's instructional contract, not a claim that an external source defines one universal creative brief.",
    boundaryZhHans: "这是课程教学合同，并非声称外部来源定义了唯一通用的创作简报。",
  },
  {
    id: "c22-m2-p1-ffprobe-observations",
    moduleSlug: "media-ingest-provenance",
    sectionIndex: 0,
    paragraphIndex: 0,
    evidenceMode: "source-grounded",
    claim: "ffprobe exposes machine-readable container, stream, packet, frame, duration, frame-rate, and time-base fields.",
    claimZhHans: "ffprobe 提供机器可读的容器、stream、packet、frame、时长、帧率与 time-base 字段。",
    sourceId: "ffprobe-docs",
    evidenceUrl: evidenceUrl("ffprobe-docs"),
    locator: "ffprobe documentation — Description, -show_streams, -show_packets, and -show_frames",
    boundary: "Rolling documentation does not prove the installed binary, input bytes, or resulting receipt; those remain separately hash-bound.",
    boundaryZhHans: "滚动文档不能证明已安装二进制、输入字节或结果凭据；这些仍须另行绑定 hash。",
  },
  {
    id: "c22-m2-p1-fixity-policy",
    moduleSlug: "media-ingest-provenance",
    sectionIndex: 0,
    paragraphIndex: 0,
    evidenceMode: "course-policy",
    claim: "A SHA-256 match establishes byte identity only relative to the recorded baseline, not truth, authorship, rights, or consent.",
    claimZhHans: "SHA-256 匹配只证明相对已记录 baseline 的字节一致，不证明真实、作者、权利或同意。",
    locator: "Course 22 v2 policy — M2 fixity-evidence boundary",
    boundary: "The policy deliberately avoids treating a hash as authenticity, provenance, or legal authorization.",
    boundaryZhHans: "该政策明确禁止把 hash 当作真实性、来源或法律授权。",
  },
  {
    id: "c22-m2-p2-c2pa-provenance",
    moduleSlug: "media-ingest-provenance",
    sectionIndex: 0,
    paragraphIndex: 1,
    evidenceMode: "source-grounded",
    claim: "C2PA 2.4 defines signed provenance manifests and validation status for declared content provenance.",
    claimZhHans: "C2PA 2.4 为声明的内容来源定义签名 provenance manifest 与验证状态。",
    sourceId: "c2pa-2-4",
    evidenceUrl: evidenceUrl("c2pa-2-4"),
    locator: "C2PA 2.4 — manifests, assertions, ingredients, trust, and validation status",
    boundary: "A valid manifest does not prove content truth, consent, ownership, legality, quality, or permission for a new use.",
    boundaryZhHans: "有效 manifest 不证明内容真实、同意、所有权、合法性、质量或新用途许可。",
  },
  {
    id: "c22-m2-p2-storage-synthesis",
    moduleSlug: "media-ingest-provenance",
    sectionIndex: 0,
    paragraphIndex: 1,
    evidenceMode: "instructional-synthesis",
    claim: "The course separates read-only originals, work, cache, analysis, and versioned render directories while retaining parent lineage.",
    claimZhHans: "课程分离只读原件、work、cache、analysis 与版本化 render 目录，并保留父级谱系。",
    locator: "Course 22 v2 synthesis — M2 directory and derivative lineage design",
    boundary: "This design does not turn an ordinary filesystem into WORM storage or a signed audit log.",
    boundaryZhHans: "该设计不会把普通文件系统变成 WORM 存储或签名审计日志。",
  },
  {
    id: "c22-m3-p1-ffprobe-timebase",
    moduleSlug: "transcripts-shots-index",
    sectionIndex: 0,
    paragraphIndex: 0,
    evidenceMode: "source-grounded",
    claim: "Frame-, packet-, stream-, and time-base fields are distinct ffprobe observations and must not be collapsed into one assumed clock.",
    claimZhHans: "frame、packet、stream 与 time-base 是不同的 ffprobe 观察，不能合并成一个假定时钟。",
    sourceId: "ffprobe-docs",
    evidenceUrl: evidenceUrl("ffprobe-docs"),
    locator: "ffprobe documentation — stream, packet, frame, and interval inspection sections",
    boundary: "Nominal or average rate fields alone do not prove constant or variable frame-rate behavior for an arbitrary file.",
    boundaryZhHans: "仅凭 nominal 或 average rate 字段不能证明任意文件是恒定或可变帧率。",
  },
  {
    id: "c22-m3-p2-whisper-navigation",
    moduleSlug: "transcripts-shots-index",
    sectionIndex: 0,
    paragraphIndex: 1,
    evidenceMode: "source-grounded",
    claim: "The pinned Whisper repository supports multilingual speech-recognition and translation workflows useful for transcript navigation.",
    claimZhHans: "固定版本 Whisper 仓库支持可用于转录导航的多语言语音识别与翻译工作流。",
    sourceId: "whisper",
    evidenceUrl: evidenceUrl("whisper"),
    locator: "README.md — Approach, Available models and languages, and command-line usage",
    boundary: "Model output does not authenticate speakers or guarantee names, numbers, negation, overlap, or every language/accent.",
    boundaryZhHans: "模型输出不认证说话人，也不保证姓名、数字、否定、重叠或所有语言与口音。",
  },
  {
    id: "c22-m3-p2-whisperx-alignment",
    moduleSlug: "transcripts-shots-index",
    sectionIndex: 0,
    paragraphIndex: 1,
    evidenceMode: "source-grounded",
    claim: "The pinned WhisperX workflow adds candidate word-level timestamps through alignment.",
    claimZhHans: "固定版本 WhisperX 工作流通过 alignment 增加候选词级时间戳。",
    sourceId: "whisperx",
    evidenceUrl: evidenceUrl("whisperx"),
    locator: "README.md — word-level timestamps and forced-alignment workflow",
    boundary: "Alignment remains model- and language-dependent candidate evidence requiring audiovisual and human review.",
    boundaryZhHans: "Alignment 仍是依赖模型与语言的候选证据，必须接受视听与人工复核。",
  },
  {
    id: "c22-m4-p1-video-use-transcript-interface",
    moduleSlug: "semantic-analysis-director",
    sectionIndex: 0,
    paragraphIndex: 0,
    evidenceMode: "source-grounded",
    claim: "The pinned Video Use workflow uses transcript evidence as a primary editing interface and introduces richer visual analysis only where useful.",
    claimZhHans: "固定版本 Video Use 工作流把转录证据作为主要剪辑界面，并只在有用时加入更丰富的视觉分析。",
    sourceId: "video-use",
    evidenceUrl: evidenceUrl("video-use"),
    locator: "SKILL.md — transcript-led analysis and visual-timeline workflow",
    boundary: "One repository pattern does not establish that sparse model sampling understands an entire video or preserves meaning.",
    boundaryZhHans: "一个仓库模式不能证明稀疏模型抽样理解整段视频或保留含义。",
  },
  {
    id: "c22-m4-p2-three-lane-policy",
    moduleSlug: "semantic-analysis-director",
    sectionIndex: 0,
    paragraphIndex: 1,
    evidenceMode: "course-policy",
    claim: "M4 requires manual and recorded-fixture offline lanes and keeps the optional live-model lane disabled until provider, version, network, cost, data path, secret delivery, and authority are explicit.",
    claimZhHans: "M4 要求手工与录制 fixture 离线 lane，并在服务商、版本、网络、成本、data path、密钥交付与权限明确前关闭可选 live-model lane。",
    locator: "Course 22 v2 policy — M4 candidate-segments three-lane schema",
    boundary: "This is a course authority contract, not a claim that any provider guarantees equivalent outputs.",
    boundaryZhHans: "这是课程权限合同，并非声称任何服务商保证等价输出。",
  },
  {
    id: "c22-m4-p2-qwen-issue-watch",
    moduleSlug: "semantic-analysis-director",
    sectionIndex: 0,
    paragraphIndex: 1,
    evidenceMode: "version-watch",
    claim: "Qwen3-VL issue 1761 is one dated user report that motivates a course regression test for time-axis alignment.",
    claimZhHans: "Qwen3-VL issue 1761 是一条有日期的用户报告，可启发课程的时间轴对齐回归测试。",
    sourceId: "qwen3-vl-issue-1761",
    evidenceUrl: evidenceUrl("qwen3-vl-issue-1761"),
    locator: "GitHub issue QwenLM/Qwen3-VL #1761 — user-reported frame-list time-axis mismatch",
    boundary: "It is not maintainer confirmation, root-cause analysis, prevalence evidence, or proof that all versions and inputs are affected.",
    boundaryZhHans: "它不是维护者确认、根因分析、发生率证据，也不能证明所有版本与输入均受影响。",
  },
  {
    id: "c22-m5-p1-otio-data-model",
    moduleSlug: "declarative-edit-plan",
    sectionIndex: 0,
    paragraphIndex: 0,
    evidenceMode: "source-grounded",
    claim: "OpenTimelineIO represents editorial timeline structure and media references, with bundle adapters distinct from decoding or rendering.",
    claimZhHans: "OpenTimelineIO 表示剪辑时间线结构与媒体引用；bundle adapter 与解码或渲染是不同能力。",
    sourceId: "opentimelineio",
    evidenceUrl: evidenceUrl("opentimelineio"),
    locator: "README.md — What OTIO Is, What OTIO Is Not, and .otio/.otioz/.otiod adapters",
    boundary: "OTIO does not itself decode, encode, render, clear rights, or guarantee every adapter preserves every field.",
    boundaryZhHans: "OTIO 本身不解码、编码、渲染、清权，也不保证所有 adapter 保留全部字段。",
  },
  {
    id: "c22-m6-p1-montaj-tools",
    moduleSlug: "agent-tools-mcp",
    sectionIndex: 0,
    paragraphIndex: 0,
    evidenceMode: "source-grounded",
    claim: "Montaj exposes small schema-bound video operations and a pending-to-human-final lifecycle for an external host agent.",
    claimZhHans: "Montaj 向外部宿主智能体提供小型 schema-bound 视频操作与 pending-to-human-final 生命周期。",
    sourceId: "montaj",
    evidenceUrl: evidenceUrl("montaj"),
    locator: "README.md — tool schemas, workflow steps, and project lifecycle",
    boundary: "Montaj does not provide the reasoning agent and some paths invoke external paid providers.",
    boundaryZhHans: "Montaj 不提供推理智能体，且部分路径会调用外部付费服务商。",
  },
  {
    id: "c22-m6-p1-qcut-shared-project",
    moduleSlug: "agent-tools-mcp",
    sectionIndex: 0,
    paragraphIndex: 0,
    evidenceMode: "source-grounded",
    claim: "QCut exposes a machine-readable CLI and a human-visible multitrack editor over one project state.",
    claimZhHans: "QCut 在同一工程状态上提供机器可读 CLI 与人类可见多轨编辑器。",
    sourceId: "qcut",
    evidenceUrl: evidenceUrl("qcut"),
    locator: "README.md — CLI, agent plugins, and visible multitrack project",
    boundary: "Optional analysis or generation can require application state, network, provider terms, and explicit media authorization.",
    boundaryZhHans: "可选分析或生成可能需要应用状态、网络、服务商条款与明确媒体授权。",
  },
  {
    id: "c22-m6-p1-velorn-preview",
    moduleSlug: "agent-tools-mcp",
    sectionIndex: 0,
    paragraphIndex: 0,
    evidenceMode: "source-grounded",
    claim: "Velorn documents local MCP editing tools with preview-first ordinary writes and queued generation/export operations.",
    claimZhHans: "Velorn 记录本地 MCP 编辑工具、普通写入的 preview-first 模式与排队生成/导出操作。",
    sourceId: "velorn",
    evidenceUrl: evidenceUrl("velorn"),
    locator: "README.md — MCP tool surface, previews, timeline operations, and queued jobs",
    boundary: "Not every filesystem or project action is undoable, and optional providers can require keys, network access, or separate licences.",
    boundaryZhHans: "并非所有文件系统或工程动作都可撤销；可选服务商可能需要密钥、网络或独立许可证。",
  },
  {
    id: "c22-m6-p2-mcp-transport",
    moduleSlug: "agent-tools-mcp",
    sectionIndex: 0,
    paragraphIndex: 1,
    evidenceMode: "source-grounded",
    claim: "The dated MCP protocol release defines capability negotiation and tool/resource/prompt message surfaces between hosts, clients, and servers.",
    claimZhHans: "有日期的 MCP 协议版本定义宿主、客户端与服务器之间的能力协商及 tool/resource/prompt 消息界面。",
    sourceId: "mcp-2026-07-28",
    evidenceUrl: evidenceUrl("mcp-2026-07-28"),
    locator: "MCP 2026-07-28 release — protocol capability and interoperability summary",
    boundary: "Protocol transport does not supply creative judgment, authenticate every downstream system, grant filesystem/network permission, or authorize publication.",
    boundaryZhHans: "协议传输不提供创意判断、不认证所有下游系统、不授予文件系统/网络权限，也不授权发布。",
  },
  {
    id: "c22-m7-p1-ffmpeg-command-surface",
    moduleSlug: "deterministic-rendering",
    sectionIndex: 0,
    paragraphIndex: 0,
    evidenceMode: "source-grounded",
    claim: "Current FFmpeg documentation exposes command and filter surfaces for bounded media transformations and logging.",
    claimZhHans: "当前 FFmpeg 文档提供有边界媒体转换与日志的命令和滤镜界面。",
    sourceId: "ffmpeg-docs",
    evidenceUrl: evidenceUrl("ffmpeg-docs", 0),
    locator: "ffmpeg documentation — Synopsis, Description, Stream selection, and Options",
    boundary: "A command surface does not make an unconstrained shell prompt safe or transfer editorial authority to the renderer.",
    boundaryZhHans: "命令界面不会让无约束 shell prompt 变安全，也不会把剪辑权限转交渲染器。",
  },
  {
    id: "c22-m7-p2-ffmpeg-seeking",
    moduleSlug: "deterministic-rendering",
    sectionIndex: 0,
    paragraphIndex: 1,
    evidenceMode: "source-grounded",
    claim: "FFmpeg seeking, stream-copy, decode/filter/encode, logging, and probing paths have different accuracy and reproducibility implications.",
    claimZhHans: "FFmpeg 的 seek、stream-copy、解码/滤镜/编码、日志与 probe 路径具有不同的准确性与可复现性影响。",
    sourceId: "ffmpeg-docs",
    evidenceUrl: evidenceUrl("ffmpeg-docs", 0),
    locator: "ffmpeg documentation — -ss input/output seeking, streamcopy, and logging options",
    boundary: "Documentation does not promise bit-identical or frame-identical output across codecs, builds, hardware, filters, and thread schedules.",
    boundaryZhHans: "文档不保证跨编解码器、build、硬件、滤镜与线程调度的字节或帧完全一致。",
  },
  {
    id: "c22-m8-p1-whisperx-alignment",
    moduleSlug: "captions-audio-formats",
    sectionIndex: 0,
    paragraphIndex: 0,
    evidenceMode: "source-grounded",
    claim: "WhisperX alignment can accelerate word-level transcript navigation for candidate edits.",
    claimZhHans: "WhisperX alignment 可加速候选剪辑的词级转录导航。",
    sourceId: "whisperx",
    evidenceUrl: evidenceUrl("whisperx"),
    locator: "README.md — word-level timestamps and alignment",
    boundary: "Alignment cannot decide whether a pause, reaction, overlap, or filler is semantically necessary.",
    boundaryZhHans: "Alignment 不能判断停顿、反应、重叠或填充词在语义上是否必要。",
  },
  {
    id: "c22-m8-p1-auto-editor-rules",
    moduleSlug: "captions-audio-formats",
    sectionIndex: 0,
    paragraphIndex: 0,
    evidenceMode: "source-grounded",
    claim: "Auto-Editor documents rule-driven first-pass editing based on loudness and motion observations.",
    claimZhHans: "Auto-Editor 记录基于响度与运动观察的规则型初剪。",
    sourceId: "auto-editor",
    evidenceUrl: evidenceUrl("auto-editor"),
    locator: "README.md — audio/motion analysis and timeline export workflow",
    boundary: "Rule-driven deletion candidates do not establish speaker intent, performance meaning, accessibility, or release suitability.",
    boundaryZhHans: "规则删除候选不能证明说话人意图、表演含义、无障碍或发布适用性。",
  },
  {
    id: "c22-m8-p2-semantic-cut-policy",
    moduleSlug: "captions-audio-formats",
    sectionIndex: 0,
    paragraphIndex: 1,
    evidenceMode: "course-policy",
    claim: "The course forbids automated cuts that create a statement the speaker did not make and requires retained rejection evidence.",
    claimZhHans: "课程禁止自动剪切制造说话人未表达的陈述，并要求保留人工拒绝证据。",
    locator: "Course 22 v2 policy — M8 semantic-cut and human-rejection contract",
    boundary: "This is a fail-closed course rule, not a claim that one metric can automatically certify preserved meaning.",
    boundaryZhHans: "这是 fail-closed 课程规则，并非声称单一指标可自动认证含义得到保留。",
  },
  {
    id: "c22-m9-p1-vmaf-scope",
    moduleSlug: "verification-human-review",
    sectionIndex: 0,
    paragraphIndex: 0,
    evidenceMode: "source-grounded",
    claim: "VMAF compares aligned reference and distorted versions for a bounded perceptual-quality question.",
    claimZhHans: "VMAF 比较对齐的参考与失真版本，以回答有边界的感知质量问题。",
    sourceId: "vmaf",
    evidenceUrl: evidenceUrl("vmaf"),
    locator: "README.md — VMAF overview, reference/distorted inputs, and feature/model workflow",
    boundary: "VMAF does not judge narrative, truth, caption accuracy, music rights, or differently edited timelines.",
    boundaryZhHans: "VMAF 不判断叙事、真实、字幕准确、音乐权利或不同剪辑的时间线。",
  },
  {
    id: "c22-m9-p2-ffprobe-qc",
    moduleSlug: "verification-human-review",
    sectionIndex: 0,
    paragraphIndex: 1,
    evidenceMode: "source-grounded",
    claim: "ffprobe supplies machine-readable container, stream, duration, frame-rate, and decode-adjacent observations for a declared technical gate.",
    claimZhHans: "ffprobe 为已声明技术关口提供机器可读的容器、stream、时长、帧率与解码相关观察。",
    sourceId: "ffprobe-docs",
    evidenceUrl: evidenceUrl("ffprobe-docs"),
    locator: "ffprobe documentation — output format, stream/frame selection, and show_entries",
    boundary: "These observations do not certify sync, caption semantics, aesthetics, safety, or publication readiness without separate algorithms and review.",
    boundaryZhHans: "若无独立算法与复核，这些观察不认证同步、字幕语义、美学、安全或发布准备度。",
  },
  {
    id: "c22-m9-p2-ffmpeg-filters-qc",
    moduleSlug: "verification-human-review",
    sectionIndex: 0,
    paragraphIndex: 1,
    evidenceMode: "source-grounded",
    claim: "Current FFmpeg filter documentation exposes optional signal checks whose installed availability and parameters must be probed.",
    claimZhHans: "当前 FFmpeg 滤镜文档提供可选信号检查；其安装可用性与参数必须实际 probe。",
    sourceId: "ffmpeg-docs",
    evidenceUrl: evidenceUrl("ffmpeg-docs", 1),
    locator: "FFmpeg Filters Documentation — black/freeze/audio analysis filter sections",
    boundary: "A filter pass is a narrow configured observation, not proof that the video is meaningful, accessible, lawful, or safe to publish.",
    boundaryZhHans: "滤镜通过只是狭窄配置观察，不证明视频有意义、无障碍、合法或可安全发布。",
  },
  {
    id: "c22-m10-p1-package-policy",
    moduleSlug: "production-capstone",
    sectionIndex: 0,
    paragraphIndex: 0,
    evidenceMode: "course-policy",
    claim: "The learner capstone starts only after current quiz and M1–M9 completion and must rebuild a fresh, independently identified learner-project lineage.",
    claimZhHans: "学习者综合项目只在当前测验与 M1–M9 完成后开始，并必须重建具有独立标识的新学习者工程谱系。",
    locator: "Course 22 v2 policy — M10 fresh learner-final package and lineage contract",
    boundary: "Repository code can validate structure and hashes but cannot authenticate ownership, consent, reviewer identity, or publication authority.",
    boundaryZhHans: "仓库代码可校验结构与 hash，但不能认证所有权、同意、审核者身份或发布权。",
  },
  {
    id: "c22-m10-p2-director-state",
    moduleSlug: "production-capstone",
    sectionIndex: 0,
    paragraphIndex: 1,
    evidenceMode: "source-grounded",
    claim: "The pinned VideoDB Director repository illustrates dynamic capability selection with explicit workflow state outside a single chat reply.",
    claimZhHans: "固定版本 VideoDB Director 仓库展示在单次 chat 回复之外进行动态能力选择与显式工作流状态管理。",
    sourceId: "videodb-director",
    evidenceUrl: evidenceUrl("videodb-director"),
    locator: "README.md — Director architecture, agents, tools, and workflow execution",
    boundary: "The young repository does not establish production maturity, rights clearance, or suitability for confidential learner media.",
    boundaryZhHans: "该较新仓库不证明生产成熟度、权利已清理或适合机密学习者媒体。",
  },
  {
    id: "c22-m10-p2-mosaic-runs",
    moduleSlug: "production-capstone",
    sectionIndex: 0,
    paragraphIndex: 1,
    evidenceMode: "source-grounded",
    claim: "Mosaic API documentation exposes graph and asynchronous run surfaces with explicit external service state.",
    claimZhHans: "Mosaic API 文档提供带显式外部服务状态的 graph 与异步 run 界面。",
    sourceId: "mosaic-api-docs",
    evidenceUrl: evidenceUrl("mosaic-api-docs"),
    locator: "Mosaic API documentation — graph/run lifecycle and asynchronous operation surface",
    boundary: "Rolling cloud documentation and a successful run do not prove footage authorization, privacy suitability, output quality, cost, or publish permission.",
    boundaryZhHans: "滚动云文档与成功 run 不证明素材授权、隐私适用性、输出质量、成本或发布许可。",
  },
];

export function getAgenticVideoEditingClaims(
  moduleSlug: AgenticVideoEditingModuleSlug,
  sectionIndex: number,
  paragraphIndex: number,
): readonly AgenticVideoEditingClaimRecord[] {
  return AGENTIC_VIDEO_EDITING_CLAIMS.filter((claim) => (
    claim.moduleSlug === moduleSlug
    && claim.sectionIndex === sectionIndex
    && claim.paragraphIndex === paragraphIndex
  ));
}
