import type { AgenticVideoEditingSourceRecord } from "./types";

const ACCESSED_ON = "2026-08-26";

/**
 * Course 20 source ledger.
 *
 * GitHub entries support inspectable implementation claims and license
 * boundaries. X entries are dated field signals only: every one records its
 * author and context and points back to repository evidence. No post media is
 * copied into the public course.
 */
export const AGENTIC_VIDEO_EDITING_SOURCES = [
  {
    id: "video-use",
    kind: "github-repository",
    role: "agent-architecture",
    repository: "browser-use/video-use",
    title: "video-use: edit videos with coding agents",
    publisher: "Browser Use",
    url: "https://github.com/browser-use/video-use/blob/92c2b34e44c205cbc2acae7f6ca7c1c219d5dd66/SKILL.md",
    claimEvidenceUrls: [
      "https://github.com/browser-use/video-use/blob/92c2b34e44c205cbc2acae7f6ca7c1c219d5dd66/SKILL.md",
      "https://github.com/browser-use/video-use/blob/92c2b34e44c205cbc2acae7f6ca7c1c219d5dd66/README.md",
      "https://github.com/browser-use/video-use/blob/92c2b34e44c205cbc2acae7f6ca7c1c219d5dd66/install.md",
      "https://github.com/browser-use/video-use/blob/92c2b34e44c205cbc2acae7f6ca7c1c219d5dd66/LICENSE",
    ],
    accessedOn: ACCESSED_ON,
    stability: "commit-pinned-at-cutoff",
    revision: "92c2b34e44c205cbc2acae7f6ca7c1c219d5dd66",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link and paraphrase the workflow; do not republish project code, examples, or demo media.",
    rightsDecisionZhHans: "链接并转述工作流；不再发布项目代码、示例或演示媒体。",
    supports: "A transcript-led agent workflow that inventories footage, proposes a strategy, waits for approval, builds an EDL, renders into a separate edit directory, inspects cut boundaries, and retains session artifacts.",
    supportsZhHans: "一种以转录为主界面的智能体流程：盘点素材、提出策略、等待批准、生成 EDL、在独立 edit 目录渲染、检查切点并保留会话产物。",
    boundary: "The repository is young, depends on FFmpeg and currently asks for an ElevenLabs key for transcription; open-source code does not make every provider call free or suitable for confidential footage.",
    boundaryZhHans: "该仓库较新，依赖 FFmpeg，当前转录安装流程还要求 ElevenLabs 密钥；代码开源不代表所有服务调用免费，也不代表适合机密素材。",
  },
  {
    id: "ffmpeg",
    kind: "github-repository",
    role: "execution-engine",
    repository: "FFmpeg/FFmpeg",
    title: "FFmpeg multimedia framework",
    publisher: "FFmpeg",
    url: "https://github.com/FFmpeg/FFmpeg/blob/bf1b838f2ab88b4f8fd83443325c782ea0e0f7fa/README.md",
    claimEvidenceUrls: [
      "https://github.com/FFmpeg/FFmpeg/blob/bf1b838f2ab88b4f8fd83443325c782ea0e0f7fa/README.md",
      "https://github.com/FFmpeg/FFmpeg/blob/bf1b838f2ab88b4f8fd83443325c782ea0e0f7fa/LICENSE.md",
      "https://ffmpeg.org/ffprobe.html",
    ],
    versionAnchorUrl: "https://github.com/FFmpeg/FFmpeg/tree/n9.0.1",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "9.0.1 Lei",
    resolvedCommit: "bf1b838f2ab88b4f8fd83443325c782ea0e0f7fa",
    license: "LGPL-2.1-or-later by default; build-dependent GPL/nonfree boundary",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Teach command structure and link to upstream; learners must inspect their binary configuration and codec licenses.",
    rightsDecisionZhHans: "讲解命令结构并链接上游；学习者必须检查自己二进制的编译配置与编解码器许可证。",
    supports: "Scriptable probing, trimming, filtering, audio processing, subtitle composition, transcoding, and machine-readable media inspection through ffprobe.",
    supportsZhHans: "通过 FFmpeg 与 ffprobe 进行可脚本化、可检查的探测、剪切、滤镜、音频处理、字幕合成、转码和媒体检查。",
    boundary: "FFmpeg executes media operations but does not decide story intent. Fast stream-copy cuts may preserve material around a seek point; bit-identical output is not guaranteed across builds, codecs, hardware, or threading. Redistribution depends on the actual build, and a build that enables nonfree components generally cannot be redistributed.",
    boundaryZhHans: "FFmpeg 执行媒体操作但不判断叙事意图；快速流复制剪切可能保留 seek point 附近内容；跨编译、编解码器、硬件或线程设置不保证逐位一致。再分发取决于实际编译配置，启用 nonfree 组件的构建通常不能再分发。",
  },
  {
    id: "remotion",
    kind: "github-repository",
    role: "execution-engine",
    repository: "remotion-dev/remotion",
    title: "Remotion: make videos programmatically with React",
    publisher: "Remotion",
    url: "https://github.com/remotion-dev/remotion/blob/a2c2a6260fee129bb55f97b9632d998f589839b7/README.md",
    claimEvidenceUrls: [
      "https://github.com/remotion-dev/remotion/blob/a2c2a6260fee129bb55f97b9632d998f589839b7/README.md",
      "https://github.com/remotion-dev/remotion/blob/a2c2a6260fee129bb55f97b9632d998f589839b7/LICENSE.md",
    ],
    versionAnchorUrl: "https://github.com/remotion-dev/remotion/releases/tag/v4.0.517",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v4.0.517",
    resolvedCommit: "a2c2a6260fee129bb55f97b9632d998f589839b7",
    license: "Remotion License (special commercial terms)",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link and teach original examples only; surface the company-license threshold before learners adopt it commercially.",
    rightsDecisionZhHans: "仅链接并讲解原创示例；学习者商业采用前必须看到公司许可证门槛。",
    supports: "Frame-addressable React compositions for repeatable titles, captions, diagrams, data graphics, brand templates, preview, and rendering.",
    supportsZhHans: "用逐帧可寻址的 React composition 重复生成标题、字幕、图解、数据图形、品牌模板、预览与渲染。",
    boundary: "Programmatic composition is not a general-purpose semantic rough-cut engine. Under the pinned v4.0.517 license, personal and nonprofit use and for-profit organizations with up to three employees are in the free category; larger for-profit organizations need a Company License. Re-check current terms before adoption; this is not legal advice.",
    boundaryZhHans: "程序化合成并非通用语义粗剪引擎。按固定的 v4.0.517 许可，个人、非营利组织及最多三名员工的营利组织属于免费范围；更大的营利组织需要 Company License。采用前须复核最新条款；这不是法律意见。",
  },
  {
    id: "remotion-skills",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "remotion-dev/remotion",
    title: "Remotion Agent Skills",
    publisher: "Remotion",
    url: "https://github.com/remotion-dev/remotion/blob/7aee2f4b3d5c05c77761f2dc6ec5aeac701dcce8/packages/skills/README.md",
    claimEvidenceUrls: [
      "https://github.com/remotion-dev/remotion/blob/7aee2f4b3d5c05c77761f2dc6ec5aeac701dcce8/packages/skills/README.md",
      "https://github.com/remotion-dev/skills/tree/7c5c10caa5294d01b168a08c9648b4deef717274",
    ],
    accessedOn: ACCESSED_ON,
    stability: "commit-pinned-at-cutoff",
    revision: "remotion 7aee2f4b3d5c05c77761f2dc6ec5aeac701dcce8; skills 7c5c10caa5294d01b168a08c9648b4deef717274",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link to the maintained skills and paraphrase their scope. The standalone skills repository has no root license grant, and a skill never changes the Remotion runtime license.",
    rightsDecisionZhHans: "链接维护中的 skills 并转述其范围。独立 skills 仓库根目录没有许可证授权，而且 skill 不会改变 Remotion runtime 许可证。",
    supports: "Agent guidance for creating, marking up, previewing, rendering, captioning, and maintaining Remotion projects from Codex, Claude Code, Cursor, and related hosts.",
    supportsZhHans: "为 Codex、Claude Code、Cursor 等宿主提供创建、编写、预览、渲染、字幕和维护 Remotion 项目的智能体操作知识。",
    boundary: "A skill is operational guidance for a host agent, not an editing agent, model, renderer, or proof that a generated composition is correct. The standalone skills repository does not publish a root LICENSE at the research cutoff.",
    boundaryZhHans: "Skill 是供宿主智能体使用的操作知识，不是剪辑智能体、模型或渲染器，也不能证明生成的 composition 正确；研究截止时独立 skills 仓库根目录未发布 LICENSE。",
  },
  {
    id: "opentimelineio",
    kind: "github-repository",
    role: "timeline-contract",
    repository: "AcademySoftwareFoundation/OpenTimelineIO",
    title: "OpenTimelineIO",
    publisher: "Academy Software Foundation",
    url: "https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/44236713c1db295a6ffc66189ae98dbdfd0cb9c4/README.md",
    claimEvidenceUrls: [
      "https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/44236713c1db295a6ffc66189ae98dbdfd0cb9c4/README.md",
      "https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/44236713c1db295a6ffc66189ae98dbdfd0cb9c4/LICENSE.txt",
    ],
    versionAnchorUrl: "https://github.com/AcademySoftwareFoundation/OpenTimelineIO/releases/tag/v0.18.1",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v0.18.1 pre-release",
    resolvedCommit: "44236713c1db295a6ffc66189ae98dbdfd0cb9c4",
    license: "Apache-2.0",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Use an original JSON teaching schema inspired by timeline concepts; link to OTIO for production interchange.",
    rightsDecisionZhHans: "使用受时间线概念启发的原创教学 JSON schema；生产交换则链接 OTIO。",
    supports: "A versioned, inspectable representation of editorial cut order, timing, tracks, transitions, metadata, and external media references, with adapter-based interchange.",
    supportsZhHans: "以有版本、可检查的形式表示剪辑顺序、时间、轨道、转场、元数据和外部媒体引用，并通过适配器交换。",
    boundary: "v0.18.1 is marked pre-release. Core .otio data references rather than embeds media; .otioz/.otiod adapters can bundle associated media, but OTIO still does not decode, encode, or render it. Adapter availability and fidelity vary by interchange format.",
    boundaryZhHans: "v0.18.1 被标为 pre-release。核心 .otio 数据引用而不内嵌媒体；.otioz/.otiod 适配器可打包相关媒体，但 OTIO 仍不解码、编码或渲染。不同交换格式的适配器可用性与保真度各异。",
  },
  {
    id: "whisper",
    kind: "github-repository",
    role: "analysis-component",
    repository: "openai/whisper",
    title: "Whisper",
    publisher: "OpenAI",
    url: "https://github.com/openai/whisper/blob/31243bad24cc746f07d4c8bfdd2d974872cb1803/README.md",
    claimEvidenceUrls: [
      "https://github.com/openai/whisper/blob/31243bad24cc746f07d4c8bfdd2d974872cb1803/README.md",
      "https://github.com/openai/whisper/blob/31243bad24cc746f07d4c8bfdd2d974872cb1803/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/openai/whisper/releases/tag/v20250625",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v20250625",
    resolvedCommit: "31243bad24cc746f07d4c8bfdd2d974872cb1803",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link to upstream and use learner-owned sample transcripts; never redistribute third-party recordings.",
    rightsDecisionZhHans: "链接上游并使用学习者自有样本转录；绝不再分发第三方录音。",
    supports: "Local multilingual speech recognition and timestamped transcription as one evidence channel for dialogue editing.",
    supportsZhHans: "本地多语言语音识别与带时间戳转录，可作为对白剪辑的一条证据通道。",
    boundary: "Recognition errors, names, numbers, negation, and timing boundaries require review. Whisper alone does not assign speakers; labels from a separate diarization component also require review. A transcript is not permission to alter meaning.",
    boundaryZhHans: "识别错误、人名、数字、否定词与时间边界都需复核。Whisper 本身不分配说话人；独立 diarization 组件给出的标签也需复核。转录文本并不授权改变原意。",
  },
  {
    id: "whisperx",
    kind: "github-repository",
    role: "analysis-component",
    repository: "m-bain/whisperX",
    title: "WhisperX",
    publisher: "WhisperX maintainers",
    url: "https://github.com/m-bain/whisperX/blob/3ccc17b8de34f305300f8a3fd3c9f76ba820c0d0/README.md",
    claimEvidenceUrls: [
      "https://github.com/m-bain/whisperX/blob/3ccc17b8de34f305300f8a3fd3c9f76ba820c0d0/README.md",
      "https://github.com/m-bain/whisperX/blob/3ccc17b8de34f305300f8a3fd3c9f76ba820c0d0/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/m-bain/whisperX/releases/tag/v3.8.6",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v3.8.6",
    resolvedCommit: "3ccc17b8de34f305300f8a3fd3c9f76ba820c0d0",
    license: "BSD-2-Clause",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link and paraphrase alignment concepts; model downloads and diarization terms must be reviewed separately.",
    rightsDecisionZhHans: "链接并转述对齐概念；模型下载与说话人分离条款需单独审查。",
    supports: "Forced alignment for word-level timestamps and optional diarization layered on a faster-whisper transcription backend.",
    supportsZhHans: "在 faster-whisper 转录后端上增加强制对齐的词级时间戳与可选说话人分离。",
    boundary: "Word alignment can still fail at accents, overlap, music, unsupported languages, or transcript errors; some diarization models require a token and separate terms.",
    boundaryZhHans: "口音、重叠语音、音乐、不支持语言或转录错误仍会使词对齐失败；部分说话人分离模型需要令牌和单独条款。",
  },
  {
    id: "pyscenedetect",
    kind: "github-repository",
    role: "analysis-component",
    repository: "Breakthrough/PySceneDetect",
    title: "PySceneDetect",
    publisher: "PySceneDetect maintainers",
    url: "https://github.com/Breakthrough/PySceneDetect/blob/6ebb72392de8acfb6c539bf15d0aa912ce7ab6b2/README.md",
    claimEvidenceUrls: [
      "https://github.com/Breakthrough/PySceneDetect/blob/6ebb72392de8acfb6c539bf15d0aa912ce7ab6b2/README.md",
      "https://github.com/Breakthrough/PySceneDetect/blob/6ebb72392de8acfb6c539bf15d0aa912ce7ab6b2/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/Breakthrough/PySceneDetect/releases/tag/v0.7.1",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v0.7.1",
    resolvedCommit: "6ebb72392de8acfb6c539bf15d0aa912ce7ab6b2",
    license: "BSD-3-Clause",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link to the detector documentation and publish only original threshold experiments.",
    rightsDecisionZhHans: "链接检测器文档，仅发布原创阈值实验。",
    supports: "Content, adaptive, and threshold detectors can produce candidate shot boundaries, scene lists or CSV output, and representative stills that a separate course step can assemble into a contact-sheet index.",
    supportsZhHans: "内容、自适应和阈值检测器可生成候选镜头边界、场景清单或 CSV 及代表帧；课程另行把这些代表帧组装为联系表索引。",
    boundary: "Shot-boundary detection finds visual transitions, not semantic scenes; camera motion, flashes, fades, and thresholds produce different errors.",
    boundaryZhHans: "镜头边界检测发现视觉切换而非语义场景；镜头运动、闪光、淡化和阈值会产生不同错误。",
  },
  {
    id: "qwen3-vl",
    kind: "github-repository",
    role: "analysis-component",
    repository: "QwenLM/Qwen3-VL",
    title: "Qwen3-VL",
    publisher: "QwenLM",
    url: "https://github.com/QwenLM/Qwen3-VL/blob/96588727e44c78b25ba03ea03b8e12f7e64fd0da/README.md",
    claimEvidenceUrls: [
      "https://github.com/QwenLM/Qwen3-VL/blob/96588727e44c78b25ba03ea03b8e12f7e64fd0da/README.md",
      "https://github.com/QwenLM/Qwen3-VL/blob/96588727e44c78b25ba03ea03b8e12f7e64fd0da/LICENSE",
      "https://github.com/QwenLM/Qwen3-VL/issues/1761",
    ],
    accessedOn: ACCESSED_ON,
    stability: "commit-pinned-at-cutoff",
    revision: "96588727e44c78b25ba03ea03b8e12f7e64fd0da",
    license: "Apache-2.0 for repository code; model terms are separate",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Teach candidate labeling with locally supplied frames; learners must inspect the selected model's terms and privacy path.",
    rightsDecisionZhHans: "用本地提供的帧讲解候选标注；学习者必须检查所选模型的条款与隐私路径。",
    supports: "Long-video understanding, OCR, descriptions, and approximate text-to-time localization useful for proposing candidate segments from sampled visual evidence.",
    supportsZhHans: "长视频理解、OCR、描述和近似文本时间定位，可从抽样视觉证据中提出候选片段。",
    boundary: "Model timestamps and semantic labels are hypotheses, not frame-accurate truth. Open issue #1761 is one unverified user report of a possible frame-list time-axis mismatch, not a maintainer-confirmed or universal defect.",
    boundaryZhHans: "模型时间戳与语义标签是候选假设而非逐帧真值。开放中的 issue #1761 是一条未经维护者确认的用户个案报告，不代表普遍缺陷。",
  },
  {
    id: "vmaf",
    kind: "github-repository",
    role: "quality-control",
    repository: "Netflix/vmaf",
    title: "VMAF",
    publisher: "Netflix",
    url: "https://github.com/Netflix/vmaf/blob/3f9e02af258a5c0e30124fc585a3c3af90126dee/README.md",
    claimEvidenceUrls: [
      "https://github.com/Netflix/vmaf/blob/3f9e02af258a5c0e30124fc585a3c3af90126dee/README.md",
      "https://github.com/Netflix/vmaf/blob/3f9e02af258a5c0e30124fc585a3c3af90126dee/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/Netflix/vmaf/releases/tag/v3.2.0",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v3.2.0",
    resolvedCommit: "3f9e02af258a5c0e30124fc585a3c3af90126dee",
    license: "BSD-2-Clause-Patent",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link to upstream and use only on learner-controlled reference/distorted pairs.",
    rightsDecisionZhHans: "链接上游，并仅在学习者控制的参考/失真成对素材上使用。",
    supports: "Full-reference perceptual video-quality assessment for aligned reference and distorted versions of the same content after encoding or processing.",
    supportsZhHans: "对同一内容经编码或处理后的对齐参考/失真版本进行全参考感知视频质量评估。",
    boundary: "VMAF does not judge narrative, truth, captions, music choice, or differently edited timelines and must not be used as a universal quality score.",
    boundaryZhHans: "VMAF 不判断叙事、真实性、字幕、音乐选择或不同剪辑时间线，不能当作通用质量分数。",
  },
  {
    id: "auto-editor",
    kind: "github-repository",
    role: "deterministic-automation",
    repository: "WyattBlue/auto-editor",
    title: "Auto-Editor",
    publisher: "Auto-Editor maintainers",
    url: "https://github.com/WyattBlue/auto-editor/blob/2f7ba68049ee67317a7afe6a0555ea6cf30ad101/README.md",
    claimEvidenceUrls: [
      "https://github.com/WyattBlue/auto-editor/blob/2f7ba68049ee67317a7afe6a0555ea6cf30ad101/README.md",
      "https://github.com/WyattBlue/auto-editor/blob/2f7ba68049ee67317a7afe6a0555ea6cf30ad101/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/WyattBlue/auto-editor/releases/tag/31.5.0",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "31.5.0",
    resolvedCommit: "2f7ba68049ee67317a7afe6a0555ea6cf30ad101",
    license: "Unlicense",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link to the project and teach original rule-threshold experiments on synthetic footage.",
    rightsDecisionZhHans: "链接项目，并在合成素材上讲授原创规则阈值实验。",
    supports: "Rule-driven first-pass editing based on loudness and motion, with exports to several NLE timeline formats.",
    supportsZhHans: "基于响度与运动的规则型初剪，并可导出到若干 NLE 时间线格式。",
    boundary: "It is deterministic automation, not an agent; aggressive thresholds can damage breath, timing, sentence boundaries, or deliberate silence.",
    boundaryZhHans: "它是确定性自动化而非智能体；过激阈值可能破坏呼吸、节奏、句子边界或有意停顿。",
  },
  {
    id: "videodb-director",
    kind: "github-repository",
    role: "agent-architecture",
    repository: "video-db/Director",
    title: "Director: AI video agents framework",
    publisher: "VideoDB",
    url: "https://github.com/video-db/Director/blob/70e0b3dfdf59c679a25f4bea511e3cc4c5f2457f/README.md",
    claimEvidenceUrls: [
      "https://github.com/video-db/Director/blob/70e0b3dfdf59c679a25f4bea511e3cc4c5f2457f/README.md",
      "https://github.com/video-db/Director/blob/70e0b3dfdf59c679a25f4bea511e3cc4c5f2457f/LICENSE",
      "https://github.com/video-db/Director/releases/tag/First",
    ],
    accessedOn: ACCESSED_ON,
    stability: "commit-pinned-at-cutoff",
    revision: "70e0b3dfdf59c679a25f4bea511e3cc4c5f2457f; latest named release v0.1.1",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Use as an architecture reading and link to code; do not make the cloud-dependent repository a required course runtime.",
    rightsDecisionZhHans: "作为架构阅读并链接代码；不把依赖云服务的仓库设为课程必需运行时。",
    supports: "A multi-agent framework in which a reasoning engine selects video search, scene, editing, subtitle, and sharing capabilities from a natural-language request.",
    supportsZhHans: "多智能体框架：推理引擎从自然语言请求中选择视频搜索、场景、剪辑、字幕与分享能力。",
    boundary: "It relies on VideoDB infrastructure and an API key; repository visibility and demos do not establish local privacy or production reliability.",
    boundaryZhHans: "它依赖 VideoDB 基础设施与 API 密钥；仓库可见和演示不能证明本地隐私或生产可靠性。",
  },
  {
    id: "montaj",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "theSamPadilla/montaj",
    title: "Montaj agent video toolkit",
    publisher: "Montaj maintainers",
    url: "https://github.com/theSamPadilla/montaj/blob/634d523f4b022a19c5cf98ffa4f9e609178437c7/README.md",
    claimEvidenceUrls: [
      "https://github.com/theSamPadilla/montaj/blob/634d523f4b022a19c5cf98ffa4f9e609178437c7/README.md",
      "https://github.com/theSamPadilla/montaj/blob/634d523f4b022a19c5cf98ffa4f9e609178437c7/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/theSamPadilla/montaj/releases/tag/v3.10.1",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v3.10.1",
    resolvedCommit: "634d523f4b022a19c5cf98ffa4f9e609178437c7",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Teach the schema-and-tool pattern through original fixtures; link to Montaj for optional exploration.",
    rightsDecisionZhHans: "用原创 fixture 讲解 schema 与工具模式；链接 Montaj 供选修探索。",
    supports: "Small JSON-schema operations, workflow steps, a project source of truth, and pending-to-draft-to-human-final lifecycle designed for an external host agent.",
    supportsZhHans: "面向外部宿主智能体的小型 JSON-schema 操作、工作流步骤、项目事实源，以及 pending→draft→human final 生命周期。",
    boundary: "Montaj explicitly does not supply the reasoning agent; it is new, low-adoption, and some generation paths invoke paid providers.",
    boundaryZhHans: "Montaj 明确不提供推理智能体；项目较新、采用度低，部分生成路径会调用付费服务商。",
  },
  {
    id: "timeline-studio",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "MartinDelophy/ai-video-editor",
    title: "Timeline Studio agent editing surface",
    publisher: "Timeline Studio maintainers",
    url: "https://github.com/MartinDelophy/ai-video-editor/blob/2a59ffcfc6042deb56456cdadf6434ce39a647cd/README.md",
    claimEvidenceUrls: [
      "https://github.com/MartinDelophy/ai-video-editor/blob/2a59ffcfc6042deb56456cdadf6434ce39a647cd/README.md",
      "https://github.com/MartinDelophy/ai-video-editor/blob/2a59ffcfc6042deb56456cdadf6434ce39a647cd/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/MartinDelophy/ai-video-editor/releases/tag/v1.0.5",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v1.0.5",
    resolvedCommit: "2a59ffcfc6042deb56456cdadf6434ce39a647cd",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Paraphrase inspect, diff, dry-run, and transaction patterns; do not embed third-party demo assets.",
    rightsDecisionZhHans: "转述 inspect、diff、dry-run 与事务模式；不嵌入第三方演示资产。",
    supports: "Stable clip IDs, project inspection, plan diffs, dry runs, transactional writes, idempotent operation IDs, and an editable timeline source of truth.",
    supportsZhHans: "稳定 clip ID、工程检查、计划差异、dry-run、事务写入、幂等 operation ID 与可编辑时间线事实源。",
    boundary: "The project is only weeks old at the research cutoff, and its headless renderer covers a documented subset rather than every browser-editor operation. The v1.0.5 tag resolves to code whose package.json still reports 1.0.0, so the tag and package version must be recorded separately.",
    boundaryZhHans: "研究截止时该项目仅发布数周，headless 渲染器只覆盖文档声明子集。v1.0.5 tag 对应代码的 package.json 仍写 1.0.0，因此必须分开记录 tag 与包版本。",
  },
  {
    id: "qcut",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "Quriosity-agent/qcut",
    title: "QCut editor and structured CLI",
    publisher: "QCut maintainers",
    url: "https://github.com/Quriosity-agent/qcut/blob/d297613a965102caf45cd5f7cbd0d407340b3dcd/README.md",
    claimEvidenceUrls: [
      "https://github.com/Quriosity-agent/qcut/blob/d297613a965102caf45cd5f7cbd0d407340b3dcd/README.md",
      "https://github.com/Quriosity-agent/qcut/blob/d297613a965102caf45cd5f7cbd0d407340b3dcd/qcut/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/Quriosity-agent/qcut/releases/tag/v2026.08.26.1",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v2026.08.26.1",
    resolvedCommit: "d297613a965102caf45cd5f7cbd0d407340b3dcd",
    license: "MIT for qcut source tree; providers and assets remain separate",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link to the editor and teach the shared-visible-state pattern without copying provider assets.",
    rightsDecisionZhHans: "链接编辑器并讲解人机共享可见状态模式，不复制服务商资产。",
    supports: "A desktop NLE, machine-readable CLI, and agent plugins that let humans and agents work against one visible multitrack project.",
    supportsZhHans: "桌面 NLE、机器可读 CLI 与智能体插件，使人和智能体在同一个可见多轨工程上工作。",
    boundary: "Editor control requires the app, optional analysis or generation may upload selected media, and the public project is still young.",
    boundaryZhHans: "编辑器控制需要启动应用；可选分析或生成可能上传所选媒体，且公开项目仍较新。",
  },
  {
    id: "velorn",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "VelornLabs/velorn",
    title: "Velorn local MCP video editor",
    publisher: "Velorn Labs",
    url: "https://github.com/VelornLabs/velorn/blob/90aa9028ee38a98458c6fbd9a9a79b189462e019/README.md",
    claimEvidenceUrls: [
      "https://github.com/VelornLabs/velorn/blob/90aa9028ee38a98458c6fbd9a9a79b189462e019/README.md",
      "https://github.com/VelornLabs/velorn/blob/90aa9028ee38a98458c6fbd9a9a79b189462e019/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/VelornLabs/velorn/releases/tag/v0.3.29",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v0.3.29",
    resolvedCommit: "90aa9028ee38a98458c6fbd9a9a79b189462e019",
    license: "GPL-3.0-only",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Use as a linked safety-pattern case; do not copy GPL code into course fixtures.",
    rightsDecisionZhHans: "作为安全模式案例链接；不把 GPL 代码复制到课程 fixture。",
    supports: "A desktop timeline with many local MCP tools, preview-first write operations, undoable ordinary edits, and queued generation/export actions.",
    supportsZhHans: "带大量本地 MCP 工具的桌面时间线，多数写操作先预览，普通编辑可撤销，生成与导出进入队列。",
    boundary: "Some generation depends on local ComfyUI; v0.3.29 also adds optional Pexels search/import that requires a configured API key and network access. Some workflows are beta, and not every filesystem or project action is undoable.",
    boundaryZhHans: "部分生成依赖本地 ComfyUI；v0.3.29 另有需配置 API key 与联网的可选 Pexels 搜索/导入。部分工作流仍为 beta，并非所有文件系统或工程动作都可撤销。",
  },
  {
    id: "veac",
    kind: "github-repository",
    role: "timeline-contract",
    repository: "AgentsMesh/veac",
    title: "VEAC agent-first video editing DSL",
    publisher: "AgentsMesh",
    url: "https://github.com/AgentsMesh/veac/blob/e3472918a8c05fe53be1c2bf6c6a76cd5730d8af/README.md",
    claimEvidenceUrls: [
      "https://github.com/AgentsMesh/veac/blob/e3472918a8c05fe53be1c2bf6c6a76cd5730d8af/README.md",
      "https://github.com/AgentsMesh/veac/blob/e3472918a8c05fe53be1c2bf6c6a76cd5730d8af/docs/architecture.md",
      "https://github.com/AgentsMesh/veac/blob/e3472918a8c05fe53be1c2bf6c6a76cd5730d8af/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/AgentsMesh/veac/releases/tag/v0.2.0",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v0.2.0",
    resolvedCommit: "e3472918a8c05fe53be1c2bf6c6a76cd5730d8af",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Link as an emerging DSL example and use an original constrained edit-plan schema in the lab.",
    rightsDecisionZhHans: "作为新兴 DSL 示例链接，在实验中使用原创受约束 edit-plan schema。",
    supports: "An agent-readable DSL compiled to FFmpeg, with explicit checks, an intermediate representation, and dry-run output before execution.",
    supportsZhHans: "面向智能体、编译到 FFmpeg 的 DSL，提供显式检查、中间表示与执行前 dry-run 输出。",
    boundary: "The documented scope is constrained and does not establish feature parity with a full NLE. The v0.2.0 tag resolves to a workspace whose Cargo.toml still reports 0.1.0; record the tag and package version separately. Manifests, packaging, and relinking are course design requirements, not verified VEAC features.",
    boundaryZhHans: "文档所示范围有限，不能据此认定与完整 NLE 功能对等。v0.2.0 tag 对应 workspace 的 Cargo.toml 仍写 0.1.0，必须分开记录 tag 与包版本。清单、打包和 relink 是课程设计要求，并非已核验的 VEAC 功能。",
  },
  {
    id: "video-edit-cli",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "computerlovetech/video-edit-cli",
    title: "video-edit-cli",
    publisher: "Computer Love Technology",
    url: "https://github.com/computerlovetech/video-edit-cli/blob/69aeeec7dad7470c1379c7115cbd4d96a4be8686/README.md",
    claimEvidenceUrls: [
      "https://github.com/computerlovetech/video-edit-cli/blob/69aeeec7dad7470c1379c7115cbd4d96a4be8686/README.md",
      "https://github.com/computerlovetech/video-edit-cli/blob/69aeeec7dad7470c1379c7115cbd4d96a4be8686/skills/video-edit-cli/references/edit-plan.md",
      "https://github.com/computerlovetech/video-edit-cli/blob/69aeeec7dad7470c1379c7115cbd4d96a4be8686/src/video_editor/inspection.py",
      "https://github.com/computerlovetech/video-edit-cli/blob/69aeeec7dad7470c1379c7115cbd4d96a4be8686/LICENSE",
    ],
    versionAnchorUrl: "https://github.com/computerlovetech/video-edit-cli/releases/tag/v0.1.2",
    accessedOn: ACCESSED_ON,
    stability: "release-pinned",
    revision: "v0.1.2",
    resolvedCommit: "69aeeec7dad7470c1379c7115cbd4d96a4be8686",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Paraphrase non-destructive JSON and provenance patterns; the lab ships its own schema and fixtures.",
    rightsDecisionZhHans: "转述非破坏性 JSON 与 provenance 模式；实验提供自己的 schema 与 fixture。",
    supports: "Fixed video operations with JSON stdout, ordered keep decisions with reasons, inspection artifacts, and provenance sidecars suitable for agent tool calls.",
    supportsZhHans: "具有 JSON stdout、带理由的有序保留决策、检查产物与 provenance sidecar 的固定视频操作，适合智能体调用。",
    boundary: "The project has minimal public adoption and must not be treated as a mature production dependency solely because its interface is well shaped.",
    boundaryZhHans: "项目公开采用度很低，不能只因接口设计良好就把它视为成熟生产依赖。",
  },
  {
    id: "davinci-resolve-mcp",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "samuelgursky/davinci-resolve-mcp",
    title: "DaVinci Resolve MCP Server",
    publisher: "Samuel Gursky",
    url: "https://github.com/samuelgursky/davinci-resolve-mcp/blob/c3c075bcc930b4f967b3abae3073bc48e435c5af/docs/guides/media-analysis-guide.md",
    claimEvidenceUrls: [
      "https://github.com/samuelgursky/davinci-resolve-mcp/blob/c3c075bcc930b4f967b3abae3073bc48e435c5af/docs/guides/media-analysis-guide.md",
      "https://github.com/samuelgursky/davinci-resolve-mcp/blob/c3c075bcc930b4f967b3abae3073bc48e435c5af/examples/README.md",
      "https://github.com/samuelgursky/davinci-resolve-mcp/blob/c3c075bcc930b4f967b3abae3073bc48e435c5af/README.md",
      "https://github.com/samuelgursky/davinci-resolve-mcp/blob/c3c075bcc930b4f967b3abae3073bc48e435c5af/LICENSE",
    ],
    accessedOn: ACCESSED_ON,
    stability: "commit-pinned-at-cutoff",
    revision: "c3c075bcc930b4f967b3abae3073bc48e435c5af",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Record the pinned MIT license and link or paraphrase safety guidance; no repository code or screenshots are copied into the course.",
    rightsDecisionZhHans: "记录固定版本的 MIT 许可证并链接或转述安全指南；课程不复制仓库代码或截图。",
    supports: "Read-only source-media inspection, sidecar analysis, dry-run plans before mutation, disposable test projects, and explicit recovery guidance for an MCP-operated NLE.",
    supportsZhHans: "在 MCP 操作的 NLE 中先只读检查源素材、把分析写入 sidecar、变更前 dry-run、使用一次性测试工程并明确恢复说明。",
    boundary: "This community project is not a Blackmagic Design product, Resolve scripting support is version/edition sensitive, and tool access does not supply editorial judgment.",
    boundaryZhHans: "这是社区项目而非 Blackmagic Design 产品；Resolve 脚本支持受版本与版本类型影响，工具访问本身不提供剪辑判断。",
  },
  {
    id: "mosaic-skills",
    kind: "github-repository",
    role: "agent-tool-surface",
    repository: "mosaic-ai-labs/skills",
    title: "Mosaic agent skills",
    publisher: "Mosaic",
    url: "https://github.com/mosaic-ai-labs/skills/tree/8331979eb00cc4840a78fddf2355c4a04c0c3219",
    claimEvidenceUrls: [
      "https://github.com/mosaic-ai-labs/skills/tree/8331979eb00cc4840a78fddf2355c4a04c0c3219",
      "https://github.com/mosaic-ai-labs/skills/blob/8331979eb00cc4840a78fddf2355c4a04c0c3219/LICENSE",
      "https://docs.mosaic.so/api/introduction",
      "https://mosaic.so/legal",
    ],
    accessedOn: ACCESSED_ON,
    stability: "commit-pinned-at-cutoff",
    revision: "8331979eb00cc4840a78fddf2355c4a04c0c3219",
    license: "MIT",
    reuseStatus: "license-noted-no-code-copy",
    rightsDecision: "Record the pinned MIT license and link to public skills and documentation; do not copy code, branded assets, example footage, or provider output.",
    rightsDecisionZhHans: "记录固定版本的 MIT 许可证并链接公开 skills 与文档；不复制代码、品牌资产、示例素材或服务商输出。",
    supports: "An agent-callable cloud workflow surface for uploaded or referenced video, graph-based processing, asynchronous runs, output timelines, and optional social publishing.",
    supportsZhHans: "面向智能体的云工作流：处理上传或引用的视频、执行图式流程、异步运行、输出时间线并可选发布到社交平台。",
    boundary: "Media and project data may be handled by Mosaic and its service providers. The API requires a key and may consume plan credits; social publishing also requires an authorized connected account. API capability does not grant source-media rights or justify unattended publishing.",
    boundaryZhHans: "媒体与工程数据可能由 Mosaic 及其服务提供商处理。API 需要密钥并可能消耗套餐 credits；社交发布还需要已授权连接的账号。API 能力不授予源素材权利，也不能合理化无人值守发布。",
  },
  {
    id: "x-video-use-release",
    kind: "x-post",
    role: "field-signal",
    title: "Introducing Video Use",
    publisher: "Gregor Zunic on X",
    url: "https://x.com/gregpr07/status/2044554557221675380",
    claimEvidenceUrls: [
      "https://x.com/gregpr07/status/2044554557221675380",
      "https://publish.x.com/oembed?url=https%3A%2F%2Fx.com%2Fgregpr07%2Fstatus%2F2044554557221675380",
    ],
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-04-15",
    stability: "dated-field-signal",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase the dated post; do not copy the post video, screenshots, or wording.",
    rightsDecisionZhHans: "链接并转述该有日期的帖子；不复制帖子视频、截图或原文表达。",
    supports: "A project-author launch signal whose oEmbed-visible text describes a talk-to-camera workflow producing final.mp4 while a coding agent handles filler removal, color correction, captions, and animations. Silence handling is documented by the repository, not the visible oEmbed excerpt.",
    supportsZhHans: "项目作者的发布信号；oEmbed 可见文本说明对镜头讲话的工作流输出 final.mp4，同时编码智能体处理口头填充、调色、字幕与动画。静音处理来自仓库文档，而非 oEmbed 可见片段。",
    boundary: "A launch demo and author claim do not establish universal quality, reliability, time savings, or zero cost; repository inspection supplies the technical corroboration.",
    boundaryZhHans: "发布演示与作者自述不能证明普遍质量、可靠性、节时或零成本；技术佐证来自仓库检查。",
    statusId: "2044554557221675380",
    authorIdentity: "Gregor Zunic (@gregpr07)",
    authorRole: "Post author; project relationship is corroborated by the paired repository, not inferred from oEmbed alone",
    threadContext: "Thread topology was not independently established. The oEmbed text is truncated; identity, date, URL, and only the visible launch text were checked through X official oEmbed. Direct status-page access was inconsistent during the audit and is not used as the text record.",
    mediaContext: "Linked demonstration media is not copied, embedded, or treated as a reproducible benchmark.",
    textCompleteness: "oembed-truncated-repository-corroborated",
    verificationMethod: "x-official-oembed",
    verifiedOn: ACCESSED_ON,
    verificationStatus: "identity-date-url-verified-visible-text-truncated",
    corroborationScope: "oEmbed verifies identity, date, URL, and a truncated launch statement; the pinned repositories corroborate workflow mechanisms only, not quality, savings, or the full post wording.",
    corroborationScopeZhHans: "oEmbed 核验身份、日期、URL 与被截断的发布陈述；固定仓库只佐证工作流机制，不佐证质量、节时或帖子全文。",
    corroboratingSourceIds: ["video-use", "ffmpeg"],
  },
  {
    id: "x-remotion-skills",
    kind: "x-post",
    role: "field-signal",
    title: "Remotion now has Agent Skills",
    publisher: "Remotion on X",
    url: "https://x.com/Remotion/status/2013626968386765291",
    claimEvidenceUrls: [
      "https://x.com/Remotion/status/2013626968386765291",
      "https://publish.x.com/oembed?url=https%3A%2F%2Fx.com%2FRemotion%2Fstatus%2F2013626968386765291",
    ],
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-01-20",
    stability: "dated-field-signal",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link to the official post and repository; no post media is republished.",
    rightsDecisionZhHans: "链接官方帖子与仓库；不再发布帖子媒体。",
    supports: "An official dated announcement that Remotion publishes Agent Skills for coding-agent video workflows.",
    supportsZhHans: "Remotion 官方发布的有日期公告，说明其为编码智能体视频工作流提供 Agent Skills。",
    boundary: "The announcement establishes availability, not that one prompt reliably produces a finished edit or that every use is covered by a free license.",
    boundaryZhHans: "该公告只证明功能可用，不证明一句提示词能可靠完成成片，也不证明所有使用都属于免费许可。",
    statusId: "2013626968386765291",
    authorIdentity: "Remotion (@Remotion)",
    authorRole: "Official project account",
    threadContext: "Thread topology was not independently established; the announcement text used by the course is complete in X official oEmbed.",
    mediaContext: "Demonstration media is linked only and is not used as a quality benchmark.",
    textCompleteness: "oembed-complete",
    verificationMethod: "x-official-oembed",
    verifiedOn: ACCESSED_ON,
    verificationStatus: "identity-date-url-and-visible-text-verified",
    corroborationScope: "oEmbed contains the complete announcement used by the course; repositories corroborate availability and scope, not generated-output quality.",
    corroborationScopeZhHans: "oEmbed 包含课程使用的完整公告；仓库佐证可用性与能力范围，不佐证生成结果质量。",
    corroboratingSourceIds: ["remotion", "remotion-skills"],
  },
  {
    id: "x-davinci-mcp",
    kind: "x-post",
    role: "field-signal",
    title: "DaVinci Resolve MCP Server showcase",
    publisher: "GitHub Projects Community on X",
    url: "https://x.com/GithubProjects/status/2075105180023144837",
    claimEvidenceUrls: [
      "https://x.com/GithubProjects/status/2075105180023144837",
      "https://publish.x.com/oembed?url=https%3A%2F%2Fx.com%2FGithubProjects%2Fstatus%2F2075105180023144837",
    ],
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-07-09",
    stability: "dated-field-signal",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase capability categories; do not reuse the showcase media.",
    rightsDecisionZhHans: "链接并转述能力类别；不复用展示媒体。",
    supports: "A dated community showcase whose oEmbed-visible text lists project lifecycle, media-pool, editing, color-grading, Fusion, and Fairlight access through a Resolve MCP server.",
    supportsZhHans: "有日期的社区展示；oEmbed 可见文本列出 Resolve MCP server 的工程生命周期、媒体池、剪辑、调色、Fusion 与 Fairlight 访问。",
    boundary: "The display name says GitHub Projects Community; organizational affiliation is not inferred. Current tool counts and safety behavior must come from specifically cited repository documents.",
    boundaryZhHans: "显示名为 GitHub Projects Community；课程不据此推断组织隶属。当前工具数量与安全行为必须来自明确引用的仓库文档。",
    statusId: "2075105180023144837",
    authorIdentity: "GitHub Projects Community (@GithubProjects)",
    authorRole: "Showcase account; organizational affiliation is not established by oEmbed",
    threadContext: "Thread topology was not independently established. The oEmbed text is truncated; identity, date, URL, and the visible capability list were verified through X official oEmbed.",
    mediaContext: "Linked demo media is not copied and cannot establish the quality of arbitrary edits.",
    textCompleteness: "oembed-truncated-repository-corroborated",
    verificationMethod: "x-official-oembed",
    verifiedOn: ACCESSED_ON,
    verificationStatus: "identity-date-url-verified-visible-text-truncated",
    corroborationScope: "oEmbed verifies the display name, date, URL, and a truncated capability showcase; the pinned media-analysis guide and examples corroborate only a bounded, review-oriented subset and its safety patterns.",
    corroborationScopeZhHans: "oEmbed 核验显示名、日期、URL 与被截断的能力展示；固定 media-analysis guide 与 examples 只佐证有边界、面向审查的能力子集及安全模式。",
    corroboratingSourceIds: ["davinci-resolve-mcp"],
  },
  {
    id: "x-creator-workflow-guide",
    kind: "x-post",
    role: "field-signal",
    title: "Claude Code video-production guide expansion",
    publisher: "りょー on X",
    url: "https://x.com/cryptoninjanime/status/1955108960060706862",
    claimEvidenceUrls: [
      "https://x.com/cryptoninjanime/status/1955108960060706862",
      "https://publish.x.com/oembed?url=https%3A%2F%2Fx.com%2Fcryptoninjanime%2Fstatus%2F1955108960060706862",
    ],
    accessedOn: ACCESSED_ON,
    publishedOn: "2025-08-12",
    stability: "dated-field-signal",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and summarize only the oEmbed-visible guide-expansion statement; do not copy the attached video or infer the truncated continuation.",
    rightsDecisionZhHans: "只链接并概述 oEmbed 可见的指南扩展陈述；不复制附件视频，也不推断被截断的后文。",
    supports: "A dated creator signal whose visible oEmbed text says a planned Remotion-and-Claude-Code editing course broadened into a wider Claude Code video-production guide as more techniques and information emerged.",
    supportsZhHans: "有日期的创作者实践信号：oEmbed 可见文本说明，原拟的 Remotion×Claude Code 剪辑课程随着更多技术与信息出现，扩展为更广的 Claude Code 视频制作指南。",
    boundary: "The post does not publish the complete project, prompts, source footage, failure cases, or a comparative benchmark.",
    boundaryZhHans: "帖子没有公开完整工程、提示词、源素材、失败案例或对比基准。",
    statusId: "1955108960060706862",
    authorIdentity: "りょー｜AI動画制作・編集 (@cryptoninjanime)",
    authorRole: "Post author; no formal role or organizational affiliation is inferred from oEmbed",
    threadContext: "Creator guide-expansion post; identity, date, URL, and only the visible text were verified through X official oEmbed. The continuation is truncated and is not reconstructed from search snippets.",
    mediaContext: "Any attached or linked media is not copied and is not treated as performance evidence; media context was not independently verified.",
    textCompleteness: "oembed-truncated-repository-corroborated",
    verificationMethod: "x-official-oembed",
    verifiedOn: ACCESSED_ON,
    verificationStatus: "identity-date-url-verified-visible-text-truncated",
    corroborationScope: "The repositories corroborate the Remotion and agent-skill mechanisms only. The post supports scope expansion as a dated creator observation; it does not compare tool quality, efficiency, or human replacement.",
    corroborationScopeZhHans: "仓库只佐证 Remotion 与 agent skill 机制；帖子只支持有日期的创作者范围扩展观察，不比较工具质量、效率，也不证明可以取代人类。",
    corroboratingSourceIds: ["remotion", "remotion-skills"],
  },
  {
    id: "x-mosaic-slack",
    kind: "x-post",
    role: "field-signal",
    title: "Mosaic video editing API for agents",
    publisher: "Adish Jain on X",
    url: "https://x.com/_adishj/status/2032121100126265551",
    claimEvidenceUrls: [
      "https://x.com/_adishj/status/2032121100126265551",
      "https://publish.x.com/oembed?url=https%3A%2F%2Fx.com%2F_adishj%2Fstatus%2F2032121100126265551",
      "https://mosaic.so/legal",
    ],
    accessedOn: ACCESSED_ON,
    publishedOn: "2026-03-12",
    stability: "dated-field-signal",
    reuseStatus: "link-and-paraphrase-only",
    rightsDecision: "Link and paraphrase the workflow; the archived-footage demo and all post media are excluded from course assets.",
    rightsDecisionZhHans: "链接并转述工作流；档案素材演示及全部帖子媒体不进入课程资产。",
    supports: "A dated, oEmbed-truncated demonstration post whose visible text says a Slack-hosted agent used the Mosaic API to clip, edit, and post video.",
    supportsZhHans: "有日期、被 oEmbed 截断的演示帖；可见文本说明 Slack 中的智能体使用 Mosaic API 对视频进行 clip、edit 与 post。",
    boundary: "The post does not establish footage authorization, privacy suitability, output quality, or permission for unattended publishing; those require separate evidence and approval.",
    boundaryZhHans: "帖子不证明素材授权、隐私适用性、输出质量或无人值守发布权限；这些都需要单独证据与批准。",
    statusId: "2032121100126265551",
    authorIdentity: "Adish Jain (@_adishj)",
    authorRole: "Post author using first-person plural about Mosaic; no formal title is inferred from oEmbed",
    threadContext: "Demonstration post; oEmbed-truncated. Identity, date, URL, and the visible clip-edit-post statement were verified through X official oEmbed; thread structure was not independently established.",
    mediaContext: "The demonstration uses described archival footage whose authorization is not documented in the post; no media is copied.",
    textCompleteness: "oembed-truncated-repository-corroborated",
    verificationMethod: "x-official-oembed",
    verifiedOn: ACCESSED_ON,
    verificationStatus: "identity-date-url-verified-visible-text-truncated",
    corroborationScope: "oEmbed verifies identity, date, URL, and a truncated demonstration statement; Mosaic documentation corroborates API mechanics and its legal page supports the separate privacy boundary, but neither proves footage authorization or output quality.",
    corroborationScopeZhHans: "oEmbed 核验身份、日期、URL 与被截断的演示陈述；Mosaic 文档佐证 API 机制，legal 页面支撑独立隐私边界，但都不能证明素材授权或输出质量。",
    corroboratingSourceIds: ["mosaic-skills"],
  },
] as const satisfies readonly AgenticVideoEditingSourceRecord[];

export function getAgenticVideoEditingSource(
  id: string,
): AgenticVideoEditingSourceRecord {
  const source = AGENTIC_VIDEO_EDITING_SOURCES.find((item) => item.id === id);
  if (!source) throw new Error(`Unknown agentic-video-editing source: ${id}`);
  return source;
}
