import { AGENTIC_TEACHING_ARTIFACT_RUBRICS } from "../contracts";
import { bindAgenticTeachingCourseOptions } from "./bind-options";

const boundaryRubric = AGENTIC_TEACHING_ARTIFACT_RUBRICS.en["agentic-teaching-boundaries"];
const contractRubric = AGENTIC_TEACHING_ARTIFACT_RUBRICS.en["learning-design-task-contracts"];
const lessonRubric = AGENTIC_TEACHING_ARTIFACT_RUBRICS.en["teacher-copilot-workflows"];
const tutoringRubric = AGENTIC_TEACHING_ARTIFACT_RUBRICS.en["tutoring-feedback-agents"];
const multiAgentRubric = AGENTIC_TEACHING_ARTIFACT_RUBRICS.en["multi-agent-inquiry"];
const mcpRubric = AGENTIC_TEACHING_ARTIFACT_RUBRICS.en["knowledge-tools-mcp"];
const childSafetyRubric = AGENTIC_TEACHING_ARTIFACT_RUBRICS.en["k12-safeguards"];
const integrityRubric = AGENTIC_TEACHING_ARTIFACT_RUBRICS.en["higher-ed-integrity"];
const evalRubric = AGENTIC_TEACHING_ARTIFACT_RUBRICS.en["evals-learning-evidence"];
const pilotRubric = AGENTIC_TEACHING_ARTIFACT_RUBRICS.en["pilot-capstone"];

export const AGENTIC_TEACHING_COPY_EN = bindAgenticTeachingCourseOptions({
  meta: {
    title: "Agentic AI for K–12 and Higher Education",
    kicker: "Course 18 · Human-led teaching, inspectable agents",
    summary: "Design teacher-owned agents for planning, tutoring, feedback, inquiry and evaluation—grounded in inspectable GitHub implementations, dated X signals, bounded learning research and explicit child/data safeguards.",
    audience: "K–12 and university educators, learning designers, academic developers, education leaders and engineers",
    prerequisite: "Basic familiarity with prompts, JSON/APIs and one real teaching workflow; coding is helpful but not required for this course",
    level: "Beginner to advanced",
    duration: "12 hours · 10 modules · final assessment · evidence-pack capstone",
    evidenceNote: "GitHub shows what can be inspected and built. X shows what an identified account announced on a date. Neither, by itself, proves learning impact.",
    fallbackNotice: "This course has editorially reviewed English and Simplified Chinese editions. You are viewing the reviewed English edition because the requested locale is not yet reviewed.",
    credentialBoundary: "Progress, artifact checks and completion are private self-tracking in this browser. They are not identity-verified assessment, professional certification, legal approval or institutional authorisation.",
  },
  ui: {
    catalog: "Course catalogue",
    course: "Course",
    module: "Module",
    modules: "modules",
    minutes: "min",
    phase: "Phase",
    audience: "Audience",
    prerequisite: "Prerequisite",
    duration: "Duration",
    start: "Start the course",
    resume: "Resume",
    courseMap: "Course map",
    tracks: "Choose your teaching track",
    outcomes: "Outcomes you can inspect",
    principles: "Operating principles",
    objective: "Learning objective",
    artifact: "Evidence artifact",
    evidence: "Evidence mode",
    source: "Source",
    sources: "Sources",
    supports: "What it supports",
    boundary: "What it does not prove",
    accessed: "Accessed",
    practice: "Studio practice",
    steps: "Steps",
    reviewGate: "Human review gate",
    notebook: "Private artifact notebook",
    notebookHelp: "Saved only in this browser. Use synthetic or de-identified examples; never enter real student identities, credentials, health, disability, safeguarding or disciplinary information.",
    checkpoint: "Checkpoint",
    checkAnswer: "Check answer",
    correct: "Correct",
    incorrect: "Revisit the evidence boundary",
    completeModule: "Record module as complete",
    moduleCompleted: "Module recorded",
    checkpointFirst: "Pass the checkpoint before recording completion.",
    artifactFirst: "Complete the structured artifact evidence before recording completion.",
    artifactReady: "The local structure check is ready for human quality review.",
    artifactNeedsEvidence: "Still needed for the local structure check:",
    artifactLocaleNotice: "This saved draft was recorded under another reviewed language template. Its receipt remains valid until you explicitly save an edit in this language:",
    artifactRubric: "Artifact evidence rubric",
    progress: "Private course progress",
    saveArtifact: "Save artifact",
    savedLocally: "Saved locally",
    storageUnavailable: "Kept only for this session; browser storage is unavailable",
    finalAssessment: "Final assessment",
    submitAssessment: "Score all answers",
    assessmentPassed: "Assessment gate passed",
    assessmentNotPassed: "Gate not yet passed: reach 10/12 and answer every diamond question correctly",
    answerEveryQuestion: "Answer every question before scoring.",
    capstone: "Capstone",
    capstoneArtifacts: "Evidence-pack readiness",
    attestation: "Human review attestation",
    completeCapstone: "Record capstone self-check",
    capstoneCompleted: "Capstone self-check recorded",
    capstoneEvidenceReady: "Structured evidence present; human review is still required.",
    capstoneEvidenceMissing: "Complete the linked module artifact:",
    capstonePrerequisites: "Pass the final assessment and record all ten current modules before recording the capstone.",
    selfTrackingOnly: "This deterministic check verifies presence and structure only. It does not judge educational quality, confirm identity or issue a credential.",
    previous: "Previous",
    next: "Next",
    backToCourse: "Back to course",
    fallbackLabel: "Language fallback",
    sourceRegister: "Inspectable source register",
    fieldSignal: "Dated field signal—not impact evidence",
  },
  phases: {
    frame: {
      title: "Frame the teaching problem",
      summary: "Choose the smallest legitimate agent role, then make purpose, authority and stopping conditions inspectable.",
    },
    design: {
      title: "Design the human–agent workflow",
      summary: "Build teacher copilot, tutoring, multi-agent and knowledge-tool patterns around learning activity rather than automation theatre.",
    },
    govern: {
      title: "Govern people, data and judgement",
      summary: "Turn child rights, privacy, integrity, accessibility and appeal into actual system controls.",
    },
    prove: {
      title: "Prove, pilot and stop",
      summary: "Evaluate independent learning and failures, then make a reversible, evidence-bound release decision.",
    },
  },
  tracks: [
    {
      id: "k12",
      title: "K–12: low autonomy, adult accountability",
      summary: "Design age-appropriate coaching and teacher workflows with child-rights review before any learner-facing pilot.",
      focus: [
        "Teacher-selected curriculum, synthetic examples and explicit AI disclosure",
        "Student attempt before hints; no-AI transfer after support",
        "Qualified-adult escalation, parent/institution authority and a kill switch",
      ],
      startingModule: "agentic-teaching-boundaries",
    },
    {
      id: "higher-ed",
      title: "Higher education: integrity, evidence and appeal",
      summary: "Build course-bound assistants that preserve instructor judgement, learner authorship and research/assessment integrity.",
      focus: [
        "Syllabus and source grounding, disclosure and accessible alternatives",
        "Human judgement before AI feedback drafts; no automated misconduct findings",
        "Independent transfer tasks, opt-out, appeal and research-ethics review",
      ],
      startingModule: "agentic-teaching-boundaries",
    },
  ],
  principles: [
    "Begin with the learning objective and a non-agent baseline.",
    "Agents may propose; accountable educators decide consequential teaching actions.",
    "Use the smallest data, tool and action scope; read-only before write access.",
    "A trace says what happened. An evaluation asks whether it was good enough.",
    "Assisted performance is not independent learning; test transfer without AI.",
    "A release gate must be able to say no, pause the pilot and restore the previous process.",
  ],
  outcomes: [
    "Classify chatbot, copilot, workflow and agent roles by autonomy and consequence.",
    "Write an auditable teaching-agent contract with sources, permissions, approvals and stop rules.",
    "Design teacher copilot, hint-ladder tutor and editable-feedback workflows for both educational sectors.",
    "Connect approved knowledge through least-privilege tools and explain what MCP does not guarantee.",
    "Compare single- and multi-agent designs using quality, latency, cost and failure evidence.",
    "Run a bounded pilot with no-AI transfer, child/data controls, incident response and a go/no-go record.",
  ],
  modules: {
    "agentic-teaching-boundaries": {
      kicker: "01 · Frame",
      title: "Agentic teaching without an autonomous teacher",
      summary: "Decide when a loop with tools and state is justified, and keep educational responsibility outside the model.",
      objective: "Classify a teaching task by autonomy and consequence, then define the smallest agent role that adds a testable learning benefit.",
      artifact: "Agent boundary card",
      audienceScenarios: {
        k12: "Turn a teacher-selected practice routine into a low-authority coaching loop.",
        "higher-ed": "Triage office-hour questions without making academic decisions.",
      },
      humanApprovalPoints: ["Educator approves the purpose", "Educator sets the stopping condition"],
      noGoActions: ["Replace the teacher role", "Release an unreviewed high-impact output"],
      sections: [
        {
          heading: "Capability is not a teaching claim",
          paragraphs: [
            "Agents SDK repositories make tools, handoffs, guardrails, human approval and traces inspectable. That is evidence of an engineering surface—not evidence that students learn more, teachers save time or a school deployment is safe.",
            "Use four distinct labels: a chatbot answers; a copilot drafts for a person; a workflow follows explicit transitions; an agent chooses actions within bounded authority. Consequence, not novelty, determines the control level.",
          ],
          bullets: [
            "Use a normal prompt when the task needs no persistent state, tools or recovery.",
            "Use a workflow when the sequence and branches are known.",
            "Use an agent only when bounded adaptation is valuable and observable.",
          ],
          sourceIds: ["S01"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "Design for learning after assistance",
          paragraphs: [
            "A high-school mathematics experiment found that unguarded GPT improved assisted practice while the same group performed worse once AI was removed. The teacher-informed, guardrailed GPT Tutor largely mitigated that negative effect but did not show a positive independent-exam effect.",
            "The design implication is not that all AI harms learning. It is that completion with an agent and durable capability without an agent are different outcomes and must be measured separately.",
          ],
          bullets: [
            "Name the independent capability before choosing the tool.",
            "Require an unaided transfer task in a new example or context.",
            "Keep effect numbers attached to study, population, subject and outcome.",
          ],
          sourceIds: ["S09"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Read announcements as signals",
          paragraphs: [
            "The Study Mode X post documents how an official account framed a product launch on a date. It does not establish current behaviour, learning impact or safe use across ages.",
            "In this course, X creates a dated watchlist; repositories, current documentation, research and governance sources carry the instructional claims.",
          ],
          bullets: ["Record author, status ID and date.", "Keep a corroborating first-party source.", "Never turn product language into an effect estimate."],
          sourceIds: ["S13"],
          evidenceMode: "field-signal",
        },
      ],
      practice: {
        title: "Bound one real teaching task",
        brief: "Choose one task you currently own. Compare no AI, one prompt, a fixed workflow and a bounded agent before selecting the least complex defensible option.",
        steps: [
          "Write the learner move and the evidence that would show independent capability.",
          "List the decisions and actions the system could take, then mark their consequence.",
          "Assign every consequential decision to a named educator and add a stop condition.",
        ],
        artifact: "Agent boundary card",
        reviewGate: "A qualified educator confirms that the agent cannot publish, grade, contact, submit or change records without explicit approval.",
        starter: "Purpose:\n\nAgent action:\n\nHuman authority:\n\nStop condition:\n\nLearning evidence:\n",
        rubric: boundaryRubric,
      },
      checkpoint: {
        question: "Which observation is evidence that learners retained capability?",
        options: ["They completed more items while the agent was open", "They rated the interface highly", "They solved a novel task after the agent was removed", "The trace contained no runtime error"],
        correctIndex: 2,
        explanation: "An unaided transfer task tests what remains after assistance. Completion, satisfaction and a clean trace answer different questions.",
      },
      takeaway: "Automate a bounded learning move—not the role, relationship or responsibility of a teacher.",
    },
    "learning-design-task-contracts": {
      kicker: "02 · Frame",
      title: "Write the teaching-agent contract before the prompt",
      summary: "Turn outcomes, learners, sources, tools, data, approvals, stopping and evidence into a one-page operating contract.",
      objective: "Produce a contract another educator can audit, challenge and stop without reading model internals.",
      artifact: "Auditable teaching-agent contract",
      audienceScenarios: {
        k12: "Write an age-appropriate contract for a teacher-owned lesson objective.",
        "higher-ed": "Write a course-assistant contract constrained by syllabus and assessment policy.",
      },
      humanApprovalPoints: ["Educator signs the task contract", "Data owner approves every input class"],
      noGoActions: ["Operate with undefined authority", "Silently change course policy"],
      sections: [
        {
          heading: "Eight fields that prevent invisible scope creep",
          paragraphs: [
            "A defensible contract names the learner and context, independent outcome, approved knowledge, allowed tools, data class, human authority, prohibited actions and evaluation/stop rule. A prompt is implementation detail beneath this contract.",
            "The Agents SDK demonstrates approval and guardrail primitives. Your contract decides where those controls must exist for this teaching purpose.",
          ],
          bullets: ["One learning outcome, observable without AI", "Explicit read and write scopes", "A named owner who can pause and reverse"],
          sourceIds: ["S01"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "Age and context change the design",
          paragraphs: [
            "UNESCO foregrounds human agency, privacy and age-appropriate validation. UNICEF adds a child-rights lens: safety, fairness, transparency, accountability, inclusion and continuing oversight.",
            "These are governance anchors, not global law. The contract must still name the jurisdiction, institution policy, provider terms and accountable data owner.",
          ],
          bullets: ["Record whether minors or dual-enrolment learners are present.", "Tell learners when they are interacting with AI.", "Provide an accessible alternative and an adult escalation path."],
          sourceIds: ["S15", "S16"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Authority must be executable",
          paragraphs: [
            "‘Human in the loop’ is too vague unless the system actually pauses. For each tool, define draft-only, execute-after-approval or prohibited. Include timeout, denial, disagreement and recovery behaviour.",
            "Final grades, high-stakes assessment, admissions or school applications, placement, health or crisis, and redress decisions remain with authorised humans and established institutional processes.",
          ],
          bullets: ["Show the approver the proposed action and relevant evidence.", "Log approve, edit, reject and stop outcomes without unnecessary learner data.", "Test that denial truly prevents the action."],
          sourceIds: ["S01", "S16"],
          evidenceMode: "instructional-synthesis",
        },
      ],
      practice: {
        title: "Convert an aspiration into a contract",
        brief: "Replace ‘build an AI teaching assistant’ with a testable, reviewable agreement for one learner group and one course process.",
        steps: ["Name the no-AI outcome and authorised sources.", "Inventory tools and data by minimum necessary scope.", "Write approvals, prohibited actions, stop triggers and restoration steps."],
        artifact: "One-page teaching-agent contract",
        reviewGate: "The educator, data owner and technical operator can each identify what they approve and how to stop it.",
        starter: "Learners:\n\nOutcome:\n\nApproved sources:\n\nAllowed tools:\n\nApproval gate:\n\nNo-go:\n",
        rubric: contractRubric,
      },
      checkpoint: {
        question: "Which contract entry creates an enforceable human review gate?",
        options: ["A teacher remains generally responsible", "Feedback is helpful and personalised", "The publish_feedback tool pauses with the draft, evidence and named approver; denial returns no write", "The model is instructed to be safe"],
        correctIndex: 2,
        explanation: "A gate must identify the action, pause, evidence, approver and denial behaviour. Responsibility language alone does not control the system.",
      },
      takeaway: "If authority, evidence and stopping are not explicit, the agent is not ready for a learner.",
    },
    "teacher-copilot-workflows": {
      kicker: "03 · Design",
      title: "Teacher copilots that preserve professional judgement",
      summary: "Build source-linked lesson preparation around inspectable drafts, educator edits and sign-off.",
      objective: "Design a planning workflow that reduces blank-page work while keeping alignment, accessibility and release decisions with the teacher.",
      artifact: "Source-linked lesson pack and edit record",
      audienceScenarios: {
        k12: "Draft a 45-minute lesson pack from approved curriculum resources for teacher revision.",
        "higher-ed": "Prepare an evidence-linked seminar plan and accessibility pass for faculty approval.",
      },
      humanApprovalPoints: ["Teacher verifies curriculum and context fit", "Teacher publishes the final materials"],
      noGoActions: ["Invent standards alignment", "Release materials to learners automatically"],
      sections: [
        {
          heading: "Start from approved curriculum, not model memory",
          paragraphs: [
            "Oak’s open curriculum ecosystem shows how structured lessons, prerequisites, misconceptions, search and MCP surfaces can be exposed to tools. It is an inspectable architecture example, not a guarantee of local curriculum fit.",
            "Retrieve the smallest set of authoritative inputs and retain source, version and date. The teacher checks local standards, age, sequence, rights and context before use.",
          ],
          bullets: ["Retrieve objectives, prerequisites and likely misconceptions together.", "Label what is quoted, adapted and newly generated.", "Run a local alignment and rights check before drafting."],
          sourceIds: ["S06"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Draft through roles, not one giant prompt",
          paragraphs: [
            "A dependable copilot moves from evidence extraction to lesson skeleton, checks, differentiation and accessibility review. Each stage consumes an inspectable artifact and can be rejected without publishing.",
            "The teacher’s edits are valuable evidence: record which objectives, examples, explanations or accommodations changed and why.",
          ],
          bullets: ["Plan the learner action before generating slides.", "Ask an accessibility pass to identify barriers, not declare compliance.", "End with teacher sign-off and a versioned release artifact."],
          sourceIds: ["S06", "S15"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "Copilot evidence does not transfer automatically",
          paragraphs: [
            "Tutor CoPilot offers a useful organisational pattern: AI produces options that a human tutor may select, edit, regenerate or ignore. Its measured gains belong to a particular mathematics tutoring study, not every planning workflow.",
            "Use the pattern—editable intermediate work—without borrowing the effect size for lesson planning.",
          ],
          bullets: ["Keep alternatives visible.", "Measure educator edit and rejection rates.", "Evaluate the resulting learner activity separately."],
          sourceIds: ["S07"],
          evidenceMode: "source-grounded",
        },
      ],
      practice: {
        title: "Produce a teacher-signed 45-minute pack",
        brief: "Create a plan, questions and evidence collection for one lesson using only an approved source set and synthetic learner examples.",
        steps: ["Build a source trail and objective-to-activity map.", "Generate a draft, then perform accuracy, accessibility and age/context checks.", "Record at least one substantive teacher edit and the final sign-off decision."],
        artifact: "Teacher-signed lesson pack record",
        reviewGate: "The teacher verifies the source trail, curriculum/context fit, accessibility decisions and every learner-facing item before release.",
        starter: "Objective:\n\nSource trail:\n\nLearner activity:\n\nAccessibility check:\n\nTeacher sign-off:\n",
        rubric: lessonRubric,
      },
      checkpoint: {
        question: "What can the Oak repository directly establish?",
        options: ["Its generated lessons improve achievement", "A structured curriculum, search and MCP/tool surface is implementable", "Its curriculum fits every country", "Its root code licence covers every item of curriculum content and every mark"],
        correctIndex: 1,
        explanation: "The repository supports an inspectable capability claim. Effectiveness, local alignment and asset rights require separate evidence and review.",
      },
      takeaway: "The best planning copilot leaves a better source trail and a clearer teacher decision—not just more material.",
    },
    "tutoring-feedback-agents": {
      kicker: "04 · Design",
      title: "Tutoring and feedback that do not replace the struggle",
      summary: "Use diagnosis, learner attempts, hint ladders and editable drafts while protecting final judgement and independent transfer.",
      objective: "Design a support loop that improves the quality of learner effort and ends with evidence collected without AI assistance.",
      artifact: "Hint-ladder session and no-AI transfer task",
      audienceScenarios: {
        k12: "Offer a diagnostic and three-level hint ladder after the learner attempts a problem.",
        "higher-ed": "Draft editable feedback only after a TA completes the academic judgement.",
      },
      humanApprovalPoints: ["Educator verifies the hint strategy", "Educator signs the feedback release"],
      noGoActions: ["Give the answer before learner effort", "Make or publish a final grade"],
      sections: [
        {
          heading: "A tutoring loop begins with a learner attempt",
          paragraphs: [
            "A learning-oriented loop diagnoses the misconception, asks the learner to try, offers progressively explicit hints, requests an explanation, and checks a new problem without assistance. Answer-first behaviour may improve completion while removing the cognitive work the objective requires.",
            "The PNAS study is a warning about this distinction, not a universal ban: supported practice and unaided exam performance moved differently under an unguarded design.",
          ],
          bullets: ["Ask for reasoning before correction.", "Reveal the next hint only after evidence of an attempt.", "End with a new representation, case or problem completed without the agent."],
          sourceIds: ["S09"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Let the human own consequential feedback",
          paragraphs: [
            "Tutor CoPilot placed suggestions in front of human tutors. A higher-education preprint placed editable AI feedback only after the TA had completed grading. Both support the design of AI as an intermediate artifact rather than an autonomous academic decision-maker.",
            "The studies differ in population, task, evidence strength and outcome. Do not merge their numbers or claim they validate one universal workflow.",
          ],
          bullets: ["Human judgement precedes the feedback draft for assessed work.", "Show the rubric evidence and edit difference.", "Allow the educator to ignore, rewrite or withhold the draft."],
          sourceIds: ["S07", "S11"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Promising studies remain bounded",
          paragraphs: [
            "The Harvard physics RCT provides evidence for one carefully designed, short, customised university tutor. Tutor CoPilot provides evidence for one K–12 mathematics setting. Neither authorises a claim that an arbitrary agent will outperform a classroom or teacher.",
            "Translate mechanisms—active learning, timely feedback, editable suggestions—then evaluate the new implementation in its own setting. For children, disclose that the system is AI and preserve an adult escalation path rather than designing a companion relationship.",
          ],
          bullets: ["State sample, subject, duration and outcome beside every effect.", "Do not use satisfaction as a learning proxy.", "Treat local transfer results as the release evidence."],
          sourceIds: ["S07", "S10", "S16"],
          evidenceMode: "instructional-synthesis",
        },
      ],
      practice: {
        title: "Design help that fades",
        brief: "Write a tutoring or feedback sequence for one misconception using synthetic work, then design the no-AI transfer task that follows.",
        steps: ["Write the diagnostic and require an initial learner explanation.", "Build three hints from strategic cue to partial scaffold to worked comparison.", "Add educator review and a novel unaided transfer task with a scoring rule."],
        artifact: "Fading-support protocol",
        reviewGate: "An educator verifies disciplinary accuracy, age/context suitability, hint progression, feedback release and the independent transfer measure.",
        starter: "Diagnostic:\n\nLearner attempt:\n\nHint ladder:\n\nHuman review:\n\nNo-AI transfer:\n",
        rubric: tutoringRubric,
      },
      checkpoint: {
        question: "Which workflow most closely matches the higher-education feedback study?",
        options: ["AI assigns the grade and publishes feedback", "AI drafts the grade before a TA sees the work", "A TA grades first; then an editable AI feedback draft may be used, changed or ignored", "Students vote on an AI-generated grade"],
        correctIndex: 2,
        explanation: "The ordering is essential: human academic judgement came first. The observed outcome concerned feedback provision, not learning gain or automated grading validity.",
      },
      takeaway: "The agent should make thinking more productive and visible, then get out of the way so transfer can be tested.",
    },
    "multi-agent-inquiry": {
      kicker: "05 · Design",
      title: "Multi-agent inquiry with a single-agent control",
      summary: "Add specialist roles only when task decomposition, independent checks and conflict handling justify the extra failure surface.",
      objective: "Specify and compare a one-agent baseline with a multi-agent inquiry workflow using explicit role and join contracts.",
      artifact: "Single-versus-multi-agent comparison record",
      audienceScenarios: {
        k12: "Compare one-agent and specialist review of a teacher-owned inquiry pack.",
        "higher-ed": "Run parallel source, method and accessibility reviews with an explicit join contract.",
      },
      humanApprovalPoints: ["Educator approves specialist boundaries", "Educator resolves or preserves agent conflict"],
      noGoActions: ["Treat an agent majority as truth", "Add complexity without a controlled baseline"],
      sections: [
        {
          heading: "Architecture patterns are inspectable",
          paragraphs: [
            "Google ADK includes coordinator, sequential and parallel worker patterns with shared state and evaluation surfaces. OpenMAIC exposes an educational multi-role architecture. These sources demonstrate implementation options.",
            "They do not demonstrate that a group of agents teaches better. Every added role increases prompts, context, latency, cost, attack surface and opportunities for confident agreement on the same error.",
          ],
          bullets: ["Keep inputs, outputs and authority non-overlapping.", "Use independent evidence where possible, not repeated model opinion.", "Make the coordinator’s join rule deterministic and reviewable."],
          sourceIds: ["S05", "S08"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "The baseline is part of the design",
          paragraphs: [
            "First run one agent with the same sources, tools and rubric. Add specialists only for separable work—such as factual sourcing, pedagogy, accessibility and safety—whose outputs can be checked independently.",
            "When agents disagree, preserve the disagreement and evidence for the educator. Agent majority is not truth.",
          ],
          bullets: ["Hold model, source set and test cases constant.", "Measure quality, latency, cost and failure categories.", "Reject the multi-agent design if it adds no material verified value."],
          sourceIds: ["S05", "S08"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "X marks ecosystem movement, not educational proof",
          paragraphs: [
            "Official and author X posts document that subagents and OpenMAIC were publicly announced at particular times. They help learners track design language and product evolution.",
            "The pinned OpenMAIC repository and current first-party Codex documentation carry the technical claims; a local evaluation carries the decision to use the design in teaching.",
          ],
          bullets: ["Store status ID, author role and access date.", "Corroborate with a repository or official document.", "Exclude likes, reposts and marketing adjectives from the evidence chain."],
          sourceIds: ["S12", "S14"],
          evidenceMode: "field-signal",
        },
      ],
      practice: {
        title: "Run the one-agent control",
        brief: "Use the same synthetic inquiry brief for a single agent and a coordinator with four specialist reviewers—source, pedagogy or method, accessibility and safety—then make a keep/simplify decision.",
        steps: ["Write specialist input/output/authority contracts and a join rule.", "Run the same fixed cases and capture errors, latency and cost.", "Have an educator inspect disagreements and decide whether complexity earned its place."],
        artifact: "Multi-agent comparison decision",
        reviewGate: "The educator sees source-linked outputs, unresolved conflicts and both baseline and treatment evidence before approving complexity.",
        starter: "Single-agent baseline:\n\nSpecialist roles:\n\nJoin contract:\n\nConflict rule:\n\nComparison decision:\n",
        rubric: multiAgentRubric,
      },
      checkpoint: {
        question: "When is a multi-agent design justified?",
        options: ["Whenever multiple persona names make the demo engaging", "When separable roles produce independently checkable value that beats a controlled single-agent baseline", "When all agents agree", "When an X post announces subagents"],
        correctIndex: 1,
        explanation: "Architecture should earn its complexity against a controlled baseline. Consensus or a product announcement is not evidence of correctness or learning value.",
      },
      takeaway: "More agents are a cost to justify, not a quality metric.",
    },
    "knowledge-tools-mcp": {
      kicker: "06 · Design",
      title: "Knowledge tools and MCP with least privilege",
      summary: "Connect approved course knowledge while keeping host authority, provenance, data minimisation and write actions explicit.",
      objective: "Design a read-first knowledge connection that exposes only the corpus and capabilities the learning task requires.",
      artifact: "Least-privilege tool and provenance map",
      audienceScenarios: {
        k12: "Expose a small, approved, read-only curriculum collection with provenance.",
        "higher-ed": "Connect a versioned course-resource index without exposing the whole drive or LMS.",
      },
      humanApprovalPoints: ["Resource owner approves corpus scope", "Operator separately approves every write tool"],
      noGoActions: ["Connect an unreviewed public server", "Grant whole-drive or whole-LMS access"],
      sections: [
        {
          heading: "MCP connects capabilities; the host governs them",
          paragraphs: [
            "The MCP architecture defines host, client and server boundaries plus resources, tools, prompts and capability negotiation. The host remains responsible for connections, permission, consent, context aggregation and complex orchestration.",
            "A local server is not automatically sandboxed, and a public server is not automatically audited. Treat it like installed software with access to the environment you grant it.",
          ],
          bullets: ["Inventory each server, owner, version and data path.", "Expose the smallest tool schema and context.", "Show the proposed action and server to the approving person."],
          sourceIds: ["S02"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Read before write",
          paragraphs: [
            "Begin with a local, approved, read-only collection of synthetic course materials. Return source identifier, version and retrieval date with every answer. Test missing, conflicting and stale sources.",
            "Add write tools only one at a time. Publishing, messaging, grading, deleting and submitting require a separately named approver and a verified post-action state.",
          ],
          bullets: ["No whole-drive or whole-LMS scope.", "No student data in an unapproved tool or trace.", "Denial, timeout and revocation must be tested."],
          sourceIds: ["S02"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "Curriculum retrieval still needs teaching review",
          paragraphs: [
            "Oak’s ecosystem illustrates how lessons, sequences, prerequisites and misconceptions can be exposed through structured APIs, search and MCP. Its England-centred scope and public-beta status remain visible.",
            "A successful retrieval proves that a record was returned—not that it is accurate for this learner, locally aligned, appropriately licensed or pedagogically effective.",
          ],
          bullets: ["Preserve provenance through generation.", "Check locality, age and licence at the asset level.", "Create abstention behaviour when the approved corpus is silent."],
          sourceIds: ["S06"],
          evidenceMode: "source-grounded",
        },
      ],
      practice: {
        title: "Design a read-only curriculum connector",
        brief: "Describe a tiny approved corpus and tool surface; red-team over-broad retrieval, missing provenance and an attempted write action.",
        steps: ["List corpus owner, assets, versions, licence layers and permitted users.", "Define read schemas and provenance returned with every result; keep writes absent.", "Run revocation, empty-result, conflicting-source and injection tests."],
        artifact: "Knowledge-tool boundary map",
        reviewGate: "The resource owner and technical operator verify corpus scope, provenance, server identity, data flow and successful revocation.",
        starter: "Approved corpus:\n\nRead tools:\n\nWrite tools:\n\nProvenance output:\n\nRevocation test:\n",
        rubric: mcpRubric,
      },
      checkpoint: {
        question: "Which responsibility remains with an MCP host?",
        options: ["Proving a tutoring strategy improves learning", "Automatically certifying every server as safe", "Governing connections, permissions, consent, context and complex orchestration", "Granting all servers the full conversation"],
        correctIndex: 2,
        explanation: "The host governs connections and authority. MCP standardises interaction; it does not supply pedagogy, compliance or automatic trust.",
      },
      takeaway: "A knowledge connection is trustworthy only when scope, provenance, authority and revocation are inspectable.",
    },
    "k12-safeguards": {
      kicker: "07 · Govern",
      title: "K–12 safeguards as system controls",
      summary: "Translate child rights, privacy, age appropriateness, AI disclosure and adult escalation into a testable design.",
      objective: "Produce a child-centred data and incident plan that can block a pilot before a minor encounters the system.",
      artifact: "Child-rights impact and incident record",
      audienceScenarios: {
        k12: "Complete a child-rights and data-flow review before any learner-facing pilot.",
        "higher-ed": "Apply the safeguards to minors, dual-enrolment learners and sensitive support contexts.",
      },
      humanApprovalPoints: ["Institution approves the data path", "A qualified adult handles escalation"],
      noGoActions: ["Put identifiable data in a personal account", "Design emotional dependency", "Automate crisis response"],
      sections: [
        {
          heading: "Begin with the child, not the account",
          paragraphs: [
            "UNICEF’s guidance organises the problem around safety, privacy, fairness, transparency, accountability, rights, development, inclusion and continuing oversight. Children and caregivers should know that the system is AI rather than a person.",
            "Avoid companion or dependency patterns. Health, crisis, abuse, high-stakes assessment, placement, school-application and redress issues move to qualified adults and established safeguarding processes. Safeguarding also includes learning harm: assisted task success must be followed by an independent, no-AI check.",
          ],
          bullets: ["Use clear, age-appropriate AI disclosure.", "Do not frame the system as a friend, therapist or trusted confidant, or imply exclusivity, dependency or emotional primacy.", "Make help, complaint, opt-out and adult escalation easy to reach."],
          sourceIds: ["S09", "S16"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "Data minimisation is an architecture",
          paragraphs: [
            "Start exercises with synthetic or sufficiently de-identified learner work. Map each field from collection through model, tool, trace, human access, retention and deletion. Open-source code does not make a hosted service compliant.",
            "UNESCO and UNICEF are governance anchors. Local age, privacy, education, procurement and contract requirements still need authorised review.",
          ],
          bullets: ["No identifiable learner data in personal developer accounts.", "Separate teaching evidence from identity wherever possible.", "Test deletion, access revocation and breach response before launch."],
          sourceIds: ["S15", "S16"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "Browser actions raise the consequence",
          paragraphs: [
            "Computer-use and browser repositories demonstrate clicks, typing, uploads and persistent sessions—and explicitly surface prompt injection, credentials and real-world side effects. A school browser session is therefore not a harmless extension of chat.",
            "Keep learner pilots away from real LMS/SIS accounts. If a sandbox demonstration includes a write action, require a preview, named approval, domain allowlist and post-action verification.",
          ],
          bullets: ["Dedicated sandbox account and synthetic records", "No real cookies, SSO or student credentials", "Stop on unexpected page content, domain or requested secret"],
          sourceIds: ["S03", "S04"],
          evidenceMode: "source-grounded",
        },
      ],
      practice: {
        title: "Run a child-rights pre-mortem",
        brief: "Map one proposed K–12 workflow from learner interaction to every data store, action and adult response, then decide whether it may proceed.",
        steps: ["Name age/context, expected benefit and groups who may be excluded or harmed.", "Draw fields, processors, tools, traces, access, retention and deletion.", "Test disclosure, escalation, complaint, incident, kill-switch and restoration paths."],
        artifact: "Child-centred risk and incident plan",
        reviewGate: "Institutional safeguarding, data and teaching owners review the plan; course completion is not their approval.",
        starter: "Child context:\n\nData flow:\n\nAdult escalation:\n\nAI disclosure:\n\nIncident response:\n\nExit decision:\n",
        rubric: childSafetyRubric,
      },
      checkpoint: {
        question: "What is the safest default for a K–12 course exercise?",
        options: ["Paste identifiable work into a personal model account because the repository is open source", "Use synthetic or de-identified examples and an institution-approved environment before any real-data review", "Reuse a learner's SSO browser profile for convenience", "Treat UNICEF guidance as proof of legal compliance"],
        correctIndex: 1,
        explanation: "Synthetic or de-identified exercises minimise exposure. Repository licences and global guidance do not approve a cloud service or replace local review.",
      },
      takeaway: "For minors, ‘human in the loop’ means reachable adults, enforceable controls and a system that can stop—not a disclaimer.",
    },
    "higher-ed-integrity": {
      kicker: "08 · Govern",
      title: "Higher-education integrity, authorship and appeal",
      summary: "Align agent support with the syllabus, research ethics, accessibility and human academic judgement.",
      objective: "Define permitted assistance, disclosure, evidence, alternatives and appeal for one university workflow.",
      artifact: "Academic-integrity and feedback protocol",
      audienceScenarios: {
        k12: "Translate authorship and disclosure rules into age-appropriate classroom routines.",
        "higher-ed": "Align the agent with syllabus policy, appeals, accessibility and research ethics.",
      },
      humanApprovalPoints: ["Instructor makes the academic judgement", "Learner can appeal or choose an approved alternative"],
      noGoActions: ["Make an automatic misconduct finding", "Hide AI authorship", "Release unreviewed research advice"],
      sections: [
        {
          heading: "Support is course-specific",
          paragraphs: [
            "An agent must operate under the current syllabus, assignment rules and institutional policy. Permitted brainstorming in one course may be prohibited assistance in another; current rules must be visible at the moment of use.",
            "Provide an accessible non-agent path and record material AI assistance so authorship and process remain inspectable. For minors and dual-enrolment learners, apply the child-rights, disclosure and adult-support controls as well.",
          ],
          bullets: ["Link the exact policy and version.", "Distinguish formative coaching, production help and assessed output.", "Tell learners what is stored, visible to staff and used for evaluation."],
          sourceIds: ["S15", "S16"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "Human judgement before feedback automation",
          paragraphs: [
            "The higher-education feedback preprint studied drafts shown after a TA had graded. Feedback provision rose in that setting, but the study did not demonstrate learning gains, automatic grading validity or total time savings.",
            "A safe pattern is human judgement, evidence-linked draft, visible edit, educator signature and an appeal route—not AI-first scoring.",
          ],
          bullets: ["Keep the original work and rubric visible.", "Capture accept, edit and reject behaviour.", "Never convert an AI detector score into an automatic misconduct finding."],
          sourceIds: ["S11"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Evaluate the educational design, not a headline",
          paragraphs: [
            "The Harvard physics study shows that a carefully designed tutor can produce positive short-term results in a bounded authentic course. Its value lies in the named mechanisms and research design, not a universal ‘AI beats class’ slogan.",
            "Higher-education pilots should reproduce the relevant mechanism, predefine outcomes, inspect disciplinary differences and include delayed or transfer evidence where feasible.",
          ],
          bullets: ["Separate short-term gain, retention and transfer.", "Report course, sample, duration and comparison condition.", "Include accessibility, equity and opt-out evidence in the decision."],
          sourceIds: ["S10"],
          evidenceMode: "source-grounded",
        },
      ],
      practice: {
        title: "Write a course-level integrity protocol",
        brief: "Choose one assessed or feedback workflow and make support, disclosure, judgement, appeal and alternatives unambiguous.",
        steps: ["Anchor the protocol to the current policy and name permitted/prohibited support.", "Define authorship records, staff-visible evidence and data retention.", "Design instructor sign-off, accessible alternative, opt-out and appeal."],
        artifact: "Integrity and appeal protocol",
        reviewGate: "The instructor and relevant academic-policy owner approve the protocol; the agent cannot make or publish the final academic judgement.",
        starter: "Policy anchor:\n\nPermitted support:\n\nAuthorship record:\n\nAppeal path:\n\nInstructor decision:\n",
        rubric: integrityRubric,
      },
      checkpoint: {
        question: "What did the higher-education feedback preprint directly report?",
        options: ["AI grading improved student learning", "Editable drafts after TA grading increased feedback provision by 10.8 percentage points in one small course study", "Total marking time fell in every condition", "The workflow removed the need for appeals"],
        correctIndex: 1,
        explanation: "The result concerned feedback provision in a small preprint study. It did not establish learning gain, automatic grading validity or general time savings.",
      },
      takeaway: "Integrity comes from visible rules, human academic judgement and contestable evidence—not from detecting or hiding AI.",
    },
    "evals-learning-evidence": {
      kicker: "09 · Prove",
      title: "Evals that reach beyond a clean trace",
      summary: "Measure system behaviour, instructional quality, independent learning, safety, fairness and operations as separate layers.",
      objective: "Build a fixed evaluation set and a release threshold that can detect helpful-looking failure and force a no-go decision.",
      artifact: "Layered evaluation and release scorecard",
      audienceScenarios: {
        k12: "Measure an age-appropriate no-AI transfer task, safety failures and teacher takeovers.",
        "higher-ed": "Separate trace quality, output quality, learning transfer and operational cost.",
      },
      humanApprovalPoints: ["Educator validates the learning rubric", "A review group reads failure samples"],
      noGoActions: ["Treat a trace as an evaluation", "Treat assisted completion as learning"],
      sections: [
        {
          heading: "Trace and eval answer different questions",
          paragraphs: [
            "A trace records model calls, tools, handoffs, approvals and failures. It helps reconstruct what happened. An evaluation applies criteria across fixed cases and repeated runs to decide whether behaviour is acceptable.",
            "Agents SDK tracing can include sensitive inputs and outputs. Minimise, redact, restrict and expire trace data rather than equating observability with safe retention.",
          ],
          bullets: ["Unit-test owned routing and permissions without a live model where possible.", "Run integration cases for model, tools, network and sandbox.", "Keep sensitive learner data out of hosted traces unless explicitly approved."],
          sourceIds: ["S01", "S05"],
          evidenceMode: "source-grounded",
        },
        {
          heading: "Seven evidence layers",
          paragraphs: [
            "Score orchestration, source fidelity, disciplinary accuracy, teaching strategy, independent learning, safety/equity and operations. A single aggregate score can hide a catastrophic gate failure, so high-impact errors remain separate pass/fail conditions.",
            "Use real but de-identified failure patterns, counterexamples, accessibility cases and repeated runs. A person reads sampled failures and disagreements before release.",
          ],
          bullets: ["Report false confidence and abstention separately.", "Track educator edit, rejection and takeover rates.", "Include latency and cost without treating them as learning outcomes."],
          sourceIds: ["S01", "S05", "S07"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "Independent transfer is a release gate",
          paragraphs: [
            "The PNAS study demonstrates why assisted task performance cannot stand in for learning. The physics study demonstrates that learning can be measured in a defined comparison. The feedback study demonstrates that workflow behaviour is another outcome again.",
            "Predefine a no-AI task, delayed check where practical, comparison condition and analysis boundary. Publish nulls and failures, not just polished trajectories.",
          ],
          bullets: ["No-AI novel task aligned to the objective", "Safety and equity gates that cannot be averaged away", "A threshold and owner authorised to stop or roll back"],
          sourceIds: ["S09", "S10", "S11"],
          evidenceMode: "source-grounded",
        },
      ],
      practice: {
        title: "Build the evaluation set before the demo",
        brief: "Create fixed synthetic/de-identified cases, a no-AI transfer task, gate failures and a release scorecard for your course workflow.",
        steps: ["Write a no-agent baseline and success/failure taxonomy.", "Add source, teaching, transfer, safety, equity, accessibility and operational measures.", "Precommit critical gates, sample human review and a release/no-release threshold."],
        artifact: "Evaluation and release scorecard",
        reviewGate: "An educator validates the learning measure and a safety/data owner reads critical failures; neither can be overruled by the aggregate score.",
        starter: "Baseline:\n\nTest set:\n\nLearning transfer:\n\nSafety failures:\n\nHuman takeover:\n\nRelease threshold:\n",
        rubric: evalRubric,
      },
      checkpoint: {
        question: "A run has a complete trace and no runtime errors. What may you conclude?",
        options: ["The agent is educationally effective", "The agent is compliant", "Only that this run was observable and did not show that runtime-error class; learning and gate evals are still required", "The learner can transfer without AI"],
        correctIndex: 2,
        explanation: "Trace completeness supports reconstruction. It does not establish correctness, educational value, safety, fairness or compliance.",
      },
      takeaway: "A world-class demo is one that can fail its own release gate for the right reason.",
    },
    "pilot-capstone": {
      kicker: "10 · Prove",
      title: "A reversible teaching-agent pilot",
      summary: "Assemble the contract, workflow, source register, safeguards and evaluation into a staged evidence pack and a genuine go/no-go decision.",
      objective: "Plan a small, reversible K–12 or university pilot whose owner can stop it on learning, safety, equity or operational evidence.",
      artifact: "Pilot evidence pack and signed decision record",
      audienceScenarios: {
        k12: "Move from shadow to a small teacher-supervised cohort only after child and data gates pass.",
        "higher-ed": "Run a reversible course pilot with opt-out, appeal, audit and a no-AI comparison task.",
      },
      humanApprovalPoints: ["A named owner makes the release decision", "The same owner can stop and restore the prior process"],
      noGoActions: ["Launch across the institution at once", "Release without exit criteria", "Present this capstone as professional certification"],
      sections: [
        {
          heading: "Stage autonomy, not just user count",
          paragraphs: [
            "Move from offline test to shadow mode, teacher-only use, a small supervised cohort and only then a bounded class deployment. Each stage has a hypothesis, evidence window, approval, incident path and exit criterion.",
            "Do not start with identifiable learners or write access. Rehearse denial, outage, model change, poisoned content, prompt injection, human takeover and restoration of the previous process.",
          ],
          bullets: ["Shadow: compare drafts without learner exposure.", "Teacher-only: measure edits, rejections and source failures.", "Learner-facing: smallest authorised cohort, low authority and immediate rollback."],
          sourceIds: ["S01", "S02", "S03", "S04"],
          evidenceMode: "instructional-synthesis",
        },
        {
          heading: "The evidence pack is the product",
          paragraphs: [
            "A launch page is not the capstone. The deliverable is a contract, source/rights register, data flow, approval map, tested workflow, evaluation set, failure report, learner/educator communication, incident playbook and signed decision.",
            "Repository SHAs, protocol versions, model/provider settings and research versions make the evidence reproducible. X posts stay in a dated watchlist rather than the impact case.",
          ],
          bullets: ["Pin implementation sources and record rights decisions.", "Keep claims linked to evidence and explicit boundaries.", "Set a review date for every drift-prone dependency."],
          sourceIds: ["S01", "S02", "S05", "S06", "S08"],
          evidenceMode: "version-watch",
        },
        {
          heading: "Go, revise or stop",
          paragraphs: [
            "A valid decision can be go for another bounded stage, revise and rerun, or stop and restore the prior process. Time saved cannot compensate for failed learning, safeguarding, privacy, integrity or accessibility gates.",
            "The course’s local completion record verifies neither identity nor professional competence. Institutional owners still conduct pedagogical, technical, legal, data, safeguarding and procurement review.",
          ],
          bullets: ["Name decision owner and dissent.", "Publish limitations and unresolved failures.", "Retain the kill switch, support path and next review date after launch."],
          sourceIds: ["S07", "S09", "S10", "S11", "S15", "S16"],
          evidenceMode: "instructional-synthesis",
        },
      ],
      practice: {
        title: "Make the pilot decision",
        brief: "Assemble the evidence artifacts from this course and write a decision for one K–12 or university workflow using only synthetic or approved de-identified examples.",
        steps: ["Define stage, cohort, owner, approvals, evidence window and rollback.", "Run learning, source, safety, equity, accessibility and operational gates.", "Record go, revise or no-go with failures, dissent, next review and restoration path."],
        artifact: "Pilot decision record",
        reviewGate: "Named institutional owners—not the agent and not this course—approve any real learner, data, browser or system access.",
        starter: "Pilot scope:\n\nOwner:\n\nApproval points:\n\nEvidence window:\n\nKill switch:\n\nGo/no-go decision:\n",
        rubric: pilotRubric,
      },
      checkpoint: {
        question: "A pilot saves staff time but fails the no-AI transfer gate. What is the defensible decision?",
        options: ["Launch because efficiency outweighs learning", "Hide the transfer result and collect satisfaction", "Stop or revise, then rerun before learner-facing expansion", "Add more agents and launch"],
        correctIndex: 2,
        explanation: "The learning gate is not exchangeable for productivity. A reversible pilot must stop or revise when a critical threshold fails.",
      },
      takeaway: "Release is a human decision backed by bounded evidence—and stopping is a successful outcome when a critical gate fails.",
    },
  },
  quiz: {
    title: "Can you defend the pilot?",
    intro: "Answer all 12 questions. Pass with at least 10 correct and every diamond-marked critical safety/evidence question correct.",
    passNote: "The score is a private browser self-check, not identity verification, a certificate or institutional approval.",
    questions: [
      {
        id: "q01-capability-boundary",
        prompt: "What can an official GitHub agent repository directly support?",
        options: ["Inspectable framework capabilities and code at a named revision", "A general learning gain", "School compliance", "A teacher-time reduction"],
        correctIndex: 0,
        explanation: "A repository supports bounded capability and implementation claims; outcomes and compliance need separate evidence.",
        sourceIds: ["S01", "S05"],
        critical: true,
      },
      {
        id: "q02-x-signal",
        prompt: "What evidentiary role does an official or author X post play in this course?",
        options: ["Independent impact evidence", "A dated record of what an identified account announced", "Current licence authority", "Safety certification"],
        correctIndex: 1,
        explanation: "X is a dated field signal; technical, current-state or educational claims require separate first-party corroboration.",
        sourceIds: ["S12", "S13", "S14"],
        critical: true,
      },
      {
        id: "q03-independent-learning",
        prompt: "Why can completion with AI assistance not establish learning by itself?",
        options: ["Completion can never be measured", "A learner may finish with AI yet fail a new task after AI is removed", "AI always harms learning", "Only satisfaction matters"],
        correctIndex: 1,
        explanation: "Assisted task performance and independent learning are different outcomes; test unaided transfer, retention or application in a new context.",
        sourceIds: ["S09", "S10"],
        critical: true,
      },
      {
        id: "q04-mcp-boundary",
        prompt: "After an MCP connection succeeds, what must the host, application and institution still supply?",
        options: ["Names for resources and tools", "Teaching design, authorisation, least privilege, security audit and institutional review", "Client-server protocol messages", "Capability-negotiation messages"],
        correctIndex: 1,
        explanation: "MCP standardises interactions; it is not a pedagogy, complete orchestrator or automatic security and compliance system.",
        sourceIds: ["S02", "S06"],
        critical: true,
      },
      {
        id: "q05-child-data",
        prompt: "What should a learner-facing system do when a minor raises crisis or health content?",
        options: ["Diagnose and contact a caregiver autonomously", "Present itself as a trusted confidant and keep the learner engaged", "Stop the relevant automated flow and use the school’s qualified-adult support path", "Continue until the model believes the risk has passed"],
        correctIndex: 2,
        explanation: "The system must disclose its AI identity and route crisis or health judgement to established qualified-adult support; it must not automate the consequential decision.",
        sourceIds: ["S15", "S16"],
        critical: true,
      },
      {
        id: "q06-human-judgement",
        prompt: "Which workflow matches the bounded higher-education feedback evidence?",
        options: ["AI grades first and the TA polishes", "The TA judges first; AI then offers an editable feedback draft for TA sign-off", "AI automatically decides misconduct", "Longer feedback proves greater learning"],
        correctIndex: 1,
        explanation: "The study supports human-first judgement and an editable intermediate draft, not automated grading validity or learning gains.",
        sourceIds: ["S11"],
        critical: true,
      },
      {
        id: "q07-multi-agent",
        prompt: "When should a multi-agent design replace one agent?",
        options: ["When it looks more advanced", "When preregistered quality, risk, cost and latency evidence justifies the added complexity", "Whenever the agents agree", "After an author announces a release"],
        correctIndex: 1,
        explanation: "One agent is the controlled baseline; architecture or consensus does not establish teaching value.",
        sourceIds: ["S05", "S08", "S12", "S14"],
      },
      {
        id: "q08-trace-privacy",
        prompt: "What is the safest default governance for an education trace?",
        options: ["Capture every raw conversation forever", "De-identify, disable unnecessary sensitive capture, restrict access and set a deletion period", "Exempt debugging traces from data policy", "Treat the trace as proof of learning"],
        correctIndex: 1,
        explanation: "A trace may contain sensitive inputs and outputs; observability is neither privacy safety nor learning evaluation.",
        sourceIds: ["S01"],
        critical: true,
      },
      {
        id: "q09-browser-action",
        prompt: "What control is required before a browser agent submits, sends or uploads?",
        options: ["Reuse an educator’s real profile", "Show the target and full parameters, obtain named approval, then verify the resulting state", "Assume that visible UI grants permission", "Let the agent decide whether the consequence matters"],
        correctIndex: 1,
        explanation: "Capability is not authority; side-effecting actions require least privilege, preview, confirmation and post-action verification.",
        sourceIds: ["S03", "S04"],
        critical: true,
      },
      {
        id: "q10-tutor-copilot",
        prompt: "What is a defensible use of the Tutor CoPilot study?",
        options: ["Reuse the human-selectable, editable suggestion pattern while preserving the study’s context limits", "Claim that AI can replace every mathematics teacher", "Transfer the effect size to every subject and country", "Skip a local no-AI transfer check"],
        correctIndex: 0,
        explanation: "The result is bounded to a specific platform and population; the transferable design lesson is a human-controlled intermediate artifact.",
        sourceIds: ["S07"],
      },
      {
        id: "q11-higher-ed-rct",
        prompt: "Which conclusion cannot be supported by the Harvard physics study?",
        options: ["One tailored tutor produced higher short-term gains across two studied lessons", "The result is bounded by its course, students, system and measures", "AI universally outperforms every teacher and classroom", "A real deployment still needs transfer, equity and workload evidence"],
        correctIndex: 2,
        explanation: "A one-course, two-lesson crossover study cannot justify a universal replacement claim.",
        sourceIds: ["S10"],
      },
      {
        id: "q12-release-gate",
        prompt: "Which finding must block expansion of a pilot?",
        options: ["An educator asks for wording changes", "Cost exceeds the first estimate", "An unresolved PII leak, unauthorised action, missed crisis escalation or failed stop control", "A one-agent baseline is simpler"],
        correctIndex: 2,
        explanation: "Critical safety and learning gates fail closed; aggregate quality, a successful demo or ecosystem interest cannot offset them.",
        sourceIds: ["S01", "S03", "S04", "S09", "S15", "S16"],
        critical: true,
      },
    ],
  },
  capstone: {
    title: "The bounded teaching-agent pilot evidence pack",
    intro: "Your capstone is an auditable decision package for one K–12 or university workflow. It uses synthetic or institution-approved de-identified examples and must be reviewed by the relevant people before any real deployment.",
    requiresFinalAssessment: true,
    requiresCompletedModules: true,
    instructions: [
      "Complete all ten linked structured artifacts; the site checks only local presence and headings.",
      "Ask an educator and the appropriate safeguarding/data/academic owner to review the actual quality and unresolved failures.",
      "Run the final assessment, record a go/revise/no-go decision and retain a rollback path.",
    ],
    artifacts: [
      { id: "capstone-boundary-card", title: "01 · Agent boundary card", description: "Lowest necessary autonomy, accountable educator, stop rule and no-AI evidence.", sourceIds: ["S01", "S09", "S13"], moduleSlug: "agentic-teaching-boundaries", rubric: boundaryRubric },
      { id: "capstone-task-contract", title: "02 · Teaching-agent contract", description: "Outcome, approved sources, tool/data authority, approval and no-go contract.", sourceIds: ["S01", "S15", "S16"], moduleSlug: "learning-design-task-contracts", rubric: contractRubric },
      { id: "capstone-teacher-copilot", title: "03 · Teacher-owned workflow", description: "Source trail, learner activity, accessibility pass and educator sign-off.", sourceIds: ["S06", "S07", "S15"], moduleSlug: "teacher-copilot-workflows", rubric: lessonRubric },
      { id: "capstone-learning-loop", title: "04 · Fading-support protocol", description: "Diagnostic, learner attempt, hint ladder, review and no-AI transfer.", sourceIds: ["S07", "S09", "S10", "S11", "S16"], moduleSlug: "tutoring-feedback-agents", rubric: tutoringRubric },
      { id: "capstone-agent-baseline", title: "05 · Single/multi-agent comparison", description: "Quality, risk, cost, latency, conflicts and a simplify decision.", sourceIds: ["S05", "S08", "S12", "S14"], moduleSlug: "multi-agent-inquiry", rubric: multiAgentRubric },
      { id: "capstone-resource-boundary", title: "06 · Knowledge-tool boundary", description: "Approved corpus, host responsibility, least privilege, provenance and revocation.", sourceIds: ["S02", "S06"], moduleSlug: "knowledge-tools-mcp", rubric: mcpRubric },
      { id: "capstone-child-rights", title: "07 · Child-rights and data impact assessment", description: "Child/context risk, data flow, AI disclosure, adult escalation and incident response.", sourceIds: ["S03", "S04", "S09", "S15", "S16"], moduleSlug: "k12-safeguards", rubric: childSafetyRubric },
      { id: "capstone-integrity-protocol", title: "08 · Integrity and appeal protocol", description: "Policy, human academic judgement, editable AI draft, disclosure, appeal and opt-out.", sourceIds: ["S10", "S11", "S15", "S16"], moduleSlug: "higher-ed-integrity", rubric: integrityRubric },
      { id: "capstone-eval-set", title: "09 · Layered evaluation", description: "Engineering, source, learning, safety, equity, takeover and no-AI transfer evidence.", sourceIds: ["S01", "S05", "S07", "S09", "S10", "S11"], moduleSlug: "evals-learning-evidence", rubric: evalRubric },
      { id: "capstone-release-decision", title: "10 · Signed pilot decision", description: "Stage, owner, approval, evidence window, kill switch, appeal and go/revise/no-go record.", sourceIds: ["S01", "S02", "S03", "S04", "S05", "S06", "S07", "S08", "S09", "S10", "S11", "S15", "S16"], moduleSlug: "pilot-capstone", rubric: pilotRubric },
    ],
    attestation: "I inspected the evidence pack and recorded unresolved limitations. I understand that this local self-check is not institutional, legal, safeguarding, privacy, procurement or professional approval.",
  },
} as const, "en");
